### ISSUE TITLE
Yapf failures

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1000]
#989 and #996 report strange yapf failures. In #989, I verified I was at the latest yapf 0.20.0, but still not able to match the Travis yapf output despite local `yapf` successes.

It might be good for us to dig more deeply to figure out what's happening.

**Comment by lilleswing** [comment]
yapf on travis is still 0.19.0

https://github.com/deepchem/deepchem/blob/master/.travis.yml

**Comment by lilleswing** [comment]
p.s. issue #1000 :tada:
