### ISSUE TITLE
Tutorial combining raw Tensorflow with TensorGraph layers

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1015]
Help ML practitioners experiment with DeepChem

**Comment by vsag** [comment]
I am good with pytorch but never used deepchem/tensorflow, I am willing to take a dig or write your tensorflow models to pytorch(if you want that). What do you need with this particular task, I am willing to help as it will enable me also to learn tf. Thanks.

**Comment by rbharath** [comment]
@vsag We're currently not planning to extend DeepChem support for pytorch, but would welcome any TensorFlow tutorials. Feel free to take a crack at it and open a PR! We can help review and provide feedback.

**Comment by souravsingh** [comment]
I am interested in working on this.

**Comment by rbharath** [comment]
@souravsingh Great! Could you start a pull request marked "[WIP]" that tracks your on-going implementation efforts? We can help debug issues there.

**Comment by souravsingh** [comment]
Sure

**Comment by rbharath** [comment]
I'm going to close this old issue since we're now removing `TensorGraph`
