### ISSUE TITLE
Documentation Quick Start Sections

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1016]
We should have Quick Start Section.  There really need to be two -- one for ML practitioners and one for applications practitioners.

**Comment by lilleswing** [comment]
Split the tutorials based on desired audience.

**Comment by rbharath** [comment]
I like this idea. There are enough tutorials now that it won't be clear to beginners where to start. More organization on the tutorial page would help.

**Comment by lilleswing** [comment]
I started by splitting the tutorials section
https://deepchem.io/docs/notebooks/index.html

I also feel like we will have more control if we split the website into its own repo inside the deepchem org as described here.

https://github.com/deepchem/deepchem/issues/1055
