### ISSUE TITLE
Google Summer of Code Application

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1017]
Let us put in an application.
https://summerofcode.withgoogle.com/

**Comment by lilleswing** [comment]
Deadline January 23

**Comment by peastman** [comment]
What projects would you suggest?

**Comment by lilleswing** [comment]
Ideas -- 

1) ChemNet
2) DruGan
3) Seq2Seq for retrosynthetic analysis
4) Hyper Parameter Optimization Framework for TensorGraph over a computer Cluster

I'm also hope this issue serves as a platform for other ideas.

**Comment by rbharath** [comment]
Here are some other thoughts:

5. Integration of data from TCGA (the cancer genomics atlas) to DeepChem (dataset processing and models)
6. Implementation of microscopy conv-nets (https://github.com/deepchem/deepchem/issues/540)

**Comment by Dgelemi** [comment]
I like the idea of ChemNet, but also if it could be extended, what happen if one tries to use 3D conformation as input for example? 
Google summercode could be the occasion to bring something new to ideas out there.

**Comment by Dgelemi** [comment]
Another one is around the parameter search. We saw quite a lot of issues raised around that - not getting same results as the paper, need to rerun search...
Having an AutoML framework around deepchem could help for hyperparamter search and make it more efficient than grid search. Something like TPOT (https://rhiever.github.io/tpot/ but would need to be ok with DL)  or others.

**Comment by lilleswing** [comment]
@Dgelemi never seen tpot before but it looks very cool!  I was thinking more along the lines of [population based training](https://arxiv.org/abs/1711.09846).  
Also by ChemNet I meant implementing the transfer learning protocol, and doing domain knowledge and empirical analysis to get a good basis set of transferable tasks.

**Comment by rbharath** [comment]
There was a suggestion on Twitter that we also consider applying to https://www.outreachy.org/ (internships for underrepresented communities). The next round of applications is in Februrary, so we could probably repurpose our GSOC application for them as well.

**Comment by patrickhop** [comment]
My vote is for retrosynthesis. The big CROs employ thousands of synthetic chemists, so any progress there will not be unnoticed.

Hyperparameter tuning is interesting, but I haven't personally seen big performance gains there - even with bayesian methods.

**Comment by peastman** [comment]
That may be too much of an open ended research project.  SOC projects probably work better if they're well defined, like implementing a particular algorithm.

**Comment by rbharath** [comment]
We're joining forces with OpenChemistry for the GSoC application. Feel free to start contributing DeepChem project ideas to the wiki http://wiki.openchemistry.org/GSoC_Ideas_2018 here.

Also, if you're interested in being a mentor for the summer please drop me a note at my-github-username at stanford dot edu.

**Comment by lilleswing** [comment]
JS export for in browser inference
https://deeplearnjs.org/demos/mnist/mnist.html

**Comment by rbharath** [comment]
Another good project might be converting all our non-custom layers over to use `tf.keras`. This is a software engineering project which we should be able to break down into a number of self-contained PRs.

**Comment by lilleswing** [comment]
dc.data.Dataset -> tf.data transition plan I think would be a stronger project.

**Comment by lilleswing** [comment]
http://wiki.openchemistry.org/GSoC_Ideas_2018#DeepChem_Project_Ideas
The top 4 projects have been chosen.  
* Transfer Learning a la ChemNet
* tf.data integration
* tf.keras integration and raw tensorflow tutorials
* Image Analysis Tools

We chose these projects for a number of reasons.
* a good mix of engineering and research
* doable with resources a summer intern would have available
* accomplishable by a student in a 4 month timeframe.

**Comment by peastman** [comment]
Better integration with tf.keras is one of the next items on my todo list.  I plan to have that largely done long before summer.

**Comment by lilleswing** [comment]
As we have been accepted and have a wiki post about it I am closing this issue.  I'm going through our issue backlog now and marking good candidates for first time contributions for the applicants.
