### ISSUE TITLE
Installation issues?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1019]
Copying over an error report on installation received over email:

I tried using Anaconda to install and followed the documentation: 

```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.3.0
```

and got this error message: 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - deepchem=1.3.0

https://github.com/deepchem/deepchem
```

The other installation steps were a pain in the neck - need to make this simpler.

**Comment by lilleswing** [comment]
There are no osx builds right now on anaconda cloud.  Is that the issue?

**Comment by lilleswing** [comment]
https://anaconda.org/deepchem/deepchem/files

**Comment by rbharath** [comment]
I suspect that's probably the issue. Will follow up with the reporter and point them to this issue.

Could we get OSX anaconda builds going?

**Comment by lilleswing** [comment]
Yeah you just need to do run [cond_build.sh](https://github.com/deepchem/deepchem/blob/master/devtools/jenkins/conda_build.sh) file from an osx machine with upload rights to our anaconda cloud.

**Comment by lilleswing** [comment]
p.s. please use DC 1.3.1 also which solves backward compatable datasets or else they will have migration steps when going to DC 2.0.0

**Comment by brookewenig** [comment]
I'm getting issues when trying to install via Anaconda on OSX. I followed the docs at https://anaconda.org/omnia/deepchem

> conda install -c omnia deepchem 

as well as trying the aforementioned 

> conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.3.0

But none of it worked.

**Comment by lilleswing** [comment]
This is my fault not building the OSX Conda builds or updating the website
telling users to build from source on OSX.  I’ll build conda installers on
OSX tomorrow morning EST.

(The build from source method does work though)
‘’’bash
git clone https://github.com/deepchem/deepchem
git fetch
git checkout 1.3.1
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
python setup.py install
‘’’

**Comment by lilleswing** [comment]
Python 2.7 and 3.5 builds are up and smoke-tested.
```bash
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.3.1
```

**Comment by rbharath** [comment]
@lilleswing Awesome, thanks for getting this going!

**Comment by pkvreddy** [comment]
Installation failing. Any tips?
![image](https://user-images.githubusercontent.com/16655273/35772618-86d71c14-08f7-11e8-8998-62468c877b67.png)
