### ISSUE TITLE
Another graph input approach

### ISSUE THREAD

**Issue by Dgelemi** [deepchem/deepchem#1025]
Not an issue, but a paper on using graph as molecule descriptor and some model comparison:
Adaptive Graph Convolutional Neural Networks, https://arxiv.org/pdf/1801.03226.pdf , code is not public

**Comment by lilleswing** [comment]
1. The comparison is not to moleculenet GraphConv despite citing our paper.  Instead it is to 
```bash
[Bruna et al. 2013] Bruna, J.; Zaremba, W.; Szlam, A.; and
LeCun, Y. 2013. Spectral networks and locally connected
networks on graphs. arXiv preprint arXiv:1312.6203.
```

![image_uploaded_from_ios_720](https://user-images.githubusercontent.com/1225605/35058145-0d8203f8-fb85-11e7-8dc5-7259ba0fb7f3.jpg)
![selection_032_720](https://user-images.githubusercontent.com/1225605/35058147-0e8e0300-fb85-11e7-8bc7-56f9b6d9424c.png)

2. I have already implemented A version of adaptive Laplacian Graph Transformations here
https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/models/graph_models.py#L500
https://arxiv.org/abs/1703.00792
It might be a good starting place for someone wanting to implement the method described in this paper.

**Comment by Dgelemi** [comment]
thanks for the info 👍
