### ISSUE TITLE
Revisiting BBBP

### ISSUE THREAD

**Issue by patrickhop** [deepchem/deepchem#1027]
Wanted to revisit #469. The dataset quoted [http://cheminformatics.org/datasets/li/bbp2.smi] has 415 lines, and the dataset we use [https://github.com/deepchem/deepchem/blob/3a03e9586b82e8d1347454c7ff4885192f7e1c99/deepchem/molnet/load_function/bbbp_datasets.py#L23] has 2051 lines.

It would be nice to double-check where this difference came from.

**Comment by lilleswing** [comment]
@miaecle @evanfeinberg

**Comment by miaecle** [comment]
@patrickhop We picked the dataset from a more recent publication: http://pubs.acs.org/doi/10.1021/ci300124c
The raw dataset can be access through: http://pubs.acs.org/doi/suppl/10.1021/ci300124c/suppl_file/ci300124c_si_001.txt

**Comment by patrickhop** [comment]
@miaecle very cool - thanks.

going to close this out.
