### ISSUE TITLE
missing tasks when merging DiskDataset

### ISSUE THREAD

**Issue by fmonta** [deepchem/deepchem#1030]
Hello,
I have come up with the problem that, after merging pre-defined cross-validation folds using DiskDataset.merge(), the resulting dataset does not contain any tasks anymore, hence cannot be transformed (because get_shape() returns empty tuples for y and w). I believe a fix would be to edit the return of the merge() method
   `    return DiskDataset.create_dataset(generator(), data_dir=merge_dir)`
 to include somehow the tasks that were included in the individual datasets we are merging.

**Comment by lilleswing** [comment]
Fixed with #1031
