### ISSUE TITLE
Integration with Keras

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1038]
This issue is to discuss how we can harmonize/integrate TensorGraph with Keras.  In the short term, I think these are the main goals:

- Be able to add Keras layers to a TensorGraph.
- Be able to add TensorGraph layers to a Keras model.

In the longer term, I suspect we want to move more of our architecture over to Keras.  That could mean completely replacing TensorGraph with Keras, or it could mean TensorGraph extends a Keras model class, or various other things.  It's all up for discussion.

I want to start by considering the obstacles to adding Keras layers to a TensorGraph.  Although they're very similar, TensorGraph layers have certain features that it isn't obvious to me how to reproduce with Keras layers.  (That may just be because I haven't used Keras much.)

- TG expects layers to be pickleable.  Keras doesn't support that, though it has various other mechanisms for saving models.
- TG layers provide special support for working with recurrent models.  I don't see anything comparable in the Keras API.
- TG layers provide support for Tensorboard.

**Comment by rbharath** [comment]
This is a great summary. Improved integration of Keras and TensorGraph layers will make it easier for more people to use DeepChem and should broaden our impact.

Here are a couple thoughts on how we might implement this feature. I believe the key semantic difference between Keras and TensorGraph layers is that Keras layers add operations to the underlying TensorFlow graph upon construction while TensorGraph layers only do so upon invocation of build().

One possibility for adding TensorGraph layers to Keras models is that we could add a flag that controls when operations are added to the underlying graph. When set correctly, would make TensorGraph layers behave like Keras layers.

**Comment by peastman** [comment]
> I believe the key semantic difference between Keras and TensorGraph layers is that Keras layers add operations to the underlying TensorFlow graph upon construction while TensorGraph layers only do so upon invocation of build().

Not exactly?  I'm trying to understand the architecture of Keras layers, but it's a bit convoluted and I'm still unclear on some parts.

To start with, `tf.keras.layers.Layer` subclasses `tf.layers.Layer`.  Each individual layer then uses multiple inheritance to subclass both that and the corresponding Tensorflow layer.  So `tf.keras.layers.Conv1D` extends both `tf.keras.layers.Layer` and `tf.layers.Conv1D` (each of which in turn extends `tf.layers.Layer`).  Of course, it's more complicated than that with additional intermediate parent classes in the middle.

The Tensorflow/Keras layers distinguish between layers and tensors.  When you construct a layer it doesn't build any tensors.  You also don't specify any inputs to the constructor.  You then invoke the layer as if it were a function, passing in the input tensors (not layers!) to it, and it returns an output tensor.

That makes it seem like a layer is just a definition that you should be able to invoke many times to create many different tensors.  But that's not the case!  One of the things `__call__()` does is to record the inputs you passed in, so you can later query the *layer* for its input *tensors*.  (I think I've got that right?)  Also, each layer has a `build()` method that gets called inside `__call__()`.  Unlike TensorGraph, where `build()` constructs all the tensors, in Tensorflow the only job of `build()` is to create the layer's variables.  Everything else is created inside `__call__()`.

And now we get into the even more complicated parts.  Each layer can operate in a few different modes.  At the beginning of `__call__()` it sets a flag called `in_graph_mode`, which I gather is related to the new eager execution mode they're developing.  But it also sets a flag called `in_deferred_mode`, and I can't find any documentation on what that's about.  In any case, the method can behave totally differently depending on which of these flags are set.  I don't claim to understand it.

**Comment by rbharath** [comment]
Great summary. Looking at the code, `tf.keras.layers.Conv1D` is basically just a thin wrapper over `tf.layers.Conv1D` with `tf.keras.layers.Layer` doing the necessary book-keeping work. Perhaps we could use a similar multiple inheritance style?

**Comment by peastman** [comment]
How would that work?

**Comment by rbharath** [comment]
I think we could inherit from tf.keras.layers.Layer to get the bookkeeping needed.

**Comment by peastman** [comment]
Are you assuming we would rewrite TensorGraph and all the layers to use the same construction model that Keras does?  Otherwise, I don't see how that could work.  The two models are different enough that trying to combine both in a single object doesn't seem viable.  But if we're going to rewrite everything, we might as well just switch over to Keras.

**Comment by rbharath** [comment]
Maybe we should just switch over to Keras. I think we're heading in that direction already..

**Comment by peastman** [comment]
That's one possible approach.  If we do that, the overall migration plan would be to 1) convert all our custom layers from TensorGraph layers to Keras layers, and 2) convert all our TensorGraph models to Keras models.  We would also need to carefully compare the Keras model class to TensorGraph, identify any features of the latter that aren't present in the former, and figure out what to do about them.

@lilleswing what do you think about this?

**Comment by lilleswing** [comment]
The first questions that come to mind are
1) Are keras layers interoperable with tf.keras?
2) How stable is the keras API (i.e. how many interfaces would have changed over the past 3 months)
3) How to combine raw tensorflow code with keras layers?  The documentation on writing your own layer is real light (https://keras.io/layers/writing-your-own-keras-layers/)

**Comment by lilleswing** [comment]
I'm not in love with the idea of a second code migration in a year -- but the writing does seem to be on the wall.

**Comment by peastman** [comment]
> Are keras layers interoperable with tf.keras?

See the "TF Integration" section at https://github.com/keras-team/keras/issues/5299.  Basically, tf.keras is a complete, independent implementation of the Keras API.  It's meant to be API compatible with the standalone version, while more easily and directly interfacing with Tensorflow code.  I assume that in all of this discussion we're talking about using tf.keras, not standalone Keras?

> How stable is the keras API (i.e. how many interfaces would have changed over the past 3 months)

According to https://blog.keras.io/introducing-keras-2.html (posted in March of last year), "The new Keras 2 API is our first long-term-support API: codebases written in Keras 2 next month should still run many years from now, on up-to-date software."

> How to combine raw tensorflow code with keras layers?

One of the goals of tf.keras is to make that very easy.  Keras layers *are* Tensorflow layers.  They take ordinary TF tensors as arguments and return ordinary tensors.  Also see https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html.

**Comment by lilleswing** [comment]
So I tried it out today, attempting to port MultiTask and GraphConv over to keras Layers/Models.
https://github.com/deepchem/deepchem/pull/1046

It was pretty mechanical until it wasn't.  The biggest issue I see is the strict checking of inputs in Keras' Model.fit interface.  It requires all inputs/outputs to have the same number of samples which doesn't work with our GraphConvolution featurization.  This means we will still need a tight coupling of featurization of datasets and custom models.

We also need to figure out how we can continue the same ability of Submodel of TG, and what the requirements are to save and load custom keras layers.

**Comment by peastman** [comment]
> We also need to figure out how we can continue the same ability of Submodel of TG

I think I see how this works.  In Keras, a layer defines a computation and a set of variables.  It does not define inputs or outputs.  A single layer can appear several times in a model.  Each time it appears, it uses the same variables but different inputs to compute a different output.  A layer can also appear in multiple models, in which case that layer's variables are shared between them.

So a submodel is just another model.  It uses a set of layers to compute a loss function based on inputs.  You can fit that model to set the values of those layers' variables.  If some of those layers happen to also appear in a different model, that other model will automatically pick up the changed variables.

**Comment by peastman** [comment]
> what the requirements are to save and load custom keras layers.

It looks like you do this by having the layer implement `get_config()`.  It returns a dict with all the arguments that need to be passed to the constructor to create an identical object.  You can include any kind of object it knows how to serialize as JSON.

**Comment by lilleswing** [comment]
Other Features
1) Saving and Loading should be doable w/ get_config()
2) the rnn states in tensorgraph?
3) a3c requires cloning and copying weights

**Comment by peastman** [comment]
> the rnn states in tensorgraph?

It should definitely be possible to do what we need, though it might be a little less convenient.  I'm still trying to understand how this works.

> a3c requires cloning and copying weights

If nothing else, we should be able to clone layers by serializing them to JSON and deserializing again.  Hopefully there's a simpler way.  Copying weights is easy: each layer has `get_weights()` and `set_weights()` methods.  Though it's probably more efficient to get the `variable` object and have Tensorflow copy it directly, if we can do that.

**Comment by peastman** [comment]
What do we want to do about the API for user code?  Should we try to keep it as close as possible to the current API, or should we move it to be more Keras like?  For example, in the current API someone might write

```python
model = MultiTaskClassifier(tasks, features, layer_sizes, batch_size=50)
model.set_optimizer(optimizer)
model.fit(dataset, nb_epoch=10)
```

If we convert MultiTaskClassifier to extend the Keras Model class and have it alter the parent class API as little as possible, that would become

```python
model = MultiTaskClassifier(tasks, features, layer_sizes)
model.compile(optimizer, model.loss)
model.fit_generator(dataset.iterbatches(batch_size=50), epochs=10)
```

Alternatively we might put the `compile()` call inside the constructor, in which case it would become

```python
model = MultiTaskClassifier(tasks, features, layer_sizes, optimizer=optimizer)
model.fit_generator(dataset.iterbatches(batch_size=50), epochs=10)
```

My inclination is that we want to go with the more natural Keras API.  The changes required by users will still be pretty small, and in the long run it will make things easier for everyone.

**Comment by rbharath** [comment]
Agree we should go with the natural Keras API (perhaps moving `compile()` inside constructor for convenience). Making the on-boarding ramp as smooth as we can for Keras users will help us here.

**Comment by peastman** [comment]
I'll try converting the fully connected multitask models and see how it goes.

**Comment by peastman** [comment]
When you call any of the predict methods on a TensorGraph, you can pass in a list of Transformers and it will automatically call `undo_transforms()` for them.  I don't see anything equivalent in Keras.  Any thoughts on how to deal with this?

**Comment by rbharath** [comment]
Good point. I'd suggest we punt on dealing with Transformers in the first iteration. Eventually, we may want to override the `predict` method in `MultiTaskClassifier` to handle this automatically.

**Comment by peastman** [comment]
Is it just me, or is importing Keras classes totally messed up?  If I write

```python
import tensorflow as tf
print(tf.keras)
```

it outputs

```
<module 'tensorflow.python.keras' from '/Users/peastman/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py'>
```

just as you'd expect.  But if I write

```python
import tensorflow.keras
```

I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.keras'
```

Huh?  According to https://stackoverflow.com/questions/47262955/how-to-import-keras-from-tf-keras-in-tensorflow you need to write `tensorflow.python.keras` instead of `tensorflow.keras`.  And indeed,

```python
import tensorflow.python.keras.backend
```

works just fine.  But if instead I write

```python
import tensorflow.python.keras.backend as K
```

then I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'python'
```

What's going on???

**Comment by peastman** [comment]
Also, it turns out the version of the Keras API in Tensorflow 1.4 is somewhat behind the current Keras release.  `fit_generator()` is missing a feature that would make the examples shown above significantly less friendly.  We would have to do something like

```python
generator = dataset.iterbatches(batch_size=50)
model.fit_generator(generator, len(generator), epochs=10)
```

This does seem to be fixed in Tensorflow 1.5.  Is it ok if I use the newer version, assuming we'll be moving to TF 1.5 pretty soon?

**Comment by peastman** [comment]
And yet another issue.  `fit_generator()` requires each batch to be either a two element tuple `(x, y)` or a three element tuple `(x, y, weights)`.  But `Dataset.iterbatches()` represents them as four element tuples `(x, y, weights, ids)`.

Maybe we need to rethink this approach.  For example, we could have a `fit_dataset()` method that handles this for you.

**Comment by rbharath** [comment]
I think a `fit_dataset()` isn't a bad idea. We could also just generalize `fit()` itself to handle this correctly.

A backwards compatibility breaking chance would be to have `Dataset.iterbatches()` return tuples `(x, y, weights)`. I'm not sure if `ids` adds much value and it would be good to have seamless interop.

**Comment by peastman** [comment]
Another significant difference is how metrics are handled.  In DeepChem, a metric is an instance of dc.metrics.Metric.  You specify them when you call `evaluate()`.  It has a `compute_metric()` method that receives a pair of numpy arrays and computes the metric.

In Keras, a metric is any function of the form `f(y_true, y_pred)`.  You specify them when you create the model (or rather when you compile it).  The arguments to it are tensors, *not* numpy arrays.  It returns a new tensor that can be used to compute the metric.

How do we want to handle this?

**Comment by rbharath** [comment]
I think Keras is using its metrics to define the model itself while our metrics are purely for evaluation and not for training. I think our set of loss functions matches what Keras calls metrics. Converting our loss functions to match Keras seems like a good direction.

`sklearn` also follows the `f(y_true, y_pred)` model, but with arguments Numpy arrays. I think it makes sense to convert `dc.metrics` over to this model to match `sklearn`.

**Comment by peastman** [comment]
I think we need to reconsider our approach, now that we have a better idea of the implications.  To summarize the situation:

- DeepChem and Keras each have a class called Model.  They have a lot of methods with the same names, but those methods take different arguments and behave in different ways.

- DeepChem has a Dataset class.  It presents data in a way that isn't compatible with how Keras expects it.

- DeepChem and Keras each support metrics, but they represent them in very different ways that work differently.

- DeepChem and Keras each have classes to represent optimizers, but they work differently and aren't compatible with each other.

- And so on.

I can see two ways forward:

1. Create a KerasModel class that extends the DeepChem Model class (*not* the Keras Model class).  It will use Keras layers internally to implement models, but the interface it presents to the user will be pure DeepChem.  This will eventually replace TensorGraph, but nothing else in DeepChem will be getting replaced.

2. Dump *most of DeepChem*, then reconstruct it as a set of tools for use with Keras.  Anything that Keras provides an API for, we use their API.  That includes models, optimizers, metrics, etc.  The parts that remain will have their APIs redesigned to work naturally with Keras.

**Comment by peastman** [comment]
> I think our set of loss functions matches what Keras calls metrics.

Not really.  Keras has distinct loss functions (for training) and metrics (for evaluation).  DeepChem offers a library of metrics, but it doesn't really have "loss functions" as such.  Each model is responsible for computing its loss itself.  TensorGraph has some layers that are useful when computing certain common types of loss functions, but that's not quite the same thing.

**Comment by rbharath** [comment]
Interesting, didn't realize Keras computed metrics as part of the network itself...

The second option is radical, but might be our path to achieving greatest long-term impact. If we achieve direct inter-op with tf.keras, we could potentially evolve into the de-facto chem/bio/science layer for TensorFlow. This would let us reach potentially an order-of-magnitude more users and impact. 

The first option feels more like a stopgap. In fact, we used to have a `KerasModel` class that functioned this way in the past, but it never saw much use.

**Comment by peastman** [comment]
Here's the latest problem I've run into.  I'm trying to convert MultiTaskRegressor.  It expects the weights to be an array of shape (n_samples, n_tasks).  The loss gets computed over `(y_true-y_pred)*weights`.  But as far as I can tell, Keras simply doesn't support losses like that.  It requires the weights to be a 1D array of per-sample weights.  You can't even do it by defining a custom loss function, because that function has to have the form `f(y_true, y_pred)`.  It never gets to see the weights.  Keras does the weighting of samples at a higher level.

I could try to work around this by defining the weights to be a regular input to the model, and having them get passed straight through to the output.  Then the loss function would be able to see them.  But this would lead to an ugly interface for the model.  If you called `predict()`, you would be forced to supply weights even though they wouldn't get used for anything, and those weights would then get returned as one of the outputs of the model.

**Comment by rbharath** [comment]
This one sounds like a genuine limitation of Keras. Perhaps a good target for a pull request into Keras itself?

For getting off the ground, introducing a KerasModel class as an intermediary to handle ugliness may be the right answer after all.

**Comment by peastman** [comment]
I'll try asking on the Keras discussion group.

**Comment by lilleswing** [comment]
@peastman I believe keras would expect you to have a list of outputs (1 per task).  Then you can use a list of lists as your sample weights.

**Comment by peastman** [comment]
That's how the multitask models used to work, before I converted them to TensorGraph.  They were really really slow.  Combining all the outputs into a single array made training a lot faster.

**Comment by rbharath** [comment]
@Chasearmer We put some effort into exploring whether we could use Keras instead of TensorGraph, but this looks like it won't work. On the technical side, some needed features aren't well supported in Keras. We didn't have much response from the Keras community when we floated the idea of a PR to add these features either.

We would like to better support DeepChem users who are using Keras and DeepChem together. Do you have any suggestions for ways we can better support your use case?

**Comment by rbharath** [comment]
I'm closing this since it looks like we're sticking with `TensorGraph` for the time being.
