### ISSUE TITLE
Integrating tf.data and dc.data

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1039]
Continuing our architectural discussions, it's starting to become clear we should integrate dc.data and tf.data in some manner. dc.data is one of the hackier parts of DeepChem and has caused us a good number of scaling and portability headaches. Swapping out this code for optimized tf defaults seems generally useful.

At the same time, we need to plan a transition that doesn't entirely break backwards compatibility. Let's use this thread to brainstorm possible implementation paths.

**Comment by peastman** [comment]
tf.data is very flexible but also awkward to use.  There's nothing nearly as simple as just passing a Dataset object to a model.  Instead, every time you use a dataset you have to write an "input function" that's responsible for gathering up the data and packaging it in whatever way is required.

I think this feature request involves two pieces:

1. Allow a DeepChem Dataset to be used with models designed for use with tf.data.  I don't think this should be hard, especially given that you're expected to write adapter code anyway.  A simple implementation would be to add a `make_iterator()` method to Dataset.  It would return a tf.data.Iterator, which exposes tensors for reading the data.  I'll try implementing this.

2. Allow TensorGraph models to work with tf.data data sources.  This will require more thought.  Possibly we want to redesign TensorGraph to be a subclass of tf.estimator.Estimator.  Or we might create a way to wrap a TensorGraph in an Estimator, similar to how `tf.keras.estimator.model_to_estimator()` works.

**Comment by rbharath** [comment]
I think we can close this since addressed by #1091 and the new tutorials on using Dataset and tf.data together.
