### ISSUE TITLE
Tutorial For Tensorboard

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1043]
Tutorial on how to use tensorboard.  Make pretty pictures like this.

![selection_033](https://user-images.githubusercontent.com/1225605/35393122-1127b268-01b2-11e8-9485-f6f0f344f51d.png)

Also showing training loss over time.

**Comment by rbharath** [comment]
Strongly agree! Good overviews of our visualization capabilities will really help on-board new users.

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/1051
