### ISSUE TITLE
Tutorial for setting up DeepChem in an ipython notebook

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1044]
We don't ship with jupyter by default.  Maybe we should?  I have had to help a lot of people because they end up using the system defaults jupyter and then they can't import things. Then they blame DeepChem for being hard to use.

**Comment by rbharath** [comment]
Yes, agreed. We should ship with jupyter to decrease friction for new users. This will be especially important for our scientific users who might be stymied by these issues.

**Comment by lilleswing** [comment]
I put it in our install script by default and we can ship it with our conda package at the next version bump.
https://github.com/deepchem/deepchem/pull/1050

With this I don't think we also need a tutorial.
