### ISSUE TITLE
KRR(CM) gains poor performance when CM featurized from gdb7.sdf

### ISSUE THREAD

**Issue by 0ut0fcontrol** [deepchem/deepchem#1047]
When CM load from `qm7.mat`, MAE(test) is about **10** kcal/mol, close to the number reported in [molnet paper](https://arxiv.org/abs/1703.00564).     

But when CM featurized from `gdb7.sdf`, MAE(test) is about **70** kcal/mol.    
 
Here is the gist that can reproduce the problem.
https://gist.github.com/0ut0fcontrol/0b80c07dde1002e8431b20f8cdc805dc    

may related issue #365    

Thanks.

**Comment by lilleswing** [comment]
@joegomes

**Comment by miaecle** [comment]
@0ut0fcontrol Thanks for pointing out the issue. `qm7.mat` is the file we use to generate molnet benchmark for CM methods. As you have noticed, `gdb7.sdf` is deprecated as the physical coordinates are not accurate, leading to the much higher MAE.

**Comment by 0ut0fcontrol** [comment]
I want to make sure that CoulombMatrix featurizer has not problem.
I found the inconsistent start from 5604 th mol in sdf file after #1048 pointing out the length different. 
So I only featurized mol 1-5603 in gdb7.sdf and train, MAE(test) was close to 10 kcal/mol.
My problem was solved.
Thank you for your help. @lilleswing @miaecle @joegomes
