### ISSUE TITLE
Error when running tox21_tensorgraph_weave.py

### ISSUE THREAD

**Issue by simonfqy** [deepchem/deepchem#1052]
I am using Linux machine. Previously I ran `python3 ./examples/benchmark.py -m weave -d tox21` and it worked smoothly without problems. However, when I was trying to run `python3 ./examples/tox21/tox21_tensorgraph_weave.py`, it worked fine in the training process, but when it was entering the evaluation processes, the following output is shown (the beginning lines in the output shown below are simply meant to demonstrate the successful training):

> Starting epoch 49
Ending global_step 4900: Average loss 640.49
TIMING: model fitting took 557.867 s
Evaluating model
Traceback (most recent call last):
  File "./tox21/tox21_tensorgraph_weave.py", line 38, in <module>
    train_scores = model.evaluate(train_dataset, [metric], transformers)
  File "/opt/anaconda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/models.py", line 192, in evaluate
    scores = evaluator.compute_model_performance(metrics)
  File "/opt/anaconda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/evaluate.py", line 103, in compute_model_performance
    self.output_transformers).astype(int)
AttributeError: 'list' object has no attribute 'astype'

Can you please help me fix this?

**Comment by miaecle** [comment]
@simonfqy Hi! I believe this issue should come from the standard output structure of tensorgraph, I fix the output shapes for deepchem graph models in #1042 , which should bypass the problem.

**Comment by simonfqy** [comment]
@miaecle Do you mean that installing the newer version of DeepChem would solve the problem? As a background information, I use a Linux GPU cluster, in which the DeepChem library was installed and could be activated by `source activate deepchem` command. Besides, I downloaded the deepchem GitHub repository privately to my own folders, just intending to use the dataset and examples inside. The `python3 ./examples/tox21/tox21_tensorgraph_weave.py` command was called after `source activate deepchem`. I saw that your change was merged 3 days ago, so it might be in my privately downloaded copy but not in the deepchem library installed in the whole system.

**Comment by miaecle** [comment]
@simonfqy That is correct. I think the newest version of repository should work(your private one) while you might need to wait till next public release for completely fixing the issue. Another workaround might be calling `model.predict_proba(train_dataset, transformers)` instead of `model.evaluate`, which will give you a list of outputs, each corresponding to a task in tox21(12 tasks in total). You should be able to manually concatenate them and compare with true labels (`train_dataset.y`).

**Comment by simonfqy** [comment]
@miaecle Thank you. I have asked our system administrator to upgrade the deepChem library. I will try it once it is done. BTW, when is the next public release?

**Comment by miaecle** [comment]
@rbharath

**Comment by rbharath** [comment]
I believe that we should have the next version out within a month or so. Sorry for the inconvenience here!
