### ISSUE TITLE
SCScore: Synthetic Complexity

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1060]
http://pubs.acs.org/doi/abs/10.1021/acs.jcim.7b00622

It is a fairly easy model to implement, and can be used to ensure de-novo designs are synthetically tractable.  

@patrickhop

**Comment by lilleswing** [comment]
We could even ship a pre-trained model for this one.

**Comment by lilleswing** [comment]
https://github.com/connorcoley/scscore

**Comment by rbharath** [comment]
+1. This seems like a great addition.

**Comment by patrickhop** [comment]
Good find @lilleswing. This would be an awesome addition.

**Comment by abster12** [comment]
I would like to work on this one

**Comment by rbharath** [comment]
@abster12 Great to hear about your interest! Could you open a WIP pull request tracking your implementation progress? We can provide feedback and guidance on that thread

**Comment by rbharath** [comment]
Implemented by @lilleswing
