### ISSUE TITLE
Question on windows support

### ISSUE THREAD

**Issue by redBirdTx** [deepchem/deepchem#1062]
Hi, I'm new to deepChem. Just wonder if there is a deepchem package for windows? I tried using conda install, however I am getting a packageNotFoundError.
Anyway getting around with this? I'd appreciate any comment on this.Thanks

**Comment by rbharath** [comment]
Unfortunately, no Windows support currently. I'd be very interested in seeing this happen though if someone wants to take on the challenge.

**Comment by leeyjjoel** [comment]
Hi @rbharath, I think I'd be able to provide windows support for deepchem. Could I have this issue too?

Joel

**Comment by rbharath** [comment]
@leeyjjoel I'm excited to hear you're interested in taking on this challenge. Could you propose a potential implementation path in this thread? If that sounds technically feasible, we'd welcome a contributed PR

**Comment by MortZx** [comment]
Hi, I'm also new to deepchem and very sad to hear it's not available to windows users. Has there been any progress on making deepchem supported on Windows? 
Thanks, Mortimer

**Comment by rbharath** [comment]
@MortZx I think deepchem is now known to work on windows subsystem for linux. That's probably going to be our recommended installation path on Windows moving forward.

**Comment by rvaidya** [comment]
GPU support for WSL isn't currently implemented and there's no timeline for its delivery, so WSL is not a good solution right now.

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16108045-opencl-cuda-gpu-support

**Comment by rvaidya** [comment]
That being said, I was able to get the installation itself to work by following the steps in install_deepchem_conda.sh and installing mdtraj and xgboost from conda-forge.  setup.py finished without issues and a lot of the tests do pass - though not all.

**Comment by peastman** [comment]
Which tests fail (aside from ones that need xgboost)?  Hopefully we only need minor changes to get them working.

**Comment by JimSEOW** [comment]
As a follow to [#599](https://github.com/deepchem/deepchem/issues/599) 

Using the Windows 10 WSL ubuntu18.04, I am able to install the latest linux64 deepchem 2.1.0 through conda. The installed deepchem seems to work with many of the provided jupyter notebooks in WSL environment. 

Feedback:
(a) I agree with @rvaidya, it is important to aim for non WSL Windows installation of Deepchem as we need tensorflow-GPU.
(b) the installed Anaconda deepchem 2.1.0 depends on old 2017 version of RDkit.

**Comment by madalsa** [comment]
> As a follow up to [#599](https://github.com/deepchem/deepchem/issues/599)
> 
> Using the Windows 10 WSL ubuntu18.04, I am able to install the latest linux64 deepchem 2.1.0 through conda. The installed deepchem seems to work with many of the provided jupyter notebooks in WSL environment.
> 
> Feedback:
> (a) I agree with @rvaidya, it is important to aim for non WSL Windows installation of Deepchem as we need tensorflow-GPU.
> (b) the installed Anaconda deepchem 2.1.0 depends on old 2017 version of RDkit.

Hi Jim,
Have you tried replicating any procedures from their MolecularNet paper on the Deepchem on WSL? I'm currently working on replicating some of their stuff on a larger molecular dataset and I wanna know if WSL would work.

Thanks

**Comment by rbharath** [comment]
I'm tidying up issues. Let's continue the discussion here in #1486 so we have a unified thread. Closing this issue
