### ISSUE TITLE
PCBA dataset, outcome variable?

### ISSUE THREAD

**Issue by selcukorkmaz** [deepchem/deepchem#1064]
I have downloaded "pcba.csv" dataset to run some deep learning examples on it. However, I could not find the outcome variable to perform the classification. I wonder which variable is the outcome variable.

**Comment by miaecle** [comment]
@selcukorkmaz Welcome! For PCBA, this is a comprehensive dataset including 128 assays for over 400k molecules. In the file `pcba.csv`, there should be 130 columns, in which the first 128 columns represent the outcomes for these essays. In other word, each column contains labels for an individual task(essay). The last 2 columns are identifiers for molecules, we typically use smiles to represent and featurize molecules.

**Comment by rbharath** [comment]
Closing this issue since I think the question was addressed.
