### ISSUE TITLE
How To Cite DeepChem

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1066]
How does one cite DeepChem?  We never published a paper specifically on DeepChem, just papers doing work using DeepChem.  Which one to we point people to for citing implementations that we do that aren't really in any publications.

**Comment by rbharath** [comment]
I think it's time for us to put together an Arxiv paper describing DeepChem. Would be a good to start gathering citations for the project and would also be a good spot for us to discuss design considerations.

I'll start putting together a skeleton this week.

**Comment by lilleswing** [comment]
I guess that means short answer for now is don't cite us?

**Comment by rbharath** [comment]
Probably short answer is to cite MoleculeNet paper while we work on the actual DeepChem paper.

**Comment by miaecle** [comment]
In MoleculeNet paper I just cited the github page, does that work?

**Comment by rbharath** [comment]
@miaecle Yeah, I think that should be fine.

**Comment by pvskand** [comment]
```
@misc{deepchem,
  title = {Democratizing Deep-Learning for Drug Discovery, Quantum Chemistry, Materials Science and Biology },
  year = {2016},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/deepchem/deepchem}}
}
```
@rbharath, Is this correct? If yes then I feel that we should put it in the README.md since citation of someone's work is very important and I feel deepchem's contributors must get a share of what they have done to make it awesome :)

**Comment by rbharath** [comment]
@lilleswing @peastman @miaecle Have thoughts?

We haven't had time to put together a formal DeepChem paper yet, (although we have a stub floating around), so it might make sense to direct people to cite the repo directly. I'm a little worried Google scholar won't pick up on it which might lead us to lose the citations...

**Comment by peastman** [comment]
It's also possible to get a DOI for a particular release.

**Comment by pvskand** [comment]
https://guides.github.com/activities/citable-code/ gives a way to create a DOI. Do have a look at it.

**Comment by UnixJunkie** [comment]
Just citing the README:
```
If you have used DeepChem in the course of your research, we ask that you cite the "Deep Learning for the Life Sciences" book by the DeepChem core team.

To cite this book, please use this bibtex entry:

@book{Ramsundar-et-al-2019,
    title={Deep Learning for the Life Sciences},
    author={Bharath Ramsundar and Peter Eastman and Patrick Walters and Vijay Pande and Karl Leswing and Zhenqin Wu},
    publisher={O'Reilly Media},
    note={\url{https://www.amazon.com/Deep-Learning-Life-Sciences-Microscopy/dp/1492039837}},
    year={2019}
}
```

So, I guess this issue can be closed.
