### ISSUE TITLE
Versioned versions of docs

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1069]
Many serious projects maintain stable versions of docs for each major version release. I think we should do this for DeepChem, especially since 2.0 and subsequent releases will have major API changes and many of our users may not upgrade quickly.

**Comment by rbharath** [comment]
Note that this would also ensure we avoid issues like #1067 in the future, since the stable versions of the docs won't be broken by new builds.

**Comment by lilleswing** [comment]
yeah we can start with the 2.0 cut next week.

**Comment by lilleswing** [comment]
This is done now
https://deepchem.io/docs/index.html
