### ISSUE TITLE
Binary Classification Tutorial

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#107]
None of our current tutorials demonstrate how to perform Binary classification. We should make a tutorial that walks users through fitting a binary classification model.

**Comment by evanfeinberg** [comment]
+1. We could do it with Dud-E once docking is wrapped into a class and
callable with deepchem API.

On Mon, Feb 22, 2016 at 3:06 PM, Bharath Ramsundar <notifications@github.com

**Comment by rbharath** [comment]
`examples/bace` now provides a simple example of a classification problem.
