### ISSUE TITLE
Installation: git clone- error: No module named 'simdna'

### ISSUE THREAD

**Issue by pkvreddy** [deepchem/deepchem#1070]
Followed installation steps to git clone the repository and got the below error. Any pointers?
![image](https://user-images.githubusercontent.com/16655273/35835284-abb82968-0a8e-11e8-9e08-272d7bc6b6ab.png)

**Comment by lilleswing** [comment]
Well the quickest way to solve this would be 
```bash
conda install -c conda-forge simdna=0.4.2
```

But can you tell me your O.S. and githash so I can see why it happened? simdna should of been installed with the [install script](https://github.com/deepchem/deepchem/blob/master/scripts/install_deepchem_conda.sh#L46).

```bash
git rev-parse HEAD
```

**Comment by pkvreddy** [comment]
Suggestions please
![image](https://user-images.githubusercontent.com/16655273/35873750-864c290e-0b1f-11e8-822a-27b16bb3e6f7.png)
![image](https://user-images.githubusercontent.com/16655273/35873795-a25c8e40-0b1f-11e8-8d7f-59263c521bfe.png)

**Comment by pkvreddy** [comment]
Suggestions please
![image](https://user-images.githubusercontent.com/16655273/35876796-3dd890fa-0b28-11e8-9ede-ce6213e919d0.png)

**Comment by lilleswing** [comment]
It seems your machine is behind a firewall which does not allow you to connect to continuum.  Lots of our dependencies are hosted there.  
That file does exist and is accessible on the internet.
```bash
(daily) ➜  ~ wget https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2
--2018-02-06 13:34:23--  https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2
Resolving repo.continuum.io (repo.continuum.io)... 104.16.18.10, 104.16.19.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.18.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 438183 (428K) [application/json]
Saving to: ‘repodata.json.bz2’

repodata.json.bz2             100%[=================================================>] 427.91K  --.-KB/s    in 0.02s

2018-02-06 13:34:23 (24.8 MB/s) - ‘repodata.json.bz2’ saved [438183/438183]
```

We do not support offline installs at this time.

**Comment by pkvreddy** [comment]
ok thank you!
