### ISSUE TITLE
LIME for model explanation

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1071]
https://arxiv.org/pdf/1602.04938.pdf

Can we apply this to our Graph Based algorithms without solving the Graph Isomorphism?  

Can we hook this up to our fingerprint and text based models?

https://github.com/marcotcr/lime/issues

**Comment by rbharath** [comment]
Marking this contributions welcome. Code experimenting with Lime would be a great addition to contrib/. This might require some sophistication to do correctly though.

**Comment by souravsingh** [comment]
I can try this for autoencoders, unless there is some better model.

**Comment by rbharath** [comment]
@souravsingh I susepct we might want to try with the plain graph convolutions first since I believe LIME is intended for supervised learning work.

**Comment by rbharath** [comment]
Implemented by @lilleswing
