### ISSUE TITLE
Featurizer fails silently when SMILES string is empty

### ISSUE THREAD

**Issue by dmoccia** [deepchem/deepchem#1073]
Not really a bug on your side but I encountered an issue while loading a dataset paired with featurization and thought you may want to address this at some point.  

I ran the following code in jupyter notebook environment

```
dataset_file = 'myFile.csv'
task = ['TARGET']
featurizer_func = dc.feat.ConvMolFeaturizer()
loader = dc.data.CSVLoader(tasks=task, smiles_field='SMILES', featurizer=featurizer_func)
dataset = loader.featurize(dataset_file)
```

which in general works quite well (and it is very fast!!).  However when SMILES is empty in your dataset the Kernel dies silently and there does not appear to be any error message in the console.  While I certainly understand that we should be checking for missing SMILES in our code upstream sometimes this sort of thing can bleed through, especially when you are learning a new framework.  

Let me know if you need more details or cannot reproduce.  Hoping I can contribute to the code as I get up to speed.

**Comment by lilleswing** [comment]
Looks like you found a bug in rdkit!
```python
rdmolfiles.CanonicalRankAtoms(mol)
```
throws a segfault on 0 atom molecules.

We have to add a 0 atom molecule check here.
https://github.com/deepchem/deepchem/blob/master/deepchem/data/data_loader.py#L72
and probably log something to warn the user.

Pull Requests Welcome!  If you have any other issues with the PR just ping this ticket and I can help out.

**Comment by lilleswing** [comment]
I brought up the issue with the rdkit team.
https://github.com/rdkit/rdkit/issues/1735

**Comment by dmoccia** [comment]
Thanks @lilleswing, I will get setup so I can initiate PR.  You guys have done a lot of nice work!

**Comment by rbharath** [comment]
It looks like this was fixed in https://github.com/rdkit/rdkit/pull/1743, so going to close this old issue
