### ISSUE TITLE
Minimizing use of  dc.data.Dataset

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1075]
One of the biggest hurdles for newcomers to the project is dealing with `dc.data.Dataset`. This object adds an extra layer of abstraction to working with datasets that isn't found in other popular python open source projects. I think this extra step puts off beginners who're looking for a quick entrypoint into the library since they have to learn an unfamiliar API to use our models.

I propose that we minimize use of `dc.data.Dataset` in DeepChem. For smaller datasets, where we use `NumpyDataset` currently, this won't cause a large disruption since we can just Numpy arrays `(X, y, w)` like other open source packages.

For larger datasets, this gets a lot trickier since we use `dc.data.DiskDataset` to store large datasets on disk for MoleculeNet and we've put significant effort into making this function. It's probably most feasible to leave this as-is for now, since I'm not sure there's a dominant abstraction for storing ML data on disk right now. 

Concretely though, I propose we modify `Model.fit` and `Model.predict` to accept Numpy arrays `(X, y, w)` by default (can also continue accepting `Dataset` for backwards compatibility for now) and we should remove uses of `dc.data.Dataset` from all our examples and tutorials.

**Comment by dmoccia** [comment]
@rbharath I can concur as a very new user I was scratching my head a little bit trying to get up and running with **Dataset**, in particular where the "w" input and its relation to the Transformers.  I think I spent time digging through the Gitter lobby looking for some explanation of how this was being initiated and eventually tracked down the use of the BalancingTransformer.  I think adding a generic input of Numpy arrays could be helpful but maybe just some more info in the docs could get users up and running quicker? 

From what I understand of the DiskDataset so far I believe this to be quite useful as I have some rather large datasets.

**Comment by rbharath** [comment]
@dmoccia Thanks for the feedback! Yes, I agree that some additional docs would be useful. 

The vision we're moving towards with all the redesign work is to make it so that experienced Python programmers should be able to use DeepChem almost instinctively since everything just "works." Some good introductory walkthroughs would really help here.

**Comment by peastman** [comment]
Making it even easier to use straight numpy arrays is a good goal, but it's only practical for small datasets.  For larger ones Dataset is an important tool.  The solution is to add *more* examples and tutorials showing how to use it, not to remove all mention of it.

**Comment by rbharath** [comment]
We discussed this at a steering committee meeting a couple weeks back (http://deepchem.blogspot.com/2018/02/steering-committee-notes.html). We've decided to just add more documentation and tutorials for `Dataset` (#1110) since there's some critical functionality that's not easy to replace with other tools.
