### ISSUE TITLE
The chirality of atom is not encoded into ConvMolFeaturizer

### ISSUE THREAD

**Issue by xiongzhp** [deepchem/deepchem#1078]
I see from the paper that chiral type has been encoded in atom features, but I just cannot find any code like 'GetChiralTag' related to chirality in ConvMolFeaturizer or WeaveFeaturizer, even not in the whole deepchem repo.
https://github.com/deepchem/deepchem/blob/d023484497feb0964ad319352d136c0e605b87b8/deepchem/feat/graph_features.py#L114

**Comment by rbharath** [comment]
@xiongzhp Going to close since we just merged your PR #1080. Thanks for the contribution!
