### ISSUE TITLE
MultiTaskClassifier

### ISSUE THREAD

**Issue by yanyuna** [deepchem/deepchem#1079]
Hi all,
When I follow the tutorials, I got two erros: 

1. First Error: 

_**home/yanyuna/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)**_
    

2. Second Error:
```
best_dnn, best_dnn_hyperparams, all_dnn_results = optimizer.hyperparam_search(params_dict, train_dataset, valid_dataset, transformers,metric=metric)
  File "/home/yanyuna/anaconda2/lib/python2.7/site-packages/deepchem/hyper/__init__.py", line 73, in hyperparam_search
    model = self.model_class(model_params, model_dir)
  File "2.py", line 129, in model_builder
    model = dc.models.MultiTaskClassifier(
AttributeError: 'module' object has no attribute 'MultiTaskClassifier'
```
When I install deepchem, there is no errors. How can I fix these two errors? Thank you very much.

**Comment by rbharath** [comment]
The `DeprecationWarning` is harmless and can be ignored for now. We should transition over to the new API soon though.

Which version of DeepChem do you have installed? https://github.com/deepchem/deepchem/blob/master/deepchem/models/__init__.py#L14 has the relevant import statement.

**Comment by pvskand** [comment]
@rbharath, even I am getting this error when I install `deepchem` using easy install via conda `conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.3.1 python=2.7`. I have checked the deepchem package in conda and there is no `fcnet.py` file in `deepchem/models/tensorgraph`. What could be the reason?

**Comment by lilleswing** [comment]
fcnet was moved after 1.3.1 from models.tensorflow_models.fcnet after 1.3.1.
It also used to be called TensorGraphMultiTaskClassifier.

Hopefully these issues will get better when we post docs from the stable cut version as well as master with the next cut (2.0.0).

**Comment by pvskand** [comment]
Okay so installing via the `scripts/install_deepchem_conda.sh` would install the latest one right?

**Comment by lilleswing** [comment]
yes

**Comment by pvskand** [comment]
@lilleswing, forgot to update : installing via `scripts/install_deepchem_conda.sh` worked. So basically easy install via conda installs the latest stable version and installing from the bash script installs from the source, shouldn't we mention it in the `README.md` regarding this?

**Comment by lilleswing** [comment]
Yes it seems like it is not clear enough in the README.md currently.  A PR for this would be lovely.

**Comment by rbharath** [comment]
Going to close this issue since it looks resolved. Feel free to re-open if necessary.

**Comment by altayg** [comment]
Hi, I got the same error message while running this tutorial: https://deepchem.io/docs/notebooks/solubility.html
I am using deepchem 2.1.1  on Python 3.5.

I changed the cell as follows and it seems to be working but not clear if correct as the results is diffrent than the output of the Cell 14 (no epocs printed). Can you confirm if this is correct or suggest a solution?

import numpy.random

params_dict = {"learning_rate": np.power(10., np.random.uniform(-5, -3, size=1)),
               "decay": np.power(10, np.random.uniform(-6, -4, size=1)),
               "nb_epoch": [20] }
n_features = train_dataset.get_data_shape()[0]
def model_builder(model_params, model_dir):
  model = dc.models.MultitaskRegressor(
    1, n_features, layer_sizes=[1000], dropouts=[.25],
    batch_size=50, **model_params)
  return model

optimizer = dc.hyper.HyperparamOpt(model_builder)
#best_dnn, best_dnn_hyperparams, all_dnn_results = optimizer.hyperparam_search(
#    params_dict, train_dataset, valid_dataset,dc.models.TensorflowMultitaskRegressor transformers,
#    metric=metric)

best_dnn, best_dnn_hyperparams, all_dnn_results = optimizer.hyperparam_search(
    params_dict, train_dataset, valid_dataset, transformers,
    metric=metric)
###
Fitting model 1/1
hyperparameters: {'decay': 1.3341860585631443e-05, 'learning_rate': 0.00020168470671811823, 'nb_epoch': 20}
W0823 11:13:18.857792 140242875389760 deprecation_wrapper.py:119] From /home/ga/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/models/keras_model.py:237: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

computed_metrics: [0.19827118512582909]
Model 1/1, Metric r2_score, Validation set 0: 0.198271
	best_validation_score so far: 0.198271
computed_metrics: [0.6237194379253364]
Best hyperparameters: (1.3341860585631443e-05, 0.00020168470671811823, 20)
train_score: 0.623719
validation_score: 0.198271

###
