### ISSUE TITLE
Removing test submodules from generated docs

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1087]
Looking at https://deepchem.io/docs/deepchem.html, many of the generated docs pages are for tests (for example, https://deepchem.io/docs/deepchem.feat.tests.html#module-deepchem.feat.tests.test_atomic_coordinates). These tests aren't really part of the public API for deepchem and shouldn't be placed prominently on the docs page. Is there a a good way we can remove these submodules from generated docs?

**Comment by dmoccia** [comment]
I do not have a ton of experience with Sphinx but looking around I think given that the Tests are not in one directory and are distributed throughout the framework (for instance models->tests, metrics->tests) you could annotate the exclude_patterns flag in the config.py file to explicitly ignore source directories.  Am I correct that tests are always kept in a "tests" directory?  If someone could direct me to the config.py file for generating the docs I would be happy to take a crack at this and figure out how to use Sphinx.

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/blob/master/docs/source/conf.py

**Comment by lilleswing** [comment]
for getting started I would look at the script in https://github.com/deepchem/deepchem/blob/master/devtools/jenkins/build_and_upload_docs.sh

This is the script we use to build the docs and the website.  You can test if your work is successful by looking at the website generated in your local tree.

```bash
cd {git_home}/website
python -m http.server
```

**Comment by dmoccia** [comment]
Great! Thank you!

**Comment by dmoccia** [comment]
Got this ready for submission, was pretty easy once I understood how sphinx operates.  For future reference in case anyone needs to exclude additional folders/files...

In the build script
https://github.com/deepchem/deepchem/blob/master/devtools/jenkins/build_and_upload_docs.sh

When you run sphinx-apidoc you generate a series of RST files for example:

deepchem.data.rst
deepchem.data.tests.rst

You cannot alter the generation of these for the codebase, Sphinx simply generates them;  however the sphinx-build command can be told to ignore certain RSTs.  

In the Sphinx config file located:
https://github.com/deepchem/deepchem/blob/master/docs/source/conf.py

There is a line
exclude_patterns = ['_build', '*tests*', '**.ipynb_checkpoints']

I have simply added '*tests*' to ignore those RSTs containing "tests"

I am ready to initiate a PR

**Comment by dmoccia** [comment]
I did not mean to submit that as a branch, let me know if you want me to delete that.

**Comment by rbharath** [comment]
@dmoccia Thanks for the summary and PR! Going to go ahead and close the issue since it looks to be fixed.
