### ISSUE TITLE
Why training by default starts from scratch, while evaluation/prediction does not?

### ISSUE THREAD

**Issue by simonfqy** [deepchem/deepchem#1093]
This could be more of a TensorFlow question. Please don't laugh at me if it is too simple.

In the `deepchem/models/tensorgraph/tensor_graph.py` script, in the documentation of the `fit_generator()` function, it says this for the `restore` parameter of the function: 

> restore: bool
      if True, restore the model from the most recent checkpoint and continue training
      from there.  If False, retrain the model from scratch.

https://github.com/deepchem/deepchem/blob/6f86377d9bff4541ff50ec014743d840a3e230f4/deepchem/models/tensorgraph/tensor_graph.py#L149

In the function, if `restore == True`, `self.restore()` is called.

And we can see that for the `predict_on_generator()` function in the same file, there is no need for calling `self.restore()` and the model predicts the output value given the input, using the most updated parameter values in the network. Why is this the case?

And I don't quite understand the `_enqueue_batch()` function and the `enqueue_thread` variable which is based on that. Maybe they have some roles to play in this?

Thanks for reading!

**Comment by lilleswing** [comment]
This is a documentation error.  When restore=False we simply do not restore the model.

TensorgGraph is a two step process
1) Construct the Graph
2) Build the Graph

Constructing the graph is done via TensorGraph.add_output(), TensorGraph.set_loss().

Before fitting we have to "build" the graph via TensorGraph.build().  This puts all of the ops in the Graph into a Tensorflow Session.  build() also calls  self.session.run(tf.global_variables_initializer()).   Restore restores all the variables from a checkpoint, but the graph is still computed via the same python mechanisms.

**Comment by peastman** [comment]
We changed some of this behavior a while back, and it looks like that docstring didn't get updated at the time.  Here's how it actually works.

1. When you first create a model, all its variables get initialized based on whatever initializers the layers specify.  (Actually this gets done in `build()`, which happens the first time you call any method that requires the graph.)

2. By default, `fit()` performs fitting starting from whatever values the variables currently have.  If this is the first call to `fit()` and you haven't done anything else to change them (like calling `restore()`), they'll have the values set by the initializers.  But you can override this behavior by specifying `restore=True`, in which case it will restore from the most recent checkpoint.

3. Usually you call `fit()` before `predict()`, so the model will already have the right variables.  But sometimes you run fitting, it saves the variables to a checkpoint, and then later (in a different run of the program) you want to do prediction.  In that case, call `restore()` before calling `predict()`.

There isn't a function to reset the variables to their initial values.  Usually it's easiest to just throw out the old model and create a new one.  But you could try this:

```python
with model._get_tf("Graph").as_default():
  model.session.run(tf.global_variables_initializer())
```

I haven't tried it, but it seems like it ought to work.

**Comment by simonfqy** [comment]
@peastman Thanks for your reply. It seems that it is related to #1094. Can you give a look at it? Thanks.
