### ISSUE TITLE
TensorGraph implementation of Junction Tree Variational Autoencoders

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1097]
There's been a lot of progress in generating graph structures from deep networks. The latest paper, "Junction Tree Variational Autoencoders" devises a clever approach which treats a molecular graph as a junction tree of subgraphs. This paper appears to be a major qualitative advance which always generates valid subgraphs.

I'd love to see an implementation in DeepChem. In addition to being useful, I think it will be a nice test for `TensorGraph` since the training procedure is complex.

CC @lilleswing

**Comment by lilleswing** [comment]
I'm not sure if this is a good first contribution as the paper is very complex IMO.

I started a different repo a week ago-ish for dev on the project.
https://github.com/lilleswing/jt-vae

So far I haven't even been able to do the junction tree decomposition to get the right number of fragments.  There are questions about how the author handles valences and attachment points to get the 780 number.

The DFS needed for the Junction Tree Decoder would be very hard to write in TensorGraph currently. 

After the reading the paper I am still not sure how the Graph Decoder works.

I agree that it is a major breakthrough -- but I don't think an implementation of this will be trivial.
If anyone wants to have a "fireside chat" over skype, or hangout about the paper let me know.  There are still many things I can't figure out and think it will require a team effort to reproduce.

**Comment by lilleswing** [comment]
Also I think the Junction Tree might have qsar reprocussions as a featurizer.  The paper shows how the latent space can contain more chemical information than previous latent spaces for molecules.

**Comment by lilleswing** [comment]
http://karlleswing.com/misc/dev_tree_decomp.html

**Comment by miaecle** [comment]
@lilleswing  Very interesting! My feeling is that the decomposition is not really chemistry based, but rather PGM based. A general tool used to decompose bayesian network and build junction tree might be helpful. Also this might be much more doable using pytorch, the tree decoder seems real complicated.

**Comment by lilleswing** [comment]
It basically decomposes into 4 parts.
1. Junction Tree Encoder
* This uses the algorithm in the synopses to decompose a molecule into a tree.  Then it uses a modified GRU and MPNN to an latent space of 28.  I can't figure out valences to get a language of 780.  When you take into account valences you get ~2k.  When you replace all aromatic bonds with single bonds you get ~ 260.  
2. Graph Encoder
* This operates on the full molecule graph with atoms as vertexes and edges as nodes.  This uses standard MPNN to a latent space of 28
3. Junction Tree Decoder
* This is a DFS w/ MPNN.  First step is determining if there is an additional child from the current node, it also determines the node type.  They do a feasibility Check during the tree dfs to only sample from possible children nodes.  I'm not sure how they do this feasibility check. and on top of that I'm not sure how they would make this differentiable.
4. Graph Decoder
* This is where things get really murky for me.  Given the fragments and the junction tree there are supposedly many different molecules that could be created.  I suppose this is from rotations of the fragments? How do you do the enumeration of all possible graphs in a differentiable way? 

Finally after the graph is decoded they enumerate all possible stereo-isomers, encode all of them into the graph latent space, and pick  the one with the lowest cosine distance to the original latent space graph encoding.  Yet again how to do this in a differentiable way?

**Comment by lilleswing** [comment]
@miaecle +1 to pytorch -- I think part of the magic of differentiability is solved through teacher forcing and computing things in cpu rdkit land.  This is heavily helped by pytorch's dynamic graph.

**Comment by rbharath** [comment]
@lilleswing Good point about this not being beginner friendly :). Agree that this paper is fascinating though. I think it would be big value add for us to get something like this integrated into DeepChem.

@miaecle @lilleswing Great points about PyTorch. This gets to the root of our longstanding TensorFlow-PyTorch debates. Although we stick with TensorFlow for software engineering needs, PyTorch just makes it easier to implement complex learning algorithms. Do you folks think `tf.eager` could be used instead of PyTorch for the implementation?

**Comment by rbharath** [comment]
PS: I think this paper would be a great topic for the next steering committee meeting

**Comment by lilleswing** [comment]
[single_bond_only.csv.txt](https://github.com/deepchem/deepchem/files/1738171/single_bond_only.csv.txt)

Although I do find it interesting/cool using their decomposition and then removing aromaticity that there are only ~260 building blocks for 250k molecules.

**Comment by rbharath** [comment]
Turns out the team that wrote this paper has already open-sourced a PyTorch implementation! https://github.com/wengong-jin/icml18-jtnn

**Comment by rbharath** [comment]
Closing this issue since we're moving away from TensorGraph
