### ISSUE TITLE
Link in README.md broken

### ISSUE THREAD

**Issue by pvskand** [deepchem/deepchem#1100]
The link of `Direct from Source` in the installation section is broken. 
Can't simply running `python setup.py install` work?

**Comment by lilleswing** [comment]
It requires a bunch of dependencies (all of the ones in scripts/install_deepchem_conda.sh)

We should remove the link altogether from the readme (as using a conda environment is actually installing from source)

**Comment by pvskand** [comment]
Merged via [PR-#12](https://github.com/deepchem/deepchem/pull/1101), hence closing this issue,
