### ISSUE TITLE
Generalized Splits

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#111]
Right now, splits are only on "scaffold" and "random". We should make this OOP style so users can specify new types of splits (like MolecularWeight).

**Comment by joegomes** [comment]
@rbharath this is something I'm interested in doing.  My idea is to split the dataset to train on low MW (small water clusters) and predict on high MW (large water clusters).  I've tried using the scaffold split to accomplish this based on SMILES strings but it crashes on my dataset.  Is this the intended use of scaffold?

**Comment by rbharath** [comment]
@joegomes The generalized splits class (`Splitter`) was added in #151 . Could you make a PR that adds a `MolecularWeightSplitter`? This should be easy to do (copy the style of `RandomSplitter` and others).

**Comment by joegomes** [comment]
@rbharath Thanks for getting this in!  I'll plan on adding the MW splitter later today in a new PR

**Comment by rbharath** [comment]
Addressed in #151, #157.
