### ISSUE TITLE
DeepChem Dataset Tutorial

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1110]
There have been a lot of questions recently about DeepChem datasets. This highlights the fact that we don't have a good introductory reference tutorial for datasets. I think it would be a great idea to put together a tutorial for `dc.data.Dataset`. This tutorial could cover:

- How to wrap `X, y, z` arrays as `NumpyDataset` objects
- How to extract `X, y, z` arrays from `Dataset` objects
- How to iterate over `(X, y, z)` tuples from a `Dataset`
- How to convert back and forth between `DiskDataset` and `NumpyDataset`
- How to load large datasets with `DiskDataset`. The meaning of shard-size and how to set it correctly.
- How to convert between `tf.data` and `Dataset`

There are a lot of topics here, but even covering some of them would be a great topic for a tutorial.

**Comment by leeyjjoel** [comment]
Hi @rbharath, can I take this issue?

**Comment by pvskand** [comment]
@rbharath 1) I think having 2 tutorials : one for `NumpyDataset` and another for `DiskDataset` is a better option since there is a lot to explain in detail in DiskDataset expecially. We can club other Dataset Methods in the NumpyDataset tutorial. 
2) A query about the data to be used in NumpyDataset. I initially thought to load a random numpy matrix (say of 10x10) for the tutorial but later thought that using a real data set (say for example the MNIST data or any other data) would also be a good option. What do you say?

**Comment by rbharath** [comment]
@pvskand I think two tutorials, one for `DiskDataset` and another for `NumpyDataset` sounds like a good idea. I think using a random matrix for the `NumpyDataset` tutorial is probably fine. The goal is mainly to show off the API. But, if you think using MNIST would really make the tutorial work better, that would be good as well.

@leeyjjoel @pvskand We'll figure out good protocols for splitting up issues when there's interest from multiple contributors. For now, @pvskand, since it sounds like you have ideas about the `NumpyDataset`, want to take that on? @leeyjjoel if you're interested, would love your contributions on a tutorial for `DiskDataset` usage.

**Comment by pvskand** [comment]
@rbharath, yes even i was thinking of that to split up the issue and collaborate. I am happy to take up NumpyDataset. Will send a PR soon for it.
And yes, I personally believe that using the MNIST example along with generating  random matrix would be a better tutorial. Although both would be similar but would make it clear enough for a newbie.

**Comment by rbharath** [comment]
@pvskand Great, that sounds like a good plan. Looking forward to your PR!

**Comment by leeyjjoel** [comment]
@rbharath  Sounds good to me. Will work on the tutorial for DiskDataset usage.

@pvskand  looking forward to working with you

**Comment by vsag96** [comment]
Is this still a requirement?

**Comment by rbharath** [comment]
Yes, I think this would be a nice addition! I'd recommend adding on directly to the existing `NumpyDataset` tutorial to make a good general `Dataset` tutorial https://deepchem.io/docs/notebooks/Deepchem_NumpyDataset_tutorial.html

**Comment by rbharath** [comment]
We do have a basic dataset tutorial so I'm going to go ahead and close this old issue.
