### ISSUE TITLE
Feature Request: Having a split=None option for load_function

### ISSUE THREAD

**Issue by ankitvgupta** [deepchem/deepchem#1115]
Is it possible to add the ability to pass split=None to the load_function datasets? It would be nice to just call, for example, `load_delaney(featurizer="ECFP", split=None)`, and have the function return the entire dataset as opposed to the train/valid/test split one.

**Comment by rbharath** [comment]
Yes, this is a great idea! We should have thought about this earlier. I've marked this as a good first contribution for newcomers.

**Comment by lilleswing** [comment]
Do we like better 
``` python
Returns
  -------
  tasks: list<str>
    List of tasks for the daataset
  datasets: tuple(dc.data.Dataset)
    len(3) for train, valid, test
  transformers: list<dc.trans.Transformer>
```
In this case we would return (dc.data.Dataset, None, None) for the middle object of the return tuple.
or 

``` python
Returns
  -------
  tasks: list<str>
    List of tasks for the daataset
  datasets: tuple(dc.data.Dataset)
    len(3) for train, valid, test
    if split==None return a single dataset with all the samples
  transformers: list<dc.trans.Transformer>
```

**Comment by ankitvgupta** [comment]
I like the former since it would mean less code changes for existing users. But can make either work!

**Comment by lilleswing** [comment]
There are still bugs in the implementation of this.

None can not be automatically be coerced into a string.  We have to go through all the load functions and cast None to a string when creating the save_dir variable.

**Comment by nitinprakash96** [comment]
@lilleswing I'll open up a PR for this.

**Comment by rbharath** [comment]
This has been implemented I believe
