### ISSUE TITLE
GPL license

### ISSUE THREAD

**Issue by ankitvgupta** [deepchem/deepchem#1120]
https://github.com/deepchem/deepchem/blob/e8a77b2d645683eff13f31272515ba602fd48f51/deepchem/feat/fingerprints.py#L10

Is this supposed to be a GPL license?

**Comment by peastman** [comment]
It's supposed to be MIT.

**Comment by ankitvgupta** [comment]
Ok cool looks like ~5 files are labeled at GPL. Can those all be changed? Happy to make a PR sometime that does that.

**Comment by rbharath** [comment]
Yes, agreed, let's see if we can change these over.

@skearnes, @joegomes It looks like you folks are listed as authors on these files. Would you be OK with us switching them to MIT license to match the rest of DeepChem?

**Comment by joegomes** [comment]
I agree, thanks!

**Comment by rbharath** [comment]
Thanks @skearnes and @joegomes for quick responses!

@ankitvgupta PRs now wlecome!

**Comment by ankitvgupta** [comment]
PR is here: https://github.com/deepchem/deepchem/pull/1123
