### ISSUE TITLE
TensorFlow 1.6.0 Version Bump

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1126]
https://github.com/tensorflow/tensorflow/releases/tag/v1.6.0

TensorFlow 1.6 has just been released. We should upgrade the DeepChem HEAD dependency.

**Comment by snagpal93** [comment]
Hi @rbharath!

What exactly is needed for this bugfix? I am assuming building against TF 1.6 and successfully running all tests and then updating the docs?

Thanks!

**Comment by lilleswing** [comment]
Yep -- bumping to tensorflow 1.6.0 in scripts/install_deepchem_conda, then updating the readme.
