### ISSUE TITLE
Tutorial Demonstrating using TensorGraph layers with TensorFlow Eager

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1127]
[TensorFlow eager](https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html) has been out as `tf.contrib.eager` since TensorFlow 1.5. It would be great to add a tutorial that demonstrates how TensorGraph layers can be used with TensorFlow eager. This would be a great first contribution for a newcomer to the library and would add a lot of value to the community.

Here are the steps needed to submit this PR:

- As with our other tutorial, this one should be an IPython notebook added to the folder https://github.com/deepchem/deepchem/tree/master/examples/notebooks
- Explain how to construct a TensorGraph layer with a few examples. For example
  - `dense_layer = Dense(5)`
- Explain that constructing the layer doesn't actually perform any tensor ops. This is done when `create_tensor()` is called. 
  - `dense_layer.create_tensor(in_layers=[input])`
- Note that as syntactic sugar, layer.create_tensor can be invoked via `__call__()`
  - `Dense(5)(input)` has the same effect as the function call above
- Provide an example of using the function invocation style with TensorFlow eager code. For example, something like the following code snippet.
```
import tensorflow as tf
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution()

x = [[2.]]
out = Dense(3)(x)
print(out)
```
- Demonstrate how to take gradients of eager code that uses TensorGraph layers.

If you're interested in implementing this tutorial, please make a comment on this thread and raise an issue marked [WIP] that tracks your in-progress implementation.

**Comment by peastman** [comment]
Does this actually work?  If so, that's really cool.  Though I suspect "write a tutorial" will turn into "discover lots of edge cases that don't work correctly, which we can then figure out ways to fix."  But it definitely sounds like something we want to support.

**Comment by nitinprakash96** [comment]
Hi @rbharath , can I take up this one. Will help me in getting more insight into TensorGraphs :)

**Comment by rbharath** [comment]
@nitinprakash96 Yep, go for it! Could you open a [WIP] pull request so we can help you with it?

@peastman It should work in principle :). In practice, as you suggest, I think we'll discover lots of bugs. But I think layers + tf eager is the API that's actually going to stick in the long run, so we definitely want to put in this time

**Comment by peastman** [comment]
Agreed.  We may also want to add methods to TensorGraph to apply the entire graph all at once.

**Comment by rbharath** [comment]
Closing this old issue for cleanup
