### ISSUE TITLE
Questions about Hindsight Experience Replay defaults

### ISSUE THREAD

**Issue by kastnerkyle** [deepchem/deepchem#1129]
Following up on https://twitter.com/rbhar90/status/970075142586974208 - am I reading the documentation right, in that k=2 for the default in HER? Is there a particular reason for this (the paper prescribes 4, but it is a very different task)? An experiment where k=2 worked much better?

I am looking at using HER in a very different scenario than the paper (music generation in my case) so I was intrigued by how it is used in deepchem. Thanks

**Comment by rbharath** [comment]
CC @peastman

**Comment by peastman** [comment]
Sorry, I'm not sure what you're referring to.  What is k?

**Comment by kastnerkyle** [comment]
In the paper, k is the number of "false state/goals" that are introduced during HER, relative to the "true" goals. They talk about the importance of the choice for k in section 4.5 of the paper https://arxiv.org/abs/1707.01495 , and specifically prescribe k=4. I've been looking around at various implementations, and yours is the first I saw for something that wasn't the same experiments as the paper. So I figured I would ask about the differences/how HER came to be used in deepchem, and why the defaults seem different (it looks like k=1 or possibly 2, based on this comment https://github.com/deepchem/deepchem/blob/e20c14513ffccb8883a84aa1ef908a9c9c5ea576/deepchem/rl/a3c.py#L91, but maybe I am just reading the code wrong)

**Comment by peastman** [comment]
You're reading it correctly.  That setting doesn't really apply to A3C.  All of the methods they consider involve a replay buffer, so they're free to take whatever set of states and goals they want from the buffer.  But A3C doesn't have a replay buffer.  It just generates a rollout, processes it exactly once, and then throws it away.  When using HER, we process it a second time using the alternate goal.

**Comment by kastnerkyle** [comment]
I see, this sounds like something I will probably try on my task. Thanks for the clarification, and for the great work on deepchem!
