### ISSUE TITLE
Remove "TensorGraph" from model names 

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1138]
It might be good to rename our `dc.model.GraphConvTensorGraph` to `dc.models.GraphConv` since all our deep models now use TensorGraph.

**Comment by lilleswing** [comment]
We should make both names work until the next major cut.  Lots of code depends on that name.

**Comment by rbharath** [comment]
Yes, we should definitely have a deprecation cycle on the old name.

**Comment by rbharath** [comment]
In addition, we should rename WeaveTensorGraph, DTNNTensorGraph, DAGTensorGraph, PetroskiSuchTensorGraph, MPNNTensorGraph as well.

**Comment by mlgill** [comment]
I am working on renaming `dc.model.GraphConvTensorGraph` to `dc.models.GraphConv` right now.

Here is the [branch](https://github.com/mlgill/deepchem/tree/issue1138_mg_GraphConvTensorGraph_to_GraphConv).

**Comment by mlgill** [comment]
@rbharath @lilleswing I've just noticed that there is also a layer called [GraphConv](https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/layers.py#L2311). Having a model and layer with the same name seems like a bad idea to me. What do you think? 

Maybe the renamed model should be called `dc.model.GraphConvModel`? Of course this raises the question of what to call the other renamed models. 

Making a to-do to get back to this once we've discussed.

**Comment by lilleswing** [comment]
I like the idea that our models have one of three post-fixes
(Model, Regressor, Classifier)

Classes with the Model prefix must take a "mode" arg which specifies if the model is classification or regression.

**Comment by mlgill** [comment]
@lilleswing I think that makes sense. In this case, the proposed GraphConvModel already takes a mode for regression/classification, as well. I will plan to do that unless @rbharath has other ideas. Should get some time over the weekend to work on this.

**Comment by rbharath** [comment]
We talked it over and decided that @lilleswing's proposal of adopting (Model, Regressor, Classifier) postfixes make sense. We're going to adopt it for naming broadly.

@mlgill Please feel free to go for it. Thanks for taking on the PR!

**Comment by mlgill** [comment]
@rbharath @lilleswing OK, I have updated just the `GraphConvModel` class. The CI build is still running, but everything has been committed [here](https://github.com/deepchem/deepchem/pull/1167). Feedback welcome.

I'm happy to take on additional renaming tasks in this issue (perhaps one at a time) if you're interested. I'll update with a pull request once I've started a task in case others want to take them on in the meantime.

**Comment by lilleswing** [comment]
This PR can serve as an example for how to rename future models.
https://github.com/deepchem/deepchem/pull/1167

**Comment by mlgill** [comment]
I am now working on renaming `WeaveTensorGraph` to `WeaveTensorModel`. WIP pull request [here](https://github.com/deepchem/deepchem/pull/1177). 

If you'd prefer that I do multiple renames all at once (to minimize email/traffic) let me know.

**Comment by peastman** [comment]
I think that should just be "WeaveModel".

**Comment by rbharath** [comment]
@mlgill Awesome, thanks for taking this on! I also like `WeaveModel` for simplicity.

**Comment by mlgill** [comment]
OK, I've used WeaveModel. This should be ready and I've yapfed the files. There is a trivial merge conflict. I haven't resolved because I don't know if I'm supposed to be doing that.

**Comment by mlgill** [comment]
I am fixing the remaining TensorGraph model names [here](https://github.com/deepchem/deepchem/pull/1181):

```
DTNNTensorGraph --> DTNNModel
DAGTensorGraph --> DAGModel
PetroskiSuchTensorGraph --> PetroskiSuchModel
MPNNTensorGraph --> MPNNModel
TextCNNTensorGraph --> TextCNNModel
```

**Comment by rbharath** [comment]
@mlgill Awesome, thanks for taking this on!

**Comment by mlgill** [comment]
Have moved the deprecation warning to the constructor method, per [this](https://github.com/deepchem/deepchem/pull/1181#issuecomment-376938610) issue, in the pull request [here](https://github.com/deepchem/deepchem/pull/1196).

**Comment by mlgill** [comment]
If there are any remaining models to be renamed let me know. Otherwise I will assume everything is complete here.

**Comment by rbharath** [comment]
@mlgill I think that's everything. Thanks for the contributions!

Going to go ahead and close this issue.
