### ISSUE TITLE
ProgressiveMultitaskClassifier intox21_tf_progressive.py

### ISSUE THREAD

**Issue by skeinan** [deepchem/deepchem#1144]
Hi guys,
In "tox21_tf_progressive.py":
There is no ProgressiveMultitaskClassifier, maybe you meant "ProgressiveMultitaskRegressor"?
Thanks,
Shahar

**Comment by rbharath** [comment]
@skeinan Good catch! The Tox21 is a classification task, so we need to use a classifier.

@miaecle Would it be hard to add a `ProgressiveMultitaskClassifier`? If so, we might want to consider just removing the example.

**Comment by miaecle** [comment]
@rbharath I think it will be pretty straightforward, I could help with it(though we haven't applied the model on any classification tasks before)

**Comment by rbharath** [comment]
Closing since implemented by #1151
