### ISSUE TITLE
Is there any limit to the size of the molecule in WeaveTensorGraph?

### ISSUE THREAD

**Issue by simonfqy** [deepchem/deepchem#1148]
In the paper (Kearnes et al., 2016) which proposes the Molecular Graph Convolution with Weave modules, there is a sentence saying: 

> Our current implementation imposes an upper limit on the number of heavy atoms represented in the initial featurization. For molecules that have more than the maximum number of atoms, only a subset of atoms (and therefore atom pairs) are represented in the input encoding.

However, I examined `deepchem/feat/graph_features.py` and class `WeaveTensorGraph` in `deepchem/models/tensorgraph/models/graph_models.py`, I couldn't find any such restrictions from the source code. So in the Weave featurizer in your implementation, is there any limit to the number of heavy atoms in the molecules? Thanks.

**Comment by lilleswing** [comment]
No there are no hard-coded limitations of our current Weave Featurizer.  

This is because we featurize using an edge list and membership tensor vs a 3 dimensional tensor with masking.

**Comment by lilleswing** [comment]
(that is my guess for why the initial paper had a limit for max number of heavy atoms)

**Comment by rbharath** [comment]
Going to close since I believe the question has been addressed.
