### ISSUE TITLE
Designing API for pretrained/application models in DeepChem

### ISSUE THREAD

**Issue by pvskand** [deepchem/deepchem#1154]
Since there are many networks/architectures coming up whose pretrained models are expected to be shipped to DeepChem soon, I was thinking of having a `dc.pretrained` or `dc.applications` like that of `keras.applications` - https://keras.io/applications/ in which we would dispatch a model whose pretrained model is intended to be use for the drug and in turn the DeepChem community. This was a high-level idea that I had got. Please do let me know about your thoughts.

**CC :** @lilleswing, @peastman, @rbharath, @miaecle

**Comment by lilleswing** [comment]
So all of our prebuilt models are the equivalent of things in keras.applications.

The way they handling loading in pretrained weights is in the constructor of the model
```python
model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=True)
```
This seems as good as any way to handle it.

The question I have is what do people expect to do with these pretrained weights besides run the models as is?  My thoughts

1) Freeze layers for transfer learning
2) Add Additional Tasks
3) Combine Latent Layer with another model as a feature.

This is all theoretically possible (see test_graph_models.change_loss_function) but we probably want to make all three easier to do and have tutorials for them.

Are there any other use cases I am missing?

**Comment by pvskand** [comment]
Regarding why pretrained weights are used you are right @lilleswing. They either use it as feature extractor or use it for finetuning the last layers (by keeping initial layers freezed) or might use the complete network as the initialized weights instead of random initialized weights for faster convergence.

Btw, do we have any pretrained model as of now in DeepChem?

**Comment by lilleswing** [comment]
We no longer have any pretrained models in DeepChem.  For a while we were shipping the Asperu-Guzik autoencoder but stopped.

**Comment by rbharath** [comment]
Building off the discussion in #1152, I think we probably want to ship pretrained image models, perhaps the same set that Keras does. Shipping the pretrained Aspuru-Guzik autoencoder would add value as well I think. We could eventually add on a Junction tree variational autoencoder model (or more advanced molecular autoencoders).

**Comment by rbharath** [comment]
@lilleswing The `include_top` option sounds good to me. We probably want to just write a nice tutorial about how to use it.

**Comment by rbharath** [comment]
Copying over notes from our steering committee meeting (will be posted on blog soon):

> Adding in support for pretrained weights makes sense at a high level, but many design decisions remain to be worked out. For image models, reusing weights from Keras with some machinery to do variable renaming seems like a good path. For chemistry-specific models like Aspuru-Guzik encoder, will need to store our own weights. Details to be decided on github. We will probably want to support some type of fine-tuning as well, along the lines of the "include_top" flag.

**Comment by pvskand** [comment]
>  For chemistry-specific models like Aspuru-Guzik encoder, will need to store our own weights.

@rbharath , why our own weights? Any specific reason. I guess the weights here can be stored in the keras format. (to maintain consistency)

**Comment by lilleswing** [comment]
I believe @rbharath was mearly stating that we would want to store the weights in our own infrastructure for safe-keeping and testing, not a hard statement of the formats of the weights.  We don't want to pin our code working to moving target github repos or things that might disappear as much as possible.

**Comment by pvskand** [comment]
Aah. I See. I got it.

**Comment by rbharath** [comment]
I'm closing this old discussion for now.
