### ISSUE TITLE
Remove GraphGather pin to CPU on upgrade to TF 1.6

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1157]
The bug requiring us to pin to CPU is fixed in tf 1.8

https://github.com/tensorflow/tensorflow/issues/16872#issuecomment-368016454

https://github.com/deepchem/deepchem/pull/1081

**Comment by rbharath** [comment]
I think this will be fixed in tf 1.6 according to the comment in this issue: https://github.com/tensorflow/tensorflow/issues/17106

**Comment by lilleswing** [comment]
yep apparently CUB is not versioned the same as tensorflow.  Title updated.

**Comment by rbharath** [comment]
Now that #1165 is merged in, I'm marking this issue open for contribution. This issue should be a good first contribution for beginners. You will need to remove the CPU pin (https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/layers.py#L2492) from the `GraphGather` layer and submit a pull request. Please leave a note here if you're interested in taking this issue on.

**Comment by souravsingh** [comment]
Interested in working on this.
