### ISSUE TITLE
Standardizing on spelling "Multitask" rather than "MultiTask"

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1162]
We have some inconsistent spelling with some models being named "Multitask" and others "MultiTask." Let's standardize on "Multitask" so APIs are consistent.

**Comment by rbharath** [comment]
I'm marking this a "Good First Contribution". If you'd like to implement this feature, please leave a comment here and raise a pull request marked "[WIP]" tracking your progress.

You will need to go through the repository and change all the spellings of "MultiTask" to "Multitask." Since this is a breaking change, you will need to make sure that the old name still works and issues a deprecation warning that we will remove the spelling at the next major release. This can likely be done by creating a stub subclass of the renamed class with the old naming that issues the warning then calls the superclass constructor.

**Comment by souravsingh** [comment]
@rbharath I am interested in working on this.

**Comment by rbharath** [comment]
@souravsingh Could you open a pull request marked "WIP" that tracks your on-going implementation progress? You should be able to use #1167 as a template for how to make the renaming change.
