### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nn' in MNIST GAN tutorial

### ISSUE THREAD

**Issue by lannguyencs18** [deepchem/deepchem#1166]
Hi! While I was trying to run the MNIST GAN tutorial on my jupyter notebook, I found this error: 

in create_discriminator(), 
        conv = layers.Conv2D(num_outputs=32, kernel_size=5, stride=2, 
                    activation_fn=dc.nn.model_ops.lrelu(0.2), normalizer_fn=tf.layers.batch_normalization, 
                    in_layers=data_inputs)
        AttributeError: 'module' object has no attribute 'nn'

The problem was one of the arguments in layers.Conv2D(), which was 
activation_fn=dc.nn.model_ops.lrelu(0.2)

I searched through the source code and modified it to be 
activation_fn=dc.models.tensorgraph.model_ops.lrelu(0.2)

It was able to compile and run. However, the result looked a bit terrible so I am not sure if this was the right function to set up for activation_fn.  Would you mind letting me know the right way to fix it? 

![mnistgan](https://user-images.githubusercontent.com/12010330/37563313-5616184a-2a54-11e8-8a11-88e7be9f43b6.png)

**Comment by peastman** [comment]
The results are random, so it'll be different every time you run it.  Sometimes it converges to a generator that only produces 1s.  Other times you get 7s and 9s.  I've occasionally seen it produce a mix of 3, 5, and 8.  Try running it a few times.

**Comment by rbharath** [comment]
@lannguyencs18 Good find on the naming issue! 

Fixing the GAN tutorial in the way indicated above would be a good first contribution. Is someone is interested in taking on the fix, please leave a note here.

**Comment by NichitaDiaconu** [comment]
Hello, I reran the whole the notebook with activation_fn=dc.models.tensorgraph.model_ops.lrelu(0.2) . Removed all the irrelevant .ipynb generated things as @peastman suggested. I also made a pull request #1174
