### ISSUE TITLE
SeqToSeq Tutorial

### ISSUE THREAD

**Issue by mehmettan** [deepchem/deepchem#1168]
Hi everyone, 

I am a new user of deepChem and trying to reproduce the results on seq2seq tutorial under examples/notebooks. However no matter what I do, I can not reproduce the results given here. I am executing the whole notebook as it is, don't get any errors, but the results are not even close. I get much larger autoencoder errors and so none of the compounds can be exactly decoded. Is there something missing in the tutorial? 

Best,

**Comment by mehmettan** [comment]
Below is the output. With this, only 80 out of 500 validation compounds can be exactly reproduced. In tutorial it is like 363. 

>>>model.fit_sequences(generate_sequences(40))
2018-03-19 15:25:47.440144: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-03-19 15:25:47.548620: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-19 15:25:47.548925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.797
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.08GiB
2018-03-19 15:25:47.548942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-19 15:25:47.737619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6832 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Ending global_step 999: Average loss 96.5865
Ending global_step 1999: Average loss 78.3183
Ending global_step 2999: Average loss 63.2105
Ending global_step 3999: Average loss 53.9386
Ending global_step 4999: Average loss 47.5207
Ending global_step 5999: Average loss 43.5996
Ending global_step 6999: Average loss 39.012
Ending global_step 7999: Average loss 35.7498
Ending global_step 8999: Average loss 32.5969
Ending global_step 9999: Average loss 30.1271
Ending global_step 10999: Average loss 27.6893
Ending global_step 11999: Average loss 25.4496
Ending global_step 12999: Average loss 23.9029
Ending global_step 13999: Average loss 22.3889
Ending global_step 14999: Average loss 21.1419
Ending global_step 15999: Average loss 19.8992
Ending global_step 16999: Average loss 19.2158
Ending global_step 17999: Average loss 18.0662
Ending global_step 18999: Average loss 17.3361
Ending global_step 19999: Average loss 16.8842
Ending global_step 20999: Average loss 15.9874
Ending global_step 21999: Average loss 15.5651
Ending global_step 22999: Average loss 15.4481
Ending global_step 23999: Average loss 14.6937
Ending global_step 24999: Average loss 14.4314
Ending global_step 25999: Average loss 14.1688
Ending global_step 26999: Average loss 14.1544
Ending global_step 27999: Average loss 13.7362
Ending global_step 28999: Average loss 13.505
Ending global_step 29788: Average loss 13.4971
TIMING: model fitting took 4058.758 s

**Comment by lilleswing** [comment]
So I reran it this morning on latest master and got 378 of 500 reproduced.

![selection_106](https://user-images.githubusercontent.com/1225605/37602902-c27dc2ac-2b63-11e8-911f-85819eb4da37.png)

Have you run it multiple times?  Are you always getting these types of results?

**Comment by mehmettan** [comment]
Yes, I ran multiple times, similar results.

**Comment by tanlab** [comment]
I also tried to install from source using conda. However, after the installation, I get the following error when trying to execute _dc.molnet.load_muv() :_ 

ImportError : No module named 'pandas.indexes'

**Comment by mehmettan** [comment]
To try the latest version, I installed from the source with conda. However, this time I get the following error when executing _dc.molnet.load_mv()_:

ImportError : No module named 'pandas.indexes' 

Should I install another version of pandas?

**Comment by mehmettan** [comment]
I managed to solve the problem with the latest version. The last problem I wrote above is due to the existance of the old muv files. When I upgrade to the latest version of deepchem, such errors occured. I removed the old files, the problem is gone. Thanks,
