### ISSUE TITLE
label masking for missing data in multitask models

### ISSUE THREAD

**Issue by davidwhealey** [deepchem/deepchem#1175]
I'm working with the ToxCast data set packaged in deepchem, of which the majority of the labels are NaNs, presumably because of sparse coverage of the assays.  When examining the resulting deepchem dataset, it seems like the NaNs have been filled with zeros.  Replacing NaNs with zeros without masking during training and evaluation may drastically overestimate the predictiveness of the model. Is there a place in the code where auc is evaluated only on nonmissing labels, and/or the loss for missing labels is masked during training?

**Comment by peastman** [comment]
This is done with the weights matrix.  Any element corresponding to a missing measurement should have a weight of 0.
