### ISSUE TITLE
Ability to reload long-running analysis notebooks

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#118]
Deepchem analysis is now often done in an ipython notebook. Unfortunately, notebooks often crash (or the GPU node on which the notebook runs is shut down), so analysis has to be painstakingly rerun. It would be nice to have the ability to reload previously done analysis. I think this should be doable if

1. We move away from using temporary directories in the examples.
2. All deepchem objects support a `reload` flag. If `reload == True`, then the object should check if the corresponding directory on disk exists and reload if it does.

**Comment by joegomes** [comment]
@rbharath Definitely ran into this a few times, I think this would be a great feature to add

**Comment by rbharath** [comment]
As an update, some partial support for a `reload` flag was added, but it looks now as if `reload` is buggy (see #148). We need to add some integration testing for `reload`.

**Comment by rbharath** [comment]
As another addendum, the `Transformer` objects don't play nicely with `reload`. As they currently stand, `Transformer` objects don't have memory or storage. As a result, there's no good way to know when a `Transformer` has already been applied to a dataset. Perhaps it's now necessary to store `Transformers` on disk so `reload` can choose not to reapply transformations?

**Comment by rbharath** [comment]
I think the `reload` feature is mostly stable now. Going to close this. Can describe any other problems that come up in follow-on issues.
