### ISSUE TITLE
SDF loader should load tasks from SDF File

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1185]
Right now we need a side car file *.sdf.csv that is aligned with the sdf file

If the file does not exist we should look for the "tasks" as properties in the SDF file itself.  If the property does not exist we should return None.

**Comment by lilleswing** [comment]
This is something that frequently confuses beginners.

**Comment by mlgill** [comment]
I just developed code to read the secondary properties from an SDF file for a project at work. So I can take this on this week or over the coming weekend.  

To make sure I'm clear -- is it desirable to only read from the SDF file or should the ability to read a CSV as an alternative be preserved (albeit with tighter integration in the function call and docstrings)?

Finally, I'd love to get opinions on storing the extra properties. Specifically, do we want to assume they're all tasks for the sake of simplicity? In my situation, that wasn't the case so I called them "properties" and will probably have to write a hook to separate things out between features and tasks. Unfortunately,  this option will introduce another level of complexity, of course.

**Comment by rbharath** [comment]
@mlgill Awesome, glad to hear you're taking this on.

I think we will want to preserve the CSV reading as an alternative for backwards compatibility. 

Good point that extra properties may not all be tasks. If it's not too painful, supporting features and tasks would be useful I suspect.

**Comment by rbharath** [comment]
I think this functionality was added in #1447 so going ahead and closing this old issue.
