### ISSUE TITLE
Adding tests for graph layers

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1186]
The layers in `dc.models.tensorgraph.layers` have a useful collection of unit tests in https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tests/test_layers.py. These tests typically assert that the output of each layer has the correct shape.

However, the layers in `dc.models.tensorgraph.graph_layers` lack equivalent tests. This issue coordinates the construction of these tests. Tests will need to be added for the following layers:

- [ ] WeaveLayer
- [ ] WeaveGather
- [ ] DTNNEmbedding
- [ ] DTNNStep
- [ ] DTNNGather
- [ ] DTNNExtract
- [ ] DAGLayer
- [ ] DAGGather
- [ ] MessagePassing
- [ ] EdgeNetwork
- [ ] GatedRecurrentUnit
- [ ] SetGather

To contribute to this issue, take the following steps:

- Create a new file `deepchem/models/tensorgraph/tests/test_graph_layers.py`
- Pick one or more of these layers. Figure out what the expected shapes of the outputs of the layers are. Add unit tests invoking the layer on suitably sized input tensors and testing that the outputs have the desired shape.

If you'd like to contribute to this issue, please leave a comment here with the layers you'd like to add tests for and start a pull request marked "[WIP]".

**Comment by peastman** [comment]
Just checking the shape of the output is a long way from being a sufficient test.  It's unfortunate that many of our existing tests don't do anything more than that.  We should try to improve them with time.  For new tests, though, we really should try to do better.  A test should verify that the output is correct, not just that it has the right shape.

**Comment by souravsingh** [comment]
@rbharath I am willing to take a stab at the issue.

**Comment by rbharath** [comment]
@peastman Good point. What are some good additional tests we could add to check functionality?

@souravsingh Want to pick one layer to start? This is going to be a big set of changes. Thanks!

**Comment by peastman** [comment]
The ideal situation is if you can create a very simple case where you know exactly what the correct output should be.  Then you can check for the exact output you were expecting.

**Comment by abster12** [comment]
are there any usage examples that are present for these layers?

**Comment by peastman** [comment]
These layers get used by the models in graph_models.py (https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/models/graph_models.py).

**Comment by abster12** [comment]
will the parent class inherit from ```unittest.TestCase``` or I will have to use some other class for the tests?

**Comment by peastman** [comment]
It's best to subclass `tensorflow.python.framework.test_util.TensorFlowTestCase`.  It simplifies using TensorFlow in tests.  Look at test_layers.py (https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tests/test_layers.py) for an example.

**Comment by rbharath** [comment]
I believe most of these tests have been added so closing
