### ISSUE TITLE
MPNN Edge Network Implementation

### ISSUE THREAD

**Issue by WesleyyC** [deepchem/deepchem#1188]
For the Edge Network in MPNN, the paper is doing A x h, but the implementation is doing elementwise product with broadcasting and has to do a reduce sum to get the right size:

https://github.com/deepchem/deepchem/blob/281a1e050ac5ef7ce4c8d481a96c44e8816e88c6/deepchem/models/tensorgraph/graph_layers.py#L928

I think a batch mode matmul makes more sense. Therefore, to replace this line:

```python
out = tf.squeeze(tf.matmul(self.A, out), axis=2)
```

I have the fix ready and would be happy to create a PR if this makes sense to you guys.

**Comment by miaecle** [comment]
@WesleyyC Hi, thanks for raising the issue! Since `tf.matmul` supports this kind of operation, I totally agree with this change. Please feel free the initialize a PR!

**Comment by WesleyyC** [comment]
@miaecle please see the PR. Thanks!

**Comment by WesleyyC** [comment]
Fix is merged
