### ISSUE TITLE
Where to find the chosen hyperparameter?

### ISSUE THREAD

**Issue by WesleyyC** [deepchem/deepchem#1192]
I am trying to reproduce some of the benchmarks on Molnet. Do you know where I can find the optimal hyperparameters used to generate the benchmark? I have tried the follow the code in example but still not able to get to the listed result.

Thanks!

**Comment by miaecle** [comment]
@WesleyyC Hi, the download link for hyperparameters is in the docstring of `benchmark.py`
http://deepchem.io.s3-website-us-west-1.amazonaws.com/trained_models/Hyperparameter_MoleculeNetv3.tar.gz

**Comment by WesleyyC** [comment]
Awesome, this is super helpful. Thanks! @miaecle
