### ISSUE TITLE
AttributeError: 'module' object has no attribute 'utils'

### ISSUE THREAD

**Issue by DJDrennan** [deepchem/deepchem#1197]
I'm in ipython, working through my first tutorial -Graph Convolutions For Tox21. When I get to the line to import deepchem as dc, it expands and does a lot of things, and gives me what looks like an error on importing numpy as np. However, if I type import numpy as np, it works fine. if I backup to the previous line, import deepchem.utils.rdkit_util as rdkit_util, and try that by itself, I get the same error that it has no attribute 'utils'. if it try import deepchem.utils I get the same error. So, it appears that deepchem.utils doesn't exist somehow, which is weird because the master lists it as existing. Am I doing something wrong, and How do I fix this ?
Thanks

----> 1 import deepchem as dc

/home/daniels/repo/deepchem/deepchem/init.py in ()
6 from future import unicode_literals
7
----> 8 import deepchem.data
9 import deepchem.feat
10 import deepchem.hyper

/home/daniels/repo/deepchem/deepchem/data/init.py in ()
15 from deepchem.data.datasets import densify_features
16 from deepchem.data.supports import *
---> 17 from deepchem.data.data_loader import DataLoader
18 from deepchem.data.data_loader import CSVLoader
19 from deepchem.data.data_loader import UserCSVLoader

/home/daniels/repo/deepchem/deepchem/data/data_loader.py in ()
20 from deepchem.utils.save import load_csv_files
21 from deepchem.utils.save import load_sdf_files
---> 22 from deepchem.feat import UserDefinedFeaturizer
23 from deepchem.data import DiskDataset
24

/home/daniels/repo/deepchem/deepchem/feat/init.py in ()
19 from deepchem.feat.coulomb_matrices import CoulombMatrix
20 from deepchem.feat.coulomb_matrices import CoulombMatrixEig
---> 21 from deepchem.feat.rdkit_grid_featurizer import RdkitGridFeaturizer
22 from deepchem.feat.nnscore_utils import hydrogenate_and_compute_partial_charges
23 from deepchem.feat.binding_pocket_features import BindingPocketFeaturizer

/home/daniels/repo/deepchem/deepchem/feat/rdkit_grid_featurizer.py in ()
14 from rdkit import Chem
15 from rdkit.Chem import AllChem
---> 16 import deepchem.utils.rdkit_util as rdkit_util
17
18 import numpy as np

AttributeError: 'module' object has no attribute 'utils'

In [23]:

**Comment by lilleswing** [comment]
My theory is that you somehow got two different versions of DeepChem installed in your conda environment.

What method did you use to install DeepChem?

**Comment by DJDrennan** [comment]
I didn’t.  I inherited the installation from someone who is no longer with the company and have been trying to learn it.  How do I check this ?

**Comment by lilleswing** [comment]
Without knowing how it was installed it is very difficult for me to speculate how to uninstall it, or to check if there are conflicting versions in the install.  It is however very easy to install a fresh copy of deepchem (and then you know you are on the latest version).

Latest Stable --
```bash
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.0.0 python=3.5
```

Or Master -- 
```bash
git clone https://github.com/deepchem/deepchem.git      # Clone deepchem source code from GitHub
cd deepchem
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
python setup.py develop                                # Manual install
nosetests -a '!slow' -v deepchem --nologcapture        # Run tests
```

**Comment by rbharath** [comment]
Closing this issue for now. Feel free to re-open if necessary.
