### ISSUE TITLE
List of methods

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#1199]
Hello,

Is there a list of ready-to-use deepchem methods (possibly with links to correct examples)?

**Comment by lilleswing** [comment]
We don't have anything better than the tutorials at this point --
https://deepchem.io/docs/notebooks/index.html


There are two open issues to make this better though for new users.
https://github.com/deepchem/deepchem/issues/1159
https://github.com/deepchem/deepchem/issues/1137
