### ISSUE TITLE
After the installation is successful, the test is wrong

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1200]
When I installed the successful deepchem with CONDA in the installation tutorial, the last step was to run the test, but when I tested it, there was a problem, as follows
`ERROR: test_combined (deepchem.feat.tests.test_rdkit_grid_features.TestRdkitGridFeaturizer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/git/deepchem/deepchem/feat/tests/test_rdkit_grid_features.py", line 520, in test_combined
    [self.protein_file])
  File "/project/git/deepchem/deepchem/feat/rdkit_grid_featurizer.py", line 1327, in featurize_complexes
    protein_pdb_lines)
  File "/project/git/deepchem/deepchem/feat/rdkit_grid_featurizer.py", line 1302, in _featurize_complex
    features_dict = self._transform(protein_pdb_file, ligand_file)
  File "/project/git/deepchem/deepchem/feat/rdkit_grid_featurizer.py", line 1349, in _transform
    protein_pdb, calc_charges=True, sanitize=self.sanitize)
  File "/project/git/deepchem/deepchem/utils/rdkit_util.py", line 127, in load_molecule
    Chem.SanitizeMol(my_mol)
ValueError: Sanitization error: Explicit valence for atom # 320 C, 5, is greater than permitted
-------------------- >> begin captured stdout << ---------------------
Featurizing 0 / 1
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.001 s

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 510 tests in 445.373s

FAILED (errors=1)

`

Excuse me, is this a mistake in the source code?

**Comment by lilleswing** [comment]
We run the tests on every merge to master, and this test can not failed for months.  The setup for our continuous integration is Ubuntu 14.04 in both python 2.7 and 3.5.

The error you are getting is rdkit sanitizing a molecule.  One hypothesis is something went wrong and you have an older version of RDKIT which can't sanitize the pdb file.  Can I look at your conda environment to help debug this?

```bash
> conda list
# packages in environment at /home/leswing/miniconda3/envs/env-check:
#
# Name                    Version                   Build  Channel
absl-py                   0.1.13                    <pip>
asn1crypto                0.24.0                   py35_0    conda-forge
astor                     0.6.2                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                     <pip>
bleach                    2.1.3                      py_0    conda-forge
boost                     1.63.0           py35h04a78bc_1    rdkit
bzip2                     1.0.6                h9a117a8_4  
ca-certificates           2017.08.26           h1d4fec5_0  
cairo                     1.14.12              h77bcde2_0  
certifi                   2018.1.18                py35_0  
cffi                      1.11.5                   py35_0    conda-forge
chardet                   3.0.4                    py35_0    conda-forge
cryptography              2.2.1                    py35_0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.2.1                    py35_0    conda-forge
deepchem                  2.0.1.dev149              <pip>
entrypoints               0.2.3                    py35_1    conda-forge
expat                     2.2.5                         0    conda-forge
fftw3f                    3.3.4                         2    omnia
flaky                     3.3.0                    py35_0    conda-forge
fontconfig                2.13.0                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gast                      0.2.0                     <pip>
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                         0    conda-forge
grpcio                    1.10.0                    <pip>
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
hdf5                      1.10.1               h9caa474_1  
html5lib                  1.0.1                      py_0    conda-forge
html5lib                  0.9999999                 <pip>
icu                       58.2                          0    conda-forge
idna                      2.6                      py35_1    conda-forge
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py35_0    conda-forge
ipython                   6.2.1                    py35_1    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
ipywidgets                7.1.2                    py35_0    conda-forge
jedi                      0.11.1                   py35_0    conda-forge
jinja2                    2.10                     py35_0    conda-forge
joblib                    0.11                     py35_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py35_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py35_0    conda-forge
jupyter_console           5.2.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py35_1    conda-forge
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                         0    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
lzo                       2.10                 h49e0be7_2  
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py35_0    conda-forge
matplotlib                2.2.2                    py35_1    conda-forge
mdtraj                    1.9.1                    py35_1    deepchem
mistune                   0.8.3                      py_0    conda-forge
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py35h3010b51_0  
mkl_random                1.0.1            py35h629b387_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py35_0    conda-forge
ncurses                   6.0                  h9df7e31_2  
networkx                  1.11                     py35_0    conda-forge
nose                      1.3.7                    py35_2    conda-forge
nose-timer                0.7.0                    py35_1    conda-forge
notebook                  5.4.1                    py35_0    conda-forge
numexpr                   2.6.4            py35h119f745_0  
numpy                     1.14.2          py35_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.45.1                   py35_0    conda-forge
openblas                  0.2.20                        7    conda-forge
openmm                    7.2.1                    py35_1    omnia
openssl                   1.0.2o               h20670df_0  
pandas                    0.22.0                   py35_0    conda-forge
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.1                    py35_0    conda-forge
parso                     0.1.1                      py_0    conda-forge
pbr                       3.1.1                    py35_0    conda-forge
pcre                      8.41                          1    conda-forge
pdbfixer                  1.4                      py35_0    omnia
pexpect                   4.4.0                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pillow                    4.3.0                    py35_2    conda-forge
pip                       9.0.1                    py35_5  
pixman                    0.34.0               hceecf20_3  
prompt_toolkit            1.0.15                   py35_0    conda-forge
protobuf                  3.5.2.post1               <pip>
ptyprocess                0.5.2                    py35_0    conda-forge
pycparser                 2.18                     py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
pyopenssl                 17.5.0                   py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_4    conda-forge
pysocks                   1.6.8                    py35_1    conda-forge
pytables                  3.4.2            py35hfa98db7_2  
python                    3.5.5                hc3d631a_1  
python-dateutil           2.7.2                    py35_0  
pytz                      2018.3                   py35_0  
pyzmq                     17.0.0                   py35_3    conda-forge
qt                        5.6.2               h974d657_12  
qtconsole                 4.3.1                    py35_0    conda-forge
rdkit                     2017.09.1                py35_1    rdkit
readline                  7.0                  ha6073c6_4  
requests                  2.18.4                   py35_1    conda-forge
scikit-learn              0.19.1          py35_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.1           py35_blas_openblas_200  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.0.1                   py35_0  
simdna                    0.4.2                      py_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                   py35_1    conda-forge
sqlite                    3.22.0               h1bed415_0  
tensorboard               1.6.0                     <pip>
tensorflow                1.6.0                     <pip>
termcolor                 1.1.0                    py35_1    conda-forge
terminado                 0.8.1                    py35_0    conda-forge
testpath                  0.3.1                    py35_0    conda-forge
tk                        8.6.7                hc745277_3  
tornado                   5.0.1                    py35_1    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
urllib3                   1.22                     py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
webencodings              0.5                      py35_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py35hd3883cf_1  
widgetsnbextension        3.1.4                    py35_0    conda-forge
xgboost                   0.6a2                    py35_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                h55aa19d_2  
zeromq                    4.2.5                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by pvskand** [comment]
As far as I remember this problem had earlier come up in the gitter channel. My advice would be to install this in separate conda environment instead of directly installing it. It avoids all the conflicts of versions. If even this doesn't solve the problem, post your conda environment here and we someone would be able to help you.

**Comment by zhouhao-learning** [comment]
@lilleswing 
My system is　ubuntu16.04
The following is the CONDA environment after I installed deepchem

`(deepchem) zh@zh:~$ conda list
# packages in environment at /home/zh/anaconda3/envs/deepchem:
#
absl-py                   0.1.13                    <pip>
asn1crypto                0.24.0                   py35_0    conda-forge
astor                     0.6.2                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                     <pip>
bleach                    2.1.3                      py_0    conda-forge
boost                     1.63.0           py35h04a78bc_1    rdkit
bzip2                     1.0.6                h9a117a8_4  
ca-certificates           2017.08.26           h1d4fec5_0  
cairo                     1.14.12              h77bcde2_0  
certifi                   2018.1.18                py35_0  
cffi                      1.11.5                   py35_0    conda-forge
chardet                   3.0.4                    py35_0    conda-forge
cryptography              2.2.1                    py35_0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.2.1                    py35_0    conda-forge
deepchem                  2.0.1.dev149              <pip>
entrypoints               0.2.3                    py35_1    conda-forge
expat                     2.2.5                         0    conda-forge
fftw3f                    3.3.4                         2    omnia
flaky                     3.3.0                    py35_0    conda-forge
fontconfig                2.13.0                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gast                      0.2.0                     <pip>
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                         0    conda-forge
grpcio                    1.10.0                    <pip>
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
hdf5                      1.10.1               h9caa474_1  
html5lib                  1.0.1                      py_0    conda-forge
html5lib                  0.9999999                 <pip>
icu                       58.2                          0    conda-forge
idna                      2.6                      py35_1    conda-forge
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py35_0    conda-forge
ipython                   6.2.1                    py35_1    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
ipywidgets                7.1.2                    py35_0    conda-forge
jedi                      0.11.1                   py35_0    conda-forge
jinja2                    2.10                     py35_0    conda-forge
joblib                    0.11                     py35_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py35_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py35_0    conda-forge
jupyter_console           5.2.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py35_1    conda-forge
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                         0    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
lzo                       2.10                 h49e0be7_2  
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py35_0    conda-forge
matplotlib                2.2.2                    py35_1    conda-forge
mdtraj                    1.9.1                    py35_1    deepchem
mistune                   0.8.3                      py_0    conda-forge
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py35h3010b51_0  
mkl_random                1.0.1            py35h629b387_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py35_0    conda-forge
ncurses                   6.0                  h9df7e31_2  
networkx                  1.11                     py35_0    conda-forge
nose                      1.3.7                    py35_2    conda-forge
nose-timer                0.7.0                    py35_1    conda-forge
notebook                  5.4.1                    py35_0    conda-forge
numexpr                   2.6.4            py35h119f745_0  
numpy                     1.14.2          py35_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.45.1                   py35_0    conda-forge
openblas                  0.2.20                        7    conda-forge
openmm                    7.2.1                    py35_1    omnia
openssl                   1.0.2o               h20670df_0  
pandas                    0.22.0                   py35_0    conda-forge
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.1                    py35_0    conda-forge
parso                     0.1.1                      py_0    conda-forge
pbr                       3.1.1                    py35_0    conda-forge
pcre                      8.41                          1    conda-forge
pdbfixer                  1.4                      py35_0    omnia
pexpect                   4.4.0                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pillow                    4.3.0                    py35_2    conda-forge
pip                       9.0.1                    py35_5  
pixman                    0.34.0               hceecf20_3  
prompt_toolkit            1.0.15                   py35_0    conda-forge
protobuf                  3.5.2.post1               <pip>
ptyprocess                0.5.2                    py35_0    conda-forge
pycparser                 2.18                     py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
pyopenssl                 17.5.0                   py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_4    conda-forge
pysocks                   1.6.8                    py35_1    conda-forge
pytables                  3.4.2            py35hfa98db7_2  
python                    3.5.5                hc3d631a_1  
python-dateutil           2.7.2                    py35_0  
pytz                      2018.3                   py35_0  
pyzmq                     17.0.0                   py35_3    conda-forge
qt                        5.6.2               h974d657_12  
qtconsole                 4.3.1                    py35_0    conda-forge
rdkit                     2017.09.1                py35_1    rdkit
readline                  7.0                  ha6073c6_4  
requests                  2.18.4                   py35_1    conda-forge
scikit-learn              0.19.1          py35_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.1           py35_blas_openblas_200  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                36.2.2                   py35_0    conda-forge
simdna                    0.4.2                      py_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                   py35_1    conda-forge
sqlite                    3.22.0               h1bed415_0  
tensorboard               1.6.0                     <pip>
tensorflow                1.6.0                     <pip>
termcolor                 1.1.0                    py35_1    conda-forge
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                    py35_0    conda-forge
testpath                  0.3.1                    py35_0    conda-forge
tk                        8.6.7                hc745277_3  
tornado                   5.0.1                    py35_1    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
urllib3                   1.22                     py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
webencodings              0.5                      py35_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py35hd3883cf_1  
widgetsnbextension        3.1.4                    py35_0    conda-forge
xgboost                   0.6a2                    py35_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                h55aa19d_2  
zeromq                    4.2.5                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
`

**Comment by zhouhao-learning** [comment]
@lilleswing 
Do I have a problem with my environment?How should I pass my test? Because I encountered errors when I was running your official examples.

**Comment by hovo1990** [comment]
Hello,
I also have issues while running tests.
I installed in a separate conda environment and used this command in the environment:

conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.0.0 python=3.5


I get these errors, it appears there is an issue with rdkit.

======================================================================
ERROR: Check num samples for loaded and reloaded datasets is equal.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/data/tests/test_reload.py", line 80, in test_reload_after_gen
    dataset_file, reload)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/data/tests/test_reload.py", line 32, in _run_muv_experiment
    raw_dataset = dc.utils.save.load_from_disk(dataset_file)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/utils/save.py", line 221, in load_from_disk
    df = pd.read_csv(filename, header=0)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 651, in pandas._libs.parsers.TextReader._setup_parser_source
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/data/tests/../../../datasets/mini_muv.csv.gz'

======================================================================
ERROR: Check ability to repeatedly run experiments with reload set True.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/data/tests/test_reload.py", line 98, in test_reload_twice
    dataset_file, reload)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/data/tests/test_reload.py", line 32, in _run_muv_experiment
    raw_dataset = dc.utils.save.load_from_disk(dataset_file)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/utils/save.py", line 221, in load_from_disk
    df = pd.read_csv(filename, header=0)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 651, in pandas._libs.parsers.TextReader._setup_parser_source
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/data/tests/../../../datasets/mini_muv.csv.gz'

======================================================================
ERROR: test_combined (deepchem.feat.tests.test_rdkit_grid_features.TestRdkitGridFeaturizer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/feat/tests/test_rdkit_grid_features.py", line 520, in test_combined
    [self.protein_file])
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 1327, in featurize_complexes
    protein_pdb_lines)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 1302, in _featurize_complex
    features_dict = self._transform(protein_pdb_file, ligand_file)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 1349, in _transform
    protein_pdb, calc_charges=True, sanitize=self.sanitize)
  File "/home/john1990/anaconda3/envs/deepus2/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 127, in load_molecule
    Chem.SanitizeMol(my_mol)
ValueError: Sanitization error: Explicit valence for atom # 320 C, 5, is greater than permitted
-------------------- >> begin captured stdout << ---------------------
Featurizing 0 / 1
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.001 s

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 432 tests in 950.360s

 conda list
# :
#
absl-py                   0.2.2                     <pip>
asn1crypto                0.24.0                   py35_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                     <pip>
bleach                    2.1.3                      py_0    conda-forge
blosc                     1.14.0                        1    conda-forge
boost                     1.63.0           py35h04a78bc_1    rdkit
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.4.16                py35_0    conda-forge
cffi                      1.11.5                   py35_0    conda-forge
chardet                   3.0.4                    py35_0    conda-forge
cryptography              2.2.1                    py35_0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
dbus                      1.11.0                        0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
deepchem-gpu              2.0.0                    py35_0    deepchem
entrypoints               0.2.3                    py35_1    conda-forge
expat                     2.2.5                         0    conda-forge
fftw3f                    3.3.4                         2    omnia
flaky                     3.3.0                    py35_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  0.9999999                 <pip>
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py35_1    conda-forge
ipykernel                 4.8.2                    py35_0    conda-forge
ipython                   6.4.0                    py35_0    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
ipywidgets                7.2.1                    py35_1    conda-forge
jedi                      0.12.0                   py35_0    conda-forge
jinja2                    2.10                     py35_0    conda-forge
joblib                    0.11                     py35_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py35_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py35_0    conda-forge
jupyter_console           5.2.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py35_1    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
lzo                       2.10                          0    conda-forge
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py35_0    conda-forge
matplotlib                2.2.2                    py35_1    conda-forge
mdtraj                    1.9.1                    py35_1    deepchem
mistune                   0.8.3                    py35_1    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py35_0    conda-forge
nose                      1.3.7                    py35_2    conda-forge
nose-timer                0.7.0                    py35_1    conda-forge
notebook                  5.5.0                    py35_0    conda-forge
numexpr                   2.6.5                    py35_0    conda-forge
numpy                     1.14.3          py35_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.45.1                   py35_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openmm                    7.2.2                    py35_1    omnia
openssl                   1.0.2o                        0    conda-forge
pandas                    0.22.0                   py35_1    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py35_0    conda-forge
parso                     0.2.1                      py_0    conda-forge
pcre                      8.41                          1    conda-forge
pdbfixer                  1.4                      py35_0    omnia
pexpect                   4.5.0                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pillow                    4.3.0                    py35_2    conda-forge
pip                       9.0.3                    py35_0    conda-forge
pixman                    0.34.0                        2    conda-forge
prompt_toolkit            1.0.15                   py35_0    conda-forge
protobuf                  3.5.2.post1               <pip>
ptyprocess                0.5.2                    py35_0    conda-forge
pycparser                 2.18                     py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
pyopenssl                 18.0.0                   py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_5    conda-forge
pysocks                   1.6.8                    py35_1    conda-forge
pytables                  3.4.3                    py35_8    conda-forge
python                    3.5.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyzmq                     17.0.0                   py35_4    conda-forge
qt                        5.6.2                         7    conda-forge
qtconsole                 4.3.1                    py35_0    conda-forge
rdkit                     2017.09.1                py35_1    rdkit
readline                  7.0                           0    conda-forge
requests                  2.18.4                   py35_1    conda-forge
scikit-learn              0.19.1          py35_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py35_blas_openblas_200  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.2.0                   py35_0    conda-forge
simdna                    0.4.2                      py_0    deepchem
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tensorflow-gpu            1.5.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
termcolor                 1.1.0                    py35_1    conda-forge
terminado                 0.8.1                    py35_0    conda-forge
testpath                  0.3.1                    py35_0    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py35_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
urllib3                   1.22                     py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
webencodings              0.5                      py35_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wheel                     0.31.0                   py35_0    conda-forge
widgetsnbextension        3.2.1                    py35_0    conda-forge
xgboost                   0.6a2                    py35_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.5                         1    conda-forge
zlib                      1.2.11                        0    conda-forge

Is there anything I can do to fix this problem?

**Comment by rbharath** [comment]
It looks like some of your data files might be missing from your install. Could you check to see that they're present and try adding them in if not?

**Comment by rbharath** [comment]
I'm going to close this old issue. Feel free to re-open if necessary.
