### ISSUE TITLE
Dataset metadata for those used in examples?

### ISSUE THREAD

**Issue by sachanganesh** [deepchem/deepchem#1204]
As a newcomer to computational chemistry, I'm finding it difficult to find the source for certain datasets that are hosted in deepchem's AWS server. I've been specifically looking for papers or dataset websites.

For example, with the KINASE dataset I was confused by what the features were supposed to describe. Is there a paper relevant to it that has this information?

**Comment by rbharath** [comment]
We should improve our documentation here, but as a first pointer, most of our datasets are listed in http://moleculenet.ai.

The KINASE dataset is from [this paper](https://pubs.acs.org/doi/abs/10.1021/acs.jcim.7b00146)

**Comment by sachanganesh** [comment]
Thank you!

**Comment by rsangikagit** [comment]
How can I read the output file model_weights.h5?
