### ISSUE TITLE
Learning rate decay

### ISSUE THREAD

**Issue by miaecle** [deepchem/deepchem#1205]
In the `TensorGraph` class, learning rate could be set to either a constant float or a `LearningRateSchedule`. I assume that the `LearningRateSchedule` should be used if we would like to do learning rate decay, is there any example on this?

**Comment by peastman** [comment]
A few of the examples do this.  Here's one: https://github.com/deepchem/deepchem/blob/f51c17e6fe72ca24f2ffdba519acb757ffe15fc2/examples/pcba/pcba_tf.py

**Comment by miaecle** [comment]
@peastman Very helpful! Thanks for the guide!
