### ISSUE TITLE
A question about variable scoping in gaussian_process.py

### ISSUE THREAD

**Issue by simonfqy** [deepchem/deepchem#1208]
Hi, in my customized implementation of `deepchem/hyper/gaussian_process.py`, I wanted to specify the model directory using a variable named `model_dir`, so that I can launch `TensorBoard` using that directory as `logdir`. 
However, after including `model_dir = "./model_dir"` in the parameter list of function `hyperparam_search()`, and when I wanted to use `model_dir` in its subfunction `f()` as a parameter fed into `benchmark_classification()` in the following line of code, it reports to me that variable `model_dir` cannot be found. I used `debugger` to check it and found that all other variables like `n_features`, `metric` are fine, only `model_dir` has this problem.  https://github.com/deepchem/deepchem/blob/6749d8d136283ad8f5eaff856222212417fc80da/deepchem/hyper/gaussian_process.py#L204

So in the body of `f()` and before that line of code, I had to write a line of code: `nonlocal model_dir` to tell the interpreter that `model_dir` was defined in a higher level of enclosure, i.e., the `hyperparam_search()` function. And the problem disappeared.

Can anyone tell me why I had to use the keyword `nonlocal` to ensure correct behavior for `model_dir`, while I don't need to do so for other variables? Thanks.

**Comment by miaecle** [comment]
@simonfqy Are you using `model_dir` also as a parameter for the search function `f`?  We utilized pyGPGO for this search, which might not support anything other than int or float (which is also written in the doc). If your `model_dir` doesn't change across the search, I will suggest you just define it out of `f` like `metric` and all datasets. Or you might want to try rebuilding the string according to the input parameters within `f`.

**Comment by simonfqy** [comment]
@miaecle I didn't pass it as a parameter for the function `f`. I have solved the problem, but just curious as to why.

**Comment by rbharath** [comment]
Closing this issue since it looks like the problem's been solved.
