### ISSUE TITLE
Improved Hyper Parameter Tuning Support

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1210]
There's been a lot of requests for better hyperparameter tuning. Let's kick off this issue to discuss how we can have better support. Some early ideas:

- Better TensorFlow Experiment support using the tf.Estimator bridge?
- Cluster integration with tools like KubeFlow? (https://github.com/kubeflow/kubeflow)
- An in-depth tutorial on hyperparameter tuning on a challenging dataset?

CC @peastman @lilleswing @miaecle

**Comment by Agent007** [comment]
How about using Berkeley's [Ray Tune](http://ray.readthedocs.io/en/latest/tune.html)? I've not tried it myself yet, but it apparently has TensorFlow support.

**Comment by mlgill** [comment]
I was going to suggest Ray as well -- I'm just getting ready to incorporate it with some work that I'm doing, so I'll probably have more thoughts next week.

**Comment by richardliaw** [comment]
Is this still a needed feature? Is there some way I can contribute Ray Tune support?

**Comment by rbharath** [comment]
@richardliaw A tutorial on how to use ray tune with DeepChem would be great. Something in the style of https://github.com/deepchem/deepchem/tree/master/examples/tutorials

**Comment by richardliaw** [comment]
Sure; a tutorial would make sense. I have a couple questions:
1. What would be the a "challenging dataset" to tune on (or something that deepchem users would care about)? It would be nice to have something that is interesting to demonstrate, as it would probably be more valuable to deepchem. 
2. Would it make sense to integrate Tune more deeply with DeepChem; i.e., something in the `dc.hyper.HyperparamOpt` module? I would be more than happy to investigate but just wanted to hear your thoughts.

**Comment by rbharath** [comment]
Sorry for the slow response.

1. For a really challenging dataset, tuning across all the datasets on http://moleculenet.ai/datasets-1 in a multitask learning setting would be a very interesting demonstration. There's growing interest in transfer learning in the space, and there hasn't been a compelling demonstration thus far.
2. I think we'd be open to this. We'd have to make Tune a soft dependency, but having something that worked out of box could be a nice value add.

**Comment by rbharath** [comment]
We might want to use Keras tuner as a base for improving hyperparameter tuning:

https://github.com/keras-team/keras-tuner

**Comment by rbharath** [comment]
Closing this issue in favor of #1754
