### ISSUE TITLE
Uncertainty Handling for TensorGraph

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1211]
There have been a lot of requests for better uncertainty information from DeepChem models. Providing better support for uncertainty estimation would a lot of value to users. Let's use this thread to kick off a discussion for better support. Ideas:

- Ensembling models to estimate uncertainty (bootstrap style)?
- Dropout Uncertainty estimation support (https://arxiv.org/abs/1506.02142)?

CC @peastman @lilleswing @miaecle

**Comment by peastman** [comment]
We already discussed this some under #1119.  Shall we keep discussing it there, rather than splitting the conversation between two issues?

**Comment by peastman** [comment]
The discussion there already moved on to the need for multiple methods.

**Comment by rbharath** [comment]
Closing in favor  of #1119.
