### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#1212]
Hello,

What is the correct way to set random seed for the whole training procedure? tf.set_random_seed seems not working

**Comment by miaecle** [comment]
@allchemist Thanks for raising the issue. As far as I know, setting `np.random.seed` and `tf.set_random_seed` are all you can do, but there still exist numerical errors that may accumulate through training, causing different performances. The range of variation will depend on dataset and training length.

**Comment by allchemist** [comment]
I'm sorry to say, but this cannot happen because of floating point errors - the results are completely different at start after first epoch. Also afaik fp errors are deterministic.

**Comment by rbharath** [comment]
I'm closing this old issue for now. Feel free to comment if there are still issues you're facing with deterministic execution.
