### ISSUE TITLE
Why does NumpyDataset reshape arrays?

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1216]
I just spent a couple of hours debugging some really strange behavior, and eventually tracked it down to the following lines in the `NumpyDataset` constructor:

```python
n_samples = len(X)
# The -1 indicates that y will be reshaped to have length -1
if n_samples > 0:
  if y is not None:
    y = np.reshape(y, (n_samples, -1))
    if w is not None:
      w = np.reshape(w, (n_samples, -1))
```

Why is it reshaping the arrays?  It's enforcing a hardcoded restriction that the labels can never have multiple dimensions per sample, which basically rules out using it with any model that produces multidimensional output.  Why?

**Comment by rbharath** [comment]
My guess is this was added in at some point to standardize the shape of `y` to make tests pass.

This seems like a bug. We shouldn't be enforcing this restriction since we're definitely going to have models with multidimensional outputs.
