### ISSUE TITLE
How can I obtain each of the training, valid, test datasets with the format of csv files in the tutorial "Graph Convolutions For Tox21"?

### ISSUE THREAD

**Issue by herbert0525** [deepchem/deepchem#1217]
Hi, I was about to extract training_dataset, valid_dataset and test_dataset from the code of this tutorial, at first I tried pandas.DataFrame and to_csv to get respective CSV files, but there was a traceback "ValueError: DataFrame constructor not properly called!"  So I thought perhaps these were already split into 3 CSV files, and I used the pandas.read_csv function and tried to print them. However, the new error indicated that the separate training_dataset does not even exist! So could you tell me how can I get the respective training, valid, test data sets with the format of CSV files please, thanks

**Comment by dmoccia** [comment]
@herbert0525 if you go [here](https://github.com/deepchem/deepchem/tree/master/datasets) you can download the full tox21 dataset as a csv.gz file.  When you run the code example (for instance one of [these](https://github.com/deepchem/deepchem/tree/master/examples/tox21)) deepchem either is accessing this file to build what is called a DiskDataset which is a specially formatted featurized version of each molecule.  Deepchem then uses something called a Splitter to break the dataset into train, validation, test sets. You cannot wrap a these sets as pandas dataframes as they are a dataset object.    I do not believe there is a function for converting the dataset to csv but perhaps someone can correct me here?
You could take the full tox21.csv file and split it using sklearn [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

**Comment by miaecle** [comment]
@herbert0525 Yes, it might be a bit tricky to write a DiskDataset to a csv file. For the case of tox21, smiles for all samples in the dataset could be accessed through `dataset.ids`, labels and weights can be accessed through `dataset.y` and `dataset.w`(note that a weight of 0 indicates an empty entry in the corresponding label, though the label will appear to be 0). You should be able to write these into a csv file in the same format.

**Comment by miaecle** [comment]
@herbert0525 Weight is used mostly in multitask classification datasets. In the original csv file, for each individual task, the labels of all samples could be positive(y=1), negative(y=0) or unavailable(no entry, or y=nan). Weight is first used to indicate the availability of each data point, with 0 meaning the label here is unavailable and it will hence not be counted in loss or evaluation. It is also used for balancing positive/negative samples by assigning different weights to different labels, keeping the total weights for each class to be equal.

**Comment by herbert0525** [comment]
OK, I think I have got what I need. Thank both of you.
