### ISSUE TITLE
TensorFlow Probability

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1219]
https://medium.com/tensorflow/introducing-tensorflow-probability-dca4c304e245

TensorFlow just announced support for better uncertainy modeling with a new `tfp` package. Might be worth looking into as we improve our uncertainty support.

CC @peastman

**Comment by rbharath** [comment]
Marked this contributions welcome. Experiments would be good additions to `contrib/` folder for now.

**Comment by souravsingh** [comment]
I am interested in pursuing the issue. What kind of models are we looking for?

**Comment by rbharath** [comment]
Excited to hear you're interested! I think to start, something like a Bayesian fully connected neural network could be really useful to implement. I'd recommend adding to `contrib/`. We can migrate into the main repo as the code matures.

**Comment by rbharath** [comment]
I'm going to close this issue for now since I don't think we have active plans to implement Bayesian neural networks, but feel free to post here if there's still interest.
