### ISSUE TITLE
cannot install deepchem on python 3.5

### ISSUE THREAD

**Issue by dewshr** [deepchem/deepchem#1220]
I can install without including python version 2.7 but when I specify python version in **"conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.0.0 python=3.5"**, i am getting following error:
UnsatisfiableError: The following specifications were found to be in conflict:

deepchem=2.0.0 -> libgfortran==3.0.0=0
deepchem=2.0.0 -> python[version='>=2.7,<2.8.0a0']
python=3.5

**Comment by lilleswing** [comment]
This is happening on OSX -- I verified this bug is indeed happening, but I don't know how to fix it as of now.

I would recommend following the instructions to install from source until then.  Sorry for the inconvenience.

```bash
git clone https://github.com/deepchem/deepchem.git      # Clone deepchem source code from GitHub
cd deepchem
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
python setup.py install                                # Manual install
```

**Comment by pvskand** [comment]
@lilleswing @dewshr, as discussed on Gitter with @XinyuuLi, this is a problem caused due to the new conda version as mentioned here : https://github.com/rdkit/rdkit/issues/1617. One solution to this could be to downgrade the conda version until there are some updates on the above mentioned thread.

**Comment by emakryo** [comment]
I have the same issue on macos. It seems the dependencies for python3.5 are too strict. For example, pyqt and pip are included in the dependency list of deepchem. These dependencies can be shown by `conda search -c deepchem deepchem --info`.

**Comment by sophia-wright-blue** [comment]
Is it possible to install from source without creating a new environment? I have a separate environment already for a ML project and would like to install deepchem in the existing environment. I'm using Python 3.6.5 on OSX. Thank you.

**Comment by rbharath** [comment]
@sophia-wright-blue You should be able to install in your existing environment, but there's a possibility that the requirements could conflict with your existing setup.

**Comment by sophia-wright-blue** [comment]
@rbharath Thank you for replying. I'm getting the same error as in the first post in this thread when using the conda install option, and the install from source instructions say that a new environment gets created, so I was wondering what the steps would be to install from source in the existing environment. I'm using Python 3.6.5 on OSX. Thank you.

**Comment by peastman** [comment]
You don't need to create a new environment.  Just make sure you have all the dependencies installed (see https://github.com/deepchem/deepchem/blob/master/scripts/install_deepchem_conda.sh), then execute either `python setup.py install` or `python setup.py develop`.

**Comment by sophia-wright-blue** [comment]
got it, i had to install a few modules manually and now i'm able to import deepchem, thank you!

**Comment by RishikeshMagar** [comment]
I am completely new to deepchem, when trying to install deepchem using: conda install -c deepchem deepchem=2.1.0 python=3.5

I am getting the below error

PackagesNotFoundError: The following packages are not available from current channels:

  - deepchem=2.1.0 -> pdbfixer==1.4
  - deepchem=2.1.0 -> rdkit==2017.09.1
  - deepchem=2.1.0 -> xgboost==0.6a2

Not sure how to fix this please guide

**Comment by pvskand** [comment]
@RishikeshMagar Try install from the source as mentioned in the `README.md`. That should install all the dependencies as well.

**Comment by RishikeshMagar** [comment]
Worked thanks @pvskand
