### ISSUE TITLE
How deepchem deals with missed values?

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#1224]
Hi,

when i looked into what values "dataset.y" stores, i found just zeros in places for missed values. So do you just substitute missed values with zeros, or there is some hidden mechanism about it?

**Comment by rbharath** [comment]
`dataset.w` assigns a weight of 0 to missing values which means that these values are not used during training.

**Comment by allchemist** [comment]
Probably the best solution. Thanks!
