### ISSUE TITLE
faster pairwise distance computations

### ISSUE THREAD

**Issue by evanfeinberg** [deepchem/deepchem#123]
In `grid_featurizer.py`, we wrote our own function to compute pairwise distance for each `(i,j)` pair of points between two arrays of points `x` and `y`. It turns out sklearn has its own version of this, `sklearn.metrics.pairwise.pairwise_distances`. We should likely swap out our version and try out sklearn's version to make featurization a little faster.

**Comment by rbharath** [comment]
@evanfeinberg +1! Do you think you'd have time to make a quick PR to implement this?

**Comment by evanfeinberg** [comment]
Definitely, I'll try tomorrow when I give mass docking a quick OOP pass. Unfortunately it looks like vsp-compute is completely down right now, however :(. Do you mind VPNing into Stanford and trying to log in to vsp-compute just to make sure the issue isn't only on my end?

**Comment by rbharath** [comment]
@evanfeinberg Going to go ahead and close this issue. We can re-open if we decide we want to make a future upgrade to `grid_featurizer.py`.
