### ISSUE TITLE
bug in mpnn

### ISSUE THREAD

**Issue by jaechanglim** [deepchem/deepchem#1232]
I think that the indentation of line 104 in deepchem/contrib/mpnn/mpnn.py is wrong..

it's indentation level should be one below

isn't it?

**Comment by lilleswing** [comment]
@jaechanglim I think you are correct.  The code in contrib is held to a lower standard than the code in the rest of the repo.  A PR to fix this issue would be much appreciated!

**Comment by rbharath** [comment]
Marked this as contribution welcome.

**Comment by MatthewMasters** [comment]
Is this issue supposed to be open still? The bug appears to have been fixed.

**Comment by rbharath** [comment]
Good catch. Will close issue.
