### ISSUE TITLE
How do I save my training model and load the model files that I saved to predict? I didn't see the corresponding tutorials and steps. Can you give me a point?

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1236]

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/models/test_graph_models.py#L45

We test a lot of our key functionality.  Looking through our model test code is usually helpful when trying to figure out how to do something.

**Comment by zhouhao-learning** [comment]
@lilleswing 
Thank you for your advice. I found the way inside.
