### ISSUE TITLE
bug while using MultiTaskRegressor with tensorboard

### ISSUE THREAD

**Issue by xiaohongniua** [deepchem/deepchem#1237]
Hello, I am using MultiTaskRegressor with tensorboard, error as follows,but there is no error when I turn off tensorboard
ValueError                                Traceback (most recent call last)
<ipython-input-54-23701dd8deee> in <module>()
      9     log("hyperparameters: %s" % str(model_params), verbose=True)
     10     model = model_builder(model_params, model_dir)
---> 11     x=model.fit(train_dataset, **model_params)

~/deepchem/deepchem/models/tensorgraph/tensor_graph.py in fit(self, dataset, nb_epoch, max_checkpoints_to_keep, checkpoint_interval, deterministic, restore, submodel, **kwargs)
    150         self.default_generator(
    151             dataset, epochs=nb_epoch, deterministic=deterministic),
--> 152         max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
    153 
    154   def fit_generator(self,

~/deepchem/deepchem/models/tensorgraph/tensor_graph.py in fit_generator(self, feed_dict_generator, max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
    254           if should_log:
    255             fetches.append(self._get_tf("summary_op"))
--> 256           fetched_values = self.session.run(fetches, feed_dict=feed_dict)
    257           if should_log:
    258             self._log_tensorboard(fetched_values[2])

~/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    903     try:
    904       result = self._run(None, fetches, feed_dict, options_ptr,
--> 905                          run_metadata_ptr)
    906       if run_metadata:
    907         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1111                              'which has shape %r' %
   1112                              (np_val.shape, subfeed_t.name,
-> 1113                               str(subfeed_t.get_shape())))
   1114           if not self.graph.is_feedable(subfeed_t):
   1115             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (1, 1) for Tensor 'Label_8/Placeholder:0', which has shape '(?, 1, 1)'

**Comment by peastman** [comment]
It's saying that your labels have the wrong shape.  Can you show the code you're using to call it?

**Comment by xiaohongniua** [comment]
this is the code 
import deepchem as dc
tasks = ['lable']
featurizer = dc.feat.CircularFingerprint(size=2048)
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles",id_field='id',featurizer=featurizer,log_every_n=10000)
dataset = loader.featurize('test.csv',shard_size=57330)

transformers = [dc.trans.NormalizationTransformer(transform_y=True, dataset=dataset)]
for transformer in transformers:
    dataset = transformer.transform(dataset)

splitter = dc.splits.RandomSplitter()
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset)

import numpy as np
import os
import itertools
import collections
from functools import reduce
from operator import mul
from deepchem.utils.save import log
import tensorflow as tf
params_dict = {#"activation": ["relu"],
               "batch_size": [1],
               "init": ["glorot_uniform"],
               "data_shape": [train_dataset.get_data_shape()],
               "learning_rate": [0.0001],
               "nb_epoch": [20],
               "dropouts": [(.0,),],
               "layer_sizes": [(3000,1028,)],
               "weight_init_stddevs": [(0.044)],
               "bias_init_consts": [(1.,)],
               "weight_decay_penalty": [0.001],
               "weight_decay_penalty_type":["l2"],
              }
n_features = train_dataset.get_data_shape()[0]
model_dir='./modeldir'
if not os.path.exists(model_dir):
    os.makedirs(model_dir) 
def model_builder(model_params, model_dir):
  model = dc.models.MultiTaskClassifier(
    len(tasks), n_features, tensorboard=True,tensorboard_log_frequency=1, use_queue=False,
      checkpoint_interval=1,configproto=tf.ConfigProto(log_device_placement=True),model_dir=model_dir, **model_params)
  return model

hyperparams = params_dict.keys()
hyperparam_vals = params_dict.values()
number_combinations = reduce(mul, [len(vals) for vals in hyperparam_vals])
for ind, hyperparameter_tuple in enumerate(itertools.product(*hyperparam_vals)):
    model_params = {}
    log("Fitting model %d/%d" % (ind + 1, number_combinations), verbose=True)
    for hyperparam, hyperparam_val in zip(hyperparams, hyperparameter_tuple):
        model_params[hyperparam] = hyperparam_val
    log("hyperparameters: %s" % str(model_params), verbose=True)
    model = model_builder(model_params, model_dir)
    model.fit(train_dataset, **model_params)

**Comment by rbharath** [comment]
@xiaohongniua Are you still facing this problem? If so, could you provide us a simplified failing test case? Ideally < 30 lines, with unnecessary code removed to help us debug.
