### ISSUE TITLE
deepchem/examples/adme datasets are not accessible

### ISSUE THREAD

**Issue by jieeshen-lilly** [deepchem/deepchem#1241]
Seems those csv files are not available anymore? 

def retrieve_datasets():
  os.system(
      'wget -c %s' %
      'https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_logd.csv')
  os.system(
      'wget -c %s' %
      'https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_hppb.csv')
  os.system(
      'wget -c %s' %
      'https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_clearance.csv'
  )

**Comment by jchodera** [comment]
I can confirm that I can't access them either:
```
lski2414:Downloads choderaj$ wget https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_logd.csv
--2018-04-28 19:50:42--  https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_logd.csv
Resolving s3-us-west-1.amazonaws.com... 52.219.28.129
Connecting to s3-us-west-1.amazonaws.com|52.219.28.129|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-28 19:50:43 ERROR 404: Not Found.
```

**Comment by rbharath** [comment]
I think the deep-crystal S3 bucket no longer exists.

@patrickhop Would it be possible to add these datasets to the DeepChem main S3 bucket?

**Comment by patrickhop** [comment]
@rbharath this is my mistake. I deleted the DeepCrystal bucket recently.

I'll email you the affected datasets.

**Comment by rbharath** [comment]
I've uploaded the renamed versions of these datasets to S3:

```rbharath@rbharath-XPS-13-9360:~/misc$ wget http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/lipo.csv
--2018-06-17 18:40:17--  http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/lipo.csv
Resolving deepchem.io.s3-website-us-west-1.amazonaws.com (deepchem.io.s3-website-us-west-1.amazonaws.com)... 52.219.20.130
Connecting to deepchem.io.s3-website-us-west-1.amazonaws.com (deepchem.io.s3-website-us-west-1.amazonaws.com)|52.219.20.130|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 282597 (276K) [text/csv]
Saving to: ‘lipo.csv’

lipo.csv                            100%[================================================================>] 275.97K   870KB/s    in 0.3s    

2018-06-17 18:40:18 (870 KB/s) - ‘lipo.csv’ saved [282597/282597]

rbharath@rbharath-XPS-13-9360:~/misc$ wget http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/clearance.csv
--2018-06-17 18:40:26--  http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/clearance.csv
Resolving deepchem.io.s3-website-us-west-1.amazonaws.com (deepchem.io.s3-website-us-west-1.amazonaws.com)... 52.219.28.3
Connecting to deepchem.io.s3-website-us-west-1.amazonaws.com (deepchem.io.s3-website-us-west-1.amazonaws.com)|52.219.28.3|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60306 (59K) [text/csv]
Saving to: ‘clearance.csv’

clearance.csv                       100%[================================================================>]  58.89K  --.-KB/s    in 0.09s   

2018-06-17 18:40:27 (652 KB/s) - ‘clearance.csv’ saved [60306/60306]

rbharath@rbharath-XPS-13-9360:~/misc$ wget http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/hppb.csv
--2018-06-17 18:40:40--  http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/hppb.csv
Resolving deepchem.io.s3-website-us-west-1.amazonaws.com (deepchem.io.s3-website-us-west-1.amazonaws.com)... 52.219.20.82
Connecting to deepchem.io.s3-website-us-west-1.amazonaws.com (deepchem.io.s3-website-us-west-1.amazonaws.com)|52.219.20.82|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 117266 (115K) [text/csv]
Saving to: ‘hppb.csv’

hppb.csv                            100%[================================================================>] 114.52K  --.-KB/s    in 0.06s   

2018-06-17 18:40:40 (1.77 MB/s) - ‘hppb.csv’ saved [117266/117266]
```

**Comment by torlarse** [comment]
I did a git pull, then inserted renamed datasets manually. Example

`os.system('wget http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/lipo.csv')`

Also renamed `DATASET = "hppb.csv" ` 

When running the script the datasets are apparently loaded. Getting

`About to build model 
Loading raw samples now.
shard_size: 8192
About to start loading CSV from hppb.csv
Loading shard 1 of size 8192.
Traceback (most recent call last):
  File "/data/####/Programs/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'
`

Sorry about missing line breaks in error message

**Comment by rbharath** [comment]
Can you provide a minimal failing exmple? This looks like a pandas error and I'm not sure where this is happening.

**Comment by dimsterdi** [comment]
@torlarse You need to either change the headers in the CSV files:

**id,target,smile** to **id,exp,smiles**

or edit run_benchmarks.py:

line 41: _tasks = ['exp']_ to _tasks = ['target']_
line 48: _smiles_field="smiles"_ to _smiles_field="smile"_

**Comment by rbharath** [comment]
Closing this old issue. Feel free to re-open if necessary!
