### ISSUE TITLE
I think there should be a API document to use, like a deep learning framework such as tensorflow and keras, otherwise the function and usage of deepchem are not very clear, and this is not very friendly.

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1243]

**Comment by xiaohongniua** [comment]
+1

**Comment by lilleswing** [comment]
I'm sorry you are having issue using DeepChem, we try our best but understand how it can be unfriendly to newcomers.  

Our API Documentation exists on our website
https://deepchem.io/
https://deepchem.io/docs/deepchem.html

As well as tutorials which show how to use it for specific use cases
https://deepchem.io/docs/notebooks/index.html

**Comment by lilleswing** [comment]
If there is anything in particular that you think would be helpful we also accept PR's on our website!

https://github.com/deepchem/deepchem.io

Any html written on the website automatically gets pushed to production on a merged pull request.

**Comment by zhouhao-learning** [comment]
@lilleswing 
OK, thank you. I'll take it seriously.
