### ISSUE TITLE
Unable to use generator prediction

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1244]
I train a model and save it under the folder, then load the model to predict, but I get the error.
this is code

       class Graphconv_Net(BaseNet):
	    def __init__(self, is_training, action_param, net_param,process, id,
		n_tasks,data,thread_safe_counter,name="graphconv",**kwargs):
		super(Graphconv_Net, self).__init__(name=name)
		self.is_training = is_training
		self.action_param = action_param
		self.net_param = net_param
		self.process = process
		self.id = id
		self.n_tasks = n_tasks
		self.data = data
		self.thread_safe_counter = thread_safe_counter
		self.error_bars = True if 'error_bars' in kwargs and kwargs['error_bars'] else False

	     def fit_predict(self):
		batch_size = vars(self.net_param)['batch_size']
		Total_train = self.data.get_shape()[0][0]
		if Total_train // batch_size == 0:
			step_per_epoch = Total_train / batch_size
		else:
			step_per_epoch = Total_train / batch_size + 1
		mode = vars(self.net_param)['mode']
		model_dir = vars(self.net_param)['model_dir']
		model = tg(tensorboard=True,
		                    batch_size=batch_size,
							learning_rate=float(vars(self.net_param)['lr']),
							use_queue=False,
							model_dir=model_dir)
		atom_features = Feature(shape=(None, int(vars(self.net_param)['number_atom_features'])))
		degree_slice = Feature(shape=(None, 2), dtype=tf.int32)
		membership = Feature(shape=(None,), dtype=tf.int32)

		deg_adjs = []
		for i in range(0, 10 + 1):
			deg_adj = Feature(shape=(None, i + 1), dtype=tf.int32)
			deg_adjs.append(deg_adj)

		# 搭建卷积层
		in_layer = atom_features
		for layer_size in ast.literal_eval(vars(self.net_param)['graph_conv_layers']):
			gc1_in = [in_layer, degree_slice, membership] + deg_adjs
			gc1 = GraphConv(layer_size, activation_fn=tf.nn.relu, in_layers=gc1_in)
			batch_norm1 = BatchNorm(in_layers=[gc1])
			gp_in = [batch_norm1, degree_slice, membership] + deg_adjs
			in_layer = GraphPool(in_layers=gp_in)
		dense = Dense(out_channels=int(vars(self.net_param)['dense_layer_size']), activation_fn=tf.nn.relu, in_layers=[in_layer])
		batch_norm3 = BatchNorm(in_layers=[dense])
		batch_norm3 = Dropout(vars(self.net_param)['dropout'], in_layers=[batch_norm3])
		readout = GraphGather(
			batch_size=batch_size,
			activation_fn=tf.nn.tanh,
			in_layers=[batch_norm3, degree_slice, membership] + deg_adjs)

		if self.error_bars == True:
			readout = Dropout(in_layers=[readout], dropout_prob=0.2)
		# 　添加loss_function
		costs = []
		labels = []
		for task in range(len(self.n_tasks)):
			if mode == "classification":
				classification = Dense(
					out_channels=2, activation_fn=None, in_layers=[readout])

				softmax = SoftMax(in_layers=[classification])
				model.add_output(softmax)

				label = Label(shape=(None, 2))
				labels.append(label)
				cost = SoftMaxCrossEntropy(in_layers=[label, classification])
				costs.append(cost)
			if mode == 'regression':
				regression = Dense(
					out_channels=1, activation_fn=None, in_layers=[readout])
				model.add_output(regression)
				label = Label(shape=(None, 1))
				labels.append(label)
				cost = L2Loss(in_layers=[label, regression])
				costs.append(cost)
			if mode == "classification":
				entropy = Stack(in_layers=costs, axis=1)
			elif mode == "regression":
				entropy = Stack(in_layers=costs, axis=1)
		weights = Weights(shape=(None, len(self.n_tasks)))
		loss = WeightedError(in_layers=[entropy, weights])
		model.set_loss(loss)
		
		def data_generator(datasets, epochs=int(vars(self.net_param)['epochs']),
							predict=False,
							deterministic=ast.literal_eval(vars(self.net_param)['shuffle']),
							pad_batches=True ):
			for epoch in range(epochs):
				if not predict:
					print('Starting epoch %i' % epoch)
				for ind, (X_b, y_b, w_b, ids_b) in enumerate(datasets.iterbatches(
						batch_size, pad_batches=pad_batches, deterministic=deterministic)):
					# print("(X_b, y_b, w_b, ids_b) is:", (X_b, y_b, w_b, ids_b)[0])
					d = {}
					for index, label in enumerate(labels):
						if mode == 'classification':
							d[label] = to_one_hot(y_b[:, index])
						if mode == 'regression':
							d[label] = np.expand_dims(y_b[:, index], -1)
					d[weights] = w_b
					multiConvMol = ConvMol.agglomerate_mols(X_b)
					d[atom_features] = multiConvMol.get_atom_features()
					d[degree_slice] = multiConvMol.deg_slice
					d[membership] = multiConvMol.membership
					for i in range(1, len(multiConvMol.get_deg_adjacency_lists())):
						d[deg_adjs[i - 1]] = multiConvMol.get_deg_adjacency_lists()[i]
					yield d
		if self.is_training:
			model.fit_generator(gene)
			model.save()

		else:
			model2 = tg.load_from_dir("/home/zh/0426") # Load the saved model
			gene = data_generator(self.data,epochs=1, predict=True, pad_batches=False)
			print("load model")

			y = model2.predict_on_generator(generator=gene, transformers=[],outputs=None)
			print("y:", y)

The mistake I got was
`TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a Label into a Tensor`

**Comment by lilleswing** [comment]
Without the definition of tg() I can't tell what is happening here

**Comment by zhouhao-learning** [comment]
@lilleswing 
Please look at me.

**Comment by zhouhao-learning** [comment]
@lilleswing 
This is all my code. Please help me look at it. I didn't quite understand what you just said. How should I correct it?

**Comment by zhouhao-learning** [comment]
@lilleswing 
Thank you very much. Thank you very much. I will try your method tomorrow. Thank you!

**Comment by rbharath** [comment]
Going to close this since it looks like issue was figured out. Please re-open if necessary.
