### ISSUE TITLE
Prediction of TensorGraph model

### ISSUE THREAD

**Issue by Running-z** [deepchem/deepchem#1246]
I use the TensorGraph to build a classification model, use the tox21 data you provide to train and save the model, then I load the saved model, use the'smiles'of tox21 data to predict, but I got the error, I see that you are given the evaluation of the official network, there is no real example of a prediction, I do not know. What should the data of the road forecast be like
This is part of the code I predict

`	               
    model2 = TensorGraph.load_from_dir(model.model_dir) # Load the saved model
			
			def layer_reference(model, layer):
				if isinstance(layer, list):
					return [model.layers[x.name] for x in layer]
				return model.layers[layer.name]
			
			labels = layer_reference(model2, labels)
			weights = layer_reference(model2, weights)
			atom_features = layer_reference(model2, atom_features)
			degree_slice = layer_reference(model2, degree_slice)
			membership = layer_reference(model2, membership)
			deg_adjs = layer_reference(model2, deg_adjs)
			
			gene = generator.data_generator(self.net_param,self.process, self.id,
											self.thread_safe_counter,self.data,
											epochs=1,predict=True,deterministic=False,pad_batches=False,
											labels=labels,weights=weights,
											atom_features=atom_features,degree_slice=degree_slice,
											membership=membership,deg_adjs=deg_adjs)

			print("load model")
			y = model2.predict_on_generator(generator=gene, transformers=[],outputs=None)`

Then I predicted the'smiles'feature of toc21 data, but I got the following error.:
`dataset = loader.featurize(data_file, shard_size=8192)
  File "/home/zh/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 234, in featurize
    shard_generator(), data_dir, self.tasks, verbose=self.verbose)
  File "/home/zh/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 556, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/home/zh/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 218, in shard_generator
    y, w = convert_df_to_numpy(shard, self.tasks, self.id_field)
  File "/home/zh/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 53, in convert_df_to_numpy
    return y.astype(float), w.astype(float)
ValueError: could not convert string to float: 'CCOc1ccc2nc(S(N)(=O)=O)sc2c1'
`

**Comment by zhouhao-learning** [comment]
+1+1

**Comment by rbharath** [comment]
You can use the `predict()` method of `Model` to make predictions. I'm going to go ahead and close this old issue. Feel free to ping here if you still have questions
