### ISSUE TITLE
Using TensorGraph's predict_on_generator () function, the number of predicted results is not correct.

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1247]
When I use predict_on_generator to predict data, I have only 3 data, my batch_size=2, epochs=1, but finally I get 4 results, and I don't understand how this is calculated.
When batch_size=1, I predict that I will get 6 results again. How do I calculate this? I have only 3 data.

**Comment by Running-z** [comment]
@rbharath 
This is my forecast generator code
`        for epoch in range(1):
            for ind, (X_b, y_b, w_b, ids_b) in enumerate(datasets.iterbatches(
                    50, pad_batches=False, deterministic=True)):
                d = {}
                for index, label in enumerate(labels):
                    if self.mode == 'classification':
                        d[label] = to_one_hot(y_b[:, index])
                    if self.mode == 'regression':
                        d[label] = np.expand_dims(y_b[:, index], -1)
                d[weights] = w_b
                multiConvMol = ConvMol.agglomerate_mols(X_b)
                d[atom_features] = multiConvMol.get_atom_features()
                d[degree_slice] = multiConvMol.deg_slice
                d[membership] = multiConvMol.membership
                for i in range(1, len(multiConvMol.get_deg_adjacency_lists())):
                    d[deg_adjs[i - 1]] = multiConvMol.get_deg_adjacency_lists()[i]
                yield d`

This is my prediction code
`model2 = GraphConvTensorGraph.load_from_dir(model_dir)
            generator = Drug_Generator()
            gene = generator.predict_generator(self.net_param, self.process, self.id,
                                            self.thread_safe_counter,
                                            self.data,
                                            labels=model2.labels,
                                            weights=model2.my_task_weights,
                                            atom_features=model2.atom_features,
                                            degree_slice=model2.degree_slice,
                                            membership=model2.membership,
                                            deg_adjs=model2.deg_adjs)

            y = model2.predict_on_generator(gene)
            print(y[0].shape)`

I have only 59 data, three prediction tasks, my batch_size=50, but every task I forecast has got 100 predictions. When I batch_size=40, I get 120 data for each prediction task. Please help me to see why it is.

**Comment by rbharath** [comment]
@zhouhao-learning This is better, but we need an encapsulated small script to debug. We don't know what your dataset here is for example.

Can you construct a minimal failing example for us that we can run directly on our machines? We can't debug until we can easily repro your error.

**Comment by Running-z** [comment]
@rbharath 
This is the data I used to predict.
[test.zip](https://github.com/deepchem/deepchem/files/2011430/test.zip)

**Comment by rbharath** [comment]
I'm going to close this old issue since we're on the verge of removing TensorGraph from DeepChem. Please feel free to re-open if you're having issues with the Keras models.

**Comment by GuangC-Git** [comment]
I recently got this error, which could be very common since the batch_size may not divisible by the whole data perfectly. In the example above, whole data = 3, and batch_size = 2, then there will be 4 predictions, rather 3. I guess it is because the pad_batches=True is set. However, when pad_batches=False is set, the predictions are still 4. Can anyone help explain? Thanks in advance.

**Comment by rbharath** [comment]
@GuangC-Git Could you provide me a failing code snippet? I'm not able to reproduce the error. This runs correctly on my local machine for example:

```
In [1]: import deepchem as dc   

In [2]: import numpy as np      

In [3]: X = np.arange(13)       

In [4]: data = dc.data.NumpyDataset(X)                           

In [5]: data                    
Out[5]: <deepchem.data.datasets.NumpyDataset at 0x1a3790fd30>

In [6]: for (X_batch, _, _, _) in data.iterbatches(batch_size=5, pad_batches=False): 
   ...:     print(X_batch.shape)
   ...:                         
(5,)
(5,)
(3,)

In [7]: model = dc.models.MultitaskClassifier(1, n_features=1, layer_sizes=[16], batch_size=5)                                   

In [8]: model.predict(data).shape                               
Out[8]: (13, 1, 2)
```

I think you might possibly be running an old version of DeepChem. Could you check your version?

**Comment by GuangC-Git** [comment]
Bharath, thanks so much for the information. I tested your code in my machine, and it is good as yours.  However, when I used data_generator and then the fit_generator as well as the predict_on_generator, there will always be errors. I sent you the snippet code and the data via your Gmail. Could you please help me find the problem inside? Thanks.

**Comment by rbharath** [comment]
I took a look at the code you sent over, and I think the error is that
you're still using TensorGraph. I think this padding error only happened up
in the old TensorGraph code. Could you try converting your code to the new
Keras style? You can follow Tutorial 4 as a guide for how to do this:
https://github.com/deepchem/deepchem/blob/master/examples/tutorials/04_Introduction_to_Graph_Convolutions.ipynb

**Comment by GuangC-Git** [comment]
Thanks so much, Bharath. It's very appreciated.
