### ISSUE TITLE
Tensorboard tutorial not working

### ISSUE THREAD

**Issue by Chasearmer** [deepchem/deepchem#1248]
Today I cloned the deepchem repository and tried running the code found in this tensorboard tutorial: https://deepchem.io/docs/notebooks/Using_Tensorboard.html

When I tried to view the tensorboard link after typing: 
`tensorboard --logdir=model.model_dir`
the tensorboard page stated there was no data to view.

Please let me know what additional details to provide.

**Comment by Chasearmer** [comment]
It appears the issue was in the 
`model = GraphConvModel(len(tox21_tasks),  
                                            mode='classification',
                                             tensorboard=True)` line, 
In order to use tensorboard I had to set the `model_dir` keyword argument.
Therefore, my code was 
`model = GraphConvModel(len(tox21_tasks),
                       mode='classification',
                       dropout=0.5,
                       tensorboard=True, model_dir='models/',
                       )`
And my input into the terminal was 
`tensorboard --logdir models/ --port 6006`
I don't know if this was supposed to be an intuitive for those who have already used tensorboard, but this step did not seem to be articulated in the tutorial. 
Please let me know if there is a misunderstanding on my end that I am not aware of.

**Comment by rbharath** [comment]
Good find! We'd welcome a PR that adds this needed information to the tutorial for TensorBoard beginners.

**Comment by lilleswing** [comment]
@Chasearmer your update is correct -- you have to launch tensorboard telling the system where the tensorboard files are (in the model directory).

**Comment by rbharath** [comment]
@Chasearmer Great! Looking forward to seeing your PR. I think the TensorBoard tutorial you're referencing lives here: https://github.com/deepchem/deepchem/blob/master/examples/notebooks/Using_Tensorboard.ipynb

**Comment by Chasearmer** [comment]
#1261

**Comment by mohammad-saber** [comment]
The Tensorboard only shows the validation dataset metric. Is there any way we can show metrics of both train and validation datasets?

**Comment by rbharath** [comment]
I'm not sure of a good way to do this, but I don't use Tensorboard much. Does anyone have suggestions?

**Comment by rbharath** [comment]
Closing this old issue for cleanup. Please feel free to reopen if necessary
