### ISSUE TITLE
Protein ligand binding

### ISSUE THREAD

**Issue by pchanda** [deepchem/deepchem#1255]
How is the data used in the examples located at "deepchem/examples/pdbbind/" featurized ? It will be helpful if the code is shared as there is minimal documentation for deepchem. Also any example on how to use deepchem Graph Convolutions to predict protein-ligand binding is most welcome.

**Comment by lilleswing** [comment]
They are featurized using the RdkitGridFeaturizer
https://github.com/deepchem/deepchem/blob/master/deepchem/feat/rdkit_grid_featurizer.py

**Comment by pchanda** [comment]
Hi Karl,
Thanks for the info, I understand that. However, if there any code I can
refer to that shows how  RdkitGridFeaturizer is being used ? As deepchem
does not have any documentations (other than api's which do not provide any
more info than the code itself), it will be helpful to see any code that
does the featurization using  RdkitGridFeaturizer.
Thanks,
Pritam

**Comment by peastman** [comment]
> As deepchem does not have any documentations (other than api's which do not provide any more info than the code itself)

We also have a pretty big collection of tutorials: https://deepchem.io/docs/notebooks/index.html

**Comment by pchanda** [comment]
I am aware of the tutorials and looked into "Predicting Ki of Ligands to a
Protein". Can you point me to one example that uses  RdkitGridFeaturizer ?

**Comment by rbharath** [comment]
I've just now added a tutorial that works through the `RdkitGridFeaturizer` with recommended settings. The numbering is still moving around, but it's in the tutorials folder. I'm going to close this issue for now. Feel free to reopen if you have questions!
