### ISSUE TITLE
Package deepchem.nn not found

### ISSUE THREAD

**Issue by JJ1991Z** [deepchem/deepchem#1257]
Hi,

I am trying to re-run one the low-data python model examples. But received this following error msg:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-3eb97c9e2a93> in <module>()
     52 
     53 # Train support model on train
---> 54 support_model = dc.nn.SequentialSupportGraph(n_feat)
     55 
     56 # Add layers

AttributeError: module 'deepchem' has no attribute 'nn'

I checked that in the github repo of deepchem, there is no model named as nn. Only in contrib packaged, but no functions in the contrib.nn is named as **SequentialSupportGraph**, **GraphConv**, **GraphPool**etc. 
---------------------------------------------------------------------------
# Add layers
support_model.add(dc.nn.GraphConv(64, n_feat, activation='relu'))
support_model.add(dc.nn.GraphPool())
support_model.add(dc.nn.GraphConv(128, 64, activation='relu'))
support_model.add(dc.nn.GraphPool())
support_model.add(dc.nn.GraphConv(64, 128, activation='relu'))
support_model.add(dc.nn.GraphPool())
support_model.add(dc.nn.Dense(128, 64, activation='tanh'))

Maybe you deleted the nn. package from 2.0.0 deepchem?

**Comment by rbharath** [comment]
@JJ1991Z Yes, good find. The one-shot models have not yet been converted into our new TensorGraph framework. I unfortunately haven't had the time to finish the port (https://github.com/deepchem/deepchem/pull/1084). If someone is interested in taking on the task, I'd love to see this happen though.
