### ISSUE TITLE
Operation error in Measuring Model Uncertainty Application Tutorial

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1263]
Your official website has an application tutorial called "Measuring Model Uncertainty", which uses the "MultiTaskRegressor" and "model.predict_uncertainty" functions, but when I run, I get a mistake without the "predict_uncertainty" function, why?

This is the running code
```
tasks, datasets, transformers = dc.molnet.load_sampl()
train_dataset, valid_dataset, test_dataset = datasets

model = dc.models.MultiTaskRegressor(len(tasks), 1024, uncertainty=True)
model.fit(train_dataset, nb_epoch=200)
y_pred, y_std = model.predict_uncertainty(test_dataset)
```

This is a mistake
`AttributeError: 'MultiTaskRegressor' object has no attribute 'predict_uncertainty'`

**Comment by abster12** [comment]
Yeah the MultiTaskRegressor has been renamed to MultitaskRegressor that is why you are getting that error.

**Comment by zhouhao-learning** [comment]
@abster12 
But your official web application is not updated. No one knows you have changed the function name.

**Comment by abster12** [comment]
We must have missed it somehow , it will be updated .

**Comment by zhouhao-learning** [comment]
@abster12 
Your "MultiTaskRegressor" has been renamed "MultitaskRegressor", but I can not get the "MultitaskRegressor" function now.

这是个错误
`y_pred, y_std = model.predict_uncertainty(test_dataset)`

**Comment by peastman** [comment]
Both these changes (predicting uncertainty and renaming "MultiTask" to "Multitask") were made since 2.0 was released.  You can either use the development code, or wait for the next release.

There's a bit of a dilemma with the tutorials on the website.  Should they match the latest release, or the current development code?  Either way, they'll sometimes be incorrect for some users (either ahead of or behind the code they're using).

**Comment by rbharath** [comment]
We may want to have a stable version of the tutorials and also a HEAD version for developers.

**Comment by rbharath** [comment]
I've revamped the uncertainty tutorial and it should now run correctly. Going to go ahead and close this old issue.
