### ISSUE TITLE
Need an amino acid fasta encoder as well as nucleotide.

### ISSUE THREAD

**Issue by TBomberman** [deepchem/deepchem#1268]
https://github.com/deepchem/deepchem/blob/2817b1372c3fb787d2e2934c0bcc34b5f7e2a764/deepchem/utils/save.py#L134

**Comment by rbharath** [comment]
This would be a nice feature. I'm going to label it contribution welcome.

**Comment by tshauck** [comment]
Biopython has an [`Alphabet`](http://biopython.org/DIST/docs/api/Bio.Alphabet-module.html) object which would probably work well here. It might it easier to support a wider variety of biological sequences.

Thoughts on adding it as a dependency vs a deepchem specific solution? Let me know what you have in mind scope-wise, and I can take a stab at this.

**Comment by rbharath** [comment]
@tshauck Yes, we'd be quite receptive to adding a `biopython` dependency. We've chatted about it a few times in the past already. Contribution would be welcome!

I think to start, maybe a simpler scope for the first PR for reviewing and debugging ease. As we figure out how to support the `biopython` dependency well, I think we'd be glad to see support for a wide variety of biological sequences.

**Comment by tshauck** [comment]
@rbharath I've opened a PR [here](https://github.com/deepchem/deepchem/pull/1278) to get feedback, thanks!

**Comment by tshauck** [comment]
I think this can be closed with the merging of deepchem/deepchem#1278.

**Comment by TBomberman** [comment]
I am new to open source development but how is testing conducted?

**Comment by tshauck** [comment]
@TBomberman You can see the PR here: https://github.com/deepchem/deepchem/pull/1278. In particular the tests are here: https://github.com/deepchem/deepchem/pull/1278/files#diff-e0f7ba235d6fb0313ace07dee2fcfcce.

In short, I created a mock fastq and fasta files with random letters. The function call is `encode_bio_sequence` which accepts a set of letters which are contained within the sequence. For fasta files with proteins something like:

```
from Bio.Data.IUPACData import extended_protein_letters
encode_bio_sequence("my-file.fasta", letters=extended_protein_letters)
```
