### ISSUE TITLE
The same model predicts the same data prediction, but the result is different.

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1270]
Why do I use the same trained model to predict the same number of data, the results of the first and second predictions are completely different, or even different? The same model predicts the same data, and should not be exactly the same?
In my previous deep learning image recognition process, I used a trained model to predict the same data. No matter how many times I predict, the final results are the same.

The model I used is GraphConvTensorGraph, and the data for training and prediction are your sample data tox21.csv.

Can you give me an explanation?

**Comment by lilleswing** [comment]
Hi @zhouhao-learning can you give me a complete working test case which shows this?  This should not be happening but I can't help without a working example.

**Comment by zhouhao-learning** [comment]
@lilleswing 
Hello, I prepared my data processing, training, prediction code, and test data. Can you help me to test it? In addition, my training function is extracted from deepchem alone, so I quoted your class.
[test.zip](https://github.com/deepchem/deepchem/files/2035896/test.zip)

**Comment by lilleswing** [comment]
@zhouhao-learning can you please make it a working reproduction of your issue.  While trying to run this code I am seeing bugs unrelated to your issue.

```bash
Traceback (most recent call last):
  File "train_predict.py", line 249, in <module>
    train_()
  File "train_predict.py", line 224, in train_
    weights=model.my_task_weights,
AttributeError: 'GraphConv_fit' object has no attribute 'my_task_weights'

```

**Comment by zhouhao-learning** [comment]
@lilleswing 
Sorry, maybe I just ignored a detail problem when I just picked up the code. I'm now in the early hours of the morning, the computer isn't around, and I'll give you a code instance that I've got to you tomorrow morning! Sorry

**Comment by zhouhao-learning** [comment]
@lilleswing 
Hello, I gave you the test code that I would run normally and did not return any error. The deepchem version I used is a formal version of 2.0.0, where my "GraphConv_fit" class is a "GraphConvTensorGraph" class inherited from deepchem.
"My_task_weights" object is defined when building a model, isn't it?
![05050505050505](https://user-images.githubusercontent.com/24581773/40521021-fd98bd34-5ffb-11e8-9dde-0d7641f4b970.png)

**Comment by zhouhao-learning** [comment]
@lilleswing 
Excuse me, can you run the test code properly? What is the reason for this problem?

**Comment by zhouhao-learning** [comment]
@lilleswing 
Hello! Do you have time to see my reply? I haven't solved this problem yet, but my code is really able to run.

**Comment by rbharath** [comment]
@zhouhao-learning We're quite sympathetic, but we need a simpler minimal failing code sample to debug. Ideally, a minimal failing sample is < 30 lines and can be posted directly on the Github issue or in an associated gist.

**Comment by zhouhao-learning** [comment]
@rbharath 
This file contains my test code and part of the test data. Can you look at it?
[test_code.zip](https://github.com/deepchem/deepchem/files/2067761/test_code.zip)

**Comment by zhouhao-learning** [comment]
@lilleswing 
I have simplified my test code and data again. Can you help me see why my prediction results are different each time?
[test_code.zip](https://github.com/deepchem/deepchem/files/2078614/test_code.zip)

**Comment by rbharath** [comment]
@zhouhao-learning Took a look at. There doesn't appear to be a `__main__`. Can you change it so running the script will reproduce your error?

**Comment by zhouhao-learning** [comment]
@rbharath @rbharath 
OK, well, I revise the code, you just need to modify the model_dir path in the code, then execute the python train_predict.py, and then output the prediction results, then you need to annotate the train () function, and then execute the train_predict.py file, and you can find that the predicted results are not the same.
[test_code.zip](https://github.com/deepchem/deepchem/files/2082610/test_code.zip)

**Comment by zhouhao-learning** [comment]
@rbharath 
Do you have a problem with me?

**Comment by rbharath** [comment]
@zhouhao-learning We're genuine in our desire to help, but please realize that we work on this repo on our personal time; it is currently 11pm on a Sunday evening for me. We can help debug, but we expect respectful behavior in return. 

Please consider this a warning under our code of conduct.

https://github.com/deepchem/deepchem/blob/master/CODE_OF_CONDUCT.md

On this particular issue, can you simplify the code so we don't need to manually modify to reproduce?

**Comment by zhouhao-learning** [comment]
@rbharath @rbharath 
Well, thank you very much. I'm now providing my sample code. You can just execute it and you can get the prediction results. You'll find that each execution gets different predictions, but I guarantee that each model is the same, because I've trained a model in this article. Inside

[test_code.zip](https://github.com/deepchem/deepchem/files/2094574/test_code.zip)

**Comment by fmonta** [comment]
Hello,
I have observed something similar with v2.1.  I trained a GraphConvModel, saved it using model.save(). Then I pick 5 molecules, featurize them, load the trained model and run model.predict(dataset). I receive every time different predictions for the same 5 molecules and the same trained model. If that helps, the model was trained with dropout and uncertainty enabled but at prediction time I want to use predict() and not predict_with_uncertainty(). Hope you can help me figuring out how to overcome that problem.

**Comment by rbharath** [comment]
@zhouhao-learning Sorry, this thread slipped off my radar for a long while. Are you still having issues here? If so can you make a short code snippet that we can look at? (A zip file isn't as friendly to deal with for us)
