### ISSUE TITLE
The tuning of  parameters when added new classifiers

### ISSUE THREAD

**Issue by herbert0525** [deepchem/deepchem#1271]
From our point of understanding, the graph convolution model in your scripts is mainly used for the extraction of features,  thus the features are used for classification or regression. Therefore we are about to add some new classifiers, e.g. RF, SVM, DNN. So I wonder when it comes to the tuning of parameters, what should we count on more,  the parameters of the graph convolution model or those of the new classifiers? Thanks.

**Comment by lilleswing** [comment]
@herbert0525 I'm not sure what you are asking.

You can use our graph models to generate a "nerual fingerprint" and then use other models over it.  Currently the "neural fingerprint" is a learned representation which is optimal for having a linear relationship with this response variable.

We already support RF, SVM etc through our SklearnModel.
https://github.com/deepchem/deepchem/blob/master/deepchem/models/sklearn_models/__init__.py

**Comment by herbert0525** [comment]
@lilleswing Well, you mean the process of generating a fingerprint in your graph models can hardly be optimized, that's my understanding. Thus for a given dataset, the optimization will only be performed in the models used over the fingerprint, is that correct...
