### ISSUE TITLE
Don't fully understand what GraphConv Layer does

### ISSUE THREAD

**Issue by Chasearmer** [deepchem/deepchem#1275]
**Description:**
I've read the source code for the GraphConv layer a few times now and unfortunately I still don't quite understand it. I also read the paper suggested to me by Karl that the GraphConv is based on, but I still don't feel I fully understand what the deepchem layer is doing, which makes it difficult for me to know how to improve the layer and use it effectively. Could we discuss what the layer does and the reasoning behind it here for future contributors and myself to view?

**Comment by rbharath** [comment]
@Chasearmer Could you explain the parts you feel like you get and the parts that you feel aren't clear? We can fill in the details from there.

**Comment by Chasearmer** [comment]
Yeah of course. I understand that the object passed to the GraphConv layer is a ConvMol, and I understand that the atoms are grouped by degree for the operations. What I do not understand is what sum_neigh does, what rel_atoms are vs. self_atoms, why both rel_atoms and self_atoms have a mat_mul operations and area then summed, and how at the end of this a fixed length vector is created.

**Comment by Chasearmer** [comment]
My current hypothesis for sum_neigh is that it sums the atom vectors of an atom's neighbors into one vector. These are referred to as rel_atoms, while the original atom is referred to as self_atoms. However I do not understand why these are summed. Additionally, I do not understand how this creates a fixed length vector. 

My understanding is that one of the main benefits of GraphConv is that it can receive a molecule with a variable number of atoms, apply a weight matrix to each atom, then return a fixed length vector (which traditional dense layers cannot do since they must received fixed size data). However, I still do not understand how this fixed length vector is created.

**Comment by rbharath** [comment]
Couple brief responses:
- Neighbors are summed to communicate information. The vector for an atom should at each layer incorporate in information from its neighbors. 
- Not sure what you mean by fixed length. If each atom has a vector of length n pre summation, it will have one of length n post summation.
- At the very end, the `GraphGather` sums all atom vectors. So if there are m atoms, each with a local vector of length n and all of these are summed, the output is of length n and doesn't depend on m.

**Comment by Chasearmer** [comment]
@rbharath Thank you for the response, by fixed length vector I was referring to what you described `GraphGather` as doing. I was looking for that functionality in GraphConv itself since I thought it summed all of the atom features of a molecule together such that the dense layers would extract features from molecule vectors and not atom vectors. Thank you that clears up my confusion
