### ISSUE TITLE
Extract first task in Dataset

### ISSUE THREAD

**Issue by sophia-wright-blue** [deepchem/deepchem#1280]
How do I extract the data for the first task in train_dataset?

I have the code:

```
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()
train_dataset, valid_dataset, test_dataset = tox21_datasets
```

train_dataset contains many tasks. I would like to extract the first task. I tried different ways, but could not get it to work. Thank you.

**Comment by peastman** [comment]
The easiest way is just to pull out the individual arrays: `dataset.X[:,0]`, `dataset.y[:,0]`, and `dataset.w[:,0]`.  For larger datasets you might not want to load the whole thing in memory at once, so you could use `iterbatches()` to get the arrays for smaller batches of samples.  Tox21 is small though, so that isn't necessary here.

**Comment by sophia-wright-blue** [comment]
Thank you for your reply. I'm trying to modify the following code to only train the first task:

```
model = dc.models.SingletaskToMultitask(tox21_tasks, model_builder, model_dir)

# Fit trained model
model.fit(train_dataset)
```

I can extract the first task from tox21_tasks by doing tox21_tasks[0]. The next line: model.fit requires just one argument. Instead of giving it all of the data in train_dataset, which throws an error, I'd like to give it the data for just the first task, so do something like 

```
model.fit(train_dataset[:,0])
```

What is the best way to pass the argument to model.fit for the first task only?

Thank you,

**Comment by peastman** [comment]
I think something along these lines will do what you want.

```python
dataset = NumpyDataset(train_dataset.X[:,0], train_dataset.y[:,0], train_dataset.w[:,0])
model.fit(dataset)
```
