### ISSUE TITLE
Graph conv Weights_28/Placeholder dimension mismatch

### ISSUE THREAD

**Issue by timaro** [deepchem/deepchem#1281]
**Description:**

Trying to train a GraphConvTensorGraph, I get the following exception with DeepChem HEAD:

```
File "/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 153, in fit
    max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
  File "/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 257, in fit_generator
    fetched_values = self.session.run(fetches, feed_dict=feed_dict)
  File "/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100,) for Tensor 'Weights_28/Placeholder:0', which has shape '(?, 1)'
```

This exception does not happen on the same code, when using the most current release version.

- DeepChem Version: HEAD (2.0.1.dev250; commit 1b171da623799b47871b95349b96ff2b139e3f41)
- Platform: Ubuntu 16.04
- Relevant libs: tensorflow-gpu  1.6.0

**Comment by peastman** [comment]
Can you provide example code to reproduce the problem?  TensorGraph is supposed to automatically add or remove dimensions of size 1 as necessary to make the values in the dataset match the expected inputs.

**Comment by timaro** [comment]
I'm doing nothing special: creating a GraphConvTensorGraph and calling
fit():

model = GraphConvTensorGraph(1, batch_size=100, mode="classification")
model.fit(data, nb_epoch=10)

The data instance is a NumpyDataset with dimensions:

data.X.shape -> (9910,)
data.y.shape -> (9910, 1)

Again, the training works correctly on release 2.0. It's only HEAD that is
failing. I see that you made a commit on the NumpyDataset file in the past
two days related to reshaping, so perhaps that's related...

**Comment by timaro** [comment]
Yes, reverting commit 2fba2bbcd68e7a145e7fdd584f8b19b75d875b95 fixes the problem.

**Comment by peastman** [comment]
I don't suppose you can provide a self contained test case?  I've been trying to put something together, but without success.  Here's where TensorGraph reshapes the input arrays: https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py#L1297-L1309.  As far as I can tell it's working correctly.  Something must be different about your case, but I'm not sure what.

**Comment by timaro** [comment]
See my comment on the PR. I've already isolated the bug: it is entirely
attributable to removal of the reshape calls on the NumpyDataset class. For
inputs of shape (N,), they were formerly converted to shape (N, -1), but
now are not. Fixing this is enough to satisfy Tensorflow.

Essentially, the old code (before your commit) allowed inputs of form
np.array(N), and the new code (after your commit) does not.

**Comment by timaro** [comment]
To answer your specific question re:TensorGraph line 1297-1309, the code is never getting there. It's failing at line 257:

https://github.com/deepchem/deepchem/blob/9b13b31a3171ad812448c75547a0d5ab2ed84264/deepchem/models/tensorgraph/tensor_graph.py#L257

Which, from the backtrace, appears to be at the point when tensorflow is initializing placeholder variables. AFAICT, no data is loaded.

**Comment by peastman** [comment]
The old code was simply wrong.  It caused a lot of problems, and we fixed it.  It turns out there was other code relying on that incorrect behavior, so now we have to fix the other code too.

> To answer your specific question re:TensorGraph line 1297-1309, the code is never getting there. It's failing at line 257:

They're on different threads.  Here's where a thread gets started to feed the queue by calling `_enqueue_batch()`:

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py#L226-L230

When `session.run()` gets called at line 257, it pulls those batches off the queue.

**Comment by timaro** [comment]
Yes, I saw that. I set a breakpoint inside the thread and it never tripped. I then made a deduction (possibly incorrect) that the exception message was correctly worded, and referencing placeholders for weights, not data.

Regardless, the *cause of the exception seems unambiguous*: I'm passing in a y-value tensor of shape (N,), which the 2.0 release code handled. The code in HEAD now expects shape (N, 1). When run my code on HEAD, and set a breakpoint in the `NumpyDataset` initializer, my X and y values have the following shapes:

```
(Pdb) X.shape
(9882,)
(Pdb) y.shape
(9882,)
```

The 2.0 code was silently reshaping this to `(N, 1)` (which was the shape I originally reported on this issue; my mistake) but the HEAD code is no longer doing this, and tensorflow is barfing on the dimension mismatch. Restoring the reshape call fixes the crash.

It's not at all clear to me if you intend the code at:

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py#L1297-L1309

to handle this case, or if you expect callers to reshape their data before `NumpyDataset` creation?

**Comment by peastman** [comment]
> I then made a deduction (possibly incorrect) that the exception message was correctly worded, and referencing placeholders for weights, not data.

It's referring to the dataset's `w` matrix.

> or if you expect callers to reshape their data before NumpyDataset creation?

No, callers are not required to reshape their data.  TensorGraph is supposed to be smart enough to handle it.  That's why I really need a way to reproduce this.  In all my tests it's working fine.  Clearly there is something different about your case, but since I haven't seen your code or your dataset, it's impossible for me to know what.

**Comment by timaro** [comment]
I've described exactly what I'm doing. There's nothing fancy or different.
Again:

* My X values are an N-length python list of ConvMol instances
* My Y values are an N-length python list of integers (binary values)

(X and Y have identical lengths. They are both simple, 1D python lists.)

These are wrapped in np.array, and passed into the initializer for a
NumpyDataset:

```NumpyDataset(np.array(train[0]), np.array(train[1]))```

The dataset is used to fit a model:

```
model = GraphConvTensorGraph(1, batch_size=100, mode="classification")
model.fit(data, nb_epoch=10)
```

The code fails at the call to fit(). Restoring the reshape fixes the
problem. Likewise, if I reshape my Y values to (N,1) in my own code, the
fitting succeeds.

**Comment by timaro** [comment]
Update:

The reason the tensors aren't being reshaped is because the queueing code is never being called at all. GraphConvModel explicitly sets use_queue to false:

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/models/graph_models.py#L601

**Comment by peastman** [comment]
Thanks!  Those extra details gave me the clue to figure out what was different between your test and mine.  I can now reproduce this.  I'll try to get a fix in within the next few days.

Does anyone know why GraphConvModel is disabling the queue?  Was that done for a good reason?
