### ISSUE TITLE
Molecular melting point test

### ISSUE THREAD

**Issue by luwry** [deepchem/deepchem#1287]
The kernel appears to have died. It will restart automatically.
`loader = dc.data.CSVLoader(
      tasks=["MTP"], smiles_field="SMILES",
      featurizer=featurizer)
dataset = loader.featurize(dataset_file)`
how can i solve this problem.I do not know why MTP can not use this featurizer.If i need update ipython.

**Comment by rbharath** [comment]
Closing this issue. Feel free to discuss further in #1289

**Comment by luwry** [comment]
@rbharath thanks your reply! I try it again.It occurs the same problem.
Here is program running process：
wangrenyu@wangrenyu-VirtualBox:~$ python Untitled8.py
/home/wangrenyu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Columns of dataset: ['smiles' 'logp' 'solubility']
Number of examples in dataset: 1164
<IPython.core.display.HTML object>
Loading raw samples now.
shard_size: 8192
About to start loading CSV from ../../home/wangrenyu/mtp/delaney.csv
Loading shard 1 of size 8192.
Featurizing sample 0
段错误 (核心已转储)
