### ISSUE TITLE
delaney-processed dates question

### ISSUE THREAD

**Issue by luwry** [deepchem/deepchem#1289]
**when i use this model to predict molecular melting point,i met some questions that i can not solve **
when i run this code:
loader = dc.data.CSVLoader(
      tasks=["mtp"], smiles_field="smiles",
      featurizer=featurizer)
dataset = loader.featurize(dataset_file)
the problem:
The kernel appears to have died. It will restart automatically.

**Comment by luwry** [comment]
IF the modeling solubility example can not predict molecular melting point?

**Comment by rbharath** [comment]
@luwry The model should be able to predict molecular melting point provided a good molecular melting point dataset. I'm not sure why the kernel is crashing though. Could you try running in a plain python script and providing the error message?

**Comment by rbharath** [comment]
I've just refreshed the solubility tutorial, and it should now run fine. Can you take a look there?

Going to go ahead and close this issue. Please re-open if you're still having issues!
