### ISSUE TITLE
Errors in Examples 

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#1297]
**Description:**

- DeepChem Version: master
- Platform: linux

The following examples currently throw exceptions on master.  
Checklist is for fixing them one at a time.

- [ ] binding_pocket_rf.py
- [x] sweet.py
- [x] membrane_permeability_graph_conv.py
- [x] bace_rf.py
- [x] qm7_BPSymmetryFunction.py
- [x] qm7_sklearn.py
- [x] hopv_graph_conv.py
- [ ] run_benchmarks.py
- [x] sampl_graph_conv.py
- [x] ~~sider_alternate_weave.py~~
- [x] chembl_tf_models.py
- [x] qm7b_DTNN.py
- [x] chembl_graph_conv.py

**Comment by peastman** [comment]
I'll start going through some of these.  I'm working on chembl_graph_conv.py right now.

**Comment by peastman** [comment]
chembl_graph_conv.py is fixed (though I'm not sure if the results are correct).  Working on qm7b_DTNN.py.

**Comment by peastman** [comment]
qm7b_DTNN.py and chembl_tf_models.py are both fixed.  (I'll send a single PR with multiple fixes in a bit.)

**Comment by peastman** [comment]
sider_alternate_weave.py uses `AlternateSequentialWeaveGraph`, which has been moved into contrib.  I don't know how we want to handle that.  Possibly just remove the example?

**Comment by peastman** [comment]
There are a bunch of examples that use `SequentialGraph`, which has been moved to contrib.  None of those currently work.  That includes some that aren't on the list above: muv_graph_conv_one_fold.py, sider_graph_conv_one_fold.py, and tox_graph_conv_one_fold.py (as well as sampl_graph_conv.py, which is on the list).

**Comment by peastman** [comment]
bace_rf.py is really seriously out of date.  I started trying to fix it, but just kept running into one problem after another, including functionality that seems to work in significantly different ways today than when the example was written.  I think I'm going to ignore that one for the moment.

**Comment by peastman** [comment]
sweet.py is another seriously messed up example.  It even includes hardcoded paths to locations in someone's home directory, which means it could never have worked on any other computer.

**Comment by rbharath** [comment]
Let's just remover sider_alternate_weave.py since we're not supporting that model anymore.

The one-shot models need to be ported to TensorGraph; a long standing TODO for me...

**Comment by rbharath** [comment]
Fixed `qm7_sklearn.py` in #1305

**Comment by rbharath** [comment]
Verified that qm7_BPSymmetryFunction.py now runs on head so ticking it off as well.

**Comment by rbharath** [comment]
Verified `chembl_tf_models.py` now runs on HEAD

**Comment by rbharath** [comment]
@lilleswing `run_benchmarks.py` isn't in examples. Did you mean `benchmark.py`?

**Comment by rbharath** [comment]
I think `binding_pocket_rf` does run, but requires that the user download the full PDBBind dataset to run properly. I'm currently with low internet, so can't verify that it works by downloading.

**Comment by rbharath** [comment]
Closing since I believe all examples have been fixed.

**Comment by li-aolong** [comment]
@rbharath I've downloaded the full PDBBind dataset, but there was a error when running `binding_pocket_rf`:
```
Processing complex 65, 4bgx
Processing complex 66, 3f39
WARNING:root:Unable to add hydrogens math domain error
Traceback (most recent call last):
  File "/home/hp/anaconda3/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 55, in add_hydrogens_to_mol
    fixer.addMissingHydrogens(7.4)
  File "/home/hp/anaconda3/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
    modeller.addHydrogens(pH=pH)
  File "/home/hp/anaconda3/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 749, in addHydrogens
    if isHbond(nd1Pos, hd1Pos, acceptorPos):
  File "/home/hp/anaconda3/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 681, in isHbond
    return acos(dot(deltaDH, deltaHA)) < 50*degree
  File "/home/hp/anaconda3/lib/python3.5/site-packages/simtk/unit/unit_math.py", line 103, in acos
    return math.acos(x) * radians
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "binding_pocket_rf.py", line 25, in <module>
    split=split, subset=subset)
  File "/home/hp/deepchem/examples/binding_pockets/binding_pocket_datasets.py", line 151, in load_pdbbind_pockets
    
  File "/home/hp/deepchem/examples/binding_pockets/binding_pocket_datasets.py", line 131, in featurize_pdbbind_pockets
    pdb_subdir = os.path.join(pdbbind_dir, pdb_code)
  File "/home/hp/deepchem/examples/binding_pockets/binding_pocket_datasets.py", line 28, in compute_binding_pocket_features
    dc.dock.binding_pocket.extract_active_site(
  File "/home/hp/anaconda3/lib/python3.5/site-packages/deepchem/dock/binding_pocket.py", line 28, in extract_active_site
    protein_file, add_hydrogens=False)[0]
  File "/home/hp/anaconda3/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 123, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "/home/hp/anaconda3/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 66, in add_hydrogens_to_mol
    raise MoleculeLoadException(e)
deepchem.utils.rdkit_util.MoleculeLoadException
```

**Comment by rbharath** [comment]
Thanks for the report. It looks like this code is still a little buggy. Re-opening this issue to coordinate debugging.

**Comment by rbharath** [comment]
We're planning on doing a sweep through the examples before the 2.4 release, so going to close this old issue. Will open a new issue to coordinate as necessary.
