### ISSUE TITLE
How to get hidden features of MultitaskFitTransformRegressor()?

### ISSUE THREAD

**Issue by DorisMai** [deepchem/deepchem#1299]
**Description:**

- DeepChem Version: 2.0.0
- Platform: linux

 Is it possible to retrieve hidden features of a model? I would like to get the features/input of the last layer of MultitaskFitTransformRegressor(). 

I was able to get the output tensor of the layer before the last layer by
```
out_tensor = model.layers['Dense_2'].out_tensor
```
However, none of the following attempts of using eval() to convert the out_tensor to nparray succeeded:
i) `out_tensor.eval()` This gives the following error:
> ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

ii) 
```
with tf.Session() as sess:
        t.eval(sess)
```
This gives the following error: 
> ValueError: Cannot use the default session to evaluate tensor: the tensor's graph is different from the session's graph. Pass an explicit session to `eval(session=sess)`.

iii) `t.eval(session=model.session)` This line has been running for an hour but still hasn't returned anything. The model has only 3 Dense layers (qm9_tf_model.py).

**Comment by peastman** [comment]
When you call `predict()` on the model (or any of the other prediction methods like `predict_on_generator()` or `predict_on_batch()`), you can use the `outputs` argument to compute something other than the model's default output.  You can't evaluate a single layer in isolation, because it generally won't have a single defined value.  The value of an output depends on what inputs you provide to the model.

**Comment by DorisMai** [comment]
Ah I never noticed that for predict(). So to get the last hidden feature, should I pass the second to last layer as the output? 
Also, why doesn't a layer has a single defined value? After training, shouldn't the weights and biases be fixed?

**Comment by peastman** [comment]
> So to get the last hidden feature, should I pass the second to last layer as the output?

That depends on the details of the model, and what you mean by "the last hidden feature".  Some layers correspond to the major building blocks you see in model diagrams, like Dense or Conv2D.  Others are more minor calculations, like Cast or ReduceMean.  You'll need to figure out which layer you want to query.

>  Also, why doesn't a layer has a single defined value? After training, shouldn't the weights and biases be fixed?

The output of a layer depends both on its parameters (like weights and biases) and also on its inputs.  For example, a dense layer computes its output as `y = w*x + b`.  You can't compute `y` if you haven't specified `x`.

**Comment by DorisMai** [comment]
I see. Thank you for your explanation!
