### ISSUE TITLE
Bump TensorFlow version on Conda install

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1312]
The TensorFlow instruction on the conda install line installs TensorFlow 1.5. We should bump this up
```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.0.0 python=3.5
```
There are probably other package versions that we should bump as well. Might be fine to do this as part of 2.1 since I think we're about ready to make the cut.

**Comment by lilleswing** [comment]
yes we also need to bump rdkit.  I'll do a big bump after I create the conda and docker builds.

**Comment by rbharath** [comment]
Closing this since implemented.
