### ISSUE TITLE
Weights for tasks

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#1316]
Hello,

is there a designed way to set weights for each task (not for each sample)?

**Comment by peastman** [comment]
The weights are an array of shape (n_samples, n_tasks).  If you set all the elements in each column to be the same, that's a weight per task.

**Comment by allchemist** [comment]
Hm, seems overkill, but very simple. Thanks!

**Comment by rbharath** [comment]
Closing since issue seems resolved.
