### ISSUE TITLE
Extract trained weights from TensorGraph Layer

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1317]
There doesn't appear to be a standard API for extracting trained weights from a `Layer` object at present. If the layer is in eager mode, then `layer.variables` stores the associated `Variable` objects. Otherwise, `layer.variables` isn't set.

What would a good standard API for extracting trained weights look like?

**Comment by rbharath** [comment]
Here's one way to get the variable associated with a layer:
```
variables = model._get_tf("Graph").get_collection("variables", scope=layer.name)
```
To evaluate these variables, you can run
```
weights = model.session.run(variables)
```
This could be wrapped up into a convenience function `layer.get_weights()`

**Comment by peastman** [comment]
`TensorGraph.get_layer_variables()` is what you want.  It's a method of TensorGraph because it owns the Graph the variables are defined in.

**Comment by rbharath** [comment]
@peastman Great, thanks for the pointer! How would you feel about adding in a `TensorGraph.get_layer_weights()` convenience method? Will make weight inspection examples and tutorials read nicer.

If this sounds good, will go ahead and open up a PR for this

**Comment by peastman** [comment]
That makes sense.

**Comment by VIGS25** [comment]
I will work on this during the weekend.
