### ISSUE TITLE
Location for genomic utility functions

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1318]
There are currently a number of genomic utility functions in `deepchem.utils.save` such as `seq_one_hot_encode`, `encode_fasta_sequence`, and `encode_bio_sequence`. These should be moved out to elsewhere in DeepChem, perhaps to a new submodule `deepchem.utils.genomics` or the like.

**Comment by rbharath** [comment]
We now have `deepchem.utils.genomics`. These utility functions should be moved over. This would be a good first PR for a new contributor.

**Comment by vsag96** [comment]
I'll do this, my idea is to have the functions in the deepchem.utils.save as well as deepchem.utils.genomics and if someone tries to run the function from save  I'll issue a warning, it'll work and you can decide when to completely remove it from deepchem.utils.save sounds good? 

Also is there an example using  these functions so I can be sure to see that I didn't break anything. I'll open a PR with wip
