### ISSUE TITLE
Dynamic transformation during model.fit

### ISSUE THREAD

**Issue by joegomes** [deepchem/deepchem#132]
For certain problems it would be advantageous to transform data on-the-fly as it is given to `model.fit`.  We should modify the `Model` class to accept a `Transformer` object and transform each minibatch during training.

**Comment by joegomes** [comment]
Started a PR #142 to add this

**Comment by rbharath** [comment]
The merge of #262 should make this easier. Since all `Transformer` objects can now transform `NumpyDataset`, on-the-fly transformations should be easier to support and handle.

**Comment by joegomes** [comment]
@rbharath Resolved in #377.
