### ISSUE TITLE
Generator source code error using Weave model

### ISSUE THREAD

**Issue by Running-z** [deepchem/deepchem#1326]
I want to use the Weave model to train the tox21 data, then I extract the generator source code from the Weave model, and then build the model training, but in the generator I get the source error report:

```
File "/home/zh/anaconda3/envs/deepchem2.0.0/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1093, in _create_feed_dicts
    for d in generator:
  File "/project/git2/WewoDL/dl/io/drug_generator.py", line 196, in weave_train
    feed_dict[pair_split] = np.array(pair_split)
TypeError: unhashable type: 'list'

```
Below is my generator code:
[WeaveModel.zip](https://github.com/deepchem/deepchem/files/2216455/WeaveModel.zip)

**Comment by rbharath** [comment]
Sorry for the very slow reply on this issue. I'm able to train Weave models successfully on the latest version of DeepChem. Are you still facing issues here?
