### ISSUE TITLE
Modify DiskDataset.from_numpy so DiskDataset.from_numpy(X) works

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1349]
Currently, `DiskDataset.from_numpy` expects at least features `X` and labels `y` to be provided. This makes it inconvenient to store datasets that lack labels to disk. (Datasets without labels pop up in tasks such as autoencoding for example). We should make a modification to remove this limitation.

**Comment by VIGS25** [comment]
Working on this.
Should raise a PR soon.

DiskDataset.write_data_to_disk() has no problems with saving even when y = None.
