### ISSUE TITLE
How to install without conda environment

### ISSUE THREAD

**Issue by hsiaoyi0504** [deepchem/deepchem#1350]
It will be good to have an option to truly install deepchem from source (rather than in a conda environment). Recently I found that there is an issue to install deepchem with r-base package from r channel at the same time. I have met so many conda environment problems to install deepchem with other packages like cario, different rdkit scikit-learn versions.

**Comment by hsiaoyi0504** [comment]
It looks like I can just install `deepchem` through `pip install .`. However, it will not install any prerequisite, right ?

**Comment by rbharath** [comment]
I believe the `pip install` is broken since RDKit doesn't work with pip at present. 

@lilleswing can probably say more

**Comment by peastman** [comment]
We should see whether we can reduce the number of dependencies for DeepChem, or at least make more of them optional.  A few times recently I've run into problems where I wanted to use another library with DeepChem, but they had mutually incompatible dependencies.  This leads to a lot of pain and suffering that could be reduced if there weren't so many hard dependencies.

**Comment by rbharath** [comment]
Definitely agree. I've run into the same issue. Often have to make an isolated conda environment to work with DeepChem which makes it tricky to use sometimes

**Comment by hsiaoyi0504** [comment]
Another thing is that although rdkit can’t be installed by pip, it can be built from source with cmake.

**Comment by peastman** [comment]
Also, rdkit is right at the top of the list of libraries I'd like to see made into soft dependencies.  It causes a lot of problems, and lots of parts of DeepChem don't need it.

**Comment by peastman** [comment]
I see six libraries that currently are hard dependencies for DeepChem (you can't `import deepchem` without them): rdkit, joblib, six, scikit-learn, pandas, and dnasim.

We only use six in a couple of places, and not for anything very complicated, so it would be quite easy to eliminate that as a dependency.  dnasim is only used in two files, so it should be easy to turn it into soft a dependency.

rdkit is used in a lot of places, but none of them are core architecture.  Given all the problems it causes, there would be a lot of value in putting in the work to turn it into a soft dependency.

joblib and pandas are both used by Dataset, and Model extends a sklearn class, so I think those probably need to remain hard dependencies.

**Comment by peastman** [comment]
And of course Tensorflow.  That clearly needs to remain a hard dependency.

**Comment by rbharath** [comment]
I like the idea of turning rdkit, six, and dnasim into soft-dependencies. Will make install easier and make a pip install version of DeepChem feasible! (sans rdkit...)

**Comment by rbharath** [comment]
Opened https://github.com/deepchem/deepchem/pull/1454 to shift `rdkit` into a soft dependency.

**Comment by rbharath** [comment]
Opened https://github.com/deepchem/deepchem/pull/1455 to shift `simdna` into a soft dependency

**Comment by rbharath** [comment]
Opened https://github.com/deepchem/deepchem/pull/1456 to shift `six` into a soft dependency

**Comment by nd-02110114** [comment]
I seem this issue is fixed. 

Currently, you could install the latest deepchem by this command

```
pip install --pre deepchem
```
