### ISSUE TITLE
How to set a custom loss function

### ISSUE THREAD

**Issue by Running-z** [deepchem/deepchem#1352]
I am using the deepchem model to predict the property values of molecules, but there are many missing values in my data. My data volume is very small. I don't want to discard these missing values, so I want to customize a loss function to make the missing data not. Calculate the loss value, but how should I pass in my custom loss function?

**Comment by rbharath** [comment]
You can set a custom loss by 

`model.set_loss(custom_loss)`

For missing data, you might want to look at Data imputation. DeepChem doesn't have much support for imputation, but there are some standard techniques out there.

**Comment by Running-z** [comment]
@rbharath 
Ok, thank you for your guidance. In addition, do you say that DeepChem has some technical standards? What do you mean?

**Comment by rbharath** [comment]
Discussion is continued in #1356
