### ISSUE TITLE
Any way to get newer TensorFlow or alternatively a newer standalone Keras?

### ISSUE THREAD

**Issue by meowcat** [deepchem/deepchem#1359]
I am using the DeepChem 2.1.0 Docker container deepchemio/deepchem.

It is very convenient as an image to train models on Paperspace Jobs because it contains both RDKit and TensorFlow and has GPU support. But the Keras 2.1.3 packaged with TensorFlow 1.6.0 is too old to support the CuDNNLSTM and CuDNNGRU layers. 

```
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.layers import Dropout
from tensorflow.python.keras.layers import CuDNNLSTM, LSTM
```

Fails at importing CuDNNLSTM.

With TensorFlow 1.9.0 this works on my local machine (but I can't actually use it because I don't have the GPU).

I have found it really hard to get my hands on any Docker image that has all of RDKit, python3, tensorflow, keras and working GPU support, and the CuDNN LSTM/GRU layers are the last thing I'm missing. I have tried making my own Dockerfile to add standalone Keras on top, but it would install an extra tensorflow which is not GPU-enabled so I'm back at step 1.

**Comment by peastman** [comment]
We're working on support for Tensorflow 1.9.  See https://github.com/deepchem/deepchem/pull/1331.  They made changes that broke some things, so it's taking a bit of time.

**Comment by rbharath** [comment]
Going to close this old issue off
