### ISSUE TITLE
Speed up PDB complex featurization to use multiple cores

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1361]
The PDBBind featurization example introduced in https://github.com/deepchem/deepchem/pull/1360 does featurization of complexes on a single core. This takes roughly a minute per molecule, the majority of which time is used to load the protein PDB into RDKit.

This code should be modified to use multiple cores to speed up the featurization. Otherwise, featurizing the refined and full subsets of PDBBind won't be feasible.

**Comment by peastman** [comment]
Actually, almost all of the time is spent adding hydrogens.  If you posted a version of the dataset that already had hydrogens it would be many times faster (although that would also double the size of the file).

If we don't want to do that, using multiple threads should be easy as long as RDKit releases the GIL while it's doing calculations.  Do you know if it does?

I also could see whether PDBFixer is faster than RDKit as adding hydrogens.  It might be.

**Comment by rbharath** [comment]
Awesome, thanks for the analysis! The PDBBind dataset is already quite large (2 GB tarred, 15 GB untarred I believe), so a pre-processed version might be a little unwieldy. Might still be worth doing.

It would also be useful for us to figure out ways to speed up hydrogen calculation regardless though, since I suspect many serious users will use this code on private datasets which they'll need to process themselves. I think RDKit mostly wraps around C++ code which does the actual compute. Does the GIL release for C++ calls?

**Comment by peastman** [comment]
From the RDKit documentation:

> Boost.Python ensures that only one thread is calling into the C++ code at any point. To get concurrent execution in Python, use the multiprocessing module or one of the other standard python approaches for this.

So it doesn't release the GIL.  Using `multiprocessing` is a bit less convenient, but it should work.
