### ISSUE TITLE
Build Times Increased

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1363]
Our Travis-CI build times seem to have increased a good bit, up to 45 minutes

https://travis-ci.org/deepchem/deepchem/builds/414945400

We should try to bring these back down

**Comment by peastman** [comment]
We can mark those tests with `@attr("slow")`.  Travis won't run them, but we'll still verify they pass before each release.

**Comment by pvskand** [comment]
@peastman, Thanks for that suggestion (didn't know this :) ) Will update the 2 tests with `@attr`.

**Comment by pvskand** [comment]
Addressed in PR #1371. I guess for the time being this issue can be closed. Can be re-opened whenever necessary.
