### ISSUE TITLE
Unable to search in Docs

### ISSUE THREAD

**Issue by pvskand** [deepchem/deepchem#1374]
Unable to search in the DeepChem. Any search like `conv2D`, `maxPool`, `data loader` returns NULL.
I suspect that the search returns NULL for all the keywords (but am not sure). This might be due to the version of Sphinx - we are currently using `1.3.5` and the latest version is `1.7.6`.
In any case this shouldn't be problem since search was working previously. I guess the root cause is something else.

**Comment by pvskand** [comment]
@rbharath @lilleswing any updates on this? I am still facing this issue.

**Comment by rbharath** [comment]
I'm moving the docs over to `readthedocs` which has search functionality.
