### ISSUE TITLE
csv file for the refined set of PDBbind

### ISSUE THREAD

**Issue by janeyin600** [deepchem/deepchem#1380]
Is the csv file for the refined set of PDBbind available (unfeaturized molecules)? Right now I can only find the csv file for the core set. if not, could you provide the script of writing the PDB and mol2 information into csv? Thanks!

**Comment by rbharath** [comment]
Take a look at the new `dc.molnet.load_pdbbind` function. This provides a way to load in the raw PDBBind data. We will continue iterating on this function to add in more features.
