### ISSUE TITLE
GraphConv feature labels and loading features from smile string

### ISSUE THREAD

**Issue by MortZx** [deepchem/deepchem#1381]
Hi,

I've been studying the code for a few weeks for a project of mine using the GraphConvTensorGraph model. I got 2 quick questions as I wasn't able to find an answer yet.

1) After loading the tox21 data, each atom for each molecule is attributed a feature vector of length 75. Where can I find a description of what each feature represents?
I vaguely know that the first 10-15(?) is a 1-hot vector representing the atom type. However I don't know which atom is represented in bit and what the remaining features represent.

2) How can I use a smile string or rdkit mol object as input and obtain features of that molecule in the same format as the GraphConv data. ie: get a feature vector of length 75 so I can use that molecule in the GraphConv model.
I understand I have to use the ConvMolFeaturizer class but I am not using it correctly, here is my attempt:

        from rdkit import Chem
        my_mol = Chem.MolFromSmiles('smile_here')
        feature_matrix = dc.feat.graph_features.ConvMolFeaturizer.featurize(mols=my_mol)

That snippet of code returns the error: featurize() is missing argument: 'self'

My apologies if this was already asked before but I couldn't find an answer.
Thanks for any help

**Comment by miaecle** [comment]
@MortZx Thanks for your interest! For the first question, you can refer to https://github.com/deepchem/deepchem/blob/905e5509df21241fa12827d95fe3328f462ba604/deepchem/feat/graph_features.py#L112 This function used in the `ConvMolFeaturizer` will return the feature vector of your input atom, which includes atom type, degree, hybridization type, etc.
For the second question, I think you need to define the featurizer first by calling `featurizer = dc.feat.graph_features.ConvMolFeaturizer()`, and then call `featurizer.featurize` function on the target molecules.

**Comment by MortZx** [comment]
Thank you very much for your reply.
This is exactly what I was looking for and the featurizer function now works as expected. 

Here's the final code if anyone else encounters this problem:
    import deepchem as dc
    from rdkit import Chem
    smile = 'your_smile_here'
    molecules = []
    molecules.append(Chem.MolFromSmiles(smile))
    featurizer = dc.feat.graph_features.ConvMolFeaturizer()
    mol_object = featurizer.featurize(mols=molecules)

**Comment by kimmo1019** [comment]
> @miaecle Thank you very much for your reply.
> This is exactly what I was looking for and the featurizer function now works as expected.
> 
> Here's the final code if anyone else encounters this problem:
> 
> ```
> import deepchem as dc
> from rdkit import Chem
> smile = 'your_smile_here'
> molecules = []
> molecules.append(Chem.MolFromSmiles(smile))
> featurizer = dc.feat.graph_features.ConvMolFeaturizer()
> mol_object = featurizer.featurize(mols=molecules)
> ```

Is there any way I can extract the adjacent matrix from a given molecule (SMILE or MOL format ) using deepchem?Thanks

**Comment by kimmo1019** [comment]
Ok, I finally found the solution.
After got the `mol_object`, just call `mod_object[0]. canon_adj_list` to get the adjacent matrix.
If `molecules ` contains multiple molecules, just call `mod_object[i]. canon_adj_list` to get the adjacent matrix of `ith` molecule.

**Comment by Sunitach10** [comment]
how I can visualize the features that I got from this code
