### ISSUE TITLE
Enter drugs and proteins

### ISSUE THREAD

**Issue by Running-z** [deepchem/deepchem#1382]
I now want to use drugs and proteins together as input, and then predict the properties after the action. Is there such a model and feature method in deepchem?

Please give me some answers and guidance, thank you

**Comment by rbharath** [comment]
Sorry for the extremely slow response. This old issue must have slipped through my inbox. The `dc.feat.RdkitGradFeaturizer` class does some of this, but you will need a joint co-crystal structure. There's unfortunately not a good way right now to feature a drug and a protein in the absence of crystal structures. This would be worth adding. I'm going to keep this issue as a place to track this work.

**Comment by rbharath** [comment]
Going to close this old issue since you can use `ComplexFeaturizer` to do this now
