### ISSUE TITLE
Installing tensorflow or tensorflow-gpu but not both

### ISSUE THREAD

**Issue by pvskand** [deepchem/deepchem#1384]
This problem arises when you try to install the GPU support. Current README instructions tend to install both.
`bash scripts/install_deepchem_conda.sh deepchem` install `tensorflow` (cpu) and `yes | pip install tensorflow-gpu==1.6.0 ` installs the gpu supported `tensorflow`. 
Edits to the bash script and README have to be me made to install either one out of them (but not both). Planning to take gpu support as a command line arg.

**Comment by rbharath** [comment]
Closing this old issue since fixed in #1385
