### ISSUE TITLE
Saliency mapping

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1386]
It's possible to implement saliency mapping on top of DeepChem, but it would be nice to provide a proper API for it.  A very simple implementation might be to add a `compute_saliency()` method to TensorGraph.  It would take a single sample as input.  It would return a matrix containing the derivative of every element of the output with respect to every element of the input.

**Comment by rbharath** [comment]
This would be a really useful feature, especially as we work on improving our support for image handling.

Could we make a version of saliency that worked for graph convs?

**Comment by peastman** [comment]
It should work for any kind of model.  The only restriction is that it will compute the derivatives with respect to the model's inputs, not the values stored in the dataset.  If a model overrides `default_generator()` to do some complicated transformations, it won't know about that.  You'll get a map over the model's Feature layers.
