### ISSUE TITLE
TensorGraph doesn't report progress during fitting

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1390]
TensorGraph used to print regular log messages to the console during fitting, so you could monitor the progress and the current loss.  At some point it stopped doing that.  I don't entirely understand why.

It's still trying to log them.  It does that with `logger.info()`.  But if I print out `logger.getEffectiveLevel()`, it returns 30 which corresponds to WARNING.  And sure enough if I change it to use `logger.warn()`, the messages get printed.

But here's the part I don't understand.  I can call `logger.setLevel(logging.INFO)` to tell it I want info messages.  If I do that, `logger.getEffectiveLevel()` returns 20 as expected.  But the messages still don't get printed!

Any idea what happened to change this, or how to fix it?

**Comment by rbharath** [comment]
I'm seeing this same error.

Could we swap these `logger.info()` statements for plain print statements perhaps? 

@lilleswing Would a swap to print statements break more sophisticated DeepChem pipelines?

**Comment by lilleswing** [comment]
It should be fine.  All production models should always be pipe-ing sterr and stdout to log files and explicitly logging their artifacts :).

If they aren't and this breaks things well that is the production models fault.

- Karl eslwing

**Comment by rbharath** [comment]
Closing this old issue since we're about to remove `TensorGraph`.
