### ISSUE TITLE
install deepchem on mac

### ISSUE THREAD

**Issue by aebk2015** [deepchem/deepchem#1396]
**I installed deepchem following the instruction on their website. I dint get any error during the installation but when I import deepchem from jupyternotebbok, the kernel will be dead:**
' ' '
The kernel appears to have died. It will restart automatically.
' ' '

If I import deepchem from terminal I get
```
>> import deepchem
Segmentation fault: 11
>> deepchem.__version__
-bash: deepchem.__version__: command not found
```

Here is my setup:
MacOS, High Sierra , 10.13.6
Python 3.5, Anaconda

**Comment by shosty1** [comment]
Did you install using conda? If so, before you start up your notebook have you activated your virtual environment (`source activate deepchem`)?

**Comment by aebk2015** [comment]
Yes I activate my environment before starting jupyter notebook

**Comment by RMeli** [comment]
For the records, the followoing
```
conda create -n deepchem
conda activate deepchem
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0
python -m pip install --upgrade pip
python -m pip install jupyter
```
worked flawlessly for me on macOS 10.13 (with Anaconca 3.6).

**Comment by lorenzoFabbri** [comment]
@RMeli If I do that, it will install Python 2.7.

**Comment by RMeli** [comment]
@lorenzoFabbri Do you have Anaconda 2.7 or 3.x installed?

You can try the following instead of the first line:
```
conda create -n deepchem python=3.6
```

**Comment by lorenzoFabbri** [comment]
@RMeli 3.x. I tried but then it complains later:

`UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - conda-forge/osx-64::pip==19.2.1=py36_0 -> python[version='>=3.6,<3.7.0a0']`

**Comment by RMeli** [comment]
@lorenzoFabbri I can't reproduce you error, but it looks like Python is being downgraded to 2.7 for me as well:
```
The following packages will be DOWNGRADED:

  python                                   3.6.8-haf84260_0 --> 2.7.16-h97142e2_0
```

**Comment by rbharath** [comment]
I've tested that the DeepChem HEAD runs fine on a recent Mac environment. I'll add improved CI support for Mac in a future PR, but going to close this old issue.
