### ISSUE TITLE
Appending features to pandas df

### ISSUE THREAD

**Issue by mmagithub** [deepchem/deepchem#1399]
**Description:**

- DeepChem Version: 2.1
- Platform: Mac OS 10.12

Hi,
I am trying to featurize a ligand dataset through the RDKitDescriptors. The dataset was given to deepchem as a Pandas dataframe. I am asking how can I append the features (the molecular descriptors) to the Pandas dataframe again.
Here is the code I am using:

```
rdkit_featurizer = dc.feat.RDKitDescriptors()
loader = dc.data.data_loader.featurize_smiles_df(selected_subset_total,featurizer=rdkit_featurizer,log_every_N=1000,field='canonical_smiles')

```

**Comment by rbharath** [comment]
Going to go ahead and close this issue. Feel free to re-open if you have more questions.
