### ISSUE TITLE
Runtime error running protein_ligand_complex_notebook.ipynb

### ISSUE THREAD

**Issue by jmichel80** [deepchem/deepchem#1401]
**Description:**
Hi, 

I'm playing with deepchem and found a runtime error while running the 'vanilla' notebook 
from 
https://github.com/deepchem/deepchem/tree/master/examples/notebooks/protein_ligand_complex_notebook.ipynb 

(...)
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

Loading dataset from disk.
TIMING: dataset construction took 0.054 s
Loading dataset from disk.
TIMING: dataset construction took 0.020 s
Loading dataset from disk.
TIMING: dataset construction took 0.017 s
Loading dataset from disk.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-8554c276f591> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

TypeError: 'NoneType' object is not iterable
(...)

- DeepChem Version:2.1.1
commit b57a23c2ca166401b8abf894652c11567f33a12c
- Platform: Ubuntu 18.04

**Comment by jmichel80** [comment]
So I think this might an indentation error in def load_pdbbind_grid from ~/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py

(..)
    if reload:
      deepchem.utils.save.save_dataset_to_disk(save_dir, train, valid, test,
                                               transformers)
    return tasks, (train, valid, test), transformers

The above return statement is not executed if passing featurizer='grid'.  Reducing indentation by one level seems to be sufficient to execute the rest of the notebook though I do not know if the results are correct.

**Comment by shirishr** [comment]
I think so too.
My results also do not match the notebook in the repository
At least I went past the error after making correction as suggested by @jmichel80 
My results:
computed_metrics: [0.8782562750588034]
RF Train set R^2 0.878256
computed_metrics: [0.22591267516980196]
RF Valid set R^2 0.225913

Repository  results
computed_metrics: [0.88553937155927021]
RF Train set R^2 0.885539
computed_metrics: [0.31742980243495422]
RF Valid set R^2 0.317430

**Comment by rbharath** [comment]
This notebook hasn't been updated in a while and should be cleaned up. Thanks for surfacing these issues! I'm going to mark this contribution-welcome if anyone wants to take a stab at cleaning up.

**Comment by VIGS25** [comment]
I'll take a look at this, @rbharath

**Comment by li-aolong** [comment]
> I think so too.
> My results also do not match the notebook in the repository
> At least I went past the error after making correction as suggested by @jmichel80
> My results:
> computed_metrics: [0.8782562750588034]
> RF Train set R^2 0.878256
> computed_metrics: [0.22591267516980196]
> RF Valid set R^2 0.225913
> 
> Repository results
> computed_metrics: [0.88553937155927021]
> RF Train set R^2 0.885539
> computed_metrics: [0.31742980243495422]
> RF Valid set R^2 0.317430

My results:
computed_metrics: [0.88362644148141112]
RF Train set R^2 0.883626
computed_metrics: [0.11158666899770164]
RF Valid set R^2 0.111587


The source code is as follow:
`if featurizer == 'grid':
    dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)

    splitters = {
        'index': deepchem.splits.IndexSplitter(),
        'random': deepchem.splits.RandomSplitter(),
        'time': deepchem.splits.TimeSplitterPDBbind(dataset.ids)
    }
    splitter = splitters[split]
    train, valid, test = splitter.train_valid_test_split(dataset)

    transformers = []
    for transformer in transformers:
      train = transformer.transform(train)
    for transformer in transformers:
      valid = transformer.transform(valid)
    for transformer in transformers:
      test = transformer.transform(test)`

Adding 'return tasks, (train, valid, test), transformers' makes no error, but the result seems not correct.

**Comment by VIGS25** [comment]
@li-aolong: Yes, I added the return statement, but the repository results agree with mine, although it fluctuates between 0.17 to 0.32. 
I haven't gottten to checking it yet, will do that and add the updated notebook.

**Comment by li-aolong** [comment]
@VIGS25 There's `transformers = []` in the code above. Is that correct or a bug?
