### ISSUE TITLE
Save dataset to disk

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1405]
I have a NumpyDataset, and I want to save it as a DiskDataset.  Am I missing something obvious, or is there no simple way of doing this?  Should I add a `save()` method to NumpyDataset?

DiskDataset does have a static method called `write_data_to_disk()`, but it doesn't create a complete dataset.  It looks like it was probably created for internal use only, and we should probably add a _ in front of the name.

**Comment by rbharath** [comment]
I think you can use `DiskDataset.from_numpy(np_dataset.X, np.dataset.y)` to do this

**Comment by peastman** [comment]
Oh right, that's what I was looking for.  Thanks!

**Comment by peastman** [comment]
But I see `from_numpy()` is helpfully reshaping your arrays to force them to have a particular number of dimensions.  Sigh.  I thought I had fixed the places where we did that, but I missed this one.  I'll fix it.
