### ISSUE TITLE
AttributeError: module 'deepchem' has no attribute 'trans'

### ISSUE THREAD

**Issue by naefl** [deepchem/deepchem#1415]
**Description:**
When running `import deepchem`

I get
`AttributeError: module 'deepchem' has no attribute 'trans'`

Windows 10, installed via conda.

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by jedison-github** [comment]
i met the same error,but i  can actually find the 'trans' in my install dir '~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/':
AttributeError                            Traceback (most recent call last)
<ipython-input-3-cb13ae64dca7> in <module>
      5 import numpy as np
      6 import tensorflow as tf
----> 7 import deepchem as dc
      8 from deepchem.models.tensorgraph.models.graph_models import GraphConvModel

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/__init__.py in <module>
      9 import deepchem.data
     10 import deepchem.feat
---> 11 import deepchem.hyper
     12 import deepchem.metalearning
     13 import deepchem.metrics

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/hyper/__init__.py in <module>
      1 from deepchem.hyper.grid_search import HyperparamOpt
----> 2 from deepchem.hyper.gaussian_process import GaussianProcessHyperparamOpt

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/hyper/gaussian_process.py in <module>
     11 from deepchem.hyper.grid_search import HyperparamOpt
     12 from deepchem.utils.evaluate import Evaluator
---> 13 from deepchem.molnet.run_benchmark_models import benchmark_classification, benchmark_regression
     14 
     15 logger = logging.getLogger(__name__)

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/molnet/__init__.py in <module>
     35 from deepchem.molnet.dnasim import simulate_single_motif_detection
     36 
---> 37 from deepchem.molnet.run_benchmark import run_benchmark
     38 #from deepchem.molnet.run_benchmark_low_data import run_benchmark_low_data
     39 from deepchem.molnet import run_benchmark_models

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/molnet/run_benchmark.py in <module>
     15 import deepchem
     16 import pickle
---> 17 from deepchem.molnet.run_benchmark_models import benchmark_classification, benchmark_regression
     18 from deepchem.molnet.check_availability import CheckFeaturizer, CheckSplit
     19 from deepchem.molnet.preset_hyper_parameters import hps

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/molnet/run_benchmark_models.py in <module>
     12 import tensorflow as tf
     13 import deepchem
---> 14 from deepchem.molnet.preset_hyper_parameters import hps
     15 from sklearn.ensemble import RandomForestClassifier
     16 from sklearn.ensemble import RandomForestRegressor

~/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/deepchem/molnet/preset_hyper_parameters.py in <module>
    121     'nb_epoch': 50,
    122     'learning_rate': 0.001,
--> 123     'fit_transformers': deepchem.trans.CoulombFitTransformer
    124 }
    125 hps['rf_regression'] = {'n_estimators': 500}

AttributeError: module 'deepchem' has no attribute 'trans'

**Comment by rbharath** [comment]
This is related to #1486. We're going to try to add formal windows support for the next release and will take a look into these issues.

**Comment by rbharath** [comment]
I'm going to close this old issue. Let's continue the discussion in #1486 if this is related to Windows support.
