### ISSUE TITLE
tensorflow installation with pip failed in scripts/install_deepchem_conda.sh

### ISSUE THREAD

**Issue by ktaneishi** [deepchem/deepchem#1422]
**tensorflow installation with pip failed in scripts/install_deepchem_conda.sh:**

I tried to build singularity image from Dockerfile of 2.1.0.

I got error when it installed tensorflow-gpu with pip.

I changed the code to install tensorflow-gpu with conda, it worked.

**Comment by lilleswing** [comment]
Hello ktaneishi!

There were issues with the install yesterday because of jupyter breaking conda installs.  The latest master has those issues fixed.

**Comment by lilleswing** [comment]
The fix was removing jupyter from the default install.

**Comment by ktaneishi** [comment]
Thanks. But dockerfile still checkout 2.1.0 which includes jupyter. Will you update 2.1.0 branch's install script or dockerfile itself? I'm replacing with sed in install script (like 2.1.0 install script).
