### ISSUE TITLE
Using fastprogress in DeepChem Notebooks

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1440]
The Fastai library fastprogress adds beautiful progress bars to Jupyter notebooks. We should instrument the DeepChem notebooks to display progress bars of this type. https://github.com/fastai/fastprogress

I'm marking this open for contribution.

**Comment by souravsingh** [comment]
I can look into this

**Comment by rbharath** [comment]
Did some digging into this on my end. One unfortunate discover is that fastprogress depends critically on f-strings, which are a new feature available only in Python 3.6. Until we upgrade to Python 3.6, we can't use fastprogress in any of our notebooks.

**Comment by rbharath** [comment]
Closing this issue for now since no plans to implement this at present
