### ISSUE TITLE
For binary classification, `to_one_hot` expects label vector of shape (batch_size,), while `pad_batches` expects (batch_size, 1)

### ISSUE THREAD

**Issue by leasunhy** [deepchem/deepchem#1446]
**Description:**

- DeepChem Version: 2.1.0
- NumPy Version: 1.15.3
- Platform: Python 2.7.15 :: Anaconda (Linux x86_64)

```
import numpy as np
from deepchem.metrics import to_one_hot

y = np.array([1, 0, 1, 0])
print(to_one_hot(y))

y = np.reshape(y, (y.shape[0], 1))
print(to_one_hot(y))
```

```
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
```

Obviously the return value of `to_one_hot` is wrong when argument `y` have two dimensions (but in the documentation `to_one_hot` should work with such arguments). This [line in `to_one_hot`](https://github.com/deepchem/deepchem/blob/master/deepchem/metrics/__init__.py#L30) causes the problem.

However, this [line in `pad_batch`](https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#102) requires `y_b` to have two dimensions.

**Comment by peastman** [comment]
> However, this line in pad_batch requires y_b to have two dimensions.

That line only gets executed if `y_b` has at least two dimensions.  It's in an `else` clause.  The lines immediately above it correctly handle the case where it only has one dimension.

```python
  elif len(y_b.shape) < 2:
    y_out = np.zeros(batch_size, dtype=y_b.dtype)
  else:
    y_out = np.zeros((batch_size, y_b.shape[1]), dtype=y_b.dtype)
```

**Comment by leasunhy** [comment]
Aha, sorry for bothering. That branch does not appear in the code of my 2.1.0 installation. Seems it has been fixed. Great work!
