### ISSUE TITLE
Allow TensorGraph to use Keras layers

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1461]
We keep coming back to the question of how to better interoperate with Keras.  This will become even more important in TensorFlow 2.0, since it will eliminate the `tf.contrib` and `tf.layers` modules and standardize on `tf.keras` as the primary API for building models.

In #1038 we considered completely replacing TensorGraph and just using `tf.keras.Model` for everything, but we concluded that wasn't practical.  TensorGraph has a lot of features that Keras doesn't, including Transformers, 2D weight matrices for multitask models, more flexibility in the shapes of input and output tensors, and first class support for DeepChem Datasets.  We rely on those features.

I'd like to propose a different possibility: keep TensorGraph, but have it accept a `tf.keras.Model` as its model definition.  In this approach, model building would all be done with standard Keras classes, but you would never call `compile()` on it.  Instead, you would pass it to a TensorGraph and rely on its methods for training and prediction.

As part of this transition, we would convert our own Layer classes to extend `tf.keras.layers.Layer`.  We also would deprecate (but not remove) all the ones that are just equivalents of standard layers.  As much as possible, we would use standard Keras layers when building our models.  We would then focus on providing two main contributions.

1. A collection of non-standard layers that are important for chemistry, like graph convolutions and atomic convolutions.  These would extend `tf.keras.layers.Layer`, so they could be used directly in any Keras model.

2. TensorGraph, which provides important features not supported by Keras models, as well as better integration with the rest of DeepChem.  This would be optional for users.  If someone doesn't need these features, they would be free to stick to `tf.keras.Model` but could still use the layers we provide.

What do you think?  Does this sound like a plausible approach?  Do you see any problems with it?

**Comment by rbharath** [comment]
I like this proposal quite a bit! Our core value as a library is the large set of non-standard layers that we maintain. Making these layers available to all TensorFlow users would make us much more useful. Retaining TensorGraph as an optional feature will let us retain backwards compatibility and support complex custom models which need TensorGraph's flexibility.

I think we'll add some additional code complexity on the backend with these changes. I think we can eventually remove deprecated layers (DeepChem 3.0 likely) which should mitigate these issues

**Comment by rbharath** [comment]
The new Keras model subclassing API might be relevant for this discussion: https://www.tensorflow.org/guide/keras#model_subclassing

**Comment by peastman** [comment]
I'm getting close to starting on this.  Here is a more detailed proposal.  Tell me what you think of it.

We will create a new module called `dc.models.layers`.  All of the layers contained in it will directly subclass `tf.keras.layers.Layer`.  We will take all our existing *nontrivial* TensorGraph layers and convert them to Keras layers in this module.

`dc.models.tensorgraph.layers` will continue to exist and have the same classes it currently does, but the amount of code will get a lot smaller.  The existing nontrivial layers will just become thin wrappers around the classes in `dc.models.layers`.

We'll create a new class called `dc.models.KerasModel`.  It will act as a wrapper around a Keras model in the same way that `SklearnModel` acts as a wrapper around a scikit-learn model.  The constructor will take an instance of `tf.keras.Model` which will define the model.  It will provide support for the same features that TensorGraph does, like multitask weights, transformers, etc.

Over time, we will gradually convert all the standard models to be based on KerasModel instead of TensorGraph.

At some point in the distant future (maybe DeepChem 4.0?), we could consider eliminating TensorGraph.  That won't be happening any time soon though.

**Comment by rbharath** [comment]
I like this proposal quite a bit. It will let us keep backwards compatibility on `TensorGraph` for at least one major release to allow people time to transition.

**Comment by peastman** [comment]
@rbharath if you want to try converting some models, Unet and ResNet50 would be good ones to try.  They're both very straightforward, so they should be easy to convert.  Neither one has any meaningful tests, though (all they do is check the shape of the output), so you'll need to create tests first so you can verify it still works after converting it.

**Comment by peastman** [comment]
I'm starting to look into converting the reinforcement learning classes.  I'd like to suggest dropping support for the MCTS algorithm.  It's way too slow to be useful, so I don't think it's worth the effort of converting it.  Does that seem reasonable?

**Comment by rbharath** [comment]
Yeah, I think that sounds pretty reasonable. I don't think anyone has been using it. (If someone has, please chime in on this thread)

**Comment by rbharath** [comment]
I'm going to close this old issue since we've converted over to Keras and are about to remove `TensorGraph` models. Let me know if I should keep this issue open.
