### ISSUE TITLE
I can't import deepchem as dc

### ISSUE THREAD

**Issue by So-hyeon** [deepchem/deepchem#1466]
**Description:**
I'm not sure that deepchem is installed correctly. 
And install deepchem in conda following to https://github.com/deepchem/deepchem . So,
When I search conda list, I can found deepchem
deepchem                  2.1.1.dev243              <pip>

but 

![2018-12-19 4 42 25](https://user-images.githubusercontent.com/45989427/50205867-1bac1a00-03ad-11e9-8ad5-60061bf2c0f2.png)

The other problem is that
I used Python 3.5.6 |Anaconda, Inc .

![2018-12-19 4 26 14](https://user-images.githubusercontent.com/45989427/50205285-f0283000-03aa-11e9-9bdf-a2c2de7fb850.png)
but when I run,  the error pops up
![2018-12-19 4 28 36](https://user-images.githubusercontent.com/45989427/50205341-2fef1780-03ab-11e9-8e64-457c4e42ef9e.png)
 
And I get this error too. 
![2018-12-18 3 24 04](https://user-images.githubusercontent.com/45989427/50205468-ae4bb980-03ab-11e9-8829-94c16a8eae86.png)

How to solve this error?

**Comment by rbharath** [comment]
Check answer in #1467. Closing this issue since we can continue discussion there.
