### ISSUE TITLE
deepchem installing & running problem

### ISSUE THREAD

**Issue by So-hyeon** [deepchem/deepchem#1467]
**Description:**
I'm not sure that deepchem is installed correctly. 
And install deepchem in conda following to https://github.com/deepchem/deepchem . So,
When I search conda list, I can found deepchem
deepchem                  2.1.1.dev243              <pip>

but 

![2018-12-19 4 42 25](https://user-images.githubusercontent.com/45989427/50205867-1bac1a00-03ad-11e9-8ad5-60061bf2c0f2.png)

The other problem is that
I used Python 3.5.6 |Anaconda, Inc .

![2018-12-19 4 26 14](https://user-images.githubusercontent.com/45989427/50205285-f0283000-03aa-11e9-9bdf-a2c2de7fb850.png)
but when I run,  the error pops up
![2018-12-19 4 28 36](https://user-images.githubusercontent.com/45989427/50205341-2fef1780-03ab-11e9-8e64-457c4e42ef9e.png)
 
When I try to deepchem Tutorials  I get this error too. 
![2018-12-19 4 50 44](https://user-images.githubusercontent.com/45989427/50206318-5d899000-03ae-11e9-9afd-d5350349a608.png)

How to solve this error?

**Comment by rbharath** [comment]
I think you need to install from `deepchem` conda channel using the following command:

```
conda install -c deepchem deepchem=2.1.0 python=3.5
```

**Comment by mc-robinson** [comment]
Having tried the above command, I would like to report a similar

```
PackagesNotFoundError: The following packages are not available from current channels:
  - deepchem=2.1.0
  - pdbfixer==1.4
  - deepchem=2.1.0
  - rdkit==2017.09.1
  - deepchem=2.1.0
  - xgboost==0.6a2
```
Interestingly, my channels do include the following:

```
Current channels:

  - https://conda.anaconda.org/deepchem/linux-64
  - https://conda.anaconda.org/deepchem/noarch
...
```

I have tried and found a similar error on my OSX machine.

**Comment by tblaschke** [comment]
The message is a little bit awkward, but it's due to unresolved dependencies.

Try this command 
`conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0`

**Comment by rbharath** [comment]
I'm able to install DeepChem on a Mac and run without issues. I'm going to close this issue for now, but feel free to re-open if necessary!

**Comment by nnnwyn** [comment]
> Having tried the above command, I would like to report a similar error
> 
> ```
> PackagesNotFoundError: The following packages are not available from current channels:
>   - deepchem=2.1.0
>   - pdbfixer==1.4
>   - deepchem=2.1.0
>   - rdkit==2017.09.1
>   - deepchem=2.1.0
>   - xgboost==0.6a2
> ```
> 
> Interestingly, my channels do include the following:
> 
> ```
> Current channels:
> 
>   - https://conda.anaconda.org/deepchem/linux-64
>   - https://conda.anaconda.org/deepchem/noarch
> ...
> ```
> 
> I have tried and found a similar error on my OSX machine.

Hi, have you solved this problem?

**Comment by arunppsg** [comment]
> 
> Hi, have you solved this problem?

Can you check once again by installing in a new conda environment? In case you are using M1, install tensorflow, test it and check whether it works. You might follow this [stackoverflow answer ](https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook) for installation errors on tensorflow. Then, install deepchem as suggested [here](https://github.com/deepchem/deepchem/#stable-version).
