### ISSUE TITLE
deepchem tutorials errors

### ISSUE THREAD

**Issue by So-hyeon** [deepchem/deepchem#1469]
l did installed deepchem(reference https://github.com/deepchem/deepchem) 
![2018-12-21 7 07 58](https://user-images.githubusercontent.com/45989427/50337245-da09a380-0553-11e9-905b-58ca6151e1e0.png)

And I try to example of deepchem's  tutorial via jupyter notebook. 
But It is doesn't work.
 
![2018-12-21 6 13 20](https://user-images.githubusercontent.com/45989427/50336926-d1fd3400-0552-11e9-8682-732bcf91fb09.png)
![2018-12-21 6 13 37](https://user-images.githubusercontent.com/45989427/50336929-d4f82480-0552-11e9-8761-e9d39d1a2324.png)

And "import deepchem" doesn't work.
![2018-12-21 7 09 14](https://user-images.githubusercontent.com/45989427/50337286-f574ae80-0553-11e9-889d-db2bd851557c.png)

**Comment by RodrigoZepeda** [comment]
I had a similar issue with the installation. This worked for me on Ubuntu albeit it failed on Mac:
```
#Create an environment
conda create -n deepchemenv

#Enter the environment
conda activate deepchemenv

#Install inside it
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0
```

**Comment by rbharath** [comment]
This works with DeepChem 2.3.0 (checked on Mac recently) so going to close this issue. Please feel free to re-open if necessary.
