### ISSUE TITLE
error about NOT working deepchem

### ISSUE THREAD

**Issue by So-hyeon** [deepchem/deepchem#1470]
**Description:**
This is my conda infomantion
![2018-12-21 8 26 48](https://user-images.githubusercontent.com/45989427/50341131-05df5600-0561-11e9-9c30-0c156753c34f.png)

To install deepchem,
I was following to this process ( "If I don't want GPU support")
![2018-12-21 8 33 06](https://user-images.githubusercontent.com/45989427/50340788-b4829700-055f-11e9-9ef6-2ad6549ae024.png)

As follows
![2018-12-21 8 28 26](https://user-images.githubusercontent.com/45989427/50340929-3ffc2800-0560-11e9-8859-23b96d9a3486.png)
![2018-12-21 8 29 21](https://user-images.githubusercontent.com/45989427/50340938-4db1ad80-0560-11e9-94b4-59feb3ebc793.png)
![2018-12-21 8 30 04](https://user-images.githubusercontent.com/45989427/50340942-50140780-0560-11e9-8c3f-668a1fd6a899.png)
![2018-12-21 8 31 22](https://user-images.githubusercontent.com/45989427/50340954-5c986000-0560-11e9-90e5-d4901021e10b.png)
The above process was successful but in "Run tests", occurring error segmentation fault : 11
And as you can see the first picture, when I try to "import deepchem" , It occurred segmentation fault : 11 too.

I don't know what is my problem. PLEASE HELP ME

![2018-12-21 8 32 08](https://user-images.githubusercontent.com/45989427/50340956-5e622380-0560-11e9-8ea6-02a28e7c7bff.png)

```
Your code sample here
```

**Comment by rbharath** [comment]
Sorry, lost track of this old issue in my inbox. Are you still having installation issues?

**Comment by rbharath** [comment]
I'm going to close this issue. Please feel free to ping here if you're still having issues.
