### ISSUE TITLE
How can we download 'az_ppb.csv' contained in script 'mpnn.py'?

### ISSUE THREAD

**Issue by Dinxin** [deepchem/deepchem#1472]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by jrthom18** [comment]
Also, are the `Delaney` and `Clearance` datasets available to download somewhere?

**Comment by VIGS25** [comment]
@Dinxin: Not really sure, the usual place for datasets was also missing it. Maybe @rbharath or @peastman would know.

@jrthom18:
`delaney` dataset can be downloaded from [here]('http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/delaney-processed.csv')
`clearance` dataset can be downloaded from [here]('http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/clearance.csv')

**Comment by salbatron** [comment]
@Dinxin Maybe [this](https://github.com/PatWalters/acs_spring_2019_acid_base/tree/master) can help

**Comment by rbharath** [comment]
I believe the `ppb` dataset is now in moleculenet so going to close this issue.
