### ISSUE TITLE
NumpyDataset and DiskDataset y vectors are not consistent

### ISSUE THREAD

**Issue by amandajean119** [deepchem/deepchem#1489]
**Description:**

- DeepChem Version: 2.1.0
- Platform: Ubuntu

For singletask datasets (1D label vector), NumpyDatasets and DiskDatasets return different views of the y vector. NumpyDataset returns a vector and DiskDataset returns a 2-D array.

```
dataset_tmp = NumpyDataset(features, vals)
dataset = DiskDataset.from_numpy(features, vals)
(Pdb) dataset_tmp.y.shape
(630,)
(Pdb) dataset.y.shape
(630, 1)
```

**Comment by rbharath** [comment]
Good find. Marked this one as a bug.

**Comment by peastman** [comment]
Does this still happen in the current code?  I think it was fixed in #1406.

**Comment by peastman** [comment]
Sorry, hit the wrong button!

**Comment by MatthewMasters** [comment]
Just verified with latest code. The problem was fixed, this can be closed.

**Comment by peastman** [comment]
Thanks!
