### ISSUE TITLE
Conda Install Tensorflow 1.10.0 dependency

### ISSUE THREAD

**Issue by bkestelman** [deepchem/deepchem#1501]
**Description:**

Hello, 

I need to use tensorflow=1.10.0, but 'conda install -c deepchem deepchem' comlains that it requires tensorflow=10.6. 

Is tensorflow=1.10.0 actually incompatible with deepchem?

**Comment by rbharath** [comment]
It's definitely on our TODO lists to upgrade DeepChem to later versions of TF. We've got this slotted for the release after next when we're planning to do a wholesale upgrade to TF2. In the meanwhile, I think it should work with tf 1.10 (I don't think there have been any breaking changes). If the test suite runs with almost all passing (a couple flaky tests here and there), you're probably fine

**Comment by peastman** [comment]
I'm starting work now on upgrading to the latest TensorFlow (1.12).  Hopefully not too much will have broken.
