### ISSUE TITLE
No way to set verbose=False when transforming datasets

### ISSUE THREAD

**Issue by kmclough** [deepchem/deepchem#1511]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by kmclough** [comment]
Am trying to turn off all the log messages that are posted to stdout when DiskDatasets are created. Most functions that invoke DiskDataset.create_dataset() allow you to pass the verbose parameter and set it False, but DiskDataset.transform() does not. It would be simple enough to add a **kwargs parameter to allow one to do this.

**Comment by VIGS25** [comment]
@kmclough, This has been fixed now.
