### ISSUE TITLE
ConvGraph features

### ISSUE THREAD

**Issue by SeanXiaoyuSun** [deepchem/deepchem#1517]
Hi all,

I'm new to DeepChem. I'm trying to understand the corresponding physical property of each element in the X vector returned by ConvMolFeaturizer. 

I used the following code to print out the X vectors of my data set
```
  loader = deepchem.data.CSVLoader(
      tasks=flashpoint_tasks, smiles_field="smiles", featurizer=deepchem.feat.ConvMolFeaturizer())
  dataset = loader.featurize(dataset_file, shard_size=8192)
  for x in dataset.X:
    print(x.get_atom_features())
```
And I got vectors like this:
```
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.
  0. 0. 0.]
```
Does anybody know the meanings of these 75 entries in every X vector?

Best,

**Comment by VIGS25** [comment]
These correspond to different atom features like the atomic symbol, degree of the atom, its implicit valence,  formal charges, hybridization and a few other properties like that. These are then converted to the appropriate one-hot encoded versions.

You can find more about this here:
https://github.com/deepchem/deepchem/blob/049779ec2f7ed3aed543aa993c2061e26a38f77a/deepchem/feat/graph_features.py#L122

**Comment by SeanXiaoyuSun** [comment]
Thanks for your quick response! I get it now.

**Comment by VIGS25** [comment]
Could you close this issue?
Feel free to reopen if necessary!

**Comment by SeanXiaoyuSun** [comment]
Issue solved
