### ISSUE TITLE
Unable to Load Disk Datasets (ValueError: No Metadata Found On Disk)

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1523]
- DeepChem Version: 2.1.0
- Platform: anaconda; python 3.5; mac OS

_I am trying to follow some of the tutorials and any time I try to load in a disk dataset, I get
 "ValueError: No Metadata Found On Disk"_

**[1]:**
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

_**gives the following output:**_

Loading dataset from disk.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-8554c276f591> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind_grid(split, featurizer, subset, reload)
     52   """Load PDBBind datasets. Does not do train/test split"""
     53   if featurizer == 'grid':
---> 54     dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
     55 
     56     splitters = {

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in featurize_pdbbind(data_dir, feat, subset)
     43         os.path.join(data_dir, 'refined_grid.tar.gz'), pdbbind_dir)
     44 
---> 45   return deepchem.data.DiskDataset(dataset_dir), tasks
     46 
     47 

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in __init__(self, data_dir, verbose)
    532 
    533     log("Loading dataset from disk.", self.verbose)
--> 534     self.tasks, self.metadata_df = self.load_metadata()
    535 
    536   @staticmethod

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in load_metadata(self)
    585       save_metadata(tasks, metadata_df, self.data_dir)
    586       return tasks, metadata_df
--> 587     raise ValueError("No Metadata Found On Disk")
    588 
    589   @staticmethod

ValueError: No Metadata Found On Disk

---------------------------------------------------------------------------

**[2]:** tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()

_**gives the following output:**_

Loading dataset from disk.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-d3e0f50769da> in <module>()
----> 1 tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/tox21_datasets.py in load_tox21(featurizer, split, reload, K)
     25     save_dir = os.path.join(data_dir, "tox21/" + featurizer + "/" + str(split))
     26     loaded, all_dataset, transformers = deepchem.utils.save.load_dataset_from_disk(
---> 27         save_dir)
     28     if loaded:
     29       return tox21_tasks, all_dataset, transformers

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/save.py in load_dataset_from_disk(save_dir)
    313     return False, None, list()
    314   loaded = True
--> 315   train = deepchem.data.DiskDataset(train_dir)
    316   valid = deepchem.data.DiskDataset(valid_dir)
    317   test = deepchem.data.DiskDataset(test_dir)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in __init__(self, data_dir, verbose)
    532 
    533     log("Loading dataset from disk.", self.verbose)
--> 534     self.tasks, self.metadata_df = self.load_metadata()
    535 
    536   @staticmethod

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in load_metadata(self)
    585       save_metadata(tasks, metadata_df, self.data_dir)
    586       return tasks, metadata_df
--> 587     raise ValueError("No Metadata Found On Disk")
    588 
    589   @staticmethod

ValueError: No Metadata Found On Disk

_Please help me figure out what the problem is... since I am only utilizing the surface functionality, I don't understand why I am getting these errors._

**Comment by VIGS25** [comment]
Can you try these: `dc.molnet.load_tox21(reload=False)` and `dc.molnet.load_pdbbind_grid(reload=False)`

**Comment by fredrikszm** [comment]
This is the output of each:

**dc.molnet.load_tox21(reload=False)**
Loading raw samples now.
shard_size: 8192
About to start loading CSV from /var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/tox21.csv.gz
Loading shard 1 of size 8192.
Featurizing sample 0
Featurizing sample 1000
Featurizing sample 2000
Featurizing sample 3000
Featurizing sample 4000
Featurizing sample 5000
Featurizing sample 6000
Featurizing sample 7000
TIMING: featurizing shard 0 took 20.316 s
TIMING: dataset construction took 26.426 s
Loading dataset from disk.
TIMING: dataset construction took 9.603 s
Loading dataset from disk.
TIMING: dataset construction took 4.423 s
Loading dataset from disk.
TIMING: dataset construction took 2.271 s
Loading dataset from disk.
TIMING: dataset construction took 2.390 s
Loading dataset from disk.

----------------------------------------------------------------------------------

**dc.molnet.load_pdbbind_grid(reload=False)**

Loading dataset from disk.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-8906d4ca7a8a> in <module>()
      1 
----> 2 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(reload=False)
      3 # error in code so need to wait for update or use source code

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind_grid(split, featurizer, subset, reload)
     52   """Load PDBBind datasets. Does not do train/test split"""
     53   if featurizer == 'grid':
---> 54     dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
     55 
     56     splitters = {

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in featurize_pdbbind(data_dir, feat, subset)
     43         os.path.join(data_dir, 'refined_grid.tar.gz'), pdbbind_dir)
     44 
---> 45   return deepchem.data.DiskDataset(dataset_dir), tasks
     46 
     47 

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in __init__(self, data_dir, verbose)
    532 
    533     log("Loading dataset from disk.", self.verbose)
--> 534     self.tasks, self.metadata_df = self.load_metadata()
    535 
    536   @staticmethod

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in load_metadata(self)
    585       save_metadata(tasks, metadata_df, self.data_dir)
    586       return tasks, metadata_df
--> 587     raise ValueError("No Metadata Found On Disk")
    588 
    589   @staticmethod

ValueError: No Metadata Found On Disk

**Comment by VIGS25** [comment]
I can see that the `load_tox21()` is working properly now, but it is surprising that it failed to work properly previously. 
For `load_pdbbind_grid()`, it looks as though the current source code (which works on my machine), is a little different from the one running on yours. I'll have to look at that one, to see what went wrong

**Comment by fredrikszm** [comment]
Just in case this information is pertinent: 
I removed and reinstalled deepchem yesterday and it made no difference. Both times (original and reinstall) I used the following to install:
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0

Thanks for looking into this for me, I really appreciate the help!

**Comment by VIGS25** [comment]
Can you try installing from source instead?
There were some issues with `pdbbind_datasets.py` file which have now been fixed. However, those changes will be passed onto the conda version only in the next release. 

If you cannot install from source, then I'd recommend not trying out the `pdbbind` loading.

**Comment by fredrikszm** [comment]
When I install from source I get the following:

Ran 576 tests in 921.017s
FAILED (errors=20, failures=1)

**Comment by VIGS25** [comment]
Can you copy the error log in a file and post it here?

**Comment by fredrikszm** [comment]
[deepchemErrorLog.txt](https://github.com/deepchem/deepchem/files/2938237/deepchemErrorLog.txt)

**Comment by VIGS25** [comment]
Did you run the tests inside the virtual environment?
I'm asking this because `mdtraj` should be present

**Comment by fredrikszm** [comment]
Yes I ran the tests in the virtual environment. But conda list shows that the virtual environment does not have mdtraj installed
Should I install it and try again?

**Comment by fredrikszm** [comment]
I installed mdtraj (1.9.2) then ran the script and it still shows the following error:

PackageNotFoundError: Packages missing in current channels:
            
  - mdtraj 1.9.1*

**Comment by VIGS25** [comment]
`bash scripts/install_deepchem_conda.sh` should have installed `mdtraj` as well. The script has it explicitly

**Comment by fredrikszm** [comment]
I don't see it in the file:

![screen shot 2019-03-06 at 1 27 23 pm](https://user-images.githubusercontent.com/44656030/53914915-94695c80-4013-11e9-852f-8e5b0b1e0bab.png)

**Comment by VIGS25** [comment]
Check line 46

**Comment by fredrikszm** [comment]
ah you are right. Do you have any idea why it is not installing it?

**Comment by fredrikszm** [comment]
Any updates on why load_pdbbind_grid is not working?

**Comment by VIGS25** [comment]
This issue can be closed, lets continue the discussion on the other one.
