### ISSUE TITLE
Issues fixed but not closed

### ISSUE THREAD

**Issue by kyscg** [deepchem/deepchem#1526]
There are quite some issues to which either the required fixes have been merged or it was agreed that the issue will not be worked upon, could we close those issues @rbharath ?

**Comment by rbharath** [comment]
Sure, want to leave a comment in those issues which should be closed? I'll do a cleanup pass after

**Comment by kyscg** [comment]
Yeah, and I'll try to list them out here too.

**Comment by VIGS25** [comment]
I can list out the few which I fixed (and some which TensorFlow doesn not allow for now):

#1499: Cutoff Arg for Butina Splitter
#1504: Renaming the BPSymmetryFunction
#1404: Adding load_binding_pocket to `dc.load_pdbbind`
#1142: Make estimator support. For the models which iterate directly over molecules and compute features, TF doesn't support that yet, so they won't be able to have `make_estimator` support.
#1317: Add `get_layer_weights` to TensorGraph
#1401: Reproducibility issues with the pdbbind_notebook
#412: BEDROC metric
#1349: DiskDataset.from_numpy(X) [ie construct DiskDataset without using labels]
#630: MolNet loaders for UV/Kinase/Factors datasets
#1362: AtomicConvolution Featurization for PDB complexes (both what is suggested in the issue, and my misinterpreted version of using the embeddings)
#1511: Set verbose=False, when transforming data.

In addition, I contributed a couple of models as well (#991, and #644) - They are both complete, but those issues can be kept open for now.

**Comment by rbharath** [comment]
@VIGS25 Thanks for listing these out! I did a pass and closed most of these (except for a couple like the `make_estimator` support which I want to keep open in case we can address in TF 2.0 upgrades)

**Comment by rbharath** [comment]
Going to close this old issue.
