### ISSUE TITLE
Get data model failed/succeeded on

### ISSUE THREAD

**Issue by danieldemarch** [deepchem/deepchem#1530]
Hey all, trying to get the subset of the data a model did/did not classify correctly. Seems to be no easy way to do this. I realize I can use model.predict, but that's returning something odd... it's an array of float pairs between 0 and 1. I initially thought this was a regression val for the molecule but then why would there be two...

Anyway yeah, need to be able to separate my succeed/fail datasets is the bottom line.

**Comment by VIGS25** [comment]
It could be a multi-task problem, but hard to judge unless you describe the problem in greater detail.

**Comment by rbharath** [comment]
Seconding @VIGS25, this depends on the type of model at hand. If you're still having an issue here, would you mind posting more details?

I'm going to close this issue for now, but please re-open if you're still facing issues.
