### ISSUE TITLE
model.save() and model.load() to user-specified filename [feature request]

### ISSUE THREAD

**Issue by UnixJunkie** [deepchem/deepchem#1537]
Hello,

It would be nice to be able to save a model to a file chosen by the user.
Same thing for load.

I.e. those functions should take an optional parameter.
If this filename is provided, model should be saved to it, instead of 'tmp_dirname/model.pickle'.

Thanks,
F.

**Comment by VIGS25** [comment]
If you specify the `model_dir` argument while initializing any of DeepChem's models, and then call `model.save()`, then the model is saved to the directory you specify. Same applies to the load.

**Comment by UnixJunkie** [comment]
Save to file is more direct than: set directory name then save.
Also, there may be several things in that directory (like checkpoints), so I am unsure that when I call load() it will load the model I saved.
With everything in a single file (whose name I specified, and to which I just wrote once), I would be more sure.
This is not a light topic: if you have trained a model and want to use it in production later, you don't want to have to retrain a model, also, you want to be sure about what your are using.

**Comment by VIGS25** [comment]
Of course this comes from my own experience, but I have found it easier so far to keep different experiments in directories When I load, I just need to point to which experiment I refer to, and the loading is smoothly done. 

To the best of my knowledge, saving the model as `.pickle` or `.joblib` circumvents the checkpoint need, and the model gets loaded from the same place it was saved. 

I never said it was a light topic :-), but yeah if you want to ship multiple trained models, then having custom filenames would be useful.

**Comment by rbharath** [comment]
We're now using Keras for saving models, so I think we should likely defer to Keras community standards on how to save/ship models. I'm going to close this old issue, but please re-open if there are additional questions here!
