### ISSUE TITLE
Loading Error: dc.molnet.load_pdbbind_grid

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1541]
Sorry to repeat an earlier issue but I am still having this problem and have run out of solutions that I can think of alone. 
I am trying to load in the pdb disk dataset (dc.molnet.load_pdbbind_grid) but I keep receiving the same error (pasted below). 
I installed DeepChem 2.1.0 using conda, and I'm running python 3.5. I tried installing from source code, but the tests gave back errors. I was able to get the individual python files from source, which I exchanged with the files that seemed to be related to the error (pdbbind_datasets.py, datasets.py).
However, I am still receiving the same error. I really need to use this dataset for a project I am working on so any help would be greatly appreciated!

Loading dataset from disk.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-0f1c31060c31> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(reload=False)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind_grid(split, featurizer, subset, reload)
     59   """Load PDBBind datasets. Does not do train/test split"""
     60   if featurizer == 'grid':
---> 61     dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
     62 
     63     splitters = {

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in featurize_pdbbind(data_dir, feat, subset)
     50         os.path.join(data_dir, 'refined_grid.tar.gz'), pdbbind_dir)
     51 
---> 52   return deepchem.data.DiskDataset(dataset_dir), tasks
     53 
     54 

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in __init__(self, data_dir, verbose)
    540 
    541     log("Loading dataset from disk.", self.verbose)
--> 542     self.tasks, self.metadata_df = self.load_metadata()
    543 
    544   @staticmethod

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in load_metadata(self)
    593       save_metadata(tasks, metadata_df, self.data_dir)
    594       return tasks, metadata_df
--> 595     raise ValueError("No Metadata Found On Disk")
    596 
    597   @staticmethod

ValueError: No Metadata Found On Disk

**Comment by VIGS25** [comment]
Can you try running `ls /tmp/pdbbind/core_grid' and post the output?
Just as a reference, I ran the above commands as you, and also the `ls` command and get:

![image](https://user-images.githubusercontent.com/32259379/54863619-3cd52b80-4d4b-11e9-8ab1-cf9edd6cc977.png)

**Comment by fredrikszm** [comment]
This is the output:
ls: /tmp/pdbbind/core_grid: No such file or directory

**Comment by VIGS25** [comment]
The data not getting downloaded is the problem here, unfortunately. 
Could you add the file which you have for pddbind_datasets here?

**Comment by fredrikszm** [comment]
[pdbbind_datasets.py.zip](https://github.com/deepchem/deepchem/files/2999173/pdbbind_datasets.py.zip)

Github doesn't accept .py so I had to compress it in order to load it here.

**Comment by VIGS25** [comment]
Well, I run the `load_function` in your file, and I still don't get any errors.

**Comment by fredrikszm** [comment]
Can you show me what you're running exactly so I can make sure it matches with what I'm doing?

**Comment by VIGS25** [comment]
I add an additional line in the end to the file you just gave:
``` 
if __name__ == '__main__':
    load_pdbbind_grid(reload=False)
```

and then I run:
```
source activate deepchem
python pdbbind_datasets.py
```

**Comment by fredrikszm** [comment]
When I run the same commands, I also do not get any errors.
But when I run the following in a jupyter notebook/ipython: 
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(reload=False)

I get the original error (ValueError: No Metadata Found On Disk)

**Comment by VIGS25** [comment]
Is what you run from the examples section?

**Comment by fredrikszm** [comment]
Yes, with the addition of "reload=False" because you had mentioned to include that in a previous discussion on this issue. With or without "reload=False" it doesn't work

**Comment by VIGS25** [comment]
So, with reload=False and reload=True, I'm able to run the example `protein_ligand_complex_notebook.ipynb` code.

**Comment by fredrikszm** [comment]
I am running the same code and am still getting the error :(

**Comment by VIGS25** [comment]
What I would suggest is to add a print statement, just to see if the download and directory creation are happening as intended.

**Comment by fredrikszm** [comment]
Where would you suggest I add the print statement?

**Comment by VIGS25** [comment]
For now, just focus on `featurize_pddbind`. Also make sure, you remove all the files in /tmp/ that are related to this task.

Add a print statement before and after the `dc.utils.download_url` statement to check for download.
Add one for the `mkdir` part, and finally one to see if the data is being moved.

**Comment by fredrikszm** [comment]
So I found that the dataset directory already exists and so the if statement in featurize_pdbbind does not get entered (and the download statements are not executed). This function returns by sending the directory to Disk Dataset. 
From here, I have found that the error occurs in load_metadata. The tasks_filename and metadata_filename are created correctly from the call to _get_metadata_filename(). 
But the tasks_filename file does not exist and so it cannot be opened in the next line of load_metadata:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/pdbbind/core_grid/tasks.json'

I am not sure why the file does not exist, do you have any idea of what I can do about this?

**Comment by VIGS25** [comment]
Thats surprising, because the `.gz` file should have the tasks.json. You can actually download the file manually from the URL and check.

**Comment by fredrikszm** [comment]
Downloading it manually made it work! Thanks so much for your help with this! Just for my understanding - Do you have an idea of why the tasks.json file wasn't there in the first place?

**Comment by VIGS25** [comment]
I am not so sure, maybe there was some issue with the extraction. The `.gz` file being downloaded should have the `tasks.json` file inside.
Can you close this issue now? - Feel free to reopen if necessary.

**Comment by fredrikszm** [comment]
Yup! Thanks again for the help!
