### ISSUE TITLE
FAIL: Test a GAN with multiple generators and discriminators

### ISSUE THREAD

**Issue by ZuoyiLi** [deepchem/deepchem#1544]
**Description:**

- DeepChem Version: 2.1.0 (Latest as of March 22nd, 2019)
- Platform: Linux 4.15.0-46-generic

I ran the nosetest and met this following error:
What would have caused this fail and how should I fix it? Thank you!

```
FAIL: Test a GAN with multiple generators and discriminators.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/u/z/u/zuoyi/deepchem/deepchem/models/tensorgraph/tests/test_gan.py", line 81, in test_mix_gan
    assert abs(np.mean(deltas)) < 1.0
AssertionError

----------------------------------------------------------------------
Ran 576 tests in 782.686s
```

**Comment by VIGS25** [comment]
This is just a stochastic test that would fail occasionally. Don't read too much into it.

**Comment by peastman** [comment]
If you look at the source code for that test, you'll notice it has the annotation `@flaky` at the top.  That means it's expected to occasionally fail.  When running the test suite on travis, it automatically reruns any failing tests with that annotation, and only reports a problem if it fails twice.

**Comment by ZuoyiLi** [comment]
@peastman  @VIGS25  Thank you so much. I have ran some code in the environment and all seems fine.
