### ISSUE TITLE
conda install error need help

### ISSUE THREAD

**Issue by HadXu** [deepchem/deepchem#1547]
![企业微信截图_15536796801158](https://user-images.githubusercontent.com/13307469/55076264-f592c600-50cf-11e9-90e5-8770471ae0d7.png)

thank you!

**Comment by abster12** [comment]
What Platform are you on?

**Comment by HadXu** [comment]
linux

**Comment by abster12** [comment]
``` conda install -c deepchem deepchem-gpu=2.1.0 python=3.6 ``` 
Did you try this command?

**Comment by MatthewMasters** [comment]
You are not including all the necessary channels. Issue the command as seen on the main README:
```conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0```

**Comment by HadXu** [comment]
Ok I try this！

**Comment by MatthewMasters** [comment]
Please close the issue if you find your problem is resolved.

**Comment by Mario-Liu** [comment]
> 
> 
> You are not including all the necessary channels. Issue the command as seen on the main README:
> `conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0`

I tried and it doesn't work.

**Comment by MatthewMasters** [comment]
@Mario-Liu Could you post a screenshot or copy-paste the error you're receiving

**Comment by alexbw** [comment]
FYI the website offers conflicting information from the README file.

The deepchem.io website tells you to try: `conda install -c deepchem deepchem=2.1.0` but the README says `conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0`.

**Comment by nilu33032** [comment]
Actually... I tried it in macOS and neither works 
the first one will give 
<img width="681" alt="Screen Shot 2019-06-19 at 15 07 33" src="https://user-images.githubusercontent.com/49758924/59740763-048aae00-92a4-11e9-9263-1b8dca01fd33.png">

the second one will for some reason downgrade python3 into python 2
<img width="809" alt="Screen Shot 2019-06-19 at 15 11 17" src="https://user-images.githubusercontent.com/49758924/59740941-811d8c80-92a4-11e9-97c0-a311b6e65e88.png">

I don't know if its a macOS only thing though

**Comment by peastman** [comment]
You need to include all the channels given in the README:

```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem
```
