### ISSUE TITLE
Stuck in nosetests when install from source

### ISSUE THREAD

**Issue by dragonofac** [deepchem/deepchem#1549]
**Description:**

 commit bcbe3e12bd123cb5ddf2fc77627fddc7b529a8ee
- DeepChem Version:  2.2.1
- Platform: linux ubuntu

The test command (which from the sample):
"nosetests -a '!slow' -v deepchem --nologcapture"
stuck too long and looks like not going ahead.
here is the position it stucks
```
Calculate molecule-level features for a multiconformer molecule. ... ok
Test CircularFingerprint. ... ok
Test CircularFingerprint with sparse encoding. ... ok
Test CircularFingerprint with sparse encoding and SMILES for each ... ok
Test if featurization works using AtomicConvFeaturizer. ... 
```

**Comment by VIGS25** [comment]
The test is running but I forgot to add the slow attribute to the test. 
Will raise a PR soon with the same.

For the time being, you could to add an additional import statement to file linked [here](https://github.com/deepchem/deepchem/blob/049779ec2f7ed3aed543aa993c2061e26a38f77a/deepchem/feat/tests/test_graph_features.py):

`from nose.plugins.attrib import attrb`

and then add  @attr("slow") before the `test_feature_generation` function in line 99 in the file.

You should then be able to re-run the tests without getting stuck.

**Comment by dragonofac** [comment]
> The test is running but I forgot to add the slow attribute to the test.
> Will raise a PR soon with the same.
> 
> For the time being, you could to add an additional import statement to file linked [here](https://github.com/deepchem/deepchem/blob/049779ec2f7ed3aed543aa993c2061e26a38f77a/deepchem/feat/tests/test_graph_features.py):
> 
> `from nose.plugins.attrib import attr`
> 
> and then add `@attr("slow")` before the `test_feature_generation` function in line 99 in the file.
> An example on how to add it can be found [here](https://github.com/deepchem/deepchem/blob/883c381a3430f70e1be4f293767c0fa730374178/deepchem/dock/tests/test_pose_generation.py).
> 
> You should then be able to re-run the tests without getting stuck.

**Comment by dragonofac** [comment]
> The test is running but I forgot to add the slow attribute to the test.
> Will raise a PR soon with the same.
> 
> For the time being, you could to add an additional import statement to file linked [here](https://github.com/deepchem/deepchem/blob/049779ec2f7ed3aed543aa993c2061e26a38f77a/deepchem/feat/tests/test_graph_features.py):
> 
> `from nose.plugins.attrib import attr`
> 
> and then add `@attr("slow")` before the `test_feature_generation` function in line 99 in the file.
> An example on how to add it can be found [here](https://github.com/deepchem/deepchem/blob/883c381a3430f70e1be4f293767c0fa730374178/deepchem/dock/tests/test_pose_generation.py).
> 
> You should then be able to re-run the tests without getting stuck.

Thank you so much. It may works.
But I finally gave up build from source and install it by conda.
