### ISSUE TITLE
How to use Random forest model?

### ISSUE THREAD

**Issue by sym823808458** [deepchem/deepchem#1554]
I wanna use RF model to train the dataset.I ran the code below.
'''
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D

import numpy as np
import deepchem as dc
from deepchem.molnet import load_tox21

# Only for debug!
np.random.seed(123)

# Load Tox21 dataset
n_features = 1024
tox21_tasks, tox21_datasets, transformers = load_tox21()
train_dataset, valid_dataset, test_dataset = tox21_datasets
# Fit models
metric = dc.metrics.Metric(
    dc.metrics.roc_auc_score, np.mean, mode="classification")
import sklearn
from sklearn.ensemble import RandomForestClassifier
nb_epoch = 10
model = sklearn.ensemble.RandomForestClassifier(
    len(tox21_tasks),
    train_dataset.get_data_shape()[0])

# Fit trained model
model.fit(train_dataset)
model.save()

print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)
'''
And I got the error below:
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a670feef8598> in <module>
     10 
     11 # Fit trained model
---> 12 model.fit(train_dataset)
     13 model.save()
     14 

TypeError: fit() missing 1 required positional argument: 'y'

Please who can tell m what should I do?
Thanks alot

**Comment by peastman** [comment]
Try this.  Change

```python
model = sklearn.ensemble.RandomForestClassifier(len(tox21_tasks), train_dataset.get_data_shape()[0])
```

to

```python
sklearn_model = sklearn.ensemble.RandomForestClassifier(len(tox21_tasks), train_dataset.get_data_shape()[0])
model = dc.models.SklearnModel(sklearn_model)
```

Scikit-learn doesn't know about DeepChem datasets.  You need to wrap it in a `SklearnModel`.

**Comment by sym823808458** [comment]
Thanks,peastman.I tried your code but failed in another way.Here is the code I tried
'''
# Fit models
metric = dc.metrics.Metric(
    dc.metrics.roc_auc_score, np.mean, mode="classification")
import sklearn
from sklearn.ensemble import RandomForestClassifier
nb_epoch = 10
sklearn_model = sklearn.ensemble.RandomForestClassifier(len(tox21_tasks), train_dataset.get_data_shape()[0])
model = dc.models.SklearnModel(sklearn_model)

# Fit trained model
model.fit(train_dataset)
model.save()


print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)

'''
and the error here
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-366bd8522bea> in <module>
      9 
     10 # Fit trained model
---> 11 model.fit(train_dataset)
     12 model.save()
     13 

~/anaconda3/lib/python3.6/site-packages/deepchem/models/sklearn_models/__init__.py in fit(self, dataset, **kwargs)
     62     # Logistic regression doesn't support weights
     63     if self.use_weights:
---> 64       self.model_instance.fit(X, y, w)
     65       return
     66     self.model_instance.fit(X, y)

~/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py in fit(self, X, y, sample_weight)
    326                     t, self, X, y, sample_weight, i, len(trees),
    327                     verbose=self.verbose, class_weight=self.class_weight)
--> 328                 for i, t in enumerate(trees))
    329 
    330             # Collect newly grown trees

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    623                 return False
    624             else:
--> 625                 self._dispatch(tasks)
    626                 return True
    627 

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    586         dispatch_timestamp = time.time()
    587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 588         job = self._backend.apply_async(batch, callback=cb)
    589         self._jobs.append(job)
    590 

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    109     def apply_async(self, func, callback=None):
    110         """Schedule a func to be run"""
--> 111         result = ImmediateResult(func)
    112         if callback:
    113             callback(result)

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    330         # Don't delay the application, to avoid keeping the input
    331         # arguments in memory
--> 332         self.results = batch()
    333 
    334     def get(self):

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

~/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py in _parallel_build_trees(tree, forest, X, y, sample_weight, tree_idx, n_trees, verbose, class_weight)
    110         indices = _generate_sample_indices(tree.random_state, n_samples)
    111         sample_counts = np.bincount(indices, minlength=n_samples)
--> 112         curr_sample_weight *= sample_counts
    113 
    114         if class_weight == 'subsample':

ValueError: operands could not be broadcast together with shapes (6264,12) (6264,) (6264,12)

**Comment by peastman** [comment]
That's a multitask dataset (12 tasks), but I don't think RandomForestClassifier supports that.  Try extracting just one task, then fitting a random forest to that.  Something along these lines:

```python
task_dataset = dc.data.NumpyDataset(train_dataset.X, train_dataset.y[:,task], train_dataset.w[:,task])
model.fit(task_dataset)
```

**Comment by VIGS25** [comment]
The Sklearn page (https://scikit-learn.org/stable/modules/multiclass.html), says that RandomForestClassifier supports both multiclass-multioutput classification, by default.

What is more surprising is the error `operands could not be broadcast together with shapes (6264,12) (6264,) (6264,12)`. Inside the DeepChem environment, I manually try the following script:

```
import numpy as np

a = np.ones((12, 12))
b = np.ones(12)

a *= b
```

This runs without any errors, and looks like the exact same operation that RandomForestClassifier threw an error in. Need to look at it in depth.

**Comment by sym823808458** [comment]
So do you figure it out?I tried several methods but failed again and again.Do you have any advice here?
Thanks for your trying.

**Comment by VIGS25** [comment]
Sorry, I haven't had the time to look at this now, and won't be able to get to it until Easter break. But I would presume, doing what @peastman suggested above. That should definitely work, since its just a single-task.

**Comment by rbharath** [comment]
Going to close this old issue. Feel free to re-open if this is still a problem!
