### ISSUE TITLE
Unable to Use Atomic Featurizer on PDBBind Dataset

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1555]
- DeepChem Version: 2.1.0
- Platform: OS; python 3.5

I am trying to load in the pdbbind dataset using the atomic featurizer. I believe the function to use is dc.molnet.load_pdbbind(featurizer="atomic") (as used in the example https://github.com/deepchem/deepchem/blob/9f7fa85755ab678885fe12f30df3efca71188db2/examples/pdbbind/pdbbind_atomic_conv.py)
However, I get the following error:
AttributeError: module 'deepchem.molnet' has no attribute 'load_pdbbind'

I know that the function dc.molnet.load_pdbbind_grid() will not work because when I read through the code there is no option that creates an atomic featurizer.

Here is my pdbbind_datasets.py file, which includes the load_pdbbind function so I don't know why it is giving me a no attribute error.
[pdbbind_datasets.py.zip](https://github.com/deepchem/deepchem/files/3025877/pdbbind_datasets.py.zip)

**Comment by peastman** [comment]
That ought to work.  Perhaps there's something wrong in your installation?  What happens when you run that example?

**Comment by fredrikszm** [comment]
When I run:
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="atomic")

I get the following error:
AttributeError                            Traceback (most recent call last)
<ipython-input-29-98f936b79ed6> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="atomic")
      2 
      3 # feat=atomic, subset=core by default (featurizes core subset of pdbbind using rdkitgridfeaturizer)
      4 # this function actually loads in a pre-featurized version of the dataset

AttributeError: module 'deepchem.molnet' has no attribute 'load_pdbbind'

----------------------------------------------------------------------------------------
When I run:
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(featurizer="atomic")

I get this error:
Loading raw samples now.
shard_size: 8192
About to start loading CSV from /var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/core_smiles_labels.csv
Loading shard 1 of size 8192.
Featurizing sample 0

AttributeError                            Traceback (most recent call last)
<ipython-input-30-1ba3c4a51c2f> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(featurizer="atomic")
      2 
      3 # feat=atomic, subset=core by default (featurizes core subset of pdbbind using rdkitgridfeaturizer)
      4 # this function actually loads in a pre-featurized version of the dataset

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind_grid(split, featurizer, subset, reload)
    110     loader = deepchem.data.CSVLoader(
    111         tasks=tasks, smiles_field="smiles", featurizer=featurizer)
--> 112     dataset = loader.featurize(dataset_file, shard_size=8192)
    113     transformers = [
    114         deepchem.trans.NormalizationTransformer(

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/data_loader.py in featurize(self, input_files, data_dir, shard_size)
    239 
    240     return DiskDataset.create_dataset(
--> 241         shard_generator(), data_dir, self.tasks, verbose=self.verbose)
    242 
    243   def get_shards(self, input_files, shard_size):

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/datasets.py in create_dataset(shard_generator, data_dir, tasks, verbose)
    563     metadata_rows = []
    564     time1 = time.time()
--> 565     for shard_num, (X, y, w, ids) in enumerate(shard_generator):
    566       basename = "shard-%d" % shard_num
    567       metadata_rows.append(

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/data_loader.py in shard_generator()
    217           self.get_shards(input_files, shard_size)):
    218         time1 = time.time()
--> 219         X, valid_inds = self.featurize_shard(shard)
    220         ids = shard[self.id_field].values
    221         ids = ids[valid_inds]

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/data_loader.py in featurize_shard(self, shard)
    261   def featurize_shard(self, shard):
    262     """Featurizes a shard of an input dataframe."""
--> 263     return featurize_smiles_df(shard, self.featurizer, field=self.smiles_field)
    264 
    265 

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/data/data_loader.py in featurize_smiles_df(df, featurizer, field, log_every_N, verbose)
     77     if ind % log_every_N == 0:
     78       log("Featurizing sample %d" % ind, verbose)
---> 79     features.append(featurizer.featurize([mol]))
     80   valid_inds = np.array(
     81       [1 if elt.size > 0 else 0 for elt in features], dtype=bool)

AttributeError: 'str' object has no attribute 'featurize'

**Comment by peastman** [comment]
Yes, but what happens if you run the existing example?  Just type

```
python pdbbind_atomic_conv.py
```

**Comment by fredrikszm** [comment]
This is the output:

/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "atomic_conv_test.py", line 16, in <module>
    from deepchem.molnet import load_pdbbind
ImportError: cannot import name 'load_pdbbind'

**Comment by mapleleaf-soar** [comment]
@fredrikszm Please check line 16 of `/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/__init__.py`.

Yours might be `from deepchem.molnet.load_function.pdbbind_datasets import load_pdbbind_grid` but it should be `from deepchem.molnet.load_function.pdbbind_datasets import load_pdbbind_grid, load_pdbbind`.

Perhaps you installed deepchem refer to [Easy Install via Conda](https://github.com/deepchem/deepchem#easy-install-via-conda). It seems that there are some differences between the conda version and source codes in GitHub repo. The `molnet/__init__.py` in source codes includes `load_pdbbind` but that of conda version does not.

**Comment by mapleleaf-soar** [comment]
BTW, I was working on testing AtomicConv model thesedays and found some bugs in the PDBBind 
 and ACNN related code. I just wonder which version i should use if i want to contribute my codes after fixing, the conda version or source code version? @peastman

**Comment by peastman** [comment]
The github code is the most up to date version, so that's the thing to work from.  @rbharath I notice we don't have a conda package for 2.2 yet.  Are you working on that?

**Comment by rbharath** [comment]
@lilleswing Would you have bandwidth to make a DeepChem 2.2 conda cut like you did for the previous releases?

**Comment by fredrikszm** [comment]
Thank you @mapleleaf-soar that was definitely the case for me. I am able to call the function now, but it is giving me a bad file error:

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/base_classes.py", line 16, in _featurize_complex
    return featurizer._featurize_complex(mol_pdb_file, protein_pdb_file)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/atomic_coordinates.py", line 209, in _featurize_complex
    frag1_coords, frag1_mol = rdkit_util.load_molecule(mol_pdb_file)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 107, in load_molecule
    suppl = Chem.SDMolSupplier(str(molecule_file), sanitize=False)
OSError: File error: Bad input file /var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/v2015/3gcs/3gcs_ligand.sdf
"""

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
<ipython-input-2-6fc12e05da30> in <module>()
      1 pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(
----> 2     featurizer="atomic", split="random", subset="core", reload=False)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, load_binding_pocket, split, subset, reload)
    275   print("Featurizing Complexes")
    276   features, failures = featurizer.featurize_complexes(ligand_files,
--> 277                                                       protein_files)
    278   # Delete labels for failing elements
    279   labels = np.delete(labels, failures)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/base_classes.py in featurize_complexes(self, mol_files, protein_pdbs)
     51     failures = []
     52     for ind, result in enumerate(results):
---> 53       new_features = result.get()
     54       # Handle loading failures which return None
     55       if new_features is not None:

~/miniconda2/envs/mypy/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

OSError: File error: Bad input file /var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/v2015/3gcs/3gcs_ligand.sdf

Is this occurring because the featurizer does not work for this ligand file? What can I do to fix this?

**Comment by VIGS25** [comment]
I wonder if the above error is happening because a `sdf` file is supplied instead of a `pdb` one?

**Comment by fredrikszm** [comment]
I took a look in /var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/v2015 and all the subdirectories for each pdb file name are listed. The ones that were being featurized before 3gcs (the failing one), have two files inside: 
2zx6_ligand.sdf
2zx6_protein.pdb   
(in the 2zx6 subdirectory, for ex)

the subdirectories for the ones that were called after are empty. The subdirectory for 3gcs exists, but it is also empty.

**Comment by mapleleaf-soar** [comment]
@fredrikszm Where did you get your PDBBind dataset? Was it downloaded by function `load_pdbbind()`?

I used `load_pdbbind()` with PDBBind **core** subset and it worked well. I saw the error similar to that you mentioned before, which was because required input files were missing. So please check whether the file `/var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/v2015/3gcs/3gcs_ligand.sdf` exists.

If not, delete `pdbbind_v2015.tar.gz` and folder `/var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/v2015/` then rerun `load_pdbbind()` to download and unpack the full dataset. If you lives in China, you can download it from `http://www.pdbbind.org.cn/download/` which might be more faster.

**Comment by mapleleaf-soar** [comment]
@fredrikszm Sorry to misunderstund your last sentence. If the subdirectory for 3gcs is empty, the reason is exactly it.

@peastman @rbharath @VIGS25 I got something wrong when I used `load_pdbbind()` with PDBBind **refined** subset.

> ~/opt/miniconda3/envs/dc_test/lib/python3.6/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(reload, data_dir, subset, load_binding_pocket, featurizer, split, split_seed, save_dir, save_timestamp)
    300   feat_t1 = time.time()
    301   features, failures = featurizer.featurize_complexes(ligand_files,
--> 302                                                       protein_files)
    303   feat_t2 = time.time()
    304   print("\nFeaturization finished, took %0.3f s." % (feat_t2 - feat_t1))
> 
> ~/opt/miniconda3/envs/dc_test/lib/python3.6/site-packages/deepchem/feat/base_classes.py in featurize_complexes(self, mol_files, protein_pdbs)
     51     failures = []
     52     for ind, result in enumerate(results):
---> 53       new_features = result.get()
     54       # Handle loading failures which return None
     55       if new_features is not None:
> 
> ~/opt/miniconda3/envs/dc_test/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    668             return self._value
    669         else:
--> 670             raise self._value
    671 
    672     def _set(self, i, obj):
> 
> Exception: Particle coordinate is nan

I guessed it was because data of refined subset is a little worse than that of core subset. I changed code of `featurize_complexes()` in `deepchem.feat.base_classes.py`

```python
for ind, result in enumerate(results):

  ########################## old code
  new_features = result.get()
  ########################## old code

  ########################## new code
  try:
    new_features = result.get()
  except:
    new_features = None
  ########################## new code

  # Handle loading failures which return None
  if new_features is not None:
    features.append(new_features)
  else:
    failures.append(ind)
```
I donot know if it's a good method to address this problem of refined subset. If you think it's fine I will make a PR with this change.

**Comment by fredrikszm** [comment]
@mapleleaf-soar I tried what you recommended and the code ran for a very long time (a few hrs), and gave the following error:

Featurizing Complexes
WARNING:root:Unable to add hydrogens math domain error

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 55, in add_hydrogens_to_mol
    fixer.addMissingHydrogens(7.4)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
    modeller.addHydrogens(pH=pH)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 752, in addHydrogens
    if isHbond(ne2Pos, he2Pos, acceptorPos):
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 681, in isHbond
    return acos(dot(deltaDH, deltaHA)) < 50*degree
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/simtk/unit/unit_math.py", line 103, in acos
    return math.acos(x) * radians
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/base_classes.py", line 16, in _featurize_complex
    return featurizer._featurize_complex(mol_pdb_file, protein_pdb_file)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/atomic_coordinates.py", line 210, in _featurize_complex
    frag2_coords, frag2_mol = rdkit_util.load_molecule(protein_pdb_file)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 123, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "/Users/fredrikszm/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 66, in add_hydrogens_to_mol
    raise MoleculeLoadException(e)
deepchem.utils.rdkit_util.MoleculeLoadException
"""

The above exception was the direct cause of the following exception:

MoleculeLoadException                     Traceback (most recent call last)
<ipython-input-2-6fc12e05da30> in <module>()
      1 pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(
----> 2     featurizer="atomic", split="random", subset="core", reload=False)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, load_binding_pocket, split, subset, reload)
    275   print("Featurizing Complexes")
    276   features, failures = featurizer.featurize_complexes(ligand_files,
--> 277                                                       protein_files)
    278   # Delete labels for failing elements
    279   labels = np.delete(labels, failures)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/base_classes.py in featurize_complexes(self, mol_files, protein_pdbs)
     47           pool.apply_async(_featurize_complex,
     48                            (self, mol_file, protein_pdb, log_message)))
---> 49     output = [p.get() for p in results]
     50     print(output)
     51     pool.close()

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/base_classes.py in <listcomp>(.0)
     47           pool.apply_async(_featurize_complex,
     48                            (self, mol_file, protein_pdb, log_message)))
---> 49     output = [p.get() for p in results]
     50     print(output)
     51     pool.close()

~/miniconda2/envs/mypy/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

MoleculeLoadException: 

WARNING:root:Unable to add hydrogens Particle position is NaN
WARNING:root:Unable to add hydrogens Particle position is NaN

**Comment by fredrikszm** [comment]
In addition, many of the pdb file directories in the v2015 folder still do not contain data.

@peastman @rbharath @VIGS25 any idea why this is occurring?
