### ISSUE TITLE
Reverse featurization for GAN

### ISSUE THREAD

**Issue by danieldemarch** [deepchem/deepchem#1559]
I see no methods to actually reverse the featurization once a GAN has created output. This makes things tricky because obviously what I need is the original SMILES, not the ECFP. Is there some module I am missing?

**Comment by peastman** [comment]
Could you explain what model you're talking about?  Showing your source code would be helpful.

A GAN is a generative model.  It produces whatever kind of output you train it to produce, whether that's SMILES or ECFP or something else.  It doesn't know anything about featurization.  It just knows what data it was trained on, and tries to produce new data that resembles it.

**Comment by danieldemarch** [comment]
Hey, thanks for getting back so fast.

I'm training multiple GANs on two different general featurizations (Raw and ECFP) as well as several types of ECFP (three different vector sizes, three different fingerprint radiuses). For my research I need to be able to take the output of a GAN with input from one featurization and convert freely. 

So let's say I train my GAN with my data featurized with an ECFP of radius 4. I want to be able to have the GAN output some data, then convert that data back to SMILES, and from there either keep it as SMILES or convert it to a different ECFP (say radius 2.)

**Comment by danieldemarch** [comment]
Basically what I was wondering is if there is already an implementation for this, since I see that your ECFP implementation is deterministic, or if I will need to create my own.

**Comment by danieldemarch** [comment]
@peastman sorry

**Comment by peastman** [comment]
That's impossible.  ECFP is a lossy transformation, so you can't reverse it.  Multiple different molecules can have identical fingerprints.

**Comment by danieldemarch** [comment]
@peastman 

Are any featurizations reversible?

**Comment by rbharath** [comment]
Picking up on this thread, I don't believe any featurizers (except `dc.feat.RawFeaturizer` which just represents the molecule as the smiles string) are reversible.
