### ISSUE TITLE
ConvGraph hyperparameter optimization

### ISSUE THREAD

**Issue by SeanXiaoyuSun** [deepchem/deepchem#1560]
Hi all,

I'm using [ConvGraph model](https://github.com/deepchem/deepchem/blob/ed586b32f90f85b901f9712bb3cd97f0471ac08c/deepchem/models/tensorgraph/models/graph_models.py#L593) for my project. I got good results but I think tuning hyperparameters can make it better. I noticed that there is a[ grid_search.py](https://github.com/deepchem/deepchem/blob/master/deepchem/hyper/grid_search.py) file for optimizing hyperparameters but I don't quite get how to use it. I looked into the [test_hyperparam_opt.py](https://github.com/deepchem/deepchem/blob/master/deepchem/hyper/tests/test_hyperparam_opt.py) file in the test folder. There are two points I'm confused about. 
https://github.com/deepchem/deepchem/blob/ed586b32f90f85b901f9712bb3cd97f0471ac08c/deepchem/hyper/tests/test_hyperparam_opt.py#L49-L54
Firstly, what should I pass to the `param_dict`, if I want to tune ConvGraph model's hyperparameters? Also, what does `model_builder` do here? What changes should I make to implement a `model_builder` for ConvGraph model?

Thank you!

**Comment by VIGS25** [comment]
@SeanXiaoyuSun 

`param_dict` should contain the arguments of GraphConvModel, and a list with the corresponding values for that argument you'd like to run hyperparameter search over.

A simple example would be:
```
param_dict = {"dense_layer_size": [128, 256, 512]}
```
You can add similar lists for other arguments.

`model_builder` here takes in a `model_params` dictionary, and a `model_dir` and returns a model with the corresponding parameters used. 

**NOTE**: `model_params` dictionary should not be confused with the `param_dict` defined above. `param_dict` contains all possible configurations to investigate, while the `model_params` contains only a particular instance. For this case, `model_params` would be {"dense_layer_size": 128}, for the `param_dict` defined above.

A simple implementation of the builder can be found here:

```
def gc_model_builder(model_params): 
   gc_model = GraphConvModel(**model_params) 
   return gc_model
```
You can modify the functions downstream accordingly.

Let me know if there's an issue with getting this right, and I'll help you fix it.

**Comment by SeanXiaoyuSun** [comment]
@VIGS25 
Thank you for your reply!
I tried implementing the optimizer based on your suggestion, but got this error:
```
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
Fitting model 1/3
hyperparameters: {'dense_layer_size': 128}
Traceback (most recent call last):
  File "param_opt_test.py", line 45, in <module>
    logdir=None)
  File "/u/x/i/xiaoyus/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/hyper/grid_search.py", line 79, in hyperparam_search
    model = self.model_class(model_params, model_dir)
TypeError: gc_model_builder() takes from 0 to 1 positional arguments but 2 were given

```
The following is my implementation:
```
# load flashpoint data set
flashpoint_tasks, flashpoint_datasets, transformers = dc.molnet.load_flashpoint(
    "/u/x/i/xiaoyus/private",
    featurizer='GraphConv')
train_dataset, valid_dataset, test_dataset = flashpoint_datasets

# Define metric for eavluating the model by using RMSE
metric = dc.metrics.Metric(dc.metrics.rms_score, np.mean)

params_dict = {"dense_layer_size": [128, 256, 512]}

def gc_model_builder(model_params = {"dense_layer_size": 128}): 
   gc_model = GraphConvModel(**model_params) 
   return gc_model

optimizer = dc.hyper.HyperparamOpt(gc_model_builder)
best_model, best_hyperparams, all_results = optimizer.hyperparam_search(
    params_dict,
    train_dataset,
    valid_dataset,
    transformers,
    metric,
    logdir=None)

print(best_model)
print(best_hyperparameters)
print(all_results)
```

Actually I'm still confused about `params_dict` and `model_params`. Can I pass multiple parameters to `params_dict`? For example, something like:  
```
params_dict = {"dense_layer_size": [128, 256, 512],
                         "number_atom_features": [75,100,125]}
```
Also, I'm a bit confused about the hyperparameters of GraphConvModel. In the [__init__()](https://github.com/deepchem/deepchem/blob/ed586b32f90f85b901f9712bb3cd97f0471ac08c/deepchem/models/tensorgraph/models/graph_models.py#L595) of  GraphConvModel, the parameters are 
```
  def __init__(self,
               n_tasks,
               graph_conv_layers=[64, 64],
               dense_layer_size=128,
               dropout=0.0,
               mode="classification",
               number_atom_features=75,
               n_classes=2,
               uncertainty=False,
               **kwargs):
```
But in [preset_hyper_parameters.py](https://github.com/deepchem/deepchem/blob/354cb7c24bbc324953fadc13405cd662e27a9bec/deepchem/molnet/preset_hyper_parameters.py#L128-L135), GraphConvModel has the following parameters:
```
hps['graphconvreg'] = {
    'batch_size': 128,
    'nb_epoch': 100,
    'learning_rate': 0.0005,
    'n_filters': 128,
    'n_fully_connected_nodes': 256,
    'seed': 123
}
```
So what should I consider as the hyperparameters of GraphConvModel?

About  `model_params`, why should I pass {"dense_layer_size": 128} to it? From my understanding, the  `model_params` is used to initialize a model. After initialization, we can use optimizer to iterate through the range of hyperparameter given in the  `params_dict` to find the best parameter value. Am I understanding this correctly?
And could you also explain what is `model_dir` in the model_builder?

Thank you very much!

**Comment by SeanXiaoyuSun** [comment]
Hi @VIGS25,

I'm still working on parameter optimization for GraphConvModel. I modified my code and it seemingly is working now. My implementation is attached at the end.
But I still have several questions: 
- Firstly, still about `gc_model_builder(model_params , model_dir)`, do I need to pass anything to `model_params` at all? In my implementation, I'm not passing anything to  `model_params` and it works. 
- Secondly, how can I change the epoch number and batch size of this model? I tried adding them to the `params_dict` but it seems like to be not working, since np_epoch=1 and np_epoch =100 gave almost same scores. I think this is because epoch number and batch size are not the parameters defined in [GrapgConvModel's init()](https://github.com/deepchem/deepchem/blob/ed586b32f90f85b901f9712bb3cd97f0471ac08c/deepchem/models/tensorgraph/models/graph_models.py#L595-L604). Also, you can notice that I added `"invalidaparam!!!":[50]` in `params_dict`. I was thinking this should lead to some kind of error, but it just ran successfully. How to understand this behavior?
- Thirdly, I notice that this [grid_search.py](https://github.com/deepchem/deepchem/blob/master/deepchem/hyper/grid_search.py) is returning the model having the highest score returned from evaluation based on the user-provided metric. However, if I want to use RMSE (rooted mean squared error) as metric, the best model should be the model with the lowest RMSE score instead of the highest score. 
- Fourthly (Sorry for so many questions :) ), this question is actually not really about optimization. I used loader function provided in the deepchem package before and I got bad result, but when I implemented the loading, featurizing, transforming and splliting parts by my own, I got better result. I think this is sort of strange. Could you have a look at my implementation and help me check if I'm implementing the loader function part correctly?  Thanks!






This is my implementation:
```
#load data set
data_dir = "/u/x/i/xiaoyus/private/Skunkworks"  
train_dataset_file = os.path.join(data_dir, "data.csv")
if not os.path.exists(train_dataset_file):
    print("data set was not found in the given directory")
flashpoint_tasks = ['flashPoint']
loader = dc.data.CSVLoader(
    tasks=flashpoint_tasks, smiles_field="smiles", featurizer = dc.feat.ConvMolFeaturizer())
train_dataset = loader.featurize(train_dataset_file, shard_size=8192)
    
# Initialize transformers
transformers = [
    dc.trans.NormalizationTransformer(
    transform_y=True, dataset=train_dataset, move_mean=True) 
]
for transformer in transformers:
    train_dataset = transformer.transform(train_dataset)

# define splitter 
splitter = dc.splits.RandomSplitter()
train_set, valid_set = splitter.train_test_split(train_dataset) 

# Define metric for evaluating the model by using Pearson R2
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score, np.mean)

params_dict = {
    "np_epoch":[1,100],
    "invalidparam!!!":[50],
    "n_tasks":[1],
    "graph_conv_layers":[[64, 64]],
    "dense_layer_size":[128,256,512],
    "dropout":[0.0],
    "mode":["regression"],
    "number_atom_features":[75],
}

def gc_model_builder(model_params , model_dir): 
    gc_model = GraphConvModel(**model_params, model_dir = "/u/x/i/xiaoyus/private/Skunkworks") 
    return gc_model

optimizer = dc.hyper.HyperparamOpt(gc_model_builder)
best_model, best_hyperparams, all_results = optimizer.hyperparam_search(
    params_dict,
    train_set,
    valid_set,
    transformers,
    metric,
    logdir=None)

#printing out results
print("\n===================BEST MODEL=================")
print(best_model)
print("\n===================BEST Params=================")
print(best_hyperparams)
print("\n===================ALL_RESULTS=================")
print(all_results)```

**Comment by VIGS25** [comment]
> Firstly, still about gc_model_builder(model_params , model_dir), do I need to pass anything to model_params at all? In my implementation, I'm not passing anything to model_params and it works

No, you don't need to pass anything to the `model_params`.

> Secondly, how can I change the epoch number and batch size of this model? I tried adding them to the params_dict but it seems like to be not working, since np_epoch=1 and np_epoch =100 gave almost same scores. I think this is because epoch number and batch size are not the parameters defined in GrapgConvModel's init(). Also, you can notice that I added "invalidaparam!!!":[50] in params_dict. I was thinking this should lead to some kind of error, but it just ran successfully. How to understand this behavior?

`batch_size` is definitely a parameter you can specify while defining the model (The basic TensorGraph model accepts a `batch_size` argument). For the epoch, I think you should use `nb_epochs` and not `nb_epoch`. About the invalidparam, I would think it just gets ignored since its not really a parameter and hence no errors raised. There must be a check somewhere to ignore it, I'd have to check where.

> Thirdly, I notice that this grid_search.py is returning the model having the highest score returned from evaluation based on the user-provided metric. However, if I want to use RMSE (rooted mean squared error) as metric, the best model should be the model with the lowest RMSE score instead of the highest score.

If you read the function arguments carefully, you can see there is a `use_max=True` option. You need to set it to False to get the lower scores.

> Fourthly (Sorry for so many questions :) ), this question is actually not really about optimization. I used loader function provided in the deepchem package before and I got bad result, but when I implemented the loading, featurizing, transforming and splliting parts by my own, I got better result. I think this is sort of strange. Could you have a look at my implementation and help me check if I'm implementing the loader function part correctly? Thanks!

This I'll check and get back to you. I still have issues understanding why you should do the train-test split after doing the transformation. This introduces dependencies between train-test data and give you over-optimistic results. I know this is present in the DeepChem load functions too.

**Comment by SeanXiaoyuSun** [comment]
Thank you! 
I'm actually still not sure about whether adding `"np_epochs":[some range]` in `params_dict` is working or not. I changed  `np_epoch` to `np_epochs`.  From my understanding, the Pearson_R2 should increase with the increase of epoch number (at lease for the first several epoch number since overfitting should not occur so early). But setting different epoch number to my model gave similar scores:
```
('regression', 1) :  0.84
('regression', 20) :  0.83
('regression', 30) :  0.82
('regression', 40) :  0.83
('regression', 50) :  0.79
('regression', 60) :  0.8
('regression', 70) :  0.86
('regression', 80) :  0.79
('regression', 90) :  0.8
('regression', 100) :  0.8
('regression', 150) :  0.84
('regression', 200) :  0.83
('regression', 300) :  0.82
('regression', 400) :  0.81
```

Also, the Pearson_R2 scores returned by `grid_search.py` are lower than what I got from another [testing file ](https://github.com/SeanXiaoyuSun/Molecular-Properties/blob/bee8e4c777b9afe82be86f3d5e15ab5ae9d49274/Carroll11/Cross_Validaion_carroll11.py#L17-L46) (with  same data set and same other hyperparameters) where I manually split training set and test set (I loaded training and test data sets separately). 
So, so far, I found:
`Pearson_R2 score from using load function < manually implementing load function + using train_test splitter < manually implementing load function + manually split training set and test set`
This is really confusing to me. Though the way of splitting data set may be the reason, I don't think it could lead to this kind of big difference (I got score of ~0.91 by using the method I described) and I actually got the training set and test set by some kind of random splitting method. Do you have any idea about what's happening here? Do you think should I open a new issue about this data set loading problem?

**Comment by VIGS25** [comment]
> I'm actually still not sure about whether adding "np_epochs":[some range] in params_dict is working or not. I changed np_epoch to np_epochs. From my understanding, the Pearson_R2 should increase with the increase of epoch number (at lease for the first several epoch number since overfitting should not occur so early). But setting different epoch number to my model gave similar scores:

Its not `np_epochs`, its `nb_epochs` (Notice the difference between b and p)

For the rest, I'd suggest you send me the scripts you used, because I'm unable to follow everything right now.

**Comment by SeanXiaoyuSun** [comment]
Sorry about the typo. But using `nb_epochs` gives me similar result:
```
(1, 'regression') :  0.75
(20, 'regression') :  0.81
(30, 'regression') :  0.78
(40, 'regression') :  0.83
(50, 'regression') :  0.77
(60, 'regression') :  0.76
(70, 'regression') :  0.8
(80, 'regression') :  0.74
(90, 'regression') :  0.81
```
Is it because the `nb_epochs` is not really passed into the model or `nb_epochs` has no effect for this model on this task?

The following is my script mentioned in my previous post (you can also find the github version via the link in my previous post): 
```
data_dir = "/u/x/i/xiaoyus/private/Skunkworks/Carroll11"  
train_dataset_file = os.path.join(data_dir, "carroll_all_trainval.csv")
test_dataset_file = os.path.join(data_dir, "carroll_all_int.csv")
if not os.path.exists(train_dataset_file) or not os.path.exists(test_dataset_file):
    print("data set was not found in the given directory")
flashpoint_tasks = ['flashPoint']
loader = deepchem.data.CSVLoader(
    tasks=flashpoint_tasks, smiles_field="smiles", featurizer = deepchem.feat.ConvMolFeaturizer())
train_dataset = loader.featurize(train_dataset_file, shard_size=8192)
test_dataset = loader.featurize(test_dataset_file, shard_size=8192)
    
# Initialize transformers for train_dataset
transformers = [
    deepchem.trans.NormalizationTransformer(
    transform_y=True, dataset=train_dataset, move_mean=True) 
]
for transformer in transformers:
    train_dataset = transformer.transform(train_dataset)
# Initialize transformers for test_dataset
transformers = [
    deepchem.trans.NormalizationTransformer(
    transform_y=True, dataset=test_dataset, move_mean=True) 
]
for transformer in transformers:
    test_dataset = transformer.transform(test_dataset)

# define splitter for cross validation    
splitter = deepchem.splits.RandomSplitter()
#train, valid, test = splitter.train_valid_test_split(train_dataset) 
split_datas = splitter.k_fold_split(train_dataset,5)

# define the RMSE metric
metric = dc.metrics.Metric(dc.metrics.rms_score, np.mean)

# conduct cross-validation
validation_scores = []
train_scores = []
for train_set, val_set in split_datas:
    model = dc.models.GraphConvModel(len(flashpoint_tasks),batch_size = 50, mode='regression')
    model.fit(train_set, nb_epoch = 80)
    train_score = model.evaluate(train_set, [metric], transformers)
    train_scores.append(list(train_score.values()).pop()) 
    valid_score = model.evaluate(val_set, [metric], transformers)
    validation_scores.append(list(valid_score.values()).pop())    
    
# print out the results of cross validation    
print("===========Final Results===========")
cross_train_score = 0    
for val in train_scores:
    cross_train_score += val
cross_train_score = cross_train_score/5
print("cross_train_score: ")
print(cross_train_score)
cross_validation_score = 0    
for val in validation_scores:
    cross_validation_score += val
cross_validation_score = cross_validation_score/5
print("cross_validation_score: ")
print(cross_validation_score)

# train the model with the whole traning set and get the test score
model = dc.models.GraphConvModel(len(flashpoint_tasks),batch_size = 50, mode='regression')
model.fit(train_dataset, nb_epoch= 80)
print("cross_test_score: ")
test_score = model.evaluate(test_dataset, [metric], transformers)
```

Really thank you for your time!

**Comment by SeanXiaoyuSun** [comment]
I just figured out that I had a silly typo again. It should be `nb_epoch` rather than `nb_epochs`. It works for different epoch number now! 
So the dataset loading problem is the only problem now! Could you have a look at my code and help me check if it is correct? This is really important for my project since it directly effects the result! Thank you again!

**Comment by VIGS25** [comment]
I would recommend doing the train-valid-test split before the `NormalizationTransformer` because it will prevent any dependencies between train, test and valid datasets. 
The rest of the code looks alright!

**Comment by SeanXiaoyuSun** [comment]
Thank you very much!

**Comment by SeanXiaoyuSun** [comment]
Hi @VIGS25 , I'm still confused about the issue about transforming and splitting. I think your suggestion is reasonable. Splitting before transforming gives less dependency between test set and training set. In this way I will have two transformers. So, which transformer should I pass to the [evaluation method](https://deepchem.io/docs/deepchem.utils.html#deepchem.utils.evaluate.Evaluator) when evaluating my model? Should it be the one used to transform training set or the one used to transform test dataset? 

Also, I noticed many examples normalized dataset before passing data into models. But why do we need to transform our datasets' Y? The only advantage I can come up with is that transformation makes it computationally cheaper.

**Comment by Lidweixiang** [comment]
> I would recommend doing the train-valid-test split before the `NormalizationTransformer` because it will prevent any dependencies between train, test and valid datasets.
> The rest of the code looks alright!

Hi @VIGS25！I may disagree with your point ！Maybe a unified transformer is better to show the relationship between before the transform and after the transform. And If you use different transformers, using this model to evaluate the test dataset is quite strange
