### ISSUE TITLE
Tunning parameters "graph_conv_layers" and "dense_layer_size" for GraphConvModel

### ISSUE THREAD

**Issue by ZuoyiLi** [deepchem/deepchem#1562]
**Description:**

- DeepChem Version:
- Platform:

Hi. I am not familiar with concepts about graph convolutional neural network. I read some paper and thought that "graph_conv_layer" is equivalent to number of layers, is this correct? The description in the code (" Width of channels for the Graph Convolution Layers") is still hard for me to understand and I am confused about the meaning of "channel". I am confused since there seems to exist more than one version of explanation. Could some one help me understand the meaning of these two parameters? I would really appreciate the help!

And from the default values of "graph_conv_layers" and "dense_layer_size", which are [64, 64] and 128, should I assume that dense_layer_size should be sum of graph_conv_layers? Or there are more nuances? Thank you!

**Comment by rbharath** [comment]
Sorry for not responding here earlier! I think it slipped through my inbox.

The channels are the number of different outputs per node that the graph Conv layer outputs. I believe `graph_conv_layer` is the number of graph convolutional layers. `dense_layer_size` is the number of fully connected units at the dense layer. It doesn't have to be the sum of `graph_conv_layers` and I believe can be anything you like.

I'm going to close this old issue, but please re-open if you still have questions!
