### ISSUE TITLE
Papers to possibly replicate in DeepChem

### ISSUE THREAD

**Issue by VIGS25** [deepchem/deepchem#1563]
**Title: End-to-end differentiable learning of protein structure**

Link: https://www.biorxiv.org/content/biorxiv/early/2018/08/29/265231.full.pdf
Code: https://github.com/aqlaboratory/proteinnet
Very interesting read. Will attempt to duplicate this in DeepChem sometime during my thesis later.

**Comment by rbharath** [comment]
That's a really interesting paper. You might find https://github.com/aqlaboratory/proteinnet a good reference (it's the repo tied to the paper)

**Comment by VIGS25** [comment]
There's also another paper on protein engineering using deep unsupervised learning, by the same author and a couple of other guys. 
Paper Link: https://www.biorxiv.org/content/10.1101/589333v1
Code: https://github.com/churchlab/UniRep

**Comment by VIGS25** [comment]
Title: Molecular Geometry Prediction using a Deep Generative Graph Neural Network
Link: https://arxiv.org/abs/1904.00314
Code: https://github.com/nyu-dl/dl4chem-geometry

**Comment by VIGS25** [comment]
**Title: Deciphering Interaction Fingerprints from protein-molecular structure**
Link: https://www.biorxiv.org/content/biorxiv/early/2019/04/11/606202.full.pdf
Code: https://github.com/lpdi-epfl/masif

**Comment by rbharath** [comment]
Closing this issue in favor of continuing the discussion in #1727
