### ISSUE TITLE
Best way to load in PDB files for prediction?

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1564]
If I want to take two PDB files (ex: protein and ligand) and make a prediction about their binding affinity using a model I have already created, how can I best go about this?

Do I take in the SMILES of each, create a pandas dataframe, and then turn this into a csv and load as a deepchem dataset object, as shown in the following?:

loader = dc.data.CSVLoader(tasks=['Val'],
                               smiles_field="SMILES",
                               featurizer=featurizer)
dataset = loader.featurize(infile_name, shard_size=8192)
pred = model.predict(dataset)

or is there a way to turn the PDB file itself into a form a featurizer can take in and then use model.predict()? [preferred]

**Comment by VIGS25** [comment]
There are many featurizers in DeepChem, that can take in PDB files of ligand and proteins and compute features. What kind of features are computed depends upon what your model takes as input.
