### ISSUE TITLE
can't get the optimal hyperparameters

### ISSUE THREAD

**Issue by tytcc** [deepchem/deepchem#1571]
**Description:**
Hi, I know we can get the hyperparameters for MoleculeNet models from http://deepchem.io.s3-website-us-west-1.amazonaws.com/trained_models/Hyperparameter_MoleculeNetv3.tar.gz
but it doesn't seem to work.
where else can I get the hyperparameters?

**Comment by fredrikszm** [comment]
In what way does it not work? For me, I was able to use the link to download then I moved the desired file into the same directory I was running my notebook from. Then the following code should allow you to open the file as a dict (with 'serialized.pkl' replaced by the file name)

import pickle
with open('serialized.pkl', 'rb') as f:
    data = pickle.load(f)

**Comment by tytcc** [comment]
@fredrikszm  Thanks.
but I can't open the link which I don't the reason.

**Comment by fredrikszm** [comment]
Glad to help!
