### ISSUE TITLE
MAML and architecture changes

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1572]
I'm trying to figure out how to keep MAML (model agnostic metalearning) working with all the architectural changes we're making.  My changes in #1567 have broken it.  I've verified that this is caused by the change to keras layers.  Simply changing one line to replace `tf.layers.Dense` with `tf.keras.layers.Dense` causes it to stop working.

 MAML is an unusual algorithm.  Most models are defined by a series of layers, with each layer defining both a set of variables and a calculation to do.  You might call the layer several times with different inputs, but it always applies the came calculation with the same variables to them.

MAML is different.  You need to apply the model several times using the *same* inputs but *different* variables.  Except sometimes they aren't really variables.  They're the output of a calculation, which you need the layer to use in its calculation where it would normally use variables.  Standard layer classes just aren't written to work that way.

I solved this problem by using the `tf.contrib.graph_editor` module.  You define a model using layers, and it builds a graph from them in the normal way.  Then it clones pieces of the graph, replacing the variables with the outputs of calculations.  This works nicely but has several problems.

First, it apparently doesn't work with keras layers.  I don't know why.  I could try to figure out what they're doing differently that interferes with the graph editor.  Possibly I could get it working again.  But there are other serious problems that will also need to be dealt with very soon.

The second problem is that this approach can never work in eager mode.  It's inherently graph based.  Given that TensorFlow is moving to eager mode as the default approach for everything, that's not very satisfactory.

But a much bigger problem is that `tf.contrib.graph_editor` is going away in TensorFlow 2.  As far as I can tell, it isn't being migrated to its own project or anything like that.  It's just being abandoned and there will no longer be any supported way of doing this sort of graph manipulation.

I've tried to think of an alternate API that could be supported with TensorFlow 2, but I haven't found anything satisfactory.  This algorithm requires you to separate the definition of the variables from the definition of the computation.  You need to define the model using functions of the form `f(inputs, variables)`, where the algorithm can pass in arbitrary tensors to use as the variables.  That isn't how keras layers work, which means you wouldn't be able to use layers in defining your model.

I'm kind of stuck on this.  Any suggestions about what to do?

**Comment by peastman** [comment]
@rbharath any thoughts on this?  It's blocking #1567, which in turn is blocking lots of other things, so I'd like to reach a decision as quickly as possible.

**Comment by rbharath** [comment]
There seem to be a couple PyTorch MAML implementations out there (https://github.com/dragen1860/MAML-Pytorch). Perhaps it might be worth seeing how they got MAML to work in eager mode and seeing if a TF eager port would be possible?

**Comment by peastman** [comment]
They define the model with a function of the form `f(inputs, variables)`.  See https://github.com/dragen1860/MAML-Pytorch/blob/master/learner.py#L121.  Then they implement the calculation using the functions in `torch.nn.functional`, which is pretty similar to `tensorflow.nn`.

**Comment by peastman** [comment]
I really need to get #1567 merged, because it's blocking my other work.  For the moment I'm just going to comment out the failing test case and mark MAML as deprecated.  If we decide to make MAML work as described above, that'll take something close to a complete rewrite.

**Comment by Qi-max** [comment]
peastman <notifications@github.com>于2019年7月27日 周六05:06写道：
