### ISSUE TITLE
How to build the multi-molecule input model?

### ISSUE THREAD

**Issue by hori1537** [deepchem/deepchem#1574]
How to create the multi-molecule input model?
As shown in tutorial-tox21, we can create the model with one molecule input.
This model shows whether ethanol has tox or not.

However, I want to do regression or classification with 2 or more inputs.
For example, the solubility of A in B.  (sugar in benzene,  tetrodotoxine in ethanol, and so on)

**Comment by rbharath** [comment]
One possibility for the task you're trying to do here is to train two models, one for each solvent. You could have a benzene solubility model, ethanol solubility model and evaluate both of them.

I'm going to go ahead and close this old issue. Feel free to re-open if you have a question :)
