### ISSUE TITLE
Segfault on graph_convolutional_networks_for_tox21.ipynb notebook

### ISSUE THREAD

**Issue by alexbw** [deepchem/deepchem#1575]
**Description:**

```
>> import deepchem
>> deepchem.molnet.load_tox21(featurizer='GraphConv')

# Segfault here

Loading raw samples now.
shard_size: 8192
About to start loading CSV from /var/folders/dc/jb_mbpls6vjbhycdcjyms0qc00dh95/T/tox21.csv.gz
Loading shard 1 of size 8192.
Featurizing sample 0
python(52928,0x10c5085c0) malloc: *** error for object 0x7fbd76b56088: pointer being freed was not allocated
python(52928,0x10c5085c0) malloc: *** set a breakpoint in malloc_error_break to debug
fish: 'ipython' terminated by signal SIGABRT (Abort)
```

**Comment by alexbw** [comment]
OSX 10.14.3

Fresh anaconda install, Python 3.7

Installed deepchem with
`conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0`

**Comment by alexbw** [comment]
Works out of the box on Linux.

**Comment by peastman** [comment]
Can you try with DeepChem 2.2 instead of 2.1?

If that doesn't work, can you run `conda list` and see what version of RDKit is installed?  Some versions of it have had issues with crashing on Macs.

**Comment by alexbw** [comment]
Tried with deepchem 2.2, using the source install script. TensorFlow version compatibility issues. I'll just use Linux.

**Comment by rbharath** [comment]
The latest version of this Notebook runs correctly locally on Linux/Mac I believe. I'm going to go ahead and close this issue, but please feel free to re-open if necessary.
