### ISSUE TITLE
Would it be possible to add the MLQSAR dataset? [moleculenet]

### ISSUE THREAD

**Issue by UnixJunkie** [deepchem/deepchem#1576]
Hello,

We should have realistic sized datasets to benchmark classification methods
on HTS datasets.

How about integrating the one from:
---
Butkiewicz, M., Lowe, E., Mueller, R., Mendenhall, J., Teixeira, P., Weaver, C., & Meiler, J. (2013). Benchmarking ligand-based virtual high-throughput screening with the PubChem database. Molecules, 18(1), 735-756.
---

Here is a textual description for it:
---
 2. Results and Discussion
2.1. Compilation of Validated PubChem HTS Screens Provides Benchmark Data Sets for Training QSAR Models
PubChem provides publically available libraries of small organic molecules that have been tested in a diverse set of HTS experiments. Primary screens often include many false-positive hit compounds which display a response in initial assay experiments but are inactive in confirmatory experiments. We focus on HTS experiments with a single well-defined biological target protein. With respect to the desired target, these hit compounds may include non-binders that act on a different component of the assay or binders that are non-specific to the target and recognize other biological molecules. To minimize the number of false-positive hit compounds we compiled nine data sets applying the following criteria: the HTS experiment must target one specific protein and contain a minimum of 150 confirmed active compounds. Further, we chose a diverse set of PubChem assays focused on pharmaceutically relevant small molecule protein targets such as GPCRs, ion channels, transporters, kinase inhibitors, and enzymes. All PubChem assays are identified by PubChem summary id (SAID) of the primary protein target and describe a collection of confirmatory screens for active compounds given by PubChem assay ids (AID). It proved critical to go through a detailed manual verification of the HTS experiments performed and collate PubChem raw data to arrive at high-quality data sets.
---

So, nine protein targets, with between 60k to 300k molecules per target.

I have a version somewhere where all molecules have been standardized and separated per target. I could turn it into some CSV files, if that's what you need.

Note that the paper should be cited when people use the dataset, as a courtesy for the people who did the work.

Regards,
F.

**Comment by UnixJunkie** [comment]
I thought MoleculeNet was on the look for high quality datasets...

**Comment by UnixJunkie** [comment]
@rbharath I am waiting for some feedback in order to push this one further (and create a corresponding PR).

**Comment by rbharath** [comment]
Yes, this one would be welcome too!

**Comment by rbharath** [comment]
Closing this old issue for cleanup
