### ISSUE TITLE
ValueError evaluating Atomic Convnet on test dataset

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1582]
DeepChem Version: 2.1.0
Platform: OS; python 3.5

I am trying to evaluate an atomic convolutional model that was trained on the random training dataset from 'http://deepchem.io.s3-website-us-west-1.amazonaws.com/featurized_datasets/acnn_core.tar.gz' using the test dataset.
I don't understand why I am getting the following error and was wondering if anyone could help me sort this out. I also get this error when I try to evaluate with the training dataset, but I can get around it by changing the batch size (not sure why).

**code that trained the model:**
frag1_num_atoms = 140 # for ligand atoms
frag2_num_atoms = 821 # for protein atoms
complex_num_atoms = 908 # in total
max_num_neighbors = 4
neighbor_cutoff = 4
batch_size = 12

from deepchem.models.tensorgraph.models import atomic_conv

atomic_convnet = atomic_conv.AtomicConvModel(
    batch_size=batch_size,
    frag1_num_atoms=frag1_num_atoms,
    frag2_num_atoms=frag2_num_atoms,
    complex_num_atoms=complex_num_atoms)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-961e8ec19685> in <module>
----> 1 test_scores = atomic_convnet.evaluate(test_dataset, [metric], transformers)

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/models.py in evaluate(self, dataset, metrics, transformers, per_task_metrics)
    168     evaluator = Evaluator(self, dataset, transformers)
    169     if not per_task_metrics:
--> 170       scores = evaluator.compute_model_performance(metrics)
    171       return scores
    172     else:

~/myenvs/testing/lib/python3.6/site-packages/deepchem/utils/evaluate.py in compute_model_performance(self, metrics, csv_out, stats_out, per_task_metrics)
     98     else:
     99       mode = metrics[0].mode
--> 100     y_pred = self.model.predict(self.dataset, self.output_transformers)
    101     if mode == "classification":
    102       y_pred_print = np.argmax(y_pred, -1)

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in predict(self, dataset, transformers, outputs)
    536     """
    537     generator = self.default_generator(dataset, predict=True, pad_batches=False)
--> 538     return self.predict_on_generator(generator, transformers, outputs)
    539 
    540   def predict_uncertainty(self, dataset, masks=50):

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in predict_on_generator(self, generator, transformers, outputs)
    469       y_pred: numpy ndarray of shape (n_samples, n_classes*n_tasks)
    470     """
--> 471     return self._predict(generator, transformers, outputs, False)
    472 
    473   def predict_on_batch(self, X, transformers=[], outputs=None):

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _predict(self, generator, transformers, outputs, uncertainty)
    429             break
    430         n_samples += 1
--> 431         feed_results = self._run_graph(tensors, feed_dict, uncertainty)
    432         if tf.executing_eagerly():
    433           feed_results = [f.numpy() for f in feed_results]

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _run_graph(self, outputs, feed_dict, training)
   1177     """
   1178     if not tf.executing_eagerly():
-> 1179       return self.session.run(outputs, feed_dict)
   1180 
   1181     def run_layers(layer, tensors):

~/myenvs/testing/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/myenvs/testing/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1130                              'which has shape %r' %
   1131                              (np_val.shape, subfeed_t.name,
-> 1132                               str(subfeed_t.get_shape())))
   1133           if not self.graph.is_feedable(subfeed_t):
   1134             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (3, 140, 3) for Tensor 'Feature_3/Placeholder:0', which has shape '(12, 140, 3)'

**Comment by VIGS25** [comment]
The error is happening because the `pad_batches` argument is set to False, when the `predict` method is called (Code from predict method below):

> https://github.com/deepchem/deepchem/blob/a5fa0439ab62d713b78a9ca0c71019817f25aec8/deepchem/models/tensorgraph/tensor_graph.py#L537

The predictions run fine for all batches except the final batch, since the placeholder is expecting 12 samples, but only gets 3 because those are the only ones left and `pad_batches` was set to False.

Three suggestions:
1. Remove the last 3 samples from your test set
2. Train using a `batch_size`: 3
3. Add a `predict` method to the `AtomicConvModel` definition (Use the definition from [here](https://github.com/deepchem/deepchem/blob/a5fa0439ab62d713b78a9ca0c71019817f25aec8/deepchem/models/tensorgraph/tensor_graph.py#L518)) ,and change `pad_batches` to True. However, this can affect some downstream evaluations and give you wrong results. (I would have to check this)

So maybe the first option is the simplest and best for now.

**Comment by 0ut0fcontrol** [comment]
You can slightly modify option 3, `return y_pred[:len(dataset)]`.
```python
  def predict(self, dataset, transformers=[], outputs=None):
    generator = self.default_generator(dataset, predict=True, pad_batches=True)
    y_pred = self.predict_on_generator(generator, transformers, outputs)
    return y_pred[:len(dataset)]
```

**Comment by VIGS25** [comment]
@0ut0fcontrol: Yup!
Just realised that. Thank you!

**Comment by fredrikszm** [comment]
I made tried two of the above suggested changes (removing the last three examples or changing the code to what was suggested by @0ut0fcontrol) and they both worked for my test dataset.

Now I am trying to use my model to predict on just one ligand-protein pair (as an example case) using predict_on_batches. I am getting the following error which is similar to the original problem:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-43-5303463ece76> in <module>
----> 1 atomic_convnet.predict_on_batch(feat_array)

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in predict_on_batch(self, X, transformers, outputs)
    489     # return self.predict_on_generator(generator, transformers, outputs)
    490     generator = self.default_generator(dataset, predict=True, pad_batches=True)
--> 491     y_pred = self.predict_on_generator(generator, transformers, outputs)
    492     return y_pred[:len(dataset)]
    493 

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in predict_on_generator(self, generator, transformers, outputs)
    469       y_pred: numpy ndarray of shape (n_samples, n_classes*n_tasks)
    470     """
--> 471     return self._predict(generator, transformers, outputs, False)
    472 
    473   def predict_on_batch(self, X, transformers=[], outputs=None):

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _predict(self, generator, transformers, outputs, uncertainty)
    417                   n_enqueued, final_sample))
    418         enqueue_thread.start()
--> 419       for feed_dict in self._create_feed_dicts(generator, uncertainty):
    420         if self.queue_installed:
    421           # Don't let this thread get ahead of the enqueue thread, since if

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _create_feed_dicts(self, generator, training)
   1153         yield {self._training_placeholder: train_value}
   1154     else:
-> 1155       for d in generator:
   1156         feed_dict = {}
   1157         for key, value in d.items():

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/atomic_conv.py in default_generator(self, dataset, epochs, predict, deterministic, pad_batches)
    299         frag1_X_b = np.zeros((batch_size, N_1, num_features))
    300         for i in range(batch_size):
--> 301           frag1_X_b[i] = F_b[i][0]
    302         orig_dict[self.frag1_X] = frag1_X_b
    303 

ValueError: could not broadcast input array from shape (70,3) into shape (140,3)

---------------------------------------------------------------------------

I first featurized a protein pdb file and ligand sdf file using the following featurizer:
**frag1_num_atoms = 70 # for ligand atoms**
**frag2_num_atoms = 24000 # for protein atoms**
**complex_num_atoms = 24070 # in total**
**max_num_neighbors = 4**
**neighbor_cutoff = 4**

**featurizer =** **dc.feat.atomic_coordinates.ComplexNeighborListFragmentAtomicCoordinates(frag1_num_atoms,** **frag2_num_atoms, complex_num_atoms, max_num_neighbors, neighbor_cutoff)**

which I used to featurize the files with:
**feat_array = np.asarray(atomic_featurizer._featurize_complex(ligand_filename, protein_filename))**

giving an array of shape (9,) which I changed to (1,9) before passing it as a parameter to predict_on_batch

Any suggestions on how to fix this?
