### ISSUE TITLE
joblib missing from pip modules

### ISSUE THREAD

**Issue by charlesreid1** [deepchem/deepchem#1585]
**Description:**

I installed deepchem from the master branch of this repo, from source, on a Mac, without GPU support, using the command:

```
bash scripts/install_deepchem_conda.sh deepchem
```

I then tried to import deepchem, but this failed due to a missing Python module `joblib`:

```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepchem as dc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/charles/codes/deepchem/deepchem/__init__.py", line 9, in <module>
    import deepchem.data
  File "/Users/charles/codes/deepchem/deepchem/data/__init__.py", line 9, in <module>
    from deepchem.data.datasets import pad_features
  File "/Users/charles/codes/deepchem/deepchem/data/datasets.py", line 13, in <module>
    from deepchem.utils.save import save_to_disk, save_metadata
  File "/Users/charles/codes/deepchem/deepchem/utils/save.py", line 9, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
>>>
```

I can run `pip install joblib` and joblib installs fine.

I am then able to import deepchem without the ModuleNotFoundError occurring.

I think you are missing joblib from the installation from source script.

**Comment by charlesreid1** [comment]
This was a problem with the conda environment, installing joblib did not actually fix the problem.

**Comment by yipy0005** [comment]
I'm also facing the same problem, so does that mean we can't run nosetests -a '!slow' -v deepchem --nologcapture till a fix is devised?

**Comment by rbharath** [comment]
@yipy0005 Could you provide more details on the problem that you're seeing? You should be able to run nosetests with a clean install

**Comment by yipy0005** [comment]
Hi Bharath,

It’s okay. I have managed to install using:
pip3 install joblib pandas sklearn tensorflow pillow deepchem
I tested the installation by running the python notebooks in the examples dir. :)

Yip Yew Mun (Dr) | Principal Scientist | Systemed Pte Ltd
School of Physical & Mathematical Sciences | Nanyang Technological University | Singapore 639798
Tel: (+65) 97967803 | Email: yipy0010@e.ntu.edu.sg| GMT+8h
