### ISSUE TITLE
Atomic CNN Model and Featurizer Parameters Conflict

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1589]
I have trained an ACNN using the atomic featurized pdbbind dataset using the following parameters:
**frag1_num_atoms = 140**
**frag2_num_atoms = 821**
**complex_num_atoms = 908**
**max_num_neighbors = 4**
**neighbor_cutoff = 4**
**batch_size = 12**

if I change these parameters at all, model.fit() will return an error because these parameters are made to correspond to the training dataset dimensions.

I am now trying to use this model to make predictions on new data. The conflict arises when I use the atomic featurizer to featurize the new data before running model.predict()

If I don't use the above parameters when defining the atomic featurizer, then model.predict() gives an error:

**featurizer parameters:**
frag1_num_atoms = 70
frag2_num_atoms = 24000
complex_num_atoms = 24070
max_num_neighbors = 4
neighbor_cutoff = 4

**error:**

ValueError                                Traceback (most recent call last)
<ipython-input-94-5303463ece76> in <module>
----> 1 atomic_convnet.predict_on_batch(feat_array)

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in predict_on_batch(self, X, transformers, outputs)
    489     # return self.predict_on_generator(generator, transformers, outputs)
    490     generator = self.default_generator(dataset, predict=True, pad_batches=True)
--> 491     y_pred = self.predict_on_generator(generator, transformers, outputs)
    492     return y_pred[:len(dataset)]
    493 

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in predict_on_generator(self, generator, transformers, outputs)
    469       y_pred: numpy ndarray of shape (n_samples, n_classes*n_tasks)
    470     """
--> 471     return self._predict(generator, transformers, outputs, False)
    472 
    473   def predict_on_batch(self, X, transformers=[], outputs=None):

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _predict(self, generator, transformers, outputs, uncertainty)
    417                   n_enqueued, final_sample))
    418         enqueue_thread.start()
--> 419       for feed_dict in self._create_feed_dicts(generator, uncertainty):
    420         if self.queue_installed:
    421           # Don't let this thread get ahead of the enqueue thread, since if

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _create_feed_dicts(self, generator, training)
   1153         yield {self._training_placeholder: train_value}
   1154     else:
-> 1155       for d in generator:
   1156         feed_dict = {}
   1157         for key, value in d.items():

~/myenvs/testing/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/atomic_conv.py in default_generator(self, dataset, epochs, predict, deterministic, pad_batches)
    299         frag1_X_b = np.zeros((batch_size, N_1, num_features))
    300         for i in range(batch_size):
--> 301           frag1_X_b[i] = F_b[i][0]
    302         orig_dict[self.frag1_X] = frag1_X_b
    303 

ValueError: could not broadcast input array from shape (70,3) into shape (140,3)

-------------------------------------------------------------------------------------

But when I use the same parameters I used for the model (above), I get the following warning when featurizing:
**WARNING:root:max_atoms was set too low. Some complexes too large and skipped**
and it returns an empty feature array.

This is the featurizer I am using:
**atomic_featurizer =** **dc.feat.atomic_coordinates.ComplexNeighborListFragmentAtomicCoordinates(frag1_num_atoms, frag2_num_atoms, complex_num_atoms, max_num_neighbors, neighbor_cutoff)**

The data I am trying to make predictions on right now is just one protein pdb file and ligand sdf file (using predict_on_batch). I need the functionality of being able to predict on just one protein-ligand pair and on datasets (of variable size).

Any suggestions on what I can do to fix this are really appreciated!

**Comment by VIGS25** [comment]
A couple of questions:
1. When you say atomic featurized pdbbind dataset, do you mean you used `ComplexNeighborListFragmentAtomicCoordinates` or the `AtomicConvFeaturizer`?

`ComplexNeighborListFragmentAtomicCoordinates` is suposed to prepare the pdbbind_dataset into a format where an `AtomicConvModel` can directly be used to call model.fit()

`AtomicConvFeaturizer` returns the co-crystal embeddings of a trained AtomicConvModel and use it for some tasks. There are a couple of problems with this method right now, not in working but the idea and hence I would recommend not to use it.

So your workflow would look like:
1. Featurize using `ComplexNeighborListFragmentAtomicCoordinates` --> (train, valid, test), transformers
2. Fit an `AtomicConvModel` to this featurized dataset --> model.fit(train)
3. Predict on test dataset --> model.predict(test)

2. Do you featurize the test-set using `AtomicConvFeaturizer` before running `model.predict()`?

**Comment by fredrikszm** [comment]
1 - I mean that I downloaded the pre-featurized atomic pdbbind dataset from the cloud, which I believe was featurized using ComplexNeighborListFragmentAtomicCoordinates:
dc.utils.download_url('http://deepchem.io.s3-website-us-west-1.amazonaws.com/featurized_datasets/acnn_core.tar.gz')

2- I don't featurize the test set because it comes pre-featurized since I get the dataset using the above download

For the new data I want to use the model to make predictions on, I featurize using ComplexNeighborListFragmentAtomicCoordinates, specifically:
--------------------------------------------------------------------------------------------
frag1_num_atoms = 70 # for ligand atoms
frag2_num_atoms = 24000 # for protein atoms
complex_num_atoms = 24070 # in total
max_num_neighbors = 4
neighbor_cutoff = 4

atomic_featurizer = dc.feat.atomic_coordinates.ComplexNeighborListFragmentAtomicCoordinates(frag1_num_atoms, frag2_num_atoms, complex_num_atoms, max_num_neighbors, neighbor_cutoff)

feat_array = np.asarray(atomic_featurizer._featurize_complex(ligand_filename, protein_filename))

--------------------------------------------------------------------------------------------

**Comment by VIGS25** [comment]
1. Okay, that clarifies things up

2. I see. 
Your featurization parameters using `ComplexNeighborListFragmentAtomicCoordinates` is different from the parameters used for building and training the network. Isn't the error bound to happen then?

**Comment by fredrikszm** [comment]
Yes, but the issue is that when I change the parameters to match the ones used to train the model, the featurizer returns an empty array and gives the following warning:
WARNING:root:max_atoms was set too low. Some complexes too large and skipped

**Comment by VIGS25** [comment]
That is unfortunately going to happen. The `ComplexNeighborListFragmentAtomicCoordinates` expects smaller complexes than `max_atoms` specified. What you can do is run the featurizer with the parameters you defined above on the original protein files, and retrain the model. (But this would cause the same cycle of pdbbind loading issues that you previously detailed)

Pdbbind runs on my machine without any errors. 
I'll try to upload the featurized version of PDBBIND dataset, with these parameters. Hopefully then you can retrain your model with those parameters, and run predictions for your files!

**Comment by fredrikszm** [comment]
When you say Pdbbind do you mean: 
pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(
    featurizer="atomic", split="random", subset="core", reload=False)

And yes, that would be awesome, thank you!

**Comment by VIGS25** [comment]
Yes, I mean the above.
If that works for you, feel free to featurize the dataset using `ComplexNeighborListFragmentAtomicCoordinates` and train the `AtomicConv` Model

**Comment by fredrikszm** [comment]
I have not been able to get that function to work for me (see most of my old issues) so I was curious how it works for you. Also how do you specify the parameters for the featurizer for that method, doesn't it just load in pre-featurized datasets depending on whether you specify "atomic", "grid", or other?

**Comment by fredrikszm** [comment]
Also may I ask why those specific numbers were chosen for featurizing the pre-featurized dataset? They seem a bit small and I'm curious as to why they are so specific?
frag1_num_atoms = 140
frag2_num_atoms = 821
complex_num_atoms = 908
max_num_neighbors = 4
neighbor_cutoff = 4
batch_size = 12

**Comment by fredrikszm** [comment]
Hi @VIGS25, I've been trying to run load_pdbbind with the parameters I want
(frag1_num_atoms = 70
frag2_num_atoms = 10000
complex_num_atoms = 10070
max_num_neighbors = 4
neighbor_cutoff = 4)

but it still is not working for me. Every time I run it I get **Exception: Particle coordinate is nan**
I tried skipping over the molecule files that were being featurized when this exception occurred, but it keeps happening no matter how many I end up removing.

At this point, I have no idea why I am getting this error. Would it still be possible for you to upload a featurized version of the pdbbind dataset with the above parameters?

**Comment by VIGS25** [comment]
Can you try with `load_binding_pocket=True`?

**Comment by VIGS25** [comment]
Anyway, I don't have access to uploading the featurized files to DeepChem's hosting service, so I added it to mine.
You can find it [here](https://polybox.ethz.ch/index.php/s/xv4oYu3NVuWH3NU).

Extract the zip file to whichever directory to want, and then run: 
```
save_dir = os.path.join(<wherever_you_saved>, full_protein-core-atomic-random)
tasks, dataset, transformers = dc.load_dataset_from_disk(save_dir)
```

I'm not sure why you keep getting the Particle coordinate is Nan exception, since I'm unable to reproduce it, and I just used the latest source version. 

If there are any issues with loading, let me know.

**Comment by fredrikszm** [comment]
Thank you so much for taking the time to upload the dataset for me. Can you change the parameters when you run the function to:

frag1_num_atoms = 70
frag2_num_atoms = 10000
complex_num_atoms = 10070
max_num_neighbors = 4
neighbor_cutoff = 4

?

My GPU memory runs out when I try to train the model on the dataset featurized with 24070 num atoms. Also, I tried it with load_binding_pocket=True and I get the following error when it tries to save the dataset: ValueError: not enough values to unpack (expected 4, got 3)

**Comment by VIGS25** [comment]
I don't know whats your wrong with the version you have, but it runs perfectly on mine.
What I would suggest with AtomicConvModel is to run the model on the binding pocket, since it trains much faster. 

The parameters for the binding_pocket setup are:
```
frag1_num_atoms = 70  # for ligand atoms
frag2_num_atoms = 1000
complex_num_atoms = 1070
max_num_neighbors = 4
neighbor_cutoff = 4
```

I will upload the featurized dataset in a while.

Can you post the whole traceback anyway?

**Comment by VIGS25** [comment]
You can find the link to featurized datasets, with load_binding_pocket set to True, [here](https://polybox.ethz.ch/index.php/s/ZlwO6HqIjrxSALE).

**Comment by fredrikszm** [comment]
This is the the error I get when I run load_pdbbind using load_binding_pocket = True
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)
<ipython-input-2-970f1cabe6bc> in <module>
      1 pdbbind_tasks, pdbbind_datasets, transformers, failures = dc.molnet.load_pdbbind(
----> 2     featurizer="atomic", split="random", subset="core", reload=False, load_binding_pocket=True)

ValueError: not enough values to unpack (expected 4, got 3)

-----------------------------------------------------------------------------------------------

**Comment by VIGS25** [comment]
Failures should not be returned.
It should be how it is below:

```
 pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(featurizer="atomic", 
         split="random", subset="core", reload=False, load_binding_pocket=True)
```

**Comment by fredrikszm** [comment]
Ahh I added that earlier to check something and forgot to change the method call. It works now that I changed that. I'm still really confused on this issue though, why does using load_binding_pocket=True allow the featurization to run smoothly, but when I don't use the binding pocket, it always gives the "particle is nan" exception?

**Comment by VIGS25** [comment]
I guess some of the molecule coordinates are messed up or corrupted in some fashion. Interestingly, I know of that error since a previous issue points to that, but I never get it when running on my local machine. With the binding pocket, you only load a certain section of the molecule, and a lesser chance of that being messed up.

The recommendation is to use the binding pockets if you use memory-intensive models like AtomicConv, otherwise the normal ones are okay.

**Comment by VIGS25** [comment]
Can you close this issue now?
Feel free to reopen if necessary.

**Comment by fredrikszm** [comment]
Yes, thank you for all your help!
