### ISSUE TITLE
Problem: (dpchm2.7) $ wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz 

### ISSUE THREAD

**Issue by dlbeveridge** [deepchem/deepchem#1593]
Trying out DLLS MNIST example p 34

 (dpchm2.7) $ wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
-bash: wget: command not found

Corresponding command in MAcos is curl -O

(dpchm2.7) $ curl -O  http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:06:01 --:--:--     0
curl: (52) Empty reply from server
(dpchm2.7) $

Any suggestions about this?

Thanks,

DLB

**Comment by VIGS25** [comment]
Don't think this is a DeepChem issue.
But the syntax should be:
`curl -o (small-o) <filename you want to save as> <url>`
