### ISSUE TITLE
ReduceMean raises assertion error in TensorGraph.build shape check

### ISSUE THREAD

**Issue by Alwin-Bucher** [deepchem/deepchem#1597]
**Description:**

- DeepChem Version: 2.2.1.dev49
- Platform: Ubuntu 16.04

I find the `ReduceMean` layer (and presumably also `ReduceMax` and `ReduceSum` layers) to raise an `AssertionError` when `TensorGraph.build` is called on a model containing these, if the `axis` keyword argument is anything other than `None`. 

```
from deepchem.models import TensorGraph
from deepchem.models.tensorgraph.layers import Feature, ReduceMean

class DummyModel(TensorGraph):
  def __init__(self, **kwargs):
    super(DummyModel, self).__init__(**kwargs)
    feature1 = Feature(shape=(None, 2))
    feature2 = Feature(shape=(None, 2))
    output = ReduceMean(in_layers=[feature1, feature2], axis=0])
    self.add_output(output)

model = DummyModel()
model.build()
```
produces the following error message:
```
 File ".../tensor_graph.py", line 764, in build
    layer.name, layer.shape, layer.out_tensor.get_shape().as_list())
AssertionError: ReduceMean_1: Expected shape [2] does not match actual shape [None, 2]
```
I believe this is due to the way the `Reduce*` layers calculate the `_shape` property
```
class ReduceMean(Layer):

  def __init__(self, in_layers=None, axis=None, **kwargs):
    if axis is not None and not isinstance(axis, Sequence):
      axis = [axis]
    self.axis = axis
    super(ReduceMean, self).__init__(in_layers, **kwargs)
    if axis is None:
      self._shape = tuple()
    else:
      try:
        parent_shape = self.in_layers[0].shape
        self._shape = [
            parent_shape[i] for i in range(len(parent_shape)) if i not in axis
        ]
      except:
        pass
```
which does not take into consideration the increase in rank of the tensor on which the `tf.reduce_*` methods are called due to the use of `tf.stack`, which increases the rank by one along the first dimension. I fixed this locally by replacing the relevant sections of code above with:
```
      try:
        parent_shape = [len(self.in_layers)] + self.in_layers[0].shape
        self._shape = [
            parent_shape[i] for i in range(len(parent_shape)) if i not in axis
        ]
      except:
        pass
```

**Comment by VIGS25** [comment]
Hi, 
If you look at the error, it says expected shape [2] (which is the correct one), and I would recommend not changing this section.

What should instead be done, in my view is turn the `tf.stack` function in `create_tensor` to `tf.concat`

**Comment by Alwin-Bucher** [comment]
Thank you for the swift reply. I am in fact using the ReduceMean layer to perform the kind of averaging that could not be accomplished with `tf.concat` (that which would as it stands require `axis=0`) , but I suppose I could just sum my layers and divide by their number. It does seem more intuitive for the `axis` keyword to refer to the dimensions of the original layers passed in.

**Comment by VIGS25** [comment]
What I wanted to say was, in the `create_tensor` definition for `ReduceMean` layer, `tf.stack` is replaced with `tf.concat`.

```
def create_tensor(self, in_layers=None, set_tensors=True, **kwargs):
    inputs = self._get_input_tensors(in_layers)
    if len(inputs) > 1:
      out_tensor = tf.concat(inputs, axis=0)
    else:
      out_tensor = inputs[0]

    out_tensor = tf.reduce_mean(out_tensor, axis=self.axis)
    if set_tensors:
      self.out_tensor = out_tensor
    return out_tensor
```

If I use this definition, your code (below) runs without any errors.
```
from deepchem.models import TensorGraph
from deepchem.models.tensorgraph.layers import Feature, ReduceMean

class DummyModel(TensorGraph):
  def __init__(self, **kwargs):
    super(DummyModel, self).__init__(**kwargs)
    feature1 = Feature(shape=(None, 2))
    feature2 = Feature(shape=(None, 2))
    output = ReduceMean(in_layers=[feature1, feature2], axis=0])
    self.add_output(output)

model = DummyModel()
model.build()
```

Let me know if the above doesnt work for you.

**Comment by Alwin-Bucher** [comment]
I agree. What I meant was that I am in fact creating multiple layers of the same shape and averaging their output tensors, such that the resulting shape is once again the shape of the original layers' output tensors (I.e. in this case `(None, 2)`). I was using `ReduceMean` for this, which worked with the modification I made to the way the `_shape` property was set, and is not possible when `tf.stack` is replaced with `tf.concat`. However, I can see how the intention of the `ReducedMean` layer is more in line with your proposition, and I can of course average my layers using the `Add` layer.

**Comment by VIGS25** [comment]
Ah I see what you mean now!
This is a valid point yes. I checked put `tf.reduce_mean` to see what their behavior is they give out (None, 2) as well. Expected shape should be modified yes!

@rbharath: What do you think?

**Comment by rbharath** [comment]
Sounds reasonable to me. @peastman what do you think?

**Comment by peastman** [comment]
I'm not really sure what behavior makes sense when there are multiple inputs.  In fact, I'm not sure it really even makes sense to allow it.  What should happen if the inputs are multiple tensors of incompatible shapes?  I'd be inclined to say ReduceMean should only accept a single input.  If you have multiple inputs, it should be up to you to combine them first in whatever way is appropriate for your problem (such as with a Stack or Concat layer).

**Comment by rbharath** [comment]
Closing this old issue for cleanup
