### ISSUE TITLE
rdkit dependency

### ISSUE THREAD

**Issue by agitter** [deepchem/deepchem#160]
I previously installed deepchem successfully, but today a fresh install had problems related to rdkit.  I installed rdkit as suggested
```
conda install -c omnia rdkit
```
but when I tried to `import rdkit.rdBase` I received the error
```
ImportError: libboost_python.so.1.59.0: cannot open shared object file: No such file or directory
```

Seemingly rdkit was looking for Boost version 1.59.0 but had installed Boost version 1.60.0.  I was able to
```
conda install -c omnia boost=1.59.0
```
as a workaround, but anyone following the standard installation instructions may have problems.

**Comment by hainm** [comment]
seems that deepchem needs to update those from .travis

```bash
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels http://conda.binstar.org/omnia
- conda update -q conda
- conda info -a
- conda install pandas
- conda install -c omnia rdkit
- conda install -c omnia boost=1.59.0
- conda install -c omnia openbabel
- conda install joblib
- conda install -c omnia theano
- conda install -c omnia keras
- conda install seaborn
- conda install six
- conda install dill
- conda install runipy
- conda install ipyparallel
- pip install runipy
- pip install nglview
- conda install -c omnia mdtraj 
- python setup.py install
- conda install -c https://conda.anaconda.org/jjhelmus tensorflow
```

**Comment by rbharath** [comment]
@agitter Thanks for pointing this out! We're currently pushing towards a next release version of deepchem, so some of the install docs have fallen out of date. I'll do a pass once the next release is ready (~ couple weeks) to clean up the install directions and the fix the issue with the boost version.

**Comment by rbharath** [comment]
The installation directions on the main github page have been updated. Going to go ahead and close this issue.
