### ISSUE TITLE
How can I get the kinase data set?

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1601]
I'm focusing on the study of kinase orientation. I see kinase-related code in deepchem, but I don't have data. How do I get the `KINASE_training_disguised_combined_full.csv.gz` dataset and instructions?

**Comment by VIGS25** [comment]
The `kinase_datasets.py` file at `deepchem/molnet/load_function` contains the required URLs for the files. 

You can download it from there.
