### ISSUE TITLE
Run python setup.py install everytime

### ISSUE THREAD

**Issue by VIGS25** [deepchem/deepchem#1604]
When I make changes in the source code somewhere, should I run `python setup.py install` everytime to sync the changes with the code under the conda environment (located at `env_name/lib/python3.5/site-packages/deepchem/`

The issue I mentioned with the KerasLayer was fixed when I used the above command.

**Comment by peastman** [comment]
A much easier way is to instead use `python setup.py develop`.  That way instead of copying the source files into your environment, it just installs a reference to your working source tree.  Then you don't have to reinstall after making changes.

**Comment by VIGS25** [comment]
Thanks!
