### ISSUE TITLE
Number of Parameters - ChemNet Transfer Learning

### ISSUE THREAD

**Issue by VIGS25** [deepchem/deepchem#1611]
![image](https://user-images.githubusercontent.com/32259379/58764572-08f75d00-8569-11e9-8bf0-b7798f55832b.png)

In the image above, the number of parameters are same in the `T3_F16_std` and `T3_F16_eng` modes are the same, but the number of input channels are different. 
`std` is the standard mode that uses a gray-scale encoding, with a single channel while `eng` is a 4 channel input. 

It doesn't make sense that the number of parameters are same when the starting image representations are different. Any ideas as to how this may be happening?

**Comment by rbharath** [comment]
@VIGS25 Where is the above image pulled from? I'll take a look

**Comment by VIGS25** [comment]
@rbharath: https://arxiv.org/pdf/1712.02734.pdf.
This is the ChemNet paper, and the figure is taken from page 5.

The input representation details are taken from https://arxiv.org/pdf/1710.02238.pdf

Thanks for taking a look at it!

**Comment by VIGS25** [comment]
Issue addressed, hence closing this.
