### ISSUE TITLE
Updating set of initialized variables under restore 

### ISSUE THREAD

**Issue by VIGS25** [deepchem/deepchem#1613]
https://github.com/deepchem/deepchem/blob/87410a5e475a043bf68e4f16e57ba8305356153a/deepchem/models/keras_model.py#L326

This is just more of a doubt I have about the ordering of operations, and about where to place restore. 

With the current setup, if `restore` is set to True in `fit_generator()`, the variable values are restored but the set of initialized variables is not updated. The problem is that `_create_training_ops` follows after `restore()`. `_create_training_ops` initializes all the variables again, and hence the restore functionality is overridden by the `session.run(variables_intializer)`. 

I also checked TensorGraph (https://github.com/deepchem/deepchem/blob/87410a5e475a043bf68e4f16e57ba8305356153a/deepchem/models/tensorgraph/tensor_graph.py#L217), and there `restore()` is invoked after everything has been initialized.

**Comment by peastman** [comment]
Good point.  I'll fix that.

**Comment by peastman** [comment]
Let's leave this open until the fix is in.

**Comment by peastman** [comment]
This is fixed by #1615.
