### ISSUE TITLE
Tensorflow dropout unrecognized keyword argument 

### ISSUE THREAD

**Issue by jayliu99** [deepchem/deepchem#1616]
When I try to run the train a multitask regressor on the pdbbind dataset, I receive the following error. I'm running tensorflow vs. 1.13.1.

The model I'm calling:
```
model = dc.models.MultitaskRegressor(
len(pdbbind_tasks),
n_features,
logdir=model_dir,
layer_sizes=[2000, 1000],
dropouts=[.25],
learning_rate=0.0003,
weight_init_stddevs=[.1],
batch_size=50)
```

The error:
```
  File "binding_pocket_tf.py", line 46, in <module>
    batch_size=50)
  File "/home/jliu99/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/fcnet.py", line 237, in __init__
    layer = SwitchedDropout(rate=dropout)([layer, dropout_switch])
  File "/home/jliu99/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/jliu99/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/layers.py", line 525, in call
    return tf.nn.dropout(inputs[0], rate=rate)
TypeError: dropout() got an unexpected keyword argument 'rate'
```

DeepChem Version: 2.2.1.dev74
- Platform: Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-50-generic x86_64)

**Comment by jayliu99** [comment]
Just a note -- this error is appearing when I run the prewritten scripts, such as pdbbind_tf.py, as well.

**Comment by peastman** [comment]
Are you sure you're really using TensorFlow 1.13?  `rate` is a valid argument to that function in 1.13 but not in earlier versions.  See https://www.tensorflow.org/api_docs/python/tf/nn/dropout.

**Comment by rbharath** [comment]
I'm going to close this old issue since it looks like a TensorFlow version issue. Please re-open if you're still facing issues!
