### ISSUE TITLE
Fail during nosetests

### ISSUE THREAD

**Issue by bmooers** [deepchem/deepchem#1622]
**Description:**

commit 4e382ee832aa79c7cda9c2844c86dee2d5e5895a
- DeepChem Version: 2.2.1
- Platform: Mac OS X Mojave

Deleted anaconda3 and reinstalled.

Created conda env named dc21 with python3.5

conda create --name dc221 python=3.5

conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.1.0

This installs python2.7 and deepchem 2.1.0
This is not what I want but it gets a number of packages including the tricky rdkit installed.

conda deactivate 

git clone https://github.com/deepchem/deepchem.git
cd deepchem
bash scripts/install_deepchem_conda.sh dc21

[Errno 1] Operation not permitted: '/Users/blaine/anaconda3/python.app/Contents/PkgInfo' -> '/Users/blaine/anaconda3/python.app/Contents/PkgInfo.c~'
Permissions on '/Users/blaine/anaconda3/python.app/Contents/PkgInfo' seems ok.

conda activate dc21
python setup.py install

python 
(fires up as 3.5.6)
import deepchem as dc
print(dc.__version__)
2.1.1 # really 2.2.1 according to version on the egg file.
exit

I can import deepchem as dc

but the load_pdbbind() fails to find the dataset

dbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(split='random', featurizer='grid', subset='core')

Dataset does not exist at /var/folders/mv/1w6nby494g5b3vjf661ktyfr0000gn/T/from-pdbbind/full_protein-core-grid-random. Reconstructing...

Raw dataset:
/var/folders/mv/1w6nby494g5b3vjf661ktyfr0000gn/T/pdbbind/v2015

Featurized and splitted dataset:
/var/folders/mv/1w6nby494g5b3vjf661ktyfr0000gn/T/from-pdbbind/full_protein-core-grid-random
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blaine/deepchem/deepchem/molnet/load_function/pdbbind_datasets.py", line 236, in load_pdbbind
    with open(index_labels_file, "r") as g:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/mv/1w6nby494g5b3vjf661ktyfr0000gn/T/pdbbind/v2015/INDEX_core_data.2013'

I ran nose:

nosetests -a '!slow' -v deepchem --nologcapture
.
.
.
Tests that overlapping boxes are merged. ... ok
Tests that pose-score works. ... ok
Tests that scores are generated ... libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
These lines were repeated indefinitely.

**Comment by rbharath** [comment]
Hmm, this looks like an error on RDKit on Mac. Has anyone seen these failures on non Mac machines? I'm trying to understand if it's a failure that's Mac specific or a broader issue

**Comment by nd-02110114** [comment]
This issue is outdated, so I closed.
