### ISSUE TITLE
How to get the feature matrix from the object created by ConvMolFeaturizer?

### ISSUE THREAD

**Issue by soumyosen** [deepchem/deepchem#1631]
Hi,
I am new in deepchem and very interested to use deepchem featurizer. After getting the featurizer object, I would like to extract the features as a matrix or a dataframe. How can I do that?

` import deepchem as dc
from rdkit import Chem
import pandas as pd

smile = 'C[N+](C)(C)CCOC(N)=O'
molecules = []
molecules.append(Chem.MolFromSmiles(smile))
featurizer = dc.feat.graph_features.ConvMolFeaturizer()
mol_object = featurizer.featurize(mols=molecules)
`

**Comment by VIGS25** [comment]
You can get the features of all atoms by using `mol_object[0].get_atom_features()`. 
Also there seems to be a parsing error in your SMILES string.

**Comment by soumyosen** [comment]
Thank you very much.

**Comment by VIGS25** [comment]
Can you close this issue? Feel free to reopen if necessary.
