### ISSUE TITLE
Training seq2seq model is very slow

### ISSUE THREAD

**Issue by zas97** [deepchem/deepchem#1634]
- DeepChem Version: 2.1.1
- Tensorflow Version: 1.13.1
- Plataform: Ubuntu 16.04 
- GPU : GeForce GT 710, 732 mb of memory

The seq2seq model trains very slowly, I'm running the notebook example from https://deepchem.io/docs/notebooks/seqtoseq_fingerprint.html with the generate_sequences replaced by the following code in order to have a progress bar:

```
from random import shuffle
from tqdm import trange


def generate_sequences(epochs):
  for i in range(epochs):
    shuffle(train_smiles)
    for it in trange(len(train_smiles)):
      yield (train_smiles[it], train_smiles[it])

model.fit_sequences(generate_sequences(50))
```
It takes around 20 minutes per epoch to train.
I wonder if this is normal behaviour seeing that in the notebook example (https://deepchem.io/docs/notebooks/seqtoseq_fingerprint.html) it took only 10 minutes to train 40 epochs.

**Comment by peastman** [comment]
> in the notebook example (https://deepchem.io/docs/notebooks/seqtoseq_fingerprint.html) it took only 10 minutes to train 40 epochs.

The output in that notebook reports that it took 5619 seconds to train 40 epochs.  That's over an hour and half.

Also, you're using a very inexpensive low end GPU.  That's going to make things a lot slower.  Take a look at the benchmarks at https://benchmarks.ul.com/hardware/gpu/NVIDIA+GeForce+GT+710+review to get a sense of how the performance compares to more powerful GPUs.
