### ISSUE TITLE
Unable to change the number of atom features in GraphConvModel

### ISSUE THREAD

**Issue by sanjaradylov** [deepchem/deepchem#1639]
I am using Deepchem to solve a multitask regression problem. Here is my setup:
- DeepChem Version: 2.1.0
- Platform: Linux
- Python Version: 3.5.6
- Environment: Anaconda

Here are the solution steps:
```
dc.feat.ConvMolFeaturizer -> dc.data.CSVLoader -> dc.models.GraphConvModel
```
I want to tune some hyperparameters of the ```GraphConvModel``` regressor. WIth the default
parameters, everything works well. But changing  ```number_atom_features``` from the
default 75 to, say, 50 gives the following error:
```
File "miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 153, in fit
    max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
  File "miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 257, in fit_generator
    fetched_values = self.session.run(fetches, feed_dict=feed_dict)
  File "miniconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "miniconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1608, 75) for Tensor 'Feature_13/Placeholder:0', which has shape '(?, 50)'
```

P.S. I was unable to fix the problem but I noticed (probably) an ambiguous line of code in the
implementation of ```ConvMolFeaturizer``` in deepchem.feat.graph_features.py:
```
class ConvMolFeaturizer(Featurizer):
  ...
  def feature_length(self):
    return 75 + len(self.atom_properties)
```

**Comment by VIGS25** [comment]
The way the code is strucutured now, you can only specify a value of 75 or more for `number_atom_features`. 
When you call `ConvMolFeaturizer`, you can specify an optional list, `atom_properties` that contains some other properties different from those used in `atom_features`. (https://github.com/deepchem/deepchem/blob/94809d39b5cee0c1ba178a1936dbf9a95b5eaad7/deepchem/feat/graph_features.py#L122). 
`number_atom_features` just accounts for the original 75 and that.

**Comment by rbharath** [comment]
Going to close this old issue. Feel free to re-open if you have more questions!
