### ISSUE TITLE
Lack of functional deepchem tests

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#164]
While debugging #163, it's become clear that the `deepchem` test suite is lacking. While current tests check that various model construction and evaluation operations run smoothly, none of them actually test that non-trivial models are learned.

It should be possible to construct simple datasets and verify that `deepchem` can build (multitask) classifier and regressors that are capable of learning simple functions on these models. These tests will prevent subtle issues with broken metrics like those in #163.

**Comment by rbharath** [comment]
Added some basic single-task models in #149. Need to follow up with some tests for unbalanced datasets, and for multitask datasets if possible.

**Comment by rbharath** [comment]
Some multitask overfit tests added in #178

**Comment by rbharath** [comment]
And some tests for skewed datasets in #175. The major oversight left is that all tests have been added for overfit only, and not for testing generalizability. I think some tests using `sklearn.datasets` to verify that  models learn generalizable models. These tests could be used to solve the bug raised in #180.

**Comment by Thatfreesky** [comment]
![2016-05-14 9 23 30](https://cloud.githubusercontent.com/assets/15063337/15265466/cf5d51b0-19b6-11e6-8c8d-b72cc5479a0b.png)

I build my environment for multitask network with your guide about deepchem, But I can not run the notebook with such problem.I do not know what the "/Users/travis/anaconda/envs/_build_placehold_placehold_placehold_placehold_place/lib/libopenbabel.4.dylib" mean. For in my computer have no User named travis

**Comment by rbharath** [comment]
@Thatfreesky It seems like you don't have openbabel installed. Could you open a new issue describing your issues in depth if you want help? This thread is reserved for discussion of deepchem tests.

**Comment by Thatfreesky** [comment]
Thanks for your answer.

At 2016-05-15 02:43:58, "Bharath Ramsundar" <notifications@github.com> wrote:


@Thatfreesky It seems like you don't have openbabel installed. Could you open a new issue describing your issues in depth if you want help? This thread is reserved for discussion of deepchem tests.

**Comment by rbharath** [comment]
Going to close this for now, since I think the functional tests situation is much better than it used to be.
