### ISSUE TITLE
Upgrade to TF 1.14

### ISSUE THREAD

**Issue by VIGS25** [deepchem/deepchem#1644]
The developers at TensorFlow addressed #1642, saying that this issue has been fixed in TF 1.14, and indeed it has been.

After upgrading to TF 1.14 on a local branch and running tests - most tests passed. The ones which were failing have been fixed except for one, which tries to fit a GAN with multiple generators and discriminators.

I isolated the reason for the failure, and this is a Keras issue and not a DeepChem one.

TF 1.13.1
https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/keras/engine/network.py#L960

TF 1.14
https://github.com/tensorflow/tensorflow/blob/a5120db4d6917f943176ef3c5bb938064604c761/tensorflow/python/keras/engine/network.py#L849

If you see, there's an extra line `depth_keys = depth_keys[1:]` which was not there in TF 1.13.1
This is preventing some tensors from being computed and hence throwing up an issue with multiple generator-discriminator GAN.

If we should upgrade to TF 1.14, then for now, the GAN test can be marked with `attr('slow')`.

**Comment by peastman** [comment]
I don't think this looks like a TensorFlow bug.  It's an intentional change in behavior.  So we need to understand what the change is, why they made it, and what assumptions it's based on.  Then we need to make the appropriate changes to our code to work correctly with the new behavior.

Possibly we'll need to check the TF version at runtime and use a different behavior depending on whether the version is <1.14.  Hopefully that won't be necessary, but we can do it if needed.

**Comment by VIGS25** [comment]
The comment in the line of change says, "Ignoring input layers while building the graph". 

L139-144 in  `dc.models.tensorgraph.models.gan` that are getting affected by this change and the tensors corresponding to them are not computed.
 
https://github.com/deepchem/deepchem/blob/94809d39b5cee0c1ba178a1936dbf9a95b5eaad7/deepchem/models/tensorgraph/models/gan.py#L139

How does one go about generally trying to fix these things?

**Comment by peastman** [comment]
I'm looking into it now.  How did you determine that particular line is responsible?

**Comment by VIGS25** [comment]
The Lambda layer corresponding to L153 was not getting computed, which was the error thrown. It takes in two layer outputs - `stacked_gen_loss` & `weight_products`. 

I track the tensors that are computed while the graph is built. `stacked_gen_loss` is computed initially, `weight_products` is missing, probably because of the change in line of code between the versions.

**Comment by peastman** [comment]
Ok, this is pretty clearly a bug in Keras.  They made the incorrect assumption that the deepest nodes in the model would always be the inputs.  I've created a simple test case demonstrating the problem, so I'll try filing a bug report with them.

**Comment by VIGS25** [comment]
Thanks!

**Comment by peastman** [comment]
Here's the bug report: https://github.com/tensorflow/tensorflow/issues/31174

**Comment by peastman** [comment]
Ok, *hopefully* my changes in #1662 have fully addressed the problems.  Want to try again?

**Comment by VIGS25** [comment]
The tests ran locally now, have pushed the changes to the corresponding PR (#1645). Waiting for Travis build. 
Can you cancel the penultimate Travis build in that? - The final one running should be sufficient.

**Comment by peastman** [comment]
Closing now that #1645 has been merged.
