### ISSUE TITLE
Imputation of missing labels in tasks

### ISSUE THREAD

**Issue by sanjaradylov** [deepchem/deepchem#1655]
There are several issues discussing the influence of samples with missing labels. As far as I can understand from the discussions, an overall technique is to assign the corresponding
weights to zero so that such samples won't affect learning. But does it mean that we simply
ignore a whole sample if at least one task label among multiple tasks is missing? If so, I
believe this is a notable problem for low data analysis, and I wonder if there are any solutions
considered (taking into account the correlation between tasks, semi-supervised learning, etc.).
If such solutions exist and are theoretically or empirically valid, do they consider regression
tasks?

**Comment by peastman** [comment]
This is why DeepChem uses a 2D weight matrix of shape (samples, tasks).  That lets you mask out just the tasks that are missing for each sample.  You can also use BalancingTransformer to adjust the weights for the remaining tasks so the total weight of positive and negative samples is equal on each task.

In contrast, some frameworks (like Keras) only allow a single weight for each sample.  That makes them unsuitable for multitask models.

**Comment by rbharath** [comment]
I'm going to go ahead and close this old issue. Feel free to re-open if you still have questions!
