### ISSUE TITLE
Load Predict Print

### ISSUE THREAD

**Issue by biswasakash95** [deepchem/deepchem#1659]
Hi, I am new into this area and I am trying to get familiar with the ADME example by @patrickhop 

I am able to execute the code and it went through successfully.
From the datasets I wish to also load the id of the data set, and I wish to save few things into a .csv file such as: **Mol_id of the trained dataset with values and the respective predicted data**.
How do I do it?
I tried the following code: 
**predicted_train=model.predict(train)
true_train=train.y
print('Predicted shape of Train:',predicted_train.shape)
print('True shape of Train:',true_train.shape)**
which gives me the trained shape perfectly, I can also use:
print(predicted_train) to print the values but I am not able to figure out which predicted values corresponds to which mol_id.

Thanks in advance

**Comment by rbharath** [comment]
Sorry for the slow response here! This slipped through my inbox. The order in `print(predicted_train)` will match the order in `train`. That is, the 5-th entry (for example) will be the same in both.

I'd recommend working through our tutorial series to learn the basic mechanics of DeepChem if you'd like to go deeper :). If you're still having issues here, please feel free to re-open!
