### ISSUE TITLE
Update examples for 2.3

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1667]
I'm reviewing the examples so we can get all of them working correctly for 2.3.  So far I've just gone through the notebooks.  Of those, there are a fair number that need changes.

First of all, the following notebooks are based around directly building TensorGraph models, so they'll need to be rewritten around KerasModel instead:

Conditional_GAN
graph_convolutional_networks_for_tox21
graph_convolutional_networks_for_tox21_on_colab
mnist
TensorGraph_Mechanics

Since TensorGraph_Mechanics is just illustrating particular features of TensorGraph, it probably doesn't make sense to convert it.  Possibly we want to just delete it.  Also, Conditional_GAN predates the GAN class, so it implements everything from scratch.  Today we could do the same thing much more simply with the GAN class, and we already have another notebook that shows how to do that.  So possibly we want to just delete that one too.

The Estimators notebook doesn't work any more because we aren't supporting Estimators in KerasModel.  Possibly we should just delete this notebook, or perhaps there are still some parts of it that should be preserved in a different form.

Two notebooks throw exceptions for reasons that I don't understand: dataset_preparation and Explaining_Tox21.  I don't know what's going on with those, but they'll need debugging.

I can get protein_ligand_complex_notebook to run by commenting out one unused import.  But that notebook has a lot of commented out code in it.  Much of it seems to be based around the deepchem.utils.visualization module that doesn't exist any more.  What do we want to do with it?

A few other notebooks need only minor changes, which I'll make.

**Comment by peastman** [comment]
We need to decide what to do with `n_evals`.  I suggest just removing that option.  The reasons are that 1) I can't see that it serves any useful purpose, 2) other models don't have that option, and 3) it didn't work correctly in past versions anyway.

**Comment by rbharath** [comment]
I think I'm on-board with removing `n_evals`

**Comment by peastman** [comment]
This was fixed by #1671.
