### ISSUE TITLE
Preparing a Dataset for Model Prediction

### ISSUE THREAD

**Issue by hl2500** [deepchem/deepchem#1673]
Hello, I'm working on the predictive model in Chapter 11, but could not find the rd_filters.py and associated data files through the link (https://github.com/deepchem/DeepLearningLifeSciences) suggested in the book. Does anyone have idea where I can find them? Thank you!

**Comment by peastman** [comment]
The examples from chapter 11 are now in the repository.  Sorry they got missed!
