### ISSUE TITLE
A question about deepchem2.2 GPU version

### ISSUE THREAD

**Issue by hl2500** [deepchem/deepchem#1674]
Hello, 
I just installed deepchem on a linux system by using: 
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.2.0
In this case, are the deepchem tasks performing on GPUs or still on CPUs?
Thank you!

**Comment by peastman** [comment]
That depends what version of TensorFlow you installed.  Is the package called `tensorflow` or `tensorflow-gpu`?  You can check with `conda list`.

**Comment by hl2500** [comment]
It's called tensorflow. If I want to have the gpu version, what can I do from here? Or should I change the installation command to deepchem-gpu=2.2.0? Thank you!

**Comment by peastman** [comment]
Yes, that should do it.

@rbharath should the installation instructions be updated to clarify this?

**Comment by rbharath** [comment]
Yes, we should definitely update the installation directions to clarify. I'll mark this contributions welcome

**Comment by rbharath** [comment]
Implemented by #1682
