### ISSUE TITLE
Support residual blocks

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1681]
Building models out of residual blocks is now a common practice, since they produce better results in many applications.  Classes like MultitaskRegressor, MultitaskClassifier, GraphConvModel, etc. could easily be modified to use residual blocks in place of simple dense or convolutional layers.  We should consider adding an option to do that.

**Comment by rbharath** [comment]
This seems really useful!

**Comment by patrickhop** [comment]
I tried residual blocks on graphconvs a few times. Never had any luck.

**Comment by peastman** [comment]
I'm experimenting with it on MultitaskClassifier right now.  On my very simple tests so far, it works about as well as simple Dense layers.  But I haven't tried anything really challenging yet.  I'm also still figuring out how to deal with various subtleties.  For example, you can only use a residual block when two successive layers have the same width.  So depending on the layer widths, it may actually be a mix of residual and ordinary layers.  And then, pre-activation is supposed to work better than post-activation for residual blocks, but I need to make sure that gets handled correctly when switching back and forth between types of layers.

**Comment by patrickhop** [comment]
yeah, there are 3 cases to consider here:

(1) next layer is wider
=> pad or upsample using convs

(2) next layer is the same size
=> proceed with residual connection

(3) next layer is thinner
=> downsample using conv

**Comment by peastman** [comment]
Exactly.  Or more simply: if it's the same size, use a residual block.  Otherwise, use an ordinary dense layer.

The implementation in #1686 seems to work pretty well.  I wrote some simple tests that tried to overfit a small dataset.  With `residual=False` it started failing when the number of layers got beyond about 10, but with `residual=True` it had no problem with 30 layers.

**Comment by rbharath** [comment]
Closing this issue since implemented in #1686
