### ISSUE TITLE
fit_generator callbacks

### ISSUE THREAD

**Issue by oguitart** [deepchem/deepchem#1684]
Hello,

I'm creating a generator to use it in the fit generator. However, I would like to get feedback on batch or each epoch about the loss. Since deepchem models do not seem to provide this feedback, I have created a callback to output this information on each batch. But the fit_generator does not seem to accept callbacks. Is that right? How am I supposed to output the desired information without callbacks?
Thanks,

oriol

**Comment by peastman** [comment]
What model are you using?  Anything based on KerasModel lets you pass callbacks to `fit_generator()`.

**Comment by oguitart** [comment]
We are using a TensorGraph model.
Thanks,

oriol

**Comment by peastman** [comment]
TensorGraph doesn't support callbacks.  DeepChem 2.3 (hopefully getting released any day now) moves to Keras as the preferred modelling API, and KerasModel (the successor to TensorGraph) does support callbacks.

**Comment by oguitart** [comment]
Ok, that's very good. New deepChem release will also use an update version of tensorflow? Will you update the tutorials to use the KerasModel instead of TensorGraph?

**Comment by peastman** [comment]
Yes.  If you look at the versions in the repository they've already been updated.

**Comment by peastman** [comment]
The current release is 2.2 (https://github.com/deepchem/deepchem/releases/tag/2.2.0).  2.3 will be released "any day now" in the sense that the code in github is final and we're just waiting on @rbharath to build the conda and pip installers.

Here are a couple of tutorials that demonstrate creating models:

https://github.com/deepchem/deepchem/blob/master/examples/tutorials/mnist.ipynb
https://github.com/deepchem/deepchem/blob/master/examples/tutorials/graph_convolutional_networks_for_tox21.ipynb

**Comment by oguitart** [comment]
Great! Thank you very much.

**Comment by oguitart** [comment]
Sorry to repoen the issue but I have installed version 2.2.0 and I tried to follow the proposed notebook tutorials and I get the following error:

`from deepchem.models.layers import GraphConv, GraphPool, GraphGather
ImportError                               Traceback (most recent call last)
<ipython-input-1-37e7473d01ef> in <module>()
----> 1 from deepchem.models.layers import GraphConv, GraphPool, GraphGather

ImportError: No module named layers`


Are the notebooks written to work on another DeepChem version?

**Comment by peastman** [comment]
That's because those tutorials are for 2.3, not 2.2.

**Comment by oguitart** [comment]
Hi,

Do you have an estimation about when the 2.3 release will be available?
Thanks,

oriol

**Comment by rbharath** [comment]
Hopefully quite soon. I'm working on the release notes for 2.3 now

**Comment by oguitart** [comment]
Hi,

I have seen the 2.3.0 is now available in the github page. But when I try to install it through conda I get this:

PackagesNotFoundError: The following packages are not available from current channels:

  - deepchem-gpu=2.3.0


Is that normal? Could you tell me when it should be available?
Thanks,

oriol

**Comment by peastman** [comment]
We're working on it!  Hopefully we'll have the conda packages up soon.

**Comment by rbharath** [comment]
The conda packages for 2.3 are now up. Going to close this issue.
