### ISSUE TITLE
GPU usage for model fitting

### ISSUE THREAD

**Issue by JanJorisDevogelaer** [deepchem/deepchem#1685]
System:
- DeepChem Version: 2.3.0 (built from source with GPU support)
- Platform: Linux Fedora 30, CUDA 10.0

Kind of new to deep learning and TensorFlow in general and I've been having some trouble running Deepchem on the GPU. After installing the latest NVIDIA drivers (430.50) and (via a painful way) CUDA 10.0 on my OS, I managed to get TensorFlow (tensorflow-gpu 1.14.0) to open the correct dynamic libraries and recognize my GPU as a 'TensorFlow device'. When I then run the graph_convolutional_networks_for_tox21 notebook and fit the ```GraphConvModel```, the memory of my GPU is filled, but computations still appear to take place on all cores of my CPU (no increase in GPU activity). Am I missing something here? All help is welcome!

P.S. : Running some testing TensorFlow testing code within the same conda environment using matrix multiplications does allow computation of the GPU .

**Comment by JanJorisDevogelaer** [comment]
Note:

When running mnist.ipynb and adding the following two lines at the start of the notebook

`import os`
`os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]='true'`

and 
`config = tf.ConfigProto()`
`config.gpu_options.per_process_gpu_memory_fraction = 0.9`
`tf.keras.backend.set_session(tf.Session(config=config));`

after the `tf.keras.layers` imports, the model is fitted using the GPUs resources.

However, adding the same lines of code to the graph_convolutional_networks_for_tox21 notebook (where again a `KerasModel` is fitted)  does not appear to result faster fitting times, and it seems that GPU usage is quite limited. 
Is the `GraphConvModel` on its own just much slower? Am I supposed to see a remarkable increase in fitting times compared to using only the CPU?

Many thanks,
Jan-Joris

**Comment by peastman** [comment]
The difference in performance between CPU and GPU can vary quite a lot between models.  This particular example trains a fairly small model on a small dataset.  That won't produce enough work to keep a powerful GPU busy, so you won't see that much difference.  But in other cases, it can make a huge difference with the GPU being 10-100x faster than the CPU.

**Comment by rbharath** [comment]
I'm going to close this old issue. Please feel free to re-open if you're still facing issues!
