### ISSUE TITLE
A question about model training

### ISSUE THREAD

**Issue by hl2500** [deepchem/deepchem#1687]
Hello, I was training a model by using 10 folds of cross validation and didn't specify the number of epochs for each training. In this case, does it mean I have trained the model for 10 epochs in total? Thank you!

**Comment by hl2500** [comment]
I think if I don't initialize the model between each training, then it's more likely trained 10 times and the cross validation is not performed properly. However, if I initialize the model every time, it will be trained only one epoch at the end. Is this right? Thank you!

**Comment by peastman** [comment]
Can you post your code?  Any of the above is possible, depending on exactly what your code is doing.

**Comment by hl2500** [comment]
I was just practicing the code from charpter 11 of the book, the code is as following:
```
for i in range(0, cv_folds):
    model = generate_graph_conv_model()
    res = splitter.train_valid_test_split(dataset)
    train_dataset, valid_dataset, test_dataset = res
    model.fit(train_dataset)
    train_scores = model.evaluate(train_dataset, metrics, transformers)
    training_score_list.append(train_scores['mean-matthews_corrcoef'])
    validation_scores = model.evaluate(valid_dataset, metrics, transformers)
    validation_score_list.append(validation_scores['mean-matthews_corrcoef'])
print(training_score_list)
print(validation_score_list)
```
I guess the model will end up being trained for roughly 1 epoch, right? Because the model was regenerated every time.

**Comment by peastman** [comment]
The default value for the `nb_epoch` argument to `fit()` is 10.  So each time you call it, you'll get 10 epochs of training.

**Comment by hl2500** [comment]
Okay, thanks! So after all the iterations, I will get a model trained for 10 epochs in total, right? If I want to train the model on the whole dataset, do I need to initialize the model again? Thank you so much!

**Comment by peastman** [comment]
Every time through the loop it creates a new model:

```python
model = generate_graph_conv_model()
```

It then trains the model for 10 epochs and evaluates it.  So many total training steps get run, but only 10 on each model.

**Comment by hl2500** [comment]
Thanks!
