### ISSUE TITLE
load_chembl25 is not available in a subfolder run

### ISSUE THREAD

**Issue by altayg** [deepchem/deepchem#1688]
**Description:**

I am on Python 3.7.4 and running in jupyter notebook.
I just installed gpu version with this command:

conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.2.0

DeepChem version seems to be: '2.3.0'

When I run 

from deepchem.molnet import load_chembl25

it works under  Desktop/deepchem folder main folder in a notebook 
but when I try to run the following example notebook in its own subfolder

/Desktop/deepchem/Chemble_data_deepchem.ipynb

and try to run 
from deepchem.molnet import load_chembl25

it does not work and it is not one of the optiona when pressed the tab after "load_".
Here is the error message:

---------------------------------------------------------------------
ImportError                         Traceback (most recent call last)
<ipython-input-6-e643859c37f6> in <module>
----> 1 from deepchem.molnet import load_chembl25

ImportError: cannot import name 'load_chembl25' from 'deepchem.molnet' (/home/ga/anaconda3/lib/python3.7/site-packages/deepchem/molnet/__init__.py)
____-_________________________

Any idea why this happens and a solution suggestion?

Also, does this load_chembl25 provides the full data from
ChEMBLdb 25 (March 2019)?

thanks

**Comment by peastman** [comment]
Python is getting confused because you launched it from a directory that has a "deepchem" subdirectory.  When you say `import deepchem`, it assumes you mean that subdirectory instead of the installed package.

**Comment by altayg** [comment]
Then why load_chembl works on both notebooks but load_chembl25 works only in the main folder?

**Comment by altayg** [comment]
I tried to run the notebook in the main folder assuming that it load there but now it gives the error as below. Any suggestions for why the  load_chembl25 does not work despite the fact that load_chembl works well?

# Load ChEMBL dataset
chembl_tasks, datasets, transformers = load_chembl25(
    shard_size=2000, featurizer="GraphConv", set="5thresh", split="random")

train_dataset, valid_dataset, test_dataset = datasets
# Load ChEMBL dataset
chembl_tasks, datasets, transformers = load_chembl25(
    shard_size=2000, featurizer="GraphConv", set="5thresh", split="random")
​
train_dataset, valid_dataset, test_dataset = datasets
/tmp/chembl_25-featurized/GraphConv does not exist. Reconstructing dataset.
---------------------------------------------------------------------
NameError                           Traceback (most recent call last)
<ipython-input-13-e6089400151b> in <module>
      1 # Load ChEMBL dataset
      2 chembl_tasks, datasets, transformers = load_chembl25(
----> 3     shard_size=2000, featurizer="GraphConv", set="5thresh", split="random")
      4 
      5 train_dataset, valid_dataset, test_dataset = datasets

~/Desktop/deepchem/deepchem/molnet/load_function/chembl25_datasets.py in load_chembl25(featurizer, split, data_dir, save_dir, split_seed, reload, transformer_type, **kwargs)
    104     featurizer = deepchem.feat.CircularFingerprint(size=1024)
    105   elif featurizer == 'GraphConv':
--> 106     featurizer = deepchem.feat.ConvMolFeaturizer()
    107   elif featurizer == 'Weave':
    108     featurizer = deepchem.feat.WeaveFeaturizer()

NameError: name 'deepchem' is not defined

**Comment by peastman** [comment]
Which version of DeepChem do you have installed?  You first said you installed with

```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.2.0
```

That indicates you should have 2.2.0.  But you then said,

> DeepChem version seems to be: '2.3.0'

We haven't built 2.3 packages yet, so you would only have that if you installed from source.  `load_chembl25()` was added in 2.3.  So if you actually have 2.2 installed, it won't be there.

**Comment by altayg** [comment]
I installed with that command but not in a separate conda environment. I miht have run conda update --all though. It was painful and time consuming to install deepchem with gpu version. In the end, after uninstalling all, that command worked fine. Not sure why the version 2.3.

Regarding my problem, I think I spotted the problem. 
In the same notebook, without any input this works fine:

c_tasks, c_datasets, transformers = load_chembl25()

So, it looks  featurizer="GraphConv" might not be working well in the options ofload_chembl25.

Is there a tutorial somewhere, which uses load_chembl25 dataset?

Because the one for load_chembl does not seem to work for load_chembl25 as well?

**Comment by peastman** [comment]
@VIGS25 that sounds like a question for you.

**Comment by altayg** [comment]
Do you havesuggestion for 
why featurizer="GraphConv" might not be working well in the options of load_chembl25?
Or, is it working in your system?

**Comment by VIGS25** [comment]
There is no tutorial available for `load_chembl25`, but there is a training script available [here](https://github.com/VIGS25/chemnet-auxilliaries/blob/master/train_chemception_chembl.py) that uses it.

I don't think the problem is `GraphConv` featurizer not working (because it runs on mine), and is probably something more subtle than that. 

`load_chembl` contains a different set of datasets which is not from the database and I did not want to disturb that. `ChEMBL25` is the version 25 from March 2019, with the duplicates removed.

**Comment by altayg** [comment]
This looks helpful, thanks. I will look into them in more detail.

**Comment by altayg** [comment]
I think there should be a better solution for this:

When I run this in a subfolder (/Desktop/deepchem/example),  it gives error:

tasks, dataset, transformers = dc.molnet.load_chembl25(data_dir=None, save_dir=None, 
featurizer='smiles2img', split='random')

But, if I run it under the main folder ( /Desktop/deepchem ), it works.

It does not seem right. Is this behavior intended to be as is?

**Comment by peastman** [comment]
I believe this is back to the issue I mentioned before: Python is interpreting `deepchem` to mean something different depending on whether you're in a directory that contains a subdirectory of that name.  That's the only reason I know of that the directory you're in would affect this.
