### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by Karunakar444** [deepchem/deepchem#1691]
I was going through the Seq2Seq tutorial. I have loaded the data from disk instead of  dc.molnet.load_muv()  as this data is very huge. When I was running the code I am getting the following error. Can somebody help me with this?
![Screenshot from 2019-10-04 22-15-14](https://user-images.githubusercontent.com/54398887/66225274-b041f780-e6f5-11e9-99a6-5e60e1e549bf.png)

**Comment by peastman** [comment]
I believe this means there's a problem in your dataset.  Somewhere in `train_embeddings_dataset.y` is there an element that's NaN?

**Comment by rbharath** [comment]
I'm going to close this issue for now. @Karunakar444 can you please re-open if you're still having issues?
