### ISSUE TITLE
Deepchem and rdkit imports from terminal but not same in Jupyter Notebook

### ISSUE THREAD

**Issue by altayg** [deepchem/deepchem#1692]
I am on Ubuntu 18.04 and 
installed DeepChem from source in a conda environment with gpu support.

The following commands run well in terminal but I do not observe the same in Jupyter Notebook. It even does not import from rdkit.  Any suggestion to solve this problem?
See below for the runs:

In shell:
---------------------------------------------------------------------------
(base) ga@ga-ws:~/Desktop$ conda activate deepchem
(deepchem) ga@ga-ws:~/Desktop$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepchem as dc
>>> dc.__version__
'2.3.0'
>>> from rdkit import Chem
>>>
---------------------------------------------------------------------------

In Jupyter Notebook:

!python -V
!python -V
Python 3.5.6 :: Anaconda, Inc.
import deepchem as dc
import deepchem as dc
dc.__version__
dc.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-b2468235e567> in <module>
----> 1 dc.__version__

AttributeError: module 'deepchem' has no attribute '__version__'

from rdkit import Chem
from rdkit import Chem
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-3a181df69616> in <module>
----> 1 from rdkit import Chem

ModuleNotFoundError: No module named 'rdkit'

---------------------------------------------------------------------------

**Comment by peastman** [comment]
It sounds like the notebook is using a different Python from the one you're running on the command line.

**Comment by altayg** [comment]
I checked and both are Python 3.5.6 as I am running in deepchem conda environment.
However, on base, I have the latest Python 3.7.4

**Comment by altayg** [comment]
I removed jupyter and ipython from base and installed them on deepchem environment again. 
This caused jupyter kernel problems.  After solving kernel issues, the problem is solved.
These were the main steps that might have helped solving the issue.
However, in between I tried many other things and not clear on exact solution for this issue.
