### ISSUE TITLE
Inconsistent installation recommendations

### ISSUE THREAD

**Issue by KacperKubara** [deepchem/deepchem#1693]
OS: Linux
Package Manager: Conda

The installation recommendations on [deepchem.io](https://deepchem.io/):
`
conda install -c deepchem deepchem=2.1.0 python=3.6
`
And the installation recommendations on [Github](url):
`
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.2.0
`

They are inconsistent and potentially confusing for new users. Especially, there are different versions of recommended deepchem and there is no Python 3.7 option on the website (although docs say that it can run on that version). Is there any reason behind of those inconsistencies, or it hasn't been updated yet?

**Comment by rbharath** [comment]
Yes, agreed the instructions are confusing for new users. The GitHub instructions are the correct one. The ones on the website need to be corrected. (The website code is on github and the instructions can be corrected via pull request https://github.com/deepchem/deepchem.io).

Marking this a bug

**Comment by KacperKubara** [comment]
[PR #19](https://github.com/deepchem/deepchem.io/pull/19) is waiting to be accepted
