### ISSUE TITLE
Issue with set_optimizer in the Seq2Seq Tutorial

### ISSUE THREAD

**Issue by JanoschMenke** [deepchem/deepchem#1703]
Hi, 

so i am trying to run the Seq2Seq Tutorial. But it always says that:

`'SeqToSeq' object has no attribute 'set_optimizer'`

Are my packages out of date or the Tutorial?

**Comment by peastman** [comment]
It sounds like you're using DeepChem 2.3, but the version of the tutorial from 2.2.  Here's the current version: https://github.com/deepchem/deepchem/blob/master/examples/notebooks/seqtoseq_fingerprint.ipynb

@rbharath we really need to get the website updated, both for the tutorials and for the installation instructions.

**Comment by rbharath** [comment]
Good point. Here's a first PR for the installation instructions: https://github.com/deepchem/deepchem.io/pull/17

**Comment by JanoschMenke** [comment]
Awesome thanks for the quick reply
