### ISSUE TITLE
save model in keras deepchem model

### ISSUE THREAD

**Issue by oguitart** [deepchem/deepchem#1705]
Hello,

I'm using latest version of deepchem (2.3), which uses keras model as default model. I have realized that there is no save method for this model. Is that right?? How can we save the models after a fitting?
Thanks,

oriol

**Comment by VIGS25** [comment]
The checkpoints are saved regularly during training. You also have the method `save_checkpoint` that allows you to do the same thing manually. 

https://github.com/deepchem/deepchem/blob/9d0fc5554b286117ae08b21b3f15877b06a1009e/deepchem/models/keras_model.py#L936

**Comment by oguitart** [comment]
Thank you. I know that. But my question was more like: are you planning to offer a method like the one in tensorgraph: 
https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py#L893
Considering that now the keras model is the default model.
Thanks,

oriol

**Comment by VIGS25** [comment]
@peastman would have a better answer to this.

**Comment by peastman** [comment]
`KerasModel` doesn't have a `save()` function, but Keras does provide a few different mechanisms that can be used to save and reconstruct  a `tf.keras.Model`.  So you could restore that, then create a new `KerasModel` wrapping it.  See https://www.tensorflow.org/guide/keras/save_and_serialize.

I think it would be nice to have an equivalent of the TensorGraph `save()` method, but I haven't been able to figure out a general way of doing it.  First you have to save the internal Keras model, and different types of models require different mechanisms.  The `save()` function works with sequential and functional models, but not with subclassed ones.  And then the loss function is defined by an arbitrary callable Python object, which may not be saveable by any mechanism.

**Comment by oguitart** [comment]
Hi,

I have tried to implement your suggestion. That is, I save the keras model using the `tf.keras.Model` save method. Then I load it and I create  a new `KerasModel` (Code below). However, I get an error, when I'm saving the keras model. I'm using tensorflow 1.14, deepchem 2.3 and python 3.6.

Code:
`inputs = [self.atom_features, self.degree_slice,self.membership] + self.deg_adjs`
`outputs = [classification]`
`keras_model_eval = tf.keras.Model(inputs=inputs, outputs=outputs)`
`model_eval = dc.models.KerasModel(keras_model_eval, loss=loss, batch_size=self.batch_size, learning_rate=self.learning_rate, model_dir=self.path_eval)`
`keras_model_eval.save(os.path.join(self.path_eval, "model.h5"))`


Error:

Traceback (most recent call last):
  File "/g/strcombio/paloy/home/oguitart/projects/deepchem/run_graphconv_mode.py", line 5, in <module>
    gph.fit("/g/strcombio/paloy/scratch/oguitart/gr_mol_sign3_b4.h5")   
  File "/g/strcombio/paloy/home/oguitart/projects/source/chemical_checker/package/chemicalchecker/tool/graphconv/graph_smiles_sign.py", line 230, in fit
    keras_model_eval.save(os.path.join(self.path_eval, 'model.h5'))
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1211, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 113, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 105, in save_model_to_hdf5
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 687, in save_weights_to_hdf5_group
    weight_values = K.batch_get_value(weights)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3010, in batch_get_value
    return get_session(tensors).run(tensors)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable graph_conv/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/graph_conv/bias)
	 [[node graph_conv/bias/Read/ReadVariableOp (defined at sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/deepchem/models/layers.py:60) ]]
	 [[graph_conv/kernel_19/Read/ReadVariableOp/_65]]
  (1) Failed precondition: Error while reading resource variable graph_conv/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/graph_conv/bias)
	 [[node graph_conv/bias/Read/ReadVariableOp (defined at sbnb/miniconda3/envs/py36/lib/python3.6/site-packages/deepchem/models/layers.py:60) ]]
0 successful operations.
0 derived errors ignored.

**Comment by peastman** [comment]
I think this message is the key:

> (1) Failed precondition: Error while reading resource variable graph_conv/bias from Container: localhost. This could mean that the variable was uninitialized.

When you first create a model with Keras, a lot of the parameters are left in an uninitialized state.  They get initialized the first time you call `fit()`.  This is done so that you can create a model without having to specify the shapes of all the inputs, and it infers the shapes based on the values you pass on the first training step.  Try fitting your model before calling `save()`.  Does that work?

**Comment by oguitart** [comment]
Hi, 

The code that I wrote was just a few lines to show what I was trying to do. The code that I'm using is always doing the fit before saving the model. Otherwise, there is no point to save the model if the model is not trained and so the weights are not chosen yet. Therefore, the error I got was after doing the fit in the model.

oriol

**Comment by peastman** [comment]
Ok, it must be something else then.  What about this?

```python
with model_eval.session.as_default():
  keras_model_eval.save(os.path.join(self.path_eval, "model.h5"))
```

Does that work?

**Comment by oguitart** [comment]
Hi,

yes, your latest suggestion works to save the model but when I try to load it, it fails.
Attached an ipython notebook from your repository . I try to do that in your  own code to make sure there was nothing from my side that my produce the error. You'll see that in one of the cells I'm saving the model and then loading it again.
Let me know if I can do anything else to help.

oriol

[graph_convolutional_networks_for_tox21.ipynb.zip](https://github.com/deepchem/deepchem/files/3836687/graph_convolutional_networks_for_tox21.ipynb.zip)

**Comment by VIGS25** [comment]
I looked at the code above. There are a few issues, some with your specification and some on the DeepChem side. 

**On DeepChem's side**
All layers (derived from `tf.keras.Layer`) must implement a `get_config` method, which will ensure all arguments to constuct a layer from that configuration are passed.

**On your side**
The custom objects for saving `keras_model` must also include other layers that you used like `GraphPool` and `GraphGather`.

**Comment by oguitart** [comment]
Thanks, I know about the missing layers. I just did a test and I was expecting an error about the missing layers but I got another kind of error. That's why I reported the error to you, Whenever you have the changes to fix the DC side issues, I'll be more than happy to retest my code adding the missing layers.

**Comment by oguitart** [comment]
Hello,

Is there any changes on this issue? It would be nice to save and reuse the models. Right now, it is only possible to do it through the TensorGraph model but I would prefer to use the Keras models.
Thanks,

oriol

**Comment by rbharath** [comment]
Sorry for the delayed response here. Do you have a minimal failing example I can take a look at? That will help me poke at this to see if there's a bug here.

**Comment by oguitart** [comment]
Hi,

In this comment [https://github.com/deepchem/deepchem/issues/1705#issuecomment-552926318] I attached an ipython notebook that I got from you. I added a cell where I tried to save and then load the model. If you try you'll see that it fails.

oriol

**Comment by VIGS25** [comment]
I started out #1713 for this, but didn't get to writing tests for the PR

**Comment by rbharath** [comment]
@VIGS25 Would you have bandwidth to add a few tests for #1713 so we can merge it in?

**Comment by VIGS25** [comment]
I should be able to get tests for all layers done by the weekend. But I can do just the layers in question (from the notebook above), by tonight.

**Comment by rbharath** [comment]
I'm going to close this old issue since I think #1713 addressed the issue here. Please feel free to re-open if it's still an issue.
