### ISSUE TITLE
in deepchem tutorial, modelling solubility tutorial is based on only water solvent data or i can do in other solvent ?

### ISSUE THREAD

**Issue by mukeshb23** [deepchem/deepchem#1707]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by peastman** [comment]
The model is a generic graph convolutional model.  You can train it on whatever data you want.  If you have data for other solvents, that should work too.

**Comment by mukeshb23** [comment]
> The model is a generic graph convolutional model. You can train it on whatever data you want. If you have data for other solvents, that should work too.

thank you so much

**Comment by shenwanxiang** [comment]
> > The model is a generic graph convolutional model. You can train it on whatever data you want. If you have data for other solvents, that should work too.
> 
> thank you so much

Hi,mukeshb123, in speaking of solubility prediction, you can see a web blog here:http://practicalcheminformatics.blogspot.com/2018/09/predicting-aqueous-solubility-its.html, whether GCN has better performance  prediction still a unclear answer

**Comment by mukeshb23** [comment]
> > > The model is a generic graph convolutional model. You can train it on whatever data you want. If you have data for other solvents, that should work too.
> > 
> > 
> > thank you so much
> 
> Hi,mukeshb123, in speaking of solubility prediction, you can have a look at this web blog here:http://practicalcheminformatics.blogspot.com/2018/09/predicting-aqueous-solubility-its.html, whether GCN has better performance in prediction of solubility still an unclear answer, i think

thank you shenwanxiang 
this link is very usefull for me

**Comment by rbharath** [comment]
I'm going to go ahead and close this issue. Feel free to re-open if you have more questions!
