### ISSUE TITLE
modelling solubility tutorial in deepchem

### ISSUE THREAD

**Issue by mukeshb23** [deepchem/deepchem#1708]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by mukeshb23** [comment]
i loaded  one small data in this tutorial for predicting solubility but this is not work.
is this tutorial required large data?

**Comment by peastman** [comment]
How small is your dataset?  In general, all deep models want as much training data as they can get, and the more data you have the better they work.  But the minimum amount of data needed to get good results varies between models and applications.  The less data you have, the simpler you want to make your model.  A very simple model trained on a small amount of data might succeed in learning something, while a larger model trained on too little data likely won't.

**Comment by rbharath** [comment]
I'm going to close this old issue. Please re-open if you're still having issues!
