### ISSUE TITLE
Could I ask where I can find the description of the database, or the orginal source?

### ISSUE THREAD

**Issue by yuanjames** [deepchem/deepchem#1709]
Cause I am not sure all data are predicted or from experiments.

**Comment by rbharath** [comment]
A lot of the datasets on deepchem are drawn from the moleculenet.ai suite. Are there other datasets you have a question on?

**Comment by yuanjames** [comment]
> A lot of the datasets on deepchem are drawn from the moleculenet.ai suite. Are there other datasets you have a question on?

Thanks for your answer,  so the datasets are not real data, I am wondering whether the datasets can be used to train and verify other models?

**Comment by rbharath** [comment]
I'm not sure what you mean. The datasets are drawn from real experiments and are not synthetic. They can be used to train and verify other models, but are of course not suitable for all applications of course

**Comment by yuanjames** [comment]
Yes, I see, appreciation.

**Comment by Prashankalikotayt** [comment]
A basic doubt. What are the node features of Delaney(Solubility data)

**Comment by rbharath** [comment]
@Prashankalikotayt The node features depend on the choice of model. For graph convs, each node is an atom and the node features are basic atomic properties (like atom type, etc.)

**Comment by rbharath** [comment]
Going to close this issue. Feel free to re-open if there are other issues.
