### ISSUE TITLE
Update Tox21 tutorial with correct imports

### ISSUE THREAD

**Issue by KacperKubara** [deepchem/deepchem#1715]
**Description:**
Related issue: #1670 
The tutorial uses old imports , i.e. 
`from deepchem.models.tensorgraph.models.graph_models import GraphConvModel`
which results in ModuleNotFoundError.
As suggested in #1670 changing the import to `from deepchem.models import GraphConvModel` solves the issue.

However, the old imports are still present in the tutorial which is confusing to new users, e.g. https://deepchem.io/docs/notebooks/graph_convolutional_networks_for_tox21.html
They should be replaced with the correct ones.

**Comment by KacperKubara** [comment]
Hey, I would like to correct this error. Could you guide me on how it should be done? I am a bit confused because this tutorial is both in this repo and in the website repo and they have both different extensions (i.e. .ipynb vs html).

**Comment by rbharath** [comment]
My apologies, the tutorials are all out of date. I'm going to do a pass over the coming week to clear them up and get them functional again...

**Comment by rbharath** [comment]
The tutorials should all be clean now. I'm going to go ahead and close this issue now.
