### ISSUE TITLE
https://deepchem.io/docs/notebooks/pong.html buggy

### ISSUE THREAD

**Issue by soerendip** [deepchem/deepchem#1721]
policy = PongPolicy()

now needs a string parameter. Otherwise, it raises an error.
And this line :

    a3c = dc.rl.A3C(env, policy, model_dir='model', optimizer=Adam(learning_rate=0.0002))

raises: 

> TypeError: 'NotImplementedType' object is not callable

**Comment by peastman** [comment]
The up to date version of that tutorial is at https://github.com/deepchem/deepchem/blob/master/examples/notebooks/pong.ipynb.

**Comment by rbharath** [comment]
We've been shuffling a few things around so pardon our noise. The tutorial is now at 

https://github.com/deepchem/deepchem/blob/master/examples/tutorials/18_Using_Reinforcement_Learning_to_Play_Pong.ipynb

It should run correctly without errors. Going to go ahead and close this issue. Please re-open if you're still having problems!
