### ISSUE TITLE
Is there a more mathematical paper explaining the GCN.

### ISSUE THREAD

**Issue by JanoschMenke** [deepchem/deepchem#1723]
Hi,

I was wondering if their is a Paper or Webpage that describes the Graph Convolution Model used in DeepChem in more detail then the "Low Data Drug Discovery with One-Shot Learning" by Altae-Tran et. al.?

**Comment by rbharath** [comment]
I don't believe that there is a more mathematical write-up available. In general, the implementation follows the description in https://arxiv.org/abs/1509.09292.

**Comment by KacperKubara** [comment]
Thanks @rbharath  for sending the link. I actually had the same problem of figuring out what paper you used to implement the model. It might be worth adding a note in docs or in the code about the paper.

**Comment by rbharath** [comment]
Yep, the models are explained in brief in the MoleculeNet paper!

The weave models are from [this paper](https://link.springer.com/article/10.1007/s10822-016-9938-8) and the DAG models are based on work by Baldi's group. Here's [one](http://www.jmlr.org/papers/volume4/baldi03a/baldi03a.pdf) of their papers
