### ISSUE TITLE
Publish deepchem 2.3.0 to PyPI

### ISSUE THREAD

**Issue by katiesandford** [deepchem/deepchem#1726]
**Description:**

Docs suggest that Deepchem should be available on PyPI, but the latest version (2.3.0) is not available.

Is it possible to publish the latest version?

**Comment by rbharath** [comment]
Yes, I'll try to push up an updated version in the next few weeks. In the meanwhile, can you try installing from source for your use case?

**Comment by katiesandford** [comment]
Thanks! I could do, but might as well wait until the new version is published :)

**Comment by rbharath** [comment]
Wanted to report back quickly! I've been working on a plan to revamp DeepChem (https://forum.deepchem.io/t/deepchem-minutes-1-17-2020/68). Once development planning is a little further along, will start getting clean builds up. Might take a few more weeks though...

**Comment by nd-02110114** [comment]
I think this issue is fixed.

Currently, you could install the latest deepchem by this command.

Please try it!
```
pip install --pre deepchem
```
