### ISSUE TITLE
ModuleNotFoundError: No module named 'deepchem.models.autoencoder_models'

### ISSUE THREAD

**Issue by gwanseum** [deepchem/deepchem#1728]
I am trying out this tutorial:

https://github.com/deepchem/deepchem/blob/master/examples/encoders/encoder_example.py
When I run that code I get:

ModuleNotFoundError: No module named 'deepchem.models.autoencoder_models'

Any help would be very appreciated!

I installed deepchem==2.3.0.

And installing it with conda.

```
Your code sample here
```

**Comment by rbharath** [comment]
Good find. This example is outdated and should be removed. I'll leave this issue open to track

**Comment by nd-02110114** [comment]
`deepchem.models.autoencoder_models` move to contrib director  and the current deepchem doesn't support this model. Maybe, we could close this issue.
