### ISSUE TITLE
Rdkit and Jupyter error when using conda installation

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [deepchem/deepchem#1731]
**Description:**

I install deepchem using conda in ubuntu:
`conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.3.0`

At the end:

> Preparing transaction: done
> Verifying transaction: done
> **Executing transaction: | b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'**
> done

Seems there are something wrong with jupyter.

What's more, when I import deepchem in jupyter-notebook:
```
import numpy as np
import tensorflow as tf
import deepchem as dc
from deepchem.models import GraphConvModel
```
There is a warning:

> RDKit WARNING: [10:07:49] Enabling RDKit 2019.09.3 jupyter extensions

Next, I load my dataset:

```
# Load Tox21 dataset
graph_featurizer = dc.feat.graph_features.ConvMolFeaturizer()
loader = dc.data.data_loader.CSVLoader(
    tasks=['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD','NR-PPAR-gamma', 'SR-ARE', 'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53'], 
    smiles_field='smiles',
    id_field="mol_id",
    featurizer=graph_featurizer)
dataset = loader.featurize('tox21-f.csv')
```
An error appeared:

> RDKit WARNING: [10:11:00] WARNING: not removing hydrogen atom without neighbors

So, what's wrong with the jupyter and rdkit, how can I fix them?

Thank you.

deepchem.__version__
**'2.1.1'**

<!-- To get the DeepChem version use the following commands:
>> import deepchem
>> deepchem.__version__

**'2.1.1'**

**Comment by VIGS25** [comment]
These are just warnings. There are no errors. You can check rdkit on how to disable warnings.

**Comment by Jiang-Lu-CAS** [comment]
> These are just warnings. There are no errors. You can check rdkit on how to disable warnings.

OK, I'll try it. What's more, when I install from the source, this warning is disappeared. It seems that there are two editions. Which one can I trust?

**Comment by rbharath** [comment]
@Jiang-Lu-CAS Hmm interesting. It's possible that a recent version of rdkit fixed the issue you're seeing. Could you check your rdkit version in both cases?

**Comment by rbharath** [comment]
I'm going to close this issue. Please feel free to re-open if you're still facing issues @Jiang-Lu-CAS !
