### ISSUE TITLE
Remaining TensorGraph models

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1732]
We still have some models that are based on TensorGraph.  Since we plan to delete TensorGraph in a future release, we need to decide what to do with them.  That means either converting them to Keras or deleting them.

OntologyModel
ResNet50
BPSymmetryFunctionRegression
ANIRegression
UNet

**Comment by rbharath** [comment]
Documenting offline discussion, we're currently planning on deleting these models. If you are currently using one of these models and would like us to keep them, please chime in on this thread!

**Comment by peastman** [comment]
I found one other:

SequenceDNN.

**Comment by rbharath** [comment]
I think we're good to delete this one as well. I don't know of anyone using it at present...

**Comment by peastman** [comment]
These classes were removed in #1733, so I'm closing this.
