### ISSUE TITLE
ScaffoldSplitter with an option to return all scaffolds

### ISSUE THREAD

**Issue by KacperKubara** [deepchem/deepchem#1738]
**Description:**

- DeepChem Version: 2.3.0
- Platform: Redhat 7.7

Hey!
I would like to suggest creating an option for the [ScaffoldSplitter ](https://github.com/deepchem/deepchem/blob/7492d910100888c07e13fc5286a48b8d67d09638/deepchem/splits/splitters.py#L848)so it can return scaffolds generated from the data instead of returning the train, test, and validation set. I think this option could be particularly useful when someone wants to see how different scaffolds can affect the model. 

For example in my case, I would like to train a model on the solubility dataset and then inspect what accuracy/r2scores I can get on particular scaffolds. In this way, I would be able to determine specific types of molecules' structures that affect solubility.

If you find might suggestions useful, I would be happy to propose changes in the ScaffoldSplitter class and submit a PR.

Best,
Kacper

**Comment by KacperKubara** [comment]
Hello, I have created a modified ScaffoldSplitter Class with an option to return the scaffolds. Any thoughts? Gist link below

Basically, I have moved part of `split()` functionality into a new function `generate_scaffolds()`. Code seems to be now a bit clearer too read and it can return only scaffolds if needed. I haven't tested it yet, but I will do it soon and will let you know. 

```python
class ScaffoldSplitter(Splitter):
    """
    Class for doing data splits based on the scaffold of small molecules.
    """

    def split(self,
              dataset,
              frac_train=.8,
              frac_valid=.1,
              frac_test=.1,
              log_every_n=1000):
        """
        Splits internal compounds into train/validation/test by scaffold.
        """
        np.testing.assert_almost_equal(frac_train + frac_valid + frac_test, 1.)
        scaffold_sets = self.generate_scaffolds(dataset)

        train_cutoff = frac_train * len(dataset)
        valid_cutoff = (frac_train + frac_valid) * len(dataset)
        train_inds, valid_inds, test_inds = [], [], []

        log("About to sort in scaffold sets", self.verbose)
        for scaffold_set in scaffold_sets:
            if len(train_inds) + len(scaffold_set) > train_cutoff:
                if len(train_inds) + len(valid_inds) + len(scaffold_set) > valid_cutoff:
                    test_inds += scaffold_set
                else:
                    valid_inds += scaffold_set
            else:
                train_inds += scaffold_set
        return train_inds, valid_inds, test_inds

    def generate_scaffolds(self, dataset, log_every_n=1000):
        """
        Returns all scaffolds from the dataset
        """
        scaffolds = {}
        data_len = len(dataset)

        log("About to generate scaffolds", self.verbose)
        for ind, smiles in enumerate(dataset.ids):
            if ind % log_every_n == 0:
                log(f"Generating scaffold {ind} {data_len}", self.verbose)
            scaffold = generate_scaffold(smiles)
            if scaffold not in scaffolds:
                scaffolds[scaffold] = [ind]
            else:
                scaffolds[scaffold].append(ind)

        # Sort from largest to smallest scaffold sets
        scaffolds = {key: sorted(value) for key, value in scaffolds.items()}
        scaffold_sets = [
            scaffold_set
            for (scaffold, scaffold_set) in sorted(scaffolds.items(),
                                                   key=lambda x: (len(x[1]), x[1][0]),
                                                   reverse=True)
        ]
        return scaffold_sets
```
https://gist.github.com/KacperKubara/64de88354b276caf42d63680785fe086

**Comment by rbharath** [comment]
@KacperKubara Sorry for the slow response! I've been offline for the last week and am just now catching up.

I think this would be a very useful bit of functionality! I'd definitely be open to a pull request with this functionality. If we have a few tests attached, we should be good to merge it in once ready :)

**Comment by KacperKubara** [comment]
Hey @rbharath 
I added a PR with tests: https://github.com/deepchem/deepchem/pull/1751
Let me know if the tests are okay and if something should be changed :)

**Comment by KacperKubara** [comment]
Closing since the PR was merged
