### ISSUE TITLE
Does output values is scaled during training?

### ISSUE THREAD

**Issue by yuanjames** [deepchem/deepchem#1739]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by rbharath** [comment]
@yuanjames Would you mind clarifying a bit further? Is the question whether output values are normalized for training? This can be done by transforming the data before training.

**Comment by yuanjames** [comment]
Hi, thanks for your reply. Yes, the training data (inputs and outputs) can be preprocessed by normalisation or standardisation.

As I can see the latest experiment results on the website, I would like to know whether you normalised output value during training and reverted prediction results back during test.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rbharath** [comment]
You can pass in a list of transformers that were applied to `predict()`. If you do so, it will undo the normalization and return rescaled predictions back to you:

https://github.com/deepchem/deepchem/blob/master/deepchem/models/models.py#L126

Hope this helps!
