### ISSUE TITLE
Different results every time!

### ISSUE THREAD

**Issue by Gvinkc** [deepchem/deepchem#1744]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by Gvinkc** [comment]
I am getting different results  (scores for test, and train ) on every run (on the same data). Could you please suggest how to get the same results?

**Comment by peastman** [comment]
You didn't give your code, so I can't be sure of all sources or nondeterminism you might have.  But generally there are a few of them:

- Most models initialize their parameters to random values.
- If you're using random splits for your dataset, that will be different every time.
- If you're explicitly using any random values (like from `np.random`), those will be diffferent every time.

Splitting methods generally offer a `seed` argument you can use to fix the random number seed.  Likewise Numpy and TensorFlow both have functions to set the random seed.

**Comment by Gvinkc** [comment]
Got you! Thank you for the suggestions :)
