### ISSUE TITLE
How to parse data when it only has only one wanted property?

### ISSUE THREAD

**Issue by sym823808458** [deepchem/deepchem#1749]
**Description:
DeepChem Version:deepchem 2.10
Platform:linux Ubuntu**

Thanks a lot.

```
diff_df = df['n1'] - df['n2']

sns.distplot(diff_df)
plt.xlabel('difference in n')
plt.ylabel('probability')
```

**Comment by rbharath** [comment]
Could you provide some more clarification on the problem you're trying to solve? It looks like you're looking to take the difference of two fields in your data frame, but I'm not sure what you're trying to do after that
