### ISSUE TITLE
How to parse my dataset when it only has one wanted property?

### ISSUE THREAD

**Issue by sym823808458** [deepchem/deepchem#1750]
**Description:
DeepChem Version:deepchem 2.10
Platform:linux Ubuntu**

I have read the example named"Creating a high fidelity DeepChem dataset from experimental data",but feel doubtful.
In that case,it has 2 properties,named n1 and n2,and then ,it uses the difference of them(diff_df = df['n1'] - df['n2']) to delete the error.I understand this.
BUT,in my case,I only has one property.Maybe just make it Gaussian distribution?delete all of the data out of it?It sounds not good for me.
Could any one give me some advice?
Thanks a lot.

```
diff_df = df['n1'] - df['n2']

sns.distplot(diff_df)
plt.xlabel('difference in n')
plt.ylabel('probability')
```

**Comment by rbharath** [comment]
In that notebook, the difference is taken to damp the noise. If you have one property that isn't too noisy, it's fine to use as is. Try plotting the distribution of that property and perhaps delete the outliers if there are any.

**Comment by rbharath** [comment]
Going to close this issue for now. Feel free to re-open if you have more questions!
