### ISSUE TITLE
Let's remove dc.hyper

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1754]
The DeepChem hyperpameter module `dc.hyper` is very simple, featuring only simple algorithms for hyper parameter searching. I propose that we remove the `dc.hyper` module and replace all tutorial usages with Ray tune or Keras tuner examples:

https://ray.readthedocs.io/en/latest/tune.html
https://github.com/keras-team/keras-tuner

Tune features a sophisticated suite of features and works with many machine learning packages. By swapping to tune, we'd place our examples more in line with community best practices. Keras tuner also has more sophisticated algorithms, but it specialized for Keras models. We can use whichever of these is more suited for the tutorial example at hand.

CC @peastman @VIGS25

**Comment by richardliaw** [comment]
Sorry for totally going awol previously; if you have an example runnable script to convert to using Ray Tune, I can definitely help out.

**Comment by rbharath** [comment]
Here's my proposed set of next steps:

1. In DeepChem 2.4, mark `dc.hyper` as deprecated. Remove outright in DeepChem 2.5
2. In examples and tutorials, remove use of `dc.hyper` and swap to use of tune/keras-tuner

@richardliaw Thanks for offering to help! Let me try to get a simple example script for you in a bit

**Comment by nd-02110114** [comment]
I think this isssue was fixed. We continue to maintain `dc.hyper`

**Comment by rbharath** [comment]
Yep, agreed. It would be really useful to add a tutorial on how to use Ray Tune with DeepChem though!
