### ISSUE TITLE
Replace deepchem.rl with rllib?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1768]
Should we consider replacing `deepchem.rl` with [rllib](https://ray.readthedocs.io/en/latest/rllib.html)? `rllib` has a number of advanced algorithms (including PPO, A2C, A3C among many others).

Using a more standard framework for reinforcement learning will reduce the amount of code we have to maintain and will let us focus on the chem/bio parts instead of maintaining our own code.

What do folks think?

CC @peastman @VIGS25

**Comment by VIGS25** [comment]
I agree with this.

**Comment by peastman** [comment]
I'm not familiar with it, but it sounds worth investigating.

**Comment by silentC1C4D4** [comment]
Hello! This is Madhur Rao. I'd like to look into this issue. Can you assign this to me?

**Comment by rbharath** [comment]
@silentC1C4D4 A good place to start experimenting might be to see if you can convert this tutorial to use `rllib`: https://github.com/deepchem/deepchem/blob/master/examples/tutorials/18_Using_Reinforcement_Learning_to_Play_Pong.ipynb
