### ISSUE TITLE
Understanding Travis Failure on Python 3.5

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1771]
Our travis build on Python 3.5 is currently failing. It looks like it's hanging on the conda build process. In general, our conda builds have been very slow recently with the conda solver hanging (see https://github.com/deepchem/deepchem/issues/1767).

I'm not really sure how to go about fixing the solver issues. Opening this thread to see if we can crowdsource some ideas...

**Comment by peastman** [comment]
Alternatively, should we just update travis to use newer Python versions?  This may be happening because some of the libraries DeepChem depends on are no longer adding Python 3.5 builds.

**Comment by rbharath** [comment]
I'd be OK with going to Python 3.6 and 3.7 support only. Are any folks still on only Python 3.5?

I think the 3.5->3.6 upgrade is pretty gentle so I think we'd probably be pretty clear to make the switch.

**Comment by peastman** [comment]
How about testing on 3.6 and 3.8?  The oldest release we support and the newest release currently available.

**Comment by rbharath** [comment]
+1 for testing on 3.6 and 3.8. Seems like a nice band of support

**Comment by rbharath** [comment]
I think 3.8 support doesn't work yet. I'm getting all sorts of package conflicts when I try to make the build work. How about just 3.6 and 3.7 support for now until the ecosystem catches up to 3.8?

**Comment by peastman** [comment]
Ok, that's reasonable.

**Comment by rbharath** [comment]
Closing this since we've bumped in #1773
