### ISSUE TITLE
Understanding features used in GraphConv featurizer

### ISSUE THREAD

**Issue by SeanXiaoyuSun** [deepchem/deepchem#1785]
Dear All,

I'm trying to play around features used in Graph Convolutional featurizer to do some feature engineering. But I'm not quite sure how [number of radical electrons for an atom](https://github.com/deepchem/deepchem/blob/f310f0a8d9eeb804f5e04974edff10ba62efab63/deepchem/feat/graph_features.py#L179) is defined in this context. Could anyone tell me anything about that? Is that the number of unpaired electrons for an atom? 

I may have some other questions regarding definitions of these features used in these featurizers in DeepChem. Should I post following questions here or should I reach out to Discourse? 

Thanks

**Comment by rbharath** [comment]
`GetNumRadicalElectrons()` is directly pulled from rdkit. You can see the reference class here https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html. Here's another docs reference:  https://www.rdkit.org/docs/source/rdkit.Chem.Descriptors.html#rdkit.Chem.Descriptors.NumRadicalElectrons

Asking here or on [gitter](https://gitter.im/deepchem/Lobby) is fine. The tradeoff is probably faster answers on gitter, but issues mean the answers are stored for posterity :)
