### ISSUE TITLE
RandomForestClassifier not accepting a graphconv featurized dataset

### ISSUE THREAD

**Issue by macca1996-bit** [deepchem/deepchem#1788]
**Description:**

- DeepChem Version: 2.3.0
- Platform: Colab

Trying to run a random forest classifier as a benchmark. Featurized my dataset using ConvMolFeaturizer and getting the following error:

TypeError: float() argument must be a string or a number, not 'ConvMol'

This occurs with and without transforming my dataset.

As an additional question: Does the balancing transformer still apply to random forests in the same way it does NN?

Thanks

```
Your code sample here
dataset_file= "my_data.CSV"
tasks = ["label"]
featurizer = dc.feat.ConvMolFeaturizer()
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="SMILES", featurizer=featurizer)
dataset = loader.featurize(dataset_file, shard_size=8192)

transformers = [
    dc.trans.BalancingTransformer(transform_w=True, dataset=dataset)]

for transformer in transformers:
  dataset = transformer.transform(dataset)

splitter = dc.splits.RandomSplitter()
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset)

from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier(n_estimators=100)
model=dc.models.SklearnModel(rf_model)
model.fit(train_dataset)


----> 5 model.fit(train_dataset)
---> 85     return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'ConvMol'
```

**Comment by peastman** [comment]
ConvMolFeaturizer is intended to be used with graph convolutions.  It produces a ConvMol object for each sample, which describes how to represent the molecule on a graph.  It isn't appropriate for any other type of model.

**Comment by macca1996-bit** [comment]
Hmmm. I've seen other featurizers being passed into random forests in the tutorials. Which featurizers are suitable for passing into a random forest?

**Comment by rbharath** [comment]
`dc.feat.CircularFingerprint`, `dc.feat.RdkitGridFeaturizer` (this is only for 3D structures like protein/ligand binding complexes), `dc.feat.RdkitDescriptors` are the ones that produce flat vectors suitable for random forest models

**Comment by peastman** [comment]
We probably could stand to improve our documentation on this.
