### ISSUE TITLE
Error when trying to import DeepChem in colab

### ISSUE THREAD

**Issue by macca1996-bit** [deepchem/deepchem#1790]
**Description:**

- DeepChem Version:
- Platform:

Been using DeepChem in colab for a few weeks, this error randomly popped up today. When trying to import DeepChem i get the following error:

```
!wget -c https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
!chmod +x Anaconda3-2019.10-Linux-x86_64.sh
!bash ./Anaconda3-2019.10-Linux-x86_64.sh -b -f -p /usr/local
!conda install -y -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.3.0
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

import deepchem as dc

ImportError
----> 3 import deepchem as dc
---> 10 from tensorflow.python.pywrap_tensorflow_internal import NewCheckpointReader
ImportError: cannot import name 'NewCheckpointReader'
```
I've tried restarting runtime, factory restarting runtime and restarting my laptop, none of this has fixed the issue.

**Comment by rbharath** [comment]
This is due to the TF2.X update on Colab that Google just pushed out. PR #1789 should have fixed this. Could you try running the tutorials again?

**Comment by Laksh1997** [comment]
Just got this same error

**Comment by macca1996-bit** [comment]
Fixed, thanks a lot for your help.

For those also facing this issue: %tensorflow_version 1.x

Add that at the beginning of your install
