### ISSUE TITLE
What are self atoms and deg_slice in GraphConv?

### ISSUE THREAD

**Issue by alexethomas99** [deepchem/deepchem#1791]
Hey, I'm trying to work out how the convolution works in GraphConv and am confused by this line:

```
# Get self atoms
begin = tf.stack([deg_slice[deg - self.min_degree, 0], 0])
size = tf.stack([deg_slice[deg - self.min_degree, 1], -1])
self_atoms = tf.slice(atom_features, begin, size)
```

What is deg_slice supposed to be (it's just passed in as "inputs" and I can't tell where from) And what is a "self atom"?

Thank you very much

**Comment by rbharath** [comment]
This implementation is unfortunately pretty contorted (we first implemented in TF0.5 or something and had to do strange contortions to make operators work out)

`deg_slice` is one of the user inputs. It's generated by `dc.feat.ConvMolFeaturizer`. To see an example of usage of the raw layer, check out this test: https://github.com/deepchem/deepchem/blob/master/deepchem/models/tests/test_layers.py#L76. Here's an explanation of what `deg_slice` means: https://github.com/deepchem/deepchem/blob/master/deepchem/feat/mol_graphs.py#L217. Roughly speaking, it's an indexing tool to help us pull out different subsets of atoms.  `self_atoms` is pulling out the atom features for atoms of degree `deg` (that is, all the atoms which have `deg` number of bonds).

This implementation is based on https://arxiv.org/abs/1509.09292. It might be useful to read the pseudocode in that paper and compare side by side to get the idea for what we're doing.

**Comment by alexethomas99** [comment]
Thanks a lot for the explanation and reading
