### ISSUE TITLE
Create PyTorch dataset

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1800]
Since our goal is for DeepChem's Dataset class to easily interoperate with all machine learning frameworks, I'd like to add support for creating a PyTorch Dataset from it.  I think this will mostly be simple: just create a subclass of torch.utils.IterableDataset that iterates over the data.  A little care will be needed to work correctly with multiprocessing, but that shouldn't be hard.

I don't want to actually add PyTorch as a dependency of DeepChem, of course.  I can mostly handle that by only importing it inside the function.  The test cases will need to import it too, of course, so for the moment I might mark those tests as slow so travis won't try to run them.  Once we migrate molnet into its own repository, we can include PyTorch in the CI for that repo.

**Comment by rbharath** [comment]
This sounds like a great idea! It'll make it much easier for folks who work primarily in PyTorch to make use of MoleculeNet datasets.
