### ISSUE TITLE
Remove verbose kwarg from DeepChem classes and make sure all prints are converted to logging statements

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1806]
Earlier versions of DeepChem relied on print statements to log. In particular, we used the following utility function:

```
def log(string, verbose=True):                                  
  """Print string if verbose."""                                
  if verbose:
    print(string)                  
```

And attached the `verbose=True/False` keyword argument to the constructor of classes. This is essentially a rudimentary logging system. I propose we remove the `verbose` flag and swap all instances of this over to using python's `logging` module. This is much friendlier for production use cases since it's possible to control the amount of logging output produced by DeepChem much more easily.

I'm planning to make this change over in #1792 but wanted to share here for feedback in case folks have concerns

**Comment by nd-02110114** [comment]
I seem #2017 fixed this problem!
