### ISSUE TITLE
Refactor RdkitGridFeaturizer Implementation

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1809]
`RdkitGridFeaturizer` is a very complicated class. It has a whole range of options which allow for the computation of different features on macromolecular input data (such as PDBBind data). However, the many options are poorly documented and the current implementation is very hard to work with. It's a giant jumble of code that isn't modular or easily modifiable.

I propose that the constituent features of `RdkitGridFeaturizer` be factored out into their own featurizer classes. Here are the new featurizer classes that would result

- `ContactCircularFingerprint`: Computes a concatenated ECFP fingerprint of the regions of two molecules that are in close contact. So for a ligand and its binding pocket on a protein, it computes a ligand circular fingerprint, a protein binding pocket circular fingerprint and concatenates them. This corresponds to the 'ecfp_hashed' feature current computed by `RdkitGridFeaturizer`. The output for a complex is a vector of length `2*size` where `size` is the circular fingerprint size.
- `ContactCircularVoxelizer`: Computes a tensor of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, size)` where `voxels_per_edge=int(box_width/voxel_width)` is the number of voxels per edge of the box around the macromolecular complex which is featurized. This corresponds to the 'ecfp' feature current computed by `RdkitGridFeaturizer`.
- `SplifFingerprint`: Compute a "SPLIF" fingerprint of a protein-ligand complex. This corresponds to feature 'splif_hashed' computed currently by `RdkitGridFeaturizer`. This produces a vector of length `2*size` for a macromolecular complex. This is conceptually pretty similar to `ContactCircularFingerprint` but computes ECFP fragments only for direct contacts instead of the entire contact region.
- `SplifVoxelizer`: Compute a "SPLIF" voxel grid of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, size)`.  Corrresponds to 'splif' feature for current `RdkitGridFeaturizer`.
- `ChargeVoxelizer`: Computes the gasteiger partial charges for atoms in the provided macromolecular complex. Produces a tensor of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, 1)` which computes the local partial charge at each voxel. Corresponds to 'charge' feature of `RdkitGridFeaturizer`
- `HydrogenBondCounter`: Counts the number of hydrogen bond interactions. Produces a scalar count of shape `(1,)` which computes the total number of hydrogen interactions in the complex. Corresponds to 'hbond_count' feature of `RdkitGridFeaturizer`.
- `SaltBridgeVoxelizer`: Counts salt-bridge interactions. Produces a tensor of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, 1)` which computes the number of salt bridges in each voxel. Corresponds to 'salt_bridge' feature of `RdkitGridFeaturizer`.
- `CationPiVoxelizer`: Counts the number of cation-Pi interactions. Produces a tensor of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, 1)` which computes the number of cation-Pi in each voxel. Corresponds to 'cation_pi' feature of `RdkitGridFeaturizer`.
- `PiStackVoxelizer`: Counts the number of Pi-Pi/Pi-T interactions. Produces a tensor of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, 2)` which computes the number of Pi-Pi /Pi-T interactions in each voxel. Corresponds to 'pi_stack' feature of `RdkitGridFeaturizer`.
- `HydrogenBondVoxelizer`: Counts the number of hydrogen bonds interactions. Produces a tensor of shape `(voxels_per_edge, voxels_per_edge, voxels_per_edge, 1)` which computes the number of hydrogen interactions in each voxel. Corresponds to 'hbond' feature of `RdkitGridFeaturizer`.

I've implemented most of these changes in #1792. The resulting code is much cleaner and much easier to reason about. In this model the external API for `RdkitGridFeaturizer` is unchanged, but it's possible to invoke the substituent featurizers independently. Under the hood, `RdkitGridFeaturizer` now just invokes the correct combination of substituent featurizers to do its work. 

Access to these featurizers as first class objects may be of its own scientific value since it will be possible to experiment with different featurizers and use combinations for different problems. Exposing the voxelizers explicitly will also make it easier to experiment with 3D convnets for analyzing macromolecular complexes.

**Comment by peastman** [comment]
I *think* this mostly sounds reasonable, though I'd like to understand the intended uses a little better.  Would RdkitGridFeaturizer still be the recommended one for most people to use most of the time?  Usually it's best to get all the information you can.  The others would then be useful for ablation studies, to identify which pieces of information are most useful?

**Comment by rbharath** [comment]
I think `RdkitGridFeaturizer` will remain useful as the kitchen-sink featurizer for people to use, but the pedagogical examples might be better of switched to the substituent featurizers since they're conceptually easier to think about. I'm not sure yet though and want to do more experimentation to see.

I have a suspicion that people might end up using `ContactCircularFingerprint` or `SplifFingerprint` often in practice since they're conceptually simple to think about.

**Comment by peastman** [comment]
In a sense, RdkitGridFeaturizer is conceptually very simple.  "This is a kitchen sink featurizer.  It computes everything we can think of to compute that might be useful."

**Comment by rbharath** [comment]
Closing as implemented
