### ISSUE TITLE
AtomicConvFeaturizer is broken

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1831]
AtomicConvFeaturizer is completely nonfunctional.  It looks like it was never adapted when we made the switch to Keras--and apparently no one noticed!  We do have a test case for it, but it's marked as slow so it doesn't get run on travis.  And anyway, it doesn't check that results are correct.

Does anyone use this featurizer?  Should we fix it or delete it?

**Comment by rbharath** [comment]
I've already gotten rid of the featurizer in #1792. Here's the older issue that explains context: https://github.com/deepchem/deepchem/issues/1798

As a tl;dr. I propose we should delete the old `AtomicConvFeaturizer`, rename `ComplexNeighborListFragmentAtomicCoordates` to `AtomicConvFeaturizer`, and add a `predict_embedding()` function to the atomic conv model which extracts embeddings for molecular complexes (which is what the current `AtomicConvFeaturizer` does under the hood).

I'll try to get out a smaller PR with this change for review in the next week or so

**Comment by peastman** [comment]
Ok, I'll ignore it then.
