### ISSUE TITLE
df.as_matrix is deprecated

### ISSUE THREAD

**Issue by Laksh1997** [deepchem/deepchem#1841]
**Description:**

AttributeError: 'DataFrame' object has no attribute 'as_matrix'

when loading ```deepchem.molnet.load_uv(featurizer="Raw", split="index")``` on the latest deepchem version.

```df.as_matrix``` has been deprecated in pandas since 0.23

**Comment by peastman** [comment]
This is already fixed in the latest development code.  It will be in the next release.

**Comment by Laksh1997** [comment]
Awesome!
