### ISSUE TITLE
Latest deepchem version (2.3.0) not on pip

### ISSUE THREAD

**Issue by Laksh1997** [deepchem/deepchem#1842]
**Description:**

Latest deepchem version (2.3.0) not on pip

Can't use datasets like thermosol etc which have been added in this version

**Comment by rbharath** [comment]
We're a little behind on this one! I'll try to get the 2.3.0 and 2.4.0rc1 version out on pip in the next few weeks. In the meanwhile, could you use conda for your experiments?

**Comment by Laksh1997** [comment]
Deepchem install failed on Conda. Will get the error up later.

**Comment by nd-02110114** [comment]
We publish the nightly build version via pip.
So, you could install the latest DeepChem (not 2.3.0) by this command.

```
pip install --pre deepchem
```
