### ISSUE TITLE
source code of model_ops

### ISSUE THREAD

**Issue by TrikiSadok** [deepchem/deepchem#1845]
I am looking for the source code of the class model_ops as it is referred in the imports block in this link:
https://github.com/deepchem/deepchem/blob/master/contrib/nn/constraints.py 
I looked up in deepchem.io and deepchem/contrib/nn but with no results.

**Comment by peastman** [comment]
I don't think it exists anymore.  Everything in `contrib` is unsupported, so there's a lot of obsolete code that doesn't work anymore, but we keep around in case we want to revive it at some point.

**Comment by rbharath** [comment]
In case you're working on low data models, I'm planning to start work on re-integrating the one-shot models into DeepChem main branch (most of the code in `deepchem/contrib/nn` was for these models). This will probably take a couple of months to get done though

**Comment by TrikiSadok** [comment]
I found the source code in https://deepchem.io/_modules/deepchem/nn/model_ops.html.
I didn't think it is a .py file and not a class.
Yes, I am trying to implement idea from 'low data drug discovery with one-shot learning' paper. Do you see another way of doing it ??

**Comment by rbharath** [comment]
At present, only `deepchem==1.3.2` works for the one-shot models. I'm working now on refactoring them to work with DeepChem 2.4 but this will take probably a month at the least to become ready.

**Comment by TrikiSadok** [comment]
I got a problem installing version deepchem==1.3.2.
after I install it with pip install deepchem==1.3.2.dev290, I run deepchem.__version__ and I always find the version to be 1.3.1 which doesn't contain classes SequentialSupportGraph and SupportGraphClassifier.
Is it my fault is some way ??

**Comment by rbharath** [comment]
It's most likely just that we forgot to bump the version tag back then... I think you're fine.

**Comment by rbharath** [comment]
Going to close this issue. We still need to port the low-data paper into DeepChem. It's on the model wishlist issues though
