### ISSUE TITLE
Installation following README doesn't work

### ISSUE THREAD

**Issue by zealseeker** [deepchem/deepchem#1880]
Hopefully this will be fixed in #1871 
As a reference I record the problem I am facing with.
Currently I cannot install deepchem either by pip or by conda.
The CI was broken where installation is by the scripts:
```
conda install -y -q scikit-learn=0.22
conda install -y -q -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.3.0
```
The error was that tensorflow is not installed. So did you remove the dependency from anaconda in 2.3.0?

By the way, I tried using pip but failed (#1842)
```
pip install scikit-learn==0.22 && \
conda install -y -c rdkit rdkit && \
pip install joblib pandas tensorflow pillow deepchem
```
 but the output was 
```
ImportError: cannot import name 'NewCheckpointReader' from 'tensorflow.python.pywrap_tensorflow_internal' (/miniconda/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py)
```

All these two ways were exactly the same as the document but nothing works.
And a stable version is highly required including well defined dependencies. For example, scikit-learn should be <0.23 in deepchem 2.3.0 due to joblib (#1861)

**Comment by nd-02110114** [comment]
Sorry for your inconvinience 🙇‍♂️ 
Maybe you can install the following command.
deepchem v2.3.0 requires tensorflow v1.

```
pip install scikit-learn==0.22 && \
conda install -y -c rdkit rdkit && \
pip install joblib pandas tensorflow==1.15 pillow deepchem
```

**Comment by zealseeker** [comment]
@nd-02110114 It works!  Great!

**Comment by OXPHOS** [comment]
Hi I was running into the `` error so I tried 

> Sorry for your inconvinience 🙇‍♂️
> Maybe you can install by using the following command.
> deepchem v2.3.0 requires tensorflow v1.
> 
> ```
> pip install scikit-learn==0.22 && \
> conda install -y -c rdkit rdkit && \
> pip install joblib pandas tensorflow==1.15 pillow deepchem
> ```

Hi, I ran into the error `cannot import name 'NewCheckpointReader' ` when following the README.
So I tried the instructions above.
I got another error:
`cannot import name 'jaccard_similarity_score' from 'sklearn.metrics' (/home/paden/anaconda3/lib/python3.7/site-packages/sklearn/metrics/__init__.py)`

I am wondering what is the correct way to do it now?

**Comment by nd-02110114** [comment]
@OXPHOS 

The correct way is the following.

```
pip install tensorflow==1.14
conda install -c rdkit -c conda-forge rdkit deepchem==2.3.0
```

If you want to use with GPU,

```
pip install tensorflow-gpu==1.14
conda install -c rdkit -c conda-forge rdkit deepchem==2.3.0
```

And if you want use nightly version,

```
pip install tensorflow=2.2 deepchem-nightly
conda install -c rdkit -c rdkit
```

**Comment by OXPHOS** [comment]
Thank you. I reset my environment and started all over. Now everything worked.

BTW, one thing I am not sure whether it was important:
```
pip install tensorflow==1.14
conda install -c rdkit -c conda-forge rdkit deepchem==2.3.0
```
installed `rdkit 20170901`, in which I could not use `rdkit.Chem.Draw`(see [the issue](https://github.com/rdkit/rdkit/issues/1675))
So I unsintalled `rdkit` and did `conda install -c conda-forge rdkit` to get the `2020.03.4` version.

So far so good.

Maybe this would be useful to someone.
