### ISSUE TITLE
Which deepchem 2.3.0 is correct...?

### ISSUE THREAD

**Issue by nd-02110114** [deepchem/deepchem#1881]
Maybe, deepchem 2.3.0 package is published by conda-forge channel and deepchem channel.  
Is this situation suitable...? Is it necessary to remove `conda-forge/deepchem` package?

https://anaconda.org/deepchem/deepchem/files
https://anaconda.org/conda-forge/deepchem/files

And, current installation guide 
```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem==2.3.0
```
maybe install package from `conda-forge/deepchem` according to this issue https://github.com/deepchem/deepchem/issues/1880

**Comment by rbharath** [comment]
I haven't personally tested the conda-forge deepchem conda package yet, but perhaps it's more sustainable to swap over to using conda-forge longer term as the default package. We should definitely look into this.

**Comment by peastman** [comment]
Who created it?

**Comment by nd-02110114** [comment]
Please check this repo.
https://github.com/conda-forge/deepchem-feedstock

> I haven't personally tested the conda-forge deepchem conda package yet, but perhaps it's more sustainable to swap over to using conda-forge longer term as the default package. We should definitely look into this.

I agree your opinion. We should replace handmade release process to CI based process like conda-forge. 

However, the current situation is not so good. Because  the following command expected to install `deepchem/deepchem`, but it installed `conda-forge/deepchem` . This conflict may lead to complex issue tracking.

```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem==2.3.0
```

I think `conda-forge/deepchem ` should be unpublished. How about? 
If you think so, I could unpublish the packages by following the process.
https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages

**Comment by rbharath** [comment]
How about we instead swap over to using conda-forge/deepchem as the default command? This would require a bit of testing but it seems the more future proofed method. I'm one of the maintainers on the feedstock repo, so we can push any fixes we need there and start using it as the default installation path.

**Comment by nd-02110114** [comment]
> How about we instead swap over to using conda-forge/deepchem as the default command? This would require a bit of testing but it seems the more future proofed method. I'm one of the maintainers on the feedstock repo, so we can push any fixes we need there and start using it as the default installation path.

I seem this is a good direction. If we can publish not only deepchem but also deepchem-gpu from conda-forge,  we should swap over to using conda-forge/deepchem!

**Comment by nd-02110114** [comment]
We think `conda-forge/deepchem` is better, so I closed this issue
