### ISSUE TITLE
DeepChem 2.4.0 Cut

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1883]
Our build issues seem to be mounting, so it seems like it's time to make a DeepChem 2.4.0 cut. Here's my proposed list of changes that we should get in before the cut:

- Merge https://github.com/deepchem/deepchem/pull/1863 (docking overhaul PR).
- Merge https://github.com/deepchem/deepchem/pull/1878 (hyperparam overhaul PR)
- Add documentation about the release process to the docs/folder (PR coming)

There's still more upstream changes in #1792, but I think it will take a few more weeks yet to finish all of those changes and we have too many build issues mounting.

Post the 2.4.0 cut, I propose we move to a faster paced release cycle. In particular, I propose we do a monthly minor release. That is, we'd release 2.4.1 a month after 2.4.0, 2.4.2 a month after that etc. When 2.4.x reaches maturity, we can tag it as 2.5.0. I'm hoping more rapid releases will mean there's less pressure to get things into a release since the next release will come up soon.

What do folks think? CC @peastman @nd-02110114 @vsomnath

**Comment by vsomnath** [comment]
What are the major things that don't work right now? - and what changes do we target for the next minor releases

**Comment by rbharath** [comment]
With #1863 and #1878 in, I think there won't be anything broken in DeepChem 2.4.0, but the grid and atomic featurizers will still be in bad shape (but no worse than 2.3.0). I think we can get these upgraded with the changes from #1792 in time for 2.4.1.

**Comment by peastman** [comment]
I still need to fix some things on Windows once #1863 is merged.  That shouldn't take long.

**Comment by nd-02110114** [comment]
> Post the 2.4.0 cut, I propose we move to a faster paced release cycle. In particular, I propose we do a monthly minor release. That is, we'd release 2.4.1 a month after 2.4.0, 2.4.2 a month after that etc. When 2.4.x reaches maturity, we can tag it as 2.5.0. I'm hoping more rapid releases will mean there's less pressure to get things into a release since the next release will come up soon.

I agree with this plan, but I think we should start after automating build and release process like peatsman mentioned in a sync call. And, monthly release may be a little hard, so we can set longer release span like per three month. I think our goal is to have an easy release system like we can release hotfix.

**Comment by rbharath** [comment]
I've been thinking about this a bit more and I don't think we're ready to make the DeepChem 2.4.0 cut. The reason is that there are many large PRs still in flight that are making large changes. Since we haven't had a release in a long time, it feels like we need to have a complete release instead of a half-baked one.

I propose instead that we follow the tac suggested in #1955 and put up a deepchem_nightly pip package. We can then start directing our developers to use this package while we mature the large deepchem refactoring that's on-going.

**Comment by rbharath** [comment]
I just realized we have a critical blocker before 2.4.0. MoleculeNet datasets are currently mostly hosted on Stanford-run AWS accounts. I've been asked to move all datasets off by the end of the month. I've started doing this, but it means that we can't make the cut for the next release until we've updated moleculenet to point to the new datasets.

**Comment by rbharath** [comment]
Joining the list of critical blockers is https://github.com/deepchem/deepchem/issues/2013, which is a serious bug in our `GraphConv` loading/saving code

**Comment by rbharath** [comment]
Here's the updated list of critical blockers to getting DeepChem 2.4.0 out:
- https://github.com/deepchem/DeepLearningLifeSciences/issues/20: New pretrained models for DeepChem book
- https://github.com/deepchem/deepchem/pull/1950: Fix moleculenet optimization functions after overhaul of hyperparameters
- https://github.com/deepchem/deepchem/pull/1923: Fix atomic convolutions to ensure that they actually learn.
- https://github.com/deepchem/deepchem/issues/2013: Fix saving/reloading issues with `GraphConvModel`

CC @peastman @nd-02110114 @ncfrey

**Comment by peastman** [comment]
> deepchem/DeepLearningLifeSciences#20: New pretrained models for DeepChem book

I don't think this one needs to block the release.  We just need to do it (and update all the book examples) pretty soon after getting the release out.

**Comment by rbharath** [comment]
Closing this since we've made the 2.4.0 cut
