### ISSUE TITLE
datasets and website directories are necessary...?

### ISSUE THREAD

**Issue by nissy-dev** [deepchem/deepchem#1892]
I seem `datasets` and `website` directories are not used.... 
Can we remove these? Especially, it is better to remove datasets (about 150Mb).
deepchem repository size is a little big and it takes time to clone.

To be exact, `datasets/mini_muv.csv.gz` (20kb) are only used in test, so we can move `deepchem/data/tests/` like `mini_emol.csv`.

**Comment by rbharath** [comment]
We should definitely get rid of the website directory. That's an artifact from earlier when the website was maintained in this repo.

I'd be in favor of removing the datasets directory eventually, but want to make sure that we've moved the used datasets into the tests folder and the other datasets onto AWS first

**Comment by nd-02110114** [comment]
Ic all files in 

- [ ] Positive Modulators Summary_ 918.TUC _ v1.xlsx
- [ ] chembl_5thresh.csv.gz
- [ ] chembl_sparse.csv.gz
- [ ] chembl_sparse.csv.gz
- [ ] crystal_desc_canvas_aug30.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv
- [ ] delaney-processed.csv

- [ ] gdb1k.sdf
- [ ] nci_2.csv.gz
chembl_5thresh.csv.gz                           gdb1k.sdf.csv                                   nci_unique.csv
chembl_sparse.csv.gz                            medium_muv.csv.gz                               pcba.csv.gz
construct_pdbbind_df.py                         membrane_permeability.sdf                       pdbbind_core_5_df.pkl.gz
crystal_desc_canvas_aug30.csv                   membrane_permeability.sdf.csv                   rev8020split_desc.csv
delaney-processed.csv                           mini_muv.csv.gz                                 tox21.csv.gz
desc_canvas_aug30.csv                           muv.csv.gz
flash_points.csv.gz                             nci_1.csv.gz

**Comment by nd-02110114** [comment]
I checked wheather files are in AWS or not.

- [ ] Positive Modulators Summary_ 918.TUC _ v1.xlsx -> Colab Tutorials 09 use
- [x] chembl_5thresh.csv.gz
- [x] chembl_sparse.csv.gz
- [x] crystal_desc_canvas_aug30.csv -> But, examples/bace uses
- [x] delaney-processed.csv
- [x] desc_canvas_aug30.csv -> But, examples/bace uses
- [ ] flash_points.csv.gz
- [ ] gdb1k.sdf -> Colab Tutorials 10 use
- [ ] gdb1k.sdf.csv -> no use
- [x] medium_muv.csv.gz
- [ ] membrane_permeability.sdf -> examples/membrain_permeability use
- [ ] membrane_permeability.sdf.csv ->no use
- [ ] mini_muv.csv.gz -> tests/test_reload use
- [x] muv.csv.gz -> But, examples/low_data uses
- [x] nci_1.csv.gz
- [x] nci_2.csv.gz
- [x] nci_unique.csv -> But, examples/low_data uses
- [x] pcba.csv.gz
- [ ] pdbbind_core_5_df.pkl.gz -> no use
- [ ] rev8020split_desc.csv -> examples/bace uses
- [x] tox21.csv.gz

Datasets which are not uploaded on AWS are related to old Colab Tutorials and examples.
So, I think it is better to remove them after

**Comment by rbharath** [comment]
Thanks for putting together this list! This is really useful :)

I agree that once #1792 is fully merged in we should get rid of the `datasets/` directory. We could perhaps add a page to the docs listing the datasets that are available on AWS and how to download them so people don't rely on the `datasets/` directory

**Comment by nd-02110114** [comment]
Update

- [ ] Positive Modulators Summary_ 918.TUC _ v1.xlsx -> Colab Tutorials 09 use
- [ ] flash_points.csv.gz -> upload 
- [ ] gdb1k.sdf -> Colab Tutorials 10 use
- [ ] gdb1k.sdf.csv -> no use
- [ ] membrane_permeability.sdf -> examples/membrain_permeability use
- [ ] membrane_permeability.sdf.csv ->no use
- [ ] mini_muv.csv.gz -> tests/test_reload use
- [ ] pdbbind_core_5_df.pkl.gz -> upload
- [ ] rev8020split_desc.csv -> examples/bace uses
