### ISSUE TITLE
Add DiskDataset data format write-up to docs

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1900]
It would be very useful to have a write-up in the docs that describes `DiskDataset`'s data format in writing to disk. This would be useful for newcomers and for people maintaining DeepChem codebases so they have a specification to build on.

**Comment by SauravMaheshkar** [comment]
@rbharath, isn't this already described [here](https://deepchem.readthedocs.io/en/latest/api_reference/data.html#deepchem.data.DiskDataset) ?

**Comment by rbharath** [comment]
Yes you're right! Will close this
