### ISSUE TITLE
Adding Type Annotations to DeepChem

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1901]
The `mypy` toolchain for static annotations has matured a good bit and become a powerful tool for improving the quality of Python codebases. I propose that we start adding type annotations onto the DeepChem codebase. This would involve the following steps:

- Adding a checker to travis for type correctness
- Incrementally adding type signatures to the DeepChem codebase over a series of pull requests.

Luckily, `mypy` is incremental so we don't need to make a transition all at once. I think the best way might be to pick isolated modules or components of DeepChem, add annotations, then proceed outwards as we gain confidence.

**Comment by peastman** [comment]
Sounds like a great idea!

**Comment by rbharath** [comment]
Closing as completed since I think we've mostly fleshed out the type annotations
