### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by vsomnath** [deepchem/deepchem#1905]
I had to install DeepChem from source on a different machine today, and there were two issues with the installation & testing I faced:

1. The command `pytest -m "not slow"` tries to run tests in `contrib/` as well, and throws errors like `No module named 'deepchem.models.tensorflow_models'` and `No module named 'deepchem.models.autoencoder_models'`. This should be replaced with `pytest -m "not slow" deepchem`.

2.  Running `bash scripts/install_deepchem_conda.sh deepchem` raises a compatibility issue in versions of two packages with the following message: `ERROR: tensorboard 2.2.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.`  Running `pip install grpcio==1.24.3` to address compatibility does not create any failing tests though.

**Comment by peastman** [comment]
> The command pytest -m "not slow" tries to run tests in contrib/ as well

That command runs all tests in your current directory, and all directories inside it.  If you're at the top level of the repository when you run it, the will include contrib. If you cd into the deepchem directory first it should only run the real tests.

**Comment by rbharath** [comment]
Perhaps we should remove `tensorboard` from `install_deepchem_conda.sh`? We don't use it in any of the examples or tutorials at present.

**Comment by vsomnath** [comment]
> That command runs all tests in your current directory, and all directories inside it. If you're at the top level of the repository when you run it, the will include contrib. If you cd into the deepchem directory first it should only run the real tests.

Yes indeed. `.travis.yml` uses `pytest -m "not slow" --cov=deepchem deepchem`

> Perhaps we should remove tensorboard from install_deepchem_conda.sh? We don't use it in any of the examples or tutorials at present.

The `install_deepchem_conda.sh` has no explicit reference to `tensorboard`. Maybe `tensorflow` itself has a problem? - Strange issue though.

**Comment by peastman** [comment]
I'm pretty sure tensorboard automatically gets installed with tensorflow.

**Comment by nd-02110114** [comment]
PR #1904 fixed  the issue 1. 
Test comamnd is `pytest -m "not slow" deepchem` in latest master readme.

**Comment by vsomnath** [comment]
Perfect, thanks!
