### ISSUE TITLE
Allow PyTorch Models Under Import Guard

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1907]
This issue is related to #1879 which suggests making TensorFlow an optional dependency under an import guard. The natural successor to this is that we should consider allowing PyTorch models into DeepChem under an import guard.

Large portions of the molecular machine learning community have switched to PyTorch as their default framework. There's now a growing body of PyTorch open source code for different models researchers have put out. Allowing PyTorch into this repo will enable us to offer more useful models for developers.

Technically, I propose we do this under the same type of import guard as proposed in #1879. What  do folks think?

CC @peastman @vsomnath @lilleswing @seyonechithrananda @nd-02110114

**Comment by vsomnath** [comment]
Does this become a nested `try-except` block? - Something like:

```
try:
    import tensorflow as tf
    # tf specific imports
except ImportError:
      try:
          import torch
          # torch specific imports
      except ImportError:
          logger.warning("Neither TensorFlow nor PyTorch found")
```

**Comment by rbharath** [comment]
Yep, that's the idea! The only tweak would be that the imports aren't nested.

```
try:
    import tensorflow as tf
    # tf specific imports
except ImportError:
    logger.warning("TensorFlow is not available. TensorFlow dependent modules will not be imported.")
try:
    import torch
    # torch specific imports
except ImportError:
      logger.warning("PyTorch is not available. PyTorch dependent modules will not be imported")

**Comment by nd-02110114** [comment]
I seem this issue is resolved, so I closed.
