### ISSUE TITLE
KerasModel weights are not initialized until fit() is called

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1911]
Here's an interesting code snippet

```
import deepchem as dc
import numpy as np
from rdkit import Chem

y = np.array([[1]])
smiles = ['C']
mols = [Chem.MolFromSmiles(smile) for smile in smiles]
featurizer = dc.feat.ConvMolFeaturizer()
X = featurizer.featurize(mols)
dataset = dc.data.NumpyDataset(X, y, ids=smiles)
# set up dummy new model first
model = dc.models.GraphConvModel(n_tasks = 1,
                                 graph_conv_layers = [128, 128],
                                 dense_layer_size = 512,
                                 dropout = 0,
                                 mode = 'regression',
                                 learning_rate = 0.001,
                                 batch_size = 8,
                                 model_dir = "model")
model._ensure_built()
init_weights = model.model.get_weights()
print("len(model.model.get_weights())")
print(len(model.model.get_weights()))
model.fit(dataset)
print("len(model.model.get_weights())")
print(len(model.model.get_weights()))
```
This snippet returns output
```
(deepchem) bharath@Bharaths-MBP /tmp % python test.py 
model._built
True
len(model.model.get_weights())
0
len(model.model.get_weights())
100
```
It's clear that model weights aren't getting initalized until `fit()` is getting called. I think this makes some DeepChem pretraining behavior behave non-intuitively and might explain what's happening in #1910 

CC @peastman @vsomnath @cpfpengfei

**Comment by vsomnath** [comment]
I think its because `model(inputs)` needs to be called before the weights are initialized (I remember reading this somewhere but need to find the source). This happens first in the `self._create_training_ops(batch)` line in `keras_model.py`.

**Comment by peastman** [comment]
This is part of the design of Keras.  It allows a model to leave the shapes of its inputs undefined, which means some weight matrices also have unknown sizes.  When you call `fit()`, that's when it figures out what the inputs look like.

**Comment by rbharath** [comment]
Good point! This seems more feature than bug so going to close out this issue.
