### ISSUE TITLE
AWS S3 for DeepChem

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#1933]
After speaking to the infrastructure expert at Materials Project, here are some notes I gathered about running an AWS S3 service for an open source project.

- By estimating the storage and traffic requirements, we can ask for promotional credits on an annual basis that may cover the costs: https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/
- The owner of the bucket should make an Identity and Access Management (IAM) role to give read/write access to other specific AWS accounts.
- All files should be gzipped, because costs accrue based on the file sizes being stored and transferred.
- Enable "lifecycle management policy," which automatically downgrades objects that aren't accessed frequently and decreases costs.
- AWS includes automatic versioning of datasets.
- Key advantage of AWS S3 is ability to scale if needed.

**Comment by rbharath** [comment]
Thanks for the notes! These are great. Setting up IAM roles for access to the DeepChem S3 bucket sounds very doable. Applying for AWS credits would also be very useful.

**Comment by rbharath** [comment]
Closing this old issue since we aren't working on this
