### ISSUE TITLE
Adding PyTorch Models and Layers

### ISSUE THREAD

**Issue by vsomnath** [deepchem/deepchem#1936]
I am going to open a PR for setting up equivalents of our models in PyTorch, under `dc.models.pytorch_models`, with suitable import guards (#1907). 

Before starting the PR, I just wanted to open a general discussion for more feedback and comments. A couple of initial comments:

- I plan to start with the graph models and associated layers, then move to ChemCeption and Transformer based models. These models are more widely used, and also allow us to extend transfer learning support to them. 

- The API of the layers / model should mostly remain unchanged since the main workhorse across `tf.keras` and `torch` is a `model(inputs)` statement. There will be some rewrite around the optimizers since they accept parameters as an initialization argument unlike `tf.keras`. 

I wil keep updating the list with any interesting workarounds or issues as I run into them. I am sure there are functions which behave differently between `tf.keras` and `torch` (an example would be the lack of a `gather_nd` function in `torch`), and one would need wrapper functions to make arguments similar.

@rbharath @peastman @seyonechithrananda @nd-02110114

**Comment by peastman** [comment]
I think we need to decide on an important question: is our goal to have a collection of TensorFlow models *and also* a collection of PyTorch models?  Or is our goal to have one single collection of models, some of which happen to be implemented in TensorFlow and others in PyTorch?

If the latter (which is what I would vote for), we should avoid duplication between them.

**Comment by vsomnath** [comment]
For the more used models, like `GraphConv` or `Transformers`, it would be useful to have it across both, but for the others, TensorFlow should be more than enough.

**Comment by peastman** [comment]
What would be the benefit of having two different versions of GraphConvModel?

**Comment by rbharath** [comment]
@vsomnath Great, thanks for taking this on! I think this will be really valuable infrastructure to have in place. As an extra addition, I'd suggest ChemProp as another PyTorch model to add. Their work seems to be getting a lot of attention recently.

I think if there are different features that the PyTorch implementation will have (like better transfer learning support), it might be worth a duplicate implementation. I know there are a lot of graph conv variants available in PyTorch, so it would be really interesting to have some of the variants in PyTorch Geometric that we don't currently support added. I'd also generally prefer avoiding duplication when possible, but perhaps some duplication is unavoidable as needed PyTorch infrastructure.

**Comment by peastman** [comment]
> I know there are a lot of graph conv variants available in PyTorch, so it would be really interesting to have some of the variants in PyTorch Geometric that we don't currently support added.

If it's a different variant that we don't currently support then that's a different model.  No problem with that.  What I wouldn't want to see is separate TensorFlowGraphConvModel and PyTorchGraphConvModel classes that implement identical graph structures and differ only in how they're implemented.

**Comment by vsomnath** [comment]
Thanks, I'll include the ChemProp model too!

Coming back to variants spread out across TensorFlow and PyTorch, it would be kinda strange to have the newer variants in PyTorch, and the original 4-5 graph models in TensorFlow. Anyone wanting to run them would have to install both PyTorch and TensorFlow for example. To retain backward compatability, it would be useful to keep the existing graph model implementations. But having all graph models in PyTorch would be easier from an installation and usage perspective. Whether the old ones get phased out or not can be decided later.

**Comment by peastman** [comment]
As much as possible, the user shouldn't need to know or care what library a particular model is implemented with.  Nothing appears in their APIs that's TensorFlow specific.  A user should be able to just create a GraphConvModel and have it work.

This does mean users will need to install both TensorFlow and PyTorch, or else some models won't be available.  But that's unavoidable if we choose to use both of them.

We might consider having the import guards provide stub classes that just throw an exception.  First define a class

```python
class TensorFlowStub(object):
  def __init__(self, *args, **kwargs):
    raise ModuleNotFoundError("The class '%s' cannot be used because TensorFlow is not installed" % type(self).__name__)
```

And then we could write

```python
try:
  import tensorflow
  from deepchem.models.graph_models import GraphConvModel
except:
  class GraphConvModel(TensorFlowStub):
    pass
```

**Comment by rbharath** [comment]
I like the idea of stub classes! It helps pin down what class needs TF/PyTorch and makes it easier on users.

+1 for the idea that a user shouldn't need to know what library a model is implemented in. It would be really nice if we had a unifying DeepChem aesthetic that meant users could get pretty far (until they want to implement their own models) without knowing the underlying infrastructure for a particular model class.

My two cents is that we're likely to have both TensorFlow and PyTorch support long-term. I think there are differences in the frameworks which mean that somethings will just be easier in the one or the other.

**Comment by rbharath** [comment]
Going to close this old issue for cleanup
