### ISSUE TITLE
Docs Build is Broken

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1946]
It looks like something about the latest build has stopped docs from rendering the docstrings. For example, https://deepchem.readthedocs.io/en/latest/transformers.html doesn't have any class doc strings. I'm not sure yet what's happening here but will take a look.

**Comment by rbharath** [comment]
Looking at the readthedocs build output (https://readthedocs.org/api/v2/build/11377758.txt), it looks like this is a `cloudpickle` issue. I'm seeing warnings of the form

```
WARNING: autodoc: failed to import class 'feat.ElementPropertyFingerprint' from module 'deepchem'; the following exception was raised:
cannot import name 'CloudPickler' from 'cloudpickle.cloudpickle' (/home/docs/checkouts/readthedocs.org/user_builds/deepchem/envs/latest/lib/python3.7/site-packages/cloudpickle/cloudpickle.py)
```

**Comment by ncfrey** [comment]
The `'CloudPickler' from 'cloudpickle.cloudpickle'` error is the same one I was seeing. In the latest version of `cloudpickle` they changed the import to `CloudPickler from cloudpickle`. Maybe the CloudPickle update broke Sphinx as well?

**Comment by rbharath** [comment]
I think the issue is we need to pin the cloud pickle version in https://github.com/deepchem/deepchem/blob/master/docs/requirements.txt. This is the file sphinx uses to install deepchem dependencies. Let me put up a PR...

**Comment by rbharath** [comment]
Ok, looks like docs are back up! Pinning the version did the trick. Going to go ahead and close this issue.
