### ISSUE TITLE
Add dc.models.optimizers to docs/

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1953]
We don't currently have a documentation page for `dc.models.optimizers`. We should add this to the docs.

**Comment by SauravMaheshkar** [comment]
@rbharath, Isn't this already implemented [here](https://deepchem.readthedocs.io/en/latest/api_reference/models.html#optimizers)?

**Comment by rbharath** [comment]
Yes, you're right! Closing this issue
