### ISSUE TITLE
Add pysmiles support for loading

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1969]
Now that deepchem-nightly pip is mostly functional, we face the challenge that deepchem is very functionality limited on a pip install. The reason is that there look to be severe structural issues that mean rdkit can't get a pip install in the foreseeable future (http://rdkit.blogspot.com/2019/11/why-rdkit-isnt-available-on-pypi.html).

I propose that we use [pysmiles](https://pypi.org/project/pysmiles/) as a back-up loader if rdkit isn't available. Most of our featurizers depend on RDKit, but a user will be able to us models like `TextCNNModel` which don't depend on RDKit featurizers to still do some work.

**Comment by peastman** [comment]
This makes me nervous.  Having two different libraries that can be used to perform the same function is a great way to get inconsistencies in behavior.  At the very least we would need to run the full test suite twice on every PR, once with rdkit and once with pysmiles.  But even then it would be really easy for bugs to get missed.  If all the developers had rdkit installed, they would never encounter problems that come up when using pysmiles instead.

**Comment by rbharath** [comment]
rdkit is now on pip so going to close
