### ISSUE TITLE
Inconsistent method definitions

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1974]
As I've started trying to add type annotations, it's uncovered that we've been inconsistent about how we override methods.  A subclass is supposed to always override methods in a way that's consistent with the parent class.  If you don't know the exact type of an object, you should be able to invoke methods using the API defined by the superclass and it should work for any subclass.

For example, Model defines the method `fit(self, dataset, nb_epoch=10, batch_size=50, **kwargs)`.  KerasModel overrides that method and adds a lot of other arguments.  That's ok: the parent class allows for arbitrary extra keyword arguments.  But those first three arguments that are explicitly specified need to be the same, and they aren't.  For KerasModel, the third argument is `max_checkpoints_to_keep` instead of `batch_size`, and in fact there's no `batch_size` argument at all.  That is set by the constructor.  The same is true for `predict()`, and I'll likely encounter others as I go along.

Somehow we need to make these consistent.  I suggest removing the `batch_size` argument from the base class methods.   The default implementations could either rely on `kwargs` to get the batch size, or we could just get rid of the default implementations altogether.  At present we only have three subclasses of Model: KerasModel, SklearnModel, and SingletaskToMultitask.  All three of them already provide their own implementations of `fit()` and `predict()`, and in fact none of them takes a `batch_size` argument, which is a pretty strong indication that it shouldn't be there in the base class.

**Comment by rbharath** [comment]
Removing `batch_size` sounds good to me!

**Comment by peastman** [comment]
This is fixed by #1979.
