### ISSUE TITLE
When is deepchem 2.4 coming out?  

### ISSUE THREAD

**Issue by Laksh1997** [deepchem/deepchem#1975]
When is deepchem 2.4 coming out? I am very keen to use the new tensorflow version in it.

**Comment by rbharath** [comment]
Hopefully soon! There are still some critical improvements we need to merge in before we can make the cut. In the meanwhile, I recommend using the new `deepchem-nightly` package:

```
pip install tensorflow
pip install deepchem-nightly
```

DeepChem nightly is pretty stable so you should be able to start working with the nightly build. We hope to have the formal cut out in the not too distant future.

**Comment by nd-02110114** [comment]
Currently, we don't publish 2.4.0, but you try the new DeepChem using the following command!

```bash
pip install tensorflow==2.2
pip install --pre deepchem
```
