### ISSUE TITLE
Improving Printing

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1977]
Printing is still currently slow for large `DiskDataset`s due to this line https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L326

For ease of reference, we find the shape of `X` by `self.X.shape` which walks the entire `X` through `itershards`. To speed this up, we should cache the shapes of `X, y, w` while we're creating the dataset. We should also clean up `DiskDataset.get_shape` https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L1808 which currently walks the full dataset as well.

**Comment by puaykaipoh** [comment]
Sir,

This [line](https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L326) you have specified is pointing to a comment. Perhaps, the [link](https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L326) is outdated?

Instead, are you referring to [this](https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L2470) (with regards to the slow printing?)

Also, you mentioned that we should also clean up [DiskDataset.get_shape](https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L1808), but it is currently pointing to an empty line.

Instead, are you referring to [this](https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L2565).

Also `DiskDataset.get_shape` seems like it is iterating over all the shards now. Does that mean this is issue is resolved

**Comment by rbharath** [comment]
Closing this old issue since prints are now fast thanks to metadata
