### ISSUE TITLE
Remove Energy features for Transformers

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1978]
At present, the transformer classes have some limited support for gradients. The assumption is that a dataset is structured so that its first task is an energy. `NormalizationTransformer` in particular has a `untransform_grad` function that undoes the normalization for the purposes of computing the gradient of this energy.

This is an interesting feature, but one that's very limited. We initially designed it for atomic convolutions, so the model makes assumptions about its input shape. 

I propose that we deprecate these features. I don't believe anyone is using them at present. While in the future we may want to add support for energy functions like ANI, we will need a cleaner design for handling gradients in general.

**Comment by alanatransrights** [comment]
Mind if I take this on?

**Comment by rbharath** [comment]
You're welcome to! I'd recommend checking out https://deepchem.readthedocs.io/en/latest/coding.html. It has a set of coding conventions that we follow for the codebase that might be useful as you're getting up to sspeed

**Comment by kavalerov** [comment]
I think this issue can be closed now as https://github.com/deepchem/deepchem/pull/2166 is merged?

**Comment by rbharath** [comment]
Yes good catch! Closing
