### ISSUE TITLE
Consider Transformations as Hyperparameters

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#199]
Transformations are currently applied once to a dataset. It should be possibly to apply/un-apply transformations during hyperparameter optimization (to test the effect of whether some transformation is fruitful or not). Adding a `Transformer.untransform(dataset)` would do the trick I think.

**Comment by evanfeinberg** [comment]
+1, this makes a lot of sense!

**Comment by rbharath** [comment]
Transformers are now functional thanks to #262 (that is, the transformation does not destroy the original dataset). It should now be quite straightforward to do hyperparameter search over transformations (since the original dataset is preserved and never overwritten).

**Comment by rbharath** [comment]
Going to close since I think this hasn't proven an issue.
