### ISSUE TITLE
Crystal Featurizer

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#2005]
I am writing a `CrystalFeaturizer` class that will be analogous to `dc.feat.base_classes.MolecularFeaturizer`. 

`MolecularFeaturizer` assumes that inputs are either SMILES strings or RDKit molecule objects. Currently, the only support we have for featurizing crystals requires pymatgen composition strings or structure dictionaries. I can assume these types of inputs and make `CrystalFeaturizer` specific to them. Alternatively, I'm wondering if there is interest in other types of crystal representations, or even more generally for systems with periodic boundary conditions, like 3D crystal structures of small molecules. In that case I will leave `CrystalFeaturizer` more abstract.

Any thoughts @rbharath @nd-02110114 ?

**Comment by rbharath** [comment]
I think there would definitely be interest in other types of crystal representations or general periodic boundary conditions! My two cents is abstract superclasses defining APIs tend to have a long lifetime (it took nearly 4-5 years for us to fix the original `Featurizer` superclass), so good to make something future facing :)

**Comment by ncfrey** [comment]
Ok great, with that in mind I think I'll err towards the class being more abstract and letting specific subclasses handle inputs.

**Comment by nd-02110114** [comment]
I have one question. What a kind of interface do you want to share by using `CrystalFeaturizer` ?

In my thinking, it is better to make the subclass on each datapoint type.


```python

# implement the abstract featurizer for each datapoint type
class CompostionFeaturizer(Featurizer):
    # some implementation

class StructureFeaturizer(Featurizer):
    # some implementation


# implement the concrete featurizing algorithm
class ElementPropertyFingerprint(CompostionFeaturizer):
    # some implementation

class SineCoulombMatrix(StructureFeaturizer):
    # some implementation

class StructureGraphFeaturizer(StructureFeaturizer):
    # some implementation
```

**Comment by ncfrey** [comment]
@nd-02110114 I think that's a good idea. It consolidates how pymatgen inputs are processed into two abstract classes and helps avoid confusion about pymatgen objects versus their dictionary and string representations. This way, the current featurizers will be supported with base classes and new base classes can be added if needed.

**Comment by nd-02110114** [comment]
We implemented the basic crystal featurizers, so I closed!
