### ISSUE TITLE
Generalize CSVLoader

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2009]
At present, our `CSVLoader` class is molecule specific. It assumes that there's a SMILES field present. We should change this class over so it can load arbitrary types of CSV data and not just CSVs with molecules in them. I think the new capability of MolecularFeaturizer to directly featurize from SMILES strings could simplify this code as well

**Comment by nd-02110114** [comment]
I seem this issue was fixed!

**Comment by rbharath** [comment]
Yes, I think you're right!
