### ISSUE TITLE
Improving our Keras Layer unit tests

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2014]
Our unit tests for our keras layers are a little sparse right now. Here are some suggestions from fchollet on how to write good Keras layer unit tests: https://twitter.com/fchollet/status/1283201263518093312

We should upgrade our unit test suite to add these types of tests

**Comment by peastman** [comment]
> That said, it's generally good practice to write unit tests for your layers, that test basic assumptions: number of weights, number of trainable weights, output shape, test that the layer produces the same output after deserialization, etc. It enables you to catch common mistakes

The part about serialization is a good idea.  When we were using TensorGraph, we had a test module just to check that every layer could be pickled properly.  We should do something similar to make sure our Keras layers can be saved and restored.

**Comment by rbharath** [comment]
One related question is that we should figure out if we're affected by this bug: https://www.reddit.com/r/MachineLearning/comments/hrawam/d_theres_a_flawbug_in_tensorflow_thats_preventing/

**Comment by shak360** [comment]
I'd like to approach this if everyone's OK with that. Is the location of the tests in question located here: https://github.com/deepchem/deepchem/blob/master/deepchem/models/tests/test_kerasmodel.py and https://github.com/deepchem/deepchem/blob/master/deepchem/models/tests/test_layers.py ?

**Comment by rbharath** [comment]
@shak360 You're absolutely welcome to take this on :). I think the biggest thing we'd want is to add serialization and de-serialization tests as @peastman suggests above to make sure our layers can be saved and restored properly.

**Comment by rbharath** [comment]
Closing this since Keras is now mostly in maintenance mode and new development has shifted to PyTorch
