### ISSUE TITLE
Inconsistent API for create_dataset in ImageLoader

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2016]
The `ImageLoader` definition of `create_dataset` has a type signature that's inconsistent with that of the other `DataLoader` classes. I propose that we fix this type signature to match the other loaders. (This came up when I was trying to add type signatures in #2010)

**Comment by peastman** [comment]
Agreed!

**Comment by rbharath** [comment]
I believe this was fixed in #2010
