### ISSUE TITLE
Cosine similarity calculation

### ISSUE THREAD

**Issue by gvisani** [deepchem/deepchem#2022]
I believe the function computing cosine similarity, found in layers.py, does not compute the denominator correctly if y is a matrix instead of a single vector:

** Current code **

```
def _cosine_dist(x, y):
  denom = (backend.sqrt(backend.sum(tf.square(x)) * backend.sum(tf.square(y))) + backend.epsilon())
  return backend.dot(x, tf.transpose(y)) / denom
```

** Possible fix **

```
def _cosine_dist(x, y):
  denom = backend.sqrt(backend.dot(tf.reshape(backend.sum(tf.square(x), axis=1), (-1, 1)), tf.reshape(backend.sum(tf.square(y), axis=1), (1, -1))) + backend.epsilon())
  
  return tf.math.divide(backend.dot(x, tf.transpose(y)), denom)
```

The denominator should not be equal for every computed similarity value. It should be specific for each pair of vectors for which we wish to compute similarity.

Edit by @rbharath: Fixed formatting on code samples

**Comment by rbharath** [comment]
@gvisani Thanks for the bugcatch! I think the original function was written assuming `x` and `y` were single vectors and not batched correctly. We should add some unit tests, improve the documentation, and incorporate the above fix.
