### ISSUE TITLE
Google colab session crashes for an unknown reason while featurizing csv data.

### ISSUE THREAD

**Issue by Gokul-11-byte** [deepchem/deepchem#2030]
Session crashes while running following code ( dataset_file is of 120 KB ), But works fine with a different csv dataset.

`import deepchem as dc
featurizer = dc.feat.CircularFingerprint(size=1024)

loader = dc.data.CSVLoader(
      tasks=["Standard Value"], smiles_field="Smiles",
      featurizer=featurizer)
dataset = loader.featurize(dataset_file)`

`Loading raw samples now.
shard_size: 8192
About to start loading CSV from covid_2020.csv
Loading shard 1 of size 8192.
Featurizing sample 0`

**Comment by rbharath** [comment]
Are there lots of logging statements coming out? This could potentially be linked to the logging bug from https://github.com/deepchem/deepchem/issues/2023

**Comment by Gokul-11-byte** [comment]
@rbharath 
There is not much of loggings, just the few output lines I mentioned. And then it crashes.
But it just work fine for another dataset of 90 KB.

**Comment by Gokul-11-byte** [comment]
@rbharath 
Link to my data: https://drive.google.com/file/d/1-8b8R3G0UgoMKP6RhEeF16Pk6VD-S9uB/view?usp=sharing
Link to my colab: https://colab.research.google.com/drive/1dzdNP8ttTbZiWQqnJP-AFCjXoBRt4yro?usp=sharing

**Comment by rbharath** [comment]
Closing this old issue for cleanup. Let me know if this is still an issue
