### ISSUE TITLE
Common data class for crystals?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2043]
Now that we're adding materials support more seriously, should we create a standard crystal data class? We're working towards unifying our molecule graph classes (https://github.com/deepchem/deepchem/issues/1942). It would be nice to do the same for crystals as well so we can support models like crystal graph convolutions and lattice graph convolutions.

One mathematical challenge here is that the right datastructure to represent a crystal is probably a multigraph and not a graph (since for a lattice element, there can be periodic wrap-around connections which means there can be two different connections between nodes)

CC @nd-02110114 @ncfrey

**Comment by nd-02110114** [comment]
You mean we need the new dataclass like CrystalGraphData....?

My answer of this question is No. I think the GraphData class can be used from any graph convolution models like molecule graph convolutions (ex: MPNN, Schnet), crystal graph convolutions. I'm not familiar with lattice graph convolutions, but the GraphData class may be used by adding some attributes.

My new PR #2045 modified the MoleculeGraphData -> GraphData, then my CGCNN featurizer return GraphData instance.

**Comment by ncfrey** [comment]
I think my opinion for now is that we still don't have a good sense for what the best graph-like representation for crystalline materials is, so it might be best to stick with something abstract like the `GraphData` class @nd-02110114 is working on. Then the featurizers can generate whatever is necessary for specific architectures.

**Comment by rbharath** [comment]
+1 for the new generic `GraphData` class :). Really nice cleanup @nd-02110114. I'm going to close this issue since the CGCNN featurizer shows we can use `GraphData` more generally
