### ISSUE TITLE
Saving GraphConvModel

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2049]
Hi, I'm training my dataset using GraphConvModel. Followed the "Deepchem/04_Introduction_to_Graph_Convolutions.ipynb" tutorial. However after I trained the model, I use "model.save("saved_model/my_model", it shows an error: "TypeError: save() takes 1 positional argument but 2 were given".

Could anyone please help me resolve this issue? I would appreciate that!

ps. this is the code I'm using:

```
> model = GraphConvModel(n_tasks=len(task), mode="classification", batch_size=50)
> num_epochs = 20
> losses = []
> for i in range(num_epochs):
>   loss = model.fit(train_dataset, nb_epoch=1)
>   print("Epoch %d loss: %f" % (i, loss))
>   losses.append(loss)
> 
> !mkdir -p saved_model
> model.save("saved_model/my_model")
```

**Comment by chstem** [comment]
Deepchem automatically creates checkpoints during training in `model_dir`, which you can reload later. To explicitly create a checkpoint you can call ` model.save_checkpoint()`. These checkpoints can be restored with `model.restore()`.

But for GraphConvModel there are currently some problems, see #2013 and #1943.

`model.save()` exists, but is not implemented. I this actually used somewhere?https://github.com/deepchem/deepchem/blob/1b7d83bd671053a2398b325d3158814cd99d8f11/deepchem/models/models.py#L123-L128

**Comment by hjzhang1018** [comment]
> Deepchem automatically creates checkpoints during training in `model_dir`, which you can reload later. To explicitly create a checkpoint you can call ` model.save_checkpoint()`. These checkpoints can be restored with `model.restore()`.
> 
> But for GraphConvModel there are currently some problems, see #2013 and #1943.
> 
> `model.save()` exists, but is not implemented. I this actually used somewhere?
> 
> https://github.com/deepchem/deepchem/blob/1b7d83bd671053a2398b325d3158814cd99d8f11/deepchem/models/models.py#L123-L128



> Deepchem automatically creates checkpoints during training in `model_dir`, which you can reload later. To explicitly create a checkpoint you can call ` model.save_checkpoint()`. These checkpoints can be restored with `model.restore()`.
> 
> But for GraphConvModel there are currently some problems, see #2013 and #1943.
> 
> `model.save()` exists, but is not implemented. I this actually used somewhere?
> 
> https://github.com/deepchem/deepchem/blob/1b7d83bd671053a2398b325d3158814cd99d8f11/deepchem/models/models.py#L123-L128

Thank you chstem! I've been struggling with this problem for a day. Now I use checkpoint and restore(), it worked :)
