### ISSUE TITLE
Adding Reaction Fingerprint Support

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2050]
I just came across the really cool https://github.com/rxn4chemistry/rxnfp library by @pschwllr. Our current support for reaction fingerprints is very limited (we have a bit of demo code but nothing actually fleshed out). It would be really cool to wrap `rxnfp` fingerprints into a DeepChem featurizer to facilitate experimentation.

CC @seyonechithrananda @pschwllr

**Comment by seyonechithrananda** [comment]
Totally agree that this would be really awesome if we can wrap the rxnfp as a featurizer under deepchem. I'm happy to help facilitate integrating it if @pschwllr is interested in adding it to the library.

**Comment by pschwllr** [comment]
Yes, would be great to see `rxnfp` included as reaction fingerprint into deepchem. 

What would you need from the `rxnfp` side? Is there an existing deepchem reaction featurizer? How do you handle external dependencies? `rxnfp` could be installed with `pip install rxnfp`

**Comment by rbharath** [comment]
Awesome :). On the DeepChem side, I think we should add a proper `ReactionFeaturizer` abstract class to define an abstract API, and then a `RxnfpFeatuizer` class to wrap `rxnfp`. I think we can add `rxnfp` as a soft requirement (https://deepchem.readthedocs.io/en/latest/requirements.html). A pip install would be great.

Out support for reaction featurization is basically nonexistent for now! We have some very limited support, but no clean APIs or documentation, so we have a clean slate to make a good API

**Comment by seyonechithrananda** [comment]
To add on to Bharath's point, can we add the `rxnfp` featurizer and SMILES tokenizer to the current set of featurizers under `dc.feat`, similar to `deepchem.feat.SmilesToSeq`? Since we don't have a base class for reaction featurizers yet, we can start by adding the implementation in under a HuggingFace + rxnfp import guard.

**Comment by seyonechithrananda** [comment]
PR #2113 works on integrating RXNFP tokenizers into 'dc.feat'

**Comment by seyonechithrananda** [comment]
Closing this issue, as #2113 implements SmilesTokenizer. There will likely be follow-up PRs with methods for featuring large scale molecular datasets, which will reference this issue.
