### ISSUE TITLE
SDFLoader doesn't handle zipped/gzipped files

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2067]
~The `dc.utils.save.load_sdf_files` operates entirely in memory. This means that loading a large .sdf file with `SDFLoader` operates entirely in memory and isn't scalable to very large SDF files.~ `SDFLoader` also doesn't have a good way to handle zipped/gzipped files

**Comment by rbharath** [comment]
#2068 fixed the memory issue, but it would be nice to handle zipped/gzipped sdf files. I'm going to mark this open for contribution

**Comment by BusinessFawn** [comment]
Do you have an example of what you'd like the input zip to look like? I assume a zip file of either .sdf or csv files?

I'd be happy to take a look but I'd like to make sure I'm working towards the correct behavior.

**Comment by rbharath** [comment]
@BusinessFawn Thanks for volunteering here :). I'm thinking just a gzipped/zipped `.sdf` file would be the desired input to support. One of the sample SDF test files used by `SDFLoader` but just gzipped/zipped should be a good test case

**Comment by murilo-cunha** [comment]
@BusinessFawn are there any updates on this? I'd like to help on this!

**Comment by NinadBhat** [comment]
Hi, @rbharath. I have submitted a PR. Kindly have a look if you have time for it.
