### ISSUE TITLE
Tutorial part 16: no module found

### ISSUE THREAD

**Issue by Draghohmmar** [deepchem/deepchem#2069]
Tutorial part 16 needs updating.
This is error I get when running on the newest version of DeepChem.
![image](https://user-images.githubusercontent.com/47124775/89406605-53e4a580-d715-11ea-9d80-e4b1db305931.png)

**Comment by rbharath** [comment]
Ah you're right! We need to clean this up in an update pass of the tutorials

**Comment by rbharath** [comment]
This tutorial needs to be updated to work with the most recent DeepChem

**Comment by Draghohmmar** [comment]
Would also be nice to see something more chemistry relevant. Hence my question on gitter regarding graph to molecule conversion.

**Comment by vishal-purohit** [comment]
I would like to resolve this issue

**Comment by peastman** [comment]
We're in the middle of doing a complete pass through all the tutorials, fixing them up.  See #2112.  This issue was already fixed in #2116, so I'm going to close it.
