### ISSUE TITLE
ClippingTransform y-transform broken

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#207]
The y-transformation for the `ClippingTransformer` doesn't work for the `y` transformation (uses variable `trunc` which isn't even defined).

**Comment by rbharath** [comment]
As a general comment, this would be a great PR for a new developer who's interested in getting involved with DeepChem. Fix should be limited to `ClippingTransformers` in file `deepchem/trans/transformers.py` Adding support for a `y` transformation and adding a test example to `deepchem/trans/tests/test_transformers.py` would be enough.

PRs welcome!

**Comment by Agent007** [comment]
I was looking at this, but I notice this issue had already been fixed in https://github.com/deepchem/deepchem/commit/ecfdcc5d420fbbd94053522e78f211fca3387b61

**Comment by rbharath** [comment]
@Agent007 Thanks for pointing this out! Going to go ahead and close issue
