### ISSUE TITLE
deepchem.nn not found

### ISSUE THREAD

**Issue by hssinejihene** [deepchem/deepchem#2070]
I've tried to use dc.nn.SequentialSupportGraph(n_feat) but I got an error saying "module 'deepchem' has no attribute 'nn'"
![erreur](https://user-images.githubusercontent.com/66692983/89432051-8e136e80-d738-11ea-9eb0-3ae5fb8d63e4.PNG)

**Comment by rbharath** [comment]
The low-data contribution code is unfortunately for an old version of DeepChem (1.3) and not supported in the current master branch. This is one of my open TODO projects to support it with DeepChem HEAD. I hope to get to this in the next few months. In the meanwhile, I'd suggest trying to install DeepChem 1.3 if possible (this might be tricky since it involves a lot of old packages)

**Comment by danielvlla** [comment]
Hi @rbharath any progress on this please? Can I assist you with the implementation in any way?

**Comment by rbharath** [comment]
Just responded to your other comment :). Yes, absolutely! Would you be able to attend one of the DeepChem developer calls? (Weekly Friday at 3pm PST). We can coordinate needed work for the implementation. If you're interested, shoot me a DM on gitter (https://gitter.im/deepchem/Lobby) with your preferred email and I'll add you to the invite

**Comment by Wissemmbarki** [comment]
I've tried to use dc.nn.SequentialSupportGraph(n_feat) but I got an error saying "module 'deepchem' has no attribute 'nn'

**Comment by rbharath** [comment]
@Wissemmbarki The code for the low-data models is not currently supported in DeepChem. I will try to see if we can find a student developer who wants to take the porting on as a project since there are repeated asks

**Comment by rbharath** [comment]
I've just added the porting to the model wishlist #2680

**Comment by Wissemmbarki** [comment]
@rbharath I thank for your answer
but i have another question hope you can help me :
if i install deepchem version 1.3 can i work with model .nn to apply model IterRefLSTMEmbedding

**Comment by Wissemmbarki** [comment]
@rbharathJe vous remercie pour votre réponse
mais j'ai une autre question j'espère que vous pourrez m'aider :
si j'installe deepchem version 1.3 puis-je travailler avec le modèle .nn pour appliquer le modèle IterRefLSTMEmbedding

**Comment by rbharath** [comment]
DeepChem 1.3 is very old and depends on old TensorFlow and other software that may be hard to run. We also didn't start docker builds until later unfortunately. You are welcome to give it a try and see if you can get it running!
