### ISSUE TITLE
Error while installing deepchem in google colab

### ISSUE THREAD

**Issue by Gokul-11-byte** [deepchem/deepchem#2073]
Installation was working fine till yesterday.

Installing code:

%tensorflow_version 1.x
!curl -Lo deepchem_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import deepchem_installer
%time deepchem_installer.install(version='2.3.0')

TypeError: install() got an unexpected keyword argument 'version'

**Comment by hjzhang1018** [comment]
same here.

**Comment by nd-02110114** [comment]
Now, we are updating the tutorial notebooks for the latest DeepChem version.
You can try the new command!

```bash
!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
!pip install --pre deepchem
import deepchem
deepchem.__version__
```

**Comment by Gokul-11-byte** [comment]
Thanks.
It worked.
