### ISSUE TITLE
Creating a Tokenizer Class for Sequence Models

### ISSUE THREAD

**Issue by seyonechithrananda** [deepchem/deepchem#2076]
A couple of weeks back, Bharath raised the following issue on adding support for the rxnfp Reaction Fingerprint tokenizer (#2050). DeepChem currently doesn't have an API for tokenizers, so I decided to start off a new issue to discuss how to best approach creating one!

Current ideas are:
- Creating an abstract Tokenizer superclass for custom tokenizers to use.
- Calling BertTokenzier as a superclass as done by the SMILES tokenizer in rxnfp
- open to better ideas!

Relevant resources:

RXNFP - chemical reaction fingerprints by  @pschwllr [(link)](https://github.com/rxn4chemistry/rxnfp)
SMILES tokenizer in the rxnfp library: [(link)](https://github.com/rxn4chemistry/rxnfp/blob/master/rxnfp/tokenization.py#L36)
Reverie Labs: Transformers for Practical Drug Discovery [(link)](https://blog.reverielabs.com/transformers-for-drug-discovery/)

Thanks!

CC @rbharath @pschwllr @peastman

**Comment by rbharath** [comment]
Closing since we have more tokenizer infrastructure now implemented as part of the Grover work
