### ISSUE TITLE
When to release version 2.4.0？

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#2080]
When to release version 2.4.0, I am looking forward to the release of tensorflow2. There is a lot of work to be done in the near future. I hope deepchem can help me more

**Comment by rbharath** [comment]
Hopefully soon! Tbh, I'm the critical blocker here. There's a few last bugs that need to be fixed, but I've unfortunately been too busy to hit for the last couple weeks. If anyone has bandwidth to hit one of the critical blockers from https://github.com/deepchem/deepchem/issues/1883#issuecomment-665991033, we can move faster. It's definitely on my TODO list and will get there once a couple things are off my plate

**Comment by rbharath** [comment]
Closing this since we've made the 2.4.0 cut
