### ISSUE TITLE
Precision Metric Value Error

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2087]
Hi I'm using GraphConvModel to train my dataset following the deepchem tutorial. After training I tried to use multiple metrics to evaluate my model performance. Here is my code. I got numbers for ROC-AUC score and recall score but an error for precision score. It said "ValueError: Target is multilabel-indicator but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted', 'samples']".
What I don't understand is why I could get result for recall score but not for precision score. Could someone help me with this issue? That would be greatly appreciated!
```
import numpy as np

metric_rocauc = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)
metric_recall = dc.metrics.Metric(dc.metrics.recall_score)
metric_precision = dc.metrics.Metric(dc.metrics.precision_score)

print("Evaluating Model")
rocauc_scores = model.evaluate(train_dataset, [metric_rocauc])
print("Trainig ROC-AUC Scores: %f" % (rocauc_scores["mean-roc_auc_score"]))
recall_scores = model.evaluate(train_dataset, [metric_recall])
print("Training Recall Scores: %f" % (recall_scores["recall_score"]))
precision_scores = model.evaluate(train_dataset, [metric_precision])
print("Training Precision Scores: %f" % (precision_scores["precision_score"]))
```

**Comment by rbharath** [comment]
I believe you're trying to evaluate a multiclass dataset using precision and are running into the issue details in this scikit-learn stackoverflow issue: https://stackoverflow.com/questions/52269187/facing-valueerror-target-is-multiclass-but-average-binary

This is a bit of a hack, but I think you can fix it by wrapping the metric:

```
def precision_average(y_test, y_pred):
  return precision_score(y_test, y_pred, average='micro') # or any other average you like. See sklearn docs
metric_precision_average = dc.metrics.Metric(precision_average, mode="classification")
model.evaluate(train_dataset, [metric_precision_average])
```

Can you give this a try adn see if it works for you?

**Comment by hjzhang1018** [comment]
@rbharath Thank you! My dataset is single task. I tried but still report an error "Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets". However I was able to get f1_score, recall_score and roc_auc_score using the following code. I guess I could calculate the precision_score manually according to the formula!

```
import numpy as np
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score

metric_rocauc = dc.metrics.Metric(dc.metrics.roc_auc_score)
metric_recall = dc.metrics.Metric(dc.metrics.recall_score)
metric_f1 = dc.metrics.Metric(dc.metrics.f1_score)

print("Evaluating Model")
train_scores = model.evaluate(train_dataset, [metric_rocauc, metric_recall, metric_f1], transformers)
print("Trainig ROC-AUC Scores: %f" % (train_scores["roc_auc_score"]))
print("Training Recall Scores: %f" % (train_scores["recall_score"]))
print("Training F1 Scores: %f" % (train_scores["f1_score"]))
```

**Comment by rbharath** [comment]
Hmm, ok so this might be a bug. Would it be possible for you to give me a small reproducing code sample? Ideally on a small synthetic dataset. It would really help me to debug if I can reproduce your error locally :)
