### ISSUE TITLE
The feature of edge of a molecular?

### ISSUE THREAD

**Issue by swpper** [deepchem/deepchem#2092]
Hi, I am learning how to build my dataset just like "ESOL". But I don`t know what the three features of edge_attr they are, how it is designed, or where can I know about it? Could you give me some advice? 

one data in ESOL:
`Data(edge_attr=[26, 3], edge_index=[2, 26], smiles="CCOc1ccc(NC(=O)C)cc1", x=[13, 9], y=[1, 1])`

**Comment by swpper** [comment]
I find two papers about it, maybe I can figure out by myself.

**Comment by rbharath** [comment]
@swpper Would you mind clarifying a bit more here? Is this the raw ESOL data and not the processed version from MoleculeNet?

**Comment by swpper** [comment]
@rbharath You are right. The data I showed above is the processed version from MoleculeNet not the  raw ESOL data. I ignored to read the raw ESOL data since the raw data of other dataset is hard to directly read. Thank you very much!
