### ISSUE TITLE
deepchem.io certificate issue

### ISSUE THREAD

**Issue by jdagdelen** [deepchem/deepchem#2114]
Seems like there may be an issue with the certificate on your site. My browser was producing a security warning.

**Comment by rbharath** [comment]
Yes, our apologies for this! (See https://forum.deepchem.io/t/pardon-our-dust/222). We're in the middle of moving our website over to new hosting infrastructure so we'll likely have some issues for the next couple weeks. I'm working on this at present

**Comment by jdagdelen** [comment]
No worries! Just wanted to let you know in case you weren’t aware.

**Comment by rbharath** [comment]
I believe I've just fixed the website! Could you take a look and verify the certificate looks good for you?

**Comment by jdagdelen** [comment]
Looks great!

**Comment by rbharath** [comment]
Awesome :)
