### ISSUE TITLE
Switching Nameservers for DeepChem.io; website may go down

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2120]
I'm raising this issue as a notice that I'm working on changing the DNS for deepchem.io (as part of our backend infrastructure change). This may result in the DeepChem.io website going down for a while. I'm actively working on this and hope to be able to fix any outages shortly

**Comment by rbharath** [comment]
I believe I've now fixed the SSL/TLS certificate issue and transferred the DNS over to our own AWS infrastructure from Stanford's. It will take some time for these changes to propagate.

@peastman @seyonechithrananda @nd-02110114 @ncfrey @lilleswing @miaecle I've also upgraded the DeepChem developer IAM settings so you have access to the DNS and certificate management for DeepChem (Route 53 / Certificate Manager). This means that in the future if there are issues with the DeepChem website or certificates, you should be able to go in and fix the issue yourselves if I'm not reachable for some reason :)

**Comment by rbharath** [comment]
Think I spoke too soon. Still trying to figure out the CNAME. I've also added Cloudfront access for the developer IAM roles so anyone interested is welcome to take a look if they're curious.

Hopefully will be able to debug this soon

**Comment by rbharath** [comment]
Writing some notes here to document the AWS infrastructure. This should be migrated to the docs in a future PR:

DeepChem's website infrastructure is all managed on AWS through different AWS services. All DeepChem developers have access to these services through the deepchem-developers IAM role. At present, @rbharath is the only admin with access to the IAM role, but longer term we should migrate this so other folks have access to the roles.

There are two core deepchem S3 buckets:
- deepchemdata: This bucket hosts the deepchem.io website, MoleculeNet datasets, pre-featurized datasets, and pretrained models. This bucket is set up to host a static website (at https://deepchemdata.s3-us-west-1.amazonaws.com/index.html). 
- deepchemforum: This bucket hosts backups for the forums. The bucket is private for security reasons. The forums themselves are hosted on a digital ocean instance that only @rbharath currently has access to. Longer term, we should migrate the forums onto AWS so all DeepChem developers can access the forums. The forums themselves are a discord instance. The forums upload their backups to this S3 bucket once a day. If the forums crash, they can be restored from the backups in this bucket

DeepChem also makes use of some other AWS infrastructure:

- Route 53: DNS for the deepchem.io website is handled by Route 53. The "hosted zone" deepchem.io holds all DNS information for the website. 
- Certificate Manager: The AWS certificate manager issues the SSL/TLS certificate for the *.deepchem.io and deepchem.io domains. (Our recent certificate issues were due to these certificates expiring)
- Cloudfront: We make use of a cloudfront distribution to serve our static website. The cloudfront distribution connects to the certificate in Certificate Manager and uses the deepchemdata bucket as the origin domain. We set CNAME for www.deepchem.io and deepchem.io

Non AWS resources:
- GoDaddy: deepchem.io is registered with GoDaddy. If you change the name servers in Route 53, you will need to update the GoDaddy record. At present, only @rbharath has this access
- Digital Ocean: The forums are hosted on a digital ocean instance


As a final comment, I've set up a lot of this infrastructure myself as a beginner to AWS devops. If you're a professional who has suggestions on how this could be done better, please chime in with suggestions!

**Comment by rbharath** [comment]
I think I've debugged the setup and the website should now be working with correct certificates and everything. Could folks take a look to verify that everything looks good?

**Comment by anand-bhat** [comment]
http and https versions of www and non www deepchem.io resolve and display correctly in Chrome. This is on a machine in Australia with no previously cached DNS entries

**Comment by rbharath** [comment]
Great to hear it seems to have propagated!

**Comment by nd-02110114** [comment]
I seem that deepchem.io website looks good! I really appreciate cleaning up infrastructure of DeepChem 🎉 

Just one suggestion is that I think it is better to move all website data to a new directory in S3.  Currently, all website data (deepchemdata/index.html, deepchemdata/about.html, deepchemdata/assets, ....) are in the root directory of deepchemdata. I think this situation is not good considering deployment using CI. I think we should create a new directory (deepchemdata/website) and move all website data to it.

After moving all data, I will restart to update deepchem.io.

**Comment by rbharath** [comment]
Moving the website data to `deepchemdata/website` could be a bit of a project because of the way pages are served from S3 buckets configured as websites. The documentation assumes there's a `index.html` in the top level bucket. I think we still could shift the website data to `deepchemdata/website`, but it would require a few steps of work and some debugging. Here's a rough sketch of what would be needed

- The static website configuration of the S3 bucket would have to shift its default from `index.html` to `website/index.html`
- The cloudfront distribution would have to have its default serving page moved from `index.html` to `website/index.html`
- We'd need to update the deepchemio repo to serve into the `deepchemdata/website` repo
- Our website hosting doesn't have mirroring or the like, so making these changes would mean the website briefly becomes inaccessible. If there's a bug we'd have to announce the downtime on Twitter

Given the extra work, I think this may not be worth the effort. That said, I think we should find ways to improve the ergonomics of upgrading the infrastructure since it shouldn't be this complex to do a directory restructuring. I'm not a AWS expert unfortunately, so there may be a simple way to do all this I'm missing

**Comment by peastman** [comment]
Would it make sense to have the website be its own bucket?  (I know even less about AWS than you.  Just wondering if that would solve the problem.)

**Comment by rbharath** [comment]
Good question! I think tentatively it wouldn't. The main reason is that the other `deepchemdata/` subfolders host MoleculeNet data and featurized datasets and trained models which would also need to be publicly hosted. I think we'd end up then with 2 buckets that then have to be configured as static websites and maintained which would add extra maintenance burden.

**Comment by nd-02110114** [comment]
Thanks for your attentive comments. I could understand how hard it is to move the website data. However, I wonder why deepchem.io is hosting by AWS. I seem that many DeepChem members are not familiar with AWS, so i think it is better to host the deepchem.io website using GithubPages. 

There are some reasons.
- We are more familiar with GitHub compared with AWS. 
  - It is easy to manage access authorizations or the custom domain
  - Well documents (See: [custom domain introduction](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site))
- No deploy scripts
- No cost (Free)

**Comment by rbharath** [comment]
@nd-02110114 Good suggestion! The answer for why we're on AWS is that when we put up the website a few years ago, hosting a static website on S3 was the easiest way to get a website out there. Now that Github pages is available, I'd be very open to us exploring transitioning the website to Github pages.

It's also worth noting that we'd still need to maintain the current AWS buckets to hold MoleculeNet datasets/pretrained-models and forum backups. But we could potentially use Github pages to remove the other AWS infra

**Comment by nd-02110114** [comment]
I think the most troublesome part of DeepChem AWS infra is the part only related to website (deepchem.io) like Route 53, Cloudfront. So, I think the migration from AWS to GithubPages will reduce our maintenance costs. 

I'm looking into how to manage custom domain, SSL/TLS certificate, CNAME and so on with GitHubPages. If migration is no problem, I will try to start with this migration in next week. If you want to know somethings about GitHubPages, please teach me freely. I try to search!

**Comment by rbharath** [comment]
@nd-02110114 Yep, go for it! If you think Github Pages will be simpler and easier for us to maintain and cut costs sounds like a good tradeoff :). I'm unfortunately not experienced at Github Pages so I'm not sure I can be of much help yet, but I'll try to do some research myself over the next week to see if I can chip in.

**Comment by ncfrey** [comment]
@nd-02110114 @rbharath +1 on the GitHub pages suggestion. I use pages for my own personal website and I really like it. It's easy to use and scale up.

**Comment by seyonechithrananda** [comment]
@rbharath +1 for me on Github pages as well, it was really easy to set it up using a .github.io domain and then route it to my own personal domain for websites.

**Comment by rbharath** [comment]
Closing since we are now on github pages
