### ISSUE TITLE
Indentation errors in deepchem/contrib/tensorflow_models/robust_multitask.py

### ISSUE THREAD

**Issue by ghost** [deepchem/deepchem#2129]
There are indentation error in deepchem/contrib/tensorflow_models/robust_multitask.py
![Screenshot from 2020-08-30 09-46-45](https://user-images.githubusercontent.com/26171922/91651102-dd359080-eaa5-11ea-81d2-4e7c900cddb6.png)

**Comment by vishal-purohit** [comment]
I would like to take up this issue

**Comment by rbharath** [comment]
@vishal-purohit You'd be very welcome to! Please go for it :)

**Comment by rbharath** [comment]
contrib is not maintained so going to close
