### ISSUE TITLE
Graphconvo Transfer Learning

### ISSUE THREAD

**Issue by RRHHQ** [deepchem/deepchem#2130]
Hi I'm trying to build a transfer learning model using chemical graph as input but I haven't been able to achieve this. Anyone know if there Is any samples codes or useful method/class available for transfer learning?

**Comment by rbharath** [comment]
Check out this cool paper from a group at stanford on pretraining on graph neural networks (https://arxiv.org/pdf/1905.12265.pdf). The authors have a nice Github repo up as well https://github.com/snap-stanford/pretrain-gnns. I'd love to see us support this type of pretraining in DeepChem, but we don't have the infrastructure yet!

**Comment by RRHHQ** [comment]
@rbharath Thanks a lot! I'll check it out.
