### ISSUE TITLE
Support for DGL Modeling

### ISSUE THREAD

**Issue by mufeili** [deepchem/deepchem#2131]
Hi DeepChem team,

This is Mufei from the [DGL](https://github.com/dmlc/dgl) team. I've also spent some time developing [DGL-LifeSci](https://github.com/awslabs/dgl-lifesci) -- a DGL-based package for working with graphs in chemistry and biology. It seems that DeepChem has started supporting DGL-based modeling with PyTorch (e.g. #2089 by @nd-02110114 ), which is rather exciting! I've had some chats with @rbharath before about contributing to this effort. Below are some observations & proposals and I'd like to know your thoughts.

Compared with pure PyTorch-based modeling, DGL-based modeling additionally requires:
- Converting graph data into DGL's data structure `DGLGraph` and storing node/edge features in `DGLGraph.ndata` and `DGLGraph.edata`
- Using APIs like `DGLGraph.update_all` for invoking message passing over graphs in NN modules

For the first point, DeepChem employs [`GraphData`](https://github.com/deepchem/deepchem/blob/master/deepchem/feat/graph_data.py) as an intermediate graph representation across different frameworks (DGL, PyTorch Geometric, etc.). It allows graph creation from a COO format along with pre-processed features and exposes a `to_dgl_graph` API for converting a `GraphData` instance into a `DGLGraph` instance. For the second point, DeepChem implements DGL-based PyTorch models under `deepchem/deepchem/models/torch_models`.

For a better support of DGL-based modeling and more generally, graph-based modeling, there are several possible points:
- Support for APIs like `from_dgl_graph` and `from_pyg_graph`, which can be helpful for users familiar with DGL/PyG before.
- A simple interface for custom dataset. This can be something like a variant of [CSVLoader](https://github.com/deepchem/deepchem/blob/master/deepchem/data/data_loader.py), which directly constructs a graph dataset from files of a standard data format like `CSV`. It allows users to specify the type of graph to construct as well as the way to featurize their nodes/edges. DGL-LifeSci's [MoleculeCSVDataset](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/data/csv_dataset.py#L19) can be an example for this.
- Functions for constructing standard types of graphs (molecular graphs, complete graphs, KNN graphs, distance-based graphs) from raw data like SMILES strings. While graph creation from a COO format maximizes the flexibility, it can be convenient to have such functions for users who only want to try existing modeling approaches on their own datasets. I think the design of [Protein Graph Library](https://github.com/a-r-j/graphein) follows a similar idea. 
- Support for heterogeneous graphs, i.e. graphs of typed nodes and edges. I have the impression that DeepChem is mainly for molecular property prediction and a bit protein-ligand binding affinity prediction, so maybe this is less an issue. However, this can still be helpful even for molecular property prediction when one wants to combine information from different graph structures. [Molecule Attention Transformer](https://github.com/ardigen/MAT) is an example for this.
- Examples for model training and evaluation on MoleculeNet
- Additionally, DGL-LifeSci has implemented some graph neural networks [here](https://github.com/awslabs/dgl-lifesci/tree/master/python/dgllife/model) and I'd like to know if you are open to directly import them in DeepChem.

**Comment by nd-02110114** [comment]
Thanks for your comments! These comments are really helpful for us. 

The following comments are my personal opinion. 

> Support for APIs like from_dgl_graph and from_pyg_graph, which can be helpful for users familiar with DGL/PyG before.

I agree. Before doing this, we need to refactor the present DeepChem's graph models using GraphData class. I will work for this refactoring in this month. I seem the priority is high.

> A simple interface for custom dataset. This can be something like a variant of CSVLoader, which directly constructs a graph dataset from files of a standard data format like CSV. It allows users to specify the type of graph to construct as well as the way to featurize their nodes/edges. DGL-LifeSci's MoleculeCSVDataset can be an example for this.

> Functions for constructing standard types of graphs (molecular graphs, complete graphs, KNN graphs, distance-based graphs) from raw data like SMILES strings. While graph creation from a COO format maximizes the flexibility, it can be convenient to have such functions for users who only want to try existing modeling approaches on their own datasets. I think the design of Protein Graph Library follows a similar idea.

I think these feature can be achieved by refactoring the [GraphData](https://github.com/deepchem/deepchem/blob/master/deepchem/feat/graph_data.py) and the [featurizer](https://github.com/deepchem/deepchem/pull/2109/files#diff-4444ec7d194cb12202277c4ead0e013e) which is implemented for molecules. This makes our graph model support more general, so I will definitely try to implement. (I like the design of Protein Graph Library, so I will imitate the API design) I seem the priority is intermediate.

> Support for heterogeneous graphs, i.e. graphs of typed nodes and edges. I have the impression that DeepChem is mainly for molecular property prediction and a bit protein-ligand binding affinity prediction, so maybe this is less an issue. However, this can still be helpful even for molecular property prediction when one wants to combine information from different graph structures. Molecule Attention Transformer is an example for this.

To be honest, I also seem that this feature is basically out of scope. But, I'm interested in Molecule Attention Transformer. If we have a time, we will try to support. I seem the priority is low.

> Examples for model training and evaluation on MoleculeNet

This is a working progress and highest priority task. Currently, I'm checking whether the model is working well with GPU or a large dataset. After finishing, I will add more details to deepchem docs.

> Additionally, DGL-LifeSci has implemented some graph neural networks here and I'd like to know if you are open to directly import them in DeepChem.

I seem this is open. But, currently, it is impossible to use DGL-LifeSci models with no modification.
How about @rbharath?

**Comment by rbharath** [comment]
> This is Mufei from the [DGL](https://github.com/dmlc/dgl) team. I've also spent some time developing [DGL-LifeSci](https://github.com/awslabs/dgl-lifesci) -- a DGL-based package for working with graphs in chemistry and biology. It seems that DeepChem has started supporting DGL-based modeling with PyTorch (e.g. #2089 by @nd-02110114 ), which is rather exciting! I've had some chats with @rbharath before about contributing to this effort. Below are some observations & proposals and I'd like to know your thoughts.

Great to see you on here @mufeili! I'm excited to see us improve DGL support/integration moving forward :)

> For a better support of DGL-based modeling and more generally, graph-based modeling, there are several possible points:
> 
> * Support for APIs like `from_dgl_graph` and `from_pyg_graph`, which can be helpful for users familiar with DGL/PyG before.

+1 to this! @nd-02110114 has kindly taken the lead on our refactoring to use `GraphData` as a common substrate. Once that's merged in, we should be able to support more of DGL's APIs.

> * A simple interface for custom dataset. This can be something like a variant of [CSVLoader](https://github.com/deepchem/deepchem/blob/master/deepchem/data/data_loader.py), which directly constructs a graph dataset from files of a standard data format like `CSV`. It allows users to specify the type of graph to construct as well as the way to featurize their nodes/edges. DGL-LifeSci's [MoleculeCSVDataset](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/data/csv_dataset.py#L19) can be an example for this.

I think our current dataloader/featurizer pipeline would support these use cases right? Taking a look at `MoleculeCSVDataset`, I think the analog would be our `InMemoryLoader` https://deepchem.readthedocs.io/en/latest/dataloaders.html#inmemoryloader which allows for loading of data from Pandas dataframes as well. Is there any useful functionality that we're missing here?

> * Functions for constructing standard types of graphs (molecular graphs, complete graphs, KNN graphs, distance-based graphs) from raw data like SMILES strings. While graph creation from a COO format maximizes the flexibility, it can be convenient to have such functions for users who only want to try existing modeling approaches on their own datasets. I think the design of [Protein Graph Library](https://github.com/a-r-j/graphein) follows a similar idea.

+1 to this as well! Props to @nd-02110114 for taking the lead here as well :)

> * Support for heterogeneous graphs, i.e. graphs of typed nodes and edges. I have the impression that DeepChem is mainly for molecular property prediction and a bit protein-ligand binding affinity prediction, so maybe this is less an issue. However, this can still be helpful even for molecular property prediction when one wants to combine information from different graph structures. [Molecule Attention Transformer](https://github.com/ardigen/MAT) is an example for this.

We've definitely talked about getting Molecule Attention Transformer support in DeepChem! I'd love to see MAT and similar models supported :)

For more heterogenous graphs, I'm not sure. DeepChem's focus is on scientific deep learning applications. Is there a good scientific use case for heterogenous graphs beyond MAT? As @nd-02110114 noted above, this may be out of scope for us if there isn't a clear use case.

> * Examples for model training and evaluation on MoleculeNet

This is definitely on our priorities! @nd-02110114 is actively working on this already, and I'd love to see more MoleculeNet benchmarks for all DGL models be put up.

> * Additionally, DGL-LifeSci has implemented some graph neural networks [here](https://github.com/awslabs/dgl-lifesci/tree/master/python/dgllife/model) and I'd like to know if you are open to directly import them in DeepChem.

We'd be very opening to directly importing DGL-LifeSci's models in DeepChem! It might also be useful to write small wrapper classes wrapping DGL models in `TorchModel` for ease of benchmarking on MoleculeNet or interoperating with the rest of the DeepChem API. In general though, I'd love to see closer integration with DGL-LifeSci's models. We're both working on similar problems and better to join forces and bring more value to our community

**Comment by mufeili** [comment]
> Thanks for your comments! These comments are really helpful for us.
> 
> The following comments are my personal opinion.
> 
> > Support for APIs like from_dgl_graph and from_pyg_graph, which can be helpful for users familiar with DGL/PyG before.
> 
> I agree. Before doing this, we need to refactor the present DeepChem's graph models using GraphData class. I will work for this refactoring in this month. I seem the priority is high.
> 
> > A simple interface for custom dataset. This can be something like a variant of CSVLoader, which directly constructs a graph dataset from files of a standard data format like CSV. It allows users to specify the type of graph to construct as well as the way to featurize their nodes/edges. DGL-LifeSci's MoleculeCSVDataset can be an example for this.
> 
> > Functions for constructing standard types of graphs (molecular graphs, complete graphs, KNN graphs, distance-based graphs) from raw data like SMILES strings. While graph creation from a COO format maximizes the flexibility, it can be convenient to have such functions for users who only want to try existing modeling approaches on their own datasets. I think the design of Protein Graph Library follows a similar idea.
> 
> I think these feature can be achieved by refactoring the [GraphData](https://github.com/deepchem/deepchem/blob/master/deepchem/feat/graph_data.py) and the [featurizer](https://github.com/deepchem/deepchem/pull/2109/files#diff-4444ec7d194cb12202277c4ead0e013e) which is implemented for molecules. This makes our graph model support more general, so I will definitely try to implement. (I like the design of Protein Graph Library, so I will imitate the API design) I seem the priority is intermediate.
> 
> > Support for heterogeneous graphs, i.e. graphs of typed nodes and edges. I have the impression that DeepChem is mainly for molecular property prediction and a bit protein-ligand binding affinity prediction, so maybe this is less an issue. However, this can still be helpful even for molecular property prediction when one wants to combine information from different graph structures. Molecule Attention Transformer is an example for this.
> 
> To be honest, I also seem that this feature is basically out of scope. But, I'm interested in Molecule Attention Transformer. If we have a time, we will try to support. I seem the priority is low.
> 
> > Examples for model training and evaluation on MoleculeNet
> 
> This is a working progress and highest priority task. Currently, I'm checking whether the model is working well with GPU or a large dataset. After finishing, I will add more details to deepchem docs.
> 
> > Additionally, DGL-LifeSci has implemented some graph neural networks here and I'd like to know if you are open to directly import them in DeepChem.
> 
> I seem this is open. But, currently, it is impossible to use DGL-LifeSci models with no modification.
> How about @rbharath?

Great! Feel free if there is anything that I might help.

**Comment by mufeili** [comment]
> I think our current dataloader/featurizer pipeline would support these use cases right? Taking a look at MoleculeCSVDataset, I think the analog would be our InMemoryLoader https://deepchem.readthedocs.io/en/latest/dataloaders.html#inmemoryloader which allows for loading of data from Pandas dataframes as well. Is there any useful functionality that we're missing here?

Does `InMemoryLoader` allow constructing a graph dataset? Also it can be convenient to:
- Support common data pre-processing for modeling in GNNs (e.g. graph construction and featurization) via arguments
- Allow parallel processing for large datasets. For example, it can be time-consuming to pre-process a large dataset like PCBA in graph-based modeling.

> For more heterogenous graphs, I'm not sure. DeepChem's focus is on scientific deep learning applications. Is there a good scientific use case for heterogenous graphs beyond MAT? As @nd-02110114 noted above, this may be out of scope for us if there isn't a clear use case.

I agree that it's a low priority. Meanwhile, heterogeneous graphs can be helpful in the following use cases:
- **Protein-ligand binding affinity prediction.** For protein-ligand binding affinity prediction, it's been a popular approach to separately construct graphs for ligands, proteins/pockets and protein-ligand complexes. You can then have heterogeneous graphs of two node types (ligand & protein) and four edge types (ligand-ligand, protein->ligand, ligand->protein, protein-protein).
- **Interaction (link) prediction in biological networks and knowledge graphs.** This might be more related to bioinformatics so I'm not sure if it's within the scope of DeepChem. For biological networks or biomedical knowledge graphs, there can be a large number of node types (e.g. drugs, proteins, diseases) and edge types (drug-drug interaction, drug-protein interaction, protein-protein interaction, etc.). There seems to be an increasing interest in applying GNNs to proteins. With biological networks containing compounds and proteins, there can be more things to play with in modeling.

> Examples for model training and evaluation on MoleculeNet
This is definitely on our priorities! @nd-02110114 is actively working on this already, and I'd love to see more MoleculeNet benchmarks for all DGL models be put up.
> 
>Additionally, DGL-LifeSci has implemented some graph neural networks here and I'd like to know if you are open to directly import them in DeepChem.
We'd be very opening to directly importing DGL-LifeSci's models in DeepChem! It might also be useful to write small wrapper classes wrapping DGL models in TorchModel for ease of benchmarking on MoleculeNet or interoperating with the rest of the DeepChem API. In general though, I'd love to see closer integration with DGL-LifeSci's models. We're both working on similar problems and better to join forces and bring more value to our community

I totally agree and I'm glad to make contributions about these. It seems that @nd-02110114 is leading the effort. Any suggestions or proposals for these?

**Comment by rbharath** [comment]
Sorry for the slow response here @mufeili! Things have been a little crazy here with all the fires and everything and this slipped to the bottom of my inbox. Short answer, we would very much love to have any contributions you can make! Responses inline with more details


> > I think our current dataloader/featurizer pipeline would support these use cases right? Taking a look at MoleculeCSVDataset, I think the analog would be our InMemoryLoader https://deepchem.readthedocs.io/en/latest/dataloaders.html#inmemoryloader which allows for loading of data from Pandas dataframes as well. Is there any useful functionality that we're missing here?
> 
> Does `InMemoryLoader` allow constructing a graph dataset? Also it can be convenient to:
> 
> * Support common data pre-processing for modeling in GNNs (e.g. graph construction and featurization) via arguments
> * Allow parallel processing for large datasets. For example, it can be time-consuming to pre-process a large dataset like PCBA in graph-based modeling.
> 

DeepChem's dataset architecture is generic (graph datasets are simply stored within numpy object arrays either in memory or on disk in `.npy` files) so `InMemoryLoader` can generate graph datasets. Our usual flow would be something as follows (in pseudocode)

```
feat = dc.feat.SomeGraphFeaturizer(feat_args=...)
loader = dc.data.InMemoryLoader(feat)
dataset = loader.create_dataset(pandas_column_with_smiles)
```
You can pass in different arguments for featurization by changing the choice of featurizer or the constructor arguments for the featurizer. Parallelization of featurization is definitely a good use case! We have some limited support for parallelization with multiprocessing but it's something we need some more maturation in our codebase on.

> > For more heterogenous graphs, I'm not sure. DeepChem's focus is on scientific deep learning applications. Is there a good scientific use case for heterogenous graphs beyond MAT? As @nd-02110114 noted above, this may be out of scope for us if there isn't a clear use case.
> 
> I agree that it's a low priority. Meanwhile, heterogeneous graphs can be helpful in the following use cases:
> 
> * **Protein-ligand binding affinity prediction.** For protein-ligand binding affinity prediction, it's been a popular approach to separately construct graphs for ligands, proteins/pockets and protein-ligand complexes. You can then have heterogeneous graphs of two node types (ligand & protein) and four edge types (ligand-ligand, protein->ligand, ligand->protein, protein-protein).
> * **Interaction (link) prediction in biological networks and knowledge graphs.** This might be more related to bioinformatics so I'm not sure if it's within the scope of DeepChem. For biological networks or biomedical knowledge graphs, there can be a large number of node types (e.g. drugs, proteins, diseases) and edge types (drug-drug interaction, drug-protein interaction, protein-protein interaction, etc.). There seems to be an increasing interest in applying GNNs to proteins. With biological networks containing compounds and proteins, there can be more things to play with in modeling.
> 

These are really nice examples! I think I'm more sold on the idea of supporting heterogenous graphs. Are there any DGL datastructures/featurizers for heterogeneous graphs that we could leverage?


> > Examples for model training and evaluation on MoleculeNet
> > This is definitely on our priorities! @nd-02110114 is actively working on this already, and I'd love to see more MoleculeNet benchmarks for all DGL models be put up.
> > Additionally, DGL-LifeSci has implemented some graph neural networks here and I'd like to know if you are open to directly import them in DeepChem.
> > We'd be very opening to directly importing DGL-LifeSci's models in DeepChem! It might also be useful to write small wrapper classes wrapping DGL models in TorchModel for ease of benchmarking on MoleculeNet or interoperating with the rest of the DeepChem API. In general though, I'd love to see closer integration with DGL-LifeSci's models. We're both working on similar problems and better to join forces and bring more value to our community
> 
> I totally agree and I'm glad to make contributions about these. It seems that @nd-02110114 is leading the effort. Any suggestions or proposals?

As a suggestion for a starting point, it would be great to expose more DGL models within deepchem. I think doing this would be straightforward and would simply involve making a wrapper class (check out our [tutorial](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Creating%20Models%20With%20TensorFlow%20and%20PyTorch.ipynb) on making custom PyTorch models in DeepChem).  We could also use help on more systematic MoleculeNet benchmarking infrastructure. We have some basic hyperparameter tuning utilities, but these could use an upgrade to hit SOTA on MoleculeNet systematically.

In general, lots to do here, and any work you can contribute would be much appreciated! If you're interested, let me know if you'd be willing to attend one of the developer calls. It might be easiest to just discuss there :)

**Comment by nd-02110114** [comment]
Sorry for slow response :bowing_man:
Currently, I face the issues about crystal graph convolutional model built with DGL, so I'm a little busy for debugging it. (The detail issue is here https://github.com/deepchem/deepchem/issues/2160)

>I think doing this would be straightforward and would simply involve making a wrapper class (check out our tutorial on making custom PyTorch models in DeepChem).

Yes! I seem we just implement the wrapper model If the input graph for model is a bi-directed graph (graph made by `smile_to_bigraph` method). The following is sample codes.  (I can not check this code work correcly, but the main implementation flow is the following)

```python

from dgllife.model import MPNNPredictor

# 1st: Define the PyTorch model for fixing output dimension of DGL original model
class DGLMPNN(nn.Module):

  def __init__(self, n_tasks, n_classes, mode, ......):
    super(DGLMPNN, self).__init__()
    self.mode = mode
    self.n_tasks = n_tasks
    self.n_classes = n_classes

    if self.mode == 'regression':
      out = n_tasks
    else:
      out = n_tasks * n_classes
     self.mpnn = MPNNPredictor(n_tasks=out, .....)

  def forward(self, dgl_graph, node_feat, edge_feat):
    out = self.mpnn(dgl_graph, node_feat, edge_feat)
    if self.mode == 'regression':
      return out
    else:
      logits = out.view(-1, self.n_tasks, self.n_classes)
      # for n_tasks == 1 case
      logits = torch.squeeze(logits)
      proba = F.softmax(logits)
      return proba, logits

# 2nd: Define the model which inherits TorchModel
class DGLMPNNModel(TorchModel):

  def __init__(self, arg1, arg2, ...., kwargs):
    model = DGLMPNN(arg1, arg2, ...)
    if mode == "regression":
      loss: Loss = L2Loss()
      output_types = ['prediction']
    else:
      loss = SparseSoftmaxCrossEntropy()
      output_types = ['prediction', 'loss']
    super(DGLMPNNModel, self).__init__(model, loss=loss, output_types=output_types, **kwargs)

  def _prepare_batch(self, batch):
    # we override `_prepare_batch` to prepare for each model inputs
    inputs, labels, weights = batch
    
    # prepare for model inputs
    dgl_graphs = [graph.to_dgl_graph() for graph in inputs[0]]
    batch_graph = dgl.batch(dgl_graphs).to(self.device)
    node_feats = batch_graph.ndata['h'].pop()
    edge_feats = batch_graph.edata['edge_attr'].pop()

    # prepare for other data
    _, labels, weights = super(DGLMPNNModel, self)._prepare_batch(([], labels, weights))

    # 1st element is the model inputs
    return (batch_graph, node_feats, edge_feats), labels, weights
```

**Comment by mufeili** [comment]
> Sorry for the slow response here @mufeili! Things have been a little crazy here with all the fires and everything and this slipped to the bottom of my inbox. Short answer, we would very much love to have any contributions you can make! Responses inline with more details

No worries. I understand this is a difficult time, which is even worse with the fires.

> > > For more heterogenous graphs, I'm not sure. DeepChem's focus is on scientific deep learning applications. Is there a good scientific use case for heterogenous graphs beyond MAT? As @nd-02110114 noted above, this may be out of scope for us if there isn't a clear use case.
> > 
> > 
> > I agree that it's a low priority. Meanwhile, heterogeneous graphs can be helpful in the following use cases:
> > 
> > * **Protein-ligand binding affinity prediction.** For protein-ligand binding affinity prediction, it's been a popular approach to separately construct graphs for ligands, proteins/pockets and protein-ligand complexes. You can then have heterogeneous graphs of two node types (ligand & protein) and four edge types (ligand-ligand, protein->ligand, ligand->protein, protein-protein).
> > * **Interaction (link) prediction in biological networks and knowledge graphs.** This might be more related to bioinformatics so I'm not sure if it's within the scope of DeepChem. For biological networks or biomedical knowledge graphs, there can be a large number of node types (e.g. drugs, proteins, diseases) and edge types (drug-drug interaction, drug-protein interaction, protein-protein interaction, etc.). There seems to be an increasing interest in applying GNNs to proteins. With biological networks containing compounds and proteins, there can be more things to play with in modeling.
> 
> These are really nice examples! I think I'm more sold on the idea of supporting heterogenous graphs. Are there any DGL datastructures/featurizers for heterogeneous graphs that we could leverage?
> 

DGL's graph data structure `DGLGraph` naturally supports heterogeneous graphs. For featurization, it shall not be difficult to extend featurization for homogeneous graphs to featurization for heterogeneous graphs.

> In general, lots to do here, and any work you can contribute would be much appreciated! If you're interested, let me know if you'd be willing to attend one of the developer calls. It might be easiest to just discuss there :)

Do you have a developer call next week? I think I can make that.

**Comment by mufeili** [comment]
> Sorry for slow response 🙇‍♂️

No worries.

> > I think doing this would be straightforward and would simply involve making a wrapper class (check out our tutorial on making custom PyTorch models in DeepChem).
> 
> Yes! I seem we just implement the wrapper model If the input graph for model is a bi-directed graph (graph made by `smile_to_bigraph` method). The following is sample codes. (I can not check this code work correcly, but the main implementation flow is the following)
> 
> ```python
> from dgllife.model import MPNNPredictor
> 
> # 1st: Define the PyTorch model for fixing output dimension of DGL original model
> class DGLMPNN(nn.Module):
> 
>   def __init__(self, n_tasks, n_classes, mode, ......):
>     super(DGLMPNN, self).__init__()
>     self.mode = mode
>     self.n_tasks = n_tasks
>     self.n_classes = n_classes
> 
>     if self.mode == 'regression':
>       out = n_tasks
>     else:
>       out = n_tasks * n_classes
>      self.mpnn = MPNNPredictor(n_tasks=out, .....)
> 
>   def forward(self, dgl_graph, node_feat, edge_feat):
>     out = self.mpnn(dgl_graph, node_feat, edge_feat)
>     if self.mode == 'regression':
>       return out
>     else:
>       logits = out.view(-1, self.n_tasks, self.n_classes)
>       # for n_tasks == 1 case
>       logits = torch.squeeze(logits)
>       proba = F.softmax(logits)
>       return proba, logits
> 
> # 2nd: Define the model which inherits TorchModel
> class DGLMPNNModel(TorchModel):
> 
>   def __init__(self, arg1, arg2, ...., kwargs):
>     model = DGLMPNN(arg1, arg2, ...)
>     if mode == "regression":
>       loss: Loss = L2Loss()
>       output_types = ['prediction']
>     else:
>       loss = SparseSoftmaxCrossEntropy()
>       output_types = ['prediction', 'loss']
>     super(DGLMPNNModel, self).__init__(model, loss=loss, output_types=output_types, **kwargs)
> 
>   def _prepare_batch(self, batch):
>     # we override `_prepare_batch` to prepare for each model inputs
>     inputs, labels, weights = batch
>     
>     # prepare for model inputs
>     dgl_graphs = [graph.to_dgl_graph() for graph in inputs[0]]
>     batch_graph = dgl.batch(dgl_graphs).to(self.device)
>     node_feats = batch_graph.ndata['h'].pop()
>     edge_feats = batch_graph.edata['edge_attr'].pop()
> 
>     # prepare for other data
>     _, labels, weights = super(DGLMPNNModel, self)._prepare_batch(([], labels, weights))
> 
>     # 1st element is the model inputs
>     return (batch_graph, node_feats, edge_feats), labels, weights
> ```

Nice examples! Then this will be rather straightforward.

**Comment by rbharath** [comment]
@mufeili We have a developer call every Friday at 3pm PST :). You're welcome to join any (or all) of these calls. I believe you should already have a calendar invite, but let me know if you don't and I'll send you another one. Looking forward to the discussion!

**Comment by mufeili** [comment]
> @mufeili We have a developer call every Friday at 3pm PST :). You're welcome to join any (or all) of these calls. I believe you should already have a calendar invite, but let me know if you don't and I'll send you another one. Looking forward to the discussion!

I've already had a calendar invite. Thank you. I will attend it next week.

**Comment by nd-02110114** [comment]
I created some wrapper models using `dgl-lifesci` models and checked the performance.

dgl-lifesci wrapper model (I tested GATPredicator and MPNNPredicator)
https://colab.research.google.com/drive/1NWPXbnMMe8vsqouE60hBBF8ouXDIxgMM?usp=sharing

GATModel with PyG
https://colab.research.google.com/drive/1eF7WtiLbdTBafP7v1ge4Mvq6F3Y7zmIQ?usp=sharing


**dgl-lifesci**
Tox21
```
train score: {'roc_auc_score': 0.8182964145182753}
valid score: {'roc_auc_score': 0.7608185458553915}
test score: {'roc_auc_score': 0.7720624225036611}
```
FreeSolv
```
train score:  {'mae_score': 0.687180647485078}
valid score:  {'mae_score': 0.8194827916145285}
test score:  {'mae_score': 0.8635092074796723}
```

**PyG**

Tox21
```
train score:  {'roc_auc_score': 0.9956798740329166}
valid score:  {'roc_auc_score': 0.7156732094284761}
test score:  {'roc_auc_score': 0.7100899730333298}
```
FreeSolv
```
train score:  {'mae_score': 1.3438364587083647}
valid score:  {'mae_score': 1.390010379775363}
test score:  {'mae_score': 1.3078179993101786}
```

GATPredicator is greater than my GATModel with PyG! 
Maybe, `WeightedSumAndMax` pooling causes the difference.

**Comment by mufeili** [comment]
> I created some wrapper models using `dgl-lifesci` models and checked the performance.
> 
> dgl-lifesci wrapper model (I tested GATPredicator and MPNNPredicator)
> https://colab.research.google.com/drive/1NWPXbnMMe8vsqouE60hBBF8ouXDIxgMM?usp=sharing
> 
> GATModel with PyG
> https://colab.research.google.com/drive/1eF7WtiLbdTBafP7v1ge4Mvq6F3Y7zmIQ?usp=sharing
> 
> **dgl-lifesci**
> Tox21
> 
> ```
> train score: {'roc_auc_score': 0.8182964145182753}
> valid score: {'roc_auc_score': 0.7608185458553915}
> test score: {'roc_auc_score': 0.7720624225036611}
> ```
> 
> FreeSolv
> 
> ```
> train score:  {'mae_score': 0.687180647485078}
> valid score:  {'mae_score': 0.8194827916145285}
> test score:  {'mae_score': 0.8635092074796723}
> ```
> 
> **PyG**
> 
> Tox21
> 
> ```
> train score:  {'roc_auc_score': 0.9956798740329166}
> valid score:  {'roc_auc_score': 0.7156732094284761}
> test score:  {'roc_auc_score': 0.7100899730333298}
> ```
> 
> FreeSolv
> 
> ```
> train score:  {'mae_score': 1.3438364587083647}
> valid score:  {'mae_score': 1.390010379775363}
> test score:  {'mae_score': 1.3078179993101786}
> ```
> 
> GATPredicator is greater than my GATModel with PyG!
> 
> I think GATPredicator has some advantages, so these lead to the difference.
> 
> * `WeightedSumAndMax` pooling
> * Residual connection
> 
> And I seem PyG model is overfitting compared with GATPredicator.
> Residual connection avoid overfitting...?

Interesting. I haven't checked the Colab links and I assume you are performing a fair evaluation. It is possible that these two components make the difference, which can be verified by a careful ablation study.

**Comment by rbharath** [comment]
Closing as implemented
