### ISSUE TITLE
Typo breaking chirality in WeaveFeaturizer

### ISSUE THREAD

**Issue by cjgalvin** [deepchem/deepchem#2135]
Using nightly build `'2.4.0-rc1.dev'`

There is a typo on line 403 of `feat.graph_features.py`, in the definition of the function `bond_features`: 

`str(bond.GetStereo()), GraphConvCoonstants.possible_bond_stereo)`

should be

`str(bond.GetStereo()), GraphConvConstants.possible_bond_stereo)`

`Coonstants` --> `Constants`

**Comment by rbharath** [comment]
Ah you're right! Let me get a fix for this up

**Comment by rbharath** [comment]
The nightly build should be updated with the fix shortly (by tomorrow or later tonight). You can install this with `pip install --upgrade --pre deepchem`. Happy hacking!
