### ISSUE TITLE
update notebooks?

### ISSUE THREAD

**Issue by hainm** [deepchem/deepchem#214]
can you update the notebooks? None of them works for me.

Some have "ImportError: cannot import name 'DataFeaturizer'" error. Some have UnicodeError when pickling data. I am using py35. thanks.

**Comment by rbharath** [comment]
@hainm Unfortunately, the notebooks have all fallen out of date. The python scripts in the `examples/` directory are all maintained though. PR #206 changed `DataFeaturizer` to `DataLoader`, which accounts for the import errors, while py35 support is still an open issue #25.

I'm very open to accepting contributions for updates to the notebooks. It should be feasible to make the fixes by copying code over from the script examples.

**Comment by rbharath** [comment]
CC @evanfeinberg, @hainm 

After some thought, I'm thinking of just going ahead and removing the ipython notebooks from the repo. It's too hard to maintain the notebooks, since I can't just run them from the command-line to verify correctness when I make breaking changes to the repo.

There's some good content in the notebooks though, so it would be good to move these into python example scripts. I won't remove the notebooks until I have time to move this code over.

**Comment by rbharath** [comment]
The notebooks have now been moved into `examples/broken` to make it clear to newcomers that they don't work anymore. I'll probably delete the notebooks once I make python examples that duplicate all the behavior. Going to close this issue for now.

**Comment by rbharath** [comment]
After a lot of thought, I think I'm going to flip-flop on this and say we should renovate the notebooks. DeepChem is much more stable than it used to be, and I think we can get the notebooks working and keep them working now.

@lilleswing, @proteneer: Do you have any thoughts on how we can incorporate ipython notebooks into the test suite to make sure they don't break? Some of the notebooks might take a while to run, so maybe they should go on Jenkins?

**Comment by lilleswing** [comment]
Yeah if they take awhile we would have to run them on Jenkins. Something like this would work, people at Anacondacon said they did it from Bloomberg and Capital One.

http://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks

**Comment by peastman** [comment]
We do this in mdtraj.  Take a look at https://github.com/mdtraj/mdtraj/blob/master/examples/test_examples.py.

**Comment by rbharath** [comment]
I believe notebooks are now up to date and maintained via Jenkins so closing.
