### ISSUE TITLE
dc.molnet.load_delaney X,y, ids are not matched the true label

### ISSUE THREAD

**Issue by shenwanxiang** [deepchem/deepchem#2144]
Hi, I use deepchem 2.4.0-rc1.dev

I found a very big issue when I load the dataset:

It gives me a wrong y label for each X or smiles:

![image](https://user-images.githubusercontent.com/21102929/92195714-30da1c80-eea0-11ea-92c9-ec873e36d5dc.png)

![image](https://user-images.githubusercontent.com/21102929/92195721-37689400-eea0-11ea-86e5-c54a6f24cbfd.png)

**Comment by nd-02110114** [comment]
Most of `molnet_function` apply data transformation to the original dataset for training. In the case of ESOL dataset, we apply NormalizationTransformer.

https://github.com/deepchem/deepchem/blob/b1cac7b13bb1f60978602813bdaf51ed16be147e/deepchem/molnet/load_function/delaney_datasets.py#L114-L117

**Comment by shenwanxiang** [comment]
Oh, many thanks. I see. I found this issue when I try to train on these data, I found the rmse is decreased to 0.23. Thank you very much for the explanation.

How do you think the model peformance after applying a normalization transformation on y? Is this will help the model to improve their performance?

**Comment by nd-02110114** [comment]
I think the normalization transformation basically  improve the model performance, but depends on models. What is your model?

And, you passed the transformers to metrics functions or evaluate functions? 

```python
model.evaluate(test_dataset, [metric], transformers)
```

**Comment by shenwanxiang** [comment]
> evaluate

Thanks! I reversed the transfromation, and I found the RMSE value do have decreased a litte,
