### ISSUE TITLE
DeepChem Benchmark Collection

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#215]
Part of the goal for DeepChem has been curating and processing a collection of benchmark datasets from the literature. So far, we've curated:
- NCI60
- MUV
- Tox21
- PCBA (from http://arxiv.org/abs/1502.02072 and follow-up papers)

Will keep this thread open as a place to request new datasets, or possibly coordinate contribution of new benchmark datasets to deepchem.

**Comment by joegomes** [comment]
The atomization energies from the Quantum Machine dataset are currently in Deepchem.  IIRC, there is a multitask dataset containing other electronic properties for these molecules that can included in the dataset and benchmarked with DeepChem.  I could work on adding the full dataset and benchmarks sometime next week.

**Comment by lilleswing** [comment]
Can we declare this complete with the [MoleculeNet](https://arxiv.org/abs/1703.00564) release?

**Comment by rbharath** [comment]
Hah, yes, this has been hit by MoleculeNet. We are still revising MoleculeNet, but we can discuss in other threads if necessary.
