### ISSUE TITLE
tutorial 1 on colab: SpecifiedSplitter cannot be imported

### ISSUE THREAD

**Issue by wendongwangmpi** [deepchem/deepchem#2154]
Greetings, 
I am going through the tutorial on colab, and in the first one, the following cell on SpecifiedSplitter gives the following error. 

It does look like something is missing. 

Best wishes,
Wendong 

`from deepchem.splits.splitters import SpecifiedSplitter
current_dir=os.path.dirname(os.path.realpath('__file__'))
input_file=os.path.join(current_dir, 'user_specified_example.csv')

tasks=['log-solubility']
featurizer=dc.feat.CircularFingerprint(size=1024)
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles",featurizer=featurizer)
dataset=loader.featurize(input_file)

split_field='split'

splitter=SpecifiedSplitter(input_file,split_field)`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-30-dbee6c6d4c67> in <module>()
----> 1 from deepchem.splits.splitters import SpecifiedSplitter
      2 current_dir=os.path.dirname(os.path.realpath('__file__'))
      3 input_file=os.path.join(current_dir, 'user_specified_example.csv')
      4 
      5 tasks=['log-solubility']

ImportError: cannot import name 'SpecifiedSplitter'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by nd-02110114** [comment]
Thank you for reporting the issue! 
Currently, we don't support `SpecifiedSplitter`, so you can skip this section in Tutorial 01.
And, if you want to use the function of `SpecifiedSplitter`, you could use `IndiceSplitter ` as an alternative.
