### ISSUE TITLE
RuntimeError: CUDA error: device kernel image is invalid

### ISSUE THREAD

**Issue by rasin-tsukuba** [deepchem/deepchem#2156]
Hey guys! I am testing on the pytorch model on deepchem. When I am trying on the tutorial: [Creating Models With TensorFlow and PyTorch](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Creating%20Models%20With%20TensorFlow%20and%20PyTorch.ipynb), there is always a error shows that: CUDA error: device kernel image is invalid. But I am sure that I have installed the correct Pytorch with CUDA support:

```
pytorch                   1.6.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
tensorflow-gpu            2.3.0                    pypi_0    pypi
```
It works fine on Tensorflow(Keras), I wonder why PyTorch is not supported?

The code I used is:

```
import torch
import deepchem as dc

tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='ECFP', splitter='random')
train_dataset, valid_dataset, test_dataset = datasets

pytorch_model = torch.nn.Sequential(
    torch.nn.Linear(1024, 1000),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(1000, 1)
)
model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())

model.fit(train_dataset, nb_epoch=50)
print('training set score:', model.evaluate(train_dataset, [metric]))
print('test set score:', model.evaluate(test_dataset, [metric]))
```

Here is the error:

```
$ python pytorch_test.py            
2020-09-09 16:45:55.087719: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "pytorch_test.py", line 13, in <module>
    model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())
  File "/home/rasin/miniconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/torch_models/torch_model.py", line 182, in __init__
    self.model = model.to(device)
  File "/home/rasin/miniconda3/envs/deepchem/lib/python3.6/site-packages/torch/nn/modules/module.py", line 607, in to
    return self._apply(convert)
  File "/home/rasin/miniconda3/envs/deepchem/lib/python3.6/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/rasin/miniconda3/envs/deepchem/lib/python3.6/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/home/rasin/miniconda3/envs/deepchem/lib/python3.6/site-packages/torch/nn/modules/module.py", line 605, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: device kernel image is invalid

```

Please help, thanks!

**Comment by nd-02110114** [comment]
Can you try these codes? I seem this issue is related to the installation of PyTorch. 

```python
$ python
>>> import torch
>>> device = torch.device("cuda")
>>> torch.rand(10).to(device)
```

**Comment by rasin-tsukuba** [comment]
Hi @nd-02110114 , thank you for your reply! I have test your code here:

```
>>> import torch
>>> device = torch.device("cuda")
>>> torch.rand(10).to(device)
tensor([0.7050, 0.5339, 0.4674, 0.3389, 0.4574, 0.7041, 0.0947, 0.4649, 0.6377,
        0.5093], device='cuda:0')
>>> torch.tensor((1, 1)).cuda()
tensor([1, 1], device='cuda:0')

```

But still deepchem cannot find the cuda device. Any ideas?

**Comment by nd-02110114** [comment]
Thank you for testing. Hmm, it seem that PyTorch installation is not problem.

And, I tested your code using Google Colab, but I didn't face the error you reported. 
Reproduce notebook : https://colab.research.google.com/drive/1Cw8GXhzCc54MxclOfgFHQ_DIe554DqvI?usp=sharing

The error message also tell us the `CUDA error`, so I think this error is related to  your GPU environments like CUDA version, cudnn version and so on.

Could you teach us your GPU environments like the result of following commands?

```
// CUDA and Device info
$ nvidia-smi
$ nvcc --version

// cudnn info
$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
or
$ cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
```

**Comment by rasin-tsukuba** [comment]
To be honest, I have first installed cuda 10.2 with nvidia-driver and I found that I should install cuda 10.1 for the tensorflow-gpu support. So I keep both cuda 101 and cuda 102 on my machine. But I believe I have link the current `/usr/local/cuda` to cuda10.1 dir. Here are some details:

```
$ nvidia-smi
Thu Sep 10 11:35:37 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
```
And my nvcc version is 
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```
```
$ ll
total 40K
drwxr-xr-x  2 root root 4.0K 8月   1 00:27 bin
lrwxrwxrwx  1 root root   21 9月   8 17:26 cuda -> /usr/local/cuda-10.1/
drwxr-xr-x 18 root root 4.0K 9月   8 17:27 cuda-10.1
```
And here in my `~/.zshrc` file:
```
export PATH=$HOME/bin:/usr/local/bin:/usr/local/cuda-10.1/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64
```
Unfortunately I got nothing from the cudnn info, it is a bit strange.
```
$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
(deepchem) 
```

Another thing is that I have installed `tensorflow-gpu` but my keras model wont run on GPU, is there any way to force it to do so?

```
$ pip freeze | grep tensorflow
tensorflow-estimator==2.3.0
tensorflow-gpu==2.3.0
tensorflow-metadata==0.23.0
tensorflow-probability==0.11.0
```

**Comment by nd-02110114** [comment]
> To be honest, I have first installed cuda 10.2 with nvidia-driver and I found that I should install cuda 10.1 for the tensorflow-gpu support. So I keep both cuda 101 and cuda 102 on my machine. But I believe I have link the current /usr/local/cuda to cuda10.1 dir. Here are some details:

Thank you for your information! I seem that cuda 10.1 link is successful. However, generally, keeping multi cuda leads to an unexpected error because of complex dependencies. I recommend you should clean install. (To be honest, I don't  have much experiences about installation of cuda, so my advice may not be correct)

> Another thing is that I have installed tensorflow-gpu but my keras model wont run on GPU, is there any way to force it to do so?

Please see https://www.tensorflow.org/api_docs/python/tf/config/get_visible_devices

In addition to this, DeepChem doesn't support TensorFlow 2.3.0 officially. We support TensorFlow 2.2.0.

**Comment by rasin-tsukuba** [comment]
Thank you very much for your reply! I would try a clean install instead.
