### ISSUE TITLE
MNIST Example Tutorial #1

### ISSUE THREAD

**Issue by Exoceus** [deepchem/deepchem#2175]
There seem to be a few errors or areas of confusion with the MNIST Example section in [Tutorial #1](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/01_The_Basic_Tools_of_the_Deep_Life_Sciences.ipynb). 
First, there seem to be a few inconsistencies regarding the use of a single # for commenting out code and ## for comments themselves. This inconsistent usage leads to some confusion regarding what is potentially just comments and what is the actual code.

Second, the second cell in the MNIST example seems of little use as none of the variables or data is used in the subsequent cells. This is likely just my lack of knowledge, but, just wanted to point out that strictly looking at the code, code cell #2 seems useless as all the data is just imported from tensorflow.examples.tutorials.mnist anyway.

Lastly, in the first markdown cell of the MNIST example, there is a reference to 'this package.' However, it is unclear which package(s) this statement is referring too as two packages are installed in the next code cell. This is very minor, but it would be great if it would be more explicit: 'You'll need to install the nightly build of the tensorflow and tensorflow dataset packages in order to make use of it.'

P.S. This is my first time submitting an issue, so please let me know if there is a specific convention to follow and feedback regarding improving the writeup.

**Comment by peastman** [comment]
That tutorial has been almost completely rewritten.  See #2169.
