### ISSUE TITLE
should nglview be listed in requirements.txt

### ISSUE THREAD

**Issue by suliuzh** [deepchem/deepchem#2189]
Hi
**nglview** is used in _contrib/visualization/utils.py_ as a must. So I am wondering if **nglview** should be listed in requirements.txt explicitly or described as a dependency of the project in documentation.
![image](https://user-images.githubusercontent.com/27858725/94342067-031c6980-0041-11eb-8432-22b879a9a614.png)

**Comment by rbharath** [comment]
@suliuzh Good question! In general our `contrib/` folder is non-maintained code so we don't count usage there as dependencies for the main package
