### ISSUE TITLE
How to convert prediction results into pandas dataframe, shape issue?

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2191]
Description: binary classification model, GCNN, single task

Hi, I'm trying to save the model prediction results into an excel file. To do that, I guess I need to convert this result into a pandas dataframe first. The shape of my prediction dataset is (2364, 2) before featurization applied. However this got an  error showing "ValueError: Must pass 2-d input". I printed the prediction shape, it's (2364, 1, 2), I guess this is because it's 3D shape. The following is the code snippet I used:
```
pred_task = ["label"]
graph_featurizer = dc.feat.graph_features.ConvMolFeaturizer()
pred_loader = dc.data.data_loader.CSVLoader(tasks=pred_task, smiles_field="SMILES", featurizer=graph_featurizer)
pred_dataset_featurized = pred_loader.featurize(pred_dataset_file)

predictions = model.predict(pred_dataset_featurized, [])
print(predictions.shape)
res = pd.DataFrame(predictions, columns=["predictions"])
res.index = pred_dataset.index
res.to_csv("prediction_results.csv")
```
Then I tried this res = pd.DataFrame(np.concatenate(predictions), columns=["predictions"]), but got another error saying :
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1654, in create_block_manager_from_blocks
    make_block(values=blocks[0], placement=slice(0, len(axes[0])))
  File "/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 3047, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 125, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 2, placement implies 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1664, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1694, in construction_error
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (2364, 2), indices imply (2364, 1)
```
I'm not very clear what this means. Great thanks for any advice!

**Comment by rbharath** [comment]
Sorry for the slow response! This slipped through my inbox. The output prediction is of shape `(2364, 1, 2)` since you have 2364 datapoints, 1 task you're making a prediction on, and 2 possible values for that prediction. The easiest solution for your problem would probable be to remove the task dimension. You can do that with

```
predictions = np.squeeze(predictions, axis=1)
```

I hope that helps!

**Comment by hjzhang1018** [comment]
@rbharath Thank you a lot! Yes it works. I've learned that this is an easy way to change the shape, thank you:)
