### ISSUE TITLE
Embed small examples in docs

### ISSUE THREAD

**Issue by micimize** [deepchem/deepchem#2196]
Many of the examples are out of date and/or poorly documented. The current thinking to solve both these problems is to:
- [x] start converting examples into doctest-able `.rst` examples in the `docs/`
- [ ] better document and update/fix them along the way
- [x] keep slow examples **out** of the current CI build (slow enough as is)

Ideas for future work include:
* breaking example CI into a separate build
* automatically adding badges to examples based on that build
  (this may be excessive as we probably don't want to publish versions with broken examples anyhow. Just having a non pr-blocking CI build is maybe enough)

Possible alternative approaches (for documentation/ future discussion):
1. turn examples into notebooks and embed them with [`nbsphinx`](https://nbsphinx.readthedocs.io/en/0.7.1/)
2. leave examples as `.py` files and embed them some other way
3. embed examples as documentation in the modules themselves
4. a mix: 3 might make sense for "dataset-wise examples", 2 might make sense for more complicated examples, etc

I'm going to start on the current outlined approach today (starting with `sampl`)

Related to #2168 and similar to #2112

**Comment by rbharath** [comment]
@micimize Thanks for writing this up! This is a really useful discussion of the possible options :)

**Comment by micimize** [comment]
We should be able to use the [`include`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include) directive to maintain a single examples page while breaking up the examples into files:
```rst
This first example will be parsed at the document level, and can
thus contain any construct, including section headers.

.. include:: inclusion.txt

Back in the main document.

    This second example will be parsed in a block quote context.
    Therefore it may only contain body elements.  It may not
    contain section headers.

    .. include:: inclusion.txt

```
