### ISSUE TITLE
DeepChem docker image doesn't have sklearn

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2201]
The DeepChem docker image doesn't have scikit-learn installed I believe. We should add it to the docker image.

**Comment by nd-02110114** [comment]
Which image did you use?  I think the scikit learn was installed in the latest image. scikit learn dependency was added in `setup.py`, so it was automatically installed by `pip install -e .` in Dockerfile. 

https://github.com/deepchem/deepchem/blob/0d3f22850988d3e2562e8f83c0459c0b74ae45f6/docker/master/Dockerfile#L23

Could you show more details...?

**Comment by rbharath** [comment]
Ah I think you're right! Ok, I might have something else going on in my docker image. Let me do a little more testing and I'll close this issue if it turns out I have a different error
