### ISSUE TITLE
Tensorflow Probability 0.11 release is incompatible with TF 2.2.0

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2204]
https://github.com/tensorflow/probability/releases/tag/v0.11.0

^ I think some of our docs don't pin TF probability to 0.11. We should do a pass to make sure that's done cleanly

**Comment by peastman** [comment]
We also should upgrade to TF 2.3.

**Comment by rbharath** [comment]
Fixed by #2209
