### ISSUE TITLE
[CI] recent mypy release breaks CI due to pickle typing

### ISSUE THREAD

**Issue by micimize** [deepchem/deepchem#2207]
The [most recent mypy release](https://mypy-lang.blogspot.com/2020/10/mypy-0790-released.html) will start breaking CI builds due to [better `pickle` typing](https://github.com/python/typeshed/commit/03c9faa37549a90a6d057b22cfe02620ba1e3b12): https://github.com/deepchem/deepchem/pull/2197#issuecomment-706741581
but has a pretty straightforward fix: https://github.com/deepchem/deepchem/commit/c7a6c148533058fe5da0613adcc2a2d949246801

So #2197 closes this or that patch can be applied before hand if it's not ready to merge

**Comment by rbharath** [comment]
Closing this issue since I think we've fixed in subsequent PRs
