### ISSUE TITLE
Issue Importing rdkit

### ISSUE THREAD

**Issue by altaetran** [deepchem/deepchem#221]
Hi,

I'm currently unable to run the nosetests for deepchem. I followed the installations step by step, and am working on a linux machine.

version info:
(deepchem) [hraut@xs-0005 ~/src/deepchem]$ cat /etc/*-release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Red Hat Enterprise Linux Server release 6.8 (Santiago)
Red Hat Enterprise Linux Server release 6.8 (Santiago)

Running 

`nosetests -v deepchem --nologcapture
`
I end up with the following

> Failure: ImportError (No module named rdkit) ... ERROR
> Failure: ImportError (No module named rdkit) ... ERROR
> Failure: ImportError (No module named rdkit) ... ERROR
> Failure: ImportError (No module named rdkit) ... ERROR
> Failure: ImportError (No module named joblib) ... ERROR
> Failure: ImportError (No module named rdkit) ... ERROR
> Failure: ImportError (No module named rdkit) ... ERROR
> Failure: ImportError (No module named rdkit) ... ERROR
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/datasets/__init__.py", line 13, in <module>
>     from deepchem.utils.save import save_to_disk
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/utils/__init__.py", line 14, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/featurizers/__init__.py", line 6, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/hyperparameters/__init__.py", line 11, in <module>
>     from deepchem.utils.evaluate import Evaluator
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/utils/__init__.py", line 14, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/metrics/__init__.py", line 5, in <module>
>     from deepchem.utils.save import log
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/utils/__init__.py", line 14, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named joblib)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 13, in <module>
>     import joblib
> ImportError: No module named joblib
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/splits/__init__.py", line 13, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/transformers/__init__.py", line 11, in <module>
>     from deepchem.utils.save import save_to_disk
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/utils/__init__.py", line 14, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ======================================================================
> ERROR: Failure: ImportError (No module named rdkit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/stanford/pande/users/hraut/programs/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/utils/__init__.py", line 14, in <module>
>     from rdkit import Chem
> ImportError: No module named rdkit
> 
> ----------------------------------------------------------------------
> Ran 8 tests in 0.003s
> 
> FAILED (errors=8)

Running some checks, I obtain

> (deepchem) [hraut@xs-0005 ~/src/deepchem]$ conda install -c omnia rdkit
> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata .........
> Solving package specifications: ..........
> 
> # All requested packages already installed.
> # packages in environment at /home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem:
> #
> rdkit                     2015.09.1                py27_2    omnia
> 
> (deepchem) [hraut@xs-0005 ~/src/deepchem]$ which python
> ~/programs/anaconda2/envs/deepchem/bin/python
> 
> (deepchem) [hraut@xs-0005 ~/src/deepchem]$ python
> Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> >>> import rdkit
> >>>
> 

Any ideas as to why this may be happening? Thanks!

**Comment by rbharath** [comment]
@altaetran What happens when you type

```import rdkit``` 

into an ipython shell?

**Comment by altaetran** [comment]
I think the import is successful, because no errors are thrown, and I can see all the rdkit modules in ipython

**Comment by rbharath** [comment]
Ah, I suspect that you might be using the system `nosetests` instead of the environment `nosetests`. What does

`which nosetests`

display?

**Comment by altaetran** [comment]
~/programs/anaconda2/bin/nosetests

**Comment by altaetran** [comment]
I am using an anaconda environment. Perhaps a fix needs to be made for this

**Comment by altaetran** [comment]
since it should be in the environment's bin

**Comment by rbharath** [comment]
Yes, here's my `which nosetests` for example:

(deepchem) [rbharath@gpu-9-1 /scratch/users/rbharath/deepchem-models/atomicnet/scripts]$ which nosetests
~/anaconda/envs/deepchem/bin/nosetests

I think you might try installing nosetests within your `deepchem` environment. You might need to uninstall your outer nosetests to get this to work right.

**Comment by altaetran** [comment]
How should I go about installing nosetests? It doesn't seem to be a package

**Comment by rbharath** [comment]
```pip install nose```

**Comment by altaetran** [comment]
Ok. I think some documentation on this should be good for people using conda environments. Thanks!
