### ISSUE TITLE
Random Forest outperform GraphConv Neural Network?

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2211]
I used both random forest and graph convolution model to train my data and make predictions for binary classification problems. 

I thought GCNN should outperform RF due to its automatic feature extraction ability. However in my situation, it turns out the very reverse. Evaluating scores in RF is better than that in GCNN. Even though both model got pretty good scores (>0.8). 

I wonder if RF is very suited for binary classification issues and what are the advantages of GCNN then?

Thank you very much.

**Comment by rbharath** [comment]
Unfortunately this is often the case! Random forests plus circular fingerprints are a very strong baseline and oftentimes will be the best performing model for a task. You might need to tune your deep model carefully to see improved performance results. A well tuned GCNN will often beat a RF but it usually takes some careful work.

**Comment by hjzhang1018** [comment]
Thank you @rbharath ! I see.
