### ISSUE TITLE
Physical Deep Learning for DeepChem

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2214]
Over the last several months, DeepChem has started to grow outwards past its core molecular machine learning system. We've got increasing support for materials datasets and learning tasks, and a growing suite of protein deep learning tools. The long term vision that's starting to emerge is for DeepChem to become a general deep learning for the sciences library. I propose that we take one important step in that direction by improving our support for physical deep learning systems. In particular, I think there are a few powerful new models that we should consider adding support for:

- [Physics Informed Neural Networks](https://www.sciencedirect.com/science/article/pii/S0021999118307125): A framework for using deep learning to solve partial differential equations
- [Physics guided recurrent neural networks](https://arxiv.org/pdf/2001.11086.pdf): 
- [Universal Ordinary Differential Equations](https://arxiv.org/pdf/2008.01527.pdf)
- [Neural Ordinary Differential Equations](https://arxiv.org/abs/1806.07366)
- [Euclidean Neural Networks](https://github.com/e3nn/e3nn)
- [Lagrangian Neural Networks](https://arxiv.org/abs/2003.04630)

This selection is inspired by the talks at https://www.cmu.edu/aced/sciML.html which I highly recommend for anyone who wants to learn more about this field!

Let's use this issue to discuss this line of work. Greater support for physical systems will help us address a broad range of problems that DeepChem today can't address. I think our new support for PyTorch will also make this much easier.

**Comment by ncfrey** [comment]
@rbharath, I think this is a great idea and I have a few thoughts.
*  For scalability, it would be great to have some on-boarding procedure to help people implement their own models in DeepChem.  I think their are obvious advantages to implementing in DeepChem: longevity, reach, etc. But it will be difficult for core contributors to implement all these models. There could be a "MoleculeNet" style framework for implementing new models. This would work nicely with a "ModelHub" for providing endpoints to trained models.
* PINNs and ENNs are developed at UPenn and Berkeley, respectively, and I know some of the authors. I'd be happy to reach out to see what they think about implementing or coordination implementation efforts in DeepChem.
* I might add a [symbolic deep learning package](https://github.com/MilesCranmer/symbolic_deep_learning) to the list, for learning governing equations from data. This particular implementation requires Julia so might be a bit tricky.
* For all these physics informed and ODE-based models I think there are some major barriers to widespread use in research. Without some extensive reading, it's kind of unclear why you would use one method versus another, what sorts of symmetries they incorporate and why they're important. Anything DeepChem can do to become a one-stop shop for these methods that cuts down on the time it takes to get started with them would be really valuable, I think.

**Comment by rbharath** [comment]
Doing a bit more brainstorming, I'd love for us to put together a core set of first physical deep learning models to get into DeepChem (say for DeepChem 2.5.0). 

@ncfrey Do you have any gut intuitions about say the top 3 physical deep learning models you'd be most excited to see in DeepChem?

**Comment by ncfrey** [comment]
I'd say E(3)NN should be top priority. It is maintained, already has a great ecosystem, and has been directly used or led to applications in [phonon properties](https://arxiv.org/abs/2009.05163), [molecular property prediction](https://arxiv.org/abs/2008.08461), and [protein complex structure prediction](https://arxiv.org/pdf/2006.09275.pdf). I think this would be a really powerful addition to DeepChem.

Then I think Lagrangian NNs and PINNs, although not yet proven out for applied science applications beyond toy problems, would provide a well-rounded physical deep learning repetoire.

**Comment by peastman** [comment]
I'd like to try implementing some of this.  I think a good first goal would be to be able to reproduce some of the results from https://arxiv.org/pdf/2012.04035.pdf.

We need to decide on a featurization for these models.  I'm not sure we currently have anything that exactly fits.  In that paper, the input data consists of the position and element of every atom.  Among our featurizers, `AtomicCoordinates` reports the positions but not elements or any other information.  `NeighborListAtomicCoordinates` adds a neighbor list, which might be useful for accelerating some models but doesn't fundamentally add any information.  `ComplexNeighborListFragmentAtomicCoordinates` adds in the atomic numbers, but is only designed to work with complexes, not single molecules.  `MolGraphConvFeaturizer` computes lots of useful information for each atom, but doesn't include positions.

Perhaps we should create a representation that specifies a position and an arbitrary feature vector for each atom?  That's a bit less general than what E(3)NN models support, since they allow the features to consist of multiple pieces that transform in different ways.  But treating all the features as scalars is probably fine for our current purposes, and that allows a single representation to be used for multiple types of models.  The feature vector could be a one-hot encoded element, or it could also contain other information.

We also will want to be able to create this representation from a variety of inputs: SDF files, PDB files, SMIlLES strings (using RDKit to create a reasonable geometry), etc.

**Comment by rbharath** [comment]
@peastman I quite like this proposal! It would nicely generalize the set of models we support while being a natural evolution of our current set of supported features. I think it would be a very nice first step towards improving our physical deep learning support

**Comment by peastman** [comment]
Here's a concrete proposal.

I'll create a new class to represent a 3D arrangement of atoms.  Those atoms could be a molecule, multiple molecules, a fragment of a molecule, a material, etc.  I'm not sure what to name this class.  AtomSet?  AtomCollection?  AtomConfiguration?  We already have a class called AtomicCoordinates, which confusingly is a featurizer, not a set of coordinates.  Suggestions appreciated!

This class will have the following fields:

`positions`: an array of shape (N, 3) where N is the number of atoms, giving the position of each one.
`properties`: an array of shape (N, M) containing the values of M scalar properties for each atom.
`property_names`: an array of length M containing the names of the properties.

It will allow arbitrary properties, but we'll define standard names for a few common ones: `'atomic number'`, `'formal charge'`, and `'partial charge'`.  (Any others we should include?)  For each of those, it will provide an accessor method as a convenience to pull out the corresponding column of the properties array (or throw an exception if it isn't present).

I'll also create a featurizer to create objects of this class.  It will allow the ID of each sample to be either a SMILES string or a filename (any of the formats supported by `load_molecule()` in rdkit_utils.py).  For SMILES strings, it will use RDKit to generate a 3D conformation.  For files, it will use RDKit to calculate formal and partial charges.

Does that sound reasonable?

**Comment by rbharath** [comment]
Sorry for the very late response here! Just circling back after looking at #2356. One thought here is we might want to refactor the AtomicConv model/featurizer to use this new base class once it's ready. The current support in the atomic conv models is very idiosyncratic and not very generalizable.

**Comment by VIGNESHinZONE** [comment]
Following the ideas of Physical Deep Learning repertoire - 
Will there be any advantages of adding JAX-Model in terms of Physics Deep Learning Libraries. I had come across these two resources - 
1) [JAX-Molecular Dynamics](https://github.com/google/jax-md)
2) [Blog](https://greydanus.github.io/2020/03/10/lagrangian-nns/) written by the author of Lagrangian Neural Networks explained in JAX.

**Comment by rbharath** [comment]
Yes, definitely think Jax could help with physical deep learning! The references you pointed out are great

**Comment by rbharath** [comment]
Closing since superseded by the model wishlist
