### ISSUE TITLE
Conda Installation Instructions Need Sklearn

### ISSUE THREAD

**Issue by altaetran** [deepchem/deepchem#222]
I think the conda installation instructions should include an sklearn dependency. Which version should I install?

**Comment by rbharath** [comment]
@altaetran Ah, good find.

```conda install scikit-learn```

should do it. Would you mind making a PR to `deepchem` that fixes the readme issues noted here and in #221?

**Comment by altaetran** [comment]
I'm not really familiar with these doc files. It might be easier if you did, I think.

The instructions are

before installing anything

`conda activate [env of choice]`

Then, we also need

`pip install nosetests`

`conda install scikit-learn`

**Comment by rbharath** [comment]
@altaetran Updated README. Can you check the installation directions again? If everything looks good, please go ahead and close this issue.

**Comment by rbharath** [comment]
Going to go ahead and close.
