### ISSUE TITLE
Fatal Error on nosetests

### ISSUE THREAD

**Issue by altaetran** [deepchem/deepchem#223]
Hi,

I am encountering this issue when running the nosetests.

I am using

```
module load tensorflow (0.9)
source activate deepchem
nosetests -v deepchem --nologcapture
```

Thanks

> Test CircularFingerprint. ... ok
> Test CircularFingerprint with sparse encoding. ... ok
> Test CircularFingerprint with sparse encoding and SMILES for each ... ok
> Run simple tests with NNScore. ... ok
> Test of singletask CoulombMatrixEig regression on .sdf file. ... /home/stanford/pande/users/hraut/src/deepchem/deepchem/datasets/__init__.py:885: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   if y[ind, task] == "":
> ok
> Straightforward test of Keras multitask deepchem classification API. ... I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
> name: Tesla K80
> major: 3 minor: 7 memoryClockRate (GHz) 0.8235
> pciBusID 0000:84:00.0
> Total memory: 11.25GiB
> Free memory: 11.13GiB
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0)
> I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 4316 get requests, put_count=4146 evicted_count=1000 eviction_rate=0.241196 and unsatisfied allocation rate=0.294254
> I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110
> ERROR
> Straightforward test of Tensorflow multitask deepchem classification API. ... I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0)
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0)
> /global/software/extras/tensorflow/0.9/numpy/lib/function_base.py:2487: RuntimeWarning: Degrees of freedom <= 0 for slice
>   warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> ok
> Test of hyperparam_opt with singletask RF ECFP regression API. ... /home/stanford/pande/users/hraut/src/deepchem/deepchem/datasets/__init__.py:885: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   if y[ind, task] == "":
> ok
> Test of hyperparam_opt with singletask_to_multitask. ... Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.

**Comment by rbharath** [comment]
@altaetran I've seen this error before. I think this is an issue with the Stanford cluster setup, and not with the test itself (since it runs fine on Travis CI).  Perhaps something to report to the cluster admins.

**Comment by altaetran** [comment]
Actually, this is a more general issue with numpy and scipy interacting on linux systems I believe. 

See https://github.com/BVLC/caffe/issues/3884

Their solution

`conda install nomkl`

works, to get things running, so I suggest adding a note somewhere in the installation.
