### ISSUE TITLE
Implementing MARIA in Deepchem

### ISSUE THREAD

**Issue by alat-rights** [deepchem/deepchem#2230]
Hi everyone! 

Here's a brief outline of my current plan for implementing MARIA in Deepchem. (MARIA: https://www.nature.com/articles/s41587-019-0280-2 )

- [ ]  Data loading. Currently WIP, #2229 . Feel free to help out. 

- [ ] Data integration. Upload the pre-trained models described in the "MARIA data integration framework" section of the Chen et al. paper to the Deepchem AWS instance. I haven't looked too deeply into this yet. 

- [ ] Implementation of RNN in eg. Pytorch and wrapping into DeepChem. Haven't looked into this yet. 

- [ ] Testing and possible steps towards expansion.

**Comment by rbharath** [comment]
Awesome, thanks for getting this started! I'm looking forward to seeing this make it into DeepChem :)

**Comment by rbharath** [comment]
Closing this old issue. Feel free to re-open if that would be useful!
