### ISSUE TITLE
Consider (enforcing) commit signing or 2FA

### ISSUE THREAD

**Issue by micimize** [deepchem/deepchem#2231]
Commit signing ([docs](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/signing-commits), [benefits](https://softwareengineering.stackexchange.com/questions/212192/what-are-the-advantages-and-disadvantages-of-cryptographically-signing-commits-a)) was mentioned in the meeting today, so I figured I'd make an issue for it.

It's possible to [enforce commit signing](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-commit-signing) in PRs, but in my experience it's an undue burden on first-time contributors. FWIW, [nodejs, rejected the idea](https://github.com/nodejs/node/issues/15457). I think if we want serious repo security, we should probably do what they do and [require collaborators use 2FA on GitHub](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization).

**Comment by alat-rights** [comment]
Here's my proposal for a sort of maximal reasonable security approach in this regard. 

```
People who do code review/merge commits keep some sort of signed, distributed notebook of secure (read: not SHA-1!) hashes of merged commits once in a while. This makes release signing very easy. 

The contents can be released in quarterly signed "canaries" [Qubes style](https://github.com/QubesOS/qubes-secpack/blob/master/canaries/canary-024-2020.txt).

2FA would, of course, be a plus. But not security critical in this case.
```

Here's the problem with 2FA: it relies on infrastructure security. The recent Twitter hack (wherein the attacker was purportedly able to directly access the CPanel and thus attain control of any account) shows that this is an incredibly flawed approach. 

While enforcing 2FA is a low-risk, low-cost approach (and a lower-cost, higher-reward policy change that can go hand-in-hand with this would be requiring code reviewers to use effective (read: non-SMS and preferably Yubikey-based) forms of 2FA), we should probably have a proper discussion about the Deepchem threat model at some point. I suppose that Deepchem may be considered security-critical in certain academic settings? But I think a serious discussion of threat modelling would certainly be in order before we implement any changes as drastic code-signing. 

Summary:
- Code signing likely less effective than signed commit-logging by reviewers
- 2FA is good and cool.
- Requiring "good" (non-SMS) 2FA for reviewers makes sense.
- Better threat modelling of Deepchem is a reasonable goal over the next few months.

**Comment by alat-rights** [comment]
Just to add to this, I think AWS would support 2FA also.

**Comment by rbharath** [comment]
@alat-rights Thanks for putting this together! As a couple of basic questions to help me understand further, what would this entail for our reviewers in practice? It might be a bit of a lift to require reviewers to purchase yubikeys (I have one, but I'm not sure who else has one. If you're also on a yubikey, please chime in!)

I might be wrong, but I think our threat model is fairly low. Our software is mostly used in discovery pipelines, with a human dat scientist in the loop. We don't have any live deployments, although DeepChem does run on some production servers. The question for me is whether the inconvenience is worth the security gain. 

CC @peastman @nd-02110114 @ncfrey @seyonechithrananda

**Comment by alat-rights** [comment]
Even something like TOTP (eg. Google Authenticator) would be much more secure than SMS.

That's good information to know! I think a 2FA requirement for reviewers is probably a very low bar (if a reviewer doesn't have a phone/tablet *or* a yubikey it becomes a bit problematic), and even across the board for commiters is probably not that difficult. Sounds a bit like a low cost/low-to-medium reward scenario. 

I guess there is some valid concern for some Tom Clancy-esque attack like someone trying to secretly bundle a malicious data-exfiltrator in Deepchem to target a specific research facility's servers/clients to gain access to specific research data before it is released. I highly doubt Deepchem would be the weakest link in the chain in a hypothetical attack like this, but it is something to *consider*.
