### ISSUE TITLE
weight save mechanism

### ISSUE THREAD

**Issue by hsjang001205** [deepchem/deepchem#2237]
Because of the first weight in Graph convolution model was not saved normally,  it was confirmed difference in the overall output result of the model. 

The easiest solution was to give the name of the weight inside the layer differently.(ex: kernel1, kernel2 ...)

However, there were no such bugs in the other models. For example, DAG model is saved normally even if the same weight name is used in layer.

**First weight in DAG(duplicate weight name):**
[array([[-0.02619981, -0.00350917, -0.01802997, ..., -0.05562029,
         0.00836199,  0.00024717],
       [-0.01967072,  0.04119263,  0.02528244, ..., -0.05213797,
        -0.04617742,  0.04094393],
       [-0.00702904,  0.02090265, -0.02785139, ..., -0.02165696,
        -0.05957941,  0.04697081],
       ...,
       [ 0.03756117, -0.00756638, -0.02054571, ...,  0.03864547,
        -0.00692571, -0.02121712],
       [-0.00597412,  0.0260972 , -0.00279761, ...,  0.01976136,
        -0.014446  , -0.0308291 ],
       [ 0.04186894,  0.04167419, -0.02048581, ..., -0.02184899,
         0.05794627,  0.03958885]], dtype=float32)

**reloaded_weight in DAG(duplicate weight name):**
[array([[-0.02619981, -0.00350917, -0.01802997, ..., -0.05562029,
         0.00836199,  0.00024717],
       [-0.01967072,  0.04119263,  0.02528244, ..., -0.05213797,
        -0.04617742,  0.04094393],
       [-0.00702904,  0.02090265, -0.02785139, ..., -0.02165696,
        -0.05957941,  0.04697081],
       ...,
       [ 0.03756117, -0.00756638, -0.02054571, ...,  0.03864547,
        -0.00692571, -0.02121712],
       [-0.00597412,  0.0260972 , -0.00279761, ...,  0.01976136,
        -0.014446  , -0.0308291 ],
       [ 0.04186894,  0.04167419, -0.02048581, ..., -0.02184899,
         0.05794627,  0.03958885]], dtype=float32)

**First and second weight in GraphConv(duplicate weight name):**
[array([[ 0.14467062, -0.02941738, -0.19794391, ..., -0.16218857,
        -0.12462973,  0.20790973],
       [ 0.13335757,  0.07646178, -0.06466344, ..., -0.1226402 ,
         0.19910176,  0.03208816],
       [ 0.08093916, -0.02584244,  0.15696831, ...,  0.17134063,
         0.0887218 ,  0.18211444],
       ...,
       [-0.10009002, -0.10924715, -0.03701026, ...,  0.15426876,
         0.11034554,  0.01643867],
       [ 0.1850215 ,  0.1275614 , -0.15505217, ...,  0.14968218,
        -0.08345054,  0.16157831],
       [ 0.11927764,  0.20578511,  0.11939959, ..., -0.12333546,
        -0.00091681,  0.13491575]], dtype=float32), 
array([[-0.05118698,  0.1233124 , -0.16214992, ..., -0.2149568 ,
         0.10525376,  0.0618633 ],
       [-0.00074832, -0.05264176, -0.2086493 , ...,  0.1965441 ,
        -0.13711777,  0.173452  ],
       [ 0.0747811 ,  0.20311798,  0.00789288, ...,  0.18251835,
        -0.0998343 , -0.20234707],
       ...,
       [-0.15927637,  0.06863301,  0.06446611, ...,  0.13603483,
        -0.16207135,  0.03863216],
       [-0.09930629, -0.17713489, -0.04652473, ...,  0.1095372 ,
         0.12955154,  0.05271424],
       [-0.19104232,  0.139223  ,  0.00166178, ...,  0.05139588,
        -0.04563957, -0.04004179]], dtype=float32)

**First and second weight in reloaded_GraphConv(duplicate weight name):**
[array([[-0.09188263, -0.20805304,  0.06342052, ...,  0.00053678,
         0.1426114 , -0.11856456],
       [-0.18032047, -0.04679585, -0.18502688, ..., -0.18120272,
        -0.11358754,  0.12151165],
       [-0.16900378, -0.10438917,  0.19674979, ...,  0.00180668,
         0.00124991, -0.1236348 ],
       ...,
       [ 0.00892474, -0.19587062, -0.1195766 , ..., -0.15710707,
        -0.14890608, -0.13049069],
       [ 0.08895644,  0.10527186, -0.04810883, ..., -0.0187088 ,
         0.00542192, -0.05521756],
       [-0.09990873, -0.04720394, -0.16681606, ...,  0.03399868,
         0.07792218,  0.06561385]], dtype=float32), 
array([[-0.05118698,  0.1233124 , -0.16214992, ..., -0.2149568 ,
         0.10525376,  0.0618633 ],
       [-0.00074832, -0.05264176, -0.2086493 , ...,  0.1965441 ,
        -0.13711777,  0.173452  ],
       [ 0.0747811 ,  0.20311798,  0.00789288, ...,  0.18251835,
        -0.0998343 , -0.20234707],
       ...,
       [-0.15927637,  0.06863301,  0.06446611, ...,  0.13603483,
        -0.16207135,  0.03863216],
       [-0.09930629, -0.17713489, -0.04652473, ...,  0.1095372 ,
         0.12955154,  0.05271424],
       [-0.19104232,  0.139223  ,  0.00166178, ...,  0.05139588,
        -0.04563957, -0.04004179]], dtype=float32)

second weight successfully saved/loaded.

#2236 

It can be solved by simply changing the name. 
However, we need to be aware of the difference between using duplicate names in different models.

DAG and others allow duplicate name.
However, graph conv model is not allow.(If weight has same name, first weights broken during the save/load.)

I found this issue a week ago, but I don't know the exact solution of duplicated weight name issues yet.

As https://github.com/tensorflow/tensorflow/issues/34298 referred to by @rbharath , it may be an issue caused by eager mode.

**Obviously if weights name were duplicated, only the first weight was not saved/loaded.**

**Comment by rbharath** [comment]
This is a really useful analysis! Perhaps for subclassing style models like `GraphConvModel` (which use Eager mode), we need to pay extra attention in the review process to make sure duplicate names aren't being used for weights

**Comment by peastman** [comment]
> Perhaps for subclassing style models like GraphConvModel (which use Eager mode)

Just to avoid confusion about terminology: using subclassing is independent of eager mode.  Regardless of which way you implement it, KerasModel runs all models in graph mode, that is, inside a function annotated with `@tf.function`.
