### ISSUE TITLE
Do we need validation dataset in random forest?

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2248]
Hi, I'm trying to understand and apply hyperparameter tuning in Random Forest model. However I saw a lot o f tutorials did not use validation dataset in these parameter tuning steps. Like this snippet shown below,
```
param_grid = {"n_estimators": range(50, 200, 50),
               "max_features": ["auto", "sqrt", "log2", None]}
rf_grid = GridSearchCV(estimator=RandomForestClassifier(random_state=10),
                       param_grid=param_grid,
                       scoring="roc_auc",
                       cv=5)
rf_grid.fit(xtrain, ytrain)
print("rf_grid best parameters: %s" % str(rf_grid.best_params_))
print("rf_grid best score: %s" % str(rf_grid.best_score_))
```
Looks like we're still using training dataset for a better score. Correct me if I'm wrong, I wonder in other models, like GCNN, do we also not use the validation dataset for parameter tuning ? Thanks a lot for any advice!

**Comment by peastman** [comment]
Hyperparameter tuning should always be done with the validation set.  Which tutorials aren't doing that?

**Comment by hjzhang1018** [comment]
Yes I  agree @peastman . I understand that validation data are used for this. In deepchem `hyperparam_search`, I know we passed both `train dataset` and `valid dataset` to this searching steps, but in this snippet I didn’t see where we passed the validation dataset to the grid searching steps. So I'm a bit confused.

**Comment by peastman** [comment]
Where did it come from?

**Comment by hjzhang1018** [comment]
It comes from a website "https://www.kaggle.com/funxexcel/p2-sklearn-randon-forest-parameter-tuning". 
Could you please tell me how to pass the valid dataset to the tuning steps in this case? Thank you very much! @peastman

**Comment by peastman** [comment]
That website isn't anything related to DeepChem.  For a description of how to do hyperparameter optimization in DeepChem, see this tutorial: https://github.com/deepchem/deepchem/blob/master/examples/tutorials/09_Advanced_Model_Training.ipynb

**Comment by hjzhang1018** [comment]
Thank you @peastman! I learned this tutorial and this is the snippet I used for random forest hyperparameter tuning. However it shows an error message and I didn’t figure a way to solve it. Could you help me with this bug? Thank you very much.
```
def rf_model_builder(model_params, model_dir):
  sklearn_model = RandomForestClassifier(**model_params)
  n_estimators = model_params["n_estimators"]
  max_features = model_params["max_features"]
  return dc.models.SklearnModel(sklearn_model, model_dir)
params_dict = {
    "n_estimators": [10, 100],
    "max_features": ["auto", "sqrt", "log2", None],
}

metric = dc.metrics.Metric(dc.metrics.roc_auc_score)
optimizer = dc.hyper.GridHyperparamOpt(rf_model_builder)
best_rf, best_rf_hyperparams, all_rf_results = optimizer.hyperparam_search(
    params_dict, train_dataset, valid_dataset, [],
    metric=metric)
```
This is the error message:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-68-725f6a0b4289> in <module>()
     13 best_rf, best_rf_hyperparams, all_rf_results = optimizer.hyperparam_search(
     14     params_dict, train_dataset, valid_dataset, [],
---> 15     metric=metric)
     16 
     17 RandomForestClassifier()

/usr/local/lib/python3.6/dist-packages/deepchem/hyper/grid_search.py in hyperparam_search(self, params_dict, train_dataset, valid_dataset, output_transformers, metric, use_max, logdir)
    146         model_dir = tempfile.mkdtemp()
    147       model_params['model_dir'] = model_dir
--> 148       model = self.model_builder(**model_params)
    149       model.fit(train_dataset)
    150       try:

TypeError: rf_model_builder() got an unexpected keyword argument 'n_estimators'
```

**Comment by peastman** [comment]
The signature for your model builder function should be

```python
def rf_model_builder(**model_params):
```

That says it accepts an arbitrary set of keyword arguments, which all get stored into the `model_params` dict.  The way you've written it, it expects exactly two arguments with the names `model_params` and `model_dir`.

**Comment by hjzhang1018** [comment]
Thank you @peastman ! This worked. Please forgive me but I do have another related question. After the hyperparameter tuning, we got `best_rf`, `best_rf_hyperparams` and `all_rf_results`, right? To my knowledge, I think that `best_rf` should have the same parameters as `best_rf_hyperparams` show, but it didn't, please see below. I wonder if this is a bug? If so, I guess we need to manually set the parameters of `best_rf` instead of using it directly because it didn't contain the same best parameters as calculated. Thank you very much!

```
In: best_rf_hyperparams
Out: (10, 'log2')
In: all_rf_results
Out: {'_max_featuresNone_n_estimators_10': 0.9671717171717172,
 '_max_featuresNone_n_estimators_100': 0.954861111111111,
 '_max_featuresauto_n_estimators_10': 0.9665404040404041,
 '_max_featuresauto_n_estimators_100': 0.9756944444444444,
 '_max_featureslog2_n_estimators_10': 0.9791666666666667,
 '_max_featureslog2_n_estimators_100': 0.9766414141414141,
 '_max_featuressqrt_n_estimators_10': 0.9646464646464648,
 '_max_featuressqrt_n_estimators_100': 0.959280303030303}
In: best_rf
Out: SklearnModel(model=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                          class_weight=None, criterion='gini',
                                          max_depth=None, max_features='auto',
                                          max_leaf_nodes=None, max_samples=None,
                                          min_impurity_decrease=0.0,
                                          min_impurity_split=None,
                                          min_samples_leaf=1,
                                          min_samples_split=2,
                                          min_weight_fraction_leaf=0.0,
                                          n_estimators=100, n_jobs=None,
                                          oob_score=False, random_state=None,
                                          verbose=0, warm_start=False),
             model_dir='/tmp/tmptw4pf82x')
```

**Comment by peastman** [comment]
Since you opened a new issue for that last question, I'm going to close this one.  If I missed something else you're still waiting for an answer on, feel free to reopen it.

**Comment by BJWiley233** [comment]
If my callable given `GridHyperparamOpt` doesn't include a parameter `model_dir` then sklearn validation.py complains with `TypeError: __init__() got an unexpected keyword argument 'model_dir'.  So if you try the tutorial with `def rf_model_builder(**model_params):` it won't run.  Anyone else experience this?

**Comment by peastman** [comment]
You're right, sorry.  It looks like the example code for GridHyperparamOpt is out of date.  We should fix it.  The [API docs for the parent class](https://deepchem.readthedocs.io/en/latest/api_reference/hyper.html#deepchem.hyper.HyperparamOpt.__init__) correctly describe it:

> This parameter must be constructor function which returns an object which is an instance of dc.models.Model. This function must accept two arguments, model_params of type dict and model_dir, a string specifying a path to a model directory. See the example.

**Comment by BJWiley233** [comment]
Ah ok thanks.  I didn't read the __init__ of the parent class.
