### ISSUE TITLE
Error in PDBbind data formatting

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#2279]
I am trying to use the `dc.dock` module with the PDBbind dataset to train a simple model to predict docking scores. I'm using this code:
```
vpg = dc.dock.pose_generation.VinaPoseGenerator()
complexes, scores = vpg.generate_poses(molecular_complex=('protein.pdb', 'ligand.pdb'),
                                       generate_scores=True,
                                      )
```
and getting this error:
```
  12687             the maximum number of iterations to perform. If this is 0, minimation is continued until the results converge without regard to how many iterations it takes. The default value is 0.
  12688         """
> 12689         return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
  12690 
  12691     if _newclass:

Exception: Particle coordinate is nan
```

which I think means that the local minimization in OpenMM is blowing up. `protein.pdb` and `ligand.pdb` are the first entries in PDBbind. I've tried different protein-ligand complexes and running on Colab and a local Jupyter server.

Any help on this would be appreciated.

CCing @peastman and @rbharath

**Comment by rbharath** [comment]
Yep, we should definitely fix this! As a couple requests, would it be possible for you to put together a small reproducing code snippet? I can run it locally and see what's going on here. If that's tricky to do, if you have the PDB code (the 4 character code for the protein in question), I can probably use that as well

**Comment by ncfrey** [comment]
So far it affects everything in PDBbind that I've tried; here's one example: `2d3u`. And you can actually just run `pdbfixer <protein.pdb>` on the command line to reproduce the error, since it looks like a problem with the PDBbind inputs. `pdbfixer` will warn that there are duplicate atoms, and then the local minimization will fail during the `addMissingAtoms` step. 

I'm trying to optimize in OpenMM to diagnose what is causing the blow ups.

**Comment by ncfrey** [comment]
Ok so this is an issue with the formatting in the PDBbind dataset from MolNet. I renamed the issue accordingly. If I download the PDB files directly from RCSB PDB, there are no problems.
