### ISSUE TITLE
Docs Build Failure

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2281]
Looks like we're getting some mysterious docs failures still: 

https://readthedocs.org/projects/deepchem/builds/12259262/

I'm not sure what the cause of this could be 

CC @nd-02110114

**Comment by rbharath** [comment]
Hmm, looks like the docs are passing but now the docs pages are missing? https://deepchem.readthedocs.io/en/latest/transformers.html is saying page not accessible for me 

<img width="1440" alt="Screen Shot 2020-11-05 at 12 53 30 PM" src="https://user-images.githubusercontent.com/1057676/98295162-fc4d1480-1f65-11eb-8d3f-b0a2d562a2fc.png">


CC @nd-02110114

**Comment by nd-02110114** [comment]
The correct link is https://deepchem.readthedocs.io/en/latest/api_reference/transformers.html

**Comment by nd-02110114** [comment]
I think it is better to add the redirect setting. Now, I'm looking into how to set the redirect link from https://docs.readthedocs.io/en/stable/user-defined-redirects.html

**Comment by nd-02110114** [comment]
I setted the redirect link for `transformer.html`, and it works well!  So, I will add all redirect link.

**Comment by nd-02110114** [comment]
I added the all redirect links. You confirmed from this page : https://readthedocs.org/dashboard/deepchem/redirects/
So I think this issue was resolved.

**Comment by rbharath** [comment]
Great! Thanks for fixing this @nd-02110114 :)
