### ISSUE TITLE
Migrating to Github Actions

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2289]
Travis CI just announced a new pricing plan. Under this plan, we're likely to run out of trial credits (which give us about 1000 minutes of linux build time) and will have to swap to a paid plan to keep using it:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Luckily @nd-02110114 has been looking into using Github actions for our CI and has made some progress there. I propose that we migrate our CI onto Github actions to prevent our CI build from shutting down as a priority.

CC @nd-02110114 @peastman @ncfrey @seyonechithrananda

**Comment by alat-rights** [comment]
Hey team <3 Will we have a roadmap or something for the migration, or is this kind of behind-the-scenes?

**Comment by alat-rights** [comment]
Here's a quick comment I want to make: We should probably be careful about binding ourselves further to Github infrastructure. After all, Github isn't open source on the server-side and as such it can get quite volatile. I think adopting something like Circle CI so we have a clearer exit strategy to Gitlab/Gitea/etc. in case things go south with Github the same way they did with Travis makes sense. Of course, if its a minor infrastructure burden then the concern is less pertinent.

**Comment by rbharath** [comment]
I'd be pretty open to us exploring Circle CI as well! Github Actions I think is nice to get in place because it's well supported and @nd-02110114 has done a lot of initial work to get us off the ground there. Longer term, having both Github actions and Circle CI in place seems smart :)

**Comment by peastman** [comment]
I wouldn't worry about it too much.  Switching CI systems just seems to be one of those things you need to do now and then.  I have another project that currently uses three(!) of them: Travis, Azure, and Jenkins.  And it used to use AppVeyor before we switched that build to Azure because it was too slow.  And now we're looking into replacing Travis with Github Actions.  It's a bit of a pain to switch, but not that big a deal.

**Comment by alat-rights** [comment]
Ah, that's fair enough! Thx for weighing in

**Comment by rbharath** [comment]
Closing this since we've migrated to Github actions (props to @nd-02110114 for leading the effort!)
