### ISSUE TITLE
mdtraj is LGPL licence

### ISSUE THREAD

**Issue by nd-02110114** [deepchem/deepchem#2291]
DeepChem depends on [mdtraj](https://github.com/mdtraj/mdtraj), but the license is LGPL.

Can DeepChem include the packages have GPL license...? 
I'm not familiar with the license, but I seem we avoid including the GPL package in the threads of PR #2287. 
So I made this issue.

**Comment by peastman** [comment]
Using packages with other licenses isn't a problem.  DeepChem just needs to have a GPL-compatible license, which MIT is.  It's only a problem if we actually incorporate GPL code into DeepChem.

**Comment by nd-02110114** [comment]
Thank you for comments! I could understand. These links are also helpful for me.

- https://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic
- https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL
- https://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible
- https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean
- https://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL
- https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
- https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic
