### ISSUE TITLE
Document molnet datasets

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#2292]
Many of the molnet loaders don't provide any useful documentation, either a description of what the dataset contains or a link to the source.  Examples include chembl, clearance, thermosol, hppb, and probably lots of others.  We need to track down the sources of these datasets and document them properly.

**Comment by rbharath** [comment]
Very much agreed on this one! I think we can use git blame to do a bit of detective work to start tracking down the contributing PRs for each dataset.
