### ISSUE TITLE
Bug: Tutorial 12_Predicting_Ki_of_Ligands_to_a_Protein throws ValueError

### ISSUE THREAD

**Issue by alat-rights** [deepchem/deepchem#2299]
Hello, I have successfully reproduced the following error reported by @xavierchee on Gitter. 

Steps to reproduce: simply load the 12_Predicting_Ki_of_Ligands_to_a_Protein.ipynb file as found on the Tutorials page using Google Colab and attempt to run it. 

I tried to figure out a fix but I can't seem to figure out how to add print statements to library files on Google Colab and that basically means I can't debug :c 

 As described by @xavierchee : 
```(a) When i reach this particular stage,
splitter = dc.splits.SpecifiedSplitter(dataset_file, "Model")
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset)
valid_dataset, test_dataset = test_dataset, valid_dataset
(b) The error that appeared was,
ValueError Traceback (most recent call last)
<ipython-input-23-8829a185af19> in <module>()
1 splitter = dc.splits.SpecifiedSplitter(dataset_file, "Model")
----> 2 train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset)
3 #NOTE THE RENAMING:
4 valid_dataset, test_dataset = test_dataset, valid_dataset
1 frames
/usr/local/lib/python3.6/dist-packages/deepchem/data/datasets.py in select(self, indices, select_dir, select_shard_size, output_numpy_dataset)
2325
2326 N = len(indices)
-> 2327 indices = np.array(indices).astype(int)
2328 tasks = self.get_task_names()
2329 n_shards = self.get_number_shards()
ValueError: invalid literal for int() with base 10: 'desc_canvas_aug30.csv'
```

**Comment by alat-rights** [comment]
@nd-02110114 This seems like it *could* be an unexpected consequence of your commit back in August, would you mind taking a look?

**Comment by xavierchee** [comment]
Thank you all =) Appreciate it.

**Comment by peastman** [comment]
We're in the middle of overhauling the whole tutorial sequence.  That particular tutorial is an obsolete one that will be getting deleted.  See #2112 for our current progress.

**Comment by alat-rights** [comment]
Ah I see, thx for letting me know. Will that take a while? If so, maybe we should throw a notice on the existing tutorials?

**Comment by xavierchee** [comment]
Thanks all. appreciate it =)  I agree with @alat-rights . If possible, would be good to have a notice in the tutorial =)

**Comment by alat-rights** [comment]
This tutorial is no longer in the tutorial list. Issue closed.
