### ISSUE TITLE
Bugs of sklearn model in deepchem-nightly edition

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [deepchem/deepchem#2309]
Hi, I tried to run a simple random forest classification model. It worked well in deepchem-stable edition both for small datasets and large datasets. But when it comes to deepchem-nightly edition. It works well when I load in small dataset (<3000 mols), but when I load a larger dataset (>10000 mols), it failed. 
 
Here is the ValueError:

> > ~/Software/Work/Anaconda/anaconda3/envs/deepchem-n/lib/python3.6/site-packages/sklearn/utils/multiclass.py in check_classification_targets(y)
>     170     if y_type not in ['binary', 'multiclass', 'multiclass-multioutput',
>     171                       'multilabel-indicator', 'multilabel-sequences']:
> --> 172         raise ValueError("Unknown label type: %r" % y_type)
>     173 
>     174 
> 
> ValueError: Unknown label type: 'unknown'

Here is the code:
` def model_builder(model_dir):
  sklearn_model = RandomForestClassifier(
      class_weight="balanced", n_estimators=500)
  return dc.models.SklearnModel(sklearn_model, model_dir)

  model_dir = "./model_dir/rf"
  model = dc.models.multitask.SingletaskToMultitask(tasks, model_builder)
  model.fit(train, nb_epoch=1)
`

It maybe a memory problem. Here is a note in class SklearnModel(Model):

>  Notes
>   -----
>   All `SklearnModels` perform learning solely in memory. This means that it
>   may not be possible to train `SklearnModel` on large `Dataset`s.
>   """
> https://github.com/deepchem/deepchem/blob/master/deepchem/models/sklearn_models/sklearn_model.py

It also likely be a type error. someone solved this Value Error by add the line 
`y=y.astype('int')`
https://stackoverflow.com/questions/45346550/valueerror-unknown-label-type-unknown

@rbharath , I'm not sure what's the real key. If it's a real type error, why it worked well for a small dataset. If it's a memory problem, why it worked well in deepchem-stable edition. Can you help me check the difference between the two editions?
What's more, I also downloaded the source code, but found it can't install successfully using your document (https://deepchem.readthedocs.io/en/latest/get_started/installation.html#from-source). Is there any suggestion or clear process?
Hoping for your early reply. Thank you.

Jane

**Comment by rbharath** [comment]
Sorry for the late reply; this fell behind in my inbox! My guess is that the larger dataset has mixed labels. Say 1/0/1.0/0.0. So the sklearn model gets confused if this is a regression or classification dataset. That's why casting to int makes it work out since it makes it unambiguous. Hope that helps!
