### ISSUE TITLE
Building models is too hard

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#232]
Currently it's pretty non-intuitive to build models in `deepchem`. The `tasks` and `task_types` arguments have to be constructed. A `params_dict` with all hyperparameters set has to be constructed (where most hyperparameters are not documented in the code). There are some steps we can take to make building new models easy:

- Remove `tasks` and `task_types` as arguments to all models. This information is usually only used to infer `n_tasks` which can be directly passed in anyways.
- Move `params_dict` into model constructors. Each model is parameterized by the choice of hyperparameters. These should be explicitly set in constructor so that hyperparameters are documented somewhere. This would also mean that default values can be set for hyperparameters so that beginners don't have to do much.
- Make `KerasModel` capable of accepting arbitrary `keras` models just as `SklearnModel` can accept arbitrary `scikit-learn` models.

Thanks to @evanfeinberg for the feedback that triggered this issue!

**Comment by rbharath** [comment]
All changes suggested here have been implemented in #233. Will go ahead and close this once that PR is merged in.

**Comment by evanfeinberg** [comment]
+2!

On Tue, Sep 20, 2016 at 8:52 PM, Bharath Ramsundar <notifications@github.com
