### ISSUE TITLE
RuntimeError: 1D target tensor expected, multi-target not supported

### ISSUE THREAD

**Issue by mufeili** [deepchem/deepchem#2323]
The error is located at [L203, SparseSoftmaxCrossEntropy](https://github.com/deepchem/deepchem/blob/master/deepchem/models/losses.py#L203), where `output` is of shape `(N, C)` and `labels` is of shape `(N, 1)`. In this case, `CrossEntropyLoss` expects `labels` to have shape `(N)` and we may fix that with `labels.squeeze(-1)`. Meanwhile, this loss function is supposed to support multitask as well and I'm not sure what will be the shape of `labels` in that case. Any suggestions @nd-02110114 ?

**Comment by nd-02110114** [comment]
In my understanding,
in the case of single task, SparseSoftmaxCrossEntropy expects 
labels have shape `(batch_size)` and outputs have shape `(batch_size, num_classes)`.
in the case of multi task, SparseSoftmaxCrossEntropy expects 
labels have shape `(batch_size, num_tasks)` and outputs have shape `(batch_size, num_tasks, num_classes)`.

**Comment by mufeili** [comment]
When I tried fitting a GCNModel on BACE, I encountered this error. It seems that `labels[0]` [here](https://github.com/deepchem/deepchem/blob/master/deepchem/models/torch_models/gcn.py#L352) is of shape `(batch_size, 1)`. Is this expected? If not, should I modify the code for `GCNModel` or `TorchModel._prepare_batch`?

**Comment by peastman** [comment]
Can you post an example that produces an error?

**Comment by mufeili** [comment]
> Can you post an example that produces an error?

See below. You may need to use the latest code in the master branch.

```python
import deepchem as dc
import torch.nn.functional as F
from deepchem.feat import MolGraphConvFeaturizer
from deepchem.molnet import load_bace_classification

tasks, all_dataset, transformers = load_bace_classification(featurizer=MolGraphConvFeaturizer(), splitter='scaffold')
train_set, val_set, test_set = all_dataset
model = dc.models.GCNModel(
            n_tasks=len(tasks),
            graph_conv_layers=[32],
            activation=F.relu,
            residual=False,
            batchnorm=False,
            dropout=0.,
            predictor_hidden_feats=32,
            predictor_dropout=0.,
            mode='classification',
            n_classes=2,
            learning_rate=3e-4)
model.fit(train_set, nb_epoch=1)
```

**Comment by nd-02110114** [comment]
I understood the situation. I think there are two options.

- Modify the return shape of label about load_bace_classification.
  - Maybe we need to modify the other load_XXX function as well.
- Modify `_prepare_batch` of `GCNModel `
  - Maybe, we need to modify the other models as well.

Given the first option brings the breaking change, I think the second option is better.

**Comment by mufeili** [comment]
Can we modify the [`_prepare_batch`](https://github.com/deepchem/deepchem/blob/f49416bede5efb9f3241a9ce538fc894e9670eaf/deepchem/models/torch_models/torch_model.py#L834) function of the base class `TorchModel` instead?

**Comment by nd-02110114** [comment]
Why do you want to modify the _prepare_batch function of the base class `TorchModel`...? Is there any reasons?

I have understood this issue happens when using some specific loss function. TorchModel accepts various loss functions, so the modification affects all loss function if we modify the _prepare_batch function of the base class TorchModel. I thinks such a situation is not good. 

And, basically if user uses labels have the shape `(N, 1)`, it is better that the loss functions takes labels have the same shape. 
The implicit reshape may confuse user, so I think we should avoid it as much as possible.

**Comment by mufeili** [comment]
I see. Make sense. I will make a PR for that.
