### ISSUE TITLE
No ANIRegression model

### ISSUE THREAD

**Issue by dkurt** [deepchem/deepchem#2329]
## To Reproduce

```
$ python3 examples/roitberg/roitberg.py

Traceback (most recent call last):
  File "roitberg.py", line 229, in <module>
    model = dc.models.ANIRegression(
AttributeError: module 'deepchem.models' has no attribute 'ANIRegression'
```

## Environment

* OS: Ubuntu 18.04
* Python version: 3.6.9
* DeepChem version: 355954b37d333fc3e2c3b3e28d103297eb642769
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

**Comment by alat-rights** [comment]
I think that feature just isn't fully supported yet! @rbharath is that right?

**Comment by rbharath** [comment]
Yep, you're right @alat-rights!

We had a version of ANIRegression implemented before in custom tensorflow, but I think it's been made somewhat obsolete by the new torch-ani library. We should re-implement using Torch-ani under the hood but this would be a bit of a project to take on

**Comment by dkurt** [comment]
Thanks @alat-rights and @rbharath. I'll take a look at PyTorch implementation.
