### ISSUE TITLE
Can sklearn model (random forest) save and restore in deepchem?

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [deepchem/deepchem#2333]
I found we can't restore the random forest model in deepchem. Is is a bug? Can anyone show me how to save it and restore it when we need to predict? Thanks.

**Comment by rbharath** [comment]
You should be able to save and reload it. I think one gotcha is that the reload is slightly different than for `KerasModel`. So it would be something like

```
model.save()
...
new_model.reload()
```

**Comment by Jiang-Lu-CAS** [comment]
> new_model.reload()

got it, thank you~

**Comment by xuwei-song** [comment]
sry, i can't follow. Why new_model.reload() rather than model.reload()? And Problem2 is that why not restore()?
