### ISSUE TITLE
DeepChem 2.4.0 Release

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2343]
At this time I think we're ready to make the DeepChem 2.4.0 release. The only possible release blocker is #2334 which shows some disconcerting RDKit featurization failures. I'm starting this issue up to coordinate the needed work:

- We need to figure out what's going on in #2334 and make a call on whether it needs to be fixed before 2.4.0. If so, then it's a critical blocker bug. I took a look and I'm kind of stumped. Could I get a volunteer to take a crack at this?
- I've started up release notes on https://docs.google.com/document/d/17eEYcNEZq2g97d6W79TN0usHAo_9xKp6NlTgC_lGTpo/edit?usp=sharing (anyone can comment with this link) which I'll flesh out over the coming week. Feel free to add on or comment 
- @nd-02110114 has put together some beautiful release notes here https://github.com/deepchem/deepchem/blob/master/notes/release.md. Following these notes, we need to make a release PR that bumps the `deepchem/__init__.py` version and a subsequent PR to the conda feedstock repo to bump the version and finally do a manual docker version bump.

I'm hoping we can get this done over the next two weeks. 

CC @peastman @nd-02110114 @ncfrey @seyonechithrananda @mufeili (and other folks too of course!). Would one of you be willing to volunteer to take a look at #2334?

**Comment by nd-02110114** [comment]
@rbharath
I'm looking forward to see the official new release!
I added a comment in #2334, and I will make the note for release process more careful in a couple of days.

**Comment by rbharath** [comment]
We have a workaround for #2334 merged in as #2351 so I'm starting off the process of the release in #2352. This is the first release we've made in a long time so it might take an iteration or two to get this right. I'll be continuing work on the release through the rest of this week and I'm hoping we can get it out the door by Friday

**Comment by rbharath** [comment]
I've just tagged the 2.4.0 release here! https://github.com/deepchem/deepchem/releases/tag/2.4.0.

We still have a number of TODOs to do here:

- Finish drafting release notes
- Bump conda-forge version
- Bump docker build version

**Comment by rbharath** [comment]
Got a conda-forge feedstock PR up for review at https://github.com/conda-forge/deepchem-feedstock/pull/5

**Comment by rbharath** [comment]
@nd-02110114 has kindly taken care of the docker release and the release notes are out. Thanks to everyone who contributed! Going to close out this issue.
