### ISSUE TITLE
dtype of `y` array in `DiskDataset` depends on whether `X` is accessed beforehand

### ISSUE THREAD

**Issue by jcwomack** [deepchem/deepchem#2355]
## 🐛 Bug

```
_, datasets, _ = dc.molnet.load_hiv(
    featurizer=dc.feat.RawFeaturizer(smiles=False),
    splitter=None,   # no splitting
    transformers=[]  # no transformation
)
print(datasets[0].y.dtype)
```
outputs
```
object
```

but
```
_, datasets, _ = dc.molnet.load_hiv(
    featurizer=dc.feat.RawFeaturizer(smiles=False),
    splitter=None,   # no splitting
    transformers=[]  # no transformation
)
print(datasets[0].X.dtype)
print(datasets[0].y.dtype)
```
outputs
```
object
float64
```

In the first case `y` has a `dtype` of `object`, but in the second case it has a `dtype` of `float64`

## To Reproduce

See above.

This is for DeepChem version 2.4.0-rc1.dev, installed via pip.

## Expected behavior

The `dtype` to consistently be `float64`

## Environment

* OS: Ubuntu 18.04. LTS
* Python version: 3.8.6
* DeepChem version: 2.4.0-rc1.dev
* RDKit version (optional): 2020.09.3

**Comment by rbharath** [comment]
Oh this is a strange bug! I'm not sure what could be causing this type change. It's probably relatively harmless, but mildly disconcerting that the type changes like that. We should fix it for code stability.

CC @peastman in case he's interested

**Comment by jcwomack** [comment]
Thanks for responding. My thoughts were that this might be due to some combination of the datatype being automatically determined and behind-the-scenes caching of the loaded datasets..

**Comment by peastman** [comment]
I finally got around to investigating this.  In `get_shard()` we load the `y` vector like this:

https://github.com/deepchem/deepchem/blob/6956e1d02ad141eafb80c1e0df2d26397442ea26/deepchem/data/datasets.py#L2105-L2106

But in `get_shard_y()`, for some reason we force the dtype to be `object`:

https://github.com/deepchem/deepchem/blob/6956e1d02ad141eafb80c1e0df2d26397442ea26/deepchem/data/datasets.py#L2183-L2184

I have no idea why it's doing that.  It seems wrong to me.  There are a few other places where it similarly forces dtypes to be `object`, such as in `get_shard_w()` and everywhere we load IDs.
