### ISSUE TITLE
load_pdbbind featurizer does not work

### ISSUE THREAD

**Issue by SaharRohaniZ** [deepchem/deepchem#2357]
## ❓ Questions & Help

I am using Deepchem version  2.4.0 and Sklearn version 0.22.2.post1. I am trying to use featurizer in load_pdbbind but I get an error:

**My code**: 

pdbbind_tasks, pdbbind_datasets, transformers = load_pdbbind(featurizer="grid", split="random", subset="core")

**Error that I get:** 

usr/local/lib/python3.6/dist-packages/deepchem/molnet/load_function/molnet_loader.py in __init__(self, featurizer, splitter, transformer_generators, tasks, data_dir, save_dir, **kwargs)
    117       logger.warning("'split' is deprecated.  Use 'splitter' instead.")
    118     if isinstance(featurizer, str):
--> 119       featurizer = featurizers[featurizer.lower()]
    120     if isinstance(splitter, str):
    121       splitter = splitters[splitter.lower()]

KeyError: 'grid'

Any help or guidance on this would mean alot. Thanks

**Comment by ncfrey** [comment]
Hi @SaharRohaniZ, the PDBBind loader was recently updated with the new MolNet template. You can read the new documentation [here](https://deepchem.readthedocs.io/en/latest/api_reference/moleculenet.html#pdbbind-datasets).
You could try something like 
`tasks, datasets, transformers = load_pdbbind(featurizer=RdkitGridFeaturizer(flatten=True), subset='refined')`

**Comment by SaharRohaniZ** [comment]
Hi @ncfrey  - Thanks for your help. I am now getting the following error:

NameError: name 'RdkitGridFeaturizer' is not defined

Unfortunately I couldn't find anything on the documentation that could help me solve this problem. I am using Google Colab, Deep chem verion 2.4 and Tensorflow version 2.3.

I don't know what's the issue. I appreciate your further input on this matter. Thank you.

**Comment by ncfrey** [comment]
No problem! You can import `RdkitGridFeaturizer` by doing
`from deepchem.feat.complex_featurizers import RdkitGridFeaturizer`

All the complex featurizers are [here](https://github.com/deepchem/deepchem/tree/master/deepchem/feat/complex_featurizers).

**Comment by SaharRohaniZ** [comment]
Thank you so much @ncfrey . This has solved the problem. Closing the issue.
