### ISSUE TITLE
MolGraphConvFeaturizer unable to featurize simple molecules

### ISSUE THREAD

**Issue by ujvl** [deepchem/deepchem#2363]
## 🐛 Bug

MolGraphConvFeaturizer errors in some simple cases (as below). I don't run into the error with other featurizers.

## To Reproduce

Run:
```
dc.feat.MolGraphConvFeaturizer().featurize("C")
```

Error:
```
Failed to featurize datapoint 0, O. Appending empty array
Exception message: zero-size array to reduction operation maximum which has no identity
```

Looks like the error happens in GraphData due to an empty array:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "deepchem/feat/molecule_featurizers/mol_graph_conv_featurizer.py", line 221, in _featurize
    edge_features=bond_features)
  File "deepchem/feat/graph_data.py", line 67, in __init__
    elif np.max(edge_index) >= len(node_features):
  File "<__array_function__ internals>", line 6, in amax
  File "anaconda3/envs/chem/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "anaconda3/envs/chem/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

## Expected behavior

Features should be returned without error

## Environment

OS: Ubuntu
Python version: 3.6
DeepChem version: 2.4.0-rc1.dev
RDKit version (optional): 2020.09.1
TensorFlow version (optional): 1.6.0
TensorFlow version (optional): 2.3.0

## Additional context

ESOL contains this sample, which is why I ran into the error.

**Comment by nd-02110114** [comment]
Unfortunately,  this is a corner case. 
`MolGraphConvFeaturizer` usually construct general graphs which have  more than two nodes and more than one edge. 
This means the input SMILES must have more than two elements. (The featurizer doesn't consider implicit hydrogen atoms as nodes.)

**Comment by rbharath** [comment]
Good suggestion! We should either throw an informative error or handle the corner case elegantly for 'C'. I've run into this issue before too when playing with different featurizers in ipython

**Comment by nd-02110114** [comment]
> I've run into this issue before too when playing with different featurizers in ipython

Which featurizer did you use?

**Comment by rbharath** [comment]
It might have been `MolGraphConvFeaturizer()` now that I'm thinking about it!

**Comment by raminans** [comment]
Yes, it is MolGraphConvFeaturizer().  It fails to featurize simple molecules like water.  Were you be able to fix this issue? Any suggestions? 

Thanks!
