### ISSUE TITLE
Failed to featurize datapoint 4777. Appending empty array

### ISSUE THREAD

**Issue by SaharRohaniZ** [deepchem/deepchem#2366]
## ❓ Questions & Help

Hi- I am trying to load PDBbind dataset and apply Grid featurizer but I get error. 

**My code:**
from deepchem.feat.complex_featurizers import RdkitGridFeaturizer
pdbbind_tasks, pdbbind_datasets, transformers = load_pdbbind(featurizer=RdkitGridFeaturizer(flatten=False), splitter="random", subset="refined")
train_dataset, valid_dataset, test_dataset = pdbbind_datasets

**Error:**
Failed to featurize datapoint 4777. Appending empty array.

Note: this error is triggered for each and every data points. For my case, is 4777 rows of error.

Any help on this issue would mean a lot. Thank you in advance for your help.

**Comment by rbharath** [comment]
Hmm, this is definitely a serious error in our structural featurization! I've marked this as a bug for us to investigate.

CC @ncfrey who has also been working on the structural featurizations
