### ISSUE TITLE
AttributeError: module 'deepchem.molnet' has no attribute 'load_pdbbind_grid'

### ISSUE THREAD

**Issue by PeterGPH** [deepchem/deepchem#2367]
## ❓ Questions & Help

Hi! I am trying to work on tutorial 13 and when I run the following codes
pdbbind_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(
    featurizer='ECFP', subset='refined')
the bug in title was reported. the version of my deepchem is 2.4.0.
Any help is highly appreciated! Thanks for in advance help:)

**Comment by ncfrey** [comment]
Hi @PeterGPH, the MolNet pdbbind loader has been updated and `load_pdbbind_grid` is no longer supported. There's also an overhaul of Tutorial 13 in the works that you can see here #2364

**Comment by rbharath** [comment]
My apologies for missing this in our DeepChem 2.4.0 release notes! I've updated the notes to note that `load_pdbbind_grid` is no longer supported https://forum.deepchem.io/t/deepchem-2-4-0-release-notes/340/3

**Comment by PeterGPH** [comment]
Thanks for your help @ncfrey  @rbharath, which solve my problem:). 
Best regards!
