### ISSUE TITLE
Implement gnina backend for molecular docking with CNNs

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#2372]
## 🚀 Feature

Currently, DeepChem's `docking` module supports only AutoDock Vina and is more of a utility, since it does not directly do anything deep learning-related. I'm interested in implementing a GPU-accelerated / deep learning-powered molecular docking backend. @rbharath suggested [gnina](https://github.com/gnina/gnina) as a possibility. 

## Motivation

Molecular docking is computationally expensive and a standard part of virtual screening workflows. I think it makes sense to offer some accelerated docking capabilities as DeepChem continues to add support for proteins and protein-ligand interactions. `gnina` in particular seems well maintained (most recent commit 11 days ago, 200+ contributors, ~6000 commits). It is available under the Apache license (rather than MIT), so I'm not sure if that causes a problem. Here is the [paper](http://pubs.acs.org/doi/full/10.1021/acs.jcim.6b00740) describing the implementation.

CCing @rbharath and @peastman for feedback.

**Comment by rbharath** [comment]
I'd be a big fan of this! I believe that gnina just had its first stable release so it would be a powerful backend to add to `dc.dock` to make available here. I believe the Apache license should be just fine.

CC @dkoes in case he's interested in following along. For context, DeepChem provides a programmatic docking API `dc.dock`. We currently have only autodock vina as a backend but would love to be able to add gnina as a backend now that the stable 1.0 version is out. @ncfrey has been leading our efforts in building out tutorials/infrastructure for building out our docking infrastructure
