### ISSUE TITLE
Failed to run Deepchem Tutorial Part 15

### ISSUE THREAD

**Issue by greenaway0824** [deepchem/deepchem#2379]
I can't avoid the error message while I am running Deepchem Tutorial Part 15 on Colab.
Please help me.

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.

**Comment by rbharath** [comment]
I'm able to confirm the error. It happens when running the code:

```
class DigitGAN(dc.models.WGAN):

  def get_noise_input_shape(self):
    return (10,)

  def get_data_input_shapes(self):
    return [(28, 28, 1)]

  def create_generator(self):
    return tf.keras.Sequential([
        Dense(7*7*8, activation=tf.nn.relu),
        Reshape((7, 7, 8)),
        Conv2DTranspose(filters=16, kernel_size=5, strides=2, activation=tf.nn.relu, padding='same'),
        Conv2DTranspose(filters=1, kernel_size=5, strides=2, activation=tf.sigmoid, padding='same')
    ])

  def create_discriminator(self):
    return tf.keras.Sequential([
        Conv2D(filters=32, kernel_size=5, strides=2, activation=tf.nn.leaky_relu, padding='same'),
        Conv2D(filters=64, kernel_size=5, strides=2, activation=tf.nn.leaky_relu, padding='same'),
        Dense(1, activation=tf.math.softplus)
    ])

gan = DigitGAN(learning_rate=ExponentialDecay(0.001, 0.9, 5000))
```

The stack trace is 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-ae2e77521692> in <module>()
     22     ])
     23 
---> 24 gan = DigitGAN(learning_rate=ExponentialDecay(0.001, 0.9, 5000))

4 frames
/usr/local/lib/python3.6/dist-packages/deepchem/models/gan.py in __init__(self, gradient_penalty, **kwargs)
    500     """
    501     self.gradient_penalty = gradient_penalty
--> 502     super(WGAN, self).__init__(**kwargs)
    503 
    504   def _call_discriminator(self, discriminator, inputs, train):

/usr/local/lib/python3.6/dist-packages/deepchem/models/gan.py in __init__(self, n_generators, n_discriminators, **kwargs)
    122           gen_output = [gen_output]
    123         discrim_gen_outputs.append(
--> 124             self._call_discriminator(discriminator, gen_output, False))
    125       self.discrim_variables += discriminator.trainable_variables
    126 

/usr/local/lib/python3.6/dist-packages/deepchem/models/gan.py in _call_discriminator(self, discriminator, inputs, train)
    507       return penalty(inputs, self.conditional_input_layers)
    508     return discriminator(
--> 509         _list_or_tensor(inputs + self.conditional_input_layers))
    510 
    511   def create_generator_loss(self, discrim_output):

/usr/local/lib/python3.6/dist-packages/deepchem/models/gan.py in _list_or_tensor(inputs)
    444 
    445 def _list_or_tensor(inputs):
--> 446   if len(inputs) == 1:
    447     return inputs[0]
    448   return inputs

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/keras_tensor.py in __len__(self)
    238 
    239   def __len__(self):
--> 240     raise TypeError('Keras symbolic inputs/outputs do not '
    241                     'implement `__len__`. You may be '
    242                     'trying to pass Keras symbolic inputs/outputs '

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.
```
I'm not sure why this isn't getting caught by our test suite... I'll mark this as a bug and try to take a closer look tomorrow.

CC @peastman who might know more about the GAN infrastructure

**Comment by peastman** [comment]
It works fine for me.  What version of TensorFlow do you have installed?  I have 2.2.0rc3.

**Comment by rbharath** [comment]
I tried running this on Colab and saw the failure, but I haven't tried running on my local TF (which is also 2.2.0). Possibly an issue in the latest TF versions?

**Comment by greenaway0824** [comment]
Yes. It seems that this problem has been solved with the downgrade.
However, another error as below comes up.

AttributeError                            Traceback (most recent call last)
<ipython-input-6-8bc8440779ef> in <module>()
     23 
     24 #gan = DigitGAN(learning_rate=ExponentialDecay(0.001, 0.9, 5000))
---> 25 gan = DigitGAN(learning_rate=0.001)

2 frames
/usr/local/lib/python3.6/dist-packages/deepchem/models/gan.py in <listcomp>(.0)
     87     for shape in self.get_data_input_shapes():
     88       self.data_input_layers.append(Input(shape=shape))
---> 89     self.data_inputs = [i.ref() for i in self.data_input_layers]
     90     self.conditional_input_layers = []
     91     for shape in self.get_conditional_input_shapes():

AttributeError: 'Tensor' object has no attribute 'ref'

**Comment by peastman** [comment]
`ref()` was added in TensorFlow 2.2.  What version were you using before, and what version did you downgrade to?

**Comment by greenaway0824** [comment]
> `ref()` was added in TensorFlow 2.2. What version were you using before, and what version did you downgrade to?

Tensorflow 2.2.0-beta
Thanks.

**Comment by greenaway0824** [comment]
Thanks so much. It works beautifully with the following revision.

!pip uninstall tensorflow -y
!pip install  tensorflow==2.2.0

**Comment by peastman** [comment]
I can reproduce the error with TensorFlow 2.4.1.  I'll try to figure out what's going on.

**Comment by peastman** [comment]
The fix is in #2381.  They changed the type of object returned by models from Tensor to KerasTensor.

**Comment by greenaway0824** [comment]
Thanks for the help.
I've run every part of the tutorial and a few of them including this one don't work.
I will post them.

**Comment by greenaway0824** [comment]
It is turning out that the problems in the tutorial are due to the same version issue mentioned here and there is nothing to revise after the version adjustment.
Thanks.
