### ISSUE TITLE
CGCNN featuriser is not working

### ISSUE THREAD

**Issue by VIGNESHinZONE** [deepchem/deepchem#2385]
## To Reproduce
```
import deepchem as dc
dataset_config = {
      "reload": False,
      "featurizer": dc.feat.CGCNNFeaturizer,
      "transformers": [],
      "featurizer_kwargs": {
        'max_neighbors': 12
      },
      "transformer_kwargs": {},
    }
tasks, datasets, transformers = dc.molnet.load_perovskite(**dataset_config)
train, valid, test = datasets
```
Code in this colab [notebook](https://colab.research.google.com/drive/1bEsghp49n_GoQdZ44omYz2b9IQnO2-IB?usp=sharing)
## Expected behavior
![Screenshot from 2021-02-04 21-45-05](https://user-images.githubusercontent.com/45672459/106931034-2c11e100-673c-11eb-97a6-fb0fc1e00230.png)

## Additional context

I had tried debugging this code using VS code and I found what the problem was but unable to fix it.  On this [line](https://github.com/VIGNESHinZONE/deepchem/blob/4eb804f96fb5454a5f2031d1c81ca9727528d878/deepchem/data/data_loader.py#L686) self.featuriser must access the Featuriser Class [here](https://github.com/VIGNESHinZONE/deepchem/blob/4eb804f96fb5454a5f2031d1c81ca9727528d878/deepchem/feat/base_classes.py#L67 ) followed by the MaterialStructureFeaturizer over [here](https://github.com/VIGNESHinZONE/deepchem/blob/4eb804f96fb5454a5f2031d1c81ca9727528d878/deepchem/feat/base_classes.py#L336). For some reason it does not go through the Featuriser class. Im trying to fix debug the CGCNN model and it will be helpful if someone could fix this error quickly as Im working on collab.

**Comment by nd-02110114** [comment]
i think you need to instantiate the featurizer.

**Comment by VIGNESHinZONE** [comment]
thanks got it working
