### ISSUE TITLE
Implementation of PAGTN: Path-Augmented Graph Transformer Network

### ISSUE THREAD

**Issue by VIGNESHinZONE** [deepchem/deepchem#2389]
I had recently come across this paper [PAGTN](https://arxiv.org/pdf/1905.12712.pdf) and [code](https://github.com/benatorc/PA-Graph-Transformer). This model uses a transformer-based approach on Graph Neural Networks such that each atom is connected to each other. Its mainly used for molecule property prediction.

I was planning to implement this paper into deepchem, Please let me know if this model will be a useful addition to deepchem repo and also if anyone is already working on it.

@mufeili Could you please let me know about your thoughts on this, as @rbharath had asked me to confirm with you before I start working on this as it was based on GNNs & Graph Representation of Molecules and wasn't sure if it was to be added in the [dgl-lifesci](https://github.com/awslabs/dgl-lifesci) repo or Deepchem's. Either way, I was planning to implement it on Pytorch and DGL, but it requires a little bit of feature preprocessing.

**Comment by mufeili** [comment]
I haven't started working on this model and I'm looking forward to your work. Feel free if you need any help.

**Comment by rbharath** [comment]
Looking forward to seeing this PR come together!

**Comment by rbharath** [comment]
Closing since implemented
