### ISSUE TITLE
tutorial 1: model.fit Not implemented error

### ISSUE THREAD

**Issue by wendong-wang** [deepchem/deepchem#2392]
## 🐛 Bug

I reinstalled latest anaconda with python 3.8 and installed tensor flow 2.3 and deepchem 2.4.0, all as instructed by the docs. 
When I run the line model.fit(train_dataset, nb_epoch=100), the following error occurred: 

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-b4948f1975af> in <module>
----> 1 model.fit(train_dataset, nb_epoch=100)

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\deepchem\models\keras_model.py in fit(self, dataset, nb_epoch, max_checkpoints_to_keep, checkpoint_interval, deterministic, restore, variables, loss, callbacks, all_losses)
    318     The average loss over the most recent checkpoint interval
    319    """
--> 320     return self.fit_generator(
    321         self.default_generator(
    322             dataset, epochs=nb_epoch,

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\deepchem\models\keras_model.py in fit_generator(self, generator, max_checkpoints_to_keep, checkpoint_interval, restore, variables, loss, callbacks, all_losses)
    407         inputs = inputs[0]
    408 
--> 409       batch_loss = apply_gradient_for_batch(inputs, labels, weights, loss)
    410       current_step = self._global_step.numpy()
    411 

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    821       # This is the first call of __call__, so we have to initialize.
    822       initializers = []
--> 823       self._initialize(args, kwds, add_initializers_to=initializers)
    824     finally:
    825       # At this point we know that the initialization is complete (or less

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\def_function.py in _initialize(self, args, kwds, add_initializers_to)
    694     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    695     self._concrete_stateful_fn = (
--> 696         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    697             *args, **kwds))
    698 

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2853       args, kwargs = None, None
   2854     with self._lock:
-> 2855       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2856     return graph_function
   2857 

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3063     arg_names = base_arg_names + missing_arg_names
   3064     graph_function = ConcreteFunction(
-> 3065         func_graph_module.func_graph_from_py_func(
   3066             self._name,
   3067             self._python_function,

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\framework\func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

NotImplementedError: in user code:

    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\deepchem\models\keras_model.py:474 apply_gradient_for_batch  *
        grads = tape.gradient(batch_loss, vars)
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\backprop.py:1067 gradient  **
        flat_grad = imperative_grad.imperative_grad(
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\imperative_grad.py:71 imperative_grad
        return pywrap_tfe.TFE_Py_TapeGradient(
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\eager\backprop.py:162 _gradient_function
        return grad_fn(mock_op, *out_grads)
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\ops\math_grad.py:470 _UnsortedSegmentSumGrad
        return _GatherDropNegatives(grad, op.inputs[1])[0], None, None
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\ops\math_grad.py:436 _GatherDropNegatives
        array_ops.ones([array_ops.rank(gathered)
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\ops\array_ops.py:3041 ones
        output = _constant_if_small(one, shape, dtype, name)
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\ops\array_ops.py:2732 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:5 prod
        
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\numpy\core\fromnumeric.py:3030 prod
        return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\numpy\core\fromnumeric.py:87 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    C:\ProgramData\Anaconda3\envs\deepChem\lib\site-packages\tensorflow\python\framework\ops.py:845 __array__
        raise NotImplementedError(

    NotImplementedError: Cannot convert a symbolic Tensor (gradient_tape/private__graph_conv_keras_model/graph_gather/sub:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

## To Reproduce

1. I just followed tutorial 1. 
2.
3.

## Environment

* OS: windows 10
* Python version: 3.8.6
* DeepChem version: 2.4.0
* RDKit version (optional): 2020.09.4
* TensorFlow version (optional): 2.3.0
* PyTorch version (optional): none
* Any other relevant information:

**Comment by wendong-wang** [comment]
I have also tried on the following environment, but also got an error message: 

OS: Mac OS Big Sur
Python version: 3.7.9
DeepChem version: 2.4.0
RDKit version: 2020.03.6
TensorFlow version: 2.3.0
PyTorch version: none

**Comment by wendong-wang** [comment]
The problem appears to be related to the Tensorflow version. The following combination of packages is working: 
Python version: 3.6.9
DeepChem version: 2.5.0.dev
RDkit version: 2020.09.4
TensorFlow version: 2.4.1

**Comment by rbharath** [comment]
This looks to be caused by a version mismatch between the DeepChem / TF version as you point out. In theory all of the package versions you list should be able to work together but perhaps it's possible there are multiple deepchem/tf versions and the environment is getting confused. Making a fresh clean environment might be the way to go

**Comment by rbharath** [comment]
Going to go ahead and close. Let me know if this is still an issue and reopen
