### ISSUE TITLE
tutorial 5, TorchModel problem

### ISSUE THREAD

**Issue by wendong-wang** [deepchem/deepchem#2393]
## 🐛 Bug

I try to run the Torch Model portion of the tutorial, the following error message appeared: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-25acb29ec5b2> in <module>
      7     torch.nn.Linear(1000, 1)
      8 )
----> 9 model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())
     10 
     11 model.fit(train_dataset, nb_epoch=50)

AttributeError: module 'deepchem.models' has no attribute 'TorchModel'

## To Reproduce

1. just follow the tutorial
2.
3.

## Environment

* OS: windows 10
* Python version: 3.8.6
* DeepChem version: 2.4.0
* RDKit version (optional): 2020.09.4
* TensorFlow version (optional): 2.3.0
* PyTorch version (optional): 1.6.0
* Any other relevant information:

**Comment by peastman** [comment]
Are you sure it isn't actually using an older version?  That class was added in 2.4.  For example, you might have multiple DeepChem versions installed in different conda environments.

**Comment by wendong-wang** [comment]
Thanks. I found the following combination that works: 

Python version: 3.6.9
DeepChem version: 2.5.0.dev
RDkit version: 2020.09.4
TensorFlow version: 2.4.1
PyTorch: 1.4.0
