### ISSUE TITLE
Featurized and split ACNN datasets

### ISSUE THREAD

**Issue by SaharRohaniZ** [deepchem/deepchem#2398]
## ❓ Questions & Help

Hi everyone,

I came across the featurized and split ACNN dataset here (https://github.com/deepchem/deepchem/blob/master/contrib/atomicconv/acnn/core/get_acnn_core.sh ) and I want to know what kind of featurizer have been used to featurize this dataset? and what does it mean ACNN dataset? (does this mean the same dataset was used to produce the work in ACNN paper?) or is ACNN a model ?

Thanks,
Sahar

**Comment by rbharath** [comment]
Sorry for the slow response! I think this was featurized with the AtomicConvolution featurizer. There's no good tutorial/guide on how to do this and the code itself is broken but we're working to fix `AtomicConvolution` now. Here ACNN means `AtomicConvolutionModel`

**Comment by SaharRohaniZ** [comment]
Thank you for your response.
