### ISSUE TITLE
Issue with "Tutorial Part 13: Modeling Protein-Ligand Interactions"

### ISSUE THREAD

**Issue by SaharRohaniZ** [deepchem/deepchem#2399]
## ❓ Questions & Help

Hi Deepchem team,
I am running tutorial 13 and I ran into an issue when loading pdbbind refined dataset using dc.molnet.load_pdbbind .The tutorial originally loaded a smaller pdbbind dataset from dc.data.NumpyDataset. I tried this and it works perfectly fine. But when loading refined/core dataset, I run into this error:

_did not match C++ signature:
    GetMorganFingerprintAsBitVect(RDKit::ROMol mol, int radius, unsigned int nBits=2048, boost::python::api::object invariants=[], boost::python::api::object fromAtoms=[], bool useChirality=False, bool useBondTypes=True, bool useFeatures=False, boost::python::api::object bitInfo=None, bool includeRedundantEnvironments=False)
Failed to featurize datapoint 17089, ('/tmp/v2019-other-PL/5llc/5llc_ligand.sdf', '/tmp/v2019-other-PL/5llc/5llc_protein.pdb'). Appending empty array
Exception message: Python argument types in
    rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect(tuple, int)_

I got this error for every single datapoint. I don't know if this is a bug so raised this as a Questions & Help. Any guidance on this matter would mean a lot.

Thanks,
Sahar

**Comment by rbharath** [comment]
Hmm, good question. 

@ncfrey Have you run into this sort of failure before?

**Comment by ncfrey** [comment]
Hi @SaharRohaniZ, I haven't seen that error before. The loader should be able to download the entire PDBBind or the refined set; we actually don't have the core set as an option yet, although that would be easy to add. Are you using the Morgan fingerprint from Rdkit to featurize the dataset? I think that will fail because it's not a `ComplexFeaturizer`.

**Comment by SaharRohaniZ** [comment]
Hi @ncfrey . I tried to load Refined dataset and I faced the same issue. I used dc.feat.CircularFingerprint() featurizer just like the tutorial.

**Comment by SaharRohaniZ** [comment]
@ncfrey : I am now using dc.feat.ConvMolFeaturizer() to load pdbbind refined dataset but I am getting below error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-ebd81afb015b> in <module>()
      2 test=dc.feat.ConvMolFeaturizer()
      3 pdbbind_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(
----> 4 featurizer=test(molecules_set), set_name="refined",reload=True)

2 frames
/usr/local/lib/python3.6/dist-packages/deepchem/molnet/load_function/pdbbind_datasets.py in create_dataset(self)
     40 
     41     # load and featurize each complex
---> 42     features = self.featurizer.featurize(list(zip(ligand_files, protein_files)))
     43     dataset = dc.data.DiskDataset.from_numpy(features, y=labels, ids=pdbs)
     44 

AttributeError: 'numpy.ndarray' object has no attribute 'featurize'`

**Comment by ncfrey** [comment]
Should be closed by recent PRs. See e.g. Tutorial 14 from #2431
