### ISSUE TITLE
Deepchem GraphConvModel Interpretability using captum

### ISSUE THREAD

**Issue by prakriti19439** [deepchem/deepchem#2400]
## ❓ Questions & Help

I am trying to use captum integrated gradients for the interpretability of the graph conv model in deepchem. Basically I have made a binary classification model and I am giving input as smiles and I get the prediction probability. Now for explainabilty,I want to represent the smiles as molecule structure and highlight the portion of molecule with green which contributes towards the model giving output close to value of 1.
(A) ig = IntegratedGradients(model)
(B) attr, delta = ig.attribute((x_user_smile), target=1, return_convergence_delta=True)
I am getting this error in line (B).
TypeError: GraphConvModel(batch_normalize=None, batch_size=32, dense_layer_size=None,
               dropout=None, graph_conv_layers=None, mode='classification',
               n_classes=2, n_tasks=1, number_atom_features=None,
               uncertainty=False) is not a callable object

model is a callable object since I have called it while predicting (model.predict).

**Comment by rbharath** [comment]
Just seeing this here on github. Copying over my suggestion from gitter: I think no one has tried captum with deepchem before. You might have to make a callable wrapper since `model` does not implement the `__call__` function
