### ISSUE TITLE
Adding a Protein Transformer Model before GSoC?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2404]
There's been some interest in adding a protein transformer model into DeepChem, most recently as a proposed GSoC project (https://wiki.openchemistry.org/GSoC_Ideas_2021#DeepChem_Project_Ideas).

@yuanqidu: You mentioned on the last developer call that you were potentially interested in taking this on as a side project now. If you think you could put together a rough implementation before GSoC starts, we could shift the GSoC proposed project to be more focused on datasets/benchmarks (potentially integrating with https://github.com/songlab-cal/tape).

Starting up a thread to discuss. Tagging @seyonechithrananda who has also been interested in better protein transformer support

**Comment by yuanqidu** [comment]
Yeah, I am very interested in this topic and the idea you proposed was great. But I am not sure if I have enough time to implement this alone. I wonder whether anyone else would like to work together on this?

**Comment by rbharath** [comment]
I can probably help review/plan but probably not enough time on my end to do implementation work right now

**Comment by yuanqidu** [comment]
Cool. Maybe let's wait for other folks who are also interested and would like to collaborate on it.
