### ISSUE TITLE
Installing DeepChem on Google Colab fail

### ISSUE THREAD

**Issue by JohnMommers** [deepchem/deepchem#2411]
I install DeepChem on Google Colab by using:

!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e

!pip install --pre deepchem

From today my scripts  give an error. It seems that not all RDKIT packages are fully installed? See error:
     11 
     12 from rdkit import rdBase
---> 13 from rdkit.DataStructs import cDataStructs
     14 from rdkit.DataStructs.cDataStructs import *
     15 

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/miniconda/lib/python3.7/site-packages/rdkit/DataStructs/cDataStructs.so)

Again, the scripts using this installation procedure had no issues before!
What could I do? Thanks for any help.

**Comment by nd-02110114** [comment]
You try to downgrade the rdkit. I found the post for troubleshooting this error.
https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg10368.html

```
!/root/miniconda/bin/conda install -q -y -c conda-forge rdkit=2020.09.02
```

**Comment by JohnMommers** [comment]
Thanks, downgrading did work. I only wonder why the latest version could not be used with Google Colab.
I used the following code and it worked:

!wget -c https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.8.3-Linux-x86_64.sh
!time bash ./Miniconda3-py37_4.8.3-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -q -y -c conda-forge rdkit=2020.09.02

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

**Comment by masun** [comment]
Thank you John, 
but when I run the same code that I used to run last week, the session is crushed saying in app.log "KernelRestarter: restarting kernel (1/5), keep random ports", 
why? What should I do? I have repeated the process many times, and in every time the session is crushed.
Kind regards
