### ISSUE TITLE
New Drug Generation

### ISSUE THREAD

**Issue by PARODBE** [deepchem/deepchem#2421]
## ❓ Questions & Help

Hi, I am new with deepchem, and it is a amazing library for cheminformatic. I have a question, for generate new molecules for example withe Variational Autoencoder, have you some function for this? and In case you don't have it with VAE, do you have any other implementation? I prefer VAE to work in a normal distribution, but for trying several options.

Thanks!

**Comment by rbharath** [comment]
We don't have a good variational autoencoder example, but check out this tutorial on how to use normalizing flows to generate new molecules: https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Training_a_Normalizing_Flow_on_QM9.ipynb by @ncfrey. The normalizing flows should be more robust and easier to use than the vanilla VAE

**Comment by peastman** [comment]
This example demonstrates using a VAE to generate molecules:

https://github.com/deepchem/DeepLearningLifeSciences/blob/master/Chapter09/vae.py

It doesn't work that well, but converting it to use SELFIES instead of SMILES like the other example would probably help a lot.

**Comment by PARODBE** [comment]
Thank you!

**Comment by atreyamaj** [comment]
Hi, just to add on:

BasicMolGAN has been implemented and merged @PARODBE  in PR #2426 . I feel like this might be of use to you!
