### ISSUE TITLE
Errors featurizing PDBBind with RdkitGridFeaturizer

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#2425]
I'm trying to run [this script](https://github.com/deepchem/DeepLearningLifeSciences/blob/master/Chapter05/pdbbind_nn.py) from the book examples, which uses RdkitGridFeaturizer to featurize PDBBind.  Here's what I find.

- With the latest code, using the core subset and featurizing only the binding pockets, it is *much* faster than before (minutes instead of hours).

- While running, it fills the console with a huge number of lines like these:

```
Coordinates are outside of the box (atom id = 7, coords xyz = [-3.97537037  0.55992593 -8.72777778], coords in box = [ 2  4 -1]
Coordinates are outside of the box (atom id = 105, coords xyz = [-1.53037037 -1.94707407 -8.81577778], coords in box = [ 3  3 -1]
Coordinates are outside of the box (atom id = 106, coords xyz = [-1.41437037 -0.88707407 -9.36477778], coords in box = [ 3  3 -1]
```

I suspect there's one line for every atom that isn't in the binding pocket?

- It fails with this error:

```
/home/peastman/miniconda3/envs/tf2/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "pdbbind_nn.py", line 11, in <module>
    n_features = train_dataset.X.shape[1]
IndexError: tuple index out of range
```

**Comment by ncfrey** [comment]
@peastman - I encountered this as well. I think the default `box_width` of 16.0 is too small for most complexes and causes all these errors. I increased `box_width` to 75 for the test cases and it got rid of the errors.

**Comment by peastman** [comment]
Increasing the box width to 75, gets rid of the "Coordinates are outside of the box" messages, but it still fails with the same exception.

Isn't the whole point of only featurizing the binding pocket that there *should* be coordinates outside the box?

**Comment by ncfrey** [comment]
Hmm, I got the "coordinates are outside of the box" message for both the pocket and the full protein featurization, but I actually haven't seen that particular error, only the warnings.

**Comment by peastman** [comment]
Did you try running the script linked above?

**Comment by ncfrey** [comment]
I ran the script locally and on Colab and around 20 complexes failed to featurize, but the rest completed successfully and I didn't see that error.

**Comment by peastman** [comment]
What is `train_dataset.X` for you?  When I run it, I get a 1D array of arrays, instead of a 2D array as expected.  Some of the arrays it contains are empty and have a different dtype than the others.

**Comment by ncfrey** [comment]
I am seeing that too, where the complexes that fail to featurize give an empty array with a different dtype. There is a `numpy.squeeze` at the end of RdkitGridFeaturizer that I think is removing the second axis for the flattened outputs.

**Comment by peastman** [comment]
Then I'm confused.  How do you not see the exception?  If `train_dataset.X` is 1D, `train_dataset.X.shape[1]` should give an error.

**Comment by ncfrey** [comment]
Sorry that was my confusion - I thought the issue was with the featurization, not the model construction. I think the error can be avoided by either changing the `np.squeeze` in RdkitGridFeaturizer or maybe by changing the script to set `n_features = train_dataset.X[0].shape[0]`

**Comment by peastman** [comment]
> I thought the issue was with the featurization, not the model construction.

It is a problem with featurization.  It used to return a 2D array, then changed to returning only a 1D array.

I notice the `squeeze()` call is preceded by a comment

```python
    # TODO(rbharath): Is this squeeze OK?
```

@rbharath can you provide insight on why it was added?

**Comment by rbharath** [comment]
I think what I was trying to do was flatten everything into a consistent shape (I think somewhere I had an extra dimension that I wanted to get rid of). Sorry, been a while since I wrote this code! Could be totally wrong and something we should get rid of

**Comment by ncfrey** [comment]
I experimented with removing the `squeeze()` call. Without it, the featurizer returns `features` with dimension `(num_datapoints, 1, n_features)`. If you keep `squeeze` and pass `axis=0`, it squeezes out one of the 1-dimensional axes and a 2D array is returned, as expected, and the script runs to completion.
I can put up a PR with a hotfix for RdkitGridFeaturizer to fix this!

**Comment by peastman** [comment]
That doesn't fix it for me.  I still get a 1D array of arrays.  It's just that each one of them has fewer dimensions.  The real problem is that we're calling `np.asarray()` to create the final output, and giving it arrays of different size.  This works as expected:

```python
>>> np.asarray([np.zeros(3), np.zeros(3)])
array([[0., 0., 0.],
       [0., 0., 0.]])
```

But this doesn't:

```python
>>> np.asarray([np.zeros(3), np.zeros(4)])
/home/peastman/miniconda3/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
array([array([0., 0., 0.]), array([0., 0., 0., 0.])], dtype=object)
```

**Comment by ncfrey** [comment]
I pushed another change that hopefully should fix this. I'm trying to handle complex featurization failures by inserting arrays with the same shape and dtype of successful featurizations, to avoid these problems. Let me know if that fixes the issue and if you have any suggestions on a better way to replace the failured featurization arrays.

**Comment by peastman** [comment]
Thanks!  That seems to have fixed it.

How about the warning messages about coordinates outside the box?  Can we eliminate them?  If I set the box width to 75 then they go away, but then it runs out of memory trying to create the model because the dataset has 1,975,467 features!  And 75A is way bigger than a typical binding site.  (I assume it's in A?  The documentation doesn't say.)  The whole point of only featurizing the binding site is that a lot of atoms should be outside the box, so it doesn't make sense to warn about them.

**Comment by ncfrey** [comment]
Great!

That sounds good, I'll eliminate the warning messages.
