### ISSUE TITLE
Dataset.to_numpy() behaves differently for single feature data

### ISSUE THREAD

**Issue by flee2** [deepchem/deepchem#243]
For an X array describing only a single feature, `Dataset.to_numpy()` loads this array X as a row vector instead of as a column vector.

**Comment by flee2** [comment]
Test code:

> import numpy as np
> from deepchem.datasets import Dataset
> from deepchem.featurizers.featurize import DataLoader
> from deepchem.featurizers import UserDefinedFeaturizer
> import os
> import shutil
> 
> features = ["feat0"]
> featurizer = UserDefinedFeaturizer(features)
> tasks = ["task0"]
> input_file = os.path.join(os.getcwd(),"min_fail_example.csv")
> data_dir = os.path.join(os.getcwd(),"test_issue")
> if os.path.exists(data_dir):
>   shutil.rmtree(data_dir)
> loader = DataLoader(
>   tasks=tasks,
>   featurizer=featurizer,
>   id_field="id",
>   verbosity=None)
> min_fail_example = loader.featurize(input_file, data_dir)
> 
> X, y, w, ids = min_fail_example.to_numpy()
> print('X.shape')
> print(X.shape)

Test data:

> id,feat0,task0
> 1,0.915904857,0.784114387
> 2,1.135308136,-0.313747777
> 3,-1.309039327,-2.169796355
> 4,0.583600997,1.085357759
> 5,0.291096743,-0.418488242
> 6,-0.793422485,0.97939904
> 7,-0.693339239,-0.32604061
> 8,0.010999993,-0.796304401
> 9,0.463213594,-0.166198479
> 10,-0.121219633,0.719803917

Output:
> X.shape
> (1, 10)

Output should give (10,1) for (n_rows,n_cols)

**Comment by rbharath** [comment]
Fixed by #244. Gives output as expected now:

    X.shape
    (10,)
    y.shape
    (10, 1)
