### ISSUE TITLE
SmilesToImage can't featurize long molecules

### ISSUE THREAD

**Issue by PascalIversen** [deepchem/deepchem#2430]
## 🐛 Bug
Hey,
the `SmilesToImage` featurizer seems unable to handle long chains.

```python
Failed to featurize datapoint 1, CCCCCCCCCCCCCCCCCCCC(=O)OCCCNC(=O)c1ccccc1SSc1ccccc1C(=O)NCCCOC(=O)CCCCCCCCCCCCCCCCCCC. Appending empty array
Exception message: index 81 is out of bounds for axis 0 with size 80
Failed to featurize datapoint 2, COc1ccc(C=CC(=O)N2CC(CCl)c3c2cc(NC(=O)C(CCCCN)NC(=O)C(NC(=O)CCOCCOCCOCCOCCNC(=O)CBr)C(C)C)c2ccccc32)cc1.O=C(O)C(F)(F)F. Appending empty array
Exception message: index 80 is out of bounds for axis 0 with size 80
```
## To Reproduce

```python
import deepchem as dc
mol = ["CCCCCCCCC(=O)OCCCNC(=O)c1ccccc1SSc1ccccc1C(=O)NCCCOC(=O)CCCC",
    "CCCCCCCCCCCCCCCCCCCC(=O)OCCCNC(=O)c1ccccc1SSc1ccccc1C(=O)NCCCOC(=O)CCCCCCCCCCCCCCCCCCC",
       "COc1ccc(C=CC(=O)N2CC(CCl)c3c2cc(NC(=O)C(CCCCN)NC(=O)C(NC(=O)CCOCCOCCOCCOCCNC(=O)CBr)C(C)C)c2ccccc32)cc1.O=C(O)C(F)(F)F"]
dc.feat.SmilesToImage().featurize(mol)
```

## Environment

* OS: Windows 10
* Python version: 3.7.6
* DeepChem version: 2.4.0
* RDKit version (optional): 2020.09.5

**Comment by rbharath** [comment]
Ah thanks for the bug report! This should be fixed. I'm not sure precisely why this is breaking, but I'll mark this as a bug and open for contribution

**Comment by rbharath** [comment]
I suspect the code is somewhere in https://github.com/deepchem/deepchem/blob/master/deepchem/feat/molecule_featurizers/smiles_to_image.py#L134-L165 where we manually construct the image as an array.

**Comment by PascalIversen** [comment]
After looking into this I think this is not really a bug, since, with a fixed resolution and image size one can not guarantee that all molecules will fit.
I would propose catching those cases, issuing a warning which recommends increasing the image size, and returning an empty array. 
What do you think?

**Comment by rbharath** [comment]
+1, sounds like a good idea! Would you possibly be interested in contributing a PR with a fix? :)

**Comment by PascalIversen** [comment]
Sure! Since the exception is already handled in the parent class, I just changed the error message to make it more meaningful.

**Comment by PascalIversen** [comment]
Adressed with #2442.
