### ISSUE TITLE
DeepChem 2.5.0 Cut

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2433]
I'm starting this issue to track the work that needs to be done for the DeepChem:

- [ ] Make the tag on github
- [ ] Update the conda-forge repo
- [ ] Write release note
- [ ] Check that pypi/docker builds have gone up correctly.

As a last check, are there any changes that need to be made before we kick off the release process?

CC @peastman @ncfrey @nissy-dev @seyonechithrananda

**Comment by nissy-dev** [comment]
FYI: If you create the new release PR, please assign me. I will review it!

**Comment by rbharath** [comment]
The DeepChem cut for 2.5.0 is now done! We can unblock PRs for 2.6.0 development now. Thank you everyone for your patience :).

I still need to write up the release notes and post those so will try get those out and post those on the forums later this week

**Comment by alat-rights** [comment]
Is this good to close now?
