### ISSUE TITLE
Deepchem Tutorial 14 issue

### ISSUE THREAD

**Issue by SaharRohaniZ** [deepchem/deepchem#2438]
## 🐛 Bug

I ran Tutorial 14 ( Modeling Protein-Ligand Interactions with Atomic Convolutions) but face an error with load_pdbbind()
## To Reproduce

1.Run all the steps in Tutorial 14

## Additional context

![featurizer error](https://user-images.githubusercontent.com/4704553/111096153-24dcb080-84fc-11eb-9791-3614707d0092.PNG)

**Comment by ncfrey** [comment]
Hi @SaharRohaniZ, I just saw this bug as well - it was introduced because of a change to the `ComplexFeaturizer` parent class. I am working on a fix now and I'll let you know when it's up!

**Comment by ncfrey** [comment]
Should be closed by #2441.
