### ISSUE TITLE
DAG bug in deepchem 2.4

### ISSUE THREAD

**Issue by ellagale** [deepchem/deepchem#2440]
## 🐛 Bug

Cannot get the DAG model to train in deepchem 2.4, get an error:'AttributeError: 'ConvMol' object has no attribute 'parents''

## To Reproduce

`import deepchem as dc`
`from rdkit import Chem`
`from rdkit.Chem import Draw`
`import tensorflow as tf`
`print("DeepChem version: " + dc.__version__)`
`print("TensorFlow version: " + tf.__version__)`
`tasks, datasets, transformers = dc.molnet.load_bace_regression(featurizer='GraphConv')`
`train_dataset, valid_dataset, test_dataset = datasets`
`model = dc.models.DAGModel(n_tasks=1, mode='regression', dropout=0.2)`
`model.fit(train_dataset, nb_epoch=1)`
`metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)`
`print("Training set score:", model.evaluate(train_dataset, [metric], transformers))`
`print("Test set score:", model.evaluate(test_dataset, [metric], transformers))`

Gives DeepChem version: 2.4.0
TensorFlow version: 2.3.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-ab72beaab2a0> in <module>
      8 train_dataset, valid_dataset, test_dataset = datasets
      9 model = dc.models.DAGModel(n_tasks=1, mode='regression', dropout=0.2)
---> 10 model.fit(train_dataset, nb_epoch=1)
     11 metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)
     12 print("Training set score:", model.evaluate(train_dataset, [metric], transformers))

~\.conda\envs\graphs-and-topology-for-chemists\lib\site-packages\deepchem\models\keras_model.py in fit(self, dataset, nb_epoch, max_checkpoints_to_keep, checkpoint_interval, deterministic, restore, variables, loss, callbacks, all_losses)
    322             dataset, epochs=nb_epoch,
    323             deterministic=deterministic), max_checkpoints_to_keep,
--> 324         checkpoint_interval, restore, variables, loss, callbacks, all_losses)
    325 
    326   def fit_generator(self,

~\.conda\envs\graphs-and-topology-for-chemists\lib\site-packages\deepchem\models\keras_model.py in fit_generator(self, generator, max_checkpoints_to_keep, checkpoint_interval, restore, variables, loss, callbacks, all_losses)
    395     # Main training loop.
    396 
--> 397     for batch in generator:
    398       self._create_training_ops(batch)
    399       if restore:

~\.conda\envs\graphs-and-topology-for-chemists\lib\site-packages\deepchem\models\graph_models.py in default_generator(self, dataset, epochs, mode, deterministic, pad_batches)
    743           # padding atom features vector of each molecule with 0
    744           atoms_all.append(mol.get_atom_features())
--> 745           parents = mol.parents
    746           parents_all.extend(parents)
    747           calculation_index = np.array(parents)[:, :, 0]

AttributeError: 'ConvMol' object has no attribute 'parents'

## Expected behavior
DAG should train.

## Environment

* OS: Windows
* Python version: 3 
* DeepChem version: 2.4
* RDKit version (optional):
* TensorFlow version (optional): 2
* PyTorch version (optional):
* Any other relevant information: running in jupyter notebook

**Comment by peastman** [comment]
DAGModel requires you to first apply a DAGTransformer to your dataset.  See https://deepchem.readthedocs.io/en/latest/api_reference/transformers.html#dagtransformer.
