### ISSUE TITLE
tutorials-22，Error when importing the MolNet dataloder from bert-loves-chemistry

### ISSUE THREAD

**Issue by Lumen97** [deepchem/deepchem#2444]
## ❓ Questions & Help

colab

![屏幕截图 2021-03-18 215747](https://user-images.githubusercontent.com/74954182/111638126-04329480-8835-11eb-8e83-396c726c1f92.png)

**Comment by seyonechithrananda** [comment]
Hey @Lumen97,

This is an issue on our part! We're refactoring the `bert-loves-chemistry` library and added a new directory called `chemberta` which utils is a subdirectory of.

If you change the following line: 
`from utils.molnet_dataloader import load_molnet_dataset, write_molnet_dataaset_for_chemprop`

To the following:
`from chemberta.utils.molnet_dataloader import load_molnet_dataset, write_molnet_dataset_for_chemprop`

It should work! Please let me know if this fixes it

**Comment by Lumen97** [comment]
Thanks for the help. @seyonechithrananda 

The code is running properly now.

**Comment by seyonechithrananda** [comment]
Great! Happy to help, and thanks for pointing it out. Would you mind closing the issue?
