### ISSUE TITLE
Running a python script in Google Colab with the DeepChem Installer

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#2448]
## ❓ Questions & Help

I have a [script](https://github.com/ncfrey/moleculenet/blob/acnn/examples/acnn.py) that runs correctly locally, the functions can be imported and run in Colab, but I can't run the actual script with
`!python myscript.py` in Colab.

I've tried using `!/root/miniconda/bin/python`, `!/root/miniconda/bin/conda run python`, but the script fails in every case.

Does anyone have an idea of how to run a python script in Colab that has DeepChem dependencies?

CCing @nissy-dev

**Comment by nissy-dev** [comment]
Can you show the error message? I will confirm this issue in a couple of days.

And, can you try `condacolab`? I'm thinking it is better to replace the current script with condacolab.

```python
!pip install -q condacolab
import condacolab
condacolab.install_miniconda()
!conda install -c conda-forge rdkit
!pip install -q deepchem
```

Repo : https://github.com/jaimergp/condacolab

**Comment by ncfrey** [comment]
Thanks! `condacolab` was much faster (< 30 seconds) to set up the environment and it helped me see that the error was due to an optional dependency not being installed with the `colab_install` script.

**Comment by nissy-dev** [comment]
> condacolab was much faster (< 30 seconds) to set up the environment

This is a good news! I will replace the current script with condacolab.
