### ISSUE TITLE
DockerHub latest failing?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2449]
It looks like the dockerhub pushes have been failing possibly due to time out on our last PRs. Does anyone have an idea what could be happening?

https://github.com/deepchem/deepchem/runs/2169747674?check_suite_focus=true

CC @nissy-dev

**Comment by nissy-dev** [comment]
The error message is `System.IO.IOException: No space left on device`. It means OS run out of disk space when building our docker image. In GitHub actions, there are are only 12 GB of free space. 

Related issue : https://github.com/actions/virtual-environments/issues/709

If this error continues, I will try to reduce the image size.
