### ISSUE TITLE
datasets loading error: no Metadata Found on Disk

### ISSUE THREAD

**Issue by wendong-wang** [deepchem/deepchem#2452]
## 🐛 Bug
I am using deepchem for teaching. In my class, a number of students reported this error when they try to load dataset delaney and hiv, and I am able to reproduce on my windows 10 conda environment, but not on my mac. 

`tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='ECFP', splitter='index')`
`train_dataset, valid_dataset, test_dataset = datasets`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-8844af48f156> in <module>
----> 1 tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='ECFP', splitter='index')
      2 train_dataset, valid_dataset, test_dataset = datasets

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\molnet\load_function\delaney_datasets.py in load_delaney(featurizer, splitter, transformers, reload, data_dir, save_dir, **kwargs)
     78   loader = _DelaneyLoader(featurizer, splitter, transformers, DELANEY_TASKS,
     79                           data_dir, save_dir, **kwargs)
---> 80   return loader.load_dataset('delaney', reload)

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\molnet\load_function\molnet_loader.py in load_dataset(self, name, reload)
    168       else:
    169         loaded, all_dataset, transformers = dc.utils.data_utils.load_dataset_from_disk(
--> 170             save_folder)
    171         if all_dataset is not None:
    172           return self.tasks, all_dataset, transformers

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\utils\data_utils.py in load_dataset_from_disk(save_dir)
    546     return False, None, list()
    547   loaded = True
--> 548   train = dc.data.DiskDataset(train_dir)
    549   valid = dc.data.DiskDataset(valid_dir)
    550   test = dc.data.DiskDataset(test_dir)

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\data\datasets.py in __init__(self, data_dir)
   1150 
   1151     logger.info("Loading dataset from disk.")
-> 1152     tasks, self.metadata_df = self.load_metadata()
   1153     self.tasks = np.array(tasks)
   1154     if len(self.metadata_df.columns) == 4 and list(

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\data\datasets.py in load_metadata(self)
   1231       DiskDataset._save_metadata(metadata_df, self.data_dir, tasks)
   1232       return tasks, metadata_df
-> 1233     raise ValueError("No Metadata Found On Disk")
   1234 
   1235   @staticmethod

ValueError: No Metadata Found On Disk

`tasks, datasets, transformers = dc.molnet.load_hiv(featurizer='ECFP', splitter='scaffold')`
`train_dataset, valid_dataset, test_dataset = datasets`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-8513f859e2ce> in <module>
----> 1 tasks, datasets, transformers = dc.molnet.load_hiv(featurizer='ECFP', splitter='scaffold')
      2 train_dataset, valid_dataset, test_dataset = datasets

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\molnet\load_function\hiv_datasets.py in load_hiv(featurizer, splitter, transformers, reload, data_dir, save_dir, **kwargs)
     80   loader = _HIVLoader(featurizer, splitter, transformers, HIV_TASKS, data_dir,
     81                       save_dir, **kwargs)
---> 82   return loader.load_dataset('hiv', reload)

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\molnet\load_function\molnet_loader.py in load_dataset(self, name, reload)
    168       else:
    169         loaded, all_dataset, transformers = dc.utils.data_utils.load_dataset_from_disk(
--> 170             save_folder)
    171         if all_dataset is not None:
    172           return self.tasks, all_dataset, transformers

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\utils\data_utils.py in load_dataset_from_disk(save_dir)
    546     return False, None, list()
    547   loaded = True
--> 548   train = dc.data.DiskDataset(train_dir)
    549   valid = dc.data.DiskDataset(valid_dir)
    550   test = dc.data.DiskDataset(test_dir)

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\data\datasets.py in __init__(self, data_dir)
   1150 
   1151     logger.info("Loading dataset from disk.")
-> 1152     tasks, self.metadata_df = self.load_metadata()
   1153     self.tasks = np.array(tasks)
   1154     if len(self.metadata_df.columns) == 4 and list(

C:\ProgramData\Anaconda3\envs\deepChem3\lib\site-packages\deepchem\data\datasets.py in load_metadata(self)
   1231       DiskDataset._save_metadata(metadata_df, self.data_dir, tasks)
   1232       return tasks, metadata_df
-> 1233     raise ValueError("No Metadata Found On Disk")
   1234 
   1235   @staticmethod

ValueError: No Metadata Found On Disk

However, the following code using GraphConv as the featurizer loads just fine: 
`tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='GraphConv', splitter='index')`
`train_dataset, valid_dataset, test_dataset = datasets`

I suspected the problem was the compatibility with RDkit, but after reinstalling rdkit and updating deepchem to 2.5.0, the error still exits. 

## Environment

* OS: windows 10
* Python version: 3.6.9
* DeepChem version: 2.5.0
* RDKit version (optional): 2020.09.5
* TensorFlow version (optional): 2.4.1
* PyTorch version (optional):
* Any other relevant information:

**Comment by rbharath** [comment]
Oh, hmm, this is tricky. I develop on a Mac so it's tough to check windows. One thought is perhaps trying to set `reload=False` to force refeaturization

```
tasks, datasets, transformers = dc.molnet.load_hiv(featurizer='ECFP', splitter='scaffold', reload=False)
train_dataset, valid_dataset, test_dataset = datasets
```

Does that help any?

CC @peastman @ncfrey @nissy-dev for ideas

**Comment by wendong-wang** [comment]
Thanks! It solves the problem on my PC. I will check with my students.  
Two questions:
1) According to the description in the docstrings, reload will save a cached dataset on the disk, is this folder under "deepchem\molnet\__pycache__"?
2) It is possible that in my class, in order to save time, we tried to run two load functions in two different jupyter notebooks at the same time. The two load processes somehow produced some error in the cached file. Is this a plausible reason? 

Thanks.

**Comment by wendong-wang** [comment]
I found the answer to my question (1). I realized that deepchem uses tempfile to get the temporary file directory, so the location depends on the system.

**Comment by rbharath** [comment]
Sorry for the slow response! This thread got lost in my inbox. For (2), this could have happened if one of the loads failed or was stopped in the middle. Then it would have left residue on disk. Setting `reload=False` blows away the residue and is a good fix if you run into these sorts of issues in general

**Comment by wendong-wang** [comment]
Thanks. Is this a new feature in the latest update that when setting `reload = False,` the cache file is removed? In the 2.5.0.dev version we are using now, it seems that we will need to go to the temporary file folder and manually remove the corresponding folder that contains the cache file. Otherwise, we have to keep using `reload = False` every time, and it could be slow for large dataset.

**Comment by rbharath** [comment]
I don't believe anything has changed here! The `reload=False` regenerating the dataset has been in DeepChem since our earliest releases I believe. I suspect that what's happening is some weirdness with jupyter notebooks. I'd suggest using a script locally to generate the datasets at some known location (by setting `DEEPCHEM_DATA_DIR`) and then re-using that in jupyter notebooks. I hope this helps!

**Comment by rbharath** [comment]
Going to go ahead and close. Let me know if this is still an issue and will reopen.
