### ISSUE TITLE
data loading-----Failed to featurize

### ISSUE THREAD

**Issue by Aether-Ren** [deepchem/deepchem#2453]
# Failed to featurize
**When I use `featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True)` <br>
`tasks, datasets, transformers = dc.molnet.load_sider(reload=False, featurizer=featurizer, transformers=[])`**

It will prompt me
Failed to featurize datapoint 41, N. Appending empty array
Exception message: zero-size array to reduction operation maximum which has no identity

**What should I do if I want to delete these data that cannot be featurized???**

**Comment by arinaafan** [comment]
Hi Aether-Ren! How did you solve the problem eventually? I am facing the same problem with PDBbind dataset and load_pdbbind method.
