### ISSUE TITLE
MultitaskClassifier() 2.3.0 does not pass arguments

### ISSUE THREAD

**Issue by filipm90** [deepchem/deepchem#2454]
Greetings,

The only arguments I am able to pass are _n_tasks_ and _n_features_ and these are detected when I print the model. But others such as _activation_fns_ and _layer_sizes_ are just _None_.

How to resolve this issue and has it been resolved with the latest version 2.5.0?

Thanks!

**Comment by peastman** [comment]
Could you post your code?  Then we can take a look and see what's wrong.

**Comment by filipm90** [comment]
`import tensorflow as tf
import deepchem as dc

params = {
          'n_tasks': 5,
          'n_features': 2048,
          'activation_fns': tf.nn.relu,
          'layer_sizes': [2000,1000],
          'dropouts': 0.25,
          'batch_size': 64,
          'nb_epochs': 100,
          'learning_rate': 0.00001
          }

model = dc.models.MultitaskClassifier(**params)
print(model)`

This is really a minimum working example. And what is printed is:

`MultitaskClassifier(activation_fns=None, bias_init_consts=None, dropouts=None,
                    layer_sizes=None, n_classes=2, n_features=2048, n_tasks=5,
                    weight_decay_penalty=None, weight_decay_penalty_type=None,
                    weight_init_stddevs=None)
`

As you can see, only _n_features_ and _n_tasks_ are accepted from _params_, but not the remaining parameters.

**Comment by peastman** [comment]
`print()` is using the implementation of `__repr__()` provided by scikit-learn's BaseEstimator class.  It doesn't know anything about MultitaskClassifier or how to print it correctly.  Possibly we should disable that.  In any case, don't pay any attention to it.  The model really is getting constructed correctly.

**Comment by filipm90** [comment]
I used the `print()` statement only after discovering that the list _layer_sizes_ that I passed produced an error: the length of the list could not be calculated for value of None. I could hardly believe that I passed None instead of an actual list, e.g. [2000, 2000], but the error occurred.

**Comment by peastman** [comment]
I don't understand what you mean?  The code above doesn't produce any error about not being able to calculate the length of a list.  And if I add `print(layer_sizes)` inside the MultitaskClassifier constructor, it correctly prints out `[2000, 1000]`.  What code produced that error?
