### ISSUE TITLE
subclass import error

### ISSUE THREAD

**Issue by JainSamyak8840** [deepchem/deepchem#2459]
## 🐛 Bug
On running => featuriser = dc.feat.LCNNFeaturizer(**PRIMITIVE_CELL_INF0)   it shows class import error.
`
ImportError                               Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/deepchem/feat/material_featurizers/lcnn_featurizer.py in __init__(self, structure, aos, pbc, ns, na, cutoff)
    149     try:
--> 150       from pymatgen import Structure
    151     except:

ImportError: cannot import name 'Structure' from 'pymatgen' (unknown location)

It will be fixed if we replace pymatgen to pymatgen.core . I think pymatgen module is updated.

`

## Environment

* OS: windows 10
* Python version: 3.7.10
* DeepChem version: 2.5.0
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

## Additional context

There is also need some little update on docstrings relates to pymatgen in lcnn.py under torch models directory.

**Comment by rbharath** [comment]
@JainSamyak8840 Thank you for the bug catch! We should have had a unit test that would catch this. Would you be willing to submit a PR that fixes this issue?

**Comment by JainSamyak8840** [comment]
@rbharath Yes, I will submit the PR to fix this issue.
