### ISSUE TITLE
Adding new loss functions and optimizers to Deepchem

### ISSUE THREAD

**Issue by atreyamaj** [deepchem/deepchem#2478]
## 🚀 Feature

I would love to see some more loss functions and features added to Deepchem. 
Maybe we can start off with:
1. Loss functions:
    a) Huber
    b) Poisson

2. Optimizers:
    a) AdamW

I have sent out PRs for the aforementioned suggestions. If there are other such features you would like to see implemented I would love to send out some PRs!

## Motivation
I believe this is a nice addition that can give the community a lot more freedom while building/using models.

**Comment by rbharath** [comment]
Closing since implemented.
