### ISSUE TITLE
Conda Install Script Fails

### ISSUE THREAD

**Issue by peterskipper** [deepchem/deepchem#2481]
## 🐛 Bug

`scripts/install_deepchem_conda.sh` fails to install deepchem due to an issue comparing strings. I'm using MacOS Mojave (10.14.6) and `zsh 5.3 (x86_64-apple-darwin18.0)`. This is due to the == comparison with the `uname` function [here](https://github.com/deepchem/deepchem/blob/master/scripts/install_deepchem_conda.sh#L27). Per [this StackOverflow post](https://stackoverflow.com/questions/20449543/shell-equality-operators-eq) it's better to use a single = in string comparison as this is valid across more flavors of shell (this fixed the problem for me). I can submit a PR with this small change, assuming we agree on the approach.

## To Reproduce

1. Download and install conda on Mac with zsh 5.3
2. run `source scripts/install_deepchem_conda.sh 3.7 cpu`

Output:
`scripts/install_deepchem_conda.sh:27: = not found`

## Expected behavior

I expected the script to run and install deepchem!

## Environment

* OS: MacOS 10.14.6
* Python version: 3.7.9
* DeepChem version: 2.6.0.dev
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

## Additional context

Let me know if I can add any useful details.

**Comment by rbharath** [comment]
Great catch! Yes, please go ahead and submit a PR with a fix :)
