### ISSUE TITLE
Question about SIDER dataset discrepancy

### ISSUE THREAD

**Issue by LanceKnight** [deepchem/deepchem#2487]
## ❓ Questions & Help

Hello, 

The MoleculeNet documents state that SIDER dataset contains 1427 drugs. But the original SIDER [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4702794/) said it had 1430 drugs. I cannot find the description for this discrepancy. Can some help me explain this? Thanks!

**Comment by rbharath** [comment]
Linking to the discussion at https://github.com/deepchem/moleculenet/issues/38
