### ISSUE TITLE
Reproducibility issue with Graph convolution model

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2489]
I'm trying to reproduce some of my earlier model test results. Like mentioned in this one #1506,  I set the same seed number when split my dataset, but got different evaluation scores between multiple runs of the script. This is the snippet I used.
```
task = ['label']
graph_featurizer = dc.feat.graph_features.ConvMolFeaturizer()
loader = dc.data.data_loader.CSVLoader(tasks=task, feature_field="Smiles", featurizer=graph_featurizer)
dataset = loader.create_dataset(dataset_file)
seed=123
splitter = dc.splits.ScaffoldSplitter()
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset, seed=seed)
from deepchem.models.graph_models import GraphConvModel
n_tasks = len(task)
model = GraphConvModel(n_tasks, mode="classification", batch_size=50)

num_epochs = 10
losses = []
for i in range(num_epochs):
  loss = model.fit(train_dataset, nb_epoch=1)
  print("Epoch %d loss: %f" % (i, loss))
  losses.append(loss)

metric_rocauc = dc.metrics.Metric(dc.metrics.roc_auc_score)
print("Evaluating Model")
v_evaluator = Evaluator(model, valid_dataset, [] )
v_score = v_evaluator.compute_model_performance(metric_rocauc)
print(v_score)
```
I compared the splitting results between multiple runs, I found the splitter successfully got the same training dataset/validation dataset/test dataset every time, but the model training results varies, and the evaluation scores varies. I wonder if there're other constraints to maintain the reproducibility ? Maybe I should use the reload function to save the model I trained earlier?

Besides, when I tried this `splitter = dc.splits.ScaffoldSplitter(seed=123)` like mentioned in #1815 there is error"TypeError: ScaffoldSplitter() takes no arguments". I wonder the issue is not resolved yet?

Thank you very much for the help!

**Comment by peastman** [comment]
If you want reproducibility, you can set the seeds for both Numpy and TensorFlow:

```python
np.random.seed(seed)
tf.random.set_seed(seed)
```

I think that should eliminate all sources of variation.

**Comment by alat-rights** [comment]
Is this good to close?
