### ISSUE TITLE
The Doc about GraphConvModel

### ISSUE THREAD

**Issue by yuanjames** [deepchem/deepchem#2498]
## To Reproduce

In the docs, 'dense_layer_size (int) – Width of channels for Atom Level Dense Layer before GraphPool', but it looks the dense layer is after the GraphPool and before GraphGather layer.

## Environment

* OS:
* Python version:
* DeepChem version:
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

**Comment by rbharath** [comment]
Good find; we should update our docs here!

**Comment by yuanjames** [comment]
> Good find; we should update our docs here!

Thanks!

**Comment by arunppsg** [comment]
Hey, the [docs](https://deepchem.readthedocs.io/en/latest/api_reference/models.html#graphconvmodel) are fixes now.
