### ISSUE TITLE
How to not redownload molnet dataset

### ISSUE THREAD

**Issue by bolton-lab** [deepchem/deepchem#2499]
Hi,

If I use the below code, how can I rerun again after it is downloaded so that it does not redownload the `muv.csv.gz` file?  This puts the folder `muv-featurized` in the `data_dir`, how can I recall `tasks, datasets, transformers = dc.molnet.load_muv()` so that it gets the info `tasks, datasets, transformers` from this folder `muv-featurized` and not from redownloading `muv.csv.gz` file?

```
tasks, datasets, transformers = dc.molnet.load_muv(splitter='stratified',
                                                  data_dir="/Users/brian/deep_learning",
                                                  save_dir="/Users/brian/deep_learning")
```

**Comment by nvtrang91** [comment]
I am not sure how it works in your case but I tried with this code, nothing was downloaded, with `muv.csv.gz` is already in `data_dir` folder
`tasks, datasets, transformers = dc.molnet.load_muv(splitter='stratified',
                                                  data_dir = '...'`

**Comment by bolton-lab** [comment]
Nevermind, seems that gz file was deleted somehow but when it stays there is loads much faster.  Sorry I thought the data_dir replaced the gz file

**Comment by arunppsg** [comment]
You could set `DEEPCHEM_DATA_DIR` environment variable for saving the downloaded files in a directory which you could reuse later. For example, by setting `os.environ['DEEPCHEM_DATA_DIR'] = os.getcwd()`, the downloaded files get saved in the current working directory.

**Comment by rbharath** [comment]
Going to go ahead and close. Feel free to comment if you need additional help
