### ISSUE TITLE
Multi-GPU parallelization?

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#251]
I'm running on AWS (p2.8xlarge) with 8 GPUs and I'm noticing that deepchem is using only one GPU. Is this the intended behavior?

**Comment by rbharath** [comment]
Yes, the out-of-the box models from Keras/Tensorflow in DeepChem are single GPU. That said, it should be relatively straightforward to get a multi-GPU model working with directions from the distributed-tf [docs](https://www.tensorflow.org/versions/r0.11/how_tos/distributed/index.html). Contributions welcome!

**Comment by hainm** [comment]
FYI: "Theano-MPI: a Theano-based Distributed Training Framework"
https://arxiv.org/pdf/1605.08325v1.pdf
https://github.com/uoguelph-mlrg/Theano-MPI

**Comment by rbharath** [comment]
@dmoccia Great to hear you're thinking of taking a crack at it! Here are some of my thoughts.

1. I think focusing on data parallelism is probably best. There have a been a few attempts at model parallelism, but I'm not aware of any really interesting results.
2. I'd suggest first optimizing for the case of multiple GPUs on the same server. This is the simplest distributed setup and many teams are actually likely to be able to afford this cluster. The TensorFlow team also has a nice tutorial on doing this for vanilla conv-nets https://www.tensorflow.org/tutorials/deep_cnn#training_a_model_using_multiple_gpu_cards
3. I believe we use TensorFlow's default settings for finding GPUs.

**Comment by saurabhclusterone** [comment]
@rbharath 

I was able to run Multi-GPU data parallelism Multitask model for Deepchem using Estimator class. The example works such that it achieves linear speed up with addition of new worker nodes.

I have a separate python file as a Standalone example of code for distributed Deepchem Multitask model using Deepchem.

Can I contribute that example to the Deepchem repo?

If yes, can you tell me the best way to do it?

Thanks!

**Comment by peastman** [comment]
That's really neat!  It's a good reason we ought to get back to work on supporting Estimators with more models (#1142).

**Comment by rbharath** [comment]
Closing this old issue out since we don't currently have plans for multi-GPU support. Might re-open in the future.
