### ISSUE TITLE
Dgllife installation error

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2511]
We have an issue with our `dgllife` installation which is causing our travis-CI test suite to break. This may be due to `dgllife`'s recent swap to pip builds instead of conda builds.

CC @mufeili @VIGNESHinZONE @ncfrey

**Comment by VIGNESHinZONE** [comment]
This is one other we are getting in Doctest failure for all `dgllife` models
```
ModuleNotFoundError: No module named 'dgl.nn.functional'
```

If Im not wrong, Doctest is initiated in Github Actions in this line (141-144) https://github.com/deepchem/deepchem/blob/a834e7264e0e1a3107f11e8bd8518c24b0542fac/.github/workflows/main.yml#L144

**Comment by rbharath** [comment]
Maybe the issue is we don't have `dgllife` marked for pip install in our `env.cpu.yml` file? 

https://github.com/deepchem/deepchem/blob/master/env.cpu.yml#L5

We do have it marked for pip install in the common file though:

https://github.com/deepchem/deepchem/blob/master/env.common.yml#L15

Also, CC @nissy-dev who might have some insight into the github action pipelines

**Comment by mufeili** [comment]
This suggests that DGL-LifeSci has been successfully installed and as its dependency, DGL is outdated. The latest version should be 0.6.1 for DGL.

**Comment by rbharath** [comment]
@mufeili Ah I see. In that case, can we remove DGL as a direct dependency and just install DGL-LifeSci directly? I think all our DGL models use DGL-LifeSci

**Comment by mufeili** [comment]
@rbharath You still need to install DGL as installing DGL-LifeSci does not install DGL.
