### ISSUE TITLE
Test scripts for loader methods are commented out

### ISSUE THREAD

**Issue by Suzukazole** [deepchem/deepchem#2515]
## ❓ Questions & Help

I was trying to fix some of the errors raised by flake8 on the deepchem/models and deepchem/molnet directories so that we could include those in the CI checks too. I had noticed that the test scripts for the loader methods were entirely commented out [here](https://github.com/deepchem/deepchem/blob/master/deepchem/molnet/load_function/tests/test_load_zinc15.py). 
Why were these commented out? Flake8 was raising an error on these scripts because the imports in these files were left uncommented which it flagged as an unused import.

**Comment by rbharath** [comment]
CC @ncfrey who I believe wrote these tests

**Comment by ncfrey** [comment]
I wrote these tests as a hacky way to test the loaders, which otherwise are not tested in any way. These tests don't actually load the real datasets - they load only a few datapoints and check to make sure that the loader returns something reasonable. If this is helpful, they can be uncommented. If not, they can be deleted.

**Comment by rbharath** [comment]
I think this would potentially be useful! Let's go ahead and uncomment the tests @Suzukazole to get flake8 running

**Comment by peastman** [comment]
I commented them out while implementing the new molnet architecture.  They relied on a hack, that if you put a file with a particular name in a particular place it would think those were real datasets that it had already downloaded.  That doesn't work anymore.

**Comment by Suzukazole** [comment]
Awesome! thanks @ncfrey and @peastman for the clarification. I shall uncomment the tests and proceed with the flake8 fix.

**Comment by peastman** [comment]
We can't uncomment the tests.  Like I said, they rely on a hack that doesn't work anymore.

**Comment by Suzukazole** [comment]
I am sorry, I misunderstood what you said previously.  Should I try removing the file instead?

**Comment by peastman** [comment]
Which file do you mean?

**Comment by Suzukazole** [comment]
The [qm9 ](https://github.com/deepchem/deepchem/blob/master/deepchem/molnet/load_function/tests/test_qm9_loader.py) and the [zinc15](https://github.com/deepchem/deepchem/blob/master/deepchem/molnet/load_function/tests/test_load_zinc15.py) loader tests, I thought if they do not work anymore, we could just remove them.

**Comment by peastman** [comment]
Sure, that would be reasonable.
