### ISSUE TITLE
Documentation on how to run full slow test suite

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2521]
We don't have good documentation right now on how to run the full slow test suite. Since this is a core part of our release process we should have a good write-up on the process on the docs

**Comment by arunppsg** [comment]
Hey, closing this since documentation on running tests have been added. See [here](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html#unit-tests). Please feel free to reopen it if you think it the issue is not yet addressed. Thanks!
