### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yuanjames** [deepchem/deepchem#2527]
File "xxxxlib64/python3.6/site-packages/deepchem/data/datasets.py", line 2546, in get_shape
    return tuple(X_shape), tuple(y_shape), tuple(w_shape), tuple(ids_shape)
UnboundLocalError: local variable 'X_shape' referenced before assignment

**Comment by peastman** [comment]
Could you provide the code that leads to this error?

**Comment by yuanjames** [comment]
> Could you provide the code that leads to this error?

Hi Thanks! I just run the demo code in docs.

**Comment by peastman** [comment]
Which demo code?  We have a lot of documentation with a lot of code.

**Comment by yuanjames** [comment]
> Which demo code? We have a lot of documentation with a lot of code.

Hi Thanks, I think this problem is fixed, probably because of relevant dependencies, I reinstalled conda environment.

**Comment by yuanjames** [comment]
> Which demo code? We have a lot of documentation with a lot of code.

BTW, may I ask the optimizer for the Pytorch model and the Tensorflow model, when fit() is called. Also, the initilisation function of weights for them are same?
