### ISSUE TITLE
Upgrading pymatgen and matminer dependencies

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#2543]
## 🐛 Bug

The latest versions of pymatgen and matminer use numpy 1.2*
I am working through some bugs related to these updates. One may require a change to matminer, which I've opened here: https://github.com/hackingmaterials/matminer/pull/641

There will probably be other test failures as we upgrade, so if @nissy-dev or anyone else has a chance to do bug fixes here, I'd appreciate it!

**Comment by rbharath** [comment]
@ncfrey It looks like we might have to pin numpy 1.19 since TF doesn't yet support numpy 1.20 (see discussion in https://github.com/deepchem/deepchem/pull/2531). Should we just pin older versions of pymatgen/matminer that use numpy 1.19?

**Comment by ncfrey** [comment]
Sounds good. We can roll back to matminer v0.6.5 and the corresponding pymatgen version.

**Comment by arunppsg** [comment]
pymatgen v2020.12.31 is compatible with tensorflow.

**Comment by rbharath** [comment]
Closing since I believe completed
