### ISSUE TITLE
which is the correct predicted value ? when predict.shape is 3D

### ISSUE THREAD

**Issue by su-chao** [deepchem/deepchem#2551]
## ❓ Questions & Help

**Hi, Anyone can tell me the output predict.shape always (#,#,2) which is 3D,
and that predict[:,:,0] and predict[:,:,1] is differnet values,which is the correct predicted value ?**

**Comment by peastman** [comment]
That means you have a classification model.  The output has shape (# samples, # tasks, # classes).  The values are probabilities.  For any particular sample/task, the probabilities of the classes should add to 1.  You have two classes, which means this is a binary classification problem.
