### ISSUE TITLE
Convert models to PyTorch

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#2552]
Given the problems we've been having with TensorFlow, we've been discussing converting more of them to PyTorch.  I'm opening this issue as a place to discuss/track doing that.

As a start, I'm looking into converting the fully connected models (MultitaskClassifier, MultitaskRegressor, etc.).  I think I can mostly do that without changing the public API, but there's one exception.  The user can pass in activation functions as either strings or TensorFlow objects:

https://github.com/deepchem/deepchem/blob/66402d1cf34d51c13ed491f1f14eaffca133dfab/deepchem/models/fcnet.py#L50

That will need to change to take PyTorch objects instead.

Should I go ahead and start on this?

**Comment by rbharath** [comment]
Yes, please go ahead and start on this!

Should we introduce an abstract DeepChem activation function type? That could help us abstract any future backend changes so we don't have to break the user API for future modifications

**Comment by peastman** [comment]
For standard activation functions, we can just make a point of using strings (`'relu'` instead of `torch.nn.functional.relu`).  For custom activation functions, I think it will be simplest if we continue to let the user provide any callable object.  Long term, there also is an effort underway to have NumPy/TensorFlow/PyTorch/JAX/etc. provide a common API so people can write functions that work with all of them.

**Comment by peastman** [comment]
The first piece is in #2559.  What are other high priority models to convert?  The next most commonly used one is probably GraphConvModel, but I don't know whether we want to convert it or just start directing people to a DGL based model instead?

**Comment by rbharath** [comment]
My two cents is converting `GraphConvModel` and the other popular models like `WeaveModel` would be worthwhile. There are a number of downstream codebases that use DeepChem that would have to be migrated manually if we deprecate `GraphConvModel` in favor of a DGL model. It would be very nice if we could change internals  on `GraphConvModel` without causing downstream ripples (but underneath the hood, we could just use DGL while preserving the user API)

**Comment by peastman** [comment]
There are two approaches we could take to doing that.  One would be to directly convert the current code over to PyTorch.  The other would be to try to reimplement equivalent models using either DGL or PyTorch-Geometric.  The former might give a more exact conversion, but the latter would probably lead to better performance.  We should investigate both possibilities.

**Comment by ncfrey** [comment]
Adding [`AtomicConvModel`](https://github.com/deepchem/deepchem/blob/master/deepchem/models/atomic_conv.py) here as a request for PyTorch implementation. 

I will put this on my TODO list, but if someone gets to it before me, it would be very useful!

**Comment by rbharath** [comment]
Closing this issue in favor of https://github.com/deepchem/deepchem/issues/2863 which is tracking the needed porting work
