### ISSUE TITLE
DeepChem Breaking Changes Tracker (2.6.0 version)

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2553]
While we're moving towards increasing backwards compatibility for robustness, we will occasionally run into unavoidable changes which require breaking of backwards compatibility (for example, this thread was inspired by https://github.com/deepchem/deepchem/issues/2552). Let's use this thread to track any changes that break backwards compatibility (even in a minor fashion) for the 2.6.0 release notes.

**Comment by rbharath** [comment]
`ANITransformer` has been broken for some time (no unit tests, TF1.x usage) and was removed by #2567. Ideally, we should re-add support for ANI (perhaps leveraging https://github.com/aiqm/torchani?) but given this was broken already feels better to remove rather than retain broken code

**Comment by arunppsg** [comment]
PR #2769 is a breaking change.

**Comment by arunppsg** [comment]
PR #2724 - breaking change.

**Comment by rbharath** [comment]
Closing since this issue is out of date
