### ISSUE TITLE
Dataset path problems for examples

### ISSUE THREAD

**Issue by miaecle** [deepchem/deepchem#257]
After I installed all the necessary packages, I tried to run some examples in the '/examples' folder, but it always shows some kind of failures due to cannot find the dataset files.

It seems that when the examples are calling the functions: load_* from deepchem.datasets.*_dataset, which is exactly the function of loading datasets, these functions use a relative path, namely joining the path of itself and '../../datasets/*.csv.gz'. If all the packages are installed as a new environment called 'deepchem' into python, this results in a path like '~/anaconda3/envs/deepchem/lib/python2.7/site-packages/datasets/*.csv.gz', where there should not be any data files.

One solution to it is to copy all the dataset files to the above path, which is not that practical when the dataset files are huge. Another more practical one is to move the *_dataset.py, which includes the dataset loading function, to the example folder, and change the calling statement. As long as the relative paths of examples and dataset files are kept constant, we can solve it this way.

**Comment by rbharath** [comment]
@miaecle Thanks for reporting the issue!

**Comment by rbharath** [comment]
Addressed by #258
