### ISSUE TITLE
Hyperparameter Tuning GraphConvModel Issue

### ISSUE THREAD

**Issue by pjspol** [deepchem/deepchem#2575]
## ❓ Questions & Help

I've been trying to run hyperparameter tuning for a GraphConvModel, but it keeps spitting out an error about the metric not being iterable. Any help is deeply appreciated!

**This is the code:**

metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)

params_dict = {
    "np_epoch":[1,100],
    "n_tasks":[1],
    "graph_conv_layers":[[64, 64]],
    "dense_layer_size":[128,256,512],
    "dropout":[0.0],
    "number_atom_features":[75],
    "batch_size":[10,20],
}

optimizer = dc.hyper.GaussianProcessHyperparamOpt(lambda **p: dc.models.GraphConvModel(n_tasks=1, mode='regression', **p))
best_model, best_hyperparams, all_results = optimizer.hyperparam_search(
    params_dict,
    train_dataset,
    valid_dataset,
    transformers,
    metric)

#printing out results
print("\n===================BEST MODEL=================")
print(best_model)
print("\n===================BEST Params=================")
print(best_hyperparams)
print("\n===================ALL_RESULTS=================")
print(all_results)

**And this is the full error message:**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-53-c676e2afd011> in <module>
     17     valid_dataset,
     18     transformers,
---> 19     metric)
     20 
     21 #printing out results

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/deepchem/hyper/gaussian_process.py in hyperparam_search(self, params_dict, train_dataset, valid_dataset, metric, output_transformers, nb_epoch, use_max, logdir, max_iter, search_range, logfile, **kwargs)
    343     gpgo = GPGO(gp, acq, optimizing_function, param_range)
    344     logger.info("Max number of iteration: %i" % max_iter)
--> 345     gpgo.run(max_iter=max_iter)
    346 
    347     hp_opt, valid_performance_opt = gpgo.getResult()

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/pyGPGO/GPGO.py in run(self, max_iter, init_evals, resume)
    186         if not resume:
    187             self.init_evals = init_evals
--> 188             self._firstRun(self.init_evals)
    189             self.logger._printInit(self)
    190         for iteration in range(max_iter):

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/pyGPGO/GPGO.py in _firstRun(self, n_eval)
     86             s_param_val = list(s_param.values())
     87             self.X[i] = s_param_val
---> 88             self.y[i] = self.f(**s_param)
     89         self.GP.fit(self.X, self.y)
     90         self.tau = np.max(self.y)

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/deepchem/hyper/gaussian_process.py in optimizing_function(**placeholders)
    335         valid set performances
    336       """
--> 337       return _optimize(nb_epoch=nb_epoch, **placeholders)
    338 
    339     # execute GPGO

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/deepchem/hyper/gaussian_process.py in _optimize(nb_epoch, **placeholders)
    297 
    298       multitask_scores = model.evaluate(valid_dataset, [metric],
--> 299                                         output_transformers)
    300       score = multitask_scores[metric.name]
    301 

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/deepchem/models/models.py in evaluate(self, dataset, metrics, transformers, per_task_metrics, use_sample_weights, n_classes)
    213       separately.
    214     """
--> 215     evaluator = Evaluator(self, dataset, transformers)
    216     return evaluator.compute_model_performance(
    217         metrics,

/hpc/group/rekerlab/pjs57/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/deepchem/utils/evaluate.py in __init__(self, model, dataset, transformers)
    192     self.dataset = dataset
    193     self.output_transformers = [
--> 194         transformer for transformer in transformers if transformer.transform_y
    195     ]
    196 

TypeError: 'Metric' object is not iterable

**Comment by peastman** [comment]
You have the last two arguments to `hyperparam_search()` reversed.  You're passing the metric for the transformers and the transformers for the metric.

**Comment by pjspol** [comment]
Thanks! That was a silly mistake on my part. A new error popped up now. I know what positive definiteness is, but I have no idea how to fix it. Any help is really appreciated!

/miniconda3/envs/MLnotebook/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
     36     if info > 0:
     37         raise LinAlgError("%d-th leading minor of the array is not positive "
---> 38                           "definite" % info)
     39     if info < 0:
     40         raise ValueError('LAPACK reported an illegal value in {}-th argument'

LinAlgError: 3-th leading minor of the array is not positive definite

**Comment by peastman** [comment]
Can you post your complete script and the complete output?  All we can tell from the above is that the error is happening inside scipy, but not where scipy is getting called from or what might be triggering the error.

**Comment by pjspol** [comment]
@peastman sorry for delay; my profile got marked as "spammy" by mistake and you may or may not have seen the full output I posted above in reply. Thanks for all your help thus far!

**Comment by peastman** [comment]
It looks like the error is happening inside pyGPGO.  Anyone have an idea what might cause that?

**Comment by rbharath** [comment]
I think what's happening here is that your params aren't in the format expected by GaussianProcessHyperparamOpt. Not that this class requires params to be specified differently than GridSearchHyperparamOpt. That's throwing off pyGPGO since it's not getting arguments in the format it expects

**Comment by pjspol** [comment]
@rbharath Where can I find the correct format? DeepChem docs give a description of what is needed but don't actually provide a viable example. What I have used above comes from poking around GitHub for examples. If you could provide an example with correct formatting, that would be phenomenal. Thanks for all you help thus far!

**Comment by rbharath** [comment]
Check out https://github.com/deepchem/deepchem/blob/master/deepchem/hyper/tests/test_gaussian_hyperparam_opt.py. Our unit tests act as a repository of guaranteed functional examples. We should improve our documentation with more usage examples though!

**Comment by pjspol** [comment]
@rbharath Everything works well now except the transformer. If I wanted to use normalization as a transformer, what should I put in the brackets for transformers = [ ]? I've tried several things, resolved several issues, but am stuck on an Attribute Error about 'y_stds'. Thank you again for your help!

**Comment by pjspol** [comment]
@rbharath Specifically what I've tried most recently was `transformers = [dc.trans.NormalizationTransformer(transform_y=True)]` and the error message is `AttributeError: 'NormalizationTransformer' object has no attribute 'y_stds'`.

**Comment by pjspol** [comment]
And from what I've run with no transformer, the kernel keeps dying. I am running a GraphConvModel so that might be more complicated that the simple RF and MultitaskRegressor used in the unit tests. 

Here is my code: 
`transformers = []

optimizer = dc.hyper.GaussianProcessHyperparamOpt(
    lambda **params: dc.models.GraphConvModel(n_tasks=1, mode='regression', 
                                                  number_atom_features=78, dropouts=[0.], **params))

metric = dc.metrics.Metric(dc.metrics.mean_squared_error)
params_dict = {"batch_size": 10}
# These are per-example multiplier
search_range = {"batch_size": 4}

best_model, best_hyperparams, all_results = optimizer.hyperparam_search(
    params_dict,
    train_dataset,
    valid_dataset,
    metric,
    transformers,
    nb_epoch=2,
    max_iter=1,
    use_max=False)

valid_score = best_model.evaluate(valid_dataset, [metric], transformers)
assert valid_score["mean-mean_squared_error"] == min(all_results.values())
assert valid_score["mean-mean_squared_error"] > 0`

**Comment by rbharath** [comment]
I suspect the kernel dying is an ipython memory managment issue (IPython can die for long running complex jobs). I'd suggest trying to run the code as a standalone script and not in a notebook to improve stability.

The transformer usage is poorly documented here but the idea is that you need to have applied the transformer to the dataset already and the transformer is only used to undo the transformation to compute metrics correctly. For example, if you transformed the dataset ahead of time with`NormalizationTransformer`, then you would have a `y_stds` field set and you could undo the transformation for metrics computation. This isn't the best API; ideally we'd have the ability to test different transformations when doing hyperparam optimization. If you want to test different transformations, I'd suggest just layering a manual for-loop above the hyperparam optimizer

**Comment by pjspol** [comment]
@rbharath So I applied the normalization transform to the dataset using a custom loader function. What should I do to make the output transformer reverse the normalization?

Here is the code:

`import os
import deepchem as dc
from deepchem.molnet.load_function.molnet_loader import TransformerGenerator, _MolnetLoader
from deepchem.data import Dataset
from typing import List, Optional, Tuple, Union

MINE_TASKS = ['task1']


class _MyLoader(_MolnetLoader):
  
  def create_dataset(self) -> Dataset:
    dataset_file = '/hpc/group/rekerlab/pjs57/AHASwgt.csv'
    loader = dc.data.CSVLoader(
        tasks=self.tasks, feature_field="smiles", featurizer=self.featurizer, id_field="id")
    return loader.create_dataset(dataset_file, shard_size=8192)


def load_mydata(
    featurizer: Union[dc.feat.Featurizer, str] = 'GraphConv',
    splitter: Union[dc.splits.Splitter, str, None] = 'scaffold',
    transformers: List[Union[TransformerGenerator, str]] = ['normalization'],
    reload: bool = True,
    data_dir: Optional[str] = None,
    save_dir: Optional[str] = None,
    **kwargs
) -> Tuple[List[str], Tuple[Dataset, ...], List[dc.trans.Transformer]]:
    
  loader = _MyLoader(featurizer, splitter, transformers, MINE_TASKS,
                          data_dir, save_dir, **kwargs)
  return loader.load_dataset('AHASwgt.csv', reload)`

`tasks, datasets, transformers = load_mydata(featurizer=dc.feat.ConvMolFeaturizer(use_chirality=True), splitter='scaffold')
train_dataset, valid_dataset, test_dataset = datasets`

**Comment by rbharath** [comment]
You can just call `untransform`: https://deepchem.readthedocs.io/en/latest/api_reference/transformers.html#deepchem.trans.NormalizationTransformer.untransform to undo the transform.

I'd recommend messing around with it in an ipython notebook and visualizing the numbers until you get the flow right :)
