### ISSUE TITLE
DeepChem Development Docker Image

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2611]
It's surprisingly tricky to get a new DeepChem development environment set up. @VIGNESHinZONE's lightweight install instructions (https://deepchem.readthedocs.io/en/latest/get_started/installation.html#from-source-lightweight-guide) are the fastest way to get a new DeepChem source environment set up, but still require multiple package installs.

Ideally, we should have a DeepChem development docker image where you can pull down a deepchem environment fully configured for doing DeepChem development. The nice advantage here is that you can get up and running doing DeepChem development on a new machine very quickly.

**Comment by VIGNESHinZONE** [comment]
Similar to hugging face we could build multiple docker images depending on the use cases [huggingface multiple Dockerfile folder](https://github.com/huggingface/transformers/tree/master/docker)

1. Deepchem-Tensorflow-CPU
2. Deepchem-Tensorflow-GPU
3. Deepchem-Torch-CPU
4. Deepchem-Torch-GPU
5. Deepchem-Jax-CPU
6. Deepchem-Jax-GPU

All the requirements for each environment are given [here](https://github.com/deepchem/deepchem/tree/master/requirements)

**Comment by rbharath** [comment]
@VIGNESHinZONE This would be great! We should also make sure to add the requirements for developers (pytest/mypy/yapf/flake8/etc). Would you have bandwidth to take a crack at putting together these docker images?
