### ISSUE TITLE
DeepChem COLAB installation fails 

### ISSUE THREAD

**Issue by ravichas** [deepchem/deepchem#2613]
## Environment

* OS: Ubuntu 18.04.5 LTS 
* Package manager (PyPI or Conda):  Conda
* Python version: 3.7
* DeepChem version: As defined in `https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py`
* TensorFlow version: NA
* PyTorch version (optional):
* CUDA/cuDNN version (optional):
* Any other relevant information: Google COLAB 

## Checklist

- [ x ] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [ x ] I used Google Colab.
- [   ] I do have multiple CUDA versions on my machine.

## Additional context

Ran the following tutorial in COLAB
https://github.com/deepchem/deepchem/blob/master/examples/tutorials/06_Introduction_to_Graph_Convolutions.ipynb   
```
!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
```
**It gave me the following error. A few weeks ago, the code worked fine.** 

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3501  100  3501    0     0  43762      0 --:--:-- --:--:-- --:--:-- 43762
python version: 3.7.11
remove current miniconda
fetching installer from https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
done
installing miniconda to /root/miniconda
done
installing rdkit, openmm, pdbfixer
added conda-forge to channels
added omnia to channels
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-5-0b37ae099887> in <module>()
      2 get_ipython().system('curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py')
      3 import conda_installer
----> 4 conda_installer.install()
      5 get_ipython().system('/root/miniconda/bin/conda info -e')

1 frames
/content/conda_installer.py in install(chunk_size, file_name, url_base, conda_path, add_python_path, additional_channels, additional_packages)
    121       "--yes",
    122       "python=={}".format(python_version),
--> 123       *packages,
    124   ])
    125   logger.info("done")

/usr/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    361         if cmd is None:
    362             cmd = popenargs[0]
--> 363         raise CalledProcessError(retcode, cmd)
    364     return 0
    365 

CalledProcessError: Command '['/root/miniconda/bin/conda', 'install', '--yes', 'python==3.7.11', 'rdkit=2020.09.02', 'pdbfixer', 'openmm']' returned non-zero exit status 1.
```

**Comment by sasmendonca** [comment]
I have the same problem in colab too.
I try to install it with other commands (old deepchem commands), but I don't know if it is written.

**Comment by rbharath** [comment]
I've gotten a few failure reports for colab now so marking this as a high priority bug. We'll try to fix as soon as we can!

**Comment by ravichas** [comment]
Thank you @rbharath for your (& your team's) help.

**Comment by VIGNESHinZONE** [comment]
This is just a momentary fix on google ollab. Even I faced this issue a few days ago and found a workaround solution from StackOverflow (Im unable to find that link)

Check out this [collab notebook](https://colab.research.google.com/drive/1CfJ616ljb_aZgBuhrWeMN9_skQx1HKkx?usp=sharing)

The problem was with Rdkit installation

**Comment by ravichas** [comment]
@VIGNESHinZONE Thank you for sharing the notebook

**Comment by ph-mehdi** [comment]
53 / 5000
Translation results
Try this

%% capture
! pip install rdkit-pypi

**Comment by ravichas** [comment]
@ph-mehdi 
I like your suggestion, of using `rdkit-pypi`. I am using DeepChem with another software and  `mamba` causes more dependency (version) related issues. Thanks for your suggestion.
