### ISSUE TITLE
Pytorch models cannot be printed to screen

### ISSUE THREAD

**Issue by mgarort** [deepchem/deepchem#2617]
## 🐛 Bug

At least some Pytorch models cannot be printed to screen, as would be normal to do through `__str__` or `__repr__`. For example, MPNN fails with the error

`AttributeError: 'MPNNModel' object has no attribute 'edge_hidden_feats'`

and AttentiveFPModel fails with 

`AttributeError: 'AttentiveFPModel' object has no attribute 'dropout'`

## To Reproduce

Steps to reproduce the behavior for MPNN:

```
>> from deepchem.models.torch_models import MPNNModel
>> model = MPNNModel(mode='classification', n_tasks=len(tasks),
..                   batch_size=32, learning_rate=0.001)
```

Now, just try to print the model

```
>> print(model)
```

leading to `AttributeError: 'MPNNModel' object has no attribute 'edge_hidden_feats'`.

## Expected behavior

A string should be printed to screen by the `__str__` or the `__repr__` magic methods.

## Environment

* OS: Ubuntu 18
* Python version: 3.7.10
* DeepChem version: 2.5.0

**Comment by rbharath** [comment]
Thanks for the bug report! I've marked this as a bug and open to contribution. This should hopefully be a relatively easy fix

**Comment by arunppsg** [comment]
This is related to #2665.
