### ISSUE TITLE
Swap to rdkit-pypi

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2629]
The new rdkit-pypi package has rdkit on pypi! https://pypi.org/project/rdkit-pypi/

We should consider swapping the CI/tutorials to using rdkit-pypi. The really nice side effect would be we can finally get a one-line deepchem install that works out of the box without the awkward need to use conda just for rdkit

**Comment by davidRFB** [comment]
Hi @rbharath  ! I could help with this issue ! but I have a question. 
the main point is to change in tutorials this colab_install.py : 
```!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
```

Just for 
```
!pip install --pre deepchem
!pip install rdkit-pypi
```
In cases where only deepchem is used. right ? 
In tutorials that need openmm for the pdbfixer or other conda installation we should keep it ?

**Comment by rbharath** [comment]
Changing the tutorials would be a great start! Next steps would be to change the pip install itself so `pip install deepchem` comes with rdkit included :)

**Comment by arunppsg** [comment]
Probably we can start with change in `setup.py` to include `rdkit` and then change installation in colab. By this, we can do a single line installation in tutorial notebooks.

Related issues to this: #2613, #2701

**Comment by davidRFB** [comment]
Hi ! 
Totally agree, there are some tutorials that use the conda installer for openMM I guess. 
One question about modifying the setup.py: 

There is a line that calls the install_requieres,
```
install_requires=[
        'joblib',
        'numpy',
        'pandas',
        'scikit-learn',
        'scipy',
    ]
```

We should simply add rdkit-pypi.  ? 

```
install_requires=[
        'joblib',
        'numpy',
        'pandas',
        'scikit-learn',
        'scipy',
        'rdkit-pypi',
    ]
```
But I do not know if the setup function uses pip for installing ?

**Comment by arunppsg** [comment]
Yes, we should simply add `rdkit-pypi` in `setup.py`. When you use `pip` to install deepchem, as in `pip  install deepchem`, `pip` will use `setup.py` to find the required modules for installation and then install it. Here is a nice question in [SO](https://stackoverflow.com/questions/1471994/what-is-setup-py) about `setup.py`.

Regarding OpenMM, I am not sure what tutorials require it but most of the tutorials only have rdkit as other dependencies.
