### ISSUE TITLE
Where is the dummy featurizer????

### ISSUE THREAD

**Issue by ellagale** [deepchem/deepchem#2639]
## 🐛 Bug 🐛 Bug 🐛 Bug

I can see you have something called DummyFeaturizer which imports the data without doing anything. It's also in the docs. 

YET! I cannot use it? It doesn't seem to be in deepchem.feat or deepchem.feat.base
I found the UserDefined featurizer, which I can probably hack around with, but where is the dummy? 

## To Reproduce

from deepchem.feat import DummyFeaturizer
Featurizer = DummyFeaturizer()
tasks, datasets, transformers = dc.molnet.load_qm8(
    shard_size=2000, featurizer=Featurizer, splitter="random")

gives:
ImportError                               Traceback (most recent call last)
<ipython-input-12-0d0bdf5751b3> in <module>
----> 1 from deepchem.feat import DummyFeaturizer
      2 Featurizer = DummyFeaturizer()
      3 tasks, datasets, transformers = dc.molnet.load_qm8(
      4     shard_size=2000, featurizer=Featurizer, splitter="random")

ImportError: cannot import name 'DummyFeaturizer' from 'deepchem.feat' (C:\Users\ella_\.conda\envs\graphs-and-topology-for-chemists\lib\site-packages\deepchem\feat\__init__.py)

I also went looking for it via tab autocomplete to show the available featurizer options in both feat and feat.base classes
## Expected behavior
Expect there to be a dummy featurizer!

## Environment

* OS: windows
* Python version:
* DeepChem version: 2.5.0 (also tried 2.4)
* RDKit version (optional):
* TensorFlow version (optional): 2.3.0
* PyTorch version (optional):
* Any other relevant information: running from jupyter notebook atm

## Temporary Fix

If anyone else is trying to do this, the following code will implement a a featurizer that just gets the data including the original coords. The dataset.X is a list of rdkit Mol objects

from deepchem.feat.base_classes import UserDefinedFeaturizer
class MyFeaturizer(UserDefinedFeaturizer):
    def _featurize(self, datapoint):
        return datapoint

tasks, datasets, transformers = dc.molnet.load_qm8(
    shard_size=2000, featurizer=MyFeaturizer(None), splitter="random")

**Comment by rbharath** [comment]
The DummyFeaturizer is in the DeepChem 2.6.0 prerelease which you can access by

```
pip install --pre deepchem
```

As a note for us, we should change the readthedocs so it displays the stable version rather than the prerelease docs. `DummyFeaturizer` isn't in 2.5.0 which is likely why you aren't able to access it. Sorry for the trouble!

**Comment by ellagale** [comment]
Ah, thanks!
