### ISSUE TITLE
import deepchem as dc

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#265]
Currently `deepchem` suffers from a glut of long imports. The package structure leads to long names that aren't friendly to import or reason with. Here are some proposed changes (building on ideas in #264):
- Like `numpy` or `tensorflow`, change `deepchem` import to `dc`. Then to import a primitive in `deepchem.prim` (proposed in #264), users can say `dc.prim.foo_bar(...)`
- Expose all `deepchem` models in `deepchem.models`. Then models can be created with `model = dc.models.RobustMultitask(...)` for example.

**Comment by rbharath** [comment]
#268 makes both these changes, and demonstrates their use in the new graph-convolution example. The resulting style looks quite nice, so I think it should be used throughout the codebase (avoids long imports, and also provides the user an intuitive sense of the relationship between various classes). The refactoring required will be onerous, so will have to be spread across multiple PRs to be easily handled.

**Comment by rbharath** [comment]
#269 basically completes the transition to new style in codebase proper, but has not yet transitioned the example and benchmarking infrastructure. Needs to be done in a follow-up PR.

**Comment by rbharath** [comment]
#273 shortens the names of many submodules to make for cleaner imports. `dc.featurizers` becomes `dc.feat`, `dc.hyperparameters` to `dc.hyper`, and `dc.transformers` to `dc.trans`. Allows for a much cleaner import style.

**Comment by mpharrigan** [comment]
The new names are much more ambiguous. I weep for a new student trying to understand "feats" "hyper" and "trans". With modern IDEs, the autocomplete should take care of the extra keystrokes

**Comment by cxhernandez** [comment]
Just use `import X as Y` internally

**Comment by rbharath** [comment]
Contentious change. Most of the time these threads are just an echo-chamber :-)

I think the new-style reads very nicely (and beginners are unlikely to know what hyperparameters or featurizers are, while experts while see the shortening easily). I'm writing up a new deepchem tutorial, which I'll solicit feedback on. If there's a broad negative reaction to the new style, I can change back easily enough.

**Comment by rbharath** [comment]
#274 started converting over to new style, but only finished for Tox21. Will take a few more PRs to finish.

**Comment by hainm** [comment]
> #273 shortens the names of many submodules to make for cleaner imports. dc.featurizers becomes dc.feat, dc.hyperparameters to dc.hyper, dc.datasets to dc.data, and dc.transformers to dc.trans. Allows for a much cleaner import style.

It seems not a good decision.  I have no idea what `hyper`, `feat`, ... are. They are not even commonly used terms. Typing is not a big deal since you have autocompletion everywhere.

**Comment by rbharath** [comment]
How about  `dc.transform`, `dc.hyperparam`, and `dc.featurize`? These are intermediate names which aren't as long as the original but are comprehensible.

PS: I like using basic vim (no extensions), so autocomplete isn't a compelling answer for me :-)

**Comment by hainm** [comment]
> How about dc.transform, dc.hyperparam, and dc.featurize? 

just like @cxhernandez  said "Just use import X as Y internally": `

> PS: I like using basic vim (no extensions)

so do I, but basic vim does have `autocompletion`.  You might using super old vim. Mine is 7.0
(try Ctrl-P)

**Comment by rbharath** [comment]
Didn't actually know about Ctrl-P! Surprising given how long I've used vim :-)

I'm not in favor of an `import X as Y` style for handling submodules. I'd like users to be able to use deepchem with a single import `import deepchem as dc` (much like tensorflow can be used with `import tensorflow as tf` or numpy with `import numpy as np`). That said, I think there's a valid point about ambiguous names here.

I'm going to stick to my original plan and make the new tutorial with the short-syntax and solicit feedback. If the majority of the feedback echoes these same concerns, I'll restore meaningful submodule names.

**Comment by rbharath** [comment]
I think the code transition is complete. Feedback from active deepchem users has been mostly positive, so the new API is here to stay. For further style discussions, please raise new issues with specific code examples that are awkward under new API and we can discuss there.
