### ISSUE TITLE
Should we consider organizing deepchem/models directory

### ISSUE THREAD

**Issue by VIGNESHinZONE** [deepchem/deepchem#2657]
At present, deepchem's Model's directory is a little unorganized [deepchem/deepchem/models/](https://github.com/deepchem/deepchem/tree/master/deepchem/models) with Torch, Jax and Tests in a folder and with all tensorflow models outside. And the [deepchem/deepchem/models/tests](https://github.com/deepchem/deepchem/tree/master/deepchem/models/tests) is also very big.

Here is the suggested file structure

├── **Tensorflow Models**
│         ├── model1.py
│         ├── **Tests**
│          ..........|── test1.py
├── **Torch Models**
│         ├── model1.py
│         ├── **Tests**
│          ..........|── test1.py
├── **Jax Models**
          ├── model1.py
          ├── **Tests**
           ..........|── test1.py

I was thinking it might be a good idea since @rbharath had already made a test directory in [Jax Model Folder](https://github.com/deepchem/deepchem/tree/master/deepchem/models/jax_models) and the same could be done with other models as well

**Comment by rbharath** [comment]
I think this would be a great idea!
