### ISSUE TITLE
Tensorflow version on main page

### ISSUE THREAD

**Issue by whitead** [deepchem/deepchem#2659]
## 📚 Installation

The deep chem website (https://deepchem.io/) says to install `pip install tensorflow~=2.4`, but that resolves to latest major version (e.g., `2.6`). I think you probably want `pip install "tensorflow<2.5"`. Unless you intend for users to install latest version of TF2.

**Comment by whitead** [comment]
Hi @arunppsg, my point is that if you run `pip install tensorflow~=2.4`, you will receive the latest 2.x version of Tensorflow (i.e., 2.6). You should revise the website to be `pip install tensorflow < 2.5` if you want version 2.4.x installed.

**Comment by rbharath** [comment]
Fixed by the new website

**Comment by whitead** [comment]
That dedication! Thanks!
