### ISSUE TITLE
I love this app could i make two pages with my same imfo

### ISSUE THREAD

**Issue by Flakotako** [deepchem/deepchem#2660]
## ❓ Questions & I wouldn't recommend but it's you

**Comment by Flakotako** [comment]
No not rrcommended

**Comment by shubhamsawant88** [comment]
Can some one remove me from this thread. I have tried unsubscribing many
times still I consistently keep on getting this email.

**Comment by peastman** [comment]
By "this thread" do you mean the deepchem repo?  You need to do that yourself.  Click the "unwatch" button at the top of this page.
