### ISSUE TITLE
AttributeError: module 'deepchem.models' has no attribute 'TorchModel'

### ISSUE THREAD

**Issue by mohammad-saber** [deepchem/deepchem#2663]
Hi, thank you for sharing your great work. 

I would like to make a PyTorch model in deepchem. However, when I run the following code:

```
pytorch_model = torch.nn.Sequential(
    torch.nn.Linear(1024, 1000),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(1000, 1)
)

model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())
```

I get error:

`AttributeError: module 'deepchem.models' has no attribute 'TorchModel'
`

Environment:

- OS: macOS 11.5
- Python 3.7

I installed deepchem and PyTorch by in a conda virtual environment:

```
pip install tensorflow~=2.4
pip install deepchem
conda install -c conda-forge rdkit
conda install pytorch torchvision torchaudio -c pytorch
```

I can import deepchem & torch in this environment.

**Comment by arunppsg** [comment]
Hey, can you share deepchem version which you are using? It seems to work for me. You can get it by using `import deepchem as dc; dc.__version__`

**Comment by mohammad-saber** [comment]
Thanks for reply. 

`pip install deepchem` installed deepchem version 2.5.0.

**Comment by arunppsg** [comment]
I tried reproducing it but I was not able to. I am not sure what is causing this issue in your case.

**Comment by mohammad-saber** [comment]
May I ask which version you are using?

**Comment by arunppsg** [comment]
It happens when the `sklearn` version is after 0.24. It requires some fix. See #2665. Meanwhile, you can use sklearn version before 0.24 to use `print(model)`.

**Comment by mohammad-saber** [comment]
I uninstalled sklearn 0.24.2 and installed version 0.23.2. However I get the following error when running print(model).

`RecursionError: maximum recursion depth exceeded while calling a Python object
`

I can get model structure by `model.model.summary()` after model fitting for Keras models. But, `print(summary)` gives error for both Keras and PyTorch models.
