### ISSUE TITLE
Printing a Model

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#2665]
## To Reproduce

Suppose I want to find the summary of a deepchem model and I use `print(model)` it throws an `AttributeError`.

```
model = dc.models.AtomicConvModel(n_tasks = 4)
print (model)
```

I would like `print(model)` to print the summary of the model. Any hints on how to fix it?
Thanks

**Comment by arunppsg** [comment]
I think it is due to a problem with `sklearn` version. When I do the same in colab, I only get a future warning

`/usr/local/lib/python3.7/dist-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning`

In my case, I was using sklearn version 0.24.2

**Comment by rbharath** [comment]
Oh hmm, I think this is happening because we inherit from Sklearn Estimator in `dc.models.Model`. This is an awkward downstream consequence!
