### ISSUE TITLE
How to get "ConvMol" features as numpy array of numeric values not "deepchem.feat.mol_graphs.ConvMol" objects

### ISSUE THREAD

**Issue by mohammad-saber** [deepchem/deepchem#2675]
## ❓ Questions & Help

Hi, thank you for reading my question. 

I would like to get "ConvMol" features for a list of SMILES as below:

```
smiles = ["C", "CCC", "C1=CC=CN=C1"]
featurizer=dc.feat.ConvMolFeaturizer(use_chirality=False, per_atom_fragmentation=False)
features = featurizer.featurize(smiles)   # numpy array, it returns an object for every molecule
type(features[0])   # deepchem.feat.mol_graphs.ConvMol
```

For every molecule, `features` contains a` deepchem.feat.mol_graphs.ConvMol` object.
Is it possible to get numeric values of features as numpy array or pandas DataFrame? I mean, every row is a molecule and columns are numeric values of features (similar to FingerPrint that we get from RDKit). 

**Reason:**
I would like to try a ML model which is not included in deepchem. This model doesn't accept deepchem object as input. So, I need to get features as numpy array or pandas DataFrame.

Thank you for your help.

**Comment by peastman** [comment]
Here is the code in GraphConvModel that takes a batch of ConvMol objects and produces the numpy arrays that get passed as input to the model:

https://github.com/deepchem/deepchem/blob/22a8fbd7350540d6e0410223c0c75d744c241495/deepchem/models/graph_models.py#L1007-L1014

**Comment by mohammad-saber** [comment]
Thank you. I used the above code. 
I can get graph features as numeric values. It is a List containing 13 numpy arrays. 
However, the size of arrays is different for every molecule (because No. of atoms is different). 
So, I cannot concatenate features of all molecules all-together and make a DataFrame. DataFrame requires the same No. of columns for every row (which is a molecule in this case). 
I think it is not possible to make a DataFrame of graph features for a set of molecules.

**Comment by peastman** [comment]
That's what the call to `agglomerate_mols()` in the first line is for.  It combines all the ConvMol objects into a single MultiConvMol.
