### ISSUE TITLE
Reshard fails for DiskDataset objects with no labels

### ISSUE THREAD

**Issue by Suzukazole** [deepchem/deepchem#2677]
## 🐛 Bug

This bug arises when attempting to reshard a `DiskDataset` created using `CSVLoader`. I believe the reason this happens is because the `create_dataset()` method of  the `DataLoader` class  sets y to `None` in the `shard_generator()` method,  if the labels column is empty ([for reference](https://github.com/deepchem/deepchem/blob/master/deepchem/data/data_loader.py#L219)). As a result, when the dataset is resharded, the call to the `generator` method fails since it requires the length of the column. 

## To Reproduce
The dummy dataset I will use to illustrate the problem looks something like [this: ](https://github.com/Suzukazole/deepchem/blob/usptotok/deepchem/data/tests/reaction_smiles.csv)
```
reactions
CCS(=O)(=O)Cl.OCCBr>CCN(CC)CC.CCOCC>CCS(=O)(=O)OCCBr
CC(C)CS(=O)(=O)Cl.OCCCl>CCN(CC)CC.CCOCC>CC(C)CS(=O)(=O)OCCCl
O=[N+]([O-])c1cccc2cnc(Cl)cc12>CC(=O)O.O.[Fe].[Na+].[OH-]>Nc1cccc2cnc(Cl)cc12
Cc1cc2c([N+](=O)[O-])cccc2c[n+]1[O-].O=P(Cl)(Cl)Cl>>Cc1cc2c([N+](=O)[O-])cccc2c(Cl)n1
```

```
# file_path is path to above dataset file

>>> featurizer = dc.feat.DummyFeaturizer()
>>> loader = dc.data.CSVLoader(tasks=[], feature_field="reactions", featurizer=featurizer)
>>> dataset = loader.create_dataset(file_path)
>>> dataset.reshard(shard_size=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/deepchem/deepchem/data/datasets.py", line 1477, in reshard
    generator(), data_dir=reshard_dir, tasks=self.tasks)
  File "/deepchem/deepchem/data/datasets.py", line 1204, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/deepchem/deepchem/data/datasets.py", line 1461, in generator
    y = np.reshape(y, (len(y),) + y_shape[1:])
TypeError: object of type 'NoneType' has no len()
```

## Expected behavior
It should reshard the above dataset to a `shard_size` of 10.

## Environment

* OS: Ubuntu
* Python version: 3.7.0
* DeepChem version: 2.6.0dev(this [branch](https://github.com/deepchem/deepchem/pull/2641))

## Additional context
Above error came up while coming up with a fix for the splitter bug, which happens due to a similar reason as well.

**Comment by rbharath** [comment]
Thanks for the write-up! Marking this as a bug and open for contribution. This would be a good first bugfix PR for newcomers

**Comment by davidRFB** [comment]
Hi @Suzukazole  @rbharath ! I have been working a little on this issue. But I found a solution involving the generator function inside the reshard function. However I have a question ! 
for the example case : 
```reactions
CCS(=O)(=O)Cl.OCCBr>CCN(CC)CC.CCOCC>CCS(=O)(=O)OCCBr
CC(C)CS(=O)(=O)Cl.OCCCl>CCN(CC)CC.CCOCC>CC(C)CS(=O)(=O)OCCCl
O=[N+]([O-])c1cccc2cnc(Cl)cc12>CC(=O)O.O.[Fe].[Na+].[OH-]>Nc1cccc2cnc(Cl)cc12
Cc1cc2c([N+](=O)[O-])cccc2c[n+]1[O-].O=P(Cl)(Cl)Cl>>Cc1cc2c([N+](=O)[O-])cccc2c(Cl)n1
```


and the code: 
```
>>>dataset = loader.create_dataset("data")
>>>dataset.reshard(shard_size=10)
>>>print(dataset.get_number_shards())
1
```
should have an output of 10 ? the number of entries in the dataset is 4 therefore  the first shard would contain the whole elements ? 

PD: The PR #2654 that we talked the last Friday solves a different issue.

**Comment by peastman** [comment]
`shard_size` is the size of each shard, not the number of shards.  Each one can have up to 10 samples, and the dataset only has 4 samples, so everything fits in a single shard.

**Comment by arunppsg** [comment]
Hey, I tried this and it seems to work fine:
```
featurizer = dc.feat.DummyFeaturizer()
smiles = [
'CCS(=O)(=O)Cl.OCCBr>CCN(CC)CC.CCOCC>CCS(=O)(=O)OCCBr',
'CC(C)CS(=O)(=O)Cl.OCCCl>CCN(CC)CC.CCOCC>CC(C)CS(=O)(=O)OCCCl',
'O=[N+]([O-])c1cccc2cnc(Cl)cc12>CC(=O)O.O.[Fe].[Na+].[OH-]>Nc1cccc2cnc(Cl)cc12',
'Cc1cc2c([N+](=O)[O-])cccc2c[n+]1[O-].O=P(Cl)(Cl)Cl>>Cc1cc2c([N+](=O)[O-])cccc2c(Cl)n1'
]

df = pd.DataFrame({'smiles':smiles})
df.to_csv('smiles.csv')
loader = dc.data.CSVLoader(tasks=[], feature_field="smiles", featurizer=featurizer)
dataset = loader.create_dataset('smiles.csv')
dataset.reshard(shard_size=10) 
dataset.get_number_shards() # 1
```
Closing this hence it is resolved.
