### ISSUE TITLE
pytorch model training error: module 'multiprocessing' has no attribute 'dummy'

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2678]
## ❓ Questions & Help

when running the examples in document, codes as follow:

- `import deepchem as dc
- dataset_config = {"reload": False, "featurizer": dc.feat.CGCNNFeaturizer(), "transformers": []}
- tasks, datasets, transformers = dc.molnet.load_perovskite(**dataset_config)
- train, valid, test = datasets
- model = dc.models.CGCNNModel(mode='regression', batch_size=32, learning_rate=0.001)
- avg_loss = model.fit(train, nb_epoch=50)`

when running "model.fit(train, nb_epoch=50)" with error:

- `Traceback (most recent call last):
-   File "D:\ProgramData\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
-     exec(code_obj, self.user_global_ns, self.user_ns)
-   File "<ipython-input-37-1c8a9c9da39e>", line 1, in <module>
-     avg_loss = model.fit(train, nb_epoch=50)
-   File "D:\ProgramData\anaconda\lib\site-packages\deepchem\models\torch_models\torch_model.py", line 324, in fit
-     checkpoint_interval, restore, variables, loss, callbacks, all_losses)
-   File "D:\ProgramData\anaconda\lib\site-packages\deepchem\models\torch_models\torch_model.py", line 397, in fit_generator
-     for batch in generator:
-   File "D:\ProgramData\anaconda\lib\site-packages\deepchem\models\torch_models\torch_model.py", line 940, in default_generator
-     pad_batches=pad_batches):
-   File "D:\ProgramData\anaconda\lib\site-packages\deepchem\data\datasets.py", line 1583, in iterate
-     pool = multiprocessing.dummy.Pool(1)
- AttributeError: module 'multiprocessing' has no attribute 'dummy'`
- 

my deepchem env. info:
windows 10 python3.7.6(conda 4.10.3)  pytorch:1.6(cpuonly)  deepchem 2.6 dev

can anyone help me?

**Comment by rbharath** [comment]
I haven't seen this error before but I suspect a python environment mismatch. Can you try following the from source lightweight guide to see if that works? https://deepchem.readthedocs.io/en/latest/get_started/installation.html#from-source-lightweight-guide

**Comment by biotech7** [comment]
thanks. i tested it on Centos 8 under the same env. , it turned out working smoothly.  so this error is mostly likely related to python/conda itself on my win10.
