### ISSUE TITLE
DeepChem Model Wishlist

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2680]
There are a number of important molecular and scientific models that I would love to see implementations for in DeepChem. Implementations of any of these models would be a great contribution to DeepChem. As an incentive for contributors, contributing a model would earn authorship on one of our upcoming manuscripts! If you have bandwidth to contribute an implementation, please chime in below 

- [ ] IterRefLSTMs from https://pubs.acs.org/doi/10.1021/acscentsci.6b00367 (We have some old DeepChem code that doesn't work in today's DeepChem that can be ported, see https://github.com/deepchem/deepchem/issues/2070). 
- [x] D-MPNN (from Chemprop, https://github.com/chemprop/chemprop, https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00237). @atreyamaj has volunteered to take a crack at the implementation
- [x] Grover (from https://github.com/tencent-ailab/grover, https://papers.nips.cc/paper/2020/hash/94aef38441efa3380a3bed3faf1f9d5d-Abstract.html). Current state of the art on MoleculeNet
- [x] FermiNet (from https://github.com/deepmind/ferminet, https://deepmind.com/blog/article/FermiNet)
- [ ] PauliNet (from https://github.com/deepqmc/deepqmc, https://arxiv.org/abs/1909.08423)
- [ ] MXMNet (from https://github.com/zetayue/MXMNet, https://arxiv.org/abs/2011.07457). Current state of the art on QM9
- [x] MEGNet (from https://pubs.acs.org/doi/abs/10.1021/acs.chemmater.9b01294, https://github.com/materialsvirtuallab/megnet)
- [ ] MultiScaleGNN (from https://arxiv.org/pdf/2106.04900.pdf)
- [ ] Rexgen (from https://github.com/connorcoley/rexgen_direct, https://pubs.rsc.org/en/content/articlelanding/2019/sc/c8sc04228d)
- [ ] Retrotemp (from https://github.com/connorcoley/retrotemp, https://chemistry-europe.onlinelibrary.wiley.com/doi/abs/10.1002/chem.201605499)
- [ ] DeepONet (from https://github.com/lululxvi/deeponet, https://github.com/lululxvi/deepxde)
- [ ] Universial DIfferential Equations (from https://arxiv.org/pdf/2001.04385.pdf, https://github.com/ChrisRackauckas/universal_differential_equations)
- [ ] Neural ODEs (from https://github.com/rtqichen/torchdiffeq, https://github.com/msurtsukov/neural-ode, https://arxiv.org/abs/1806.07366)
- [ ] Lagrangian Neural Networks (from https://arxiv.org/abs/2003.04630, https://github.com/MilesCranmer/lagrangian_nns)
- [ ] Hamiltonian Neural Networks (from https://arxiv.org/abs/1906.01563, https://github.com/greydanus/hamiltonian-nn)
- [ ] hPINNs (from https://arxiv.org/abs/2102.04626, https://github.com/lululxvi/deepxde)
- [x] Gaussian Processes (this is already in scikit learn https://scikit-learn.org/stable/modules/gaussian_process.html, so it would be sufficient to add a tutorial. Might be good for beginners)
- [ ] NequIP (from https://arxiv.org/abs/2101.03164, https://github.com/mir-group/nequip)
- [ ] Junction Tree Variational Autoencoders (https://github.com/wengong-jin/icml18-jtnn, https://arxiv.org/abs/1802.04364)
- [ ] Convolutional Neural ODEs (https://ml4physicalsciences.github.io/2020/files/NeurIPS_ML4PS_2020_125.pdf)

## Equivariant Models
- [ ] Tensor Field Network (https://github.com/tensorfieldnetworks/tensorfieldnetworks)
- [ ] E3NN (from https://github.com/e3nn/e3nn, https://arxiv.org/abs/2101.03164)
- [ ] SE(3) Transformer (from https://github.com/FabianFuchsML/se3-transformer-public, https://github.com/lucidrains/se3-transformer-pytorch, https://arxiv.org/abs/2006.10503)

## Classical Machine Learning
- [ ] Hidden Markov Models (perhaps just a wrapper around https://github.com/hmmlearn/hmmlearn). 
- [ ] Kalman Filter (can use https://github.com/rlabbe/filterpy as a reference.)

**Comment by nicola-decao** [comment]
Maybe seen and implementation of MolGAN would be nice

**Comment by rbharath** [comment]
@nicola-decao We already have MolGAN in DeepChem! https://deepchem.readthedocs.io/en/latest/api_reference/models.html#basicmolganmodel. I hadn't realized you were the lead author :)

**Comment by xuzhang5788** [comment]
how about reinforcement learning, such as Reinvent.

**Comment by nicola-decao** [comment]
@rbharat Oh WOW I did not know that! 😱 I'll proudly share that with people then!

**Comment by huvers** [comment]
MegaMolBART would be interesting to compare against the other generative models: https://ngc.nvidia.com/catalog/models/nvidia:clara:megamolbart

**Comment by rbharath** [comment]
We have some funding now to support people who want to implement models. Please apply following directions at https://forum.deepchem.io/t/deepchem-model-wishlist-internships/569 if you are interested!

**Comment by DwaraknathT** [comment]
Hi. I would love to take a crack at implementing SE(3) Transformer. Since it has a high quality implementation available already, it should give me a gentle intro to deepchem's repo!

**Comment by shivance** [comment]
Neural Flows (https://proceedings.neurips.cc/paper/2021/file/b21f9f98829dea9a48fd8aaddc1f159d-Paper.pdf) proposes an
alternative by directly modeling the solution curves — the flow of an ODE — with a neural network. This immediately eliminates the need for expensive numerical solvers while still maintaining the modeling capability of neural ODEs.

**Comment by TheRealSalmon** [comment]
I'm currently working on adding a tutorial for scikit-learn's Gaussian Processes. However, I've been having trouble with getting calibrated uncertainty out of it. I plan to try again with a different implementation of Gaussian Processes like GPy.

**Comment by rbharath** [comment]
@TheRealSalmon I believe that @atreyamaj was working with a student on ChemProp but I'm not sure if that project is still proceeding. Perhaps it might be worth teaming up and discussing? I'd really like to see D-MPNN make it into ChemProp so I can help on the effort as well :)

**Comment by atreyamaj** [comment]
> @TheRealSalmon I believe that @atreyamaj was working with a student on ChemProp but I'm not sure if that project is still proceeding. Perhaps it might be worth teaming up and discussing? I'd really like to see D-MPNN make it into ChemProp so I can help on the effort as well :)

Hi! I'm really sorry for the delay, got caught up with my thesis project for this semester. Now that the project is almost over, I will be working on DMPNN starting now.

**Comment by Crispae** [comment]
@atreyamaj  I would like to work on DPMNN project as well,

**Comment by Zymrael** [comment]
Many of these models (Neural ODEs, Lagrangian / Hamiltonian) and various neural operators are available in [torchdyn](https://github.com/DiffEqML/torchdyn) and / or the [DiffeqML](https://torchdyn.org/) ecosystem. We'd be happy to help `deepchem`  adopt our API.

**Comment by rbharath** [comment]
@Zymrael I believe @shivance and @VIGNESHinZONE are both working on different ODE/PDE/NODE models and might be interested in discussing with you

**Comment by shivance** [comment]
@Zymrael Can we hop on a call sometime to discuss on the same?

**Comment by BalajiAI** [comment]
@rbharath this also seems interesting!
https://astroautomata.com/paper/rediscovering-gravity/

**Comment by riya-singh28** [comment]
@gusty1g Is this Model Wishlist updated?

**Comment by gusty1g** [comment]
> @gusty1g Is this Model Wishlist updated?

Mostly. I am working on grover. If you are interested to work on some, post that you are working on it here.

**Comment by HridayM25** [comment]
Hey! Can I work on the Kalman Filter? Is it still available?

**Comment by naseehasalam** [comment]
Hey @rbharath and fellow DeepChem contributors! Can I work on HM Models,if someone else isnt' working on it? @rbharath

**Comment by shreyasvinaya** [comment]
@rbharath can we add GFlowNet (https://papers.nips.cc/paper/2021/hash/e614f646836aaed9f89ce58e837e2310-Abstract.html), (https://openreview.net/pdf?id=JFSaHKNZ35b),(https://pubs.rsc.org/en/content/articlepdf/2023/dd/d3dd00002h) as a generative model

**Comment by gs-chaitanya** [comment]
Hey @rbharath, can I work on implementing Neural ODEs under GSOC 2024.
Please let me know how to proceed

**Comment by benkimz** [comment]
Hamiltonian Neural Networks

**Comment by benkimz** [comment]
> There are a number of important molecular and scientific models that I would love to see implementations for in DeepChem. Implementations of any of these models would be a great contribution to DeepChem. As an incentive for contributors, contributing a model would earn authorship on one of our upcoming manuscripts! If you have bandwidth to contribute an implementation, please chime in below
> 
> * [ ]  IterRefLSTMs from https://pubs.acs.org/doi/10.1021/acscentsci.6b00367 (We have some old DeepChem code that doesn't work in today's DeepChem that can be ported, see [deepchem.nn not found #2070](https://github.com/deepchem/deepchem/issues/2070)).
> * [x]  D-MPNN (from Chemprop, https://github.com/chemprop/chemprop, https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00237). @atreyamaj has volunteered to take a crack at the implementation
> * [x]  Grover (from https://github.com/tencent-ailab/grover, https://papers.nips.cc/paper/2020/hash/94aef38441efa3380a3bed3faf1f9d5d-Abstract.html). Current state of the art on MoleculeNet
> * [x]  FermiNet (from https://github.com/deepmind/ferminet, https://deepmind.com/blog/article/FermiNet)
> * [ ]  PauliNet (from https://github.com/deepqmc/deepqmc, https://arxiv.org/abs/1909.08423)
> * [ ]  MXMNet (from https://github.com/zetayue/MXMNet, https://arxiv.org/abs/2011.07457). Current state of the art on QM9
> * [x]  MEGNet (from https://pubs.acs.org/doi/abs/10.1021/acs.chemmater.9b01294, https://github.com/materialsvirtuallab/megnet)
> * [ ]  MultiScaleGNN (from https://arxiv.org/pdf/2106.04900.pdf)
> * [ ]  Rexgen (from https://github.com/connorcoley/rexgen_direct, https://pubs.rsc.org/en/content/articlelanding/2019/sc/c8sc04228d)
> * [ ]  Retrotemp (from https://github.com/connorcoley/retrotemp, https://chemistry-europe.onlinelibrary.wiley.com/doi/abs/10.1002/chem.201605499)
> * [ ]  DeepONet (from https://github.com/lululxvi/deeponet, https://github.com/lululxvi/deepxde)
> * [ ]  Universial DIfferential Equations (from https://arxiv.org/pdf/2001.04385.pdf, https://github.com/ChrisRackauckas/universal_differential_equations)
> * [ ]  Neural ODEs (from https://github.com/rtqichen/torchdiffeq, https://github.com/msurtsukov/neural-ode, https://arxiv.org/abs/1806.07366)
> * [ ]  Lagrangian Neural Networks (from https://arxiv.org/abs/2003.04630, https://github.com/MilesCranmer/lagrangian_nns)
> * [ ]  Hamiltonian Neural Networks (from https://arxiv.org/abs/1906.01563, https://github.com/greydanus/hamiltonian-nn)
> * [ ]  hPINNs (from https://arxiv.org/abs/2102.04626, https://github.com/lululxvi/deepxde)
> * [x]  Gaussian Processes (this is already in scikit learn https://scikit-learn.org/stable/modules/gaussian_process.html, so it would be sufficient to add a tutorial. Might be good for beginners)
> * [ ]  NequIP (from https://arxiv.org/abs/2101.03164, https://github.com/mir-group/nequip)
> * [ ]  Junction Tree Variational Autoencoders (https://github.com/wengong-jin/icml18-jtnn, https://arxiv.org/abs/1802.04364)
> * [ ]  Convolutional Neural ODEs (https://ml4physicalsciences.github.io/2020/files/NeurIPS_ML4PS_2020_125.pdf)
> 
> ## Equivariant Models
> * [ ]  Tensor Field Network (https://github.com/tensorfieldnetworks/tensorfieldnetworks)
> * [ ]  E3NN (from https://github.com/e3nn/e3nn, https://arxiv.org/abs/2101.03164)
> * [ ]  SE(3) Transformer (from https://github.com/FabianFuchsML/se3-transformer-public, https://github.com/lucidrains/se3-transformer-pytorch, https://arxiv.org/abs/2006.10503)
> 
> ## Classical Machine Learning
> * [ ]  Hidden Markov Models (perhaps just a wrapper around https://github.com/hmmlearn/hmmlearn).
> * [ ]  Kalman Filter (can use https://github.com/rlabbe/filterpy as a reference.)

Hamiltonian Neural Networks

**Comment by manas1245agrawal** [comment]
Hey is there still any model left to make

**Comment by ShigrafS** [comment]
There are models that are not ticked off from the list. I have experience with implementing models and would like to contribute to the code.

**Comment by abhivansh-in** [comment]
Hey @rbharath !
I am up for implementing MultiScale GNN model, has previously worked with them , and a past experience of Debugging as well!

**Comment by shivamgcodes** [comment]
Hey, i would love to contribute to the project, i am particularly interested in the Neural ODE project...
Can i get some more details and guidance on what exactly i have to do ?? I noticed the GitHub links attached to the Neural ODE section—are those implementations already integrated, or are they provided for reference? If they're not integrated, should I work on integrating those libraries with DeepChem, or build the implementation from scratch?

**Comment by GodRishUniverse** [comment]
@rbharath I would like to contribute and create models for Hamiltonian Neural networks and NequIP. How can I reach out to a GSoC 2025 mentor for this? I have relevant experience and would greatly appreciate your response.

**Comment by hkazemabad** [comment]
Hi everyone! 👋  
I’m interested in contributing the Directed Message Passing Neural Network (D-MPNN) model to DeepChem.   
I have experience in AI/ML, particularly in drug discovery, and I’ve reviewed the Chemprop paper and implementation.  

I’d like to start working on this. Please let me know if there are any specific guidelines I should follow.  
Looking forward to your feedback! 🚀  

Best,  
Hoda

**Comment by Zrahay** [comment]
Heyo @rbharath! 

I see Hidden Markov Models had been taken up but not successfully implemented yet, so, I'll be working on that.

**Comment by aadilrizwan** [comment]
Hi @rbharath I Implement Differentiable Kalman Filter in PyTorch #4722 plz check it

**Comment by kevinquach** [comment]
Hi @rbharath as a first time contributor, I'm interested in implementing NeuralODEModel as a TorchModel subclass, but would like to check in on the design first before implementing.

I found the [ODE utility file](https://github.com/deepchem/deepchem/blob/master/deepchem/utils/differentiation_utils/integrate/explicit_rk.py) in the codebase (the infrastructure from the Singh et al. 2024 paper) and [tutorial](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Ordinary_Differential_Equation_Solving_using_deepchem.ipynb) and looked at them carefully. It implements fixed-step Runge-Kutta solvers with the signature _fcn(t, y, params)_ where params is a tensor of explicit equation parameters and designed for the case where the ODE is known and you are estimating scalar coefficients from data.

If I'm understanding correctly, the Neural ODE in this wishlist is a different use case. The ODE function _f(t, h)_ is itself an nn.Module whose weights are learned end-to-end from data. This needs the following, which the current infrastructure doesn't provide:

- Adjoint method for O(1) memory backpropagation (odeint_adjoint)
- Adaptive step sizing (default to dopri5) for reliable integration of nonlinear learned dynamics
- Function interface that accepts an nn.Module rather than a params tensor

All three are provided by [torchdiffeq](https://github.com/rtqichen/torchdiffeq, which I plan to use as a soft dependency and implement NeuralODEModel as a TorchModel wrapping an ODEFunc(nn.Module) integrated via odeint_adjoint. 

Please let me know what you think, thanks!
