### ISSUE TITLE
Installation from source fails (Jax)

### ISSUE THREAD

**Issue by RMeli** [deepchem/deepchem#2683]
## 📚 Installation

Installation command:
```bash
source scripts/install_deepchem_conda.sh 3.7 gpu
```

Installation error:
```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.70+cuda111 (from jax[cuda111]->-r /biggin/b195/lina3015/Documents/git/deepchem/condaenv.dendjjs6.requirements.txt (line 10)) (from versions: 0.1.41, 0.1.42, 0.1.43, 0.1.44, 0.1.45, 0.1.46, 0.1.47, 0.1.48, 0.1.50, 0.1.51, 0.1.52, 0.1.55, 0.1.56, 0.1.57, 0.1.58, 0.1.59, 0.1.60, 0.1.61, 0.1.62, 0.1.63, 0.1.64, 0.1.65, 0.1.66, 0.1.67, 0.1.68, 0.1.69, 0.1.70)
ERROR: No matching distribution found for jaxlib==0.1.70+cuda111 (from jax[cuda111]->-r /biggin/b195/lina3015/Documents/git/deepchem/condaenv.dendjjs6.requirements.txt (line 10))
```

## Environment

* OS: Ubuntu 18.04.5 LTS
* Package manager (PyPI or Conda): `conda`  +  `pip` (see #2414)
* Python version: Python 3.7.11
* DeepChem version: 7c42ebb7
* TensorFlow version: 2.4
* PyTorch version (optional): 1.8.1+cu111
* CUDA/cuDNN version (optional): 11.2

## Checklist

- [x] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [ ] I used Google Colab.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by VIGNESHinZONE** [comment]
Thanks for raising the issue, i think there is misinformation in the documentation for the lightweight guide. 
```
source scripts/light/install_deepchem.sh $1 $2 $3
```
$1  = Python version , for Ex - `3.7`
$2  = hardware setting , for Ex - `cuda` or `cpu`
$3  = Neural Network backend , for Ex - `tensorflow`, `torch`, `jax`

**Comment by RMeli** [comment]
Hi @VIGNESHinZONE , thanks for the fast reply! However, I was trying to [install from source with conda](https://deepchem.readthedocs.io/en/latest/get_started/installation.html#from-source-with-conda) and not the [lightweight](https://deepchem.readthedocs.io/en/latest/get_started/installation.html#from-source-lightweight-guide) guide. As far as I can tell, the `source scripts/install_deepchem_conda.sh` script only requires two arguments (8b73e2e40e4e7ae41c8637a3bc7fee40e869c8a6)? This problem might actually be related to #2671
