### ISSUE TITLE
Converting NumpyDataset to Pytorch dataset

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#2687]
## 🐛 Bug

I tried to create a torch dataset from `dc.data.NumpyDataset` and I tried the following example:

```
import deepchem as dc
import numpy as np
X = np.random.rand(5, 2)
y = np.random.rand(5)
dataset = dc.data.NumpyDataset(X, y)
type(dataset.make_pytorch_dataset())
```

I expected a `torch.utils.data.IterableDataset` but got a `deepchem.data.pytorch_datasets._TorchNumpyDataset` object.

## Environment

* OS: Google Colab
* DeepChem version: 2.6.0.dev

**Comment by arunppsg** [comment]
Two pointers on this:

- `deepchem.data.pytorch_datasets._TorchNumpyDataset` derives from `torch.utils.data.IterableDataset` class. We can add few lines of code in `_TorchNumpyDataset` class to return a `torch.utils.data.DataLoader` object. A sample:
```
dataset = dc.data.NumpyDataset(X, y)
iterable_dataset = dataset.make_pytorch_dataset()
loader = torch.utils.data.DataLoader(iterable)
```
- Or we can update the documentation [here](deepchem.data.pytorch_datasets._TorchNumpyDataset) that the return type is `deepchem.data.pytorch_datasets._TorchNumpyDataset` so that it is not misleading. In this case, the user has to convert the `IterableDataset` into a `DataLoader` object explicitly.

**Comment by rbharath** [comment]
Maybe to keep the fix simple, let's just update the documentation and add a usage example perhaps?

**Comment by peastman** [comment]
What is misleading about it?  The documentation says the return value is a torch.utils.data.IterableDataset.  It is.  The fact that it's a private subclass of IterableDataset is unimportant.  That's the whole point of subclassing: to separate the internal implementation (`_TorchNumpyDataset`) from the public API (`IterableDataset`).  The API refers only to public classes.

**Comment by arunppsg** [comment]
Sorry, I didn't know about it earlier. Thanks for clarification.
