### ISSUE TITLE
module load error：module 'deepchem.models' has no attribute 'GraphConvModel'

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2689]
## ❓ Questions & Help

Hi, team!
     i failed to load 'GraphConv' model when in an effort to load it. the simplified codes as follows:
```
import deepchem as dc

model = dc.models.GraphConvModel(n_tasks=1,
                                 mode='regression',
                                 batch_size=100,
                                 learning_rate=0.001
                                 )

Traceback (most recent call last):
  File "D:\ProgramData\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-67d77169f2a2>", line 1, in <module>
    model = dc.models.GraphConvModel(n_tasks=1,
AttributeError: module 'deepchem.models' has no attribute 'GraphConvModel'
```
i cannot resolve this issue whether it is mainly due to IPython or deepchem itself ?

**Comment by biotech7** [comment]
if i set `model = dc.models.graph_models.GraphConvModel` it also return error `module 'deepchem.models' has no attribute 'graph_models'`

**Comment by arunppsg** [comment]
I tried reproducing it but I was not able to using `deepchem` version 2.6.0.dev. Can you share your version?

**Comment by biotech7** [comment]
Hi, @arunppsg , i followed the instructions to install deepchem v2.6.0 dev ,[install latest deepchem](https://github.com/deepchem/deepchem). In all, just run this command if you use pytorch as backend `pip install --pre deepchem[torch]`

**Comment by biotech7** [comment]
i reproduced this error in Windows 10 as well as centos 7  with the same error. 
deepchem version:  v2.6.0 dev

**Comment by biotech7** [comment]
as  for misunderstanding of pytorch-dependant module , this is an normal error because i use pytorch as backend while GraphConvModel is a tensorflow-dependant module. so calling GraphConvModel will  conflict with my backend env. resulting in raising exception.

**Comment by Dreampop0215** [comment]
Is that means we can't use torch as backend?
