### ISSUE TITLE
FeaturizationTransformer failed with RDKit mismatched C++ signature

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2693]
## ❓ Questions & Help
when transformering dataset with FeaturizationTransformer, it failed with mismatched C++ signature in RDKit while using
NormalizationTransformer can pass through transformering.
I tried on Win10 and Centos 7, all with the same result.

deepchem version: 2.6.0 dev
rdkit version:  2021.03.5
```
import deepchem as dc
import numpy as np

np.random.seed(1234)

featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True)
loader = dc.data.CSVLoader(tasks=['target'], feature_field="smile", featurizer=featurizer)
dataset = loader.create_dataset(['./data/clearance.csv'])

transformer = dc.trans.FeaturizationTransformer(dataset, dc.feat.MolGraphConvFeaturizer())
dataset = transformer.transform(dataset)


Failed to featurize datapoint 0, <deepchem.feat.graph_data.GraphData object at 0x000001D4522B9488>. Appending empty array
Exception message: Python argument types in
    MolChemicalFeatureFactory.GetNumMolFeatures(MolChemicalFeatureFactory, GraphData)
did not match C++ signature:
    GetNumMolFeatures(class RDKit::MolChemicalFeatureFactory, class RDKit::ROMol mol, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > includeOnly='')
Failed to featurize datapoint 1, <deepchem.feat.graph_data.GraphData object at 0x000001D4522B9A88>. Appending empty array
。
。
。
```

can someone help me figure out this issue? i have been trapped in this for a few days.

**Comment by rbharath** [comment]
The issue here is you're double featurizing I believe. Check out the usage example for `FeaturizationTransformer`: https://deepchem.readthedocs.io/en/latest/api_reference/transformers.html#featurizationtransformer

The input needs to be something the featurizer can process. You're featurizing with `MolGraphConvFeaturizer` then feeding that back into a `MolGraphConvFeaturizer` which doesn't quite make sense.

**Comment by biotech7** [comment]
@rbharath solved my doubts. It's quite helpful.
