### ISSUE TITLE
Making DeepChem Layers Multibackend

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2697]
Here's a current list of DeepChem layers and the backends for which they are available

| Layer Name | TensorFlow | Torch | Jax |
|---|---|---|---|
|InteratomicL2Distances|X|-|-|
|GraphConv|X|-|-|
|GraphPool|X|-|-|
|GraphGather|X|-|-|
|MolGANConvolutionalLayer|X|-|-|
|MolGANAggregationLayer|X|-|-|
|MolGANMultiConvolutionLayer|X|-|-|
|MollGANEncoderLayer|X|-|-|
|LSTMStep|X|-|-|
|AttnLSTMEmbedding|X|-|-|
|IterRefLSTMEmbedding|X|-|-|
|SwitchedDropout|X|-|-|
|WeightedLinearCombo|X|-|-|
|CombineMeanStd|X|-|-|
|Stack|X|-|-|
|Variable|X|-|-|
|VinaFreeEnergy|X|-|-|
|NeighborLlist|X|-|-|
|AtomicConvolution|X|-|-|
|AlphaShareLayer|X|-|-|
|SluiceLoss|X|-|-|
|BetaShare|X|-|-|
|ANIFeat|X|-|-|
|GraphEmbedPoolLayer|X|-|-|
|GraphCNN|X|-|-|
|Highway|X|-|-|
|WeaveLayer|X|-|-|
|WeaveGather|X|-|-|
|DTNNEmbedding|X|-|-|
|DTNNStep|X|-|-|
|DTNNGather|X|-|-|
|DAGLayer|X|-|-|
|DAGGather|X|-|-|
|MessagePassing|X|-|-|
|EdgeNetwork|X|-|-|
|GatedRecurrentUnit|X|-|-|
|SetGather|X|-|-|
|Stem|X|-|-|
|InceptionResnetA|X|-|-|
|InceptionResnetB|X|-|-|
|InceptionResnetC|X|-|-|
|ReductionA|X|-|-|
|ReductionB|X|-|-|
|ScaleNorm|-|X|-|
|MultiHeadedMATAttention|-|X|-|
|MATEncoderLayer|-|X|-|
|SublayerConnection|-|X|-|
|PositionwiseFeedForward|-|X|-|
|MATEmbedding|-|X|-|
|MATGenerator|-|X|-|
|Linear|-|-|X|

Our layers are a powerful library of differentiable primitives that we should be able to leverage to build more complex differentiable programs, but the fact that layers are currently poorly documented and not available on multiple backends limits their usability. I'm raising this issue to help brainstorm some ideas to make layers more useful.

**Comment by peastman** [comment]
This could ultimately play an important role:

https://data-apis.org/array-api/latest/

The developers of lots of Python libraries (NumPy, TensorFlow, PyTorch, JAX, Dask, etc.) are working together to create a common API so you can write code that works with all of them.  They're still working on the spec, so it won't be available in any of those packages for a while yet.  Eventually it should make this sort of thing much easier.

**Comment by rbharath** [comment]
A good intermediate step for us might be to just improve the documentation, tests, and usage examples on our existing layers. A lot of the layers are written primarily for internal use and don't have well documented APIs really.

**Comment by rbharath** [comment]
Closing since we have decided to standardize on PyTorch after PyTorch joined the linux foundation
