### ISSUE TITLE
which one is the preferred API service for deepchem TorchModel?

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2702]
## ❓ Questions & Help
I want to deploy  deepchem TorchModels on a server which can be queried by users .
there are many choices for deployment of torch models. e.g.  

- 1. apache+flask+wsgi+pytorch
- 2. springboot+pytorch
- 3. pytorch serve tools(https://github.com/pytorch/serve)
- 4. many third-party SDKs or libraries...

so what's the preferred strategy for serving a deepchem TorchModel ?

**Comment by rbharath** [comment]
I've done something very simple before which is just set up a flask server and answer queries directly but definitely not a sophisticated web setup. I'd be interested for us to set up a more documented pathway to set up a DeepChem API service.

@biotech7 Can you let us know what ends up working for you?

**Comment by biotech7** [comment]
As to the point of language environment，JAVA may be  one of the best candidates for erection of AI service. so JAVA-based service such as “Springboot+pytorch” could satisfy many demands in various industries. 
       to the point of deepchem, intergation of pytorch serve tools(https://github.com/pytorch/serve) into deepchem may be a good choice. but i cannot ,technically，figure out how to seamlessly complete this job. 
flash+apache+wsgi+pytorch is a webframe but not a lib. or a tool which is unreasonable to be merged into deepchem.
finally, i'll try to do a trial on webservice erection of  among  flash+apache+wsgi+pytorch , pytorch serve tools and JAVA+pytorch env. at my spare time .

**Comment by rbharath** [comment]
Closing this since there are no plans to specify a preferred API service for DeepChem
