### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run'

### ISSUE THREAD

**Issue by bilalzafarpak** [deepchem/deepchem#2723]
## 🐛 Bug

When i am training the model graphconv, here is an error occurred

code
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score, np.mean)
n_feat =75
batch_size =128
model = dc.models.GraphConvModel(
    len(delaney_tasks), batch_size = batch_size, mode = 'regression')
model.fit(train_dataset, nb_epoch=20)

print("Evaluating Model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)

print("Train Scores")
print(train_scores)

print("validation Scores")
print(valid_scores)

error
AttributeError: 'NoneType' object has no attribute 'run'

**Comment by rbharath** [comment]
Let me know if this is still an error. I tested `GraphConvModel` recently and it should work fine
