### ISSUE TITLE
Error running colab tutorial notebook(s) 

### ISSUE THREAD

**Issue by SciGuy1839** [deepchem/deepchem#2727]
## The_Basic_Tools_of_the_Deep_Life_Sciences Colab Notebook 🐛 Bug

Error when trying to run tutorial notebooks on google colab 

## To Reproduce

1. Run first cell in notebook

!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e

Error message 

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-1-402465323f4b> in <module>()
      1 get_ipython().system('curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py')
      2 import conda_installer
----> 3 conda_installer.install()
      4 get_ipython().system('/root/miniconda/bin/conda info -e')

/content/conda_installer.py in install(chunk_size, file_name, url_base, conda_path, add_python_path, additional_channels, additional_packages)
    121       "--yes",
    122       "python=={}".format(python_version),
--> 123       *packages,
    124   ])
    125   logger.info("done")

/usr/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    361         if cmd is None:
    362             cmd = popenargs[0]
--> 363         raise CalledProcessError(retcode, cmd)
    364     return 0
    365 

CalledProcessError: Command '['/root/miniconda/bin/conda', 'install', '--yes', 'python==3.7.12', 'openmm', 'pdbfixer', 'rdkit=2020.09.02']' returned non-zero exit status 1.

2. Running notebook with suggested code below from (https://forum.deepchem.io/t/getting-deepchem-running-in-colab/81) executes and allows for second cell in notebook to be executed ([] !pip install --pre deepchem)

!wget -c https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
!chmod +x Anaconda3-2019.10-Linux-x86_64.sh
!bash ./Anaconda3-2019.10-Linux-x86_64.sh -b -f -p /usr/local
!conda install -y -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.3.0
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

3. Then third cell in notebook fails 

[] import deepchem as dc
dc.__version__

Error: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-42cd10cbd366> in <module>()
----> 1 import deepchem as dc
      2 dc.__version__

ModuleNotFoundError: No module named 'deepchem'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

## Environment

* OS: google colab
* Python version: 3.7.12
* Conda version (error 2): 4.7.12
* DeepChem version: 2.3.0

**Comment by arunppsg** [comment]
Hey, colab notebooks have been updated with new installation procedures. Hence, closing this issue. Let us know if it is to be reopened. Thanks!
