### ISSUE TITLE
Generative models

### ISSUE THREAD

**Issue by PARODBE** [deepchem/deepchem#2736]
## ❓ Questions & Help

Hi, what is the difference between GAN.py and molgan.py??? By the way, are there any method to apply conditional VAE and GAN, controlling the Molecular weight, Log P...basically the features following the lipinski rules. Thanks!

**Comment by rbharath** [comment]
The GAN is a generic GAN superclass while the molgan is an architecture for generating molecules. I don't know of a good way offhand to control molecular weight etc for MolGAN, but that would be an excellent contribution for someone to make!
