### ISSUE TITLE
Error in intializing VinaPoseGenerator

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#2737]
## To Reproduce

1. Install deepchem latest version in colab `pip install --pre deepchem`
2. Run the following code sample:
```
import deepchem as dc
vpg = dc.dock.VinaPoseGenerator()
```

The above raises a`SSLCertVerificationError` but it is expected to initialize `vpg`.

There are two points regarding this:
- The download location of autodock vina executables was updated from the side of Vina team. Previously, DeepChem referenced them from [here](http://vina.scripps.edu/download/autodock_vina_1_1_2_mac_64bit.tar.gz) but now it is referenced from [here](https://vina.scripps.edu/wp-content/uploads/sites/55/2020/12/autodock_vina_1_1_2_mac_64bit.tar.gz)
- There is some problem in the server side which is causing `SSLCertVerificationError`, probably an expired SSL Certificate.

Some possible fixes:
- Move the executables to DeepChem's infrastructure
- Upgrade to the latest version of Autodock vina - 1.2.2

**Comment by rbharath** [comment]
Thank you for the excellent write-up! I think the right fix is to upgrade autodock vina to 1.2.2. We should also consider upgrading to using the pypi python bindings for autodock vina directly (then we can just pip install vina and avoid having to wrangle executables ourselves! https://autodock-vina.readthedocs.io/en/latest/installation.html)
