### ISSUE TITLE
configuring pre-commit

### ISSUE THREAD

**Issue by ncfrey** [deepchem/deepchem#2743]
## 🚀 Feature

Setting up [pre-commit](https://pre-commit.com/) for DeepChem developers.

## Motivation

New DeepChem devs often run into formatting issues (mypy, yapf, flake8, etc.). `pre-commit` (or something else like it) allows a one-time configuration of pre-commit hooks that devs can use to automatically make sure their code complies with DeepChem's formatting standards.

**Comment by rbharath** [comment]
This would be amazing! Automatic formatting would remove one of the biggest barriers new devs face

**Comment by ARY2260** [comment]
> ## 🚀 Feature
> Setting up [pre-commit](https://pre-commit.com/) for DeepChem developers.
> 
> ## Motivation
> New DeepChem devs often run into formatting issues (mypy, yapf, flake8, etc.). `pre-commit` (or something else like it) allows a one-time configuration of pre-commit hooks that devs can use to automatically make sure their code complies with DeepChem's formatting standards.

Hello. Could you share more details on what formats are needed in the configuration if pre-commit is used?

**Comment by ncfrey** [comment]
The coding conventions for DeepChem that we'd want to include are here: https://github.com/deepchem/deepchem/blob/master/CONTRIBUTING.md#coding-conventions

**Comment by SauravMaheshkar** [comment]
@ncfrey can I work on this ?

**Comment by ncfrey** [comment]
> @ncfrey can I work on this ?

Absolutely, a contribution here would be very helpful! Feel free to tag me on a Work-in-Progress PR as you get started.

**Comment by SauravMaheshkar** [comment]
@ncfrey Sorry for the late response (got caught up in NeurIPS 😅). I've added references to why certain choices for pytest and specific releases were made in the PR. LMK how it looks.
