### ISSUE TITLE
Error loading tutorials

### ISSUE THREAD

**Issue by ConnorBarnhill** [deepchem/deepchem#2744]
## 🐛 Bug

Error loading tutorial The_Basic_Tools_of_the_Deep_Life_Sciences.ipynb

## To Reproduce

1. Go here: https://colab.research.google.com/github/deepchem/deepchem/blob/master/examples/tutorials/The_Basic_Tools_of_the_Deep_Life_Sciences.ipynb

![image](https://user-images.githubusercontent.com/7959016/140574928-986093d7-2d4e-4393-91ab-6507026fe6af.png)

**Comment by arunppsg** [comment]
Hey, thanks for letting us know. Will fix this shortly!
