### ISSUE TITLE
Is there a progress bar for DataLoader.create_dataset ?

### ISSUE THREAD

**Issue by mgarort** [deepchem/deepchem#2755]
## ❓ Questions & Help

Sometimes we need to create a large dataset, and featurization takes a long time. Therefore, `DataLoader.create_dataset` seems to hang for a long while. Is there a way to view the progress of the featurization process with a progress bar?

Thanks in advance.

**Comment by rbharath** [comment]
@mgarort Great question! There isn't a progress bar right now, but you can turn on logging and watch the logging statements (it will say something like X/Y compounds featurized so far or something at set intervasl)

**Comment by mgarort** [comment]
That makes sense, thanks!
