### ISSUE TITLE
PagtnModel not found

### ISSUE THREAD

**Issue by pjspol** [deepchem/deepchem#2758]
## 🐛 Bug

An AttributeError occurs when trying to import the PagtnModel both from dc.models and dc.models.torch_models.

## To Reproduce

After `!pip install rdkit-pypi` and `!pip install deepchem`

1. `!pip install dgl -f https://data.dgl.ai/wheels/repo.html`
2. `!pip install dgllife`
3. `import dgl`
4. `import dgllife`
5. `import deepchem as dc`
6. `model = dc.models.PagtnModel`
7. Or, instead of number 6 above, run `model = dc.models.torch_models.PagtnModel`

AttributeError: module 'deepchem.models.torch_models' has no attribute 'PagtnModel'

AttributeError: module 'deepchem.models' has no attribute 'PagtnModel'

## Expected behavior

PagtnModel should be found under one of the two models listed above, per the DeepChem docs.

**Comment by rbharath** [comment]
@VIGNESHinZONE Would you have any ideas about what's going on here?

**Comment by VIGNESHinZONE** [comment]
@rbharath Im able to reproduce the error but I'm not exactly sure what's causing this error. The more surprising thing is, the tests for Pagtn model are also passing https://github.com/deepchem/deepchem/runs/4226253335?check_suite_focus=true#step:12:102


Also, I was unable to import `from deepchem.feat import PagtnMolGraphFeaturizer`

**Comment by VIGNESHinZONE** [comment]
@pjspol could you check it now, Im able to import the models in google collab.

```
!pip install --pre deepchem[torch]

import deepchem as dc
from deepchem.models import PagtnModel
from deepchem.feat import PagtnMolGraphFeaturizer
```

cc: @rbharath

**Comment by pjspol** [comment]
@VIGNESHinZONE Something very similar happens when trying to use AdamW. I can make a separate bug report for that if you'd like; just let me know. Thank you for your help!

**Comment by VIGNESHinZONE** [comment]
@pjspol I'm sorry for the late reply.
yeah please do, it would be really nice if you make another issue.
 This issue can be closed.
