### ISSUE TITLE
Sparse_Matrix_OneHotFeaturizer

### ISSUE THREAD

**Issue by davidRFB** [deepchem/deepchem#2778]
## 🚀 Feature

This new class featurize custom strings into one hot vectors. However, the implementation of sparse matrix allows better memory management in case of large datasets. 

## Motivation
Some protein datasets that contains more than 500000 datapoints can not be easily transformed used the OneHotFeaturizer. There are some memory problems loading the whole dataset. Therefore, this sparse matrix representation will help in those cases.

**Comment by rbharath** [comment]
Closing since implemented by #2870
