### ISSUE TITLE
Consolidating deepchem installation using .yml files

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#2782]
Currently, there are multiple .yml files which are to be merged for DeepChem installation. They are also at two places - few in the [root](https://github.com/deepchem/deepchem/) directory and couple of others in [requirements](https://github.com/deepchem/deepchem/tree/master/requirements) directory. This is causing some confusion on which .yml files are used for setup and installation of dependencie in different environments.

Ideally, all installation .yml files should go into requirements directory. We should consolidate the required installation files and remove the redundant ones. Also, corresponding changes has to be made in installation of deepchem in github workflows and docs.

Listing the .yml files and their ideal use cases:

Common - These yml files should contain the libraries which DeepChem uses internally (like numpy, pandas etc). They should not contain the backend frameworks for deep learning. 
- [requirements/env_common.yml](https://github.com/deepchem/deepchem/blob/master/requirements/env_common.yml)
- [env.common.yml](https://github.com/deepchem/deepchem/blob/master/env.common.yml)

Test - the libraries here are installed only during testing purposes and they are not required otherwise (like end use).
- [env.test.yml](https://github.com/deepchem/deepchem/blob/master/env.test.yml)

The below three contain the installation procedure for backends in different backend environments.
Jax related:
- [requirements/jax/env_jax.cpu.yml](https://github.com/deepchem/deepchem/blob/master/requirements/jax/env_jax.cpu.yml)
- [requirements/jax/env_jax.gpu.yml](https://github.com/deepchem/deepchem/blob/master/requirements/jax/env_jax.gpu.yml)
- [requirements/jax/env_jax.yml](https://github.com/deepchem/deepchem/blob/master/requirements/jax/env_jax.yml) - probably this can be removed as it is similar to common .yml files.

Torch related - contains torch related dependencies:
- [requirements/torch/env_torch.cpu.yml](https://github.com/deepchem/deepchem/blob/master/requirements/torch/env_torch.cpu.yml)
- [requirements/torch/env_torch.gpu.yml](https://github.com/deepchem/deepchem/blob/master/requirements/torch/env_torch.gpu.yml)
- [requirements/torch/env_torch.yml](https://github.com/deepchem/deepchem/blob/master/requirements/torch/env_torch.yml)  - probably this can be removed as it is similar to common .yml files.

Tensorflow related:
- [requirements/tensorflow/env_tensorflow.yml](https://github.com/deepchem/deepchem/blob/master/requirements/tensorflow/env_tensorflow.yml) - This should be updated to include tensorflow related dependencies and remove libraries which are part of common .yml files.

Core - with the use of seperate torch, tensorflow and jax installation procedures, I think these files are not required:
- [env.cpu.mac.yml](https://github.com/deepchem/deepchem/blob/master/env.cpu.mac.yml)
- [env.cpu.yml](https://github.com/deepchem/deepchem/blob/master/env.cpu.yml)
- [env.gpu.yml](https://github.com/deepchem/deepchem/blob/master/env.gpu.yml)

Feel free to chip in your ideas. Thanks!

CC @rbharath

**Comment by arunppsg** [comment]
Also some questions which I have in this regard are:

- Do we really need seperate .yml files for different environment? - less files, low maintenance overhead.
- Maybe we should add installation procedure with respect to end use like material science/molecular ML etc rather than based on backend. This will be ideal in long term prospects.

**Comment by rbharath** [comment]
I'd be happy for us to simplify the set of .yml files we need! I think we should probably maintain the smallest number of yml files that is required to run our build/test processes

**Comment by arunppsg** [comment]
Let's say, we have one yml for common dependencies, one for test dependencies and then each one for ubuntu, macos, windows for cpu and gpu backends respectively, we will have 8 installation files. We will be removing installation by backend (the tensorflow, torch and jax ymls) and make it to installation by OS type. Will it be good?

**Comment by SauravMaheshkar** [comment]
Maybe this is also worth looking into as `pre-commit` hook.

```YAML
-   repo: https://github.com/MarcoGorelli/madforhooks
    rev: 0.2.1
    hooks:
    -   id: conda-env-sorter
```
---
> [Source](https://github.com/MarcoGorelli/madforhooks): MarcoGorelli/madforhooks
