### ISSUE TITLE
Approximately what % of the codebase is molecule-based, vs. crystal structure or composition (i.e. chemical formula)

### ISSUE THREAD

**Issue by sgbaird** [deepchem/deepchem#2787]
## ❓ Questions & Help

From what I can tell, it seems mostly to be based on molecules. There is some mention of [facilities for crystal structure](https://github.com/deepchem/deepchem/issues/2005). What about composition (i.e. fractional prevalence of atoms or chemical formulas)?

I'm OK with very rough estimates.

**Comment by peastman** [comment]
I don't think you can really analyze the whole codebase in those terms.  A lot of it isn't specific to any application.  A GCN is a GCN whether you apply it to molecules, crystals, or social networks.  Most of the models aren't application specific.  Same with metrics, as well as a lot of the splitters and transformers.

One area of the code that is mostly application specific is the featurizers.  Take a look at https://deepchem.readthedocs.io/en/latest/api_reference/featurizers.html.  It lists all of them, organized by what type of data each is designed to work with.

**Comment by sgbaird** [comment]
@peastman that's a good point about GCNs being non-application-specific. The list of featurizers you included helps a lot for me to see what's already built-in/compatible. Thank you!
