### ISSUE TITLE
I came across this problem with my dataset

### ISSUE THREAD

**Issue by kurapikult** [deepchem/deepchem#2792]
I am trying to transform my data, however, I came across this problem:

Is it a problem with my dataset, or am I not using the right transformer?
![Screenshot (75)](https://user-images.githubusercontent.com/92780129/146145462-89edf3d9-51ac-4f9a-b348-e08b5041864b.png)

Note: I am very new at using Python and machine learning, so I am quite unsure how to solve this. I have also attached my dataset for reference. 
[EBNA1_dataset_csv.csv](https://github.com/deepchem/deepchem/files/7717397/EBNA1_dataset_csv.csv)

**Comment by MariBerry** [comment]
You use a single transformer object, why do you iterate over it? Just run line 6 of your code without _for_ loop.

**Comment by kurapikult** [comment]
> You use a single transformer object, why do you iterate over it? Just run line 6 of your code without _for_ loop.

Hello, thank you for replying and I did as you suggested. But at the end, the same problem occurred again, the transformer somehow needs to iterate over the object (?).
![Screenshot (77)](https://user-images.githubusercontent.com/92780129/146306637-0e5882fa-18d9-4b08-9ea3-5106ea6a55b8.png)
![Screenshot (76)](https://user-images.githubusercontent.com/92780129/146306662-364afc17-5c39-47c1-b28b-d247edd39c29.png)

**Comment by MariBerry** [comment]
Try to create a list of transformers. That's the data type which should be passed to` evaluate() `, if read the documentation.
`transformers = [dc.trans.NormalizationTransfomer(dataset=dataset, tranform_y=True)]`
Note, you use `tranformers = (dc.trans.NormalizationTransfomer(dataset=dataset, tranform_y=True))`, which doesnt create list, nor tuple.
