### ISSUE TITLE
Eof error 

### ISSUE THREAD

**Issue by RaguramRamamoorthy** [deepchem/deepchem#2800]
## ❓ Questions & Help

"EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached"

I get this error when i try to load from molnet - tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()

**Comment by rbharath** [comment]
I tested this on colab just now and it should work correctly. Please re-open if you are still facing an issue
