### ISSUE TITLE
Import error: No module named 'numpy.typing'

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2808]
## 🐛 Bug

Import Error just happened today (yesterday works fine)

## To Reproduce

`!pip install --pre deepchem`

## Error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-624644e87df7> in <module>()
----> 1 import deepchem

2 frames
/usr/local/lib/python3.7/dist-packages/deepchem/data/datasets.py in <module>()
     16 
     17 import numpy as np
---> 18 from numpy.typing import ArrayLike
     19 import pandas as pd
     20 

ModuleNotFoundError: No module named 'numpy.typing'

I know it probably came from version conflicts, but I used `!pip install -U numpy` still not working. Thanks for any help!

**Comment by TKassis** [comment]
What did you end up doing?
