### ISSUE TITLE
Error with installing deepchem on google colab

### ISSUE THREAD

**Issue by kurapikult** [deepchem/deepchem#2809]
## 📚 Installation

Hello, I have been using google colab to run deepchem all this while and never came across any problems beforehand. However, today I was trying to run my cells again, and this error came up.

![Screenshot (7)](https://user-images.githubusercontent.com/92780129/148682645-bb8dfbbe-b857-4076-a4a1-e9aacc13f122.png)

I have tried to uninstall and install NumPy to the latest version several times, but whenever I check, it always showed version 1.19.5, instead of the newly installed version, 1.21.5. How can I overcome this problem?

![Screenshot (8)](https://user-images.githubusercontent.com/92780129/148682753-32be2ca6-2014-4ea1-b38c-8388aed33123.png)

## Checklist

- [ /] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [ /] I used Google Colab.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by arunppsg** [comment]
A quick fix for colab installation - replace `!pip install --pre deepchem` with

```
!pip install --upgrade numpy
!pip install --pre deepchem
```

**Comment by kurapikult** [comment]
I tried installing deepchem with conda install and pip install; both are not working.
