### ISSUE TITLE
Tutorials do not currently work when run in google colab - suspect package version issue

### ISSUE THREAD

**Issue by ellagale** [deepchem/deepchem#2810]
## 🐛 Bug

It seems that the tutorials are broken when you run them in google colab. Suspect a versioning issue.
This is the error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-42cd10cbd366> in <module>()
----> 1 import deepchem as dc
      2 dc.__version__

2 frames
/usr/local/lib/python3.7/dist-packages/deepchem/data/datasets.py in <module>()
     16 
     17 import numpy as np
---> 18 from numpy.typing import ArrayLike
     19 import pandas as pd
     20 

ModuleNotFoundError: No module named 'numpy.typing'

## To Reproduce

1. Tried running the deepchem/examples/tutorials/ in google colab. I ran this one: 01_The_Basic_Tools_of_the_Deep_Life_Sciences.ipynb which is the Molecular Fingerprints tutorial
2.First line of notebook:  `!pip install --pre deepchem` 
3. Second line of notebook: `import deepchem as dc`
dc.__version__
3. Get error due to python package (see above)
I also tried the introduction to moleculenet notebook. Same error. All tutorials are currently broken.

## Expected behavior
I expect to be able to run the colab notebooks.

## Environment

* OS: Online in google colab
* Python version:
* DeepChem version:
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

## Additional context

I expect that te tutorials would work

**Comment by rbharath** [comment]
We just pushed an upgrade to the latest numpy 1.22. Perhaps that's not supported on google colab yet, hmm. We will try to figure out what's going on here. Thanks for the bug report!

**Comment by greenaway0824** [comment]
I also had the same problem.
After spending some time on the internet, I found an answer.
Please start with the code below.
It seems that the first line of the code changes the version of Numpy.

%pip install -U numpy
!pip install --pre deepchem
import deepchem as dc
dc.__version__

**Comment by arunppsg** [comment]
Hey, can you check now and let us know whether it works in colab? You may be required to factory reset runtime and do `!pip install --pre deepchem`. We upgraded minimum numpy requirement version and we hope that it will fix the problem.

**Comment by kurapikult** [comment]
Hello, I have tried the solution, and it's broken again. It works yesterday, but today the error comes up again

**Comment by greenaway0824** [comment]
I just ran

> Hello, I have tried the solution, and it's broken again. It works yesterday, but today the error comes up again

I just ran Deepchem to check it out. An error message came up just like you said, but it works without any problem with 'RESTART RUNTIME.'
All you have to do is click the button 'RESTART RUNTIME' and re-run the code.

**Comment by arunppsg** [comment]
As @greenaway0824 said, restart run-time and it will work fine! Things will work smooth when numpy version is updated in colab by the colab team.

**Comment by kurapikult** [comment]
Hello again! I did ask you suggested and it still didn't work. Also, tried upgrading numpy, but whenever I import numpy, it shows an older version instead of the imported one. 

![Screenshot (20)](https://user-images.githubusercontent.com/92780129/150487153-0ddeefe2-8195-4f32-9da1-d6f472a8720d.png)

Is there any way to solve this?

**Comment by kurapikult** [comment]
I restarted the runtime, still unable to import deepchem

**Comment by arunppsg** [comment]
Try `Factory reset runtime` under `runtime` tab in colab. After this, install `deepchem`.

**Comment by kurapikult** [comment]
I have tried this, and it works. Thanks so much!

**Comment by arunppsg** [comment]
Closing this since resolved! Feel free to reopen if the issue persists. Thanks!
