### ISSUE TITLE
Increase atom neighbors in ConvMolFeaturizer

### ISSUE THREAD

**Issue by saharctech** [deepchem/deepchem#2811]
## ❓ Questions & Help

Dear Deepchem team,

I would like to use ConvMolFeaturizer for the PDBBIND dataset and I want the featurizer to consider more atom neighbors (default is 10 nearest neighbor atoms). How can I do that?

Thanks so much for your help in advance.

**Comment by rbharath** [comment]
You might want to try looking at a different graph conv. I think `Weave` allows you to look at all neighbors if desired
