### ISSUE TITLE
Graph Convolution Network performance plotting 

### ISSUE THREAD

**Issue by bilalzafarpak** [deepchem/deepchem#2831]
## 🚀 Feature

Hello dear!
Can you plot the training and testing score of Graph Convolution Network for regression problems. It will help me
Thank you,

**Comment by rbharath** [comment]
Yes, you can do this by passing in 
```
all_losses = []
model.fit(..., all_losses=all_losses)
plt.plot(np.range(len(all_losses)), all_losses)
```
