### ISSUE TITLE
New Numpy requirement is too strict

### ISSUE THREAD

**Issue by TKassis** [deepchem/deepchem#2832]
## 🚀 Feature

The numpy requirement >=1.21 is too strict and causes a lot of dependency issues with other packages.

## Motivation

I realize that numpy.typing was introduced in 1.20 and for some reason DeepChem is using it, but this renders DeepChem unusable in any kind of complex environment with multiple packages that still have strict requirements for numpy to be <1.20.

**Comment by rbharath** [comment]
deepchem 2.6.0+ no longer type checks with older versions of numpy since mypy type checks fail due to new numpy types. If you have to work in a legacy environment with requirements for numpy < 1.20, I'd recommend using deepchem 2.5.0 until you are able to upgrade your environment.

**Comment by peastman** [comment]
Also be aware that recent versions of PyTorch don't work with numpy < 1.20.
