### ISSUE TITLE
Error while predicting

### ISSUE THREAD

**Issue by kurapikult** [deepchem/deepchem#2835]
I ran the DAG model on Delaney, and it ran smoothly. But when I tried to predict the model, this error came up. Is there a solution to it?

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-14-f669e3005e62> in <module>()
----> 1 DAG_model.predict(DAG_dataset)

4 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57     ctx.ensure_initialized()
     58     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 59                                         inputs, attrs, num_outputs)
     60   except core._NotOkStatusException as e:
     61     if name is not None:

InvalidArgumentError:  slice index 53 of dimension 1 out of bounds.
	 [[node model/dag_layer/strided_slice_215
 (defined at /usr/local/lib/python3.7/dist-packages/deepchem/models/layers.py:3532)
]] [Op:__inference__compute_model_93893]

Errors may have originated from an input operation.
Input Source operations connected to node model/dag_layer/strided_slice_215:
In[0] inputs_1 (defined at /usr/local/lib/python3.7/dist-packages/deepchem/models/keras_model.py:649)	
In[1] model/dag_layer/strided_slice_215/stack:	
In[2] model/dag_layer/strided_slice_215/stack_1:	
In[3] model/dag_layer/strided_slice_215/stack_2:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>     "__main__", mod_spec)
>>> 
>>>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
>>>     app.start()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
>>>     self.io_loop.start()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
>>>     self._run_once()
>>> 
>>>   File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
>>>     handle._run()
>>> 
>>>   File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
>>>     handler_func(fileobj, events)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
>>>     self._handle_recv()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
>>>     self._run_callback(callback, msg)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
>>>     callback(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
>>>     return self.dispatch_shell(stream, msg)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
>>>     handler(stream, idents, msg)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
>>>     user_expressions, allow_stdin)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
>>>     interactivity=interactivity, compiler=compiler, result=result)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
>>>     if self.run_code(code, result):
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "<ipython-input-14-f669e3005e62>", line 1, in <module>
>>>     DAG_model.predict(DAG_dataset)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/deepchem/models/keras_model.py", line 828, in predict
>>>     output_types=output_types)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/deepchem/models/keras_model.py", line 733, in predict_on_generator
>>>     return self._predict(generator, transformers, outputs, False, output_types)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/deepchem/models/keras_model.py", line 649, in _predict
>>>     output_values = self._compute_model(inputs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/deepchem/models/keras_model.py", line 701, in _compute_model
>>>     return self.model(inputs, training=False)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 452, in call
>>>     inputs, training=training, mask=mask)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/deepchem/models/layers.py", line 3501, in call
>>>     for count in range(self.max_atoms):
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/deepchem/models/layers.py", line 3532, in call
>>>     target_index = tf.stack([tf.range(n_atoms), parents[:, count, 0]], axis=1)

**Comment by rbharath** [comment]
I am able to confirm that `DAGModel` is working correctly. Try this snippet:

```
max_atoms = max([mol.get_num_atoms() for mol in dataset.X])
transformer = DAGTransformer(max_atoms=max_atoms)
dataset = transformer.transform(dataset)

model = DAGModel(len(tasks),
                     max_atoms=max_atoms,
                     mode='classification',
                     learning_rate=0.001)

model.fit(dataset, nb_epoch=30)
# You want to change this to your inference dataset, but for simplicity, just predicting on train here
model.predict(dataset)
```
