### ISSUE TITLE
On argument types to deepchem layers

### ISSUE THREAD

**Issue by gusty1g** [deepchem/deepchem#2842]
DeepChem has pytorch, tensorflow and jax layers. Different layers use different array data types for computation (ex: pytorch - torch.Tensor, jax - jnp.ndarray).

A broad question here is what should be the input argument to `forward`/`call` methods of layers? We can either have it the input corresponding to layers backend (ex: torch.Tensor in case of pytorch) or we can have it more generally as `numpy.ndarray` for all kind of layers and internally convert it to a form corresponding to the backend.

Having it as numpy.ndarray as input data type has two advantages: the data objects represent data as numpy arrays and it can be uniform across layers, so users need not worry about data type will training models. But calling, say `torch.from_numpy()` for every forward call is going to be computationally expensive.

Another idea is to use a helper function which can convert the data type of data objects into the corresponding backends data type of the model/layers which is going to be used.

**Comment by peastman** [comment]
The goal of the [Python array API standard](https://data-apis.org/array-api/latest/) is to let you write a single piece of code that works with any of these types.  Numpy 1.22 added preliminary support for it.  PyTorch is currently working on adding support.  I'm not sure what the status of Jax support is.

Clearly we can't rely on it quite yet.  But hopefully we can soon write all our layers to use the standard API and have them automatically work with any type of input.

**Comment by rbharath** [comment]
Thinking about this, I propose for now we just standardize on all DeepChem layers using torch tensors. In the future torch tensors should eventually become compliant with the Python Array API standard so I think we should be reasonably future proof this way. (Jax tensors are another option, but I think Jax isn't stable on Windows yet and torch is more mature)

**Comment by peastman** [comment]
A corollary to that is that as far as possible, we should manipulate those tensors using the methods and arguments of the API standard.  PyTorch has been gradually tweaking its API to support the standard.  It isn't all the way there yet, but the closer we can get the code now, the less we'll have to change later.

**Comment by rbharath** [comment]
Closing since we've moved forward on standardizing around torch
