### ISSUE TITLE
Reorganising models section of DeepChem docs

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#2861]
Currently, models section of DeepChem docs is organized as keras model, torch model, sklearn model etc. It will be more useful if it is organized as molecular models, materials models etc. A good first step will be improving the model cheatsheet and categorizing DeepChem models into different groups.

CC @rbharath @peastman

**Comment by arunppsg** [comment]
Similar to this, can we also split the suite of datasets into molecule, materials and others?

**Comment by rbharath** [comment]
Organizing the dataset suite into molecules/materials/etc would be a great idea!

**Comment by j-frie** [comment]
I would like to start contributing to deepchem and improve the model cheatsheet as a first task.

Currently the table looks like this:
![image](https://user-images.githubusercontent.com/107413352/173820833-788837b7-cca3-4690-986a-e90b3ccc538c.png)

I would suggest to have separate tables for
- general models (CNN, GBDT, MultitaskClassifier, SeqToSeq, WGAN and others)
- molecule models (lots of models from AtomicConvModel to WeaveModel)
- material models (CGCNN, MEGNet, LCNN)

To make the table a bit smaller, I would move the information regarding transformations and fit_method (which are used for only very few models) into one column, but even then it will probably be too broad for the current page layout.

Should I also add information regarding the backend (Keras/torch) as an additional column?

**Comment by arunppsg** [comment]
Hey, thanks for your interest. We can create a new `model_cheatsheet.rst` file in `docs/source/api_reference`. I like the idea of having separate tables for general models, molecule models and materials models. Regarding columns, to start with, we can just have the ModelName with the reference paper as a link (if available) next to the name, type, acceptable featurizers, backend. Regarding input type, we are planning to unify input type across models. So we can skip it for now. The backend will column be superuseful to the users.
