### ISSUE TITLE
Making benchmark Numbers more reproducible

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#288]
CC @miaecle 

Currently, the benchmark performances vary by a few percentage points between runs. Some of this is natural, due to the random initializations of the matrices used in training, and in the random sampling of mini-batches. Here are a few potential solutions to make the benchmark runs more stable:

1. Set numpy random seed.
2. Set tensorflow random seed.
3. Repeat benchmark runs on datasets multiple times and return average.

Options 1. and 2. are easy to implement, but 3. will be inconvenient, especially for larger benchmarks like PCBA which take ~6hrs/run already.

**Comment by rbharath** [comment]
http://stackoverflow.com/questions/36288235/how-to-get-stable-results-with-tensorflow-setting-random-seed seems relevant. Apparently, tensorflow random seeds are graph-specific. Since `TensorflowGraphModel` creates its graphs internally, probably have to set seeds within class.

**Comment by miaecle** [comment]
I will try to implement and see if we can get it stabilized! So should we add a random seed line into each model script inside deepchem?

**Comment by rbharath** [comment]
@miaecle Thanks for offering! I think I already have a preliminary fix in #289. I will see if it stabilizes the benchmarks, and if so, will merge in PR in a day or two.

**Comment by miaecle** [comment]
@rbharath Oh I have not noticed that! That was very nice, thanks for your work! After this PR merged I will immediately start rebuilding the performances with fixed random seed.

**Comment by rbharath** [comment]
Closing this issue since I think most of these issues have been ironed out.
