### ISSUE TITLE
Neural Differential Equation API

### ISSUE THREAD

**Issue by shivance** [deepchem/deepchem#2882]
## 🚀 Feature

**Neural Differential equation** are a new variety of layers for neural networks , securing place in Deepchem Model <a href="https://github.com/deepchem/deepchem/issues/2680" >wishlist </a>. I hereby propose following API for the same 

torch_model (deepchem TorchModel API)
 
       |---------differential (api for neural differential equation ode, sde, cde)
                         |------- core  # contains ode blocks for ode, sde, cde
                         |------- odeint  # functional API for ode integration routines  eg. odeint, ode_adjoint, odeint_syplectic
                         |------- sensitivity
                         |------- solvers # will contain ode solvers
                         |------- interpolators # will contain several interpolation classes eg Linear, Fourth order.
                         |------- utils # utilities for ode methods

**Comment by shivance** [comment]
@rbharath I would request you to assign me this issue.

**Comment by rbharath** [comment]
Can you turn this into a more extended proposal and perhaps share on the forums or with me directly for feedback? I think adding improved support for Neural ODEs would be good but we will need to think carefully about the design. We can also discuss at the office hours
