### ISSUE TITLE
env_torch.gpu.yml requires conflicting versions (torch and torchvision 0.11)

### ISSUE THREAD

**Issue by Matthew-Hostetler** [deepchem/deepchem#2915]
## 🐛 Bug

env_torch.gpu.yml requires both torch and torchvision 0.11, resulting in error when installing:

```
The conflict is caused by:
    The user requested torch==1.11.0+cu113
    torchvision 0.11.0+cu113 depends on torch==1.10.0+cu113
```

## To Reproduce

Run `conda env update --file env_torch.gpu.yml`

```
The conflict is caused by:
    The user requested torch==1.11.0+cu113
    torchvision 0.11.0+cu113 depends on torch==1.10.0+cu113
```

Expect the versions to be compatible.

## Environment

* OS: Windows 11 (WSL2 Ubuntu)
* Python version: 3.8

**Comment by rbharath** [comment]
Thanks for bug-report and proposed PR! We will take a look and get back to you shortly
