### ISSUE TITLE
open in colab button does not work (Tutorial Part 13: Modeling Protein-Ligand Interactions)

### ISSUE THREAD

**Issue by juliaLopanskaia** [deepchem/deepchem#2966]
## 🐛 Bug
Notepad not found

when I try to go with a link (open in colab button) it says that the page is not found

**Comment by rbharath** [comment]
Which notebook is failing? It's probably that we forgot to update a link after renaming a notebook

**Comment by juliaLopanskaia** [comment]
If I go to the page https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Modeling_Protein_Ligand_Interactions.ipynb 
and click on "open in Colab" it searches for this page which it cannot find https://github.com/deepchem/deepchem/blob/master/examples/tutorials/13_Modeling_Protein_Ligand_Interactions.ipynb

**Comment by exnx** [comment]
same, the "open in Colab" link doesn't work for me either. However, when I just copy and paste the code cell by cell, it fails at the first one. Seems like the script to install conda breaks.

Code that breaks
```
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
```

Error received
```
CalledProcessError: Command '['/root/miniconda/bin/conda', 'install', '--yes', 'python==3.7.15', 'pdbfixer', 'openmm']' returned non-zero exit status 1.
```
