### ISSUE TITLE
yapf version error in pull request template 

### ISSUE THREAD

**Issue by ARY2260** [deepchem/deepchem#2969]
## PR template issue
There is a yapf version error in pull request template. There its mentioned as `Run yapf -i <modified file> and check no errors (yapf version must be 0.22.0)`, but based on the issue: https://github.com/deepchem/deepchem/issues/2869, the yapf version is changed to  version 0.32.0

**Comment by ARY2260** [comment]
@arunppsg

**Comment by arunppsg** [comment]
Thanks for letting us know. Update pull request template in #2954
