### ISSUE TITLE
AttributeError: module 'deepchem.models' has no attribute 'MultitaskClassifier' issue encountered.

### ISSUE THREAD

**Issue by J1NJ1NJ4R4** [deepchem/deepchem#2981]
## ❓ Questions & Help

AttributeError: module 'deepchem.models' has no attribute 'MultitaskClassifier' issue encountered.

I also installed deepchem and tensorflow, but the code does not work.

Please help me. 😭

deepchem version: 2.6.1
tensorflow version: 2.0.0

It's my code.

import numpy as np
import deepchem as dc

tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()
train_dataset, valid_dataset, test_dataset = tox21_datasets

model = dc.models.MultitaskClassifier(n_tasks = 12, n_features = 1024, layer_sizes = [1000])
model.fit(train_dataset, nb_epoch = 10)

metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)
train_scores = model.evaluate(train_dataset, [metric], transformers)
test_scores = model.evaluate(test_dataset, [metric], transformers)
print(train_scores)
print(test_scores)

**Comment by arunppsg** [comment]
Do you have tensorflow installed? MultitaskClassifier requires tensorflow backend.

**Comment by J1NJ1NJ4R4** [comment]
TensorFlow is already installed.

**Comment by J1NJ1NJ4R4** [comment]
Torch is also installed. 😭

**Comment by shivance** [comment]
@rbharath Yes ! MultitaskClassifier has been ported to PyTorch,, see [here](https://github.com/deepchem/deepchem/blob/master/deepchem/models/fcnet.py#L24-L184). However, the import of the model seems to be missing in module __init__.py

**Comment by shivance** [comment]
@J1NJ1NJ4R4 Can you check back once again ? The import seems to work fine.

**Comment by shivance** [comment]
@rbharath, I think we should move [fcnet.py](https://github.com/deepchem/deepchem/blob/master/deepchem/models/fcnet.py#L24-L184) to `torch_models` folder, as it has been ported to torch.

**Comment by osbm** [comment]
Well, I had this same error when I was trying to import `BasicMolGANModel`. I noticed, for some reason, that I wasn't able to install the latest version of the deepchem on python version `3.10`.  I lowered my python version to `3.9.13` using pyenv. and installed the latest versions of TensorFlow and deepchem. Then it worked. 

Still, your sample code still gives me the same error:
```
AttributeError: module 'deepchem.models' has no attribute 'MultitaskClassifier'
```
But I thought, I should share this, it may be somehow helpful to devs.

**Comment by shivance** [comment]
Hi, the import worked on downgrading because deepchem currently supports Python 3.7 through 3.9, See [this](https://github.com/deepchem/deepchem#requirements)

**Comment by shivance** [comment]
@J1NJ1NJ4R4 I think you should check your Python version as well.

**Comment by J1NJ1NJ4R4** [comment]
@shivance My Python version is 3.7.13.

**Comment by rbharath** [comment]
Going to close this old issue for cleanup. Please feel free to re-open if this is still an issue
