### ISSUE TITLE
Progressbar while training models?

### ISSUE THREAD

**Issue by shivance** [deepchem/deepchem#3010]
## ❓ Questions & Help

While we call `model.fit()` in deepchem models, it doesn't show any indicator which would tell us how many epochs (or %) training has been completed, unless until we are using tensorboard or wandb ?

**Comment by shivance** [comment]
The potential solution would be to wrap the looping of epoch in `tqdm` , in `default_generator` method of TorchModel and KerasModel

**Comment by peastman** [comment]
It used to print out regular progress messages, and the code is still there to do it.  It's just that we write them with `logger.info()`, and the default logging level ignores them.  We have an open issue to change that: #2023.
