### ISSUE TITLE
Why "USPTO_50k.csv" a little bit different from its original version

### ISSUE THREAD

**Issue by xuchunqiu** [deepchem/deepchem#3031]
- original version: 
 https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.6b00564/suppl_file/ci6b00564_si_002.zip (named `dataSetB.csv`)
- DeepChem version: 
 https://github.com/deepchem/deepchem/blob/6b52a15956c679c2e49099dcf817a3b98120e81f/deepchem/molnet/load_function/uspto_datasets.py#L26

I found there are two differents in the files above, while the comments in `./molnet/load_function/uspto_datasets.py` didn't help. So here is my question:

1. Original version has 50,000 data row while DeepChem version has 50,016 data row. Where does the extra data come from?
  ![image](https://user-images.githubusercontent.com/57806510/184265723-6c44f747-005e-402f-8608-69e979416b5a.png)

2. Original version has three reaction SMILES columns: `rxnSmiles_Mapping_NameRxn`, `rxnSmiles_Mapping_IndigoTK`, `rxnSmiles_IndigoAutoMapperKNIME` which represents the results of atom-mapping with three different methods. DeepChem version has only one reaction SMILES column and no atom-mapping inside. Which of the three columns does DeepChem version extract the reaction SMILES from?

**Comment by subzjee** [comment]
Regarding the second question: 
According to the docstring of `load_uspto()` in that file you linked, that dataset is the canonicalized dataset from [this paper](https://arxiv.org/pdf/2006.07038.pdf).
Details regarding reasoning can be found in appendix C.2 of that paper.

**Comment by xuchunqiu** [comment]
Oh, I'm so careless. Thank you for your reply.

**Comment by subzjee** [comment]
No problem at all, good luck!
