### ISSUE TITLE
JsonLoader is not rendered in the docs

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#3045]
The list of DataLoaders at https://deepchem.readthedocs.io/en/latest/api_reference/data.html#data-loaders doesn't include `JsonLoader` https://github.com/deepchem/deepchem/blob/master/deepchem/data/data_loader.py#L515. This should be added to the docs file

**Comment by girishsontakke** [comment]
Hi @rbharath, I guess the `JsonLoader` documentation is included [here](https://deepchem.readthedocs.io/en/latest/api_reference/data.html#jsonloader).

**Comment by rbharath** [comment]
Good catch @girishsontakke!
