### ISSUE TITLE
DMPNNFeaturizer not available 

### ISSUE THREAD

**Issue by venustheplanet** [deepchem/deepchem#3048]
## 🐛 Bug

Cannot import `DMPNNFeaturizer`

## To Reproduce

`!pip install --pre deepchem`
`import deepchem as dc`
`from deepchem.feat import DMPNNFeaturizer`

Error:
`ImportError: cannot import name 'DMPNNFeaturizer' from 'deepchem.feat'  (/usr/local/lib/python3.7/dist-packages/deepchem/feat/__init__.py)`

## Environment
Colab
Deepchem 2.6.1

**Comment by rbharath** [comment]
@ARY2260 Would you be able to take a look?

**Comment by ARY2260** [comment]
> @ARY2260 Would you be able to take a look?

Yes, I will look into it.

**Comment by ARY2260** [comment]
![image](https://user-images.githubusercontent.com/75680850/188149273-572f7dc5-8adc-4ed9-8098-c9dbdb324db4.png)
I am confused about the fact that even though the `circular_fingerprint.py` is updated, it is not registered by the interpreter.

**Comment by ARY2260** [comment]
![image](https://user-images.githubusercontent.com/75680850/188155321-1c60efe2-c090-48bd-bf22-263e5cdb9f76.png)

`!pip install --pre deepchem` is installing an older version of deepchem which does not have dmpnn featurizer

**Comment by ARY2260** [comment]
> `!pip install --pre deepchem` is installing an older version of deepchem which does not have dmpnn featurizer
Same is the case for `!pip install deepchem`

**Comment by ARY2260** [comment]
![image](https://user-images.githubusercontent.com/75680850/188149273-572f7dc5-8adc-4ed9-8098-c9dbdb324db4.png)
I tried git clone the master branch of the main deepchem repo, and I am confused about the fact that even though the `circular_fingerprint.py` is updated, it is not registered by the interpreter.

**Comment by ARY2260** [comment]
![image](https://user-images.githubusercontent.com/75680850/188166113-6a0764d9-3f25-4b1c-8786-be415fe892bd.png)
This is working fine.

**Comment by ismorphism** [comment]
They should upload the last version into pypi or conda channels then.

**Comment by rbharath** [comment]
Discussing with @ARY2260 offline, the bug is that we forgot to bump the dev version in https://github.com/deepchem/deepchem/blob/master/deepchem/__init__.py#L6. @ARY2260 said he will make a bugfix

**Comment by jwasswa2023** [comment]
Hello all, I am working with DMPNN in deepchem, but I am getting the same error. Was this issue solved?
