### ISSUE TITLE
Integrating graph features with other descriptors

### ISSUE THREAD

**Issue by Chopin2** [deepchem/deepchem#3049]
## ❓ Questions & Help

This may sound strange since I am not familiar with graph features, is it possible to integrate a graph feature with other features such as RD kit descriptors for training on DeepChem? I thought that graph features could be combined with other features to achieve higher accuracy.

**Comment by ARY2260** [comment]
Yes, it's possible to do the same. For example, in the [DMPNN encoder layer](https://github.com/deepchem/deepchem/blob/2b53dc69a93a655d97067ad31c6357129b957d45/deepchem/models/torch_models/layers.py#L1609-L1618) implementation, we concatenate graph features (after encoding) with global features (such as RD kit descriptors).

**Comment by Chopin2** [comment]
Thanks for your quick answer!  I will try it later.
