### ISSUE TITLE
[RFC] Long CI runs

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#3054]
DeepChem CI runs take a long time and it slows down developement time. One of the factors for long CI runs is running unit tests on multiple python versions - for example, unit test on torch CI runs on python 3.7, 3.8, 3.9.

Since unit tests runs same test on different environments, as long as it works in one version, it should also work in another version. I suggest we can run unit test on only one main version (say py 3.8). But we should run build tests on all versions.

**Comment by peastman** [comment]
Running tests on multiple versions is important, because changes to Python do sometimes break things.  But it's generally ok to test just two versions: the oldest and newest ones you want to support.  If it works on those, you can be pretty confident it will also work on versions between them.
