### ISSUE TITLE
Results.txt for grid_search returns train_score instead of validation_score

### ISSUE THREAD

**Issue by nagam11** [deepchem/deepchem#3064]
## 🐛 Bug
In line https://github.com/deepchem/deepchem/blob/66e3e74025f1e261a829db484c1ef42fb69cbcf1/deepchem/hyper/grid_search.py#L233 the logfile returns the train_score instead of the validation score. 

## To Reproduce

1. Use grid_search to find the best hyperparameters.

## Expected behavior

I think it should show: 
` f.write("Best validation score %s" % str(validation_score))`.

Ideally, both scores. 

## Environment

* OS: MacOS
* Python version: 3.9
* DeepChem version: 2.6.1

**Comment by arunppsg** [comment]
That's a nice catch! Will put up a PR shortly for fixing it.
