### ISSUE TITLE
examples/benchmark.py fails when split is None

### ISSUE THREAD

**Issue by ktaneishi** [deepchem/deepchem#307]
`examples/run_benchmark.py tox21 tf 1` causes the next error.

Traceback (most recent call last):
  File "examples/run_benchmark.py", line 113, in <module>
    verbosity='high', out_path=out_path)
  File "/home/tane/deepchem/examples/benchmark.py", line 121, in benchmark_loading_datasets
    f.write(dataset+','+split+',train,')
TypeError: Can't convert 'NoneType' object to str implicitly

I simply replaced split with str(split) and got successfully finished.

**Comment by miaecle** [comment]
@ktaneishi Thanks for pointing out the error and providing the solution! I have noticed this bug too, and change has been made in the recent PR #306

**Comment by ktaneishi** [comment]
@miaecle Thank you!  PR  #306 seems very nice changes. I'll try it.
