### ISSUE TITLE
MultiTaskClassifier is not working

### ISSUE THREAD

**Issue by andresilvapimentel** [deepchem/deepchem#3098]
## To Reproduce

The piece of code below in the tutorial Introduction_to_Model_Interpretability.ipynb is not working

n_tasks = len(tasks)
n_features = train_dataset.get_data_shape()[0]
model = dc.models.MultitaskClassifier(n_tasks, n_features)
model.fit(train_dataset, nb_epoch=50)

The error message is:  AttributeError: module 'deepchem.models' has no attribute 'MultitaskClassifier

## Environment

* OS: Windows
* Python version: 3.7.15
* DeepChem version: 2.6.2.dev
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information: on Google colab

**Comment by arunppsg** [comment]
MultitaksClassifier requires pytorch. Could you check whether you have it in your environment?

**Comment by andresilvapimentel** [comment]
Yes, it is.
I solved the issue installing the version 2.6.1, but there is an issue with the version 2.6.2.

**Comment by arunppsg** [comment]
I think the import fails when there is no torch-geometric package even though MultitaskClassifier does not depend on torch-geometric. I will able to reproduce it and I will put a fix soon.
