### ISSUE TITLE
Doc of Keras implementation of MPNN's referencing the correct paper?

### ISSUE THREAD

**Issue by rchen19** [deepchem/deepchem#3100]
## ❓ Questions & Help

Keras implementation of MPNN is referencing:

> Vinyals, Oriol, Samy Bengio, and Manjunath Kudlur. “Order matters: Sequence to sequence for sets.” arXiv preprint arXiv:1511.06391 (2015).

And the PyTorch version of MPNN is referencing:

> ustin Gilmer, Samuel S. Schoenholz, Patrick F. Riley, Oriol Vinyals, George E. Dahl. “Neural Message Passing for Quantum Chemistry.” ICML 2017.

The reference of the Keras version seems irrelevant to me, can someone confirm this is correct?

Many thanks.

**Comment by arunppsg** [comment]
The reference in Keras impl. is partially correct. The MPNN model uses a set2set layer for summing up the final node states and the reference Order matter ... is for the set2set layer. The MPNN model was introduced in Neural Message ... paper. We should update our reference in the docs.
