### ISSUE TITLE
New release with dependency on rdkit rather than rdkit-pypi

### ISSUE THREAD

**Issue by CompRhys** [deepchem/deepchem#3103]
## 📚 Installation

RDKit is now installed from the pypi repository `rdkit` as opposed to `rdkit-pypi`. The setup.py file here has been updated to reflect this but the package on pypi still depends on `rdkit-pypi`. This means that pip installing `deepchem` will now install `rdkit-pypi` alongside `rdkit` which leads to a namespace clash, ambiguity and potentially bugs.

## Environment

* OS: MacOS 12.4
* Package manager (PyPI or Conda): pypi
* Python version: 3.8.13
* DeepChem version: 2.6.1

**Comment by CompRhys** [comment]
https://pypi.org/project/rdkit-pypi/

**Comment by arunppsg** [comment]
We will make deepchem 2.7 release. That will fix update the package in pypi (#3099)

**Comment by CompRhys** [comment]
When will the release be made? There are still several things that are fixed in 2.7 that are really bad practice i.e. current version on pypi requires an internet connection to run as it downloads files due to using class calls as default arguments. Having to have an internet connection can pose a security risk for some users.
