### ISSUE TITLE
Sider Dataset

### ISSUE THREAD

**Issue by ph-mehdi** [deepchem/deepchem#3104]
## ❓ Questions & Help

[Here](https://github.com/deepchem/deepchem/tree/master/examples/sider) you use the sider dataset based on 27 organ system classes. I can't figure out how this dataset is created because [there ](http://sideeffects.embl.de/)is nothing like this to download. I need the same dataset based on High-Level Terms in MedDRA.
Can you guide me?
Thanks

**Comment by pmorerio** [comment]
Hi, I was exactly trying to figure out the same. 
More in detail, how are scores  aggregated into the 27 classes? 
@ph-mehdi have figured out anything useful?

**Comment by rbharath** [comment]
Sider is drawn from http://sideeffects.embl.de/

**Comment by pmorerio** [comment]
Hi @rbharath , that is exactly the link provided by @ph-mehdi, but they provide different kind of target scores (non-binary). How do you aggregate into binary?
