### ISSUE TITLE
Hyperlink for "datasets already available in MolNet" not working

### ISSUE THREAD

**Issue by ARY2260** [deepchem/deepchem#3117]
## 🐛 Bug

The link to information about already available datasets in [MoleculeNet documentation](https://deepchem.readthedocs.io/en/latest/api_reference/moleculenet.html) is not working correctly. It is redirecting to some random spam websites.

## To Reproduce

1. go to [MoleculeNet documentation](https://deepchem.readthedocs.io/en/latest/api_reference/moleculenet.html)
2. click _`datasets already available in MolNet`_

or direct  link: http://moleculenet.ai/datasets-1

**Comment by gusty1g** [comment]
The link should be updated to https://moleculenet.org/datasets-1
