### ISSUE TITLE
Docs failing issue

### ISSUE THREAD

**Issue by BalajiAI** [deepchem/deepchem#3139]
## 🐛 Bug

I've made changes to the docs folder but it doesn't reflects in the docs website. Here is my [change](https://github.com/deepchem/deepchem/pull/3110), but my changes doesn't get updated in the docs website.

It should be automatically updated right? Or someone needs to run anykind of script to update?
cc - @arunppsg

**Comment by arunppsg** [comment]
That's a nice catch. Our docs build are failing which should be fixed - some issue due to dependency management.

**Comment by BalajiAI** [comment]
This issue keep tracks of the Docs failing issue.

**Comment by gusty1g** [comment]
Fixed in #3317
