### ISSUE TITLE
Loading of top layer in pretrained model when bias is False

### ISSUE THREAD

**Issue by gusty1g** [deepchem/deepchem#3145]
When we are reloading model weights with `include_top=False` using `load_from_pretrained` method, if the top layer has bias set as False, weights for the below the top layer is not getting copied. Here is the code to reproduce:
```
import deepchem as dc

import torch
import torch.nn as nn

class Model(nn.Module):    
    def __init__(self):
        super(Model, self).__init__()
        self.dense = nn.Linear(in_features=8, out_features=2, bias=True)
        self.head = nn.Linear(in_features=2, out_features=1, bias=False)
        
    def forward(self, x):
        return self.head(self.dense(x)) 

pre = Model()
pre_dc = dc.models.TorchModel(pre, loss=dc.models.losses.L2Loss())
pre_dc.save_checkpoint()

fine = Model()
fine_dc = dc.models.TorchModel(fine, loss=dc.models.losses.L2Loss())

fine_dc.load_from_pretrained(pre_dc, include_top=False)

print (fine_dc.model.state_dict())
OrderedDict([('dense.weight',
              tensor([[-0.1105, -0.3411, -0.0083, -0.0793,  0.1559,  0.2183,  0.2238, -0.2569],
                      [ 0.2783, -0.2978,  0.0273, -0.0058, -0.2408, -0.1351,  0.0046, -0.3154]])),
             ('dense.bias', tensor([-0.0330, -0.0030])),
             ('head.weight', tensor([[-0.4924, -0.0605]]))])

print (pre_dc.model.state_dict())
OrderedDict([('dense.weight',
              tensor([[-0.1105, -0.3411, -0.0083, -0.0793,  0.1559,  0.2183,  0.2238, -0.2569],
                      [ 0.2783, -0.2978,  0.0273, -0.0058, -0.2408, -0.1351,  0.0046, -0.3154]])),
             ('dense.bias', tensor([-0.1272, -0.2554])),
             ('head.weight', tensor([[0.4836, 0.2152]]))])
```

Expected output: For the layer `dense.bias`, pre_dc model and fine_dc should have same weights. In source, 

https://github.com/deepchem/deepchem/blob/8f5267cdec58449dcd5972c3d531447d0c0900ff/deepchem/models/torch_models/torch_model.py#L1078-L1080

the above lines cause skipping of an additional layer when bias is False.

Some ideas:
- I think we should have an option to specify whether top layer has bias or not.
- Another option is to update our `load_from_pretrained` method to use model.state_dict() and match keys with an assignment map indicating layer names to load. Currently, assignment map is a dictionary of tensors with keys as tensors in source model, values as tensors in destination model (finetune model). The user has to specify assignment map. If the assignment map uses state_dict, users can avoid specifying top layers in the state_dict.

**Comment by rbharath** [comment]
I think this has been superseded by the new `ModularTorchModel` design. Going to go ahead and close. Feel free to re-open if this is still an issue
