### ISSUE TITLE
Need a procedure for creating disk datasets

### ISSUE THREAD

**Issue by joegomes** [deepchem/deepchem#315]
If DataLoader does not support it, not clear how to create a large, sharded disk dataset.

**Comment by rbharath** [comment]
I think I'll go ahead and refactor the `DiskDataset` and `DataLoader` objects some to address this and #314. There's a lot of cruft in there that has made it difficult to extend those classes.

**Comment by proteneer** [comment]
Support for persistence in a database would also be useful (especially for sharing data). pandas.Dataframe.to_sql does exist :)

**Comment by peastman** [comment]
In the mean time, could you post instructions on how to do it with the current API?  I'm waiting on that.

**Comment by rbharath** [comment]
@peastman, @joegomes : Here's the general procedure

- Create a data directory `data_dir`.
- Write shard `shard_num` to disk and get its metadata with  `metadata_row = DiskDataset.write_data_to_disk(data_dir, "shard-%d" % shard_num, tasks, X_shard, y_shard, w_shard, ids_shard)` to write the data for shard `shard_num` to disk.
- Construct a `DiskDataset` by calling `DiskDataset(data_dir=data_dir,                  metadata_rows=metadata_rows)`

I'll work on cleaning up `DataLoader` to see if I can make a more reasonable API, but this should hopefully get you going.

**Comment by rbharath** [comment]
@proteneer Contributions welcome! The `Dataset` class is abstract, and we currently have `NumpyDataset` and `DiskDataset` for an in-memory and disk (joblib based) implementations. A `SQLDataset` class could work as well.

**Comment by peastman** [comment]
I tried to follow your instructions, but it isn't working.  I called `write_data_to_disk()` for each shard, which created a set of files: `shard-#-ids.joblib`, `shard-#-X.joblib`, etc.  And then I created a DiskDataset, which wrote out one more file called `metadata.joblib`.

Now I try to load that dataset back in from a different script.  I construct a DiskDataset, passing it the directory name, and that seems to work.  But I then call `get_data_shape()` on it, and that fails with an exception:

```
  File "/home/peastman/workspace/deepchem/deepchem/data/datasets.py", line 509, in get_data_shape
    next(self.metadata_df.iterrows())[1]['X-transformed']))[0]
  File "/home/peastman/workspace/deepchem/deepchem/utils/save.py", line 108, in load_from_disk
    return joblib.load(filename)
  File "/home/peastman/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 443, in load
    with open(filename, 'rb') as file_handle:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/metadata-X-transformed.joblib'
```

**Comment by rbharath** [comment]
@peastman Would you mind posting your code? This looks like `metadata_rows` wasn't passed in to the `DiskDataset` constructor. I've updated the procedure above to hopefully make this a little clearer.

**Comment by peastman** [comment]
Here's the code:

```Python
metadata = []
for shard, files in enumerate(shardFiles):
    print('creating shard', shard)
    ids = np.array([f[:4] for f in files], dtype=np.object)
    x = []
    y = []
    for i, filename in enumerate(files):
        data = np.load(filename)
        x.append(data[:, :5])
        y.append(np.array(data[:, 5:], dtype=np.float))
    metadata.append(DiskDataset.write_data_to_disk('dataset', "shard-%d" % shard, None, X=x, y=y, ids=ids, compute_feature_statistics=False))
dataset = DiskDataset(data_dir='dataset', metadata_rows=metadata)
```

**Comment by rbharath** [comment]
@peastman Couple of minor bugs which may be causing issues

- `x` and `y` should be numpy arrays instead of lists
- Can you pass in `tasks` to `write_data_to_disk`? This can just be `np.arange(n_tasks)` where `n_tasks` is the number of tasks.
- I think we need to set the reload flag in the constructor `DiskDataset(data_dir='dataset', metadata_rows=metadata, reload=True)`

Could you give these a try and see if they solve the issue?

**Comment by peastman** [comment]
I tried all the things you suggested, but they don't help.

**Comment by peastman** [comment]
I don't see how it's supposed to work.  When you construct the DiskDataset object, that calls `self.save_to_disk()`, which simply calls

```Python
    save_to_disk(
self.metadata_df, self._get_metadata_filename())
```

So that's only going to write one file: "metadata.joblib".

**Comment by rbharath** [comment]
#317 should address this issue and make it straightforward (hopefully) to load arbitrary datasets.
