### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'pos'

### ISSUE THREAD

**Issue by ClinicalAI** [deepchem/deepchem#3168]
## To Reproduce
```

f = featurizer.featurize(["COc1ccc(Nc2nc(C#N)c(N)s2)cc1"])
data = f[0].to_pyg_graph()
```
## To Fix:
deepchem/feat/molecule_featurizers line 253 need to change to:
`z=np.asarray(pos)`

replace 'pos' with 'z' in this line and save the file.

## Environment

* OS: Linux 18
* Python version: 3.7
* DeepChem version: 2.7.1
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

**Comment by gusty1g** [comment]
I think this is similar to #3142 and it was fixed in #3097.
