### ISSUE TITLE
Making DataLoader Generic

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#318]
The `DataLoader` class currently only supports CSV and SDF files. Ideally, we should have a generic interface to `DataLoader` that lets users handle data of any type they like. However, it's not clear how to structure this sort of interface current. #317 (WIP) has made some progress by significantly simplifying the `DataLoader` class through removing the multiprocessing support that was cluttering up the codebase. 

The `DataLoader` implementation still assumes that all data going through the system is in dataframes. For CSV and SDF files, `dc.utils.save.load_csv_files` and `dc.utils.save.load_sdf_files` read in CSV and SDF files respectively and turn them into dataframes.

This dataframe assumption is unworkable for any data involving PDB files. Need to replace with a joint interface if possible. Any thoughts or feedback on generic loading much appreciated :)

CC: @joegomes @peastman

**Comment by rbharath** [comment]
Notes which may help design.

Types of featurization current handled by `DataLoader`:

- Featurization of SMILES strings in CSV files, loaded into SMILES strings in dataframes by `dc.utils.save.load_csv_files`
- Featurization of SDF structures, loaded into RDKit mols in dataframes by `dc.utils.save.load_sdf_files`

Types of featurization we would like to handle

- Featurization of PDB complexes. Each PDB lives in its own file on disk. User can specify a list of pdb files to be loaded. For complexes, maybe user specifies list of tuples, where each tuple holds files for that complex.

**Comment by rbharath** [comment]
Potential Design: Users provide a generator and a featurizer. The generator is responsible for generating objects which are understood by featurizer. These objects can be single molecules, or they can be arbitrary dataframes (needed by `UserDefinedFeaturizer` for efficiency), or lists of pdb files. Users can load arbitrary data by making generators and featurizers suited to their data source.

@peastman Does this design sound sensible?

**Comment by peastman** [comment]
What exactly is meant by a "dataframe"?  That isn't a class, is it?

Anyway, I find it a bit confusing to frame this in terms of "data loaders" and "featurizers".  What we're really talking about is how to construct a DiskDataset.  That might involve loading data from some set of files, or it might be data that's generated directly in memory, such as from a simulation.  It might involve featurization, or the original data might already have exactly the features you want.

Any "data loader" is necessarily specific to whatever source it's loading from.  That can't be generic.  But once you write specialized code for loading data from some source, you need a generic mechanism for saving that data as a DiskDataset.

**Comment by rbharath** [comment]
@peastman Earlier versions of `DiskDataset` used to store everything as pickled pandas dataframes. Some of that code still exists in modified form today.

You raise a good point that the key issue is that we're missing a generic mechanism for constructing and saving a `DiskDataset`. Let me poke around with the code in #317 to see if I can come up with something reasonable.

**Comment by rbharath** [comment]
Here's the new proposed generic `DiskDataset` construction API in #317 

`DiskDatset(shard_generator, data_dir, tasks)`

where `shard_generator` is an iterator that returns the data `(X_shard, y_shard, w_shard, ids_shard)` for a single shard each time it is invoked. This allows users to create arbitrary `DiskDataset` objects if they can specify iterators.

**Comment by peastman** [comment]
That sounds really good.

**Comment by rbharath** [comment]
@peastman, @joegomes: The new `DiskDataset` api has been merged in with #317. It should now be straightforward to create `DiskDataset` objects for arbitrary data sources. Going to go ahead and close this issue.
