### ISSUE TITLE
Flake8 checks on deepchem/models directory

### ISSUE THREAD

**Issue by gusty1g** [deepchem/deepchem#3182]
I was having a look at `scripts/flake8_for_ci.sh` script which runs flake8 in CI. I noticed that the flake8 tests are currently not run in `deepchem/models` directory. We should add `deepchem/models` to the list of items in `scripts/flake8_for_ci.sh`.

Subsequently, we should also fix the breakages caused by adding flake8 checks for `deepchem/models` directory.

**Comment by kid-116** [comment]
Could I take up this issue?

**Comment by csking101** [comment]
Upon adding `deepchem/models` to the `scripts/flake8_for_ci.sh` there were many required changes generated. I have taken the text file output of the same (https://github.com/csking101/deepchem/blob/flake8_check/breakages.txt). Can I work on clearing the conflicts created in the files?

**Comment by gusty1g** [comment]
Pick one file, share here what file you are fixing, so that no two people work on the same file and make a pr with the fixed changes.
