### ISSUE TITLE
How to set  a seed for k_fold_split?

### ISSUE THREAD

**Issue by taikichi-pc** [deepchem/deepchem#3219]
## ❓ Questions & Help

Thank you for your deepchem lib. i  love this.

Like above, how do I set a seed for "k_fold_split" ? I found it as a argument in "train_valid_test_split" and so on.
```
splitter = dc.splits.RandomSplitter()
split_datas = splitter.k_fold_split(train_data, 5)
```
I look forward to your helpful reply. Thank you.

**Comment by gusty1g** [comment]
You can pass it as a kwarg `seed` which will then be passed to `split` method. (`k_fold_split` and `train_valid_test_split` internally calls `split` method which accepts an argument `seed` and other kwargs passed to the downstream methods)

https://github.com/deepchem/deepchem/blob/fe6dd43cc952d47b2c93bad65bf0e02fb7804b59/deepchem/splits/splitters.py#L226-L231

But we should make it explicit for `k_fold_split` to accept `seed` argument.
