### ISSUE TITLE
Error creating DiskDataset

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#322]
I'm trying to use the new API for creating a DiskDataset.  Since my dataset doesn't have weights, my shard iterator returns `None` for the `w` element.  I assume that's valid, since `None` is the default value for the corresponding argument to `write_data_to_disk()`.  And in fact it appears to work correctly.  It doesn't report any errors, and I can then create a new DiskDataset object by loading the data in.  But when I call `get_shape()` on that object, it throws an exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peastman/workspace/deepchem/deepchem/data/datasets.py", line 854, in get_shape
    for shard_num, (X, y, w, ids) in enumerate(self.itershards()):
  File "/home/peastman/workspace/deepchem/deepchem/data/datasets.py", line 511, in iterate
    os.path.join(dataset.data_dir, row['w'])))
  File "/home/peastman/workspace/deepchem/deepchem/utils/save.py", line 106, in load_from_disk
    return joblib.load(filename)
  File "/home/peastman/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 443, in load
    with open(filename, 'rb') as file_handle:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/shard-0-w.joblib'
```

**Comment by rbharath** [comment]
@peastman Good find. This is a bug. The issue is that `DiskDataset.itershards()` and `DiskDataset.get_shards()` should check if files for `w` (and `X`, `y`, `ids`) exist on disk, and return `None` if they don't. This should be relatively localized bugfix. Open to a PR for this, or will add it to my debugging queue.

**Comment by peastman** [comment]
With that change I get this error:

```
  File "/home/peastman/workspace/deepchem/deepchem/data/datasets.py", line 858, in get_shape
    w_shape += np.array(w.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
```

What should `get_shape()` be returning in this case?

**Comment by rbharath** [comment]
Good catch. I think `w_shape` should be set to `None` if `w is None` (with the same for `X, y, ids`). So `get_shape()` should return `(X_shape, y_shape, w_shape, ids_shape)` where some of these will be set to `None` if the corresponding data isn't present.

**Comment by peastman** [comment]
I also see that `itersamples()` won't work correctly in this case:

```Python
    def iterate(dataset):
        for (X_shard, y_shard, w_shard, ids_shard) in dataset.itershards():
            n_samples = X_shard.shape[0]
            for i in range(n_samples):
                yield (X_shard[i], y_shard[i], w_shard[i], ids_shard[i])
    return iterate(self)
```

Are you sure we want to support those fields being None?  It looks like there's a lot of code that assumes they won't be.

**Comment by rbharath** [comment]
Good point. `sparse_shuffle` and `select` also seem to require non-None values. In this case, I think an easier fix would be to change `itershards()` and `get_shards()` to return sensible defaults. I think we can assume that `X` is never missing (error in that case). If `w` is missing, return `np.ones(len(X), len(self.tasks))`. If `y` is missing, raise error. If `ids` is missing, raise error.

**Comment by peastman** [comment]
> If w is missing, return np.ones(len(X), len(self.tasks))

Would it be better to return `np.ones(y.shape)`?  Remembering that `self.tasks` is another optional field.

**Comment by rbharath** [comment]
Good call. Since we're mandating `y` missing to be an error, this is a safer definition.
