### ISSUE TITLE
CSVLoader or create_dataset impute NaN values with 0

### ISSUE THREAD

**Issue by soulios** [deepchem/deepchem#3223]
## 🐛 Bug

After creating a dataset with csv loader, the NaN values are imputed with 0. 
I attach a subset of my dataset.
[tox21_subset.csv](https://github.com/deepchem/deepchem/files/10578948/tox21_subset.csv)

## To Reproduce
You can run it on colab or jupyter.
```
#!pip install deepchem
import deepchem as dc
import os
import pandas as pd
# Load the input dataset and check how many NaNs per task
input_file = "tox21.csv"
tasks = ["NR-AR","NR-AR-LBD","NR-AhR","NR-Aromatase","NR-ER","NR-ER-LBD","NR-PPAR-gamma","SR-ARE","SR-ATAD5","SR-HSE","SR-MMP","SR-p53"]
df = pd.read_csv(input_file)
for task in tasks:
  print(df[task].isnull().sum())

# After loading it with csv loader
loader = dc.data.CSVLoader(tasks=tasks, feature_field="smiles", featurizer=dc.feat.CircularFingerprint(size=2048))
input_dataset = loader.create_dataset(input_file)
# make it a dataframe and check for NaNs
input_df = input_dataset.to_dataframe()
for i in range(1,len(tasks)+1):
  print(input_df[f'y{i}'].isnull().sum())
```
Output on the whole dataset.
`566
1073
1282
2010
1638
876
1381
1999
759
1364
2021
1057
0
0
0
0
0
0
0
0
0
0
0
0
`

## Expected behavior

Shouldn't it keep the NaNs or remove the row with the NaNs?

## Environment

* OS: Ubuntu 20.04.5 LTS (Focal Fossa)
* Python version: Python 3.8.10
* DeepChem version: DeepChem 2.7.1

**Comment by rbharath** [comment]
Those values with imputed `0` will also have their associated weights be set to `0`. This ensures these values don't have any downstream effect on results. The reason this is done is to prevent NaN propagation.

**Comment by soulios** [comment]
Ohh I see.Thanks for your help! May be a good idea to include in the documentation as well.  I guess that is the line that does that. 
```
        valid_inds = np.array(
            [1 if np.array(elt).size > 0 else 0 for elt in features],
            dtype=bool)
```
