### ISSUE TITLE
Add usage example documentation for splitters

### ISSUE THREAD

**Issue by gusty1g** [deepchem/deepchem#3230]
Many splitters in `dc.splitters` lack example documentation. We should add documentation to those to make splitters more useful.

**Comment by GreatRSingh** [comment]
I am working on it.

**Comment by GreatRSingh** [comment]
Can anyone suggest which dataset should i use to make examples for the molecular splitter functions.

**Comment by gusty1g** [comment]
You can use a random NumpyDataset, as in the [docs](https://deepchem.readthedocs.io/en/latest/api_reference/splitters.html#randomsplitter) of RandomSplitter. Maybe you can modify it to specific use cases because some cases require smiles strings and you need to choose X accordingly. I would suggest to add for one particular splitter, make a pull request, get a review and then continue working on it.
