### ISSUE TITLE
Installation error Deepchem

### ISSUE THREAD

**Issue by etiu** [deepchem/deepchem#3245]
## Checklist

- [x] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [ ] I used Google Colab.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

Hi I tried to follow the installations but I could not install deepchem. Please could you help me resolve this? I am attaching the following errors which I am finding in my terminal and my jupyter notebook.
I tried making a new environment to install deepchem as well but it seems it doesnt work. My terminal says I have successfully installed deepchem, but when I write import deepchem as dc on my jupyter notebook, it gives an error, I am attaching the photos here. Please could you help me? Thank you.
<img width="1414" alt="installation error2" src="https://user-images.githubusercontent.com/119134543/219716435-670bf364-ca09-414c-b2b5-f124fde0e9dc.png">
 <img width="576" alt="installation error1" src="https://user-images.githubusercontent.com/119134543/219716458-5fa2ae99-135e-4d72-9180-c0b3a578b29b.png">

**Comment by gusty1g** [comment]
It is something to do with tensorflow. Could you uninstall tensorflow and reinstall it?

**Comment by etiu** [comment]
Hi @gusty1g, I uninstalled and installed tensorflow again, but deepchem still does not run. This is the error I am seeing upon uninstalling and reinstalling tf and then importing deepchem as dc...
<img width="1266" alt="installation error3" src="https://user-images.githubusercontent.com/119134543/219875327-fcb2865f-4f79-4394-bd64-9794ac784a9e.png">

**Comment by etiu** [comment]
Update: I tried to install tensorflow following the instructions in https://github.com/mrdbourke/m1-machine-learning-test but I am getting this error on my jupyter notebook when I try to import tensorflow:
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by gusty1g** [comment]
Could you share what OS are you in? I would suggest create a fresh conda environment, install tensorflow and test it by running `import tensorflow as tf; print (tf.__version__)`.

**Comment by rbharath** [comment]
Going to close this issue for cleanup. Please feel free to re-open if you still have issues!
