### ISSUE TITLE
How will CI treat tests which require both torch and tensorflow?

### ISSUE THREAD

**Issue by riya-singh28** [deepchem/deepchem#3263]
## ❓ Questions & Help

I am working on porting EdgeNetwork Layer from Tensorflow to Pytorch and I was writing a test that checks if both the implementations are comparable, but CI runs either Tensorflow or Pytorch tests at one time. So how will CI treat tests which require both torch and TensorFlow?

**Comment by gusty1g** [comment]
We use pytest to mark tests in CI. If the test is marked as `torch`, it will run in torch CI. For a test running in torch CI, the environment will not have tensorflow as a dependency. So, it the test calls tensorflow, the test will fail. Similarly, a test marked as `tensorflow` will run in tensorflow CI and it will not have torch dependency.

An unit test should test only one functionality - a method or a class. A comparison between two techniques is not necessary.

**Comment by rbharath** [comment]
The answer landed at is to use .npy files to store expected output generated by the TensorFlow tests and checking the torch tests against that output
