### ISSUE TITLE
Samples in nci dataset exceed max_deg limit

### ISSUE THREAD

**Issue by miaecle** [deepchem/deepchem#328]
I was trying to implement graph convolution regression on nci dataset, but it seems that several compounds in the dataset have degs of 10, which exceed the limit of max_deg. 
example:
No. 1564, c1ccc(C[PH](c2ccccc2)(C23[Fe]456789%10(C%11=C4C5C6=C7%11)C(=C82)C9=C%103)C23[Fe]456789%10(C%11=C4C5C6=C7%11)C(=C82)C9=C%103)cc1 
I am still running the model after altering the max deg limit(but it seems there is no systematic way to do this), another possible solution is directly delete these outliers.
Also, the example above has several duplicates in the file, is this normal?

**Comment by rbharath** [comment]
@miaecle Good find here! I think we should remove duplicates from the file (usually a sign of misprocessed data), but I think we should allow for compounds with greater `max_deg` (the compound above seems to be organometallic, which is a large enough category that we should account for it). Does setting `max_deg=10` in the `GraphTopology` constructor work?

**Comment by miaecle** [comment]
@rbharath after modifying files below(mostly the value of max_deg, also the n_features per atom is increased to 75) I was able to run graph conv model on the ferrocene molecule, should we just add these modifications to the whole repository?
`dc.feat.graph_features`, `dc.feat.mol_graphs`, `graph_topology.py`, `keras_layers.py`

**Comment by rbharath** [comment]
@miaecle Yes, I think so. Would you mind verifying that the existing graph-convolution numbers don't change with the update?

**Comment by miaecle** [comment]
@rbharath I have been checking it recently. Classifications give approximately the same results. However, one thing is that graph conv models seem to have the same problem of instability as low data models(which is actually making sense since they are all keras based), the variation can go up to 0.05 (AUC) in classification, which is not significantly big, but much worse (in stability) than other tf-based models.

**Comment by rbharath** [comment]
@miaecle Going to close this since #336 fixes the issue with ferrocene and other NCI compounds.
