### ISSUE TITLE
About bbbp, an error of the loading

### ISSUE THREAD

**Issue by yxnyu** [deepchem/deepchem#3328]
## ❓ Questions & Help
Here is the code I just want to split the dataset.
import deepchem as dc
from sklearn.metrics import roc_auc_score

tasks, datasets, transformers = dc.molnet.load_bbbp(featurizer='ECFP')

I do not know why the error is appearing.

Here is the error：
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[40], line 4
      1 import deepchem as dc
      2 from sklearn.metrics import roc_auc_score
----> 4 tasks, datasets, transformers = dc.molnet.load_bbbp(featurizer='ECFP')

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\molnet\load_function\bbbp_datasets.py:84, in load_bbbp(featurizer, splitter, transformers, reload, data_dir, save_dir, **kwargs)
     34 """Load BBBP dataset
     35 
     36 The blood-brain barrier penetration (BBBP) dataset is designed for the
   (...)
     80    information and modeling 52.6 (2012): 1686-1697.
     81 """
     82 loader = _BBBPLoader(featurizer, splitter, transformers, BBBP_TASKS, data_dir,
     83                      save_dir, **kwargs)
---> 84 return loader.load_dataset('bbbp', reload)

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\molnet\load_function\molnet_loader.py:177, in _MolnetLoader.load_dataset(self, name, reload)
    174 # Create the dataset
    176 logger.info("About to featurize %s dataset." % name)
--> 177 dataset = self.create_dataset()
    179 # Split and transform the dataset.
    181 if self.splitter is None:

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\molnet\load_function\bbbp_datasets.py:22, in _BBBPLoader.create_dataset(self)
     19   dc.utils.data_utils.download_url(url=BBBP_URL, dest_dir=self.data_dir)
     20 loader = dc.data.CSVLoader(
     21     tasks=self.tasks, feature_field="smiles", featurizer=self.featurizer)
---> 22 return loader.create_dataset(dataset_file, shard_size=8192)

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\data\data_loader.py:227, in DataLoader.create_dataset(self, inputs, data_dir, shard_size)
    223     logger.info("TIMING: featurizing shard %d took %0.3f s" %
    224                 (shard_num, time2 - time1))
    225     yield X, y, w, ids
--> 227 return DiskDataset.create_dataset(shard_generator(), data_dir, self.tasks)

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\data\datasets.py:1266, in DiskDataset.create_dataset(shard_generator, data_dir, tasks)
   1264 metadata_rows = []
   1265 time1 = time.time()
-> 1266 for shard_num, (X, y, w, ids) in enumerate(shard_generator):
   1267   if shard_num == 0:
   1268     if tasks is None and y is not None:
   1269       # The line here assumes that y generated by shard_generator is a numpy array

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\data\data_loader.py:207, in DataLoader.create_dataset.<locals>.shard_generator()
    205 for shard_num, shard in enumerate(self._get_shards(inputs, shard_size)):
    206   time1 = time.time()
--> 207   X, valid_inds = self._featurize_shard(shard)
    208   ids = shard[self.id_field].values
    209   ids = ids[valid_inds]

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\data\data_loader.py:414, in CSVLoader._featurize_shard(self, shard)
    411 if self.featurizer is None:
    412   raise ValueError(
    413       "featurizer must be specified in constructor to featurizer data/")
--> 414 features = [elt for elt in self.featurizer(shard[self.feature_field])]
    415 valid_inds = np.array(
    416     [1 if np.array(elt).size > 0 else 0 for elt in features], dtype=bool)
    417 features = [
    418     elt for (is_valid, elt) in zip(valid_inds, features) if is_valid
    419 ]

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\feat\base_classes.py:70, in Featurizer.__call__(self, datapoints, **kwargs)
     60 def __call__(self, datapoints: Iterable[Any], **kwargs):
     61   """Calculate features for datapoints.
     62 
     63   `**kwargs` will get passed directly to `Featurizer.featurize`
   (...)
     68     Any blob of data you like. Subclasss should instantiate this.
     69   """
---> 70   return self.featurize(datapoints, **kwargs)

File C:\anaconda\envs\deeplearn\lib\site-packages\deepchem\feat\base_classes.py:323, in MolecularFeaturizer.featurize(self, datapoints, log_every_n, **kwargs)
    320     logger.warning("Exception message: {}".format(e))
    321     features.append(np.array([]))
--> 323 return np.asarray(features)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2050,) + inhomogeneous part.

**Comment by rbharath** [comment]
I just tried running this in Google colab and it's working for me. Can you try running in colab to see if that works for you?

**Comment by yxnyu** [comment]
Thanks, I do not know why this cannot used in my local machine. I also can do it in the colab
