### ISSUE TITLE
GridFeaturizer cation_pi and pi_stack features cause segfault

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#333]
Enabling the `cation_pi` and `pi_stack` features for `GridFeaturizer` causes seg-faults. Might be related to #329, #331 since it's likely an underlying `openbabel` issue, but will have to do some careful digging to understand the root cause of the error.

**Comment by lilleswing** [comment]
No more segfault without openbabel!  We can close this.

**Comment by evanfeinberg** [comment]
Awesome, thank you Karl for all of your efforts on this!
