### ISSUE TITLE
Add MoleculeNet Cheatsheet

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#3330]
We should have a MoleculeNet cheatsheet that provides a listing of all the available datasets in MoleculeNet like we have with the models cheatsheet

**Comment by JoseAntonioSiguenza** [comment]
This is how table will look like:


[moleculenet_datasets_desccription.csv](https://github.com/deepchem/deepchem/files/11312118/moleculenet_datasets_desccription.csv)
