### ISSUE TITLE
用着好好地一刷新kernel报错了？

### ISSUE THREAD

**Issue by xianyu-123** [deepchem/deepchem#3337]
## ❓ Questions & Help

昨天还使用给出的示例做单步查看，今天再用的时候便无法加载了？
/home/wanggj/.conda/envs/deepchem/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
WARNING:deepchem.models.torch_models:Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
WARNING:deepchem.models:Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/home/wanggj/.conda/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/__init__.py)
/home/wanggj/.conda/envs/deepchem/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")

**Comment by rbharath** [comment]
@xianyu-123 This looks like a cuda installation error perhaps.

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢

**Comment by rbharath** [comment]
I'm going to close this issue. Please feel free to reopen if you still have questions. (I'd also suggest posting in english if possible for ease of answering if possible)
