### ISSUE TITLE
Google Colab: DMPNN Bug

### ISSUE THREAD

**Issue by yxnyu** [deepchem/deepchem#3345]
I start a new google colab jupyter notebook：

```
pip install deepchem

import deepchem as dc
from deepchem.models import DMPNNModel

#### Load Tox21 dataset
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21(featurizer=dc.feat.DMPNNFeaturizer(features_generators=["rdkit_desc_normalized"]), splitter='scaffold')

train_dataset, valid_dataset, test_dataset = tox21_datasets
print('dataset is featurized')

#### Assess featurized data
print(len(train_dataset), len(valid_dataset), len(test_dataset))
print(train_dataset.X[:5])

#### Initialise the model
model = DMPNNModel(n_tasks=len(tox21_tasks), \
                   n_classes=2, \
                   mode='classification', \
                   batch_size=50, \
                   global_features_size=200)

#### Model training
print("Training model")
model.fit(train_dataset, nb_epoch=30)

#### Model evaluation
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)

print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)

print("Train scores: ", train_scores)
print("Validation scores: ", valid_scores)
```

#### WARNING:deepchem.models:Skipped loading some Jax models, missing a dependency. No module named 'haiku'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-7487ae091687>](https://localhost:8080/#) in <cell line: 2>()
      1 import deepchem as dc
----> 2 from deepchem.models import DMPNNModel
      3 
      4 # Load Tox21 dataset
      5 tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21(featurizer=dc.feat.DMPNNFeaturizer(features_generators=["rdkit_desc_normalized"]), splitter='scaffold')

ImportError: cannot import name 'DMPNNModel' from 'deepchem.models' (/usr/local/lib/python3.9/dist-packages/deepchem/models/__init__.py)

---------------------------------------------------------------------------
#### NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

#### "Open Examples" button below.
---------------------------------------------------------------------------

I am wondering how I can properly use the DMPNN？

**Comment by rbharath** [comment]
I believe you need to install torch_geometric on the colab instance

**Comment by rbharath** [comment]
Verified that the code snippet above runs correctly in colab with torch_geometric installed so going to go ahead and close the issue
