### ISSUE TITLE
PCBA raw dataset download

### ISSUE THREAD

**Issue by Data-reindeer** [deepchem/deepchem#3349]
## ❓ Questions & Help
Hi, 
I want to download the raw file of PCBA dataset containing SMILES strings rather than loaded from deepchem. But the URL for PCBA dataset does not work. [URL](https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/%s) Can you provide available URL for raw file download. That would be very helpful.

Reindeer

**Comment by chertianser** [comment]
Some datasets, including the PCBA dataset, are available in the main `deepchem` repository in the [datasets directory](https://github.com/deepchem/deepchem/tree/master/datasets).

**Comment by Data-reindeer** [comment]
Thanks for your reply. I have successfully download the PCBA dataset from the provided directory.
No more questions.
