### ISSUE TITLE
Running deepchem on GPU

### ISSUE THREAD

**Issue by SoodabehGhaffari** [deepchem/deepchem#3357]
## 📚 Installation
I installed tensorflow cuda version with pip by the command below:
pip install tensorflow==2.12.0 --no-cache-dir  

and then load modules below in my job script.

module load cudatoolkit/11.7
module load cudnn/cuda-11.x/8.2.0 

I expected to be able to use tensorflow GPU with the installation that I did above and with the loading of  the required modules, but when I ran hyperparameter optimization, it took me three days to run. 
Here are the first lines of log file. I appreciate it if you can help me to run deepchem on GPU.

2023-04-12 11:30:31.083238: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-12 11:30:37.861091: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/scratch/gpfs/sg6615/CONDA/envs/deepchem/lib/python3.11/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.1.0)/charset_normalizer (None) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

**Comment by GrayCyberWildman** [comment]
Are you using Windows? Tensorflow no longer supports GPU on Windows since 2.11, see:
https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0

**Comment by SoodabehGhaffari** [comment]
Thanks for the reply. No, I am using deepchem on linux ( on the university
high performance computing cluster), but the log file shows it doesn’t use
GPU. I appreciate it if you help to leverage GPU feature of deepchem.

Best Regards
Soodabeh

**Comment by SoodabehGhaffari** [comment]
Thanks for the reply. No, I am using deepchem on linux ( on the university
high performance computing cluster), but the log file shows it doesn’t use
GPU. I appreciate it if you help to leverage the GPU feature of deepchem.


Please see the log file below:

2023-04-19 11:42:24.525108: I
tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary
is optimized to use available CPU instructions in performance-critical
operations.

To enable the following instructions: AVX2 AVX512F FMA, in other
operations, rebuild TensorFlow with the appropriate compiler flags.

2023-04-19 11:42:25.631013: W
tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could
not find TensorRT

/scratch/gpfs/sg6615/CONDA/envs/deepchem/lib/python3.11/site-packages/requests/__init__.py:102:
RequestsDependencyWarning: urllib3 (1.26.8) or chardet
(5.1.0)/charset_normalizer (None) doesn't match a supported version!

  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({})
doesn't match a supported "


Soodabeh

**Comment by SoodabehGhaffari** [comment]
Please see the complete log file below:
There are two issues:
1. Using GPU
2. Internal failure

Any suggestions are greatly appreciated.

Best Regards
Soodabeh

2023-04-19 11:42:24.525108: I
tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary
is optimized to use available CPU instructions in performance-critical
operations.

To enable the following instructions: AVX2 AVX512F FMA, in other
operations, rebuild TensorFlow with the appropriate compiler flags.

2023-04-19 11:42:25.631013: W
tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could
not find TensorRT

/scratch/gpfs/sg6615/CONDA/envs/deepchem/lib/python3.11/site-packages/requests/__init__.py:102:
RequestsDependencyWarning: urllib3 (1.26.8) or chardet
(5.1.0)/charset_normalizer (None) doesn't match a supported version!

  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({})
doesn't match a supported "

2023-04-19 11:53:54.253776: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device
/job:localhost/replica:0/task:0/device:GPU:0 with 30924 MB memory:  ->
device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:18:00.0, compute
capability: 7.0

2023-04-19 11:54:02.464056: I
tensorflow/compiler/xla/service/service.cc:169] XLA service 0x62c60f50
initialized for platform CUDA (this does not guarantee that XLA will be
used). Devices:

2023-04-19 11:54:02.464124: I
tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device
(0): Tesla V100-PCIE-32GB, Compute Capability 7.0

2023-04-19 11:54:02.503281: I
tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling
MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to
enable.

2023-04-19 11:54:03.604709: E
tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded
runtime CuDNN library: 8.2.0 but source was compiled with: 8.6.0.  CuDNN
library needs to have matching major version and equal or higher minor
version. If using a binary install, upgrade your CuDNN library.  If
building from sources, make sure the library loaded at runtime is
compatible with the version specified during compile configuration.

2023-04-19 11:54:03.947996: E tensorflow/compiler/xla/status_macros.cc:57]
INTERNAL: RET_CHECK failure
(tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:618) dnn != nullptr

**Comment by SoodabehGhaffari** [comment]
There was an issue from our cluster.
