### ISSUE TITLE
Deepchem doesn't work on Python 3.6 due to Openbabel Conflict

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#338]
DeepChem currently doesn't install with Python 3.6 (now the default Anaconda 3 python version) due to a conflict over openbabel

```
(deepchem3) rbharath@tensorbr0:~$ conda install -c omnia openbabel=2.4.0
Fetching package metadata .........
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - openbabel 2.4.0*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jbesnard** [comment]
I have the same problem. And to ass to the issue, on windows x64: 

> Package missing in current win-64 channels

Using conda install -c omnia openbabel=2.4.0

**Comment by rbharath** [comment]
I believe the pip install only installs wrapper and not underlying babel install itself. You might try doing `conda install -c biopython openbabel`. This is an alternate conda channel that might work better than Omnia version.

**Comment by Lnaden** [comment]
None of the `omnia` packages are built against Python 3.6, only 2.7, 3.4 and 3.5. I'll raise an issue about it on the omnia-md/conda-recipes repo though and get the discussion going. Python 3.6 is only a month old though, so I don't have an idea on a timeline.

**Comment by rbharath** [comment]
@Lnaden Thanks! I think Python 3.6 is still somewhat alpha, but it's probably good to get the discussion going.

**Comment by rbharath** [comment]
We no longer depend on openbabel so going to go ahead and close this issue.
