### ISSUE TITLE
A descriptors list has been removed from RDKitDescriptors?

### ISSUE THREAD

**Issue by taidbui** [deepchem/deepchem#3396]
## ❓ Questions & Help

Hi, I tried to create a predictive model using RDKitDescriptors and need access to the descriptor names. It seems the featurizer.descriptors had been removed in the current version. Could we have it back?

Here is the example using rdkitdescriptors I extracted from https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Going_Deeper_on_Molecular_Featurizations.ipynb
```
rdkit_featurizer = dc.feat.RDKitDescriptors()
features = rdkit_featurizer(['CCC'])[0]
for feature, descriptor in zip(features[:10], rdkit_featurizer.descriptors):
    print(descriptor, feature)
```
The above code will throw an error `AttributeError: 'RDKitDescriptors' object has no attribute 'descriptors'`

**Comment by rbharath** [comment]
I'm not sure when this was removed. I'd be open to a PR to add it back in. We should document it as a public attribute and make it part of the supported API

**Comment by szaman19** [comment]
Late reply, but following up on this. I also ran into the same issue. Version `2.8.0` takes out the `descriptors` attribute. Rolling back to version `2.7.0` fixes the issue. 

Reference in code: https://github.com/deepchem/deepchem/blob/fb9fe9fac9fc002a62583b8c6019fad84638592b/deepchem/feat/molecule_featurizers/rdkit_descriptors.py#L87

**Comment by rbharath** [comment]
Yes, I think this was something that slipped through the review process. @szaman19 or @taidbui I would be open to a PR that fixes this. I will mark it as a bug open for contribution
