### ISSUE TITLE
wget downloaded same files duplicately

### ISSUE THREAD

**Issue by ktaneishi** [deepchem/deepchem#341]
In nosetests, wget downloaded same files duplicately like random_full_DNN.tar.gz.1.
I've appended `-c` option for wget command to confirm which files have already downloaded or not.

**Comment by rbharath** [comment]
@ktaneishi Good suggestion. PR welcome for this one, or I could potentially get to this in a week or too.

**Comment by ktaneishi** [comment]
@rbharath Thank you, I've created PR #344 for this issue.
