### ISSUE TITLE
add more flexibility for high order valences

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#342]
For some organometallics that have 6+ degrees, the following line breaks in graph_features.py:

```
one_of_k_encoding(atom.GetDegree(), [0, 1, 2, 3, 4, 5, 6])
```

It may be prudent to support possibly up to 10+ valences (though the obvious downside is that it's going to introduce additional sparsity into the one-hot representation).

**Comment by proteneer** [comment]
as an aside and somewhat relevant extension - it'll be convenient if there's an official way for us provide our own one-hot encoded binary vector for each atom.

**Comment by rbharath** [comment]
@miaecle I believe that your latest changes for NCI support will increase valences. Will we be able to handle decavalent compounds?

@proteneer Do you have sense for the highest valency compound that we might reasonably expect to see?

Interesting suggestion about user-defined binary encodings. Is the idea that the user might want to provide an initial embedding of atoms (potentially generated by a proprietary toolchain)?. `dc.feat.UserDefinedFeaturizer` provides analogous support for fully connected networks, so this isn't an unreasonable ask. Might be a little technically tricky to pull off though.

**Comment by proteneer** [comment]
we've seen 10+ degrees for highly coordinated systems

The custom binary encodings isn't even necessarily related to proprietary toolchains - it's more of a way to have a more flexible architecture for the initial embedding. So it's something similar in spirit to the UserDefinedFeaturizer, as you mentioned. I'd need to dig deeper into the convmol code to see how difficult it is technically for any arbitrary encoding.

**Comment by miaecle** [comment]
@rbharath , I have modified it to 10 because of the ferrocene molecule, and I guess it can go up to 12 at most. Also there seems no systematic way to modify it within each run, due to the change in `max_deg` and `n_features`

**Comment by rbharath** [comment]
@miaecle Let's just keep it at 10 for now then. If we come across a compound with higher valency, we can always bump it up later.

**Comment by rbharath** [comment]
@proteneer Recent fix #336 has made it so graph-conv models support up to decavalent compounds. I'm going to go ahead and close the issue. Thanks for the report!

@miaecle Thanks for getting the fix in quickly!
