### ISSUE TITLE
Redundant samples in nci dataset

### ISSUE THREAD

**Issue by miaecle** [deepchem/deepchem#346]
There are in total 1 million data points in the nci dataset file, but it seems that each compound has 30~50 duplicates in that. So actually the number of compounds is far less than 1 million, which turns out to be around 20,000 after eliminating identical ones.
This also explains why index and random splitting has much higher valid score than scaffold, it is just because same compounds exist both in train and valid groups.
After refining the dataset, both three splitting methods(vanilla multitask model) give similar results(R2) of: train 0.17, valid 0.05 after 20 epochs. The train score can increase significantly to 0.6 when going up to 300 epochs, but it does not make any differences on valid score. Preliminary graphconv regression figures are similar on valid. I guess this is maybe the intrinsic problem with the dataset, anyone has any idea about it?

**Comment by rbharath** [comment]
@miaecle Good find! This would certainly explain why our numbers were so artificially high.

I think we should replace the NCI numbers in the table with the new numbers, but let's leave the issue of fixing NCI for some other time so we can focus on the other benchmarking TODOs.

**Comment by rbharath** [comment]
I believe this issue was fixed by #347 so closing. Please re-open if necessary.
