### ISSUE TITLE
implement save for MultitaskGraphClassifier

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#349]
because re-running large amounts of training data is really not fun.

**Comment by gufodotto** [comment]
Second that.

**Comment by rbharath** [comment]
Thanks for reporting this. It's certainly on the TODO list. I hope to have something in a couple weeks.

**Comment by lilleswing** [comment]
I think we can close this in favor of save/load on the new TensorGraph models.

**Comment by rbharath** [comment]
Agreed. We still need good tutorial material for new graph conv models, but that's for a separate issue.
