### ISSUE TITLE
Do you already have a GraphConvRegressor?

### ISSUE THREAD

**Issue by gufodotto** [deepchem/deepchem#352]
Hi all, 

thanks for pushing ahead with this great framework, and apologies for using this venue to ask questions about usage and not to report issues. If that's unacceptable, please point me to the correct venue.

now, for my question: Just befor Xmas I updated and thought I had seen a GraphConv\<XYZ\>Regressor class and example, but can't find it any longer. Did I imagine that? The closest thing I can find is the *MultitaskGraphRegressor* used in **deepchem/examples/delaney/delaney_graph_conv.py** - but I don't think this uses the GraphConv paradigm.

Any hints? Thanks,

    Luca

**Comment by rbharath** [comment]
@gufodotto No worries. Traffic is low enough for now that usage questions are fine here for now.

`MultitaskGraphRegressor` is in fact the graph conv regressor you're looking for :). Try using `delaney_graph_conv.py` to get started with your use case.
