### ISSUE TITLE
Bump python <3.11 to <3.12

### ISSUE THREAD

**Issue by MischaPanch** [deepchem/deepchem#3566]
## 📚 Installation

Currently deepchem can't be installed on python3.11. Is this really needed, or just an omission? Would be great to bump the version, if there are no backwards compatibility issues (there shouldn't be, right?)

**Comment by rbharath** [comment]
There were previously some openmm install issues iirc on 3.11. This may have been fixed in the latest openmm release. We will take a look at and report back

**Comment by shreyasvinaya** [comment]
Hi @MischaPanch @j-adamczyk I am working on adding support to python 3.11, 
you can track the progress here: https://github.com/deepchem/deepchem/pull/3686

**Comment by shreyasvinaya** [comment]
@MischaPanch @j-adamczyk Deepchem now supports python 3.11
