### ISSUE TITLE
DeepChem Documentation Roadmap

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#366]
Now that parts of the deepchem API are starting to stabilize (see development roadmap #343), we need to start prioritizing documentation. We currently have auto-generated API documentation, but we don't have tutorials on how to do simple tasks with DeepChem. Here's a list of the types of docs I'm thinking:

1. CSV file loading tutorial: Show how to load and featurize dataset in a CSV file with DeepChem.
2. Dataset tutorial: Demonstrate how to work with `DiskDataset` and `NumpyDataset` in DeepChem.
3. Train/Valid/Test + Cross Validation Tutorial: Show how to split a dataset up into train/valid/test or k-fold splits. Give an overview of different types of `Splitter` objects.
4. Featurizer Tutorial: Walk through the available `Featurizer` classes and discuss how they work.
5. Classification Tutorial: Walk through the construction of a simple classifier. Show how to fit a model to a dataset, evaluate its performance with `Metric` objects on validation sets. Demonstrate how to make predictions on new compounds.
6. Regression Tutorial: Same, but for a regression dataset.
7. One-shot tutorial: Show how to train a one-shot dataset and use it to make predictions.
8. Docking tutorial: Walk users through using `dc.dock` to perform docking.
9. **Edit:** Standardizing docstrings: As @peastman points out in thread below, docstrings aren't present for every class. We should make sure that all public-facing functions and classes have useful docstrings (with examples if possible)

@miaecle, @joegomes, @peastman : Would you mind helping out with documentation writing? It would be great to get volunteers to help write subsections :-). All the documentation lives on github at https://github.com/deepchem/deepchem/tree/master/docs, so can be added via small pull requests as people find time to contribute.

Also, if there are any other suggestions for useful tutorials, please add on to this thread.

**Comment by rbharath** [comment]
Also, @prasadkawthekar, @evanfeinberg, @flee2, @bowenliu16 Would be great if you have time to help out as well :-)

**Comment by peastman** [comment]
The API documentation could also use a lot of work.  There are some classes that have almost no docstrings at all, such as https://github.com/deepchem/deepchem/blob/master/deepchem/models/tf_new_models/multitask_regressor.py.  And a lot of others do have docstrings, but they're so terse that unless you already understand what the class does and how to use it, they don't give you much help in figuring out.  For example https://github.com/deepchem/deepchem/blob/master/deepchem/models/multitask.py.

**Comment by rbharath** [comment]
Good point! Have added it to the list above.

**Comment by rbharath** [comment]
Closing this issue since a lot of the specifics are really out of date.
