### ISSUE TITLE
Same construction principle between MXMNetSphericalBasisLayer and SphericalBasisLayer

### ISSUE THREAD

**Issue by linjing-lab** [deepchem/deepchem#3672]
## ❓ Questions & Help

I found a dependency named sympy in deepchem, and was very interesting about how sympy contribute to the algorithm built in deepchem, so [MXMNetSphericalBasisLayer](https://github.com/deepchem/deepchem/blob/0e99a2088f55ee2a0bfc8d01a67e2830911a0501/deepchem/models/torch_models/layers.py#L5953C7-L5953C32) coming from *deepchem.models.torch_models.layers.py* and [SphericalBasisLayer](https://github.com/pyg-team/pytorch_geometric/blob/9f7e82442efb41687e60469f1e63b0efaa793165/torch_geometric/nn/models/dimenet.py#L74) coming from *torch_geometric.nn.models.dimenet.py* have the same contribution about *sympy.lambdify* with [real_sph_harm](https://github.com/pyg-team/pytorch_geometric/blob/9f7e82442efb41687e60469f1e63b0efaa793165/torch_geometric/nn/models/dimenet.py#L97).

I was wondering if the efficiency of MXMNetSphericalBasisLayer will be higher than that of SphericalBasisLayer, or if their efficiency is almost the same, though they applied the same lambda function [*sym.lambdify from torch_geometric/nn/models/dimenet.py#L105*](https://github.com/pyg-team/pytorch_geometric/blob/9f7e82442efb41687e60469f1e63b0efaa793165/torch_geometric/nn/models/dimenet.py#L105) and [*sym.lambdify from deepchem/models/torch_models/layers.py#L6010*](https://github.com/deepchem/deepchem/blob/0e99a2088f55ee2a0bfc8d01a67e2830911a0501/deepchem/models/torch_models/layers.py#L6010)

**Comment by rbharath** [comment]
@riya-singh28 Would you be able to take a look at this question? I think this was your code

**Comment by linjing-lab** [comment]
@rbharath Whatever you'd like to say, you did some prior knowledge to deepchem by taking the same models coming from torch_geometric, and so on.
