### ISSUE TITLE
Problem when importing deepchem

### ISSUE THREAD

**Issue by ryansamuel13** [deepchem/deepchem#3717]
## 📚 Installation

I have been using deepchem on google colabs for quite a while now with the same code chunk to initialize my  environment:

{!pip install --pre deepchem[tensorflow]

import deepchem as dc
dc.__version__

from rdkit import Chem

!pip install tensorflow
!pip install jedi
!pip install packaging
!git clone https://github.com/NVIDIA/apex
!cd /content/apex
!pip install -v --no-build-isolation --no-cache-dir /content/apex
!pip install transformers
!pip install simpletransformers
!pip install wandb
!pip install scikit-learn
!cd ..

import tensorflow as tf

import sys
!test -d bertviz_repo && echo "FYI: bertviz_repo directory already exists, to pull latest version uncomment this line: !rm -r bertviz_repo"
# !rm -r bertviz_repo # Uncomment if you need a clean pull from repo
!test -d bertviz_repo || git clone https://github.com/jessevig/bertviz bertviz_repo
if not 'bertviz_repo' in sys.path:
  sys.path += ['bertviz_repo']
!pip install regex

!git clone https://github.com/seyonechithrananda/bert-loves-chemistry.git}

But today when I tried to run this, deepchem appeared to install correctly but I get this error when I try to import deepchem:

ImportError                               Traceback (most recent call last)
[<ipython-input-9-89367030f4a1>](https://localhost:8080/#) in <cell line: 4>()
      2 get_ipython().system('pip install --pre deepchem[tensorflow]')
      3 
----> 4 import deepchem as dc
      5 dc.__version__
      6 

6 frames
[/usr/local/lib/python3.10/dist-packages/deepchem/utils/safeops_utils.py](https://localhost:8080/#) in <module>
      2 import torch
      3 from typing import Union, Optional, Tuple
----> 4 from deepchem.utils.dft_utils import ZType
      5 
      6 eps = 1e-12

ImportError: cannot import name 'ZType' from 'deepchem.utils.dft_utils' (/usr/local/lib/python3.10/dist-packages/deepchem/utils/dft_utils/__init__.py)

**Comment by naseehasalam** [comment]
Facing the same issue.

**Comment by GreatRSingh** [comment]
Sorry about that, I have put up a patch for it.
https://github.com/deepchem/deepchem/pull/3718
