### ISSUE TITLE
Remove compute_energy_metric from Metric class

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#373]
The `Metric` class currently has an option `compute_energy_metric`. I believe this can be removed from the class without harm and moved to user-space.

@joegomes Is this correct?

**Comment by joegomes** [comment]
@rbharath This could be removed but is actively being used by me.  I'll explain what it does and some ideas to replace it.

This is used in force field training.  The general idea is that there are two sets of tasks (energy and forces) that don't make sense to average together with `task_averager`.  This flag will trigger code to average and report the error on the atomic forces and return only the energy metric as if the model was single task.  The idea that certain tasks should be averaged together might be something to create a general implementation of.  My other thought was creating a `ForceFieldEvaluator` object that inherits from `Evaluator` and overrides `compute_model_performance` with a function suitable for force field opt tasks.  Thoughts?

**Comment by rbharath** [comment]
@joegomes Creating a `ForceFieldEvaluator` seems like a good strategy to me! This avoids cluttering up the main `Evaluator` while preserving the needed functionality.

**Comment by joegomes** [comment]
@rbharath Sounds good to me.  I can create a PR removing this and adding `ForceFieldEvaluator` early next week.

**Comment by rbharath** [comment]
This has been removed.
