### ISSUE TITLE
Error loading BBBP dataset

### ISSUE THREAD

**Issue by sajjadGG** [deepchem/deepchem#3739]
## 🐛 Bug

I am trying to load the BBBP dataset following the example in the documentation but I get an error when it want to put everything as numpy array

## To Reproduce

run the below script
```Python
import deepchem as dc
dc.molnet.load_bbbp(featurizer=dc.feat.MolGraphConvFeaturizer())
```

this will return the following error

```
    return self.featurize(datapoints, **kwargs)
  File "/lustre06/project/6006204/sajad47/HSCMP/.venv/lib/python3.9/site-packages/deepchem/feat/base_classes.py", line 323, in featurize
    return np.asarray(features)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2050,) + inhomogeneous part.
```

## Environment

my version of deepchem is 2.7.1
python 3.9.6

**Comment by GreatRSingh** [comment]
@sajjadGG I was able to successfully run it in colab.
python 3.10.12
deepchem 2.7.1

**Comment by shreyasvinaya** [comment]
@sajjadGG Could you please confirm if the issue was resolved, if it did, i will close the issue

**Comment by sajjadGG** [comment]
yeah it got resolved
