### ISSUE TITLE
How to load and train on a significantly large dataset? [question]

### ISSUE THREAD

**Issue by UnixJunkie** [deepchem/deepchem#3796]
## ❓ Questions & Help

Hello,

What is the recommended way to train a WeaveModel classifier on a large dataset (millions of molecules)?

Thanks a lot!
Francois.

**Comment by rbharath** [comment]
Most everything should work out of the box. We've run weave up to 100M+ molecules. You'll need a few tricks like making sure you're using diskdataset not numpydataset but I don't think there should be major issues

**Comment by UnixJunkie** [comment]
Ok, thanks.
