### ISSUE TITLE
deepchem import issue with haiku and jax

### ISSUE THREAD

**Issue by mihirdate** [deepchem/deepchem#3821]
## 📚 Installation

import deepchem as dc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/deepchem/__init__.py", line 10, in <module>
    import deepchem.hyper
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/deepchem/hyper/__init__.py", line 2, in <module>
    from deepchem.hyper.base_classes import HyperparamOpt
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/deepchem/hyper/base_classes.py", line 6, in <module>
    from deepchem.models import Model
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/deepchem/models/__init__.py", line 74, in <module>
    from deepchem.models.jax_models import JaxModel
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/deepchem/models/jax_models/__init__.py", line 2, in <module>
    from deepchem.models.jax_models.jax_model import JaxModel
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/deepchem/models/jax_models/jax_model.py", line 20, in <module>
    import haiku as hk
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/haiku/__init__.py", line 19, in <module>
    from haiku import data_structures
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/haiku/data_structures.py", line 18, in <module>
    from haiku._src.data_structures import to_haiku_dict
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/haiku/_src/data_structures.py", line 30, in <module>
    from haiku._src import utils
  File "/Users/mdate/anaconda3/envs/deepchem/lib/python3.8/site-packages/haiku/_src/utils.py", line 42, in <module>
    def auto_repr(cls: type[Any], *args, **kwargs) -> str:
TypeError: 'type' object is not subscriptable

## Environment

* OS: Mac Ventura 13.6.3
* Package manager (PyPI or Conda): Pip and Conda
* Python version: 3.8.18
* DeepChem version: 2.7.1
* TensorFlow version:2.13.0
* PyTorch version (optional): 
pytorch-lightning       2.1.4
torch                   2.2.0
torch_cluster           1.6.3
torch_geometric         2.4.0
torch_scatter           2.1.2
torch_sparse            0.6.18
torch_spline_conv       1.2.2
torchmetrics            1.3.0.post0

* CUDA/cuDNN version (optional): NaN
* Any other relevant information: 

## Checklist

- [x] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [ ] I used Google Colab.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by mihirdate** [comment]
pip list
Package                 Version
----------------------- -----------
absl-py                 2.1.0
aiohttp                 3.9.3
aiosignal               1.3.1
astunparse              1.6.3
async-timeout           4.0.3
attrs                   23.2.0
cached-property         1.5.2
cachetools              5.3.2
certifi                 2024.2.2
charset-normalizer      3.3.2
chex                    0.1.7
deepchem                2.7.1
dm-haiku                0.0.11
dm-tree                 0.1.8
etils                   1.3.0
filelock                3.13.1
flatbuffers             23.5.26
flax                    0.7.2
frozenlist              1.4.1
fsspec                  2024.2.0
gast                    0.4.0
google-auth             2.27.0
google-auth-oauthlib    1.0.0
google-pasta            0.2.0
grpcio                  1.60.1
h5py                    3.10.0
idna                    3.6
importlib-metadata      7.0.1
importlib-resources     6.1.1
jax                     0.4.13
jaxlib                  0.4.13
Jinja2                  3.1.3
jmp                     0.0.4
joblib                  1.3.2
keras                   2.13.1
libclang                16.0.6
lightning-utilities     0.10.1
Markdown                3.5.2
markdown-it-py          3.0.0
MarkupSafe              2.1.5
mdurl                   0.1.2
ml-dtypes               0.2.0
mpmath                  1.3.0
msgpack                 1.0.7
multidict               6.0.5
nest-asyncio            1.6.0
networkx                3.1
numpy                   1.24.3
oauthlib                3.2.2
opt-einsum              3.3.0
optax                   0.1.8
orbax-checkpoint        0.2.3
packaging               23.2
pandas                  2.0.3
pillow                  10.2.0
pip                     24.0
protobuf                4.25.2
psutil                  5.9.8
pyasn1                  0.5.1
pyasn1-modules          0.3.0
Pygments                2.17.2
pyparsing               3.1.1
python-dateutil         2.8.2
pytorch-lightning       2.1.4
pytz                    2024.1
PyYAML                  6.0.1
rdkit                   2023.9.4
requests                2.31.0
requests-oauthlib       1.3.1
rich                    13.7.0
rsa                     4.9
scikit-learn            1.3.2
scipy                   1.8.1
setuptools              69.0.3
six                     1.16.0
sympy                   1.12
tabulate                0.9.0
tensorboard             2.13.0
tensorboard-data-server 0.7.2
tensorflow              2.13.0
tensorflow-estimator    2.13.0
tensorflow-macos        2.13.0
tensorstore             0.1.45
termcolor               2.4.0
threadpoolctl           3.2.0
toolz                   0.12.1
torch                   2.2.0
torch_cluster           1.6.3
torch_geometric         2.4.0
torch_scatter           2.1.2
torch_sparse            0.6.18
torch_spline_conv       1.2.2
torchmetrics            1.3.0.post0
tqdm                    4.66.1
typing_extensions       4.9.0
tzdata                  2023.4
urllib3                 2.2.0
Werkzeug                3.0.1
wheel                   0.42.0
wrapt                   1.16.0
yarl                    1.9.4
zipp                    3.17.0

**Comment by shreyasvinaya** [comment]
Hi, 
Jax and haiku are not supported on python 3.8 by the developers, 
you can bump up your python version to python 3.9 or above and this issue should resolve itself
