### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by CompRhys** [deepchem/deepchem#3823]
Can we get a new release? the current release is over a year old and requires `scipy<1.9` which is becoming a compatibility issue as other packages bump minimum requirements.

**Comment by rbharath** [comment]
For now, please use the pre-release `pip install --pre deepchem`. It's stable to use in production.

I agree on pushing out a new release. We'll cut a 2.7.3 soon

**Comment by CompRhys** [comment]
Can I bump this? I don't see the need to wait for 2.7.3 to be cut before we get an official 2.7.2 release that we can include in deps files. Note that the max scipy pinning makes it necessary to use 2.7.2. Due to pypi only exposing a limited number of dev builds the dev build we pinned to back in Feb now gives "ERROR: No matching distribution found for deepchem==2.7.2.dev20240208164340" when we attempt to install with pip

**Comment by rbharath** [comment]
Ah, that's unfortunate with the pypi limitation. Yes, we will try to push this out as soon as we can.

@shreyasvinaya How is progress on the release notes? We could just release the cut on Wednesday and update the release notes later

**Comment by CompRhys** [comment]
thanks!
