### ISSUE TITLE
Error when importing deepchem on Colabs

### ISSUE THREAD

**Issue by ryansamuel13** [deepchem/deepchem#3873]
## 📚 Installation

I have been using deepchem on google colabs for quite a while now with the same code to install and import deepchem into my environment:

{!pip install --pre deepchem[tensorflow]

import deepchem as dc}

But today when I tried to run this, deepchem appeared to install correctly but I get this error when I try to import deepchem:

AttributeError                            Traceback (most recent call last)
[<ipython-input-6-036ea2520bbc>](https://localhost:8080/#) in <cell line: 2>()
      1 get_ipython().system('pip install --pre deepchem[tensorflow]')
----> 2 import deepchem as dc

8 frames
[/usr/local/lib/python3.10/site-packages/deepchem/feat/molecule_featurizers/rdkit_descriptors.py](https://localhost:8080/#) in _make_normalised_func_dict(self)
    214 
    215       # get required distribution_ from `scipy.stats` module.
--> 216       cont_distribution: rv_continuous = getattr(st, distribution_name)
    217 
    218       # cdf => cumulative density functions

AttributeError: module 'scipy.stats' has no attribute 'gilbrat'

## Environment

* OS:
* Package manager (PyPI or Conda):
* Python version:
* DeepChem version:
* TensorFlow version:
* PyTorch version (optional):
* CUDA/cuDNN version (optional):
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [x] I used Google Colab.
- [x] I do have multiple CUDA versions on my machine.

**Comment by shreyasvinaya** [comment]
Hi @ryansamuel13 could you please try again, I am unable to replicate the error on colab
