### ISSUE TITLE
Manually add install sklearn to README.md

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#389]
sklearn does not come installed by default in the non-root package of conda.  The reason we think it does is conda lazily creates a new python install after the first package is attempted to be installed.

**Attached is a bash script which reproduces the issue.**
[repro.txt](https://github.com/deepchem/deepchem/files/751877/repro.txt)
[repro_results.txt](https://github.com/deepchem/deepchem/files/751878/repro_results.txt)

Environment
Ubuntu 16.04.1
conda 4.3.8

**Comment by rbharath** [comment]
I think we talked about this offline and it turned out this was a conda env vs. raw anaconda issue. The conda-env instructions include sklearn, so we're probably good to close those. (@lilleswing please reopen if I'm wrong)
