### ISSUE TITLE
Shrink size of deepchem repo by removing large dataset files

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#391]
The deepchem repo is quite large. We may want to use `bfg` to remove from history some of our larger datasets after moving all datasets to S3 

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by mpharrigan** [comment]
note that this is generally a bad thing from a "git etiquette" perspective. make sure no one has any branches branched off of the history you will re-write

**Comment by rbharath** [comment]
@mpharrigan This is a good point.

 Erk, there's an ugly tradeoff here between keeping the source repo at hundreds of MB versus destroying the history. For now, maybe I'll just leave the repo alone to avoid creating complicated issues. If anyone has strong feelings, please chime in on this thread and I'll reopen the issue.

**Comment by mpharrigan** [comment]
If you know everyone who may have branched and can merge in their changes before cleaning the repo, it might be ok
