### ISSUE TITLE
Deepchem does not work with Numpy 1.25.2 (installed by default in Colab)

### ISSUE THREAD

**Issue by nikopavl4** [deepchem/deepchem#3920]
## 🐛 Bug

I am using Google Colab to run some simple experiments with Deepchem. The code is very simple:
```
mols = [Chem.MolFromSmiles(smiles) for smiles in df["smiles"]]
featurizer = dc.feat.MACCSKeysFingerprint()
featurized_molecules = featurizer.featurize(mols)
```
This code was running with just a deprecation warning under Numpy 1.23 installed:
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```
Now that Google Colab has officially updated to Numpy 1.25.2, the warning has become an error, thus the notebook crashes with the following error:
![image](https://github.com/deepchem/deepchem/assets/62307313/2fa18996-eb20-417b-bd81-bcd15f5a5564)

## To Reproduce

```
mols = [Chem.MolFromSmiles(smiles) for smiles in df["smiles"]]
featurizer = dc.feat.MACCSKeysFingerprint()
featurized_molecules = featurizer.featurize(mols)
```

## Environment

* OS: Google Colab
* Python version: 3.10.12
* DeepChem version: 2.7.1
* RDKit version (optional): 2023.9.5
* Numpy version: 1.25.2

**Comment by rbharath** [comment]
Ah, thank you for the note. This one is a little serious.

@shreyasvinaya @aaronrockmenezes Could you both take a look?

**Comment by shreyasvinaya** [comment]
@rbharath the code that is shared works on colab, we are presently using numpy 1.26, so 1.25 shouldn't cause any issues

@nikopavl4 could you please use the pre-release of deepchem, that will resolve all the issues, 
We are in the process of releasing deepchem version 2.8.0

**Comment by nikopavl4** [comment]
Hello. Using the **pre-release** of Deepchem actually resolved all the issues. Thank you very much for your instant support.
