### ISSUE TITLE
Local issue with GraphConvModel

### ISSUE THREAD

**Issue by P-Kelley** [deepchem/deepchem#3953]
https://github.com/deepchem/deepchem/blame/4464190d7e510505b6a0c9f06ec74adc80fcb5f9/deepchem/models/graph_models.py#L840C12-L840C12

I am getting an error from the GraphConvModel in line 840: BatchNormalization(fused=False) . ValueError: Unrecognized keyword arguments passed to BatchNormalization: {'fused': False}. I am not seeing the fused keyword referenced in the documentation for keras BatchNormalization. I know this model is working properly in the docs-build workflow so I am wondering what I am missing for my local implementation.

**Comment by P-Kelley** [comment]
I found the issue I was having. I was using a updated version of keras by mistake. deepchem currently uses keras 2 and is not compatible with 3.

**Comment by osangma** [comment]
which version usable ?

**Comment by osangma** [comment]
which version is usable?

**Comment by 17855461143** [comment]
How did you solve it, please
