### ISSUE TITLE
Fix Tox21 Benchmark Scores

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#397]
Logistic Regression and Multitask with Random Splitting are deterministic and getting different scores.

Logistic Regression

|Model  |New Train | New Test| Old Train    | Old Test|
|-------|-----------|----------|------------|---------|
|Logreg| 0.902       | 0.715       | 0.903         | 0.735     |
|TF        |0.844        | 0.795       | 0.856        | 0.783    |

Scaffold Splitter is currently non deterministic.  This causes TF/Scaffold to fail benchmarks in 2/11 cases.

[concat_results.txt](https://github.com/deepchem/deepchem/files/774834/concat_results.txt)

**Comment by lilleswing** [comment]
P.S. Graph Conv is also non deterministic but hasn't been worse than 99% of the benchmark percentage in 11 runs.

**Comment by rbharath** [comment]
@lilleswing Thanks for doing this analysis! This will be very useful for us. So, does it look like there's an issue with the Scaffold splitter returning different splits in different calls?

**Comment by proteneer** [comment]
https://github.com/deepchem/deepchem/blob/master/deepchem/splits/splitters.py#L391

Is non-deterministic when len(x[1]) is equivalent

**Comment by rbharath** [comment]
Good find. If we fix the non-determinism of scaffold splitter, would there still be breaking in Multitask and Logistic Regression?

**Comment by lilleswing** [comment]
@rbharath yes, the tests which always break are the (random splitter, tox21, logreg) and (random splitter, tox21, tf).  These results are deterministic and worse than .99 of the benchmarks in Readme.md.  I'm running ScaffoldSplitter again now that I changed it to be deterministic.

**Comment by lilleswing** [comment]
This can be closed
