### ISSUE TITLE
Phenotypic Cell Models wanted

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#407]
Pasting over a conversation in Gitter with @EricJohnMartin:

- EJM: I saw a presentation on deepchem at Stanford and I would like to try it, but my problem biological, not chemical. Does it only work with molecules? I saw it expects a smiles (or SDF) in the input. Can it be used for image recognition on small data sets? I want to use it to identify phenotypes from high-content imaging assays of cells. If not, can you recommend a similar framework for images? Thanks.
- BR: DeepChem doesn't support this yet, but I'd be very happy to go in this direction. A lot of drug discovery is moving towards phenotypic assays so well within our goals to democratize drug discovery. Do you have any datasets we could use as benchmark targets to develop a prototype here?
- EJM: Thank you for offering to look into image data. A collection of public image sets are at https://data.broadinstitute.org/bbbc/image_sets.html. As a benchmaark, a postdoc at one of our other sites has published his convolutional DNN models for several of these image sets in bioinformatics. Godinez Navarro, William Jose and Hossain, Imtiaz and Lazic, Stanley and Davies, John and Zhang, Xian (2017) A Multi-scale Convolutional Neural Network for Phenotyping High Content Cellular Images. Bioinformatics. ISSN 1367-4811; 1367-4803. Many thanks!
- EJM: The bioinformatics reference I mentioned used 5 specific assays from the Broad collection: BBBC013, BBBC014, BBBC015, BBBC016, and BBBC021. That paper also builds models for 2 data sets from Orlov, N. et al. WND-CHARM: Multi-purpose image classification using compound image transforms. Pattern Recognit. Lett. 29, 1684–1693 (2008), the WND-CHRM Hela and The WND-CHRM CHO sets available at https://ome.irp.nia.nih.gov/iicbu2008/ . Good luck!

PRs very welcome here!

**Comment by proteneer** [comment]
this is super cool! +1 on seeing more of these

**Comment by rbharath** [comment]
Closing this issue, since I think there are a couple other issues discussing adding support for microscopy datasets.
