### ISSUE TITLE
IJCNN-07 HIV Dataset & DHFR Dataset

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#413]
The IRV paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2750043/) is benchmarked on these two datasets. Would be great to add these to the dataset suite so we can add them to the benchmarks (very curious how graph convolutions perform against them for example).

CC @miaecle

**Comment by miaecle** [comment]
@rbharath I have found the HIV dataset, the webpage of DHFR dataset is no longer accessible. Planning to process and add in the HIV data tomorrow.

**Comment by rbharath** [comment]
Going to go ahead and close. Thanks for the effort here @miaecle!
