### ISSUE TITLE
Test Coverage for DeepChem

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#414]
While DeepChem has a decent test-suite, I suspect that our test coverage could be better. What are some standard tools for measuring test coverage and how could we incorporate them into DeepChem?

@lilleswing, @proteneer, @peastman Would love your thoughts here.

**Comment by peastman** [comment]
I haven't used it, but this seems to be the most widely used coverage tool for Python: https://coverage.readthedocs.io/en/coverage-4.3.4.  Apparently there's also a plugin that integrates it with nosetests: http://nose.readthedocs.io/en/latest/plugins/cover.html.

**Comment by joegomes** [comment]
Another tool for measuring test coverage https://coveralls.io/

**Comment by rbharath** [comment]
#414 by @lilleswing has added coverage!

@lilleswing: The badge displays unknown coverage though (I see the 85 percent on clicking through however). Do you have any thoughts on what's going wrong there?

**Comment by lilleswing** [comment]
I see 85%  I think you just had to wait a bit for caches to heat up on coveralls :).  I think we can close this one for now.

**Comment by rbharath** [comment]
Yep, see it now too!
