### ISSUE TITLE
I completely followed the docker plan, but something went wrong

### ISSUE THREAD

**Issue by xuan-lab** [deepchem/deepchem#4157]
## 📚 Installation

[deepchemio/deepchem:latest]

![image](https://github.com/user-attachments/assets/0ae93183-42ca-4275-ba68-09a0fef5069a)

I solved each software package step by step according to the error report, but in the end it didn't help.

- [T ] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [T ] I used Google Colab.
- [ T] I do have multiple CUDA versions on my machine.

**Comment by xuan-lab** [comment]
I guarantee that I have not made any changes to the docker image or software package, they are all original and official. In addition, my CPU is Ultra 7 155H and there is no independent graphics card.

**Comment by rbharath** [comment]
It's possible the docker image might be out of date. Could you share the precise installation command you used and we will debug?

**Comment by xuan-lab** [comment]
> It's possible the docker image might be out of date. Could you share the precise installation command you used and we will debug?

it just docker pull deepchemio/deepchem:latest
all commands show in my image which i post.

**Comment by xuan-lab** [comment]
> It's possible the docker image might be out of date. Could you share the precise installation command you used and we will debug?

Can you reproduce it

**Comment by rbharath** [comment]
@aaronrockmenezes Can you please take a look at this bug and report back?

**Comment by aaronrockmenezes** [comment]
@xuan-lab Can you please highlight the exact issue you're facing? Are you referring to the CUDA warning?

**Comment by xuan-lab** [comment]
> @xuan-lab Can you please highlight the exact issue you're facing? Are you referring to the CUDA warning?

I have solved it in the past few days. It is a driver problem. Sorry to trouble you.
