### ISSUE TITLE
Add QM9 to Benchmark Suite

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#421]
Google's new paper (https://arxiv.org/abs/1702.05532) analyzes the QM9 dataset and presents a variety of benchmark results. We should add qm9 to the DeepChem benchmark set.

**Comment by rbharath** [comment]
CC @joegomes

**Comment by joegomes** [comment]
@rbharath Agreed, although this one is not as easy to add as QM7 since the structures/properties are stored in individual files.  I currently only have an atomization-only version of this dataset, I'm re-running my parsing script to pull all properties and should be ready tomorrow.

**Comment by rbharath** [comment]
@joegomes Thanks for getting this in so promptly!

@miaecle Would it be possible to incorporate QM9 into the benchmark suite?

**Comment by miaecle** [comment]
@joegomes Running into a minor problem, there is a 'smiles' column in the .sdf.csv file which needs to be deleted(SDFLoader will add another column named 'smiles' into the dataframe together with the one from csv file, this could cause dimension problems of dataset.ids). Would you mind helping me do the change in the remote directory?
@rbharath Running on different splits now, should be done by this weekend.

**Comment by rbharath** [comment]
@miaecle Awesome! Looking forward to integrating this into MoleculeNet.

**Comment by joegomes** [comment]
@miaecle I've removed smiles strings from the csv and updated the dataset in the remote directory.  Let me know if this works.  Thanks for looking into this!

**Comment by rbharath** [comment]
@miaecle Thanks for merging into benchmarks!
