### ISSUE TITLE
Run full benchmarks weekly and auto-update perf table

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#422]
The full benchmark suite currently takes about 20 hours to run. This is onerous enough that the full benchmark isn't run often. Ideally, we should have an automatic weekly run of the full benchmark suite that automatically generates a new performance table and creates a new github PR with the updated perf table in `README.md`. This would keep our numbers honest and prevent bitrot or inadvertent bugs from creeping in undetected.

@lilleswing: Would it be feasible to use our Jenkins CI to do this?

**Comment by lilleswing** [comment]
I actually already have it set up and running.

http://171.65.103.54:8080/job/Full%20Benchmark/

I just haven't gotten around to analyzing the results and making the pull request for the benchmarks that are off.

Something to note is that ToxCast currently heap dumps when running on a 1080, so I had to disable it.  I can file a separate issue for that.

**Comment by lilleswing** [comment]
I also think e-mail on loosing 1% accuracy is better than automatically updating the table.

**Comment by rbharath** [comment]
@lilleswing Awesome! Can we set it up so it emails the deepchem-dev google group (https://groups.google.com/forum/#!forum/deepchem-dev) with a full perf table after every weekly run? (With say a large warning if performance drop greater than 1% is noticed)

**Comment by lilleswing** [comment]
Yeah I'll do that after I fix the diffing logic (it isn't parsing the results.csv correctly right now)

**Comment by rbharath** [comment]
Benchmarks now run weekly (or so) on Jenkins so going to go ahead and close this issue.
