### ISSUE TITLE
Add Crystallography Open Database to Benchmarks

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#425]
http://www.crystallography.net/cod/: "Open-access collection of crystal structures of organic, inorganic, metal-organic compounds and minerals, excluding biopolymers."

Would be very neat to incorporate into DeepChem, especially to make more useful for inorganic chemists.

**Comment by rbharath** [comment]
If you're interested in solving this issue, you will need to create a pull request that does the following:

- Download and package the C.O.D dataset into a suitable .tar.gz or .zip file
- Add a new function to `dc.molnet` that adds a function `load_cod`. This function should match the other moleculenet loader functions and return a tuple `(train_dataset, valid_dataset, test_dataset)`. Each dataset object should be a `dc.data.Dataset` that holds crystal structures from the C.O.D dataset. This function should load the data from the .tar.gz (or .zip) file you created previously
- The actual dataset, depending on the size, might need to be hosted on the DeepChem AWS bucket. Once your loader function works, before merging, ask one of the technical steering committee members to  load your dataset to the cloud bucket. Modify your `load_cod` function to pull down the dataset from AWS.

If you would like to implement this feature, please leave a comment here, then create a PR marked [WIP] that tracks your implementation efforts.

**Comment by VIGS25** [comment]
I had a look at the downloaded zip file, but the zip file organization consists of a sequences of multiple directories, subdirectories and sub-sub directories with the final files contained in the .cif format. Some directories are empty as well.

I would think a better way to do it would be to just extract out all files and then add them together into another zip, and just write the loading function for that.

@rbharath: What do you think?

**Comment by rbharath** [comment]
I'd be open to a simplified ZIP so long as the usage terms of the original dataset allow us to do so. We can host the simplified zip in the DeepChem S3 bucket.

Thanks for taking a lead on this!

**Comment by VIGS25** [comment]
I looked around the website, but couldn't find any usage terms that talk about reuse of the data.
For now, I think I can retrieve the files using their structure.

Also, I noticed rdkit has no method to read .cif files. I used pybel (would need to install this) to convert them to .sdf files to be used by the sdf loader in utils.save directly.

However, the space used for the files would be ~60 GB.

**Comment by peastman** [comment]
You can load them with OpenMM, which is already a dependency for DeepChem.  http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.pdbxfile.PDBxFile.html

**Comment by VIGS25** [comment]
I tried opening the file with OpenMM but it threw an error: `simtk.openmm.app.internal.pdbx.reader.PdbxReader.SyntaxError: %ERROR - [at line: 15] Unexpected token in loop_ declaration`

Attached below is a minimal failing script, with the loading for a random file and one of the cod files.

**Bash Script**
```
wget www.crystallography.net/cod/cif/1/00/04/1000401.cif
wget ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/mmCIF/v4/4v40.cif.gz
gunzip 4v40.cif.gz
```

**Python Script**
```
import os
from simtk.openmm.app.pdbxfile import PDBxFile

test_file_cod = './1000401.cif'
assert os.path.exists(test_file_cod) == True

test_file_random = './4v40.cif'
assert os.path.exists(test_file_random) == True

print('Loading random file...')
loaded_random = PDBxFile(test_file_random)
print('Random file loaded.')

print('Loading COD file...')
loader_cod = PDBxFile(test_file_cod)
print('COD file loaded')
```

**Comment by peastman** [comment]
The file is messed up.  The line it's complaining about is

```
_publ_author_name
```

That ought to be


```
_publ_author.name
```

Note the change of a `_` to a `.`.  `_publ_author` is the data category, and `name` is the data item within that category.  (See http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/publ_author.html.)  The file seems to have the same error in lots of other lines.

Be grateful OpenMM gave you a clear error message telling you where the problem was.  When I tried loading that file into VMD, it segfaulted!

**Comment by VIGS25** [comment]
Thanks for the explanation!

https://www.iucr.org/resources/cif/dictionaries/cif_mm

The above page states that they use the same names as the CoreCIF dictionary, but in a difference in formalism. The difference corresponds exactly to the use of `.` and `_`, which we encounter in all the files.

**Comment by rbharath** [comment]
Closing this issue. We can continue discussion in https://github.com/deepchem/moleculenet/issues/2
