### ISSUE TITLE
Use Tensorflow queues?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#429]
This blog post claims that using feed-dicts instead of tensorflow queues can signficantly hurt GPU utilization:

https://blog.metaflow.fr/tensorflow-how-to-optimise-your-input-pipeline-with-queues-and-multi-threading-e7c3874157e0#.1ovwdpqjl

It would be great to investigate whether switching to using queues can increase our GPU utilization. @proteneer noted previously that the one-shot models had mediocre utilization numbers for example.

**Comment by peastman** [comment]
I'll try some experiments and see if they help.  If so, we'll need to think about how they can fit into the API.

**Comment by rbharath** [comment]
@peastman Awesome! Let's definitely brainstorm APIs if it looks like queues improve performance.

**Comment by peastman** [comment]
I've done some experiments on Tox21, and it looks like there's definitely some performance to be gained.  It's not huge, but not negligible either.  So I'd like to move forward to implementing this.  I'll start by adding queue support to `TensorflowGraphModel`, then move on to other classes once all the details are ironed out on that.

This will require some small API changes.  It won't affect the code for using these model, but subclasses will need to change a bit.  Currently `construct_graph()` contains this code:

```Python
output = self.build(graph, name_scopes, training)
labels = self.add_label_placeholders(graph, name_scopes)
weights = self.add_example_weight_placeholders(graph, name_scopes)
```

With this change, `labels` and `weights` won't necessarily be placeholders anymore, and they'll be constructed differently for training and evaluation.  So I'd like to change this so `build()` is responsible for creating them and returning them:

```Python
(output, labels, weights) = self.build(graph, name_scopes, training)
```

Does that look ok to everyone?

Next, it currently creates two graphs in the constructor, one for fitting and one for evaluation:

```Python
self.train_graph = self.construct_graph(training=True, seed=self.seed)
self.eval_graph = self.construct_graph(training=False, seed=self.seed)
```

The queue causes problems for the training graph.  At the end of training, once all data has been fed into the queue, we need to close it.  That means it can only be used once.  If you try to call `fit()` again and reuse the same training graph, you'll get an exception.  So I'd like to change it to no longer create a persistent training graph.  It will be created when you call `fit()`, and if you call it a second time, a different graph will get created.  I don't think that should cause any problems, but does anyone see issues with it?

One method that would have to change is `_get_shared_session()`.  Currently it creates two persistent shared sessions: one used for training and one used for evaluation, and the session is stored in a field of the relevant graph.  If there's no persistent training graph, that obviously has to change.

I talked to @rbharath about this, and he doesn't think there's any good reason to have two shared sessions.  Does anyone see a problem with creating only one session object and using it for everything, both training and evaluation?

**Comment by joegomes** [comment]
@peastman LGTM, thanks for taking this on!
