### ISSUE TITLE
why not use 4-space-tab when we are updating to tensorflow 1.0?

### ISSUE THREAD

**Issue by ludlows** [deepchem/deepchem#430]
Writing python code with 4-space-tab is a common sense in python community.
Can we change the current code to follow that order?

**Comment by rbharath** [comment]
@ludlows Google's python style guide (when we started) dictated 2-space indentation, so DeepChem followed that style (the original models we used were open-sourced by Google). It's worked for us so far, and I don't see a compelling reason to change it.

**Comment by ludlows** [comment]
ok. I will write code by the google style.
Thanks for your reply.
