### ISSUE TITLE
dc.molnet module

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#437]
Building off the discussion in #433, we need a way of letting DeepChem users run MoleculeNet benchmarks in user-space. Here's a preliminary design for this system:

- Add a dc.molnet module to DeepChem. This module has a `run_benchmarks(datasets, model)` function. The model must be of type `dc.model.Model` (through inheritance). The datasets will be a list of strings naming the different datasets desired to be benchmarked against. Then users can run MoleculeNet benchmarks locally without having to contribute their code into the DeepChem repo. Users can use xgboost, or pytorch models locally without having to make a PR (or add dependencies) to DeepChem.
- Add functions `dc.molnet.load_X`, for every dataset in MoleculeNet. These functions currently live in the `examples/` folder. Let's move them all into the new `dc.molnet` module. (We probably want to leave a couple loader functions, say `tox21/` in the `examples` so users know how to load code). All datasets will live on S3 and will be pulled down locally to user computer first time `dc.molnet.load_X` function is called.
- To accept a new model as "official" (listed on the front benchmarks page), the model will need to be open source in a github/bitbucket repo. A DeepChem dev will code-review to make sure there's no cheating, then re-run the benchmark locally, and upload the numbers obtained.

@miaecle: Could you check out the difficulty of refactoring `benchmark.py` and the loaders in `examples/` into the proposed `dc.molnet` module?

**Comment by miaecle** [comment]
@rbharath Thanks for proposing this, looks really helpful! 
Should be very straightfoward to do the transfer, I will let you know when things are ready.

**Comment by miaecle** [comment]
@rbharath One concern here is that whether the `model` should be a function(need to specify hyperparameters) or an object(already defined). For the former, it will be in a very similar shape as `benchmark.py`. For the latter, I believe it should be able to handle user-defined model as long as  it has `fit` and `evaluate`  operations(and their parameters and returns are the same).

On the other hand, the latter will cause another problem: n_tasks, n_features need to be specified when defining model, making it not suitable for deepchem models.

My preference is to making two separate scripts, one for deepchem models, one for user-defined models. As they are working on the same dataset with same splittings, results should be comparable.

**Comment by XericZephyr** [comment]
Hey @rbharath , I am currently trying it out. 

I think our method basically acts as a new featurizer. My point is we might also need to provide a way for the user to **override** the `featurizer_func`. At present, it seems not possible, e.g., `examples/muv/muv_datasets.py:load_muv`.

**Comment by rbharath** [comment]
@XericZephyr Good point. We should let users provide their own featurizers for benchmarking.

@miaecle Thanks for looking into this! Could you put together a basic prototype and open a PR? I think your proposal sounds reasonable at a high level, but I'll need to do some code review before I know for sure.

**Comment by XericZephyr** [comment]
Actually, for the featurizer part, which I learned from sklearn,  
you can produce some function like: 

```python
def check_featurizer(featurizer):
      featurizer_dict = {
            "ECFP": XXX.ECFPFeatuerizer,
            "GraphConv": XX.GraphConvFeaturizer
      }
      if isinstance(featurizer, str):
           featurizer_func = featurizer_dict.get(featurizer, None)
           if featurizer_func is None:
                 raise Exception() # Raise some reasonable exception, indicating this is not supported.
      elif isinstance(featurizer, dc.xx.UserFeaturizer):
           featurizer_func = featurizer
      else:
           raise Exception() # Raise: it is not supported
      return featurizer_func
```

**Comment by miaecle** [comment]
@rbharath got it, will try to get everything into the new module.
@XericZephyr Thanks a lot for providing the insight, I totally agree with you on the importance of user-defined featurizations. I guess the biggest difficulties here is to make customized featurizer compatible with deepchem dataset structure.

**Comment by XericZephyr** [comment]
PR #447 . Maybe we could close this issue. @rbharath
