### ISSUE TITLE
libprotobuf version problem issue?

### ISSUE THREAD

**Issue by XericZephyr** [deepchem/deepchem#439]
I did the following line in bash

```bash
python -c "import deepchem as dc"
```

But was getting the following error: 
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
[libprotobuf FATAL google/protobuf/stubs/common.cc:78] This program was compiled against version 3.1.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.2.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.1.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.2.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
Aborted (core dumped)
```

But it is not caused by tensorflow since I tried `import tensorflow as tf` and we are good. 

Are you guys aware of any other dependency package which uses the protobuf?

**Comment by rbharath** [comment]
Hmm, this is a new bug for me. I'm not sure what's going on. Has anyone else run into this?

**Comment by XericZephyr** [comment]
Thanks @patrickhop, it works by putting `import tensorflow` before `import deepchem as dc`, i.e., 

```
python -c "import tensorflow as tf; import deepchem as dc"
```

**Comment by rbharath** [comment]
@patrickhop Thanks for the fix!

This seems like some terrible Tensorflow/DeepChem ugliness. It would be nice if we could figure out what's going on at a deeper level. For now, I'm going to leave this issue open so we can point new users here.

**Comment by lilleswing** [comment]
@XericZephyr  are you using the installs script in 
```bash
scripts/install_deepchem_conda.sh
```

It specifically installs protobuf 3.1.0 vs 3.2.0

**Comment by XericZephyr** [comment]
Hey, @lilleswing , thanks for point it out. But I think I would like to keep my current solution since I do not want to change my system libprotobuf version to mess up some other library.

**Comment by lilleswing** [comment]
We are currently using protobuf 3.1.0 with tf 1.0.1.  Latter versions of tf require protobuf 3.2.x.  We will upgrade the protobuf when we upgrade tensorflow (probably to 1.2.x).  This issue can be closed and further conversation can be had https://github.com/deepchem/deepchem/issues/602
