### ISSUE TITLE
Apache/BSD License for DeepChem

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#441]
We intend to move DeepChem from the GPL license to an Apache/BSD license (ideally, the same [license](https://github.com/tensorflow/tensorflow/blob/master/LICENSE) that Tensorflow uses). The reasons for this move are that we want to make DeepChem maximally useful to the greatest number of users, including commercial users.

There are a few steps that we will need to take before we can swap the license:

1. Remove DeepChem dependency on OpenBabel, which is GPL licensed. @lilleswing has taken a lead on this project. (Major thanks for taking on the effort!)
2. Set up a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) so that new contributors agree to contribute under Apache/BSD terms.

If you have any comments, concerns, or thoughts, please chime in on this thread.

**Comment by rbharath** [comment]
Also, props to @mpharrigan for kicking off a conversation on the merits of BSD vs. GPL and making a strong case for why BSD is better for the community.

**Comment by peastman** [comment]
Tensorflow uses Apache 2.0, which is quite different from BSD.  There are similarities, but also significant differences.

You might also consider the MIT license (which *is* a "BSD style") license.  That's what we use for OpenMM.

**Comment by rbharath** [comment]
@peastman Good to know! What are the key differences between Apache 2.0 and MIT?

**Comment by peastman** [comment]
You can compare the licenses directly:

https://opensource.org/licenses/MIT

https://www.apache.org/licenses/LICENSE-2.0

The most significant difference is the patent license section in the Apache license.  Some people really like it, since it gives some protection against patent suits.  But some companies refuse to contribute to Apache licensed software because they're afraid they might inadvertently end up giving away their patents.

**Comment by lilleswing** [comment]
@rbharath how do we want to go about tackling writing a CLA?  

https://github.com/deepchem/deepchem/pull/460
Removes all of the GPL code from the repo.

**Comment by rbharath** [comment]
To provide an update on this thread, @lilleswing and I are working offline on getting a CLA for DeepChem. We've decided to proceed with an MIT license. In the meanwhile:

- For all new PRs, we'll ask contributors that they're OK with their contributions being switched to MIT. (stopgap until CLA is set up).
- @CCXD: I believe that you're the only major contributor who is external to the Pande group. Are you ok with your Chembl contribution being moved to an MIT license? If not, we will move the Chembl code into an external deepchem-gpl repo.

**Comment by CCXD** [comment]
@rbharath I have no problem with the switch, but I'm not familiar with the licensing on all the datasets in this case. Will the dataset be distributed with the Deepchem package, or should the datasets be fetched from the ChEMBL service directly? I think the former will be in conflict with the CC license that ChEMBL has.

**Comment by lilleswing** [comment]
We now have a CLA and are under the MIT license.  I believe we can close this issue.
