### ISSUE TITLE
convert_atom_to_voxel

### ISSUE THREAD

**Issue by huizhuzhao** [deepchem/deepchem#445]
Recently, I am working on deepchem, and found it is great. I have a question about the meaning of function `_conver_atom_to_voxel` at module `deepchem.feat.grid_featurizer.py` ; the code if short, but I still can not grasp the underlying mechanism of such a **convertion**. 

Any help would be much appreciated.

**Comment by rbharath** [comment]
CC @evanfeinberg and @lilleswing who are much more familiar with the grid featurizer code than me.

**Comment by lilleswing** [comment]
@huizhuzhao it is attempting to move from a continuous [x,y,z] space into a cubic grid.  [0,0,0] in in [x,y,z] space should correspond to [box/2, box/2, box/2] in voxel space, and everything outside the box should be ignored.  

It doesn't seem like this is actually what this function is doing :(.  I'll investigate re-implementing the function correctly and see what happens to our scores.

**Comment by rbharath** [comment]
Going to close this issue since I think we refactored and cleaned up this code. Please re-open if still an issue.
