### ISSUE TITLE
Add PDBFixer info to README

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#450]
The README needs to be updated to indicate how to add installation instructions for PDBFixer.

@lilleswing Would you mind making a PR for this?

**Comment by XericZephyr** [comment]
FYI, I found we need to install openmm first. This is simple by `conda install -c omnia openmm`.

Also, I am willing to make a PR for this.
You can assign the issue to me @XericZephyr if you are good with some *online guy* making changes to your documentation.

**Comment by rbharath** [comment]
@XericZephyr Please go for it!

**Comment by XericZephyr** [comment]
cf PR #452 .

**Comment by rbharath** [comment]
@XericZephyr Thanks for getting this done quickly!
