### ISSUE TITLE
Remove pybel from scripts/dock_dude

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#456]
@evanfeinberg do we still need scripts/dock_dude?  Is there an example of how to use it?  On my feature branch it is the last use of openbabel.  

https://github.com/lilleswing/deepchem/pull/9

**Comment by rbharath** [comment]
@lilleswing It would be nice to port this script if possible. The dataset comes from http://dude.docking.org/ and is used to preprocess data from that source before doing docking. It would be great to have an rdkit version of this :-)

**Comment by lilleswing** [comment]
I ported scripts/dock_dude to no longer require openbabel

**Comment by evanfeinberg** [comment]
Awesome! The less dependency on openbabel the better :-)
