### ISSUE TITLE
deepchem-dev@googlegroups.com is not forwarding jenkins failure emails to the group

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#457]
![selection_013](https://cloud.githubusercontent.com/assets/1225605/23770690/e9c228a2-04c8-11e7-9efd-19ce5e90149d.png)

![selection_014](https://cloud.githubusercontent.com/assets/1225605/23770699/f473d066-04c8-11e7-81ce-d55f2582351d.png)

Do we have to allow mail to be sent from no-reply@deepchem.io?  Do we have to allow mail signed by sendgrid.net?

**Comment by rbharath** [comment]
@lilleswing Hmm, I don't really know too much about mail signing/sending. Is there anyone with good suggestions?

**Comment by lilleswing** [comment]
@rbharath I guess you can take this issue as a heads up then for maybe getting some spam while I figure out how google groups e-mailing works.

**Comment by lilleswing** [comment]
Resolved -- have to send from karl.leswing@schrodinger.com (A member of the group -- not no-reply@deepchem.io)
