### ISSUE TITLE
Checkpointing is significantly slowing down training

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#458]
@peastman has been doing some great profiling work of the multitask networks. Here are his suggestions:

> The saver [for PCBA] isn't as huge a bottleneck as [for Tox21], but it's still significant.  It spends maybe two minutes computing one epoch, then 30 seconds saving it.  Why is saver so slow???  Anyway, you could get a significant speedup by checkpointing less often.  Perhaps make it a configurable option, with the default being to do it every 10 epochs?

We should try to switch down the default to every 10 epochs and add a user flag.

**Comment by peastman** [comment]
For comparison, with Tox21 it actually spends more time saving checkpoints than it does computing.

I can add this.  Does a `checkpoint_interval` argument to every `fit()` method sound good?

**Comment by rbharath** [comment]
@peastman :+1: Please go for it!

**Comment by ludlows** [comment]
can we give an option to use numpy array as the trained parameters?

**Comment by rbharath** [comment]
@ludlows I don't think we want to get into loading via Numpy. Better to use Tensorflow's save/loading mechanisms natively.

@peastman Thanks for the quick turnaround! Will go ahead and merge this PR in.
