### ISSUE TITLE
DeepChem Docker Image?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#463]
Got some interest expressed in having a DeepChem docker image for new users to play with. I don't use Docker that much since our Stanford clusters ban Docker (superuser on shared cluster is a big no-no for them), but I'd be pretty welcoming of community contributed Docker images. PRs welcome!

**Comment by mpharrigan** [comment]
sherlock supports "singularity" containerization http://singularity.lbl.gov/ which is designed with supercomputation in mind. I mentioned this in lab as a potential way to get whichever version of tensorflow you want (by making a container from the latest fedora or whatever and installing things normally).

**Comment by jchodera** [comment]
See #464.

**Comment by jchodera** [comment]
Now that you have a top-level `Dockerfile`, you probably want to set up an account on [DockerHub](https://hub.docker.com/) to create automated builds.

Once you have your DockerHub account set up, you can select "Create" from the top drop-down menu, "Create Automated Build", then "Create Auto-build Github".

**Comment by jchodera** [comment]
You could even create a `deepchem` organization (Organizations -> "Create Organization") so that docker users can install and run the image with a single line:
```bash
docker run -i -t deepchem/deepchem bash
```

**Comment by rbharath** [comment]
@jchodera Definite thumbs up. Will set up DockerHub account soon.

**Comment by rbharath** [comment]
I think we're set up on DockerHub now https://hub.docker.com/r/deepchem/deepchem/. Could someone give it a try to see if things are working?

**Comment by jchodera** [comment]
The build hasn't posted yet. Is it still in the process of building on dockerhub?

**Comment by rbharath** [comment]
Hmm, I think I might have messed up the dockerhub settings...

**Comment by jchodera** [comment]
It says your source repo is `rbharath/deepchem`. Don't you want `deepchem/deepchem`?

**Comment by rbharath** [comment]
Yep, you're right. Having trouble figuring out the dockerhub UI so can't figure out how to change it right now  (it's probably something simple I'm blanking on...)

**Comment by jchodera** [comment]
You can just delete the project and try again!

**Comment by patrickhop** [comment]
a separate cpu-only and gpu version would be nice

**Comment by jchodera** [comment]
Will it fall back to CPU if no GPUs are available?

If separate versions are needed, you can have dockerhub build two different branches to produce different tagged images, but this could quickly get hard to maintain. You could migrate the `Dockerfile`s to another repo, but then the images would have a different name.

**Comment by rbharath** [comment]
Any volunteers to help with the set-up on DockerHub? I probably won't have bandwidth to sit down and figure this out for a few days.

**Comment by patrickhop** [comment]
@jchodera Sounds complicated. As long as it can fall back from GPU to CPU (i think it does?), one image seems to make more sense.

**Comment by jchodera** [comment]
> Any volunteers to help with the set-up on DockerHub? I probably won't have bandwidth to sit down and figure this out for a few days.

Let me take a quick stab at it.

**Comment by jchodera** [comment]
Whoops, I can't, since I'm not a member of the `deepchem` github org.

**Comment by rbharath** [comment]
@jchodera Welcome to deepchem! (just invited you to join the deepchem github org :-))

**Comment by jchodera** [comment]
That's odd. For some reason, `deepchem` isn't showing up in the list of organizations in my linked GitHub account:
![image](https://cloud.githubusercontent.com/assets/3656088/24029506/fb0cb020-0aac-11e7-9ac2-0d8595abc23e.png)
Maybe it has something to do with the new GitHub teams vs organizations vs members?

**Comment by lilleswing** [comment]
We have a working gpu-enabled docker image with documentation on creating and uploading it in the release docs.  We can close this issue now.
