### ISSUE TITLE
Add Membrane Permeability to MolNet

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#467]
Drug discovery practitioners often run into permeability issues.  Having a membrane permeability benchmark would help with the development of permeability models.

**Comment by rbharath** [comment]
Love the idea. Are there any public datasets we could use for this purpose?

**Comment by patrickhop** [comment]
I'm not aware of any public permeability dataset > 200 examples. If anyone finds one, I'm happy to write up an example.

@lilleswing I'm putting in a pull request for a few ADME examples tonight. There are a few assays that have public data that is large enough to be interesting.

**Comment by lilleswing** [comment]
A membrane permeability dataset has been added to MoleculeNet
https://github.com/deepchem/deepchem/tree/master/examples/membrane_permeability

We can close this now.
