### ISSUE TITLE
Add Blood-Brain Barrier Permeability to Molnet

### ISSUE THREAD

**Issue by evanfeinberg** [deepchem/deepchem#469]
Inspired in part by @lilleswing 's issue #467 , it would be great to predict BBB penetration as well. There seems to be a dataset of 500+ molecules here:

http://cheminformatics.org/datasets/li/bbp2.smi (p = penetrate , n = not penetrate) 

http://dx.doi.org/10.1021/ci050135u (paper about the dataset). 

It would be great if there were larger datasets available as well.

**Comment by rbharath** [comment]
Definitely would like to have this in MolNet. PR welcome!

**Comment by miaecle** [comment]
Looks interesting, I am willing to take the job!

**Comment by rbharath** [comment]
Now merged in. Thanks for quick turnaround @miaecle and for the suggestion @evanfeinberg!
