### ISSUE TITLE
Several ops (esp. for multitask) not available in GPU

### ISSUE THREAD

**Issue by evanfeinberg** [deepchem/deepchem#475]
@rbharath and I were experimenting with some tensorflow multitask models and noticed relatively low GPU utilization when running ```nvidia-smi```. When adding a ``` with tf.device('/gpu:0'):``` line, the TensorFlow graph failed to build due to an error stating that ```tf.split()``` did not have a GPU kernel. Potentially, these ops are actually being computed on the CPU. This could help explain the persistent low GPU utilization in other models as well.

**Comment by lilleswing** [comment]
https://www.tensorflow.org/api_docs/python/tf/dynamic_partition

is also CPU only

**Comment by rbharath** [comment]
I think @peastman has optimized the multitask code in later work. Going to close this issue.
