### ISSUE TITLE
Travis Is Timing Out

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#476]
https://travis-ci.org/deepchem/deepchem/jobs/211983666

Did we add a lot of tests?
Which tests are taking the longest?
For longer running tests we might want to switch over to jenkins.

**Comment by rbharath** [comment]
IIRC, the major time sink in the test suite is the autodock-vina runs in `dc.dock.tests`. I'll aim to swap these out with the GPU-vina (it will be half-baked at first, but should be fast :-))

**Comment by miaecle** [comment]
I believe tests for molnet also take quite some time, planning to swap to tests on smaller datasets.

**Comment by lilleswing** [comment]
After adding @slow annotations on slow tests we can now close this issue.
