### ISSUE TITLE
MoleculeNet PyTorch Port

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#479]
PyTorch makes it much easier than Tensorflow to define dynamic models. Some cheminformatics deep models (notably http://pubs.acs.org/doi/abs/10.1021/ci400187y) are very dynamic and may be easier to implement in PyTorch than in DeepChem.

I'd like us to start building up a suite of PyTorch models. The install for PyTorch looks very simple (`conda install pytorch torchvision cuda80 -c soumith` for the Cuda 8.0 version). We can use MoleculeNet to benchmark the new models. The goal would be to replicate the MoleculeNet model implementations in PyTorch so new contributors can use either Tensorflow or PyTorch as desired.

I believe @miaecle has taken a crack at this already. If anyone else is interested in PyTorch porting, please chime in on this thread and we can coordinate.

**Comment by soumith** [comment]
hey guys, it's cool that you're thinking of a pytorch port. what kind of help could i offer?

**Comment by rbharath** [comment]
@soumith Thanks for chiming in here! We really appreciate your efforts with PyTorch. For now, we're just starting work, so we don't have many concrete questions yet, but as we start porting models in https://arxiv.org/abs/1703.00564 over, we might have some feature requests to make.

Also, if you're ever in the Bay area, come by and say hi! Most of us are based at Stanford.

**Comment by miaecle** [comment]
@soumith Hi, thanks for participating! PyTorch is a real wonderful package, it has been a pleasure to play around with it. We are currently still on the very first step of utilizing the model(and planning to use it to build up some more fancy models), will let you know if there is any concerns or requests!

**Comment by rbharath** [comment]
Closing this since we've decided to focus on TensorFlow as our backend for the time being. Will reopen this issue if matters look different in future.

**Comment by bionicles** [comment]
I would love to help integrate DeepChem's moleculenet features with PyTorch!

**Comment by peastman** [comment]
You should be able to use the MoleculeNet datasets directly with a PyTorch model, no modification required.  Just call `iterbatches()` on the dataset.  It will return an iterator that represents each batch as a tuple of NumPy arrays.
