### ISSUE TITLE
Better Support For Reaction ML in DeepChem

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#480]
Based off conversations (on Gitter and offline), it's becoming clear that DeepChem doesn't have great support for reaction chemistry. This would include support for file formats such as SMARTS and REACTION-SMILES, and would include MoleculeNet integration for public reaction datasets. In particular, I'd love to port the following paper (http://pubs.acs.org/doi/abs/10.1021/ci5006614) to DeepChem.

Here are some concrete TODOs:
- Adding SMARTS and REACTION-SMILES loaders
- Adding the patent dataset used in the paper above to `dc.molnet`
- Duplicating the reaction-type classifier reported in paper above within DeepChem

This effort should be able to build on great efforts by RDKit team to improve reaction informatics (CC @proteneer).

PRs welcome for any of the TODOs mentioned above!

**Comment by rbharath** [comment]
Also, props to @bowenliu16 for the great conversation that made me realize that DeepChem needed lots of reaction-handling improvements.

**Comment by mrwns** [comment]
Currently, I won't be able to write a lot of code myself (thesis ongoing...), but I can certainly join the discussion and have a look at PRs... after all, most of what we did for http://onlinelibrary.wiley.com/doi/10.1002/chem.201605499/full is in rdkit

**Comment by rbharath** [comment]
I'm temporarily shelving this issue since it looks like we won't have enough manpower to take it on. Might reopen at some future point as things change.
