### ISSUE TITLE
Contrib Folder

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#489]
@lilleswing suggested offline that having a `Contrib` folder at the top level (next to `examples/`) might be a useful resource. DeepChem right now contains a mix of maturing models (suitable for users) and pretty bleeding-edge research code. For very research-y code, it's often more important to get the math right than to clean up the code into DeepChem style. The `Contrib` folder can serve as a natural home for this type of code. Other (more engineering-inclined) users can volunteer to clean up `Contrib` entries and coordinate with the owner of the contributed code to do so.

**Comment by XericZephyr** [comment]
I do think we can even completely split out the entire model section, **to another repo**, for both mature and bleeding-edge research code. This actually eliminates most heavy dependencies, e.g., tensorflow, making it extremely useful in many complex environments, e.g., CentOS-based clusters. 

But the con side is this step is engineering expensive. We might need a plan and some additional efforts at this moment to walk towards it. If we mostly agree, we might open an issue for open discussion.

**Comment by rbharath** [comment]
@XericZephyr We'd prefer to keep the models in this repo. While we're happy to share DeepChem with the community, we don't have the bandwidth to maintain multiple deepchem repos. We very much encourage community forks though that explore alternative design choices

**Comment by lilleswing** [comment]
We can close this issue.
