### ISSUE TITLE
How to uninstall it ?

### ISSUE THREAD

**Issue by codemarsyu** [deepchem/deepchem#491]
Some could help me about how to uninstall the package. I create conda environment to install the dependency and deepchem. Now how to remove the deepchem ? I rewrite part of the code and want to recompile it and replace it with the old package which is already sitting in env/chenenv/lib/python2.7/site-package/ .

Any help is welcome!

**Comment by rbharath** [comment]
If you're developing, you can install with `python setup.py develop` so you don't have to remove old DeepChem after making changes. If you want to uninstall, an easy way is to just delete the `deepchem` package from within `site-package/`

**Comment by cxhernandez** [comment]
Or `pip uninstall deepchem`

**Comment by codemarsyu** [comment]
@rbharath Thanks for your reply! It is a good way to install the package by develop mod. In past few days, I install and remove those package again and again. So stupid! Thank you !
