### ISSUE TITLE
Can we cache the features from dataset ?

### ISSUE THREAD

**Issue by codemarsyu** [deepchem/deepchem#494]
Each time I rerun the benchmark, it will load and featurize the data samples. The process is very time-consuming and it may take minutes each run. Can we cache them somewhere ?

**Comment by rbharath** [comment]
@miaecle This might be a nice upgrade for `dc.molnet` after the current large refactor. Probably best to have a flag added to the `load_X` constructors to determine whether or not caching should happen.

**Comment by miaecle** [comment]
@codemarsyu @rbharath This is definitely a good idea, will try to make the change.

**Comment by XericZephyr** [comment]
Simple suggestion, maybe we can use `joblib` to do so. 

For example,
```
mem = joblib.Memory(cachedir=os.environ.get("DEEPCHEM_CACHE", "/tmp"))
@mem.cache
def load_datasets(xx, xxx, xx):
     pass
```
which directly benefits from my new prototype design #485  as I mentioned in my note.

If you guys do not mind, I can take this issue and quickly adapt it to the outside benchmark dataset loading procedure.

**Comment by rbharath** [comment]
@XericZephyr Definitely appreciate the offer, but I think this one would be better for us to do in-house since it will affect the architecture of a number of our internal models. We should have a prototype in a couple weeks, and would love to hear your feedback then

**Comment by rbharath** [comment]
Added by #496.
