### ISSUE TITLE
[BUG] HopV dataset wrong featurizer variable name.

### ISSUE THREAD

**Issue by XericZephyr** [deepchem/deepchem#499]
In https://github.com/deepchem/deepchem/blob/master/deepchem/molnet/load_function/hopv_datasets.py

L35 should be:
```
featurizer = deepchem.feat.CircularFingerprint(size=1024)
```
This will allow customized featurizer input.

Will send a PR to fix it.

**Comment by miaecle** [comment]
@XericZephyr Did not notice the fault here, thanks for the quick fix!
