### ISSUE TITLE
Message Passing Neural Networks

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#507]
Cool new paper from Google Brain that beats all previous benchmarks on QM9. It would be great to see how it does on MoleculeNet.

https://arxiv.org/abs/1704.01212

CC @miaecle

**Comment by lilleswing** [comment]
No source code or network topology :( and you know they did it in tensorflow.

**Comment by rbharath** [comment]
The paper is a little sparse on details. The say they started from gated graph neural networks:

https://arxiv.org/abs/1511.05493

**Comment by patrickhop** [comment]
perhaps a starting point would be to implement graph convolutions (weave style) in this new message passing framework?

**Comment by rbharath** [comment]
Very open to community contributions if anyone is interested in taking this on :)

**Comment by patrickhop** [comment]
I took a quick shot at implementing a message-passing GG-NN yesterday.

Convergence at the message passing stage doesn't seem to be an issue. Experimentally i'm getting: ||h(v)^(t) - h(v)^(t+1)|| < 1e-3 for t > 10.

I'm not getting noteworthy results on delaney though (yet). The only interesting takeaway I have so far is that pushing each vertex feature vector through a NN before the sum in the readout / gather stage seems to be helpful. I think one of the papers speculates that this acts as an attention mechanism. Perhaps it's worth trying this in the GC-DNNs.

**Comment by rbharath** [comment]
@patrickhop You should contribute your implementation to DeepChem once it looks good :-)

**Comment by patrickhop** [comment]
I've got some early results for a variation of GG-NN, which beats graph-convs by a small margin on the one test i've tried. I'll need to do more tests to confirm everything, but I think this will turn out to be an exciting direction that's worth exploring further.

Best Result:
Delaney (Index Split) r2=.812

Featurization Structure:
Message Fn: h_w
Veretx-Update Fn: nn.linear(concat(m_v^(t+1), h_v^(t)))
Readout Fn: sum_{v \in V}(relu(nn.linear(h_v)))

Message-passing converges surprisingly well. The updates (from what i've seen) seem to be contractive almost everywhere. Using a GRU for the update function seems to work, but slightly lags a simple linear layer, which surprised me.

Implementation is in pytorch, but this probably won't be ready for broader use in the codebase for some time. @rbharath would this be a good fit for the new contrib directory?

**Comment by miaecle** [comment]
@patrickhop Thanks for testing on the model, very excited to see the results. I have implemented weave(Steven Kearnes's graph convolution, also mentioned in the paper) and another DAG model based on a directed graph version of molecules, both showing similar results(slightly higher than graphconv) on delaney, while still cannot beat graphconv on most classification tasks(though pretty close). I personally think these "graph" models share similar levels of explanatory power, differences may mostly due to specific tasks. 

Looking forward to see more results from your model, hope it can perform better on classification too! For deepchem, I believe contrib folder will be the best choice. BTW, have you tested the reproducibility of your pytorch model? Graph models in deepchem(tensorflow based) are not perfectly stable.

**Comment by rbharath** [comment]
@patrickhop Sounds awesome! Seconding @miaecle's comments that this would be a good fit for the `Contrib/` folder.

**Comment by patrickhop** [comment]
Thanks for the kind words guys. @miaecle i've noticed that you've been quite busy lately! I've been meaning to try how those models perform on the ADME tasks. Wrt to reproducibility, I think it's pretty good. I'm setting the random seeds and using OrderedDicts for the graph-structure.

I agree that all graph models seem to be pretty similar. After casting all of them as message passing algorithms, their structures don't seem to be radically different - more radical directions imo are virtual nodes, inclusion of distance data, and using set2set in the readout fn. This stuff seems to help with QM9, but it's unclear how / if that will transfer to more traditional datasets.

I'll try to send out a PR sometime today.

As an aside, should we be using explicit hydrogens for the chemical graphs? The Google paper indicates that it helped them a lot, but it wouldn't surprise me if it was a QM9 thing.

**Comment by mrwns** [comment]
for quantum-chemical problems, explicit hydrogens should be used, as the input to a DFT calculation will also contain all atoms, and of course more information is retained.

for medchem problem one can get away with implicit Hs :)

**Comment by rbharath** [comment]
Going to close since implemented by #710.
