### ISSUE TITLE
Turn off yapf for Contrib/ folder

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#510]
The `Contrib/` folder is our new home for user-contributed code. If users have a new model which looks cool, they can contribute it to this folder. DeepChem devs will take on responsibility for porting code into `DeepChem` itself if there's wide user interest.

Since this folder is meant for new users (and not part of the DeepChem package itself), we should turn off `yapf` checks for it.

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/643
