### ISSUE TITLE
Consistent dimensions in tensorgraph

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#525]
Implementing the fully connected models in tensorgraph, I ran into a lot of inconsistencies between the dimensions of different tensors that make the process a lot more difficult.  Let's consider how to improve the situation.

In an offline discussion with @rbharath and @lilleswing last week, we reached one tentative conclusion: all models in deepchem (not just tensorgraph ones) should have outputs of dimension three or higher: (batch_size, n_tasks, something).  For regressors, the third dimension is 1.  For classifiers, it's n_classes.  For some models, there might be more dimensions.  But there will always be at least three, and the first two will always be batches and tasks.  The goal of this is to let other code handle regression and classification models in a more uniform way.

That's fine  as far as it goes, but it immediately creates a problem: the `y` vector in a dataset has dimension 2, not 3.  So should the `Label` layer be dimension 2 or 3?  If 3, that guarantees you always have to override `default_generator()` to reshape it when building the feed dict.  If 2, then it's inconsistent with the output, which means you immediately have to wrap it in a `Reshape` layer before you can send it into a `L2LossLayer` or `SoftMaxCrossEntropy`.

Assume you've done that and computed a loss.  For multitask networks, you'll usually want to put that into a `WeightedLoss` layer.  But here we have another problem: the losses and weights have different dimensions.  So you either need to a) override `default_generator()` to reshape the weight vector, b) wrap the weights in a `Reshape` layer, or c) wrap the losses in a `Reshape` layer.  It's very confusing and creates obstacles for anyone trying to use it for the first time.

Can we improve the situation?  Here are a few possibilities I've thought about.

 - `default_generator()` could do some reshaping automatically.  It knows the dimensions of the `Label` and `Weight` layers, so it could reshape the inputs as necessary.

- Alternatively (or in addition?) it could call a `_transform_labels()` method that subclasses could override.  That would also simplify other cases.  For example, classifiers need to convert the labels to one hot representation.  This way they would only need to override a one line method to do that, rather than having to completely reimplement `default_generator()`.

- `L2LossLayer`, `SoftMaxCrossEntropy`, and `WeightedLoss` could all be made more intelligent.  They could inspect the shapes of their inputs and automatically reshape them as necessary.

**Comment by rbharath** [comment]
I like the idea of making `L2LossLayer`, `SoftMaxCrossEntropy`, and `WeightedLoss` more intelligent. Ideally, I'd like to make the issue of weights something beginners don't have to deal with, and pushing more intelligence into layers we can implement seems a nice plan.

**Comment by rbharath** [comment]
I think #567 resolved this issue so going to close.
