### ISSUE TITLE
Computing gradients w.r.t input in TensorGraph

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#527]
In order to implement pose-generation algorithms for docking, we need to be able to take the derivative of the deep score function with respect to the atomic coordinates of the molecule. If the score function is implemented as a `TensorGraph` model, we will consequently need a way to take a derivative of the loss w.r.t a `Features` node. I can see a couple ways to make this happen:

- Define a general `gradients(layer_1, layer_2)` method that returns `tf.gradients(layer_1.out_tensor, layer_2.out_tensor)`.
- Define a special purpose method for taking gradients w.r.t `Features` instead of arbitrary layers.

@lilleswing, @peastman, would love to hear your thoughts on which API you'd prefer.

**Comment by patrickhop** [comment]
We're getting a gradient-based docking method? Very nice!

Any literature on this, or is it new?

**Comment by rbharath** [comment]
This is part of the Autodock Vina port. Turns out that Autodock Vina takes exactly this gradient as part of its local ligand pose optimization. (It also uses a random perturbation step to change ligand poses to escape local optima).

**Comment by rbharath** [comment]
I'm going to close this issue. It doesn't look like there's been much request for this feature. Might re-open if necessary later.
