### ISSUE TITLE
weird PDB dataset issues

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#529]
I'm debugging the pdb files in the pre-processed core pdbbind_core_5_df.pkl file, and there's really weird assignments of formal charges, amongst other things.

For example, in the first row of the pickle'd dataframe, the C1 in many arginine residues have a formal charge of +1. (Which literally can't happen because it has no hydrogens to donate, and it's bonded to three nitrogens, one which of which is double bonded, thereby satisfying the octet rule).

Th original 2D3U PDB file is fine, but the open-babel processed pdb file is totally messed up:

```
...
AUTHOR    GENERATED BY OPEN BABEL 2.3.90
...
ATOM    237  CZ  ARG A  32      29.622  31.291  74.146  1.00  0.00           C1+
```

How were these files generated? Does it go through an RDKit intermediate representation somewhere?

**Comment by rbharath** [comment]
I think these might be really old files. We haven't used `df.pkl` is a number of months. My guess is that openbabel was used to handle the loading and processing since RDKit couldn't handle proteins nicely then.

**Comment by rbharath** [comment]
Closing since I think there are now cleaned up files on AWS. Please re-open if necessary.
