### ISSUE TITLE
Initialization of Dense layers

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#532]
TensorGraph's Dense layer now lets you specify initializers for weights and biases, but it does it in a way that makes it not very useful.  Instead of specifying an initializer object, you just specify the class.  It then constructs an instance of that class by calling the constructor with no arguments.  That means you can't use any initializer that requires constructor arguments (`constant_initializer`, `random_normal_initializer`, etc.).

I tried modifying it to let you pass in an initializer object instead, but that caused `model.save()` to throw an exception because initializer objects can't be pickled.  It looks like this requires a somewhat more involved fix.

**Comment by rbharath** [comment]
Keras has `Initializer` objects which let users specify initializations that require constructor arguments. Perhaps we could to the same, and make sure the initializer objects are implemented in a pickle-able fashion?

**Comment by peastman** [comment]
We discussed passing in a lambda to get around this problem, but it turns out that doesn't work either: lambdas also can't be pickled.  Apparently there are a couple of libraries that implement pickling of lambdas: http://stackoverflow.com/questions/16626429/python-cpickle-pickling-lambda-functions.  Possibly we could use one of those, or maybe we want to rethink the whole approach here.

**Comment by peastman** [comment]
For the moment, I've created the following class to work around the problem:

```Python
class Initializer(object):
  """This class exists as a workaround for Tensorflow initializers not being picklable."""

  def __init__(self, initializer_class, **kwargs):
    """Create an Initializer for constructing Tensorflow initializers.

    Parameters
    ----------
    initializer_class: class
      the type of initializer to create
    kwargs:
      any other arguments will be passed on to the Tensorflow initializer's constructor
    """
    self.initializer_class = initializer_class
    self.kwargs = kwargs

  def __call__(self):
    return self.initializer_class(**self.kwargs)
```
