### ISSUE TITLE
Factor TensorGraph into separate repo?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#534]
Had a good conversation with @cxhernandez today who suggested some interesting ideas.

`TensorGraph` is a general purpose framework for building deep-learning models on top of Tensorflow. It might make sense to factor it out into its own repo rather than having it be a part of DeepChem, since `TensorGraph` could be used to build other types of deep-networks and not just ones for molecular machine learning.

@lilleswing, @peastman would love your thoughts here.

**Comment by peastman** [comment]
In principle it's a generic API.  In practice, though, it's entwined with a lot of the deepchem code.  At the top of tensor_graph.py I see the following imports:

```Python
from deepchem.data import NumpyDataset
from deepchem.metrics import to_one_hot, from_one_hot
from deepchem.models.models import Model
from deepchem.utils.evaluate import GeneratorEvaluator
```

Some of those are just utility function that could be separated out.  But some of them are pretty fundamental to how it works.  Like the fact that `TensorGraph` extends `Model`, and that `fit()` takes a `Dataset` object.

Of course, you could say that `Model` and `Dataset` are themselves generic classes, not specific to chemistry.  So perhaps the proposal is to split DeepChem into two libraries, one that's a generic machine learning library and one that only has things specific to chemistry.  But we need to think very carefully about what we gain by doing that, and what's the cost.

**Comment by rbharath** [comment]
This is a good analysis. I think it's not worth making changes this drastic
to the library, especially when the code is under rapid development.

Perhaps there's a simple answer here. DeepChem is already a general purpose
machine learning library, but just one with better utilities and support
for chemistry than other existing packages. We just need to add more
non-chemistry examples and documentation to make this fact clearer to users.

@cxhernandez: what changes would you like to see before you'd be open to
using DeepChem as a general purpose ML library?


On Apr 26, 2017 9:07 AM, "peastman" <notifications@github.com> wrote:

In principle it's a generic API. In practice, though, it's entwined with a
lot of the deepchem code. At the top of tensor_graph.py I see the following
imports:

from deepchem.data import NumpyDatasetfrom deepchem.metrics import
to_one_hot, from_one_hotfrom deepchem.models.models import Modelfrom
deepchem.utils.evaluate import GeneratorEvaluator

Some of those are just utility function that could be separated out. But
some of them are pretty fundamental to how it works. Like the fact that
TensorGraph extends Model, and that fit() takes a Dataset object.

Of course, you could say that Model and Dataset are themselves generic
classes, not specific to chemistry. So perhaps the proposal is to split
DeepChem into two libraries, one that's a generic machine learning library
and one that only has things specific to chemistry. But we need to think
very carefully about what we gain by doing that, and what's the cost.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepchem/deepchem/issues/534#issuecomment-297460724>,
or mute the thread

**Comment by cxhernandez** [comment]
> what changes would you like to see before you'd be open to using DeepChem as a general purpose ML library?

For me personally? Zero.

I suggested separating the two codebases because your reason for developing Tensorgraph in the first place doesn't seem unique to DeepChem. I can imagine a large number of people working on NNs would want to take advantage of the workflows available here but are either thrown off or intimidated by the chemistry-oriented nature of this library. Separating the two might engage a larger community to develop Tensorgraph, which would eventually improve the models in DeepChem.

**Comment by rbharath** [comment]
I definitely like the idea of broader community outreach. We could write
some blog posts to get the message out that DeepChem isn't only for
chemistry :-)
