### ISSUE TITLE
Definition of save() and reload() inconsistent between TensorGraph and other models

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#545]
Copying over @peastman's comment from #522 to kick off the discussion

> TensorGraph doesn't implement reload(), so I'm trying to implement it. In the process, though, I've found there's some ambiguity in what save() and reload() are supposed to do. For other Model subclasses, save() means to write out the current values of all parameters. That is, write a checkpoint. reload() then loads those saved parameters back in. But in TensorGraph, save() does something completely different: it pickles the TensorGraph object itself, so a description of all the layers that make up the model. It then has a load_from_dir() method for reconstructing pickled models, but as far as I can tell, no method for loading checkpoints. Instead, it automatically reloads the most recent checkpoint (if there is one) when you call fit() or predict().
>
> How should this work?

I agree that we should figure out a consistent semantics for all models otherwise we'll have some confused users

**Comment by lilleswing** [comment]
I might be biased -- but I do like the internal weights of a model being part of its internal state and as hidden from the user as possible.

That is how TensorGraph currently does it --
#save() saves the whole object, including weights
#fit() and #predict() use the most up to date weights at all times.

**Comment by rbharath** [comment]
I agree that the new `TensorGraph` API is nice since users don't need to explicitly call `reload()`.

@lilleswing Would it be hard to convert `SklearnModel` and `XGBoostModel` over to this style? (We don't need to convert the old `TensorflowModel`s since those are getting deprecated).

**Comment by rbharath** [comment]
I'm going to close this issue since it doesn't seem to have come up again. Please re-open if necessary.

**Comment by peastman** [comment]
This behavior was changed by #791, so it's now more consistent.
