### ISSUE TITLE
Towards TensorGraph Docking

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#553]
I've been working for a while on getting GPU powered docking enabled with a TensorGraph implementation. There are still a number of TODOs on this:

- Add a `Gradient` layer to TensorGraph that enables taking the derivative of molecular positions with respect to an energy function. (Pose generation requires the ability to locally use gradient descent to optimize molecular positions).
- Change `predict` on `TensorGraph` so that the output of an arbitrary layer can be fetched (So that `Gradient` layer otuputs can be fetched from graph).
- Implement some methods to randomly shake ligands within a binding pocket. (Pose Generation methods work by iteratively shaking, then gradient descent minimization of ligand coordinates in a binding pocket).
- Put these steps together to implement a pose-generation method.

**Comment by patrickhop** [comment]
very exciting!

**Comment by rbharath** [comment]
I'm going to close this issue for the time being since I'm no-longer working on this feature. If you're interested in taking up the challenge, leave a note here and will re-open the issue.
