### ISSUE TITLE
Create a Kaggle Organization?

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#559]
Beat the benchmarks in moleculenet.

https://www.kaggle.com/organizations/new

**Comment by rbharath** [comment]
I'd be interested with the idea of making a Kaggle organization, but with a few caveats:

- @miaecle is working on a significantly upgraded version of MoleculeNet. We should wait for this version of the paper to come out.
- The challenge should be something like "design a single architecture that beats all the benchmarks in moleculenet". If we let people make different architectures per datasets, the results won't be that useful.

**Comment by rbharath** [comment]
Is this still interesting for folks?

**Comment by rbharath** [comment]
Closing for now. Feel free to re-open if there's interest.
