### ISSUE TITLE
Benchmarking RL Algorithms

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#571]
Moving conversation over from #568. 

I suggested
> I really like the idea of adding more environments to DeepChem. New environments are the only real > way of benchmarking our RL suite, and it would be great to build up our capabilities. In fact, I have a > couple extra suggestions:
> - Can you make a new submodule dc.rl.envs that hosts environments and move the Tic-tac-toe  environment there?
> - Can you add a section to the benchmarks on the README.md that documents best performance on the Tic-Tac-Toe environment? I think we should start keeping running numbers on the RL environments like we do for MoleculeNet (betting RL is going to be increasingly important moving forward).

@lilleswing responded
> @rbharath what do we mean by performance?
> - avg score of a rollout?
> - How much do we allow to train?
> - Time to a given avg score?
> - Max score of a rollout?
> Performance for these things is hard because everyone disagrees on what performance means

In general, I think we should follow OpenAI's lead. For some environments like cartpole, they set "solve" conditions on its environments and counts the number of episodes trained until solved. For other environments, (air-raid) they use best 100-episode performance. This sounds like a reasonable lead. For tic-tac-toe, using 100-episode performance sounds good (OpenAI does this for Go boards)

**Comment by rbharath** [comment]
As another note, following recommendations from OpenAI (https://blog.openai.com/openai-baselines-dqn/amp/), we should add a random baseline to each environment we benchmark.

**Comment by Agent007** [comment]
Oh wow. How is RL applied to drug discovery? I can see the reward being something like the affinity score in protein-ligand docking, but I don't see where the Markov process is.

**Comment by rbharath** [comment]
The RL work is more following a hunch rather than a solid application. We suspect it will eventually be useful.

**Comment by rbharath** [comment]
Going to close this PR since creating stable RL algorithms is a broad area of research that doesn't neatly fit within DeepChem's mandate. There's also been a lot of external efforts on this question (see https://arxiv.org/abs/1709.06560 for a good recent paper).
