### ISSUE TITLE
Comment on test_graph_features

### ISSUE THREAD

**Issue by jnhwkim** [deepchem/deepchem#581]
Is it a correct comment in https://github.com/deepchem/deepchem/blob/master/deepchem/feat/tests/test_graph_features.py#L29 ?

It said:
```
# Note there is a central carbon of degree 4, with 3 carbons and
# one nitrogen of degree 1 (connected only to central carbon).
raw_smiles = ['C[N+](C)(C)C']
```
however,

Ref: [Smiles visualizer 1](http://molview.org/?q=C[N+](C)(C)C)
[Smiles visualizer 2](http://hulab.lifemodules.org/smi2img/C%5BN%2B%5D%28C%29%28C%29C/)

**Comment by lilleswing** [comment]
@jnhwkim you are correct about the molecule.

![selection_005](https://cloud.githubusercontent.com/assets/1225605/26787971/bc421ce2-49d9-11e7-95e7-10e932bdaabb.png)

However the test is still correct despite the bad comments.
Internally ConvMol reorders the atoms by adjacency degree in the featurizer.  
This means ["degree slice"](https://github.com/deepchem/deepchem/blob/master/examples/tox21/tox21_tensorgraph_graph_conv.py#L42) can be the [start_index, stop_index) for atoms of a certain degree.

If you look at the atom features themselves for the test and do a one-hot decoding of the [4]'th atom you will see that its [1] atom feature is set to 1, which is the one-hot index for nitrogen.

I updated the docs for the test here.
https://github.com/deepchem/deepchem/pull/582

**Comment by rbharath** [comment]
@jnhwkim, @lilleswing: Thanks for the catch and quick fix.

Going to go ahead and close the issue.
