### ISSUE TITLE
Use faster Tensorflow on Travis

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#586]
The travis build log reports

```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
```

The build of Tensorflow installed by pip is designed for maximum compatibility.  That means it doesn't use modern CPU features like AVX and FMA, which makes it a lot slower.  There's a collection of alternate builds maintained by the community at https://github.com/yaroslavvb/tensorflow-community-wheels/issues, or we could create our own if none of those works.  This might make some of the tests run faster.

**Comment by lilleswing** [comment]
I compiled TF from source with the appropriate CPU flags when attempting to boost GPU utilization (i5-6500, GTX 1080).  I anecdotally only received marginal speedups (< 5%) over common bench marking  tasks (MoleculeNet Tensorflow Models).

This is not to say that it would not improve Travis times because Travis is CPU only, and travis is running the nosetests not MoleculeNet.

**Comment by peastman** [comment]
I wouldn't expect it to have much effect when using a GPU.  But I've seen anecdotal reports of people getting as much as a 3x speedup when running calculations on CPUs.

**Comment by peastman** [comment]
Intel has posted a conda installer for their optimized tensorflow.  We should give it a try:

https://software.intel.com/en-us/articles/intel-optimized-tensorflow-wheel-now-available
https://anaconda.org/intel/tensorflow

**Comment by rbharath** [comment]
Going to close since I think we've solved this issue.

**Comment by peastman** [comment]
I don't think we really solved it, but I believe the next version of Tensorflow will move to including those features by default, so that will hopefully solve it.  Also, my attempt at using faster Tensorflow (#863) was unsuccessful.  I'll close that.
