### ISSUE TITLE
got error when running atomicconv

### ISSUE THREAD

**Issue by odek53r** [deepchem/deepchem#590]
I ran the tensor_graph_hyper_param_eval program which is located at /deepchem/contrib/atomicconv/acnn/refined/ and got NotImplementedError.

`root@2d7339f2dcad:~/a60008/deepchem/contrib/atomicconv/acnn/refined# python tensor_graph_hyper_param_eval.py 
/opt/conda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Warning: No xgboost installed on your system
Attempting to run %s will throw runtime errors
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
/opt/conda/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
/root/a60008/deepchem/contrib/atomicconv/acnn/refined/datasets
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
TIMING: dataset construction took 79.411 s
Loading dataset from disk.
TIMING: dataset construction took 19.661 s
Loading dataset from disk.
Traceback (most recent call last):
  File "tensor_graph_hyper_param_eval.py", line 118, in <module>
    feed_dict_generator(train_dataset, batch_size, epochs=num_epochs))
  File "/opt/conda/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 134, in fit_generator
    self.build()
  File "/opt/conda/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 326, in build
    node_layer.create_tensor(training=self._training_placeholder)
  File "/opt/conda/lib/python2.7/site-packages/deepchem/models/tensorgraph/layers.py", line 47, in create_tensor
    raise NotImplementedError("Subclasses must implement for themselves")
NotImplementedError: Subclasses must implement for themselves
`
does anyone know how to solve it?

**Comment by rbharath** [comment]
The files in contrib are not actively maintained. It's more a staging area for code to facilitate new developer contributions. Try using the atomicconv version merged into the main branch of deepchem or in examples.
