### ISSUE TITLE
Version bump to 1.2.0

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#591]
There have been a couple of major bugfixes (#574, #577, #584). It might be time to consider doing a version bump soon. Are there any other changes people would like to see before we make the bump?

**Comment by lilleswing** [comment]
We found some issues with padding in Datasets which we are fixing here --
https://github.com/schrodinger/schrodingerdeepchem/pull/1

those changes should be up for PR by end of week though.

**Comment by lilleswing** [comment]
Also GPU docker we fixed in place -- so a version bump is not necessary to get the docker image.

**Comment by rbharath** [comment]
Closing since we're about to shift to 1.3
