### ISSUE TITLE
Internal Vina and NNScore (Binana)

### ISSUE THREAD

**Issue by mwojcikowski** [deepchem/deepchem#596]
Hello DeepChem team and conributors,

I'm planning to port/include the Numpy based implementation of Vina scoring function and Binana featurizer to DeepChem, as briefly discussed with @rbharath. It's based on my implementation which is currently included in [ODDT](https://github.com/oddt/oddt). In short, the Vina SF is operating purely with Numpy/Scipy which does not require additional IO nor the complicated PDBQT writer procedures. For detailed code see [oddt.docking.internal](https://github.com/oddt/oddt/blob/master/oddt/docking/internal.py) module.

The easiest way to go, would be add a `PoseScorer` or other featurizer API for both and build around ODDT, but will need it as dependency (BSD license). Additional advantage is that it could help phase out Pybel dependecies (#371) by switching them to RDKit backend with ODDT.

The other option is to port the code leaving the boilerplate behind, but it will be much more work and harder to maintain.

The only problem with DeepChem's Binana/NNscore is that it does not use the exact atom types definition on both sides of contacts (ligand and protein). This leads to much bigger (and probably sparse) vector of features. Do we wish to keep that?

Thoughts or suggestions?

**Comment by lilleswing** [comment]
@mwojcikowski can you comment on the PoseScorer API you want to propose?  I'm a  bit lost in how you would encapsulate the new atom typing with Rdkit molecules.

**Comment by rbharath** [comment]
@mwojcikowski Excited to see this moving forward! I think there's a lot of need for improved protein-ligand open source tooling.

In general, I'd be OK with adding on an ODDT dependency. There's no need to add on extra code into DeepChem if there's a good open-source implementation (with usable license) elsewhere. The one question I have is that it looks like ODDT has an openbabel (GPL code) backend. Does that conflict with ODDT's BSD license?

Seconding @lilleswing comment about the API. Would be good to post proposed PoseScorer API here to get feedback before PR.

**Comment by mwojcikowski** [comment]
@rbharath ODDT does not include any GPL code. We have `from pybel import *` and we extend base classes from openbabel to our needs. Both toolkits RDKit and OpenBabel are optional and are not required to function properly. Most of the functionality is toolkit independent. Main disadvantage of RDKit is limited format readers/writers, but for Vina and NNScore we're fine.

@lilleswing The atom typing is straightforward. ODDT generates structured Numpy array representing molecule (aka. `atom_dict`, see [docs](https://oddt.readthedocs.io/en/latest/#atom-dict)). It is standardized in both toolkits as much as possible. `atom_dict` is all Vina needs. NNscore on the other hand uses [additional translation](https://github.com/oddt/oddt/blob/master/oddt/scoring/descriptors/__init__.py#L13) from ADT to `atom_dict`.

I hope that clears things up.

Considering the API I will ping you back in a while, I need a moment to identify the best one. Basically we can replace every Vina "--score_only" call. Same goes with NNScore featurizer, which also does Vina scoring. The sampling algorithm for pose generation is under intensive work.

**Comment by lilleswing** [comment]
@mwojcikowski openbabel is GPL :(.  I will begin chats with a legal team on whether incorporating it as an optional module in DeepChem breaks the MIT license (i.e. importing it from util.dependencies and failing if it does not exist and not having it in the ez install script).

How much of the base class logic do you use?  Do you use methods or just the interfaces?  Interfaces are not copy writable, so if we fulfill the interfaces but don't use implementation we are safe.  If we are only using a little simple logic we can rewrite it.
https://www.gnu.org/prep/standards/standards.html#Reading-Non_002dFree-Code

**Comment by lilleswing** [comment]
[pybel](https://pypi.python.org/pypi/PyBEL) is Apache 2.0 so we are probably fine.

**Comment by rbharath** [comment]
Great, I think we should be good license wise for now.

@mwojcikowski the ODDT docs look very nice! We would greatly appreciate any help with the DeepChem docs. They're all in github, but have been languishing for want to attention :-)

**Comment by mwojcikowski** [comment]
@lilleswing It's not the Pybel you were looking for ;) The actual pybel (`pip install openbabel`) is [GPL](https://pypi.python.org/pypi/openbabel). I will underline once again: ODDT does not contain GPL code. 

The ODDT backend for openbabel in question is [here](https://github.com/oddt/oddt/blob/master/oddt/toolkits/ob.py). Feel free to compare its content with the [Pybel module](https://github.com/openbabel/openbabel/blob/master/scripts/python/pybel.py). I use the common interfaces/API for classes, which as you said are not copy writable. If the has no underlying changes it is absent in ODDT code, and inherited from external pybel, eg. `class Molecule(pybel.Molecule)`.

Side note: toolkits are not forced to be installed neither from conda nor from pip. If there are none then ODDT reises exception. If there is just one (RDKit either Openbabel) it keeps using the one throughout.

The only real part you can find identical is the `Residue` class, which I have [authored](https://github.com/openbabel/openbabel/commit/7c8a9b63279cee7cdab0635af218f8165b2fa90f) in between 2.3 and 2.4 so I keep it for backward compability.

Legally there is nothing wrong if MIT code uses GPL code from outside the codebase (hey, you all probably use kernel somewhere). It probably might be forbidden in the company legal guideline to use GPL libraries for any internal use, which as I understand, is what worries you. But in the RDKit + DeepChem + ODDT trio does not violate that rules in any ways (no copyleft code there).  

I hope this calcifies the licensing for now.  

@rbharath Thanks, I try to document as much as I can, although I'd say its rather under-documented at best ;) It's fine that you have tutorials in notebooks but we could maybe move parts of them to straightforward RST and let Sphinx do its magic. I have no idea if google indexes the content of .ipynb on Github.

**Comment by rbharath** [comment]
I'm going to close this old issue (cleaning up open issues). Feel free to re-open if there's new things to discuss!
