### ISSUE TITLE
Expansion of dc.hyper

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#598]
Industry often wants a push button find me a good model.  Expanding dc.hyper to have state of the art hyper parameter searching would greatly help with industry pickup.  What is done should support GPU clusters in some way.

**Comment by rbharath** [comment]
Yes, would be glad to see this pushed further. The current version of dc.hyper could use a lot of work.

**Comment by patrickhop** [comment]
I've had a lot of luck with this:

https://github.com/hawk31/pyGPGO

**Comment by rbharath** [comment]
I think we now have GP optimization support. Going to go ahead and close this issue
