### ISSUE TITLE
Installing DeepChem in WS for Linux?

### ISSUE THREAD

**Issue by JimSEOW** [deepchem/deepchem#599]
Has anyone here ever attempted to install DeepChem in [Windows Subsystems for Linux](https://blogs.msdn.microsoft.com/commandline/2017/05/11/new-distros-coming-to-bashwsl-via-windows-store/) (Ubuntu, Suse and Fedora) in Windows 10 ?
![workbook](https://msdnshared.blob.core.windows.net/media/2017/05/Multi-distro-1280x838.png)

**Comment by rbharath** [comment]
I'd be very happy to see this happen. Lots of pharma still on Windows...

**Comment by JimSEOW** [comment]
Using Win10 x64 [ NOT Windows Subsystems for Linux]
Visual Studio 2015 x64 Environment console. 
Miniconda3 [python3.5]

I get:

Ran 329 tests in 1138.065s
FAILED (**errors=17, failures=1**)

Perhaps it is possible to systematically work through the 17 Errors and failures 1 to make deepchem works in Windows 10.

Not yet test on WSL yet.

**Comment by lilleswing** [comment]
Is  WSL more available to people than installing Docker on Windows?
https://docs.docker.com/docker-for-windows/

**Comment by JimSEOW** [comment]
If the motivation of DeepChem includes **[Democratizing Drug Discovery](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjkpJnMmsDUAhWBAMAKHZadCAYQtwIILTAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsntikyFI8s8&usg=AFQjCNH1jOc5j8iVvR9_Tps3Xj_RyYXjLQ)** through some of the [500 active Windows 10 users](https://www.engadget.com/2017/05/10/windows-10-500-million-users/)

Here are the options in the degree of increasing (a) _integration possibility_ and (b) risk of _test failure_ without modification of the existing codes

1. Docker for Windows through Hyper-V => **close** container [100% Linux]
2. WSL => .NET can **directly execute** WSL linux command and display the results using e.g. WPF [almost 100% bash linux]
3. Windows e.g. Anaconda PY3.5 => .NET (e.g. F#) can **embed** DeepChem python codes using PythonNET [0% linux] => Installation seems OK with **nosetests -v deepchem --nologcapture** results

**Ran 329 tests in 1138.065s**
FAILED (errors=17, failures=1)

**Comment by rbharath** [comment]
I'd be glad to see this happen, but it all depends on someone willing to do the legwork. 

PRs welcome :)

**Comment by JimSEOW** [comment]
This would take a critical mass of a users to test the Windows installation and start sharing the errors and report back to others. For RDKit, although there is windows installation, it is always behind the linux.

**Comment by peastman** [comment]
What currently prevents it from working?  DeepChem itself is pure Python, so it should work without change in any of those environments.  The catch is that the libraries it depends on also need to work.  Which of them don't?

**Comment by JimSEOW** [comment]
I encourage others to try. As I did a quick and dirty installation just to see how bad is the compatibility. Lessons learn from RDkit is that it is always tricky to support Window.  Perhaps we will move forwards faster if we recruit those Python Windows experts from RDkit

I follow the steps in[ install_deepchem_conda.sh](https://github.com/deepchem/deepchem/blob/master/scripts/install_deepchem_conda.sh) MANUALLY step by step

```
conda create -y --name $envname python=$python_version
source activate $envname
conda install -y -c omnia pdbfixer=1.4
conda install -y -c rdkit rdkit
conda install -y joblib
yes | pip install six
conda install -y -c omnia mdtraj
conda install -y scikit-learn
conda install -y setuptools
conda install -y -c conda-forge keras=1.2.2
yes | pip install --upgrade $protobuf_url
yes | pip install --upgrade $protobuf_url
conda install -y -c anaconda networkx=1.11
conda install -y -c conda-forge xgboost=0.6a2
conda install -y -c pillow
conda install -y -c anaconda pandas=0.19.2
yes | pip install $tensorflow==1.0.1
yes | pip install nose
yes | pip install nose-timer
yes | pip install flaky==3.3.0
```
Not all the dependent libraries in linux are available in EXACTLY the same version as in Windows. One has to systematically analyse. I suggest more people give it a try. I did it just out of curiosity of the benefits I listed above. The same benefits would also apply to users from RDKit. Hopefully more people put some effort together. I have to continue with using DOCKER in WINDOWS. If I do find time next week, I would see what else I could report.

**Comment by JimSEOW** [comment]
FAILED (errors=16, failures=1)
Once I replaced deepchem\dock\autodock_vina_1_1_2_linux_x86\bin with Win32 vina.exe and vian_split.exe there is no more failure

**Comment by rbharath** [comment]
@JimSEOW encourage you to contribute a PR with your fixes!

**Comment by JimSEOW** [comment]
@rbharath please give me some time, I am still sorting out much of deepChem.

I am very excited of the immense potential of using deepChem to integrate deep learning to disrupt existing docking algorithms

The test I did today, both for Win10 X64 with GPU tensorflow and also OpenSuse [one click installable from Window Store and not shown here], looks very promising. I encourage more people to join to test.

**Comment by rbharath** [comment]
Of course, please take the time you need :)

**Comment by JimSEOW** [comment]
@rbharath what kind of [Autogrow ](http://autogrow.ucsd.edu/) algorithms are available in DeepChem?

There is also windows x64 [igrow](https://github.com/HongjianLi/igrow), inspired by AutoGrow

**Comment by rbharath** [comment]
We don't currently have any Autogrow algorithms, but I would be happy to see contributions of Autogrow methods :)

**Comment by jbesnard** [comment]
I run deepchem directly with win 10 and python 3.6, and tf is using my GPU.
Benchmark.py is working fine.
Running nosetests -v deepchem --nologcapture gives:
Ran 312 tests in 689.807s
FAILED (errors=25)

Some are from import flacky failing, as mentioned by JimSEOW, vina.

I did not try docker because I'm sure if it can use the GPU.
I can look at some and reports some error. Documentation on how to use vina and processed files may be needed, if it tries to run some linux scripts there, then it may be a problem on windows.

**Comment by rbharath** [comment]
Great, thanks for the report! I'd very much welcome any PRs fixing these broken tests on windows. If the Windows build starts working, we can set up an Appveyor build to make sure that we maintain windows capabilities.

**Comment by JimSEOW** [comment]
@jbesnard, how did u install deepchem and its components in W10? Manual or script? Python3.6 from anaconda3? VIna just down and replaced. The other errors are the issues which need more time to investigate.

**Comment by jbesnard** [comment]
I have anaconda for python installation.
I followed the instruction from the readme for deepchem; other libraries, if failing pip or conda were installed by following instructions from their website (tensorflow-GPU for example).

I pip install flaky, but as a results, the test would get stuck at
> test_tensorboard (deepchem.models.tensorgraph.tests.test_tensor_graph.TestTensorGraph) ... 2017-07-21 09:29:34.484424: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
Not sure why.

I removed it, and now trying with vina.exe in correct location. Vina is running as I'm writing so looks to be ok.

Is there a command to nosetest to output the errors in one text file?
Also with more info as:
> Test that VinaGridDNNDocker can dock. ... ok
> Test that VinaGridDNNDocker can be initialized. ... ok
> Test that VinaGridRFDocker w/pockets can be initialized. ... ok
> Test that VinaGridDNNDocker can dock. ... ERROR
> Test that VinaGridDNNDocker can be initialized. ... ERROR
Show that VinaGridDNNDocker sometimes work and sometimes doesn't!

Should we create a new issue for windows 10 installation?

**Comment by JimSEOW** [comment]
@jbesnard 

We definitely need this: _Is there a command to nosetest to output the errors in one text file?_

**Comment by jbesnard** [comment]
I found one to export xml, but it exports everything, not just errors! Need to add those 2 flags: --with-xunit --xunit-file=output.xml
It helps a bit to debug though. Some problem on windows are linked to the test, and not the program itself. The test downloads files from s3 as tar.gz, and there is a tar command. But there is no "tar" under windows. Can be solved by doing it on the side (random_full_DNN and core_grid). Also need wget in windows available, I didn't have it in my path.

I can't get flaky to work, I must remove it to get the test to go through the end.

[output2.zip](https://github.com/deepchem/deepchem/files/1165633/output2.zip)

**Comment by JimSEOW** [comment]
@jbesnard   any gnu tool you need. download this into a folder and add that folder to Path
http://gnuwin32.sourceforge.net/packages.html

**Comment by jbesnard** [comment]
@JimSEOW , tar -zxvf is not implemented. 
> Cannot fork: Function not implemented

**Comment by Dgelemi** [comment]
A bit of gap here. But would a python solution to extract tar.gz files from the test and example be more appropriate than the tar command?
I think there was a PR or comment on using python own library instead of wget. This could be another step to make it more OS independent (may still have encoding error though).
This may work: https://sukhbinder.wordpress.com/2014/03/06/untar-a-tar-file-with-python/ , but I don't know if need to change some argument to replicate the current tar command of the test files.

**Comment by peastman** [comment]
That sounds like a great idea.

**Comment by rbharath** [comment]
+1. This sounds great.

**Comment by Dgelemi** [comment]
I have a solution with a new function in deepchem\utils\__init__.py that would read a .tar.gz and uncompressed it.
the function is to work in pair with the function download_url.
For example for qm9_datasets:
`    if not os.path.exists(dataset_file):
      deepchem.utils.download_url(
          'http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/gdb9.tar.gz'
      )
      deepchem.utils.untargz_file(os.path.join(data_dir, 'gdb9.tar.gz'),data_dir)`
This creates the file gdb9.csv within the data_dir and the function load_qm9() runs

All the loader would need to be edited, but I think that's what was done to replace wget by the python urlretrieve function.

`def untargz_file(file, dest_dir=get_data_dir(),name=None):
  if name is None:
    name = file	
  tar = tarfile.open(name)
  tar.extractall(path=dest_dir)
  tar.close()`
Would someone be able to test on linux and python not 3.6?

**Comment by rbharath** [comment]
@Dgelemi Submit a PR? This looks like it could potentially be a good fix and we can let Travis run the test for us.

**Comment by Dgelemi** [comment]
ok, I can try. Never done it before, so I'll try not to break anything :)

**Comment by bitcrazed** [comment]
Hey @JimSEOW. Was referred to this thread: I am a PM at Microsoft for WSL.

Just wanted to make clear a few things that may help you: 

1. WSL only supports running ELF-64 (x84) binaries natively
1. WSL doesn't yet support CUDA/openCL GPU offload. If GPU computation is important, you'll likely want to port DeepChem to run in Windows where it can take full advantage of low-level GPU computation offload.
1. This said, WSL does enable interop - you can invoke Windows .exe's from within WSL if you want. This way you MIGHT be able to create a hybrid system that calls/invokes some stuff in Windows, and other stuff in Linux ... if that helps ;)

**Comment by rbharath** [comment]
@bitcrazed Welcome to DeepChem and thanks for the comments! Would love to see DeepChem running in Windows :)

**Comment by bitcrazed** [comment]
Many thanks @rbharath. Happy to help if we can; do ping me if you bump into further issues.

**Comment by rbharath** [comment]
I've marked this as a good first contribution. If you'd like to take on this issue, please do the following:

- Attempt to install DeepChem in Windows Subsystem for Linux
- If installation works, please submit a PR that updates our documentation and notes that the installation is possible.
- If installation does not work, debug the issue and create PR that makes the necessary changes and updates our documentation accordingly.

If you're interested in taking on this PR, please leave a comment here and raise a pull request marked [WIP] that tracks your on-going implementation efforts.

**Comment by VIGS25** [comment]
@rbharath : Update on the same:

1. Installed DeepChem in the Windows Subsystem for Linux and the installation part went through smoothly
2. Ran all the tests and two of them failed. (Error Message below)

======================================================================
FAIL: test_weave_regression_model (deepchem.models.tensorgraph.models.test_graph_models.TestGraphModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vignesh/deepchem/deepchem/models/tensorgraph/models/test_graph_models.py", line 201, in test_weave_regression_model
    assert all(s < 0.1 for s in scores['mean_absolute_error'])
AssertionError:
-------------------- >> begin captured stdout << ---------------------
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
computed_metrics: [0.05014588440102095, 0.13715766552735403]

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Test training a policy for the roulette environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vignesh/deepchem/deepchem/rl/tests/test_mcts.py", line 73, in test_roulette
    assert action_prob.argmax() == 37
AssertionError

----------------------------------------------------------------------
Ran 534 tests in 660.393s

FAILED (failures=2)

3. I had also installed this on my other machine running Linux today and the test titled, Test training a policy for the roulette environment, had failed there as well.

**Comment by peastman** [comment]
I think those are both just stochastic tests that occasionally fail.  They probably don't indicate any problem with the installation.

**Comment by JimSEOW** [comment]
As it is now possible to install Anaconda's Deepchem 2.1.0 in Windows 10's WSL, I close this issue.

Great effort to the Deepchem community and the latest push to bring DeepChem to Windows.
