### ISSUE TITLE
Implement "Set2Set" as a Graph Gather Layer

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#600]
The google paper [Neural Message Passing for Quantum Chemistry ](https://arxiv.org/pdf/1704.01212.pdf) discusses in results that using [set2set](https://arxiv.org/pdf/1511.06391.pdf) gave a very large performance boost on Graph Convolution Neural Networks.

Implementing this as a Graph Gather Layer would mean we could use it for all of our Graph Convolution Variant Models.

**Comment by lilleswing** [comment]
![selection_009](https://user-images.githubusercontent.com/1225605/27188318-c4a5e24e-51bb-11e7-9acc-b9969fadab86.png)

**Comment by rbharath** [comment]
+1. Glad to see this happen!

**Comment by rbharath** [comment]
Btw, the one-shot models use essentially a variant of set2set. It might be possible to adapt that code over for these purposes.

**Comment by patrickhop** [comment]
would love to see this happen

**Comment by rbharath** [comment]
I believe this was implemented by @miaecle already.
