### ISSUE TITLE
Is cuDNN not installed on the current Dockerfile?

### ISSUE THREAD

**Issue by relutropy** [deepchem/deepchem#605]
I think that cuDNN is not installed in the current Dockerfile/Docker image.
It is necessary to modify Dockerfile as follows.

In dockerfile
Now
`FROM nvidia/cuda`
New
`FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04`
or
`FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04`

https://hub.docker.com/r/nvidia/cuda/

**Comment by rbharath** [comment]
@relutropy Thanks for reporting this.

@lilleswing Is there perhaps a way we could add in a cudnn reference without specializing to Ubuntu 16.04?

**Comment by peastman** [comment]
If you install Tensorflow with conda instead of pip, it automatically brings in cuDNN.

**Comment by lilleswing** [comment]
Yeah I'm ok with installing tensorflow from conda.  When I created the script tensorflow-gpu didn't exist in conda.

https://github.com/deepchem/deepchem/pull/607

Is there some test you want us to do on the docker container to check if cuDNN is installed @relutropy?  We can add it to the dev release notes to test for it.

**Comment by lilleswing** [comment]
Also side-note with DeepChem's current utilization it doesn't matter too much whether cuDNN is installed or not.

**Comment by relutropy** [comment]
In order to use Tensorflow-gpu, it seems that CUDA and cuDNN v 5.1 need to be installed. Even in Docker 's container, even in a pure computer.

It seems appropriate that CUDA and cuDNN are prepared in containers beforehand.
Even if you use a pure computer, not only in the container, it seems necessary to have an environment where CUDA and cuDNN are installed first.

Therefore, it seems that you will use the Docker image which nvidia has released.
Even the official tensorflow-gpu Docker image is as follows.

FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu

In an environment where CUDA and cuDNN are installed, Tensorflow is installed.
I think it would be nice to do the same.

**Comment by proteneer** [comment]
I've tested tensorflow-gpu without cudnn before and it works fine. Some of the ops won't be as fast, but they happen to be not too important for many of our models.

**Comment by relutropy** [comment]
If cuDNN is already in the current Docker image, about that point ごめんね🙏

**Comment by relutropy** [comment]
Try the Docker build test with the Dockerfile that changed only the first line.
The effect by installing cuDNN seems to have been better than ever.
