### ISSUE TITLE
Logic flow

### ISSUE THREAD

**Issue by evanfeinberg** [deepchem/deepchem#61]
There are some possibly superfluous divisions in the API that may expose too much of the underlying code and file handling to the user. As a concrete example, we often featurize with a line like:

```
feature_files = featurizer.featurize(input_file, self.feature_dir)
```

and then immediately after create an instance of ```FeaturizedSamples```, e.g.,:

```
samples = FeaturizedSamples(samples_dir=self.samples_dir, featurizers=featurizers, 
                                dataset_files=feature_files,
                                reload_data=False)
```
I propose we do this in one fell swoop, and make featurizer.featurize() return an instance of object FeaturizedSamples(). Exposing the list ```feature_files``` to the user is likely unnecessary, as it's never used once ```FeaturizedSamples()``` is called.

**Comment by evanfeinberg** [comment]
This seems to be implemented and passing tests in the WIP PR in my fork.

**Comment by rbharath** [comment]
Going to close this since it's now in `master`
