### ISSUE TITLE
Deprecation warnings from sklearn

### ISSUE THREAD

**Issue by cfperez** [deepchem/deepchem#610]
Using Docker image, on running benchmark I get:
```
miniconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: T
his module was deprecated in version 0.18 in favor of the model_selection module into which 
all the refactored classes and functions are moved. Also note that the interface of the new 
CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/miniconda/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This m
odule was deprecated in version 0.18 in favor of the model_selection module into which all t
he refactored classes and functions are moved. This module will be removed in 0.20.
```

**Comment by hfxfroi** [comment]
you can try this : 
first, pip uninstall scikit-learn   
then, pip install scikit-learn==0.17.1

**Comment by rbharath** [comment]
Let's fix this issue so we can use the standard scikit-learn.

@lilleswing: Do you have a sense of how tricky this one is?

**Comment by mwojcikowski** [comment]
The `sklearn.cross_validation` is deprecated. We should use `sklearn.model_selection` instead. AFAIK `GridSearchCV` and `train_test_split` API is the same, so switching the import source should do the trick.

**Comment by rbharath** [comment]
@mwojcikowski Thanks for the pointer! This sounds like a quick fix then.

PRs welcome for this one! Sounds like a good quick fix for new contributors

**Comment by lilleswing** [comment]
@mwojcikowski is this fixed now?

**Comment by lilleswing** [comment]
Closing as we have not seen the warning recently and we can no longer find the cross_validation import.
