### ISSUE TITLE
Is it supposed be _add_layer or add_layer in TensorGraph?

### ISSUE THREAD

**Issue by alphaCTzo7G** [deepchem/deepchem#614]
The function _add_layer is defined in https://github.com/deepchem/deepchem/blob/4a96d6d121e85cb747a1a1ff10bdbae5571d4c0a/deepchem/models/tensorgraph/tensor_graph.py.

However most of the function calls are based on add_layer (without a preceding underscore)

1. https://github.com/deepchem/deepchem/blob/6959cf0f405628edb04247a9109483fa54b63d49/deepchem/models/tensorgraph/models/robust_multitask.py
2. https://github.com/deepchem/deepchem/blob/757c59135056bb7f2a021ff4e2740423e514dd77/docs/using_tensorgraph.md
3. https://github.com/deepchem/deepchem/blob/6959cf0f405628edb04247a9109483fa54b63d49/deepchem/models/tensorgraph/models/robust_multitask.py
4. https://github.com/deepchem/deepchem/blob/4c18f1130594dceb66831c229b3440b8e9f386c8/examples/tensorgraph/mnist.ipynb

Is the function name supposed to be _add_layer (with a preceding underscore) or add_layer (without a preceding underscore)? there doesnt seem to be another place where this function is defined..

So I am guessing its a typo and it should be add_layer in tensor_graph.py?

**Comment by rbharath** [comment]
In this case, I believe it's not a typo. This is a helper method present
only in the super class TensorGraph. Note the differing content of this
method versus the downstream add_layer

@lilleswing: Is my analysis correct?

**Comment by lilleswing** [comment]
@dibyadeeppaul TensoGraph#_add_layer is indeed supposed to be a private method to TensorGraph.

You construct a graph of layers and tell TensorGraph about the graph via TensorGraph#add_ouput.  We than construct the DAG and call _add_layer to each layer in topological sort order.

**Comment by lilleswing** [comment]
@dibyadeeppaul do you have any other questions about the API or can we close this issue?

**Comment by rbharath** [comment]
Going to go ahead and close this issue.
