### ISSUE TITLE
a3c value update question

### ISSUE THREAD

**Issue by jadeshi** [deepchem/deepchem#619]
Just a quick question about the current value update scheme. I noticed that right now the value function is adjusted using just the difference between the reward and the estimated current state value, R - V(s). Why isn't it using the difference between the reward plus the discounted value of the next state, i.e. R + gamma * V(s') - V(s), per the Bellman equation?

**Comment by peastman** [comment]
In theory it could be implemented that way, but that isn't how it's done in any of the existing implementations I've seen (for example https://github.com/openai/universe-starter-agent/blob/master/a3c.py).  I don't know how well it would work in practice.

Remember that `R` is the *total* discounted reward from that step to the end of the rollout, not just the next single step reward, so the equation you gave isn't quite correct.

**Comment by jadeshi** [comment]
Okay I think I see. So would it be correct to interpret this as: excluding the last step of the rollout, when you actually observe a direct reward by winning or losing the game, the discounted reward at any step before that is basically the estimate for the value of the next state s', with the step reward being 0?

**Comment by peastman** [comment]
Rewards don't just come at the end of the game.  Depending on the task, there could be rewards at every step, or less often than that.  The discounted reward at any step is the sum of all rewards received from that step until the end, reduced by a discount factor.  That applies to one particular rollout.  The value function is the expectation value of the discounted reward.  So if you generate many rollouts all starting from the same state, their average reward is the value function for that state.  That's what you're trying to train an estimate of.

**Comment by jadeshi** [comment]
Right, I think we may be talking about the same thing. I was specifically referring to the reward scheme for a game like pong where the rewards aren't explicitly known until you win or lose, and in this case the discounted reward at each state per rollout would just be exactly the value estimate for that state.

**Comment by peastman** [comment]
Not quite.  In that situation, the discounted reward at that state would be different for every rollout, but the value estimate would be the same for every one.  The latter is the expectation value of the former.

**Comment by jadeshi** [comment]
Ah, I think I said that unclearly. To clarify, I meant that during every rollout, the discounted reward serves as an isolated per-rollout estimate of the value of the state, and then the value function is updated to move a little bit towards this estimate, and the difference between the per-rollout value estimate and the value function, the advantage, is also used to update the policy. As I understand it that's what the algorithm is doing. Is that right?

**Comment by peastman** [comment]
Correct.

**Comment by rbharath** [comment]
Going to close this issue since I think the original question has been answered. Feel free to re-open if not.
