### ISSUE TITLE
Add MoleculeNet wrappers for Factors/Kinase/UV datasets

### ISSUE THREAD

**Issue by LRParser** [deepchem/deepchem#630]
I recently ran python benchmark.py from examples/ using 1 K80 on a Amazon EC2 p2.xlarge instance. The benchmark failed after 18.5 hours with the following error:

```bash
Traceback (most recent call last):
  File "benchmark.py", line 1097, in <module>
    test=test)
  File "benchmark.py", line 179, in benchmark_loading_datasets
    featurizer=featurizer)
  File "/home/ubuntu/deepchem/examples/kaggle/kaggle_datasets.py", line 139, in load_kaggle
    shard_size=shard_size)
  File "/home/ubuntu/deepchem/examples/kaggle/kaggle_datasets.py", line 74, in gen_kaggle
    train_dataset = loader.featurize(train_files, shard_size=shard_size)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 197, in featurize
    shard_generator(), data_dir, self.tasks, verbose=self.verbose)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 440, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 174, in shard_generator
    self.get_shards(input_files, shard_size)):
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/save.py", line 98, in load_csv_files
    for df in pd.read_csv(filename, chunksize=shard_size):
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 609, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:7348)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/deepchem/examples/kaggle/KAGGLE_training_disguised_combined_full.csv.gz'
```

The time elapsed was:
real    1125m29.127s
user    1723m4.204s
sys     170m16.504s

This issue is to ensure that the /home/ubuntu/deepchem/examples/kaggle/KAGGLE_training_disguised_combined_full.csv.gz file is either made present before benchmarking, and if not to handle more gracefully.

**Comment by rbharath** [comment]
@LRParser Good catch! I think removing KAGGLE from the benchmark run is the right way to handle this for now.

PRs welcome for fix!

**Comment by LRParser** [comment]
Submitted a basic PR. The README.md format is nice since when you're browsing on Github, you start to learn what the datasets are. Can definitely use some help on this one as I'm still a novice - I'm mostly working on learning the project by mapping in my mind from the academic papers to code comments and creating docs as I go

**Comment by lilleswing** [comment]
@rbharath are there legal concerns with the kaggle dataset?  You already seem to be storing them in s3.  Why not lazily load them into the data directory?
https://github.com/deepchem/deepchem/blob/master/examples/kaggle/get_kaggle.sh
https://github.com/deepchem/deepchem/blob/master/examples/kaggle/kaggle_datasets.py

**Comment by rbharath** [comment]
@lilleswing There are no legal issues, and a lazy load would be a reasonable technical solution as well.

**Comment by agitter** [comment]
Are the other three Merck datasets (Factors, Kinase, UV) from your [new paper](http://pubs.acs.org/doi/abs/10.1021/acs.jcim.7b00146) also available in S3?  I saw `KINASE_datasets.py` loads three csv files but didn't know where to find those data files.

**Comment by rbharath** [comment]
Not yet. Will upload them soon.

**Comment by rbharath** [comment]
#949 points out that the Factors/Kinase/UV datasets still need to be added to moleculenet

**Comment by chao1224** [comment]
Can we expect the the other three Merck datasets (Factors, Kinase, UV) to be coming out soon?
Seem to be some very interesting datasets to try on.

**Comment by rbharath** [comment]
This one's on me. Ping me in a few weeks if I haven't taken care of it yet.

**Comment by chao1224** [comment]
Hey, just want to check in. @rbharath

**Comment by rbharath** [comment]
Haven't had a chance to write a MoleculeNet load function, but the datasets are online at:

https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/FACTORS_test1_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/FACTORS_test2_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/FACTORS_training_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/KINASE_test1_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/KINASE_test2_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/KINASE_training_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/UV_test1_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/UV_test2_disguised_combined_full.csv.gz
https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/UV_training_disguised_combined_full.csv.gz

Contributions welcome for adding simple `dc.molnet wrappers`. Will rename the issue to reflect that.

**Comment by VIGS25** [comment]
Working on this and #425. Should raise a PR in a couple of days. 
About the Cambridge Structural Database (#426), do I need some sort of license to be able to download the data?

**Comment by rbharath** [comment]
Great to hear you're working on the issues. For the CSD, I'd recommend writing a MoleculeNet loader function, but if the license prohibits automatic download of data, have the loader expect the user to have downloaded the data manually, and print an error string with instructions on how to download the needed data for users if the data isn't already downloaded.

**Comment by VIGS25** [comment]
@rbharath: A few questions:

1. For the UV dataset, the paper mentions 190 tasks, but the dataset contains tasks from 210-400 (both
inclusive) and that makes it 191 tasks. There's also a log TIC, but I am not sure if that is a task. 
For now, I have added them all.

2. Was about to write tests,  but  I couldn't find any for loading the datasets, just the one for test_molnet.

3. Also, I wasn't sure whether to add any transformers. The kaggle_datasets.py had the added transformers commented.
