### ISSUE TITLE
GRU layer with RL

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#639]
I want to use a TensorGraph GRU layer as part of a model for reinforcement learning.  It's not clear how to make that work.  I'm pretty sure it's going to need some modifications, but I'm not certain of the best way to do it.

The GRU layer doesn't expose its internal state in any way.  Every time you call `session.run()`, it reinitializes the state to all zeros, runs that batch through it, and throws away the final state.  But for RL, we call `run()` repeatedly to select the action for the next step, and we somehow need to be able to preserve that state from one step to the next.  Separately from that, we also sometimes call `run()` to evaluate the loss on a rollout, and in that case it is appropriate to reinitialize the state to zero for the start of the rollout.

How can we modify the GRU layer to make it work with this?

**Comment by peastman** [comment]
I've been studying how Tensorflow implements RNNs, and I think I see how this could work.  It will take some architectural changes to TensorGraph.

As I understand it, for each tensor defining the internal state of a recurrent unit (GRU has one, LSTM has two), we need three different tensors:

- A placeholder used to specify the initial state in the feed dict.  We need to create this and pass it to `dynamic_rnn()` as `initial_state`.

- A tensor that can be evaluated to get the final state of the recurrent unit.  This is created by `dynamic_rnn()`.

- A tensor defining an internal state that is all zeros.  This is created by calling `zero_state()` on the recurrent unit.

So here are the changes I suggest:

1. Add three new arrays to Layer: `rnn_initial_states`, `rnn_final_states`, and `rnn_zero_states`.  They'll get filled in when you call `create_tensor()` with `set_tensors=True`.  For all non-recurrent layers, these will be empty.

2. When `build()` is called on a TensorGraph, it will collect up those arrays and build its own corresponding arrays with all the tensors from all recurrent layers in the graph.

3. For each of those tensors, `default_generator()` will include `feed_dict[initial_state] = zero_state`.

4. A3C can use those tensors to keep track of the internal states of any recurrent layers and either preserve them or clear them, as needed.

5. Of course this will cause yet more problems for pickling.  I suggest generalizing the current mechanism for dealing with that so that `none_tensors()` can clear and return an arbitrary list of tensors, not just the single output tensor.

**Comment by lilleswing** [comment]
@peastman none_tensors() was built for arbitrary lists of tensors -- you can see it in action already in InputFifoQueue, GraphConv and my CR for making the weave layers pickle-able.

Do we want to be explicit about the tensors we want to use?  Or would we rather store a list of tensors and then we know what they are for rnn type problems?

**Comment by peastman** [comment]
Ok, that's fine.  If the return value from `none_tensors()` can be an arbitrary list, that will work.
