### ISSUE TITLE
Splitter(splitter.py) "local variable 'directories' referenced before assignment"

### ISSUE THREAD

**Issue by DorisMai** [deepchem/deepchem#645]
I encountered `UnboundLocalError: local variable 'directories' referenced before assignment
` as I tried to do a k-fold split: 
```
    splitter = dc.splits.SingletaskStratifiedSplitter()
    train_dataset, valid_dataset, test_dataset = splitter.k_fold_split(dataset,5)
```

I don't understand what is directories and where should I pass value for this variable. I would really appreciate some help and explanation on it. The k_fold_split() function in the SingletaskStratifiedSplitter class does not take directories as a parameter: 

```
def k_fold_split(self, dataset, k, seed=None, log_every_n=None): 
     log("Computing K-fold split", self.verbose)
     if directories is None:
      directories = [tempfile.mkdtemp() for _ in range(k)]
     else:
      assert len(directories) == k
```

Would changing directories to self.directories fix the problem?

**Comment by lilleswing** [comment]
The implementation of SingletaskStratifiedSplitter is not fullfilling the k_fold_split interface of Splitter

```python
class Splitter(object):
  def k_fold_split(self, dataset, k, directories=None):

class SingletaskStratifiedSplitter(Splitter):
  def k_fold_split(self, dataset, k, seed=None, log_every_n=None):
```

We should make SingletaskStratifiedSplitter adhere to the interface and add a **kwargs to the interface.

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/647

**Comment by rbharath** [comment]
@DorisMai Thanks for the bugcatch!

@lilleswing Thanks for the rapid fix!

Going to close this issue since I think the issue has been resolved. @DorisMai you should be good once you pull from head. Feel free to raise a new issue if there are further problems
