### ISSUE TITLE
Change Coveralls Coverage Decrease Failure Threshold

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#648]
We are failing a lot of builds with very small changes in coverage.  Lets change the difference in coverage required to be within 1% of existing coverage.

![selection_042](https://user-images.githubusercontent.com/1225605/27965399-ab748d34-6309-11e7-8565-53d3c723c0ea.png)
1) Go to coveralls [website](http://coveralls.io)
1.5) Click on Deepchem Repo

![selection_043](https://user-images.githubusercontent.com/1225605/27965402-ad793152-6309-11e7-8c36-2cef1a47a7fe.png)
2) Click on Settings

![selection_044](https://user-images.githubusercontent.com/1225605/27965404-afc22a54-6309-11e7-8462-f2fc563b9b4b.png)
3) Change value to 1%

@rbharath you own the coveralls so you have to be the one to change these settings

**Comment by peastman** [comment]
Also, I don't think the numbers it reports have much to do with reality.  I've seen cases where it reports that a PR decreased the coverage, then when it gets merged it reports that same PR increased the coverage.  I'm not sure what exactly it's reporting, but I don't think it's what we intend it to be reporting.

**Comment by rbharath** [comment]
Agreed that it's worth making the coverage failure more robust. Increased threshold to 1%.
