### ISSUE TITLE
TensorGraphMultiTaskRegressor(fcnet.py) Import error and Attribute error

### ISSUE THREAD

**Issue by DorisMai** [deepchem/deepchem#649]
When I run this line:
`from deepchem.models.tensorflow_models.fcnet import TensorGraphMultiTaskRegressor`, I encountered 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TensorGraphMultiTaskRegressor'
```

When I try to build a model:
`model = dc.models.TensorGraphMultiTaskRegressor(1,1024)`, I encountered 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'deepchem.models' has no attribute 'TensorGraphMultiTaskRegressor'
```

Is it possible that there are circular imports for TensorGraphMultiTaskRegressor?

**Comment by rbharath** [comment]
@DorisMai The same import and construction seems to work on my system:

```
In [1]: import deepchem as dc
Warning: No xgboost installed on your system
Attempting to run %s will throw runtime errors
/home/rbharath/deepchem/deepchem/models/tensorgraph/layers.py:1040: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (self.batch_size > 1, "graph_gather requires batches larger than 1")

In [2]: from deepchem.models.tensorflow_models.fcnet import TensorGraphMultiTaskRegressor

In [3]: model = dc.models.TensorGraphMultiTaskRegressor(1,1024)

In [4]: 
```

Perhaps a bug in your install?

**Comment by DorisMai** [comment]
I don't quite understand. I can successfully import TensorflowMultiTaskRegressor which is from the same file fcnet.py as TensorGraphMultiTaskRegressor.  Do you have any suggestion on what bug it might be and what I should do?

**Comment by rbharath** [comment]
Could you post the full script you're trying to run and the full error message here?

**Comment by DorisMai** [comment]
Here's the full script and output messages.

Command:
```
import deepchem as dc
from deepchem.models.tensorflow_models.fcnet import TensorflowMultiTaskRegressor
```
Output message:
> /home/huanghao/anaconda3/envs/py35/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
>   "This module will be removed in 0.20.", DeprecationWarning)
> /home/huanghao/anaconda3/envs/py35/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
>   DeprecationWarning)

Command:
`model = dc.models.TensorflowMultiTaskRegressor(1, 1024)`
`from deepchem.models.tensorflow_models.fcnet import TensorGraphMultiTaskRegressor`
Output message:
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-5-d4c4e833e50c> in <module>()
> ----> 1 from deepchem.models.tensorflow_models.fcnet import TensorGraphMultiTaskRegressor
> 
> ImportError: cannot import name 'TensorGraphMultiTaskRegressor'

Command:
```
model = dc.models.TensorGraphMultiTaskRegressor(1, n_features=1024, layer_sizes=[800], dropouts=[.3],
    learning_rate=0.001, weight_decay_penalty=1e-4,batch_size=50,verbosity="high")
```
Output message:
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-7-d49bd4970234> in <module>()
> ----> 1 model = dc.models.TensorGraphMultiTaskRegressor(1, n_features=1024, layer_sizes=[800], dropouts=[.3],
>       2     learning_rate=0.001, weight_decay_penalty=1e-4,batch_size=50,verbosity="high")
> 
> AttributeError: module 'deepchem.models' has no attribute 'TensorGraphMultiTaskRegressor'

**Comment by rbharath** [comment]
I'm pretty stymied on this one. Does anyone else have thoughts?

CC @evanfeinberg

**Comment by peastman** [comment]
Are you sure you have the current version of the code installed?  That looks like you're just using an old version from before that class was created.

**Comment by DorisMai** [comment]
I used git pull origin master to update my files and I've checked that fcnet.py indeed has the new classes. But I still have this problem.

**Comment by peastman** [comment]
How did you install it?  Are you sure Python isn't picking up an old version somewhere?

Try this:

```Python
print(dc.models.tensorflow_models.fcnet.__file__)
```

That will tell you for sure what file it's using.

**Comment by DorisMai** [comment]
You are right. It is indeed picking up an old version: /home/huanghao/anaconda3/envs/py35/lib/python3.5/site-packages/deepchem/models/tensorflow_models/fcnet.py

The new file is actually in ~/deepchem/deepchem/models/tensorflow_models/fcnet.py

How can I make python use the new file? Do you have any suggestion on what to do with the old files after I git pull in the future?

**Comment by peastman** [comment]
You probably installed the old version by typing

```
python setup.py install
```

If you type that again, it will install the new version in its place.  Alternatively, you can type

```
python setup.py develop
```

That will tell it to use the versions of the files in your source tree, so whenever you pull new changes from github it will see them automatically.

**Comment by evanfeinberg** [comment]
Thank you, @peastman and @rbharath! and +1 to installing in ```develop```
mode!

**Comment by DorisMai** [comment]
Thank you @peastman, @rbharath, and @evanfeinberg! I used `python setup.py develop` and now all problems are fixed.

**Comment by rbharath** [comment]
Awesome, glad to hear this was worked out!
