### ISSUE TITLE
Saving the model to use for prediction

### ISSUE THREAD

**Issue by mkputul** [deepchem/deepchem#650]
Dear All,

How do we save a model to use for predictions? For example, I ran delaney_tf_models.py in example folder. I see that there is a model.save() command but it does not produce anything. 
I apologize if my question is simple as I am a newbie in using deepchem and tensorflow. 

Thanks

**Comment by rbharath** [comment]
This is a good question. The short answer is that you will need to use the TensorGraph graph convolutions. There are multiple backends for graph convs. The earlier ones unfortunately can't be saved. We're gradually moving towards making TensorGraph the default, but are still debugging and adding conveniences.

**Comment by mkputul** [comment]
Thank you for your response. While I was trying, I could save the transformers and datasets to a folder using save_dataset_to_disk command from utils.save. So I wanted to load the model using model.predict(datasets, transformers). Is this the right way to do it, because I got the following error:

model.predict(datasets, transformers)
  File "/home/mk/anaconda2/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorflow_models/__init__.py", line 519, in predict
    for (X_batch, _, _, ids_batch) in dataset.iterbatches(
AttributeError: 'tuple' object has no attribute 'iterbatches'

**Comment by rbharath** [comment]
Could you put together a short script that exhibits this failure (ideally < 30 lines) and post it on this issue?

**Comment by mkputul** [comment]
**As I am not a professional programmer, I was not sure how to put this together to make it short (since the data was trained and and saved on local disk, and then loaded via another script) . But here is what I did. I first trained model using following code (It is deleany code with small edit- You will need the delaney_dataset.py as well.)**
------------------------------------------------------------------------------------------------------
"""
Script that trains multitask models on Delaney dataset.
"""
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals
import os
import shutil
import numpy as np
import deepchem as dc
from delaney_datasets import load_delaney
import deepchem.utils.save
from deepchem.utils.save import save_dataset_to_disk
np.random.seed(123)
n_features = 1024
delaney_tasks, delaney_datasets, transformers = load_delaney()
train_dataset, valid_dataset, test_dataset = delaney_datasets
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score, np.mean)
model = dc.models.TensorflowMultiTaskRegressor(
    len(delaney_tasks), n_features, layer_sizes=[1000], dropouts=[.25],
    learning_rate=0.001, batch_size=50, verbosity="high")
model.fit(train_dataset)
model.save()
print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)
print("Train scores")
print(train_scores)
print("Validation scores")
print(valid_scores)
save_dataset_to_disk("./", train_dataset, valid_dataset, test_dataset, transformers)
--------------------------------------------------------------------------------------------------------------------------
**It will save the dataset and transformers in current directory. Then, I prepared another script and thats where I get the error:**

--------------------------------------------------------------------------------------------------------------------

"""
Script that plan to load and predict.
"""
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals
import pickle 
import os
import shutil
import numpy as np
import deepchem as dc
from delaney_datasets import load_delaney
import deepchem.utils.save
from deepchem.utils.save import load_dataset_from_disk
np.random.seed(123)
n_features = 1024
delaney_tasks, delaney_datasets, transformers = load_dataset_from_disk("./")
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score, np.mean)
model = dc.models.TensorflowMultiTaskRegressor(
    1, n_features, layer_sizes=[1000], dropouts=[.25],
    learning_rate=0.001, batch_size=50, verbosity="high")
model.predict(delaney_datasets, transformers)

**Comment by patrickhop** [comment]
This code works, and should work across the tensorgraph family.

As for the older models, I assume it's hit or miss?

```
"""
Script that trains weave models on delaney dataset.
"""
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals

import numpy as np
np.random.seed(123)
import tensorflow as tf
tf.set_random_seed(123)
import deepchem as dc

# Load Delaney dataset
delaney_tasks, delaney_datasets, transformers = dc.molnet.load_delaney(
    featurizer='GraphConv', split='random')
train_dataset, valid_dataset, test_dataset = delaney_datasets

# Fit models
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score, np.mean)

n_atom_feat = 75
n_pair_feat = 14
# Batch size of models
batch_size = 48
n_feat = 128

model = dc.models.GraphConvTensorGraph(
    len(delaney_tasks),
    batch_size=batch_size,
    learning_rate=1e-3,
    use_queue=False,
    mode='regression',
    model_dir='models')

# Fit trained model
model.fit(train_dataset, nb_epoch=2)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)

model.save()
model = model.load_from_dir('models')
valid_scores = model.evaluate(valid_dataset, [metric], transformers)
```

**Comment by mkputul** [comment]
Thank you Patrick. It works for me as well. 
Bests,

**Comment by rmurphy2718** [comment]
How do you actually save the model to a specific file?  If I train two models A and B, how do I load B when desired?
