### ISSUE TITLE
Get rid of yapf

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#657]
Can we switch to some other formatter instead of yapf?  I really really dislike it.  To begin with, it produces horrible looking code.  Here's an example from a file I just checked in.  I wrote a simple, readable line of code:

```Python
advantages[j-1] += self.a3c.discount_factor * self.a3c.advantage_lambda * advantages[j]
```

But here is how yapf decided to reformat that:

```Python
advantages[
    j -
    1] += self.a3c.discount_factor * self.a3c.advantage_lambda * advantages[
        j]
```

Seriously???  That looks like something someone would write as a joke.

I could live with that if it weren't for a bigger problem: it doesn't produce consistent results.  Although I'm running exactly the same version of yapf on my computer as what's on travis, it still sometimes produces different results.  Every @#$% time I make a change to layers.py and run yapf, I then have to go in and manually fix a few lines that yapf has changed, but that will cause travis to fail if I don't put them back again.

**Comment by lilleswing** [comment]
We are two version behind on yapf

https://github.com/google/yapf/releases
https://pypi.python.org/pypi/yapf/0.16.2

Maybe they fixed some bugs in between the versions?

**Comment by rbharath** [comment]
Switching to later versions of yapf sounds like a good first step.

Are there any other good python formatters?

**Comment by mpharrigan** [comment]
The pycharm built-in formatter is excellent, but I don't think you can run it standalone

**Comment by rbharath** [comment]
Going to close this issue since I think we're sticking with `yapf` for the time being, despite its issues. Feel free to re-open if there's good alternatives we can use.

**Comment by j-adamczyk** [comment]
@rbharath [black](https://github.com/psf/black) is currently the most commonly used code formatter, and it gives very consistent and nice-looking results from my experience. It is very actively maintained by Python Software Foundation, and has been adopted by several large projects, e.g. Django. Maybe DeepChem could switch to it? I could work on this.

**Comment by rbharath** [comment]
Responding on an old issue, it would be interesting to experiment with black, but probably too early for us to make a call on whether black could be a fit for us until we get more data
