### ISSUE TITLE
Custom features

### ISSUE THREAD

**Issue by mkputul** [deepchem/deepchem#663]
Dear All,

Is there a way to train a model using multiple features where one of the features be the GraphConv or ECFP and others be other properties such as molecular weight or  heavy atom count or etc. ?
I can see that the user defined features are used as an example in "bace" (although it does not work in my PC), but I would like to have one of the features as ECFP or GraphConv in addition to other features. 

Thank you for your time and efforts.

**Comment by sacombs** [comment]
For the graph convolution method, I added a virtual atom with properties on
it. I have tinkered around with making a custom graph method that encodes a
separate convolution for molecule descriptors, but I haven't made much
progress on this yet.

Steven combs

**Comment by mkputul** [comment]
Thanks Steven. Could you please elaborate on how you made the virtual atom?

**Comment by rbharath** [comment]
For the ECFP version, you should be able to use a `Concat` layer with `TensorGraph` to combine multiple feature types.

**Comment by mkputul** [comment]
Thank you Bharath . So I added another feature to ECFP by converting my temperature to a binary. Therefore, the size of fingerprint increased from 4096 to 4106 (10 bit representation of temperature). However, the issue is that when I want to assign the new fingerprint (with size 4106) to `dataset.X`, it raises an attribute error: `AttributeError: can't set attribute`.  Here is small part of code I am working with and `Y` is the fingerprint with size 4106 bits.

```
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles", featurizer=featurizer)
dataset = loader.featurize(dataset_file, shard_size=8192)
dataset.X = np.copy(Y)
```


Thanks for helping.

**Comment by rbharath** [comment]
You want to make a new dataset object. Try `new_dataset = NumpyDataset(Y, dataset.y, dataset.w, dataset.ids)`

**Comment by mkputul** [comment]
Thanks Bharath. The issue is solved.

Bests,
