### ISSUE TITLE
Submanifold Sparse Convolutional Networks

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#672]
https://arxiv.org/abs/1706.01307
https://github.com/facebookresearch/SparseConvNet 

New paper from Facebook for dealing with sparse, volumetric data. Comes with some nice PyTorch code too! This could be a very useful paper for analyzing binding pockets featurized volumetrically (`grid_featurizer` does this already).

PRs adding submanifold sparse models to `contrib/` welcome!

**Comment by evanfeinberg** [comment]
Been waiting for this for a while, ever since the author's first papers on
this (e.g., https://arxiv.org/abs/1505.02890).

**Comment by sinhasam** [comment]
I can take a look at this one! I have read the paper, and followed the work and it sounds really interesting. @rbharath

**Comment by rbharath** [comment]
Sounds good! PRs adding submanifold sparse networks to contrib/ would be very welcome.

**Comment by sinhasam** [comment]
I will be developing the models in Tensorflow, right?

**Comment by rbharath** [comment]
I'd recommend using the PyTorch implementation (no need to reinvent the wheel)

**Comment by sinhasam** [comment]
So the requirement is to develop the Sparse nets in PyTorch and then write a DeepChem wrapper?

**Comment by rbharath** [comment]
I'd recommend wrapping or adapting facebook's PyTorch code into DeepChem

**Comment by rbharath** [comment]
I'm going to close this issue since it looks like a very involved port, especially since we've decided to go all-in on TensorFlow instead of PyTorch for the time being.
