### ISSUE TITLE
Resuscitate deepchem.io site?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#673]
The documentation site is broken currently (the javascript isn't working, and everything is out of date).

Are there any volunteers who want to help resuscitate the website?

If I can't find volunteers, I'm considering closing down the site for the time being. Better to have people come to the github rather than a broken docs site.

**Comment by lilleswing** [comment]
I think the github + gitter is better with our current velocity.

**Comment by rbharath** [comment]
Working on fixing up deepchem.io. This will take some time, so the main site is now down. Hope to have it back up by the end of the week.

Docs can still be viewed at:

deepchem.io.s3-website-us-west-1.amazonaws.com

**Comment by rbharath** [comment]
https://deepchem.io should be back up again. We'll be working on adding more content up there soon.
