### ISSUE TITLE
Move TensorFlow to lazy imports?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#678]
I get lots of requests from people to use DeepChem without TensorFlow as a strict requirement. How hard would it be for us to make TensorFlow a lazy imports like xgboost?

**Comment by lilleswing** [comment]
I can do this -- it is literally just a find/replace

**Comment by lilleswing** [comment]
I also think pytorch should be lazy

**Comment by lilleswing** [comment]
After I do this there are no guarantees on what works though.... the real work is defining a minimum set of what we want to work without TF and then having someone write tests for it (probably on jenkins).  I would recommend before we ship it as "not needing tensorflow"

**Comment by rbharath** [comment]
Let's leave this one rest for a while. It sounds like there would be some nontrivial engineering work required to do this in a stable fashion. I'm going to close this issue for now, but might re-open at a later date if it becomes more important.

**Comment by lilleswing** [comment]
I wouldn't declare it engineering work -- more "product" work.  What is the user experience we expect for people without Tensorflow.  Being able to run sci-kit learn based models, being able to create datasets.  I think we are actually quite close if not having solved these issues.

We can also lazy load and provide "as is", but I don't think that is a good solution as why even bother installing DeepChem if you can't have the latest state of the art models?

Also the answer will soon be just be to buy Schrodinger Suite :) (We expect to ship DeepChem 1.2 with suite 17-3 released in late august).

**Comment by rbharath** [comment]
Great, to hear DeepChem will be part of Schrodinger's suite. Any chance we can get a press release with a shout out to DeepChem? :-)
