### ISSUE TITLE
Replace shell drop wget with requests commands

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#687]
Use the [requests](https://github.com/requests/requests) library instead of shell dropping to wget.  wget doesn't exist on all systems (it doesn't even come default on osx).  This will help us get to be more cross platform.

examples
https://github.com/deepchem/deepchem/blob/ea879e410d27a833f7dd635164157889153c9a79/deepchem/molnet/load_function/chembl_datasets.py
https://github.com/deepchem/deepchem/blob/367bea14cab47b1093bf106e0c196bb02d55c755/deepchem/dock/tests/test_pose_scoring.py

This is a good first task for someone who wants to get to know the codebase!

**Comment by mpharrigan** [comment]
gah never use os.system. use subprocess if you have to! If you (or a malicious 3rd party) sets an environment variable `DEEPCHEM_DATA_DIR` to something like `; rm -rf /` you could do damage!

**Comment by rbharath** [comment]
Fixed by #802 so closing.
