### ISSUE TITLE
Using Labels on Github for Issues

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#691]
A pain point I see for new developers of DeepChem is not knowing where to start.  I think we can use Labels to help with problem.  I want to add and use the following label.

\[paper-port\]

@rbharath is great at looking through current research in ML and computational chemistry and proposing ideas.  Some of these papers already have very clear interfaces and pieces built into DeepChem.  Other of these papers are completely new directions which require building a lot of new tooling.  I believe that by adding \[paper-port\] to issues which the team believes are "easier" ports which will immediately provide value would help new developers pick up a task and get onboarded.

Example tickets that I would want to apply the label to would be
https://github.com/deepchem/deepchem/issues/617
https://github.com/deepchem/deepchem/issues/616
https://github.com/deepchem/deepchem/issues/600
https://github.com/deepchem/deepchem/issues/503

**Comment by rbharath** [comment]
I'd be down for labels. There are a number of issues that [paper-port] would fit well. All the ones listed above (except #616, which I'd consider more involved) would be good.

Feel free to start adding [paper-port] labels where it makes sense!

**Comment by rbharath** [comment]
Closing this since we now have labels for new developers.
