### ISSUE TITLE
RDkit needs NumPy downgrade

### ISSUE THREAD

**Issue by RK900** [deepchem/deepchem#692]
RDkit is a package requirement for deepchem. However, when using `conda install -c rdkit rdkit`, the following prompt shows up:

```
The following packages will be DOWNGRADED:

    numpy:        1.12.1-py27_0               --> 1.11.3-py27_0 
```
It seems that numpy needs to be downgraded in order for rdkit to be installed.

**Comment by lilleswing** [comment]
yeah that sounds about right.  Conda is good about traversing the graph of dependencies and finding versions which fit everything.

We don't currently require any specific version of numpy but maybe we should pin it.

**Comment by rbharath** [comment]
Would there be any disadvantages to pinning to a Numpy version?

**Comment by lilleswing** [comment]
Nah we can pin it in scripts/install_deepchem_conda.sh

**Comment by rbharath** [comment]
I think this issue has been resolved.
