### ISSUE TITLE
training and prediction with generic (numerical array) inputs?

### ISSUE THREAD

**Issue by vmorozov** [deepchem/deepchem#695]
Hi,

Would be possible to use DeepChem methods (MuliTaskRegressor ones particularly)  for training and prediction with generic (numerical array) inputs. As far I can see from examples  the models require chemical compound datasets. Examples with generic input would be appreciated
Vlad

**Comment by rbharath** [comment]
Yes, all the DeepChem methods such as `fit()` and `predict()` accept dataset objects. `dataset.X` and `dataset.y` can be arbitrary numerical arrays.

I'd be glad to accept PRs adding numerical examples.

**Comment by rbharath** [comment]
Going to go ahead and close this issue. Feel free to reopen if there are further questions.
