### ISSUE TITLE
How to load the datasets based on example codes?

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#699]
Hi all,

I am brand new to DeepChem. So I am playing around with some example codes. I found I was not able to load some datasets. For example, in the example code "tox21_logreg.py"

When I run it, I got error from this line
"from tox21_datasets import load_tox21"
ImportError: No module named tox21_datasets

I am wondering how to get access to this datasets. I noticed there is a database folder in github. I also copied it to deepchem folder. But it was still not working.

Thanks,
Cheng

**Comment by rbharath** [comment]
Hi Cheng.

You need to run `tox21_logreg.py` from within the same directory it's located in (`tox21_datasets.py` is in the same directory).
