### ISSUE TITLE
Add Layer.shape

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#714]
When working with TensorGraph, I'm always getting confused about the shapes of different layers and trying to figure out how to reshape everything to get successive layers to match up.  It would be really helpful if each layer had a `shape` attribute I could query for its output shape.  Right now the best I can do is check the shape of its output tensor, but you can't do that until after the whole graph has been built, whereas I really want to do it as I'm creating the layers.

This would be pretty easy to implement, but it would have to be implemented separately for each Layer subclass.

**Comment by rbharath** [comment]
I'd be in favor of this addition. I do the same trick of checking shapes of layers as I'm building models and this could be quite useful in debugging.

**Comment by lilleswing** [comment]
@peastman do you propose each layer goes up the operation graph lazily when requesting the shape value, or eagerly in the Layer constructor?  I personally prefer lazy, and don't like doing work in Constructors -- but that could just be my Java background bias.

In order to Roll it out gradually we can have it throw a ValueError with the class name that needs to be implemented -- then if Developers wishes to use this feature she has to implement it on her own Graph.

If we implement this I would also want to add an additional check at the end of TG.build() which ensures that the layers which DO implement it are correct.  The added runtime overhead will be outweighed by the saved developer time for when Layer.shape is calculated incorrectly.

this idea SGTM

**Comment by peastman** [comment]
Good questions.  I was originally figuring it would compute it lazily, since usually it would never be requested.  But if TensorGraph is going to check it, then it will *always* be requested, so we might as well compute it in the constructor.

I agree this should be an optional feature.  It can throw a `NotImplementedError` if a particular layer doesn't implement it.

**Comment by peastman** [comment]
I can do an initial implementation of this.  I'll only do the layers where I'm sure I know what the output shape is supposed to be, though.

**Comment by peastman** [comment]
In the process of implementing this, I've been struck once again by an inconsistency in the API: we have two different mechanisms for indicating a dimension of unknown size.  When creating an input, you specify it as `None`.  When creating a `Reshape` layer, you specify it as -1.  This isn't really our fault, since TensorFlow has the same inconsistency.  But still it's ugly, and it wouldn't be hard to pick one or the other and do the necessary translations for talking to TensorFlow.

Even if we don't do that, we should at least pick one or the other for what `Layer.shape` will return.  I suggest:

- `Layer.shape` should always report `None` for dimensions of unknown size.
- We modify `Reshape` to accept `None` as well.  It can continue to accept -1 as well, if we want that for backward compatibility or consistency with TensorFlow.  But in our examples, we should generally try to use `None`.

**Comment by lilleswing** [comment]
@peastman numpy uses -1 and DOES NOT allow None. 

``` python
In [1]: a = np.zeros((10,2))
In [2]: np.reshape(a, (2,None)) 
TypeError: an integer is required
In [3]: np.reshape(a, (2,-1))
Out:
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
```
Since Numpy is more strict I think we should default to Numpy and default to -1, instead of None.  I have been doing this recently.

**Comment by peastman** [comment]
I'm sure that's why TensorFlow used -1 for `tf.reshape()`, since they wanted to be consistent with NumPy, even though they used `None` everywhere else.  But I think that was a mistake, because it doesn't really mean the same thing.  In NumPy, you're always working with arrays of known size.  Specifying an axis as -1 is just a shortcut.  You could easily compute the dimensions yourself, but you're allowed to be lazy and let NumPy compute it for you.

In TensorFlow, you're usually dealing with tensors where one dimension has unknown size.  When you specify `None` for one dimension of a placeholder, you aren't saying, "I'm being lazy so compute this for me."  You're saying, "This size is unknown and may be different for different batches."  And when you do a resize operation, the same is usually true.  It's impossible for you to compute the dimensions yourself because one of them is undefined.

Try this, for example:

```Python
a = tf.placeholder(tf.float32, [None, 5, 10])
b = tf.reshape(a, [-1, 50])
print(b.get_shape().as_list())
```

That prints `[None, 50]`.  That's just confusing.

**Comment by lilleswing** [comment]
Ok None sounds good to me then.

**Comment by rbharath** [comment]
I like the idea of standardizing around `None` as well.
