### ISSUE TITLE
PDBBind Dataset

### ISSUE THREAD

**Issue by hkmztrk** [deepchem/deepchem#715]
I failed to find the exact data set that's used in in this study (https://arxiv.org/pdf/1703.10603.pdf)
Could you please help me with that?

Thanks!

**Comment by lilleswing** [comment]
@hkmztrk are you looking for the featurized datasets with the atomicconv featurizer? These scripts will get you the featurized core and refined sets.
https://github.com/deepchem/deepchem/blob/master/contrib/atomicconv/acnn/core/get_acnn_core.sh
https://github.com/deepchem/deepchem/blob/master/contrib/atomicconv/acnn/refined/get_acnn_refined.sh

If you are looking for the raw dataset (protein/ligand co-crystallized pairs) you can use this script.
https://github.com/deepchem/deepchem/blob/master/examples/pdbbind/get_pdbbind.sh

**Comment by hkmztrk** [comment]
@lilleswing I was looking for the raw data set, thank you! It contains binding affinities of the pairs, right?

**Comment by hkmztrk** [comment]
Hello again,

Sorry if this is a trivial question!
I downloaded the raw data set, and I realized that (in general set for instance) there are three types of binding affinity types (Ki, Kd, IC50).  I remember reading Ki binding is predicted, so how do you deal with other types, do you convert them to Ki?
In PL general data there are total 11,987 complexes, but only 3650 complexes with Ki.

Thanks in advance.

**Comment by evanfeinberg** [comment]
Great question! Since they are closely related measures with the same units
we have been treating all three as identical when training many models.
However this is not universally recommended. For example an agonist will
have a very poor IC50 but a strong Kd

**Comment by hkmztrk** [comment]
Thanks for the clarification @evanfeinberg, about the units, they also seem to differ (nM, uM, mM etc.), which unit did you use? Does it matter which unit we convert them all? (e.g. all of them nM)

**Comment by rbharath** [comment]
All training is done in log-units (log-Kd/log-Ki/log-IC50). These are directly provided in the labels files for PDBBind.

**Comment by hkmztrk** [comment]
@rbharath what I mean is molar concentration unit, for instance, all three are Kd samples, but they have different molar concentrations (uM, mM, nM), do you perform a conversion among those?

3p9t	2.02	2011	6.20	Kd=0.63uM	3p9t.pdf	(TCL)
4ad2	2.10	2012	6.20	Kd=625nM	4acz.pdf	(GLC-IFM)
4qsw	1.80	2014	1.68	Kd=21mM	4qsw.pdf	(38T)

**Comment by evanfeinberg** [comment]
Yes, all are converted to units of Molar (i.e., 0.63 uM --> 6.3e-7 M) and
then -log10(value) is performed.

**Comment by hkmztrk** [comment]
thank you @evanfeinberg !

**Comment by evanfeinberg** [comment]
HTH!
