### ISSUE TITLE
Gaussian Process Hyperparameter Search

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#720]
`dc.hyper` now supports only a simple grid based hyperparameter search. Nonetheless, it still proves pretty useful for users getting new models off the ground and is featured prominently in our newly refurbished notebooks.

It would be great to put together a Gaussian process hyperparameter optimizer as a new feature for `dc.hyper`.

CC @miaecle

**Comment by patrickhop** [comment]
I've had a lot of luck with this codebase: https://github.com/hawk31/pyGPGO

Might be a good starting point for us.

**Comment by miaecle** [comment]
@rbharath I do have a simple GPGO optimization script for `run_benchmark` using the package pyGPGO(thanks to @patrickhop ), how should we merge in the package(lazy import maybe)?

**Comment by rbharath** [comment]
Merging in with lazy import would be a great idea.

**Comment by rbharath** [comment]
Implemented by #738 so going to go ahead and close.
