### ISSUE TITLE
How can I check the generated features for molecules?

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#722]
Hi all, 

I am quite interested in the deep.chem.feat module, and I want to compare different feature generation methods. I am wondering how could I run feature generation methods and print out the results? i.e. the input would be a molecule smiles, and the output wound be a vector or a matrix of features. I tried the following codes, but it can't display my generated features.

def load_dataset(dataset_file, featurizer='ECFP'):
  tasks = ['exp']

  if featurizer == 'ECFP':
    featurizer = dc.feat.CircularFingerprint(size=4096)
  elif featurizer == 'GraphConv':
    featurizer = dc.feat.ConvMolFeaturizer()
	
  loader = dc.data.CSVLoader(
      tasks=tasks, smiles_field="smiles", featurizer=featurizer)
  dataset = loader.featurize(dataset_file, shard_size=8192)
  
  return dataset
 
print (load_dataset(mol_file, featurizer='ECFP'))

Output:
<deepchem.data.datasets.DiskDataset object at 0x7f6fd264b7d0>

Thanks,
Cheng

**Comment by rbharath** [comment]
`dataset.X` contains the matrix of features.
