### ISSUE TITLE
Can't load tensorgraph.models.graph_models

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#742]
Hi all,

I tried some codes in deepchem example folder. I tried 
"deepchem-master/examples/tox21/tox21_tensorgraph_graph_conv.py".

However, I came across the error : 
from deepchem.models.tensorgraph.models.graph_models import GraphConvTensorGraph
ImportError: cannot import name GraphConvTensorGraph

Does anyone have the same problem as mine? Thank you

Cheng

**Comment by lilleswing** [comment]
@chf42 I would try rebuilding your environment.

``` bash
git clone https://github.com/deepchem/deepchem.git      # Clone deepchem source code from GitHub
cd deepchem
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
pip install tensorflow-gpu==1.2.1                       # If you want GPU support
python setup.py install                                 # Manual install
nosetests -v deepchem --nologcapture                    # Run tests
```

Note the difference between "install" and "develop" with setup.py
```python
# This copies the source/binaries into the python environment
# That means that if you update the git repo your python environment WILL NOT get the changes
python setup.py install

# This sym-links the source/binaries into the python environment
# That means that if you update the git repo your python environment will get the changes
python setup.py develop
```

**Comment by chf42** [comment]
Thank you, lilleswing! I will give a try soon, and to see whether I can fix it or not.

Cheng

**Comment by rbharath** [comment]
Going to go ahead and close this issue. Feel free to reopen if there are further problems.
