### ISSUE TITLE
The parameters in "dc.models.TensorflowMultiTaskClassifier"

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#744]
Dear all,

I am implementing fully-connected DNN using dc.models.TensorflowMultiTaskClassifier for classification problem. **General question**:  I am confused **how many hyperparameters in total that can be adjusted in this model** & **what are the exact meanings** for these parameters. I looked through deepchem.io documents, but couldn't find any description for this model. 

Some other **specific questions** related to the "dc.models.TensorflowMultiTaskClassifier":
1) **how to define n_features?** should I put as the length of descriptors for each compound? I noticed in example codes, if using "ECFP", n_features =1024 was adopted. I am wondering if I use a sequence of self-defined 100 descriptors, should I put n_features =100 instead?

2) I see we are allowed to add % of drop-out neuron for hidden layers via dropouts = [.25,.25,.25,]. I am wondering if there is any way to add drop-out to input layer in deepchem as well?

Thanks,
Cheng

**Comment by rbharath** [comment]
`n_features` is indeed the number of descriptors for each compound. If you use 100 self defined descriptors, you should set `n_features=100`.

I believe that adding drop-out to the input layer isn't feasible in `TensorflowMultiTaskClassifier`. You may want to use `TensorGraph` to build a custom model instead for this case.

**Comment by chf42** [comment]
@rbharath Thank you for quick response. A general question is that in TensorflowMultiTaskClassifier, how many hyperparameters are available? is there any document for that model? For example, can I change activation functions for each layer in TensorflowMultiTaskClassifier?

**Comment by peastman** [comment]
No, it hardcodes RELU as the activation function.  For more flexibility, TensorGraph is definitely the way to go.

Actually, TensorflowMultiTaskClassifier is basically deprecated and will probably get removed.  There's a replacement class called TensorGraphMultiTaskClassifier with a nearly identical API, but implemented in a much simpler way with TensorGraph.  You can see it here:

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorflow_models/fcnet.py#L25-L130

As you can see, the implementation is quite simple, and you could easily copy it and customize it however you want.

That said, we probably should add an option to TensorGraphMultiTaskClassifier for customizing the activation function.  That's a pretty standard thing to customize, so you shouldn't really have to write a new class just for that.

**Comment by rbharath** [comment]
+1 to the idea of adding activation as an option to `TensorGraphMultiTaskClassifier`.

This just merged notebook also gives a tutorial introduction to `TensorGraph` and might be useful:

https://github.com/deepchem/deepchem/blob/master/examples/notebooks/graph_convolutional_networks_for_tox21.ipynb

**Comment by chf42** [comment]
@peastman Thank you for your helpful comments. I will try TensorGraphMultiTaskClassifier and TensorGraph if more flexibility is required.

**Comment by chf42** [comment]
@rbharath Thank you Bharath. That is a good example I am looking for. I will go through that and implement it soon.

**Comment by chf42** [comment]
@peastman I tried TensorGraphMultiTaskClassifier as follows:
model = dc.models.TensorGraphMultiTaskClassifier(
	len(tasks),
	n_features,
	layer_sizes=[1000,1000,1000],
	weight_init_stddevs=[.02,.02,.02],
	bias_init_consts = [1.,1.,1.],
	weight_decay_penalty = 0.0,
	weight_decay_penalty_type="l2",
	dropouts=[.25,.25,.25],
	n_classes=2,
	learning_rate=0.001,
	batch_size=50,
	seed=5758)

However, I came across errors as : 
  **File "tgMultiTaskClassifier_models.py", line 28, in <module>
    seed=5758)
  File "/home/cfang/.conda/envs/deepchem_2.7/lib/python2.7/deepchem/models/tenso                                       rflow_models/fcnet.py", line 65, in __init__
    super().__init__(mode='classification', **kwargs)
TypeError: super() takes at least 1 argument (0 given)**

Would you help me double-check with that error? Thanks! Another related question is that in your fcnet.py code, you mentioned: "**In addition to the following arguments, this class also accepts all the keyword arguments from TensorGraph.**". I am not that clear what are those other keywords arguments from TensorGraph. Would you mind provide a link for that? Thanks!

Cheng

**Comment by peastman** [comment]
Looks like that's an inconsistency between Python 2 and 3.  I'll fix that...

**Comment by peastman** [comment]
Actually, I think you must have an old version of the code.  Here's what line 65 is in the current code:

```Python
    super(TensorGraphMultiTaskClassifier, self).__init__(
        mode='classification', **kwargs)
```

Update to the latest code and it should work.

**Comment by peastman** [comment]
> I am not that clear what are those other keywords arguments from TensorGraph.

You can find the relevant documentation at https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py.

**Comment by peastman** [comment]
I just posted a PR that adds the option for activation function: #751.

**Comment by chf42** [comment]
@peastman Thank you so much. I will update my source code with Deepchem and give one more try. 
I will check TensorGraph documents to find something useful.

**Comment by rbharath** [comment]
Going to go ahead and close this issue. Feel free to re-open if there are further bugs.
