### ISSUE TITLE
Thermodynamic Solubility

### ISSUE THREAD

**Issue by patrickhop** [deepchem/deepchem#747]
From what I understand, this is a thermodynamic solubility assay - should be much more interesting than Delaney.

https://www.ebi.ac.uk/chembl/assay/inspect/CHEMBL3301364

If there's interest, i'm happy to add this in.

**Comment by rbharath** [comment]
Yes, absolutely! PR welcome

**Comment by patrickhop** [comment]
@rbharath When implementing this, should I add a file to: https://github.com/deepchem/deepchem/tree/master/deepchem/molnet/load_function

Also, would you be able to host the file on S3?

**Comment by rbharath** [comment]
Yes, please add a file. Send me the datafile offline while we're reviewing the PR and I'll get it loaded onto S3.

**Comment by rbharath** [comment]
@patrickhop Wanted to give you a quick ping on this issue. If your schedule is looking tight, glad to mark this issue as open for contribution

**Comment by patrickhop** [comment]
I'm dropping in three datasets that I think are valuable.

Thermodynamic solubility (1743 examples) is interesting from a research perspective because it's quite hard to score high on this one, even though the assay is relatively low-noise. Scoring high on this dataset likely requires capturing something that we are not right now.

pKa-A1 and pKa-B1 are fundamental properties that if well predicted improve predictions on other tasks. They are considerably smaller though (~200 examples).

I emailed the datasets to @rbharath .

**Comment by rbharath** [comment]
Thanks @patrickhop!

I'm marking this issue as open for contribution. If you'd like to take on this PR, please get in touch with me (rbharath@x.y) where x=deepchem, y=io and I'll email you the datasets. Please start a pull request marked "[WIP]" adding functions to `dc.molnet` that load these datasets.

**Comment by VIGS25** [comment]
It looks like this issue is still open. Can I work on it if thats the case?

**Comment by rbharath** [comment]
Yep, go for it!

**Comment by VIGS25** [comment]
Hi @rbharath! Shot you an email for the datasets, based on the information above, but it said the address not found.

**Comment by rbharath** [comment]
Closing this issue since fixed in #1596
