### ISSUE TITLE
StarCraft Integration

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#749]
DeepMind has recently released a powerful set of StarCraft integration tools and python API that makes it possible to train RL agents on starcraft.

https://deepmind.com/blog/deepmind-and-blizzard-open-starcraft-ii-ai-research-environment/
https://github.com/deepmind/pysc2
https://deepmind.com/documents/110/sc2le.pdf

So far, reported results are only successful on mini-games, and global performance on starcraft play is quite mediocre. At the same time, signs are positive that StarCraft is the right next problem for reinforcement learning. It focuses scaling to larger move sets and move spaces, and requires handling of adversarial uncertainly.

We should start thinking about making a StarCraftEnvironment to work with `deepchem.rl`. This will let us reproduce future StarCraft driven RL results and let us test new algorithms on very challenging environments.

**Comment by evanfeinberg** [comment]
This is one of those moments, along with the release of the impossible
burger and self-driving cars, where one cannot help but think to oneself,
"we now live in the future.'

On Fri, Aug 11, 2017 at 1:53 PM, Bharath Ramsundar <notifications@github.com

**Comment by peastman** [comment]
Closely related news: OpenAI created a bot that can beat the top professional players at Dota 2.  https://blog.openai.com/dota-2/.  They don't give a lot of information about how it works, aside from the following: "The bot learned the game from scratch by self-play, and does not use imitation learning or tree search."  Presumably they'll be publishing more information soon.

> "we now live in the future.'

Dude, where's my flying car?

**Comment by rbharath** [comment]
I think this one is outside DeepChem's scope :)
