### ISSUE TITLE
Converting Models to TensorGraph

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#754]
#753 deprecates all non-`TensorGraph` TF models. A number of these models should be converted over to `TensorGraph` in time for the DeepChem 1.3 release.

- Molecular Autoencoder (Old classes `TensorflowMoleculeEncoder`, `TensorflowMoleculeDecoder`)
- Influence Relevance Voting (Old classes `TensorflowMultiTaskIRVClassifier`)
- Progressive Models (Old classes `ProgressiveMultitaskRegressor`).
- Bypass Models (Old classes `RobustMultiTaskClassifier`, `RobustMultiTaskRegressor`; Bypass models used to be called "robust")
- Logistic Regression (Old Classes `TensorflowLogisticRegression`)
- Matching Networks [one-shot] (Used `SupportGraphClassifier`)
- Iterative Refinement LSTM Networks [one-shot] (Used `SupportGraphClassifier`)

PRs are welcome for any of these networks.

**Comment by peastman** [comment]
What do you think about also removing "TensorGraph" from the names of the newer models?  So `TensorGraphMultiTaskClassifier` can become just `MultiTaskClassifier` etc.

**Comment by rbharath** [comment]
I'm a big fan! Less verbose class names are great.

**Comment by rbharath** [comment]
Going to close this issue since we've completed the transition (with the exception of the in-progress #1084).
