### ISSUE TITLE
How to implement one-shot learning with DeepChem?

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#757]
Dear all,

I am wondering how to implement one-shot learning in DeepChem? since I have low amount of data at hand.

In the "Low Data Drug Discovery with One-Shot Learning" paper, if I am correct, you were using LSTM (AttLSTM & IterRefLSTM)  or some others I wasn't aware of to achieve one-shot learning. Would you mind me some example to show how to use one-shot learning with DeepChem? 

Thanks,
Cheng

**Comment by rbharath** [comment]
https://github.com/deepchem/deepchem/blob/master/deepchem/models/tf_new_models/graph_models.py has SequentialSupportGraph which is the parent class for the one-shot models.

The one-shot layers are in https://github.com/deepchem/deepchem/blob/master/deepchem/nn/layers.py. ResiLSTMEmbedding and friends.

The low-data examples live in https://github.com/deepchem/deepchem/tree/master/examples/low_data

All of this code is deprecated though. We're working on converting this code to `TensorGraph` so one-shot models can be saved. We will put together an IPython notebook at that point.

**Comment by chf42** [comment]
@rbharath Thank you, Bharath. I will take a look at those.

**Comment by chf42** [comment]
@rbharath I went through your published "one shot learning in drug discovery" paper, as well as the codes in "low-data" example.  Here I have some specific questions. You might help me figure them out. 

1) I was not able to find IterRefLSTM (Iterative Refinement LSTM in your paper) model in your GitHub codes? I noticed you have added "dc.nn.ResiLSTMEmbedding" layer in "tox_res_one_fold.py" file. Is the residual LSTM identical to IterRefLSTM in your paper?

2) What does the n_feat (# of features on Conv-mols featurization) exactly mean? Should I change & how can I change when I am modeling my own data using Conv-mols featurization ? 

3) My last concern is about the Convolutional network architecture. In previous paper, you were using fixed architecture, leaving hyperparameter optimization to future work. I am just wondering how these dimensions for each layer are sensitive to the date size. Do you have general suggestions so far?

Thanks,
Cheng

**Comment by rbharath** [comment]
Good catch. Yes `dc.nn.ResiLSTMEmbedding` is the Iterative Refinement LSTM. We will rename when we convert this layer over to a `TensorGraph` layer.

`n_feat` is the number of per-atom descriptors used by the Conv-mol. You shouldn't change this if you're using `dc.feat.ConvMolFeaturizer()`.

I'd recommend using default settings, as in `dc.models.GraphConvTensorGraph` for hyperparameters on graph convs.

**Comment by rbharath** [comment]
Closing this issue since it refers to the old implementation (non TensorGraph). The TensorGraph implementation is being worked on https://github.com/deepchem/deepchem/pull/1084. Let's shift discussion of implementation issues there.
