### ISSUE TITLE
New TensorGraph predict/run API

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#761]
As https://github.com/deepchem/deepchem/pull/760 notes, the current `TensorGraph.predict()` and `TensorGraph.predict_proba()` methods have issues. It's not well defined what happens when there's more than one element of `self.outputs` and there are some confusing transpose operations.

Here's a proposed API update to `TensorGraph` to resolve these issues:

- Make `predict/predict_proba` work with only one specified output. `TensorGraph.predict(dataset, transformers, output=None)`. `output` can be passed in as a keyword argument, or else, will assert `len(self.outputs) == 1` and set `output = self.outputs[0]`. This method will return the call from `sess.run(output.out_tensor)`. We will remove the transpose operation.
- Add a general method `TensorGraph.run(dataset, transformers, outputs=None)`. This can either be passed a list of outputs, or set `outputs = self.outputs`. This method will return `sess.run([output.out_tensor for output in outputs]))`, that is, return a list of the fetched outputs. This could be useful for probing the structure of more complicated graphs (where we may want to inspect intermediate features learned by a graph conv for example).

This change should preserve backwards compatibility (I believe).

@lilleswing @peastman Would love your thoughts.

**Comment by lilleswing** [comment]
@rbharath I do like this API better -- but it does not preserve backwards compatibility.  
All of our multi-task evalutators rely on the current API.

**I am willing to make a breaking API change though.**  

The current state of affairs is confusing to reason about and can't support things like multi-tasking a regression and a classification problem.  Or multitasking a classification problem where each task has a different number of classes.

**Comment by peastman** [comment]
I wouldn't worry too much about incompatible changes, given some of the other things we're planning on changing (like eliminating a bunch of classes).

What exactly is the different between `predict()` and `run()`?  Is it just that `run()` can compute multiple outputs, while `predict()` computes only one?  That seems like a rather minor distinction to require two different methods.  Besides, there are a lot of `predict_*()` methods, and all of them might conceivably be applied to multiple outputs.

How about this behavior instead?  We add the `outputs` argument to all those methods.  It's interpreted as follows:

- If it's None, we assert there's only one output and then interpret it as if they had specified `outputs=self.outputs[0]`.
- If it's a single Layer or Tensor, we evaluate just that one and return the result as a single array.
- If it's a list of Layers or Tensors, we evaluate all of them and return the result as a list of arrays.

In both of the last two cases, you're allowed to specify arbitrary Layers or Tensors.  They don't have to be in the graph's list of outputs.

**Comment by rbharath** [comment]
I'm a fan of @peastman's proposed simplification. Let's have multiple options to `predict_*()` as outlined above.

I'll take a crack at this, starting from my closed PR #760.

**Comment by rbharath** [comment]
Closing since this issue was addressed in #763. We can reopen if there are further problems.
