### ISSUE TITLE
Is there a model zoo?

### ISSUE THREAD

**Issue by mostafachatillon** [deepchem/deepchem#764]
Are there ready-made models available?

In the 'examples' section, I found scripts to build models, but not models already trained.

**Comment by lilleswing** [comment]
We do not currently ship any pretrained models (With the exception of the molecule variational autoencoder).  We want to start shipping pre-trained models with DeepChem 1.3

See the conversation about pretrained models [here](https://github.com/deepchem/deepchem/issues/669#issuecomment-315941086).
