### ISSUE TITLE
Tutorial on creating new TensorGraph layers

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#779]
The process of creating a new `TensorGraph` layer is currently pretty un-documented. It's relatively easy to figure out how to create the raw layer, but the process of making it pickle-able (dealing with `set_tensors` and `none_tensors` in particular) needs more documentation.

This seems like a good topic for a new IPython notebook.

**Comment by nggih** [comment]
I would like to work on this issue.

**Comment by rbharath** [comment]
@nggih Great! Could you create a WIP pull request to track your implementation progress?

**Comment by nggih** [comment]
very sorry I am very new with git, did the WIP pull request created?

**Comment by rbharath** [comment]
Yep, looks good https://github.com/deepchem/deepchem/pull/1187

**Comment by nggih** [comment]
After reading the deepchem [Features](https://deepchem.io/docs/deepchem.models.tensorgraph.html#deepchem.models.tensorgraph.layers.Feature) documentation, I think I understand how the create_tensor works.
I got some questions, I believe I need to use `Feature(shape=(None, n))` as input layer? then we put the `x+2` layer, right?
For the `x+2` layer, should it be written as in this TensorGraph [example](https://github.com/hycis/TensorGraph), the 

>  'create a new model (layer) by subclass the BaseModel layer'?  

or do DeepChem have specific module for custom layer?

**Comment by rbharath** [comment]
TensorGraph has been deprecated so closing this old issue.
