### ISSUE TITLE
TensorGraph Layers with Multiple Outputs

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#780]
It currently appears that we don't support `TensorGraph` layers with multiple output tensors. This issues arises in #778, where the `LSTMStep` class natively returns `h, [h, c]`, where `h` and `c` are both tensors. Right now, there only exists `Layer.out_tensor` which has to be a single tensor.

Is there a good design fix to this limitation? 

CC @lilleswing @peastman

**Comment by rbharath** [comment]
Turns out `AttnLSTMEmbedding` and `IterRefLSTMEmbedding` also naturally return pairs of tensors as outputs.

**Comment by lilleswing** [comment]
```python
class IterRefLSTMEmbedding(Layer):
  # Stuff
  def create_tensor(self, in_layers=None, set_tensors=True, **kwargs):
    # Do stuff
    # self.out_tensor = c
    # self.h  = c
  def none_tensors():
    # Implement this so we can pickle

class PassThroughLayer():
  def create_tensor(self, in_layers=None, set_tensors=True, **kwargs):
    in_layer = in_layers[0]
    self.out_tensor = in_layer.h

def IterRefLSTMEmbedding(**kwargs):
  c = IterRefLSTMEmbedding(**kwargs)
  h = PassThroughLayer(in_layer=lstm)
  return [h,c]
```

Would be pseudo code for what I am thinking.

**Comment by rbharath** [comment]
This is a reasonable workaround, but it feels like we ought to be about to make a more general solution. If we had to return `[x, y, z]` from a layer, this particular solution wouldn't work.

Perhaps we can add `Layer.out_tensors`, which defaults to `[Layer.out_tensor]` if not explicitly set. Then `TensorGraph.build()` could be modified to use `Layer.out_tensors` by default.

**Comment by lilleswing** [comment]
I think that implementation would be a mistake.  Layers are the unit that
we compose to make computation graphs.  Think of the lstm example, we then
want to take those outputs and process them further.  If we create a single
layer with multiple outs we then need to put logic in downstream layers on
which out tensor to operate over.

I think the factory methods are a much cleaner option.  We can create tools
to make factory methods with pass through layers more painless.

**Comment by peastman** [comment]
I can see arguments for both, but overall I think Karl's approach will be simpler.  There's no fundamental difference between a layer with two outputs, and a pair of layers that take the same inputs and each produce one output.  It's just a question of what will be easier for users to work with.  It seems like this is an unusual situation.  Most layers only produce one output.  Given that, it's better to require a little extra work in the exceptional cases rather than require *every* layer to deal with the possibility that its inputs are producing multiple values.

**Comment by rbharath** [comment]
This argument makes sense to me. I like the idea of optimizing to make the common case simple. I'll give a crack at the factory method approach in the one-shot PR.

**Comment by rbharath** [comment]
I believe the factory methods have been implemented and stabilized already. Might be good to make a tutorial for this...

Going to close this issue for now.
