### ISSUE TITLE
Replace Autodock Vina with Quick Vina

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#781]
Our docking code currently uses AutoDock Vina. This results in our docking being quite slow, which in return causes deepchem-gui to be quite slow.

It might be good to replace AutoDock Vina with QuickVina2, which claims to have 20x speed improvements over autodock vina.

https://github.com/aalhossary/qvina

We would need to build qvina and host a built version on AWS to make this feasible.

**Comment by rbharath** [comment]
H/T Bryce Allen of SilconTx

**Comment by mwojcikowski** [comment]
Isn't the problem the I/O introduced by writing the ligand files instead of the software itself?

**Comment by Dgelemi** [comment]
There was a tool few years ago doing the same, speeding up Vina: idock https://github.com/HongjianLi/idock . The program itself doesn't seem to be maintained on the github, but vina latest version is from May 2011, so it shouldn't be a problem.

**Comment by rbharath** [comment]
IIRC, pose generation is indeed compute bound. Vina uses a genetic algorithm + search to find poses, which takes a lot of effort.

I'd be very open to PRs with faster pose generation if anyone is interested in taking this on :).

**Comment by laeeq80** [comment]
I am using autodock vina with apache spark and found the same problem. Reading single ligand has I/O problem so I modified it to read from stdin and write to stdout multiple ligands so that you can pipe from your software and get back to your software. https://github.com/laeeq80/vina

Searching google I reached your post. Now I thinking to modify Qvina2 for multiple ligands. Lets see how it goes.

**Comment by latticetower** [comment]
Hi, I would like to work on this issue

**Comment by rbharath** [comment]
@latticetower Great! Could you open up a WIP pull request to track your on-going implementation progress?

**Comment by rbharath** [comment]
Closing this old issue since it's not clear we want to use Quick Vina or even retain docking support in core DeepChem.
