### ISSUE TITLE
ANI training uses CPU for some tensordot op

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#787]
Looks like the ANI Symmetry functions use a tensordot:

```
      output = self.activation(
          tf.tensordot(inputs, self.W[i, :, :], [[2], [0]]) + self.b[i, :])
```

Which doesn't have a GPU implementation. https://github.com/tensorflow/tensorflow/issues/11619 confirms this. Will play around to see if we can do what they did and replace with einstein summation.

**Comment by rbharath** [comment]
Good find!

**Comment by rbharath** [comment]
Closing this old issue
