### ISSUE TITLE
setting data_shape manually

### ISSUE THREAD

**Issue by evanfeinberg** [deepchem/deepchem#79]
Currently, attribute ```data_shape``` is set manually by calling something like:

```model_params["data_shape"] = train_dataset.get_data_shape()```

We should implement a way that this happens automatically, as it is essentially the same for every model creation task.

**Comment by rbharath** [comment]
After some more thought, I think it's relatively harmless to have this in there. The issue is that model specifications depend on data shape, so data shape must be passed in somehow, and setting it in the `model_params` seems like a mostly pain-free way of making this happen.
