### ISSUE TITLE
TensorFlow 1.3 Upgrade

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#790]
We should upgrade to TensorFlow 1.3 in time for the DeepChem 1.3 release (#669). Are there any potential gotcha's that might cause issues?

**Comment by proteneer** [comment]
Things we've noticed:

1. requires

**Comment by lilleswing** [comment]
Yeah I'll upgrade as soon as tf-gpu hist conda-forge.

**Comment by danielfrg** [comment]
Right now we only have CPU versions of tensorflow on conda-forge.

**Comment by peastman** [comment]
Do we think this will happen soon?  I've come across a case where I'd really like to use a 1.3 API.  I can work around it, but that would take a bit of effort.  So if the move to 1.3 is imminent, I'll just use that API and wait a few days before checking it in.

**Comment by rbharath** [comment]
@peastman I'd lean towards going ahead and using the new API. I think we should move to 1.3 sooner rather than later barring large technical difficulties.

**Comment by rbharath** [comment]
Implemented by #852
