### ISSUE TITLE
Transforming data

### ISSUE THREAD

**Issue by evanfeinberg** [deepchem/deepchem#80]
In writing the tutorial, I realize another area that the older, command-line oriented style is clashing a bit with the newer, OOP style. I think transforms should be reorganized into classes as well. Perhaps a general Transformer() class from which Normalizer(), LogTransformer(), etc. might inherit. It is noteworthy that sklearn has a lot of nice preprocessing routines that we should be able to allow the user to take advantage of. This isn't urgent but should be taken care of at some point reasonably soon.

**Comment by rbharath** [comment]
+1. I really like this idea. The implementation of this idea should also address #51. Let's chat more about the design IRL.

**Comment by rbharath** [comment]
Added by #99
