### ISSUE TITLE
https://deepchem.io/docs doesn't go to deepchem docs

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#808]
Right now https://deepchem.io/docs gives an error instead of forwarding to https://deepchem.io/docs/index.html. I think fixing this would require adding some type of GET support for /docs to the deepchem.io S3 bucket. Not yet sure how to do this.

**Comment by lilleswing** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html
Are the docs on how to do it.

The Bucket owner has to do it.

**Comment by rbharath** [comment]
http://deepchem.io.s3-website-us-west-1.amazonaws.com/docs/ works fine but deepchem.io/docs doesn't. Perhaps a DNS issue?
