### ISSUE TITLE
YAPF == 0.17.0

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#812]
New minor version of yapf is out do we want to upgrade?
https://pypi.python.org/pypi/yapf

0.17.0
https://github.com/deepchem/deepchem/pull/805

**Comment by rbharath** [comment]
Yeah, it's probably worth an upgrade. Might be good to first sanity check that it hasn't gotten worse though :-)

**Comment by lilleswing** [comment]
The issues from https://github.com/deepchem/deepchem/pull/805 were occurring because @galenxing installed yapf==0.17.0 instead of 0.16.2.

https://github.com/deepchem/deepchem/pull/813/files

It fixed one mistake over the
``` bash
deepchem/models/tensorgraph
``
module.

**Comment by lilleswing** [comment]
I'm also down to close the issue if its not worth the effort for all the devs to update their venvs.  I just wanted to see the changes.

**Comment by peastman** [comment]
If it's at all an improvement, I'm fine with upgrading.

**Comment by rbharath** [comment]
Closing since #813 has been merged. Please update your developer environments everyone!

**Comment by peastman** [comment]
You didn't actually close it.

**Comment by rbharath** [comment]
Oops :)
