### ISSUE TITLE
Math operators for TensorGraph layers

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#818]
What do people think about supporting standard math operators on Layer objects?  Here's an example of some code I recently wrote:

```Python
log_prob = layers.Log(layers.Add([prob, layers.Constant(np.finfo(np.float32).eps)]))
objective = layers.ReduceMean(layers.ReduceSum(log_prob, axis=1))
loss = layers.Multiply([objective, layers.Constant(-1)])
```

That's a kind of wordy way of writing something that's really a simple calculation.  It would be easier if I could instead write

```Python
log_prob = layers.Log(prob+np.finfo(np.float32).eps)
loss = -layers.ReduceMean(layers.ReduceSum(log_prob, axis=1))
```

That would automatically produce the same set of layers shown above.

**Comment by rbharath** [comment]
Strongly in favor!

Now that we've decided each layer has exactly one output_tensor, operators are semantically well defined and will make complicated models much nicer.
