### ISSUE TITLE
Data preparation tutorial

### ISSUE THREAD

**Issue by kmckiern** [deepchem/deepchem#820]
Essential to building models using novel data is the process of data clean up (parsing and denoising). @rbharath and I chatted recently, and we believe it would be useful for the deepchem community to have a tutorial on this subject. 

Having gone through this procedure recently, I'd be happy to write this tutorial, highlighting why this is important as well as some best practices.

**Comment by rbharath** [comment]
@kmckiern Awesome! Looking forward to the new tutorial :)

**Comment by rbharath** [comment]
Closing since @kmckiern contributed this tutorial in #829!
