### ISSUE TITLE
3D convolution and max pooling

### ISSUE THREAD

**Issue by marta-sd** [deepchem/deepchem#821]
Hi all,
I needed a 3D convolutional layer so I implemented one. Would you be interested in a PR with such a layer? For now:

* I implemented the `Conv3D` class using `tf.layers.conv3d`. The code is based on the `Conv2D` implementation and my layer has the same API.
* I also added `MaxPool3D` using the same logic: it wraps `tf.nn.max_pool3d` and has the same structure and API as `MaxPool`.
* I added both classes to `deepchem.models.tensorgraph.layers`

I guess I should also add tests to models/tensorgraph/tests/test_layers.py and models/tensorgraph/tests/test_layers_pickle.py

Let me know if I should change or add anything in order to contribute.

Best,
Marta

**Comment by rbharath** [comment]
Yes, this would be great! The general design sounds good, and to merge we will need unit tests in test_layes and test_layers_pickle. Looking forward to seeing the PR!

**Comment by rbharath** [comment]
Thanks for the contribution! Closing since #822 has been merged.
