### ISSUE TITLE
Remove sudo from .travs.yml

### ISSUE THREAD

**Issue by rmcgibbo** [deepchem/deepchem#83]
Tip: If you remove `sudo` from .travis.yml and follow https://docs.travis-ci.com/user/workers/container-based-infrastructure/, your test suite will start much faster.

**Comment by rbharath** [comment]
@rmcgibbo Thanks for the tip. Looked into this, but it turns out that the travis containers (without sudo) don't play well with nested temporary directories (used in a number of `deepchem` tests). Going to go ahead and close this issue for now.
