### ISSUE TITLE
Multitask regressor with transformer

### ISSUE THREAD

**Issue by miaecle** [deepchem/deepchem#837]
Tensor graph based models(MPNN, ANI-1, etc.) will raise error when working on multitask regression datasets(qm8, qm9).
Currently all `predict` methods will output a list of numpy arrays correspond to the `outputs` parameter. #763 In case of multitask regression, typically we need to undo NormalTransformer in the `predict` action(also necessary for `evaluate`), which is not supported at this point. Since transformer cannot specify which output(s) to work on, my current idea is to either merge outputs that need untransforming or split transformer to a list with same length as outputs, any other idea to solve this?

**Comment by rbharath** [comment]
How about having to specify a dictionary mapping outputs to transformers? It may be meaningful to transform different outputs in different fashions, so specifying explicitly might be necessary.

In the case of just one output, we should preserve the current behavior for backwards compatability

**Comment by rbharath** [comment]
I believe we've implemented this feature already. Going to go ahead and close.
