### ISSUE TITLE
Automatic docs building messes up Mime types

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#84]
When the docs are automatically built by travis, the mime-type of _static/css/theme.css is set to text/plain when it should be set to text/css. When I run the same load command

    s3cmd -M -H sync docs/_build/ s3://deepchem.io/

on my laptop as I run on travis, the mime-type is set correctly. This is really strange the same command succeeds/fails in different environments. @rmcgibbo: Do you have any thoughts? I remember your mentioning something about mime-types for mdtraj.

**Comment by rmcgibbo** [comment]
I think there are some options to `s3cmd` about guessing the mime types.

**Comment by rmcgibbo** [comment]
You probably just have to fiddle with it. :(

**Comment by rbharath** [comment]
I think that `deepchem` is going to use manual docs-building (fiddling with this issue sucked up a lot of time, and I don't think it's worth the hassle).
