### ISSUE TITLE
Making model parameters portable?

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#842]
Currently the pkl file used to save/load models are binary and very brittle. It's a common use-case where we train models on a cluster, save the results, and transfer the parameters to a different machine (with possibly different versions of python, numpy, OSes, etc.)

The underlying protocol buffer object itself for saving the tf objects *are* portable, but the rest of the python specific objects are not. Any ideas?

**Comment by rbharath** [comment]
Pkls are definitely brittle and been bit a couple times by this myself.

At the same time, serialization is a formidable problem and one I don't think we should try to solve ourselves. Perhaps the right answer is to make TensorGraph compatible with TensorFlow serving https://www.tensorflow.org/serving/

**Comment by rbharath** [comment]
Closing this old issue since we've worked to make models use Keras model saving/loading.
