### ISSUE TITLE
Many temporary directories

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#85]
When working on the new tutorial for solubility prediction, I noticed that we need to create a lot of temporary directories to hold the features, train/valid/test splits, and models. Is there perhaps a principled way to avoid forcing the user to constantly have to specify these datasets? Perhaps set a ```base_dir``` variable in a config file somewhere.

**Comment by hainm** [comment]
can deepchem use a single dir for all training, testing, ...?

**Comment by rbharath** [comment]
@hainm In deepchem, each class is associated with a dir on disk (some of the datasets we're training on are quite large (1 TB), so writing to disk becomes necessary). We probably should have a single top-level dir to store everything though.

**Comment by hainm** [comment]
> We probably should have a single top-level dir to store everything though.

yeah, definitely.

**Comment by rbharath** [comment]
I think a fix was proposed in #118, with partial solution in #154. Going to close this, please follow discussion in newer issue.
