### ISSUE TITLE
Regulatory Element Detection

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#864]
This is a little outside our purview, but how do people feel about adding genomic deep learning models to DeepChem? There are some very cool models getting constructed with a fair amount of overlap with our specialties. For example, here's an example using dilated 1D convolutions for regulatory element detection

https://arxiv.org/abs/1710.01278

I don't think there are standard libraries for the genomic deep learning space either so there's an unmet scientific need.

**Comment by peastman** [comment]
That's a cool dataset they created.  If we want to expand beyond just chemistry, bioinformatics does seem like a natural direction.

**Comment by rbharath** [comment]
Awesome. Bioinformatics seems a great area for us in general. Our chemoinformatics support is pretty mature at this point (lots of room for improvement, but we've got a good set of features). Adding in more bioinformatics support would really meet a need in the ecosystem.

**Comment by aarvey** [comment]
For genomics/bioinformatics, would you want to follow similar translational-science capabilities as DeepChem, presumably focused on drug-discovery biology, diagnostics, or genome engineering?  It's unclear what a generalizable framework may look like, but could discuss sometime.

**Comment by rbharath** [comment]
I think a focus on translational capabilities is probably good since most of the DeepChem devs are very applied scientists. At the same time, I'm not at all opposed to basic science here (transcription factor binding site prediction? non-coding region modeling?).

General policy is vote by PR. If you have an interesting idea in this space and want to take it on, please open an issue describing your proposed change and then send in your PR!

**Comment by aarvey** [comment]
For basic science, lots of existing deep learning frameworks (e.g.,
transcription factor modeling by Kundaje Lab).

For translational work, is there interest in synthetic biology, biopsy
diagnostics (liquid & solid), and single cell RNA-seq machine learning
problems?  Existing datasets and re-usable data representations make these
fields attractive.  I have personally found that traditional small molecule
drug-development and target discovery/validation require novel, highly
tailored approach for each target; however, would be interested to hear
thoughts to the contrary.



On Wed, Oct 11, 2017 at 1:38 PM, Bharath Ramsundar <notifications@github.com

**Comment by rbharath** [comment]
Yeah absolutely, would love to see more synthetic biology, biopsies, single cell RNA-seq are other applications. Here's how I'd propose adding them in:

- Making PR that adds relevant dataset to `dc.molnet` module to enable easy loading of datasets.
- Making PR that adds new model implementation (if needed) along with an example in `examples/` and ideally an IPython notebook providing a tutorial overview.

**Comment by rbharath** [comment]
Closing this issue since we've added basic support for DragoNNs.
