### ISSUE TITLE
hERG data

### ISSUE THREAD

**Issue by patrickhop** [deepchem/deepchem#867]
Would be really nice to have some binding data added to moleculenet. I think the following hERG dataset would be a good start. For those that don't know, hERG is a commonly tested anti-target that mediates electrical activity in the heart. I'll try to add this soon, if there are no objections.

https://www.ebi.ac.uk/chembl/assay/inspect/CHEMBL3301460

**Comment by rbharath** [comment]
PR welcome!

**Comment by patrickhop** [comment]
someone bother me if i don't do this by the end of the week

**Comment by zealseeker** [comment]
I am working on collection of toxicity data and keep attention to this endpoint. 
ChEMBL is not enough I think.
These two papers may be useful.
doi: 10.1021/mp300023x
doi: 10.1039/C5TX00294J

**Comment by lilleswing** [comment]
ping @patrickhop

**Comment by lilleswing** [comment]
ping @zealseeker @patrickhop

**Comment by lilleswing** [comment]
p.s. I just collected some data for hERG by cleaning up Chembl.  I'm going to attempt to get approval to open source it.

~ 4500 points

**Comment by rbharath** [comment]
Closing this old issue in favor of https://github.com/deepchem/moleculenet/issues/2
