### ISSUE TITLE
Reach Out To The Material Science Community

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#872]
A lot of DeepChem can be applied to Material Science Problems.
We should make an effort to 
1. Add Material Science Datasets to our examples
2. Add Material Science Tutorials to our notebooks
3. Reach out to the Material Science community to see what problems we can work on.

**Comment by rbharath** [comment]
Definitely in favor of this effort. Feel free all to chime in on this thread with suggestions.

**Comment by rbharath** [comment]
Marking contributions welcome! If you're a materials scientist, we'd welcome your experimental code in contrib or new tutorials!

**Comment by rbharath** [comment]
Closing this old issue since the focus of DeepChem has shifted more towards the life sciences. Feel free to ping here if there's any interest from materials science and I'll re-open
