### ISSUE TITLE
No Easy Way To Shuffle DiskDataset Shards

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#875]
When dealing on datasets which don't fit into RAM we have to use deepchem.data.DiskDataset. 

The FeedDict Generator when deterministic=False shuffles entries within a shard.

However shards themselves are very dependent on the initial ids when creating the DiskDataset.
DiskDataset.select does a sort on ids making the shards in order by ids.

We should add a feature which shuffles DiskDataset.

**Comment by peastman** [comment]
If you call `iterbatches()` with `deterministic=False`, it first shuffles the shards, then shuffles the samples within each shard.

**Comment by lilleswing** [comment]
@peastman yeah what I'm saying is I don't think that is sufficient for any dataset which is originally delivered in sorted order.

An example would be the Roitberg DFT calculations.
You naturally load them sequentially from hd5 files.  This means that conformers have indexes next to each other.  Even if we are shuffling within a shard and shard order we still pass all examples of a single conformer exist in a single or two shards.

**Comment by peastman** [comment]
True, it's still not completely random.  To do that without loading all shards into memory at once would be a lot more complicated.

**Comment by rbharath** [comment]
I'm definitely on-board with the idea but second @peastman's comment that this gets complicated :). I've tried doing this a few times. There used to be a pairwise shard swapper that would load two shards into memory and do a complete shuffle and repeat. This was very slow so I think it was removed at some point.

Are there any standard industrial strength out-of-memory shuffling methods or is it all custom?

**Comment by peastman** [comment]
I'd probably do it in two passes.  The first pass would create a new set of shuffled shards on disk.  It would open all of them for writing, then load shards one at a time, loop over samples, and randomly pick an output file to append each one to.  The second pass would iterate samples in order from the shuffled shards.

**Comment by pvskand** [comment]
@lilleswing Is there an example for loading data via `deepchem.data.DiskDataset`?

**Comment by rbharath** [comment]
@pvskand I don't think there's a good tutorial yet, but you should be able to spot some examples of loading via `DiskDataset` in `dc.molnet`. I've also opened https://github.com/deepchem/deepchem/issues/1110 requesting the construction of a full Dataset tutorial.

**Comment by rbharath** [comment]
We have added a `shuffle` functionality to `DiskDataset`. Closing this old issue
