### ISSUE TITLE
Changes in rdkit_grid_featurizer

### ISSUE THREAD

**Issue by marta-sd** [deepchem/deepchem#876]
Hi all!

As you might have noticed, I'm working with the `rdkit_grid_featurizer` module. I've already created a few tests and fixed some minor issues (#868 and #873). Now, I want to test the `RdkitGridFeaturizer` class, so I'm trying to figure out what are the possible use-cases.

I found an example in `protein_ligand_complex_notebook.ipynb`, but I'm a little confused. Why is `voxel_width=16.0` used? Do I understand correclty, that it means that a single voxel is used to represent the whole box? Is it a way to sum up all features over coordinates and represent the whole protein-ligand complex with a 1D array?

Apart from providing the tests for this module, I also plan to add docstrings and do a little cleanup (TL;DR: I want to improve readability and fix some inconsistencies). But before I start coding I want to make sure that my assumptions are correct and discuss the changes I propose:

1. I think that the `get_formal_charge` function defined in this module has a misleading name - it actually returns **partial** charge. I propose to change its name to `get_partial_charge`. If you want to change the name, but also provide backward compatibility, we can do it as follows:
```python
def get_partial_charge(atom):
  try:
    value = atom.GetProp(str("_GasteigerCharge"))
    if value == '-nan':
      return 0
    return float(value)
  except KeyError:
    return 0

def get_formal_charge(atom):
  warn('get_formal_charge function is deprecated, use get_partial_charge instead',
       DeprecationWarning)
  return get_partial_charge(atom)
```

2. After reading the code of the `RdkitGridFeaturizer` class I can't figure out what is the relationship between `feature_types` and `voxel_feature_types` arguments. Could you please explain this?

3. Also, I'm not sure whether `feature_types` should be a string or a list. The default value is a string, some parts of the code suggest that we expect a list, but also that we ignore other elements of this list, e.g: https://github.com/deepchem/deepchem/blob/a0a586fde9f949cc25ea837907a287a2369c932f/deepchem/feat/rdkit_grid_featurizer.py#L799-L802

4. Another thing that bothers me is how the `flatten` argument is used: https://github.com/deepchem/deepchem/blob/a0a586fde9f949cc25ea837907a287a2369c932f/deepchem/feat/rdkit_grid_featurizer.py#L1087-L1088
Shouldn't we use `feature_tensor.flatten()` here to create flat arrays? `np.squeeze` works for the use-case I found in the examples, but in general it only removes the dimensions of length 1.

5. I would also like to re-write the `_transform` method to make it easier to read and maintain. I will keep its functionality (with respect to the changes I propose in this issue), but change the code structure completely.
The main idea is to create a dictionary, which will map from keyword provided by the user in the `feature_types` or the `voxel_feature_types` argument (e.g. ``"ecfp"``) to the function calculating the feature (`compute_ecfp_features` in this case). This will allow to calculate features in a loop, and simplify the code drastically.
I'm afraid it's quite difficult to discuss this idea in details without actually writing the code. So let me know if you don't want me to change the code structure and if it's not a problem, I'll just implement it and then we'll discuss the details.

6. Using a list as a default argument in a function is a bad idea (see [link](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html)). I propose to use `None` as a default value and create an empty list:
```python
class RdkitGridFeaturizer(ComplexFeaturizer):
  def __init__(self, ..., voxel_feature_types=None):
    if voxel_feature_types is None:
        self.voxel_feature_types = []
    ...
```
...or use an empty tuple, if this argument doesn't need to be mutable:
```python
class RdkitGridFeaturizer(ComplexFeaturizer):
  def __init__(self, ..., voxel_feature_types=()):
    self.voxel_feature_types = voxel_feature_types
    ...
```

7. I think there are some unused arguments in this class: `save_intermediates`, `voxelize_features`, and `parallel`. Also, `box_x`, `box_y`, and `box_z` are only used in the `_generate_box` method, which is a private method not used anywhere. Additionally, I think this method won't work, because it doesn't use the RDKit Mol class to represent the molecule.
Are those arguments deprecated? Or are they more like TODOs? If they are deprecated, I'm willing to remove them and throw a DeprecationWarning if the User tries to use them (it can be done really easily with `kwargs`). Also I propose to remove `_generate_box` method (or replace its body with DeprecationWarning).

8. There are several parameters in `RdkitGridFeaturizer` that are hard-coded. I think it is a good idea to allow the User to provide custom bins and cutoffs with `kwargs`, e.g.:
```python
if 'hbond_dist_bins' in kwargs:
    self.hbond_dist_bins = kwargs['hbond_dist_bins']
else:
    self.hbond_dist_bins = [(2.2, 2.5), (2.5, 3.2), (3.2, 4.0)]
...
```

Let me know what you think about these changes. Also, if you want me add or change anything else, I'm open to your suggestions! :)

Best,
Marta

**Comment by rbharath** [comment]
@marta-sd Glad to see you're taking on this refactor! Some comments

1. Proposed change sounds good.
2. This is a little unclear to me as well. We might want to combine both of these into just one flag `feature_types`, and remove `voxel_feature_types`.
3. I think we probably want `feature_types` as a list.
4. +1 for moving to `.flatten()`
5. I like this proposed refactor. Better than our explicit listing we have currently.
6. +1 for using `None` as the default argument.
7. Feel free to remove unused arguments.
8. +1 for allowing users to provide values as suggested.

CC @evanfeinberg, @lilleswing who might have more comments on this code.

**Comment by marta-sd** [comment]
@rbharath Thanks for your comments :) I think it's a great idea to combine `feature_types` and `voxel_feature_types` into a single flag. I propose the following design:
* `voxel_feature_types` is deprecated and ignored, the User is warned
* `feature_types` is a list
* if the User specifies multiple features, created vectors/tensors are concatenated
* if `feature_types` contains both flat and voxel features, the tensors are flatten
* there are 3 predefined sets of features: 'flat_combined', 'voxel_combined', and 'all_combined'

**Comment by mwojcikowski** [comment]
I believe it is also important to state in `DeprecationWarning` at what point (version) the function would be eventually moved. Usually it's 1-2 major releases in case of scikit-learn.

Keep up the good work ;)

**Comment by rbharath** [comment]
@marta-sd Sounds like a good plan! Seconding @mwojcikowski's comment about `DeprecationWarning`. I think this module is used sparsely enough that a warning of changes from DeepChem 1.4 onward should be enough.

I'd also recommend running a full featurization test at the end to make sure that the new featurization retains performance as reported on moleculenet.ai.

**Comment by lilleswing** [comment]
voxel_feature_types were meant to be a subset of feature types which only effect voxels.

feature_types was intended to be a list

**Comment by evanfeinberg** [comment]
Thank you for all of your efforts @marta-sd ! Agreed with the comments from @rbharath and @lilleswing . 

Another area where you can make a significant contribution is in computing aromatic interactions. This feature worked properly in the older, ```openbabel```-based version of the code but led to issues when we switched over to ```rdkit```, leading us to disable the feature in the interim. Re-integrating this feature would likely lead to a statistically significant boost in signal.

**Comment by marta-sd** [comment]
@mwojcikowski @rbharath You're right, I'll add the version number to the warnings.

@lilleswing Thank's for clarifying. What do you think about removing the `voxel_feature_types` argument? I still think it's a good idea, although I realized it would require defining some new keywords to distinguish between flat and voxel features (e.g. `splif_hashed` and `splif` for flat and voxel splif features, respectively).

@evanfeinberg I'll give it a try. Is this: https://github.com/deepchem/deepchem/blob/0906d8b0ecfd87faceafe0f10d7622a5f1421e89/deepchem/feat/grid_featurizer.py#L584
 the last fully-functional version of the code?

**Comment by evanfeinberg** [comment]
Great find, @Marta, that should be the last version. Echoing your excellent
suggestion from earlier, it may be worth adding keyword arguments for
certain cutoffs that were hard-coded in that version (e.g., 5.5 Angstroms
from cation-π interactions).

**Comment by marta-sd** [comment]
#879 has been merged, so I'm closing this issue. Thank you all for your help! :)
