### ISSUE TITLE
Travis CI Timing Out

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#877]
Our builds are currently timing out due to our docs build (H/T @lilleswing). We should fix this soon, possibly by moving all docs building over to Jenkins. I believe @lilleswing is taking point on this, but wanted to open the issue to let people know we are working on it :)

**Comment by mwojcikowski** [comment]
Why not https://readthedocs.org/? I use it for my other projects and they work fine. They offer both building with conda support and hosting.

**Comment by rbharath** [comment]
I like the idea of using Jenkins since we can perform complex builds, such as running IPython notebooks (for tutorials) that may need a GPU.

**Comment by rbharath** [comment]
Checking some of the build failures more closely. I think this might be caused by the new `UserWarning`s in `rdkit_grid_featurizer`. 

https://travis-ci.org/deepchem/deepchem/jobs/287174284

We might want to turn off some warnings or silence by default.

**Comment by marta-sd** [comment]
@rbharath There are definitely too many warning, but I had this problem before adding them. Anyway, I think it wasn't a good idea to add them.
