### ISSUE TITLE
Use tf.data?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#882]
TensorFlow has a new dataset API tf.data:

https://docs.google.com/presentation/d/16kHNtQslt-yuJ3w8GIx-eEH6t_AvFeQOchqGRFpAD7U/edit#slide=id.p

We might want to look into using this for our larger datasets.

**Comment by lilleswing** [comment]
It looks nice -- but it is only in the beta release right now (1.4.0).

**Comment by rbharath** [comment]
Closing in favor of #1039. Let's take discussions there.
