### ISSUE TITLE
Any One-Shot Learning documentation / scripts?

### ISSUE THREAD

**Issue by UnixJunkie** [deepchem/deepchem#884]
Hello,
I am looking for some documentation or scripts that would allow
to apply the protocol from "Low Data Drug Discovery with One-Shot Learning"?
Thanks,
F.

**Comment by rbharath** [comment]
Scripts are available in https://github.com/deepchem/deepchem/tree/master/examples/low_data. Note that this code is deprecated though; we're working on translating the one-shot models to the new `TensorGraph` API

**Comment by UnixJunkie** [comment]
Thanks for the info.
