### ISSUE TITLE
Planning for DeepChem 2.0

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#891]
What are some features people would like to see in DeepChem 1.4?

I'll kick off the list with a couple needed changes:

- Remove all deprecated non-TensorGraph TensorFlow models/code to contrib/
- Complete the transfer of the one-shot models into TensorGraph.

Suggestions welcome...

**Comment by peastman** [comment]
Some things I'm working on right now:

- MCTS algorithm for RL
- SeqGAN

**Comment by patrickhop** [comment]
My suggestions:
(1) Cleaning up the github homepage
(2) Binding data. (I'll do this eventually)
(3) Add ECFP4+descriptors baselines. These are more competitive than we think.

**Comment by lilleswing** [comment]
Backwards incompatible changes are most likely going to require the next cut to be 2.0.
https://github.com/deepchem/deepchem/issues/900

**Comment by lilleswing** [comment]
Things I'm working on now for the cut:

1. OSX official Support w/ CI
2. Rewriting Metrics
3. More visibility into our performance and "slow" testing with feedback on github.

**Comment by rbharath** [comment]
I think we're just about ready to make the 2.0 cut. Going to go ahead and close this issue since anything not already in head isn't going to make it in :)
