### ISSUE TITLE
Mol2Vec

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#894]
A word2vec variants for molecules. Might be good to get an implementation into DeepChem

https://chemrxiv.org/articles/Mol2vec_Unsupervised_Machine_Learning_Approach_with_Chemical_Intuition/5513581

**Comment by LRParser** [comment]
I've been working on it. Also similar is ChemTS.

**Comment by rbharath** [comment]
Thanks to @LRParser for hitting this!

Going to go ahead and close the issue.
