### ISSUE TITLE
Feature request: Add SMILES labels to featurizer output with dense option 

### ISSUE THREAD

**Issue by rhodos** [deepchem/deepchem#898]
I'm trying to extract features from SMILES strings and at the same time, extract labels for each feature (i.e. the SMILES string for each substructure). Currently, it is only possible to get these labels using the sparse version of a featurizer, e.g. `dc.feat.CircularFingerprint(radius=radius, size=feature_size, features=False, sparse=True, smiles=True)`. Would be very useful if this could also work with `sparse=False`.

**Comment by lilleswing** [comment]
The only purpose of the "sparse" flag is to return the information you are asking for.

"sparse"=False encodes the feature into a bit-vector which can then immediately get passed into Tensorflow.

**Comment by rhodos** [comment]
But is there an easy way to convert back into dense format? While keeping the feature metadata?

**Comment by lilleswing** [comment]
You could just featurize twice -- once with the flag and once without.  X elements would align by ID and then you would have both versions.

Also in theory you could just mod all the feature values by the bit string length to compute your own feature vector.

**Comment by rhodos** [comment]
"X elements would align by ID".. what IDs are you talking about?

**Comment by lilleswing** [comment]
```python
import deepchem as dc
import json


def to_numpy_dataset(dataset):
  return dc.data.NumpyDataset(dataset.X, dataset.y, dataset.w, dataset.ids)

dataset_file ="./example_compounds.csv"
tasks = ['dummy_task']

shard_size = 2
feature_size = 1024
radius = 4

#ECFP4
featurizer = dc.feat.CircularFingerprint(radius=radius, size=feature_size, features=False, sparse=True, smiles=True)
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles", featurizer=featurizer)
sparse = to_numpy_dataset(loader.featurize(dataset_file, shard_size=shard_size))

# Dense
featurizer = dc.feat.CircularFingerprint(radius=radius, size=feature_size, features=False, sparse=False, smiles=True)
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles", featurizer=featurizer)
dense = to_numpy_dataset(loader.featurize(dataset_file, shard_size=shard_size))

dense.X[0] # This is the bitvector representation needed for tensorflow models.
sparse.X[0] # This is the drill down information you are interested in
```

**Comment by rhodos** [comment]
@lilleswing Of course, but how do I know which bit maps to which "substructure" SMILES id? The sparse information is a dictionary, meaning that there is no ordering, so I can't just reverse engineer right? Seems that I will have to take the sparse information and construct my own dense matrix, but first going through and identifying all of the unique features, and then mapping them to a binary matrix.

**Comment by lilleswing** [comment]
```python
d1 = dense.X[0]
s1 = sparse.X[0]

fp_length = d1.shape[0]
reconstruct = np.zeros(shape=(fp_length,))
for key in s1.keys():
  reconstruct[key%fp_length] = 1

print(np.all(reconstruct == d1))
```

The keys are the features -- you just mod them to create the dense bit-vector.

**Comment by rhodos** [comment]
Ahhhh okay I see, thanks!
