### ISSUE TITLE
Deprecate metadata.joblib files in DiskDataset

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#900]
metadata.joblib files are pinned to a specific (python, pandas) version tuple.  This means that the Dataset is no longer readable if we upgrade either of these dependencies.

https://github.com/deepchem/deepchem/pull/899

Lazily moves the metadata to a hd5 file and json file instead.  How should we inform people that they should read their Datasets once in order to get future compatible Datasets?

**Comment by lilleswing** [comment]
This issue is blocking an upgrade of rdkit.

**Comment by peastman** [comment]
We also should convert all the datasets included with deepchem or hosted online.

**Comment by rbharath** [comment]
Big fan of this change! Will cut out one of the main instabilities with deepchem.

**Comment by lilleswing** [comment]
Once it is green and more tested I think this is a large enough change to release as a 1.3.1 cut.  It will git people who are working on latest a smooth transition.

**Comment by rbharath** [comment]
Going to close since we've made the cut.
