### ISSUE TITLE
Moving TensorGraph layers to deepchem.nn

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#902]
#891 notes that we will likely have to make backwards compatibility breaking changes for the next DeepChem release, so it strikes me as a good time to do some namespace cleanup. Following conventions from other NN libraries, I propose we move the TensorGraph layers to `deepchem.nn`. A number of the old-style layers live there already which will be removed soon. This way, users will be able to use our layers easily in custom code:

```
import deepchem as dc
out_tensor = dc.nn.GraphConv(...)(in_tensor)
```

**Comment by peastman** [comment]
I'd suggest keeping the `layers` module in the path.  I have a lot of code that begins with `import deepchem.models.tensorgraph.layers as layers`, and then refers to `layers.Dense()`, etc.  That way all I'd have to do is change the import to `deepchem.nn.layers`.  That's also similar to Keras, where it's common to write `import keras.layers as layers`.

**Comment by peastman** [comment]
Looking into making this change, I see we already have a `layers.py` file in `deepchem.nn`.  What do we want to do about that?

**Comment by rbharath** [comment]
I believe all those layers should be removed. (I think they were deprecated in the last release)

**Comment by 1particle** [comment]
Looking into the examples and documentation today, I noticed that classes such as nn.GraphConv are absent from the documentation, but  tensorgraph.layers.GraphConv is documented. My first impression was that the nn module is stale and TensorGraph is new, but then seeing this thread gave me the opposite impression. Can someone please elaborate?

**Comment by rbharath** [comment]
@1particle Good catch. I've opened https://github.com/deepchem/deepchem/pull/1090 to move `deepchem.nn` over to contrib. As you suspect, there's only stale code in there now.

I'm also less enthusiastic about moving `deepchem.models.tensorgraph.layers` to `deechem.nn.layers`. I think this is a relatively low yield change that will cause a lot of code breakage. I'm inclined to not bother at this point.

**Comment by rbharath** [comment]
I'm going to close this PR since I think it's not a priority development goal for now. May re-open at a future date as needed.
