### ISSUE TITLE
Saving tensorflow models

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#906]
Hi.

I have troubles with dumping (and later restoring) trained model. Can you please provide some example, how to save model in delaney/graph_conv example?

inspect.getsource(model.save) returns
`def save(self):\n    """\n    No-op since this model doesn\'t currently support saving...\n    """\n    pass\n'`

When i try to use pickle/marshal/joblib serializers, i get TypeError: can't pickle module objects,
with dill serializer i get:
`sys.setrecursionlimit(50000)

dill.dumps(dcm)

TypeError: can't pickle SwigPyObject objects
`

Using tensorflow saver leads to:
`ValueError: Fetch argument <tf.Operation 'init_3' type=NoOp> cannot be interpreted as a Tensor. 

(Operation name: "init_3"

op: "NoOp"

input: "^Variable_3/Assign"

input: "^dcm_1/Assign"

 is not an element of this graph.)
`
But i'm not sure if i use tensorflow saver correctly.

Thanks

**Comment by lilleswing** [comment]
The delaney_graph_conv is deprecated.  Consider looking at tox21/tox21_tensorgraph_graph_conv example (It is the same model, refactored to enable saving, just over a different dataset).  

PR's welcome to move delaney_graph_conv over to the new TensorGraph style.

**Comment by allchemist** [comment]
Thanks for your answer.

I created the model with GraphConvTensorGraph, as in tox21 example, and it successfully dumped with 'save'.

Now i'm trying to restore it back, and get
`NotImplementedError: Each model is responsible for its own reload method.`

Also, can i find somewhere a list of non-deprecated examples, at least one example for each model, implemented in deepchem?

Thanks

**Comment by lilleswing** [comment]
yeah that is on our TODO list for DeepChem 1.4.  sorry we don't have that list yet :(
