### ISSUE TITLE
Cannot find predict_on_smiles_batch in graph_models in deepchem 1.3

### ISSUE THREAD

**Issue by zealseeker** [deepchem/deepchem#913]
https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/models/graph_models.py#L900
The function `predict_on_smiles` in line 883 requires another function `predict_on_smiles_batch` which does not exist not.

In deepchem 1.2 it works since both `predict_on_smiles` and `predict_on_smiles_batch` were included. But now some patches changed the code, which results in the error when using `predict_on_smiles`.

Directly predict molecule in SMILES format is important and convenient. So It will be appreciate if this function can be conserved and shared in other models.

**Comment by rbharath** [comment]
Good catch. predict_on_smiles should have been removed entirely from TensorGraph since the class is general and can't be assumed to just take in smiles strings.

It would be fine to add predict_on_smiles to subclasses that do operate only on smiles.

**Comment by zealseeker** [comment]
Do deepchem have such a subclass that can help handle SMILES.
If not, I think it is necessary to provide an API that can transfer array of smiles into a featurized dataset.

**Comment by rbharath** [comment]
It's straightforward to featurize an array of smiles using `dc.feat`. That said, if there's a natural API that makes sense, it might make sense to add as a convenience feature.

**Comment by anhvu-hcmiu** [comment]
Hi rbharath, could you please show me an example of how to use dc.feat to featurize an array of smiles? I am playing with the HIV dataset but have no idea how to use the model to predict unseen chemical compounds, which are not labelled in terms of HIV activity. I tried using model.predict(np.array('Clc1ccc2NC(=O)n3ncnc3c2c1')) but it did not work. Thank you in advance.

**Comment by rbharath** [comment]
Here's a short example of how to featurize smiles with `dc.feat`

```
import deepchem as dc
from rdkit import Chem

smiles ='C1CCC1'
mol = Chem.MolFromSmiles(smiles)
featurizer = dc.feat.CircularFingerprint(size=1024)
features = featurizer.featurize([mol])
```

**Comment by anhvu-hcmiu** [comment]
Thank you so much @rbharath , the example was really helpful.

**Comment by zealseeker** [comment]
This gist gives an example about how to featurize and predict compounds represented as SMIELS, though it's not good enough and was used for another issue #951 .
https://gist.github.com/zealseeker/ffac72705adaa4501948bdc7d834774e

I think this issue can be closed.
