### ISSUE TITLE
TensorFlow Eager Integration

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#915]
https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html

This might settle our perennial PyTorch vs. TensorFlow discussions in favor of TensorFlow :-). For now, eager is only in the nightly release, but I suspect that eager models will gain wide adoption once it matures a bit.

**Comment by rbharath** [comment]
Turns out that eager execution will be included in TensorFlow 1.6. We should start experimenting once it's out. I think will really help us with more sophisticated models such as the Junction Tree Variational Autoencoders (#1097)

**Comment by rbharath** [comment]
Marking contributions welcome. We'd happily welcome PRs to contrib if you have any tf.eager code you've played with! This should be easy to do for beginners (although you will need to install the 1.6 release candidate of TensorFlow)

**Comment by peastman** [comment]
Individual TensorGraph layers already work nicely with eager execution, as shown in #1158.  We should also consider adding eager execution support for TensorGraph as a whole.  I'm thinking of another version of `predict()` that takes a list of input tensors and returns a list of output tensors.  Possibly all we need to do is make `predict_on_batch()` accept either a tensor or a numpy array for `X`.

**Comment by rbharath** [comment]
@peastman We might consider making a `TensorGraph` callable. That is, `TensorGraph.__call__(tensor)` is syntactic sugar for `TensorGraph.predict(tensor)`. This would behave similarly to how `Layers` are callable now and could enable nice tutorial demonstrations of how to make predictions with models in Eager mode.

**Comment by rbharath** [comment]
Closing since implemented in #1191
