### ISSUE TITLE
Build failure blocking DeepChem 1.3.1

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#922]
It looks like everything needed for the DeepChem 1.3.1 cut is in, but we should get the build passing again before we make the cut. Looks like we're timing out on Python 2.7 for some reason. Let's figure this out soon so we can make the release.

CC @lilleswing @peastman

**Comment by hsiaoyi0504** [comment]
It fails to finish fitting conditional WGAN.

https://travis-ci.org/deepchem/deepchem/jobs/296425824#L5473

**Comment by hsiaoyi0504** [comment]
Detailed message: https://travis-ci.org/deepchem/deepchem/jobs/296425824#L5792-L5797
```
FAIL: Test fitting a conditional WGAN.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/deepchem/deepchem/deepchem/models/tensorgraph/tests/test_gan.py", line 99, in test_wgan
    assert abs(np.mean(deltas)) < 1.0
AssertionError
```

**Comment by rbharath** [comment]
@hsiaoyi0504 Good suggestion! Seems to have solved the problem. DeepChem 1.3.1 is now cut.
