### ISSUE TITLE
ValueError: No Metadata Found On Disk for example

### ISSUE THREAD

**Issue by pgreisen** [deepchem/deepchem#938]
Hi all - I am trying to test protein_ligand_complex_notebook.ipynb on a Mac OS but getting this issue when I go through the different cells: 
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

which gives me the following error:

Loading dataset from disk.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-35c550224653> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

...

/Users/test/anaconda2/lib/python2.7/site-packages/deepchem/data/datasets.pyc in load_metadata(self)
    500       save_metadata(tasks, metadata_df, self.data_dir)
    501       return tasks, metadata_df
--> 502     raise ValueError("No Metadata Found On Disk")
    503 
    504   @staticmethod

ValueError: No Metadata Found On Disk

How to fix this - thanks!

**Comment by lilleswing** [comment]
It worked before only in python 2.7 because the datasets were made before dc 1.3.1.  I updated the Datasets on the internet to be of the new style so it can also work on python 3.5.

https://github.com/deepchem/deepchem/pull/940

**Comment by rbharath** [comment]
#940 should have fixed this so closing.
