### ISSUE TITLE
It occupies all GPU memory

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#944]
Hi.

When i run graph_conv and irv models with gpu, it eats all memory available. At one machine i have 8gb and it occupies 8 gb. But at another machine i have only 1gb, and it takes 1gb and wotks fine. The whole dataset is much less than 1gb, so i suppose that it just takes all memory that it can take.

Other models, like robust_mtnn, does not eat all memory at same task.

I cannot run several processes at a time, so can i somehow disable that behaviour?

Thanks

**Comment by rbharath** [comment]
Hmm, interesting. I believe the `allow_growth` option (https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorflow_models/__init__.py#L492) means that not all memory is allocated up front, so it looks like graph_conv/irv are naturally memory intensive.

Has anyone else run into this before?

**Comment by allchemist** [comment]
One detail: at the beginning (tensorflow initialization) it says smth like:
`Total memory: 972MiB
Free memory: 906MiB`
and at another machine:
`Total memory: 7920MiB
Free memory: 7800MiB`
so it really takes all avail memory up front

**Comment by lilleswing** [comment]
You can manually set the configproto in the constructor for TensorGraph.
e.x.

```python 
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
model = GraphConvTensorGraph(
    len(tox21_tasks), batch_size=batch_size, mode='classification', configproto=config)
```

**Comment by rbharath** [comment]
Going to close this issue. Feel free to re-open if it's still a problem.

**Comment by allchemist** [comment]
Hi. Yes, there is still a problem with IRV method. TensorflowMultiTaskIRVClassifier does not inherit 'configproto' option. I tried manual substitution of tf session, but it does not work.

**Comment by lilleswing** [comment]
The new TensorflowMultiTaskIRVClassifier now accepts the configproto keyword.
