### ISSUE TITLE
Shape of SoftMaxCrossEntropy

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#946]
I'm working on some cleanup, and I'm running into lots of problems trying to get the shapes of different TensorGraph layers to match up correctly.  I've tracked part of the problem down to a few layers whose shapes just don't make any sense to me.

`SoftMaxCrossEntropy` and `SparseSoftMaxCrossEntropy` each reshape their output as

```python
out_tensor = tf.reshape(self.out_tensor, [-1, 1])
```

So for example, if you have a batch of 100 samples and 25 values per sample, it reshapes all of them into a [2500, 1] output tensor.  Why?  The very next thing I want to do with it is put it into a `WeightedError` layer, which needs to combine it with a [100, 25] weight tensor.

**Comment by peastman** [comment]
`L2Loss` has a different but related problem: it does a `reduce_mean()` over all but the first dimension, leaving a single number per sample.  That makes it impossible to apply weights.

**Comment by proteneer** [comment]
I ran into this recently. The -1 is for the batch, a WeightedError is applied afterwards which actually does the real reduce.

**Comment by proteneer** [comment]
(ie. the L2 doesn't actually compute an L2 at all)

**Comment by rbharath** [comment]
Good find. +1 for cleaning up these shapes to make sense.
