### ISSUE TITLE
Different predictions (which are wrong) after saving and restoring the TensorGraph model

### ISSUE THREAD

**Issue by zealseeker** [deepchem/deepchem#951]
Though the tensorgraph model can be saved, the predictions are different and totally wrong (with very bad performance) after saving and restoring the model.

Here is the gist that can reproduce the problem.
https://gist.github.com/zealseeker/ffac72705adaa4501948bdc7d834774e

I wonder whether I did something wrong during saving and restoring the TF model?

Here is a thumbnail of my code
```python
model, transformers = build()
mols = []
for smi in NRs:
    mols.append(Chem.MolFromSmiles(smi))
featurizer_func = dc.feat.ConvMolFeaturizer()
X = featurizer_func.featurize(mols)
print(model.predict_on_batch(X,transformers).astype('float'))


# Save and restore
print('Saving and restoring')
model_dir = 'model'
if not os.path.exists(model_dir):
    os.makedirs(model_dir)
model.model_dir = model_dir
model.save()
model = None

model = GraphConvTensorGraph.load_from_dir('model')
print(model.predict_on_batch(X,transformers).astype('float'))
```

Both `GraphConvTensorGraph.load_from_dir` and `TensorGraph.load_from_dir('model')` were tried and it didn't matter

**Comment by peastman** [comment]
You need to set `model_dir` before fitting, or else call `save_checkpoint()` after you set it.

There are two different aspects of the model that can be written to disk:

1. The structure of the model (the layers that make it up, loss function, etc.).  This is saved to disk by calling `save()` and restored by calling `load_from_dir()`.

2. The values of all trainable parameters.  Checkpoints recording the most recent values are periodically written during training, and you can also call `save_checkpoint()` to write another copy of them at any time.  You can load the most recent checkpoint by calling `restore()`, and it's also loaded automatically by `load_from_dir()`.

So here's what's happening in your case.  Initially the model has one data directory (probably in your temp directory), and that's where checkpoints get written during training.  Then you change the directory and have it write out the model structure but *not* the trainable parameters to that new directory.  So when you call `load_from_dir()`, there's no checkpoint in that directory to load.

**Comment by zealseeker** [comment]
Hi @peastman ,
Thanks for your quick replay. I tried your suggestion but also failed with some error.
As I edited the code (see the gist in my post), the `model.model_dir` was set before fitting. If I only use `model.save()`，nothing changes and I found that there was only a `model.pickle` in the directory of `model`.
When I tried using `model.save_checkpoint()`, error occurred that I cannot solve.
```
Traceback (most recent call last):
  File "tox21_predict.py", line 79, in <module>
    model.save_checkpoint()
  File "/home/lmmd_wz/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 755, in save_checkpoint
    saver = tf.train.Saver(max_to_keep=max_checkpoints_to_keep)
  File "/home/lmmd_wz/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/lmmd_wz/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1162, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Comment by lilleswing** [comment]
TensorGraph.model_dir currently has to be set in the constructor.  We create a class variable "save_file" based on model_dir which tells the object where to save the tensorflow checkpoints (which contain the model weights).

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py#L90

If we want to change the model_dir after construction of the class we would have to create a method on TensorGraph which also updates self.save_file.

**Comment by lilleswing** [comment]
@zealseeker is there a strong use case for having to set the variable after calling the constructor?

**Comment by zealseeker** [comment]
Hi @lilleswing , Thanks and your suggestion is useful. I set the `model_dir` when I created the instance and it worked. 

However, `model.save_checkpoint` would still generate the error of `ValueError: No variables to save`. So I do not use this function.

**Comment by peastman** [comment]
> However, model.save_checkpoint would still generate the error of ValueError: No variables to save.

Is that before or after training the model?  If you haven't yet trained it, the model internals likely haven't been build, so there are no variables to save.  You could call `model.build()` first, but in that case all you're saving is whatever random values they get initialized to.  Once you call `model.fit()` the variables should all exist and have values worth saving.

**Comment by zealseeker** [comment]
Hi @peastman, have you tried my code in the gist?
I did train my model by `model.fit()`. But when I used `model.save_checkpoint()`, the error happened.
(Using model.save() was ok.)

**Comment by zealseeker** [comment]
I think this can be closed since the function of save is good enough.
