### ISSUE TITLE
Use custom mdtraj which dyanmically dlopens

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#960]
After upgrading tensorflow to 1.4 we run out of things that we can open with static TLS.
https://travis-ci.org/deepchem/deepchem/jobs/312146212

Can we build a version of mdtraj which dynamically loads the dll's instead of the fast static loading?

Without this we cannot upgrade to tensorflow 1.4.

**Comment by peastman** [comment]
I'm not certain about this, but some of the pages I've found on similar problems suggest that if we just specify `-fPIC` when compiling MDTraj that might fix the problem.

**Comment by lilleswing** [comment]
@peastman no such luck.

I raised an issue on the mdtraj page
https://github.com/mdtraj/mdtraj/issues/1324

Reading through mdtraj source I couldn't find out what the flags -fPIC did -- so many a flag exists and we just got the wrong one.

**Comment by lilleswing** [comment]
So it looks like on older linux kernels we can't run both mdtraj and tensorflow at the same time.  (Same with xgboost).  

I think the only option is to move the tests over to jenkins which runs on a newer linux kernel.

**Comment by rbharath** [comment]
@lilleswing Blech, this is an icky build mess. Thanks for looking into this.

I agree that moving xgboost/mdtraj overs to Jenkins is probably the right step. A side benefit is that it will lower our Travis CI times which will make dev work more convenient.

**Comment by lilleswing** [comment]
So after the latest comment I was able to build a custom mdtraj and host on our anaconda cloud account.  

So now its just xgboost that we have to move to jenkins
