### ISSUE TITLE
DeepChem 2.0 Deprecated Code Plan

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#963]
### TensorflowMultiTaskRegressor
- [x] We should be able to write a class which has the same functionality built on top of TensorGraph
- [ ]  Current datasets are missing which use this class -- UV, KINASE, Factors Where are they @rbharath ?  Should we remove them from examples?
- [x]  BACE Notebook must be updated

### TensorflowMultiTaskClassifier
- [x]  BACE Notebook must be updated
- [x]  MUV Notebook must be updated

**Comment by peastman** [comment]
> We should be able to write a class which has the same functionality built on top of TensorGraph

We already have one.

We still need a replacement for TensorflowMultiTaskIRVClassifier.

**Comment by lilleswing** [comment]
@peastman so we have.  

@rbharath can you find the datasets for UV, KINASE, and FACTORS or can we move those examples to contrib?

**Comment by lilleswing** [comment]
Fix the ipython notebooks here
https://github.com/deepchem/deepchem/pull/961

**Comment by rbharath** [comment]
@lilleswing The UV, Factors, Kinase are all in S3 already. Need to just add them to MoleculeNet.

We also need to implement the one-shot models in TensorGraph for DeepChem 2.0.

**Comment by rbharath** [comment]
I'm closing this issue since I think we're about ready to cut 2.0 and have finished the set of needed changes.
