### ISSUE TITLE
Dense Layer Doesn't have activation.

### ISSUE THREAD

**Issue by jackasser** [deepchem/deepchem#974]
https://github.com/deepchem/deepchem/blob/master/deepchem/nn/copy.py#L314

Dense Layer has activation propaty above.
```python
    self.activation = activations.get(activation)
```

But the propaty will be never used.

So, should we add the activate function to Dense layer??

**Comment by lilleswing** [comment]
We should mark that code as deprecated in favor of Tensorgraph Layers.

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/layers.py#L445
Under the hood we use tf.contrib.layers.fully_connected which does use the activation function.

**Comment by jackasser** [comment]
thanks!!
I try to use tf.contrib.layers.fully_connected!!

**Comment by rbharath** [comment]
#976 has removed the old deprecated layers. You can find the new `Dense` layer at `dc.models.tensorgraph.layers.Dense`
