### ISSUE TITLE
libicui18n.so.56 error

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#980]
I'm seeing some strange RDKit import errors in Python 3.5 on Travis-CI causing tests to break.

    File "/home/travis/anaconda/envs/deepchem/lib/python3.5/site-packages/rdkit/Chem/__init__.py", line 28, in <module>
        from rdkit.Chem.rdmolops import *
    ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

Has anyone seen similar errors before? CC @lilleswing @peastman

**Comment by rbharath** [comment]
#976 and #925 are currently blocked on this error.

**Comment by lilleswing** [comment]
I solved this early by installing icu=56.1 manually. 
Lets see what this CR does

https://github.com/deepchem/deepchem/pull/982

**Comment by rbharath** [comment]
I think #982 has solved this issue. Going to go ahead and close for now.
