### ISSUE TITLE
Reduce Travis-CI test time

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#984]
The Travis-CI tests now routinely take 45 minutes or so to run. This makes development unwieldy since even minor errors require long waits to fix. We should move more of the slow tests off Travis.

**Comment by peastman** [comment]
From the most recent run of the test suite, it looks like just three tests account for more than 1/3 of the total test time;

```
[success] 13.04% deepchem.dock.tests.test_docking.TestDocking.test_vina_grid_dnn_docker_dock: 243.3852s
[success] 12.69% deepchem.dock.tests.test_docking.TestDocking.test_vina_grid_rf_docker_dock: 236.8578s
[success] 12.68% deepchem.dock.tests.test_pose_generation.TestPoseGeneration.test_vina_poses: 236.6745s
```

**Comment by rbharath** [comment]
Good find. These are good candidates to move to Jenkins since that part of the codebase isn't undergoing much churn.

**Comment by rbharath** [comment]
#987 moves these tests to Jenkins. Are there any other good candidates for us to move out?
