### ISSUE TITLE
Aligning constructor arguments for TensorGraph Layers and Keras Layers

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#988]
Currently, our layer constructors differ from Keras layer constructors in a number of subtle ways. For example, consider 2d convolutions in TensorGraph:

```
Conv2D(num_outputs, kernel_size=5, stride=1, padding='SAME', activation_fn=<function relu>, normalizer_fn=None, biases_initializer=<class 'tensorflow.python.ops.init_ops.Zeros'>, weights_initializer=<function xavier_initializer>, scope_name=None, **kwargs)[source]
```

versus in Keras

```
Conv2D(filters, kernel_size, strides=(1, 1), padding='valid', data_format=None, dilation_rate=(1, 1), activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None)
```

The arguments are almost identical, but there are a number of subtle differences that make things tricky. I'm running into this a lot in #979 where I'm porting the Keras Dragonn models into DeepChem. Since Keras layers have been adopted by `tf.keras`, I think they're starting to become a standard API. Aligning the APIs to share names, arguments, and argument ordering would make it easy for people to port code over. This would be very nice feature target for DeepChem 2.0.

**Comment by rbharath** [comment]
Digging into the code more, it looks like the `tensorgraph.layers.Conv2D` arguments match those for `tf.contrib.layers.conv2d`. This is also a semantically meaningful alignment. Do people have strong preferences for matching either the raw Tensorflow API or the Keras API?

**Comment by lilleswing** [comment]
tf.contrib.layers are just that -- contrib.

tf.keras is a higher namespace

**Comment by rbharath** [comment]
Agreed. In general, I'd be in favor of starting to use `tf.keras` to back our non-custom layers to the degree possible. We shouldn't be reinventing the wheel on basic layers.

Would people be onboard with making `tf.keras` integration a 2.0 target?

**Comment by rbharath** [comment]
Closing this old discussion since `TensorGraph` is now deprecated.
