### ISSUE TITLE
Tutorial for splitters

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#990]
We don't have a good set of learning resources for people who want to use `dc.splits` since our example tutorials use `dc.molnet` which comes with pre-split datasets. We should put together a small tutorial for `dc.splitters` and the different types of splits available.

**Comment by pvskand** [comment]
I guess this issue can be closed as in the recent PR #1104 by @abster12 has covered `splitters` is a very good way.

**Comment by rbharath** [comment]
Good point. Will close.
