### ISSUE TITLE
Improve documentation on deepchem.molnet.load_pdbbind_grid() for first usage

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#995]
#994 reports a confusing error encountered when running `load_pdbbind_grid` for the first time. This documentation should be improved so first time users have a better experience. PRs welcome.

**Comment by lilleswing** [comment]
Master already loads the dataset in the background instead of throwing the exception.

I updated the docstrings because I was already looking at it.

https://github.com/deepchem/deepchem/pull/997

**Comment by rbharath** [comment]
Awesome, going to go ahead and close this issue.
