### ISSUE TITLE
nose-flaky and nose-timer don't work together

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#999]
We are failing builds which should be passing with nose-flaky.

Nose-Timer overrides nose-flaky causing builds to fail when the flaky tests fail only once.  If we can only have one of these two plugins which do we want more?

**Comment by rbharath** [comment]
Nose-timer is pretty useful for catching slow tests. Maybe we should move the flaky tests to Jenkins and keep timer?

**Comment by peastman** [comment]
Perhaps we can figure out how to make some of the flaky tests less flaky?  But even so, it's inevitable that some of our tests will be stochastic.  That's inherent in how lots of the algorithms work.  It's a question of whether we can make the failures infrequent enough to be acceptable.

**Comment by lilleswing** [comment]
I'm going to start keeping track of which ones are failing.  We can add manual restart code after failure for the worst candidates.

**Comment by lilleswing** [comment]
https://docs.google.com/spreadsheets/d/1rLARKLz7O6xYqN_tsdlz1YI_nA21szH1_bzW9JdRK50/edit#gid=0

**Comment by rbharath** [comment]
Closing out this old issue. We still have issues with failing builds, but I'm not sure if that's related to this discussion. Will reopen if pertinent.
